### ISSUE TITLE
[BUG] - Slows down BetterDiscord and crashes alot

### ISSUE THREAD

**Issue by richmailYT** [mwittrien/BetterDiscordAddons#1002]
**Describe the bug**
slows BetterDiscord and Crashes it alot

**To Reproduce**
uhh...download themes repo and go into themes, try to search for Clear and it'll crash.
also, it slows discord, download ur theme repo and plugin repo, as well as ur libray, restart discord and on start up, (for me) it'll take a good few seconds of freezing before it'll respond

**Expected behavior**
a crash and slowness

**Screenshots**

**Discord Build (stable, ptb or canary):**
stable

**Additional context**

**Comment by mwittrien** [comment]
The delay on startup is normal due to my plugins loading

Cant expierence a slowdown while on ThemeRepo tho
