### ISSUE TITLE
[BUG] - SpotifyConrols Plugin

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#1008]
**Describe the Bug**
if the plugin is activated the call box is everytime on top if you in a call  and not on the normal position like before

**To Reproduce**
**use spotifycontrols plugin** and hear music **on Spotify** and beeing in a call

**Expected Behavior**
that the call box be still on the original position and not on top

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/128062949-d12a8879-11c9-4afd-994b-922186f04806.png)

**Discord Version**
1.0.9002

**Plugin Version**
v1.1.8

**Comment by mwittrien** [comment]
Thats the intended order

**Comment by BlueStarBRS** [comment]
> Thats the intended order

then make it possible to swap pls

**Comment by mwittrien** [comment]
You can change it with css

**Comment by BlueStarBRS** [comment]
> You can change it with css

what i must do to use that ?
und do you have a command line for me ?
