### ISSUE TITLE
[IMPROVEMENT] - lightcord

### ISSUE THREAD

**Issue by coolbirdd** [mwittrien/BetterDiscordAddons#1011]
It's known that you hate Lightcord. In all of your plugins you bash on Lightcord. When people asked you why, you said that lightcord doesn't work with your plugins, it's putting your account at risk etc. All of your answers are perfectly summarized by logan2611 in issue #883 (which you ghosted and closed). Lightcord literally is just BetterDiscord with more features. So with all of this in mind, ive come to the conclusion that you probably have some agreement with BetterDiscord devs to not support Lightcord, but then I wonder, why not just say that? Why lie to the users of your plugins?

**Comment by mwittrien** [comment]
Because thats not the case :)
