### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications - Timelogging option

### ISSUE THREAD

**Issue by Mereck13579** [mwittrien/BetterDiscordAddons#1012]
**Describe the solution you'd like**
Having the option to log status change in the timelog for specific users (+ default setting option for new user).

**Describe alternatives you've considered**
Logging everything in the timelog. That would clutter it a bit but there is a search function so I wouldn't mind that much.

**Additional context**
For most of my friends on discord I don't want notification each time they are online or not, but sometimes I want to know if they were recently online (kind of akin to Steam's "last online" feature). Being able to look it up in the timelog would be ideal.

**Comment by mwittrien** [comment]
Added an option to disable timelog for certain ppl

**Comment by Mereck13579** [comment]
That's not actually what I meant with this improvement. Basically I wanted something to be able to timelog activity **without** a notification on.
