### ISSUE TITLE
[BUG] - ServerFolders React Error

### ISSUE THREAD

**Issue by Smaltin** [mwittrien/BetterDiscordAddons#1014]
**Describe the bug**
When I open a folder up, React throws an error.

**To Reproduce**
1. Start ServerFolders
2. Open a folder
3. Notice "React Component Error" appears where folders would normally be

**Expected behavior**
I should be able to view my servers inside the folder

**Screenshots**
![SS](https://coding.life-is-pa.in/56p3hYIJn.png)
![SS2](https://coding.life-is-pa.in/56p3Obnp6.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
[Logs](https://github.com/mwittrien/BetterDiscordAddons/files/6948389/discord.com-1628298734268.log)

**Comment by Smaltin** [comment]
Issue **reproducible** on PTB without any other plugins/themes enabled.

**Comment by mwittrien** [comment]
Reload discord
