### ISSUE TITLE
[IMPROVEMENT] - EditServers - Set server to Verified or Partner

### ISSUE THREAD

**Issue by Alespren** [mwittrien/BetterDiscordAddons#1015]
**Describe the solution you'd like**
The ability to edit a server so that it appears to be either Verified or Partnered and has the appropriate icon next to the name. Also the ability to remove the Partnered/Verified status of a server so the icon doesn't appear.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mwittrien** [comment]
Dont see the point of faking that i dont wanna endorse such behaviour
Same reason i didnt include adding badges in EditUsers
