### ISSUE TITLE
RemoveBlockedUsers removes notification about new messages

### ISSUE THREAD

**Issue by Adenser** [mwittrien/BetterDiscordAddons#1025]
As in the title, when the RemoveBlockedUsers plugin is enabled, there is no notification that a new message was sent in the channel, after disabling RemoveBlockedUsers message notification comes back
![image](https://user-images.githubusercontent.com/39248856/128595630-7a626792-eac5-4b87-9a95-de2465337c07.png)

**Comment by shadow306k** [comment]
+1 this, having exactly the same problem

BDFDB 1.7.13 | RBU 1.3.1

**Comment by Adenser** [comment]
Fixed in 1.3.2
