### ISSUE TITLE
[improvement] Toggle button color adjustment

### ISSUE THREAD

**Issue by KirbyKat21** [mwittrien/BetterDiscordAddons#1026]
![image](https://user-images.githubusercontent.com/73803545/128606049-d50ea82e-9371-47d1-9832-39b7e873bbb8.png)

Would love to be able to set the color of enabled and disabled for the auto capitalize switch in the text field. Red for on (which it usually is) mentally makes me feel its off.

**Comment by mwittrien** [comment]
Use css to change it
