### ISSUE TITLE
[BUG] - ReadAllNotificationsButton v1.6.8

### ISSUE THREAD

**Issue by kokozweeb** [mwittrien/BetterDiscordAddons#1027]
**Describe the bug**
When I press the "read all" button nothing get marked as read.

**To Reproduce**
When I press the "read all" button.

**Expected behavior**
Marks every server as read.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable 92762 (a95e09a)

**Additional context**
N/A

**Comment by teisseire117** [comment]
I have the same issue. When I go on the server, the channels are gray as if every messages/notifications were read
But it doesn't show on the server list

**Comment by miklereverie** [comment]
Getting the same issue after Discord's latest update.

**Comment by mwittrien** [comment]
fixed
