### ISSUE TITLE
[BUG] -Server Folders

### ISSUE THREAD

**Issue by d3athrow** [mwittrien/BetterDiscordAddons#1029]
**Describe the bug**
Unread message and mention indicators do not properly update for guilds in expanded folders

**To Reproduce**
Have current version of stable desktop discord and better discord with the server folders plugin

**Expected behavior**
Unread message and mentions indicators show up and clear properly

**Screenshots**
n/a

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Ctrl R
