### ISSUE TITLE
[BUG] - ReadAllNotificationsButton doesn't work perfectly

### ISSUE THREAD

**Issue by austinbabe** [mwittrien/BetterDiscordAddons#1031]
**Describe the bug**
- After clicking the button, Some channels didn't clear the blue bubble.

**To Reproduce**
- Clicking the button.

**Expected behavior**
- All bubbles are gone.

**Screenshots**
![img](https://i.imgur.com/BkAQQ9t.png)

**Discord Build (stable, ptb or canary):**
- OS: Win10
- Discord: 92814
- BD: v1.2.1
- BDFDB: v1.7.13
- ReadAllNotificationsButton: v1.6.8

**Additional context**
> Already redownload the plugin. Or try it on a different PC.  Still meet the same issue.

**Comment by mwittrien** [comment]
Ctrl R
