### ISSUE TITLE
[BUG] - DiscordRecolor message highlight issue

### ISSUE THREAD

**Issue by PimpUigi** [mwittrien/BetterDiscordAddons#1032]
Clicking this doesn't highlight the attachment anymore, and if someone replies to a message, when I click the original message it doesn't highlight that either. iirc it's supposed to follow the (--mentioncolor, --warningcolor) stuff
![image](https://user-images.githubusercontent.com/7344271/128839007-a631084f-55e5-45a3-a526-9082abf449a4.png)

**Comment by PimpUigi** [comment]
This bug seems to have creeped back into DiscordRecolor at some point.

**Comment by mwittrien** [comment]
Discord changed it
