### ISSUE TITLE
[IMPROVEMENT] - Translator 

### ISSUE THREAD

**Issue by xiao-e-yun** [mwittrien/BetterDiscordAddons#1033]
googleAPI have "zh-TW" Languages
can you add this please
[position](https://github.com/mwittrien/BetterDiscordAddons/blob/092c9ff231e351f6520040b54c15be829afa73fd/Plugins/Translator/Translator.plugin.js#L290)

**Comment by mwittrien** [comment]
Google does not fully support zh-TW as input AND output language

**Comment by xiao-e-yun** [comment]
![image](https://user-images.githubusercontent.com/67814228/128845917-6a877803-96c5-48c1-8a57-8b8638519d7e.png)
in https://cloud.google.com/translate/docs/languages
