### ISSUE TITLE
[BUG] - CustomStatusPresets

### ISSUE THREAD

**Issue by A983Hub** [mwittrien/BetterDiscordAddons#1038]
**Describe the bug**
When i click on my user avatar to pick a status, my Discord Client goes into the "Well, this is awkward" error message. When i turn off CustomStatusPresets, the error message doesn't appear anymore.

**To Reproduce**
Just use CustomStatusPresets.

**Expected behavior**
To go to the status menu with Do Not Disturb, Idle, Online, and Custom Preset Stuff like Normal.

**Screenshots**
None. It's just an error message thing.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Idk if this is a bug with a update or bug fix. I never had that bug before. Maybe it was recent with no warnings?

**Comment by saiv123** [comment]
i have just realized this bug as well, it started happening after the last discord update.

**Comment by saiv123** [comment]
![image](https://user-images.githubusercontent.com/22565623/129125022-705e6aa7-d395-468b-b508-93d8bbc18f6b.png)
this is the error that happens

**Comment by 226914011** [comment]
![圖片](https://user-images.githubusercontent.com/62089446/129139908-2747e596-87d1-402f-85c7-e524724d22ea.png)
Same problem here with these error message

**Comment by 226914011** [comment]
![圖片](https://user-images.githubusercontent.com/62089446/129141981-d4808c76-fc33-4bdf-8960-3a2eb5661e44.png)
The problem seems to be the navID right here and I have no idea how to fix it

**Comment by 226914011** [comment]
![圖片](https://user-images.githubusercontent.com/62089446/129163023-a2db400a-4f96-4984-8b3c-7304f99b89d1.png)
It should be a problem cause by discord?

**Comment by TheHunter1234** [comment]
I can confirm, the same issue on PTB with the same cause and place of the crash.

**Comment by mwittrien** [comment]
Fixed, Ctrl R to reload for fix

**Comment by TheHunter1234** [comment]
Issue still occurs even after a restart of client and pc.

**Comment by TheHunter1234** [comment]
Will set your status on the client as invisible (idk if you are actually invisible) and if you click on your profile and hover to change the status or online presence (DND, Invisable, etc.) the client will crash.

**Comment by TheHunter1234** [comment]
Update: Will force you to invisible Discord wide.
