### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by EmotionChild** [mwittrien/BetterDiscordAddons#1039]
**Describe the bug**
Whenever I open the sound configuration is says: There was an unexpected Error. Click to open the console for more details

**To Reproduce**
Open the sound configuration

**Expected behavior**
It is meant to show the sound configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/36905598/129129037-dafd190e-100c-4182-8f9e-0ee05dc482a0.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This just started happening after I installed the BDFDB update

**Comment by identity7** [comment]
![image](https://user-images.githubusercontent.com/85660015/129133214-f13565cf-a573-4a10-ac38-4e60854fb189.png)
this is the error it in console it gives, for added info

**Comment by sebastienpuylaurent** [comment]
Same here, with the same discord error. I hope it will be fixed soon ^^ (I just discover betterdiscord today so)

**Comment by sebastienpuylaurent** [comment]
Thanks
