### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by scorpion19961007** [mwittrien/BetterDiscordAddons#1040]
**Describe the solution you'd like**

Hello, I want to give you a suggestion. Can I add a function: "when I enter Chinese or other languages in the message box, I can automatically convert the language I enter into English or other languages and send it out when sending". The article is machine translation, which may be different from the original text.

**Comment by mwittrien** [comment]
Translator Plugin
