### ISSUE TITLE
[BUG] - PLUGIN/SOUNDCONFIG

### ISSUE THREAD

**Issue by AestheticallyJanked** [mwittrien/BetterDiscordAddons#1041]
**Describe the bug**
Every time I click "Sound Configuration," it gives me an unknown error.

**To Reproduce**
Every single time I click the button

**Expected behavior**
I expected to see the menu that I see in YT tutorials and plugins reviews.

**Screenshots**
[https://media.discordapp.net/attachments/125591732321517568/875231951060103168/unknown.png](url)

**Discord Build (stable, ptb or canary):**
Stable v1.0.9002

**Additional context**
None

**Comment by mwittrien** [comment]
#1039
