### ISSUE TITLE
[BUG] - BDFDB/(not dependent on theme) - blurred Toast notification with no info

### ISSUE THREAD

**Issue by Poirot12345T** [mwittrien/BetterDiscordAddons#1042]
**bug description**
The plugin seems to do it's work at the back-end part (Toast notification is jumping out, when clicking, it redirects you to the users DM as it should do so), but it contains no info (just empty blurred box) and when clicking on online friend online counter to show the log in the past, it throws "react component Error", reloading or reinstalling the plugin didn't solve the problem.

**To Reproduce**
a) toast nofication: just let the plugin run and wait until some state-change appears
b) log: click on online counter

**Expected behavior**
a) showing info from the state-change
b) showing all catched state-changes

**Screenshots**
a) blurred toast notification showing no info 
![Snímek obrazovky 2021-08-12 113748](https://user-images.githubusercontent.com/82270962/129175015-69ce892c-eb3a-4c04-8d85-9780fc2f41bd.png)
b) react component error from friend-log
![Snímek obrazovky 2021-08-12 113741](https://user-images.githubusercontent.com/82270962/129175003-3b5d4704-f5d9-44b6-87e0-ee34548fa9bf.png)

**Discord Build:**
stable, changelog date 2021-08-02

**Comment by Poirot12345T** [comment]
![image](https://user-images.githubusercontent.com/82270962/129175716-2de31d5c-d86d-4c53-8e35-a64fb10dfa30.png)
when looking into console, it throws this error (sorry for bad plugin targeting)

**Comment by mwittrien** [comment]
Fixed, Ctrl R to reload for fix
