### ISSUE TITLE
[BUG] - CustomStatusPresets/Crash when using

### ISSUE THREAD

**Issue by Kipotuzer26** [mwittrien/BetterDiscordAddons#1044]
**Describe the bug**
Discord crashes when opening the status menu.

**To Reproduce**
Create a custom status preset, open the custom status menu with the plugin enabled.

**Expected behavior**
Discord to not Crash

**Discord Build (stable, ptb or canary):**
Stable

**Comment by TheHunter1234** [comment]
@Kipotuzer26 Main issue: https://github.com/mwittrien/BetterDiscordAddons/issues/1038
