### ISSUE TITLE
[BUG] - FriendNotifications plugin not working (blurred notifications)

### ISSUE THREAD

**Issue by marcpinet** [mwittrien/BetterDiscordAddons#1046]
**Describe the bug**
Notifications are appearing blurred.

**To Reproduce**
To reproduce, just get the latest version of FriendNotifications and see.

**Expected behavior**
The notification to not being blurred

**Screenshots**
![image](https://user-images.githubusercontent.com/52708150/129202194-c9dabff4-2025-4620-9ed5-e5dd7973a239.png)

**Discord Build (stable, ptb or canary):**
Latest Stable

**Comment by mwittrien** [comment]
Fixed, Ctrl R to reload for fix
