### ISSUE TITLE
[BUG] - Image Utilities - MOV File Auto-changing Format to Quicktime

### ISSUE THREAD

**Issue by Gimpy3887** [mwittrien/BetterDiscordAddons#1048]
**Describe the bug**
When I save a file that's in `mov` format, the format changes to `.quicktime`--everytime this happens for those files: I'm forced to go back and mass change them to `.mov`. 

**To Reproduce**
Download a `mov` file using the plugin.

**Expected behavior**
I expected the `mov` file to be in `mov` format not `quicktime`.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Thats an issue with your mac and not the plugin

**Comment by Gimpy3887** [comment]
mac? i'm on windows
