### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Behelden** [mwittrien/BetterDiscordAddons#1052]
0BDFDB from https://betterdiscord.app/plugin/BDFDB, causes issue where all settings have disappeared. Have used Sandboxie to try isolate the issue, cannot find the cause.
GPU: 5700XT latest driver as of 14th August.
Removing BDFDB fixes issue on Lightcord running on both USB, Sandboxie and default installation.

Considering you made the plugin I thought you might have an idea of what might be the issue. I assume compatibility with one of Lightcords features?
![image](https://user-images.githubusercontent.com/55672265/129458775-bcbf612f-536b-4fc4-81e2-11d511b8a2af.png)

**Comment by mwittrien** [comment]
My plugins are not fot Lightcord
