### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities - New search engine

### ISSUE THREAD

**Issue by Flo2ent** [mwittrien/BetterDiscordAddons#1053]
**Describe the solution you'd like**
A new search engine for the ImageUtilities plugin: _[i.rarchives.com](https://i.rarchives.com/)_.

**Additional context**
_i.rarchives.com_ is for **NSFW** reddit reverse image search.

**Comment by mwittrien** [comment]
No NSFW stuff in my plugins
