### ISSUE TITLE
[BUG] - EditUsers - no colored username and not changed nickname on the down left corner

### ISSUE THREAD

**Issue by Ash3781** [mwittrien/BetterDiscordAddons#1063]
**Describe the bug**
the plugin won't color messages and change the down left corner with my username and it's color even if i set it to something else

**To Reproduce**
it simply does not change the down left corner and the message color, i guess just try it yourself

**Expected behavior**
welp to change my nickname (locally ofc) and my message color to what i set it to (Ashy and hex code #8634D9FF as color for name, tags and messages)

**Screenshots**
![2021-08-24_10-25](https://user-images.githubusercontent.com/37660156/130583887-fcbeaf13-217c-4c22-a7fc-f1500953c204.png)
![2021-08-24_10-25_1](https://user-images.githubusercontent.com/37660156/130583892-8586cda0-8325-4925-a4a9-653729b71607.png)

**Discord Build (stable, ptb or canary):**
Stable 94542 (e0f6b92)
BetterDiscord 1.2.1
Host 0.0.15 Linux 64-Bit (5.13.12-Zen1-1-Zen)
(Garuda (arch ish) linux with latest updates)

**Additional context**
i got it to work on my laptop by toying around a lot with multiple things, reinstalled a couple times every layer (first the plugin, then bd, after that reinstalled the entire discord app itself) but still i can't get it to work on my pc, laptop has the same os with the same bd info on it, i literally copied the whole bd folder

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/130618738-d241069a-f178-4372-baff-19df52d58d1e.png)
works fine for me

try a Ctrl R
if that doesnt fix it it's most likely a plugin conflict like with AccountDetailsPlus or a theme conflict for the message colors not changing
