### ISSUE TITLE
[BUG] - DiscordRecolor - Partly changes accentcolor2 (boostpink)

### ISSUE THREAD

**Issue by kilickerem066** [mwittrien/BetterDiscordAddons#1064]
**Describe the bug**
DiscordRecolor partly changes accentcolor2 (boostpink).

**To Reproduce**
- Install the theme and change accentcolor2 value.
- Partly changes the color (not changing boost badge color)

**Expected behavior**
It shold completely change the color. But it doesn't.

**Screenshots**
![Screenshot_20210824_134715](https://user-images.githubusercontent.com/64794941/130604026-812ac406-47c4-4b70-b05a-a3583df471ad.png)
![Screenshot_20210824_134739](https://user-images.githubusercontent.com/64794941/130604036-365fba92-ce8f-4718-af07-538035167661.png)
![Screenshot_20210824_134803](https://user-images.githubusercontent.com/64794941/130604047-c6338904-a1bc-451c-a681-b3a67ce1052a.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
- Operating System: Kubuntu Linux 20.04 (linux kernel 5.11)
- Discord Version: 0.0.15

![Screenshot_20210824_134850](https://user-images.githubusercontent.com/64794941/130604059-2d476aef-6442-456c-8bba-9177eb014196.png)

**Comment by mwittrien** [comment]
The subscriptions tab uses accentcolor not accentcolor2

**Comment by kilickerem066** [comment]
I am not talking about the subscriptions tab, I am talking about the server boost tab (and badges)

**Comment by mwittrien** [comment]
Ah i am blind didnt see the boost tab oof
