### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by phamleduy04** [mwittrien/BetterDiscordAddons#1069]
**Describe the bug**
When trying to use slash command the discord client crashed.

**To Reproduce**
Go to the server and type `/`.

**Expected behavior**
Show list of slash command avaliable.

**Screenshots**
![image](https://user-images.githubusercontent.com/32657584/131438853-8ab01548-85f5-4e15-86d4-8ffddd06084f.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
The issue is BetterBlockedUsers not BDFDB
