### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by Nerxxy** [mwittrien/BetterDiscordAddons#1071]
**Describe the solution you'd like**

I have an idea on how you could make the incoming call thing work for DnD users... when getting a call there is an element that shows up, so I'm thinking, maybe you could check to see if that element is active and then if it is then force play a sound? the element id is "callContainer-36WRfH"

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by mwittrien** [comment]
Or dont use DnD if you wanna get Notifications
