### ISSUE TITLE
[IMPROVEMENT] - SpotifyControls - improve "previous" function

### ISSUE THREAD

**Issue by guiloj** [mwittrien/BetterDiscordAddons#1072]
**Describe the solution you'd like**

I found it quite frustrating to go back a song on the plugin so I created my own fix, it involves altering the code on the for the `previous` button to resemble the one bellow, the fix should make it so when the button is clicked the song goes back to the start immediately, but gives the user 2 seconds to click it again for the previous song to start playing. I found this fit me well but may need some adjustments to fit the plugin well.

**Describe alternatives you've considered**

# Altering The Code:

this is the altered function I was talking about, I am not at all experienced with this library, so there is probably a better way to implement this.

```js
BDFDB.ReactUtils.createElement(SpotifyControlsButtonComponent, {
    type: "previous",
    player: this,
    disabled: socketDevice.device.is_restricted,
    onClick: _ => {
        if (previousIsClicked || !_this.settings.general.doubleBack) {
            previousIsClicked = false;
            this.request(socketDevice.socket, socketDevice.device,"previous");
        }
        else {
            previousIsClicked = true;
            this.request(socketDevice.socket, socketDevice.device, "seek", {
                    position_ms: 0
                });
            previousDoubleTimeout = BDFDB.TimeUtils.timeout(_ => {
                previousIsClicked = false;
            }, 2000);
        }
    }
}),
```

from what I understand the changes I implemented just simply execute the `seek` command before waiting the timeout and making the timeout bigger, this should make it way more comfortable to use, at least on my side.

# Creating New Settings:
* new switch:

this is a more user interactable way to implement something like this.
other than the doubleBack setting a new switch could be introduced, to make this delay possible.

```json
"general": {
    "addActivityButton": true,
    "addTimeline": true,
    "doubleBack": false,
    "doubleBackDelay":true,
    "_comment":"doubleBack and doubleBackDelay should be always opposite"
}
```

* new field:

or to make it easier on the user, make an implementation of the first snippet shown in this issue (Altering The Code:) but adding to the settings a field to choose the delay time to what suits one best.

```json
"general": {
    "addActivityButton": true,
    "addTimeline": true,
    "doubleBack": true,
    "doubleBackDelay":300,
    "_comment":"the delay can be changed to whatever, I personally like 2000"
}
```

and something like this?

```js
previousDoubleTimeout = BDFDB.TimeUtils.timeout(_ => {
                previousIsClicked = false;
            }, _this.settings.general.doubleBackDelay);
```
**Additional context**

This is way more of a suggestion than a improvement per say, but I do think it does make the button way less frustrating, the first time I used it I even blamed it on the Spotify API, that I have used before and know to be headache inducing, and brushed it off, but seeing it to be a simple fix I decided to make it and try to share it here.

**Comment by mwittrien** [comment]
I don't get what your issue is,
the back button acts the same way as in the original spotify player,

if you click it once it will jump back to the beginning of the song and if you click it twice it will jump to the previous song, this can be disabled to always jumping to the previous song if you disable "doubleBack"

**Comment by mwittrien** [comment]
Weird double click to previous seems to have been broken in some update, i fixed it
