### ISSUE TITLE
[BUG] - ThemeRepo

### ISSUE THREAD

**Issue by Lubieerror** [mwittrien/BetterDiscordAddons#1076]
**ThemeRepo wants to update theme to older version**

**To Reproduce**
When WindowsXI theme by Leeprky#2063 is installed and updated to v1.1.0

**Expected behavior**
Most recent version would will be prefered

**Discord Build (stable, ptb or canary):**
Stable 96355 (c244e32)
BetterDiscord 1.2.1
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)
[Theme] Version: v1.1.0 (Latest)

**Additional context**
Besides of possible versioning problem, this might be caused because old source pointed to version from commit, instead of stable/main one. I'm not sure how it's backend works but old version might be eg. cached there.

Update urls for:
- Old version: [https://github.com/leeprky/WindowsXI/blob/**a8beceec376f510d1f674a13f5111048c6e3a7c1**/source/support/betterdiscord/windowsXI.theme.css](https://github.com/leeprky/WindowsXI/blob/a8beceec376f510d1f674a13f5111048c6e3a7c1/source/support/betterdiscord/windowsXI.theme.css)

- New version: [https://github.com/leeprky/WindowsXI/blob/**main**/source/support/betterdiscord/windowsXI.theme.css](https://github.com/leeprky/WindowsXI/blob/main/source/support/betterdiscord/windowsXI.theme.css)

[Actual @updateUrl points to not existing lode branch, which redirects to main. I already proposed change to theme author.]

**Comment by Lubieerror** [comment]
#1073 probably related

**Comment by mwittrien** [comment]
The repo plugins use the source url from the api of the BD webpage which is the last commit which was verified by the website mods, so the newest Version of the theme hasnt been approved yet
