### ISSUE TITLE
[IMPROVEMENT] - SpotifyControl

### ISSUE THREAD

**Issue by Just5KY** [mwittrien/BetterDiscordAddons#1077]
**Add "Like" button"** 
Hello Dev, 
please add a like button on the expanded form. I feel that's the only feature because of which I have to open Spotify every time.

Spotify
![image](https://user-images.githubusercontent.com/71321862/132109811-2dcc1d24-18ed-493c-a650-35bcc6435c9e.png)

Discord Plugin
![image](https://user-images.githubusercontent.com/71321862/132109801-5a31d1c1-1acc-484d-8b45-062a66f09b58.png)

**Comment by mwittrien** [comment]
Not possible, discords spotity integration has no permissions to like a song
