### ISSUE TITLE
[BUG] - ShowHiddenChannels incompatible with AccountSwitcher

### ISSUE THREAD

**Issue by OsoaGitHub** [mwittrien/BetterDiscordAddons#1078]
**Describe the bug**
After changing accounts with [AccountSwitcher](https://github.com/l0c4lh057/AccountSwitcher), all channels are locked until plugin is disabled.

**To Reproduce**

1. Enable both AccountSwitcher and ShowHiddenChannels.
2. Swap account by middle-clicking the bottom-left profile picture.
3. View a server on the second account.
4. See all channels are locked.
5. See these locked channels are not openable.

**Expected behavior**
I expect channels I have permission to view are openable and that channels that I do not have permission to view are viewable but not openable.

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by mwittrien** [comment]
AccountSwitcher aint an official plugin
I am not making sure my plugins work with inofficial stuff
