### ISSUE TITLE
[BUG] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by flamdru** [mwittrien/BetterDiscordAddons#1079]
when clicking yourself on the right side in members list the username disappears. basically cannot click on yourself in members list

**Comment by flamdru** [comment]
it appears that you cant click on the last person in the server booster role list

**Comment by mwittrien** [comment]
Not the case for me, might be another plugin causing it

**Comment by flamdru** [comment]
i have left only removeblockedusers in the plugin folder

**Comment by flamdru** [comment]
and redownloaded it
