### ISSUE TITLE
Discord PFP's not showing in chat

### ISSUE THREAD

**Issue by GamR-the-Great** [mwittrien/BetterDiscordAddons#108]
On BandagedBD, with the Basic Background theme enabled, it removes pfp's from the chat. I have turned off my plugins to make sure it was not the cause, but to no avail, they appear after I turn off the theme though. This happened recently as before they would show in the chat. Is their a fix to this?

Attached are example pictures showing what I mean

With Theme

![unknown 1](https://user-images.githubusercontent.com/37517323/43683660-7b2f5ccc-985e-11e8-901a-8b51108e8636.png)

Without Theme
![unknown 1](https://user-images.githubusercontent.com/37517323/43683665-9b49272c-985e-11e8-96c5-b38bd0d93ae9.png)

Please contact me if there is a fix to this

Sincerely, GamR

**Comment by mwittrien** [comment]
Fixed
