### ISSUE TITLE
[BUGs] - Basic Background

### ISSUE THREAD

**Issue by NeverEndingCycle** [mwittrien/BetterDiscordAddons#1081]
Top pixels of PFP's are cut off in calls.

![image](https://user-images.githubusercontent.com/42754840/132388100-22eb27ad-838d-4d6c-88c3-b87a4df77d7f.png)

When opening settings, opacity gets lowered then increased after about a second.
![image](https://user-images.githubusercontent.com/42754840/132388228-7c6228fe-9f55-40d4-8b2a-dc98d1ecac6f.png)
![image](https://user-images.githubusercontent.com/42754840/132388246-e24b099a-887d-4668-8891-7948a2ec713d.png)

There is a black seam above your profile in the bottom left. Not sure if this one is intentional.
![image](https://user-images.githubusercontent.com/42754840/132388799-403734f3-6d9d-419f-ace2-dafce0242bf0.png)

Editing default roles has the wrong opacity in this spot.
![image](https://user-images.githubusercontent.com/42754840/132389338-8d5c21b1-854a-454e-9c7e-2e4996a7cc0c.png)

Sorry for posting so many at once, but it seems easier for both of us this way.

**Comment by mwittrien** [comment]
Voice avatars being cut off is an issue with discord
