### ISSUE TITLE
[BUG] - SpotifyControls

### ISSUE THREAD

**Issue by ThatOneJay** [mwittrien/BetterDiscordAddons#1084]
**Describe the bug**
When Spotify hasn't been playing for a while and you press play on the plugin, it won't play the song and the timeline bar jumps to the very end. However in spotify nothing changes. (Discord shows correct song though). Before pressing play though, the plugin does show the correct spot on the timeline.

**To Reproduce**
I'm not sure how to reproduce it I really just notice it happening when using it after inactivity.

**Expected behavior**
When pressing play, it should be able to play from the spot the player says.

**Screenshots**
![image](https://user-images.githubusercontent.com/76684256/132626743-ccff36c4-1b61-4af8-b96c-9d40b7d8d496.png)

**Discord Build (stable, ptb or canary):**
Stable 96622 (0cc9fd7)
BetterDiscord 1.2.1
ClearVision 6.1.1

**Additional context**

**Comment by mwittrien** [comment]
Because the session is lost and spotifycontrols cant initiate a session by itself
