### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by Nareonith** [mwittrien/BetterDiscordAddons#1087]
**Describe the solution you'd like**
Option to have Notification sounds play through the output device selected in discord instead of my system sounds.

**Additional context**
I requested this quite a while back and it was quickly implemented, but it seems to have been removed? Hoping it wasn't because it was causing issues and just got forgotten in an update somewhere. Regardless, thanks for making this awesome plugin :D

**Comment by mwittrien** [comment]
That wasnt changed
