### ISSUE TITLE
[BUG] - EditUsers - Changes don't appear in some areas

### ISSUE THREAD

**Issue by vylryna** [mwittrien/BetterDiscordAddons#1090]
**Describe the bug**
User changes don't appear in stream spectators or search.

**To Reproduce**
Change someone's profile picture or username locally, it won't change in the stream spectators or search.

**Expected behavior**
The user should have their edited details changed in those areas as well.

**Screenshots**
How it should look (member list): https://i.imgur.com/53JToVL.png
How it appears (search list): https://i.imgur.com/hyuWNMf.png

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None.

**Comment by mwittrien** [comment]
Where exactly in streams?

**Comment by vylryna** [comment]
When viewing a stream, on the bottom left, it shows a list of the current spectators. The profile pictures don't change there.
