### ISSUE TITLE
[IMPROVEMENT] - Ping per user (plugin)

### ISSUE THREAD

**Issue by Harmless05** [mwittrien/BetterDiscordAddons#1092]
**Describe the solution you'd like**
In DMs, if a person pings you and the spam it (hearing the ping sound multiple times) should be turned to only hear the ping sound once even if the person has sent you multiple messages.

**Describe alternatives you've considered**
Don't have one.

**Additional context**
A plugin that only pings you with the sound once per user or server even if they send multiple messages.

**Comment by mwittrien** [comment]
I am not taking plugin requests
