### ISSUE TITLE
[BUG] - SERVER FOLDERS

### ISSUE THREAD

**Issue by SuperDasher** [mwittrien/BetterDiscordAddons#1093]
This is a problem I've only experienced today, and it seems that the plugin ServerFolders makes my discord client stop working, with a blank screen and a button labeled "reload". I found out the problem was caused by this plugin because I uninstalled it and discord worked, as soon as I installed it again it did the same thing

**Comment by mwittrien** [comment]
The Issue is HideChannels and not ServerFolders
