### ISSUE TITLE
[BUG] - PinDMs - Issue with Game Activity Toggle plugin

### ISSUE THREAD

**Issue by XDMelone333** [mwittrien/BetterDiscordAddons#1095]
**Describe the bug**
When loading PinDMs after the Game Activity Toggle Plugin the button to toggle the gameactivity disappears.

**To Reproduce**
Load the Game Activity Toggle plugin, load the PinDMs plugin and the button to toggle the game activity will disappear.

**Expected behavior**
The PinDMs plugin should load without making the Game Activity Toggle button disappear.

**Discord Build (stable, ptb or canary):**
Stable 97662 (924f611)
BetterDiscord 1.2.1
Host 1.0.9002 
BDFDB v1.8.5

**Additional context**
Since i dont know much about all this stuff, the problem could also be on the side of the Game Activity Toggle plugin, but since only the PinDMs plugin makes it disappear i thought i'd report it as a bug in PinDMs. Sorry if im wrong.

**Comment by mwittrien** [comment]
Your version of GameActivityToggle is old, use the one made by me
