### ISSUE TITLE
[IMPROVEMENT] - ShowHiddenChannels - Keep existing `parent_id` (somewhere?) without overwriting it.

### ISSUE THREAD

**Issue by Farcrada** [mwittrien/BetterDiscordAddons#1096]
***Presumed location***
https://github.com/mwittrien/BetterDiscordAddons/blob/6b568c2e64ebc62dd783bb70f30e5be8c66298b9/Plugins/ShowHiddenChannels/ShowHiddenChannels.plugin.js#L471-L474

***The situation***
The `parent_id` is overwritten in channels in the `hidden`-category. This happens when the user selects: "Extra Category 'Hidden'". If a hidden channel was part of a category this is overwritten by the hidden category's (new) ID. I'm using a comparison based off of the `parent_id` to see if a channel is synced permission wise with it's parent (the category). Source here: https://github.com/Farcrada/DiscordPlugins/blob/master/Channel-Permissions/ChannelPermissions.plugin.js#L496-L499

***My issue, current solution and request***
Having this work on hidden channels would be cool as well. I've fixed it by reporting the category is unknown, but having the original `parent_id` somewhere would be my request.

***Screenshots:***
![image](https://user-images.githubusercontent.com/8385001/134144256-678ad2f8-3378-4740-9a6a-bae964017106.png)
![image](https://user-images.githubusercontent.com/8385001/134144018-b81bfa3b-470c-475f-a213-ff4fa38273d7.png)

**Comment by mwittrien** [comment]
The parent_id is used by Discord to categories channels in a category and its not possible to add custom properties to discord objects

**Comment by mwittrien** [comment]
Just grab the original channel obj from discords channel store `BdApi.findModuleByProps("getChannel").getChannel(CHANNEL_ID);` and use the parent_id from that

**Comment by Farcrada** [comment]
Perfect. Should've thought of that myself. Thank you!
