### ISSUE TITLE
The default translation is all. Click to view the original text.

### ISSUE THREAD

**Issue by 57382** [mwittrien/BetterDiscordAddons#1099]
This will avoid frequent manual click to translate. Thus, greatly enhances the availability and convenience of the plugin. thanks.

**Comment by mwittrien** [comment]
What

**Comment by 57382** [comment]
> What

I mean: automatically translate all conversations. You don't have to tap translate one by one.
At this point, do the opposite: if you click on it, it will display the original text without translation.

**Comment by 57382** [comment]
@mwittrien

**Comment by mwittrien** [comment]
Not possible as mentioned hundred times already
