### ISSUE TITLE
[BUG] - DisplayServersAsChannels - Servers are invisible

### ISSUE THREAD

**Issue by djinnsynth** [mwittrien/BetterDiscordAddons#1100]
The new Force High Contrast Off setting seems to have made the text for servers invisible while using your plugin:

![image](https://user-images.githubusercontent.com/60988604/134607565-0ef208fc-d4f7-4b04-961b-8e9fd47e250c.png)

I had a quick look in the inspector and found this: 

`html.disable-high-contrast * {
    forced-color-adjust: none;
}`

which mayyyy have something to do with it but I'm not so sure.

**Comment by GreenMan36** [comment]
Yup broken af 
![image](https://user-images.githubusercontent.com/5887406/134654974-08089e14-ce25-4eaf-933c-b1217bcfae45.png)
