### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by ThePluffy** [mwittrien/BetterDiscordAddons#1102]
When I enable PinDms it nearly instantly crashes my Discord. It only crashes when I have other plugins enabled, not alone with the librarys.

I am using Discord stable.
These are all my plugins, I have nearly all of them enabled:
![image_2021-09-24_163405](https://user-images.githubusercontent.com/89693021/134692480-8e5b175f-1307-42fe-900b-8dc45fa6324a.png) 
![image](https://user-images.githubusercontent.com/89693021/134692627-8ad9fada-99e8-4ed4-b078-1436e3ca5f5c.png)
![image](https://user-images.githubusercontent.com/89693021/134692662-2d78ac21-4c5e-4e3b-bb04-278904cc0683.png)

**Comment by mwittrien** [comment]
Your HideChannels plugin is outdated
