### ISSUE TITLE
Change the location of the copy text button

### ISSUE THREAD

**Issue by Feeenix** [mwittrien/BetterDiscordAddons#1103]
i want to be able to customize the location of the "Copy Text (Raw)" button.
right now the buttons location is the same as the old Delete button. i am not used to this, and when i go to delete my message, i end up copying it instead. 

i would like a way to change the place where the button is located, either by editing code or changing a variable. or alternatively you can show me how to change the index of the element in the context menu.

i would greatly appreciate if it was not at the very bottom of the context list

![image](https://user-images.githubusercontent.com/85449712/134722732-7bae7ce8-8f6f-4ea0-98a3-852c7e24fcec.png)

**Comment by mwittrien** [comment]
Change it yourself in the code, adding an option is rather tedious

**Comment by Feeenix** [comment]
> 
> 
> Change it yourself in the code, adding an option is rather tedious

how do i do that

**Comment by Feeenix** [comment]
```onMessageOptionContextMenu (e) {
  if (e.instance.props.message && e.instance.props.message.content) {
	  let [children, index] = BDFDB.ContextMenuUtils.findItem(e.returnvalue, {id: "mark-unread"});
	  children.splice(index + 1, 0, BDFDB.ContextMenuUtils.createItem(BDFDB.LibraryComponents.MenuItems.MenuItem, {
		  label: BDFDB.LanguageUtils.LanguageStrings.COPY_TEXT + " (Raw)",
		  id: BDFDB.ContextMenuUtils.createItemId(this.name, "copy-message-raw"),
		  icon: _ => {
			  return BDFDB.ReactUtils.createElement(BDFDB.LibraryComponents.SvgIcon, {
				  className: BDFDB.disCN.menuicon,
				  name: BDFDB.LibraryComponents.SvgIcon.Names.RAW_TEXT
			  });
		  },
		  action: _ => {
			  BDFDB.LibraryRequires.electron.clipboard.write({text: e.instance.props.message.content});
		  }
	  }));
  }
}```
what do i need to edit
