### ISSUE TITLE
[BUG] - Server Folders - Blurry Server Icons

### ISSUE THREAD

**Issue by NVHT** [mwittrien/BetterDiscordAddons#1106]
**Describe the bug**
Server icons inside the server folders are blurry.

**To Reproduce**
Update to latest version 6.9.4.

**Expected behavior**
Server icons inside the server folders are blurry.

**Screenshots**
![image](https://user-images.githubusercontent.com/8341213/134757924-97c5dd08-3d3d-42b3-8082-7a735f49b15c.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None.

**Comment by abinroy04** [comment]
![image](https://user-images.githubusercontent.com/85763004/134759286-5e75f854-3dea-4be9-b300-5caa08e603f8.png)

**Comment by re11ding** [comment]
Can vouch for this too. Experiencing the same issue.

**Comment by JacksonFrost13** [comment]
+1 for this. Same stuff on 6.9.4 and after a backup on 6.9.3 too

**Comment by DVD8084** [comment]
Same issue for me. Seems like the latest Discord update might be the culprit.
There was a similar issue at https://github.com/Strencher/BetterDiscordStuff/issues/88, though I'm not sure if that helps.

**Comment by kilickerem066** [comment]
I have the same problem too
