### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by KastroMugnaio** [mwittrien/BetterDiscordAddons#1107]
**Describe the bug**

0BDFDB.plugin.js: Could not be compiled.

**To Reproduce**
At the start it display this and obviously all plugin that requires this not work at all

**Expected behavior**
Anything type of error

**Screenshots**
![image](https://user-images.githubusercontent.com/65294975/134770690-7b335efd-b17e-4d2c-8c1d-ff876f51cb7f.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Redownload it
