### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by reodeza** [mwittrien/BetterDiscordAddons#1109]
**Describe the bug**
Low res server icons in extra column (right one in screenshot)

**To Reproduce**
Happened after discord update, just turn on Extra Colum in plugin settings and open any folder with servers

**Expected behavior**
Clear high res icons as at left column in screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/38606782/134783267-75424308-bc19-472c-8819-9307e5a68fba.png)

**Discord Build (stable, ptb or canary):**
Stable 99016 (0d5a801)
BetterDiscord 1.2.1

**Additional context**

**Comment by mwittrien** [comment]
#1106 already fixed
