### ISSUE TITLE
[BUG] - PinDMs - pinning a DM to server list makes the DM icon in the server list blurry (and laggy)

### ISSUE THREAD

**Issue by kilickerem066** [mwittrien/BetterDiscordAddons#1110]
**Describe the bug**
pinning a DM to server list makes the DM icon in the server list blurry (and laggy)

**To Reproduce**
1. Install PinDMs plugin.
2. Pin a DM to server list.
3. The DM will appear in server list with blurry icon and lag.

**Expected behavior**
It should pin normally without blurry icon and lag.

**Screenshots**
![Screenshot_20210926_093452](https://user-images.githubusercontent.com/64794941/134796501-cebc6dec-591f-4bd9-9758-625f7089b57d.png)

**Discord Build (stable, ptb or canary):**
Stable 99031 (720b494)

**Additional context**
Operating System: Kubuntu Linux 20.04 64-Bit (Linux Kernel 5.11.0-36-generic)
BetterDiscord 1.2.1
Discord Version: 0.0.16

**Comment by mwittrien** [comment]
Has nothing to do PinDMs, most likely StatusEverywhere
