### ISSUE TITLE
[BUG] - ServerDetails.plugin.js Lag

### ISSUE THREAD

**Issue by GreenMan36** [mwittrien/BetterDiscordAddons#1111]
**Describe the bug**
Any time you click in and out of Discord, the client freezes for a moment.

**To Reproduce**
Have ServerDetails.plugin.js installed and enabled.
Click outside of Discord
Click inside of Discord
Observe the hitch/lagg

**Expected behavior**
A fast and snappy Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/5887406/134808279-3d8bdfd6-e4b8-4432-bbc6-e8dcc2a1a20d.png)
Image of lagg timing with only this plugin installed.

**Discord Build (stable, ptb or canary):**
Stable 99031
BetterDiscord 1.2.1
Host 1.0.9003
Windows 10 64-Bit (10.0.19043)

**Additional context**
I went in and enabled/disabled EVERY single plugin (200+) I had to find what was causing this.
My brain is not big enough to use the performance profiler.

**Comment by mwittrien** [comment]
#1105
