### ISSUE TITLE
[BUG] - DisplayServersAsChannels.plugin.js Lag

### ISSUE THREAD

**Issue by GreenMan36** [mwittrien/BetterDiscordAddons#1112]
**Describe the bug**
Any time you click in and out of Discord, the client freezes for a moment.

**To Reproduce**
Have DisplayServersAsChannels.plugin.js installed and enabled.
Click outside of Discord
Click inside of Discord
Observe the hitch/lagg

**Expected behavior**
A fast and snappy Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/5887406/134808942-c075e1da-5061-4567-bf49-26b79a1a6498.png)
Image of lagg timing with only this plugin installed.

**Discord Build (stable, ptb or canary):**
Stable 99031
BetterDiscord 1.2.1
Host 1.0.9003
Windows 10 64-Bit (10.0.19043)

**Additional context**
I went in and enabled/disabled EVERY single plugin (200+) I had to find what was causing this.
So just like in #1111 , I disabled all plugins, enabled them one by one until I noticed lag.
Then I disabled all plugins and enabled the lagging one to confirm it was that plugin causing it.
My brain isn't big enough to use the performance profiler so I have no clue why these two plugins are causing lag.

**Comment by mwittrien** [comment]
#1105
