### ISSUE TITLE
[BUG] - Image Utilities - Pictures are overlapped in gallery mode

### ISSUE THREAD

**Issue by yul-oh895** [mwittrien/BetterDiscordAddons#1115]
**Describe the bug**
When viewing a picture, the rest of the pictures overlap between them and it is not possible to fully view them.

**To Reproduce**
Anytime I open picture.

**Expected behavior**
When opening a picture, It would be fully shown and there should be a spacing between the previous picture and the next one.

**Screenshots**

![2021-09-28_17-38-25](https://user-images.githubusercontent.com/64549167/135179806-7940b1be-423b-4ea8-b101-ec48495acbe0.jpg)

![2021-09-28_17-42-57](https://user-images.githubusercontent.com/64549167/135180012-a94ec1f0-c6fe-49d4-aad4-4bd3ba45f819.png)

As you can see here, there is no spacing between the pictures which makes the text on the middle picture unreadable unless opened on web browser.

**Discord Build (stable, ptb or canary):**
Stable 99447
BetterDiscord 1.2.1

**Additional context**
This started happening since the release previous to 4.4.9 but I was unable to report at that time.

**Comment by mwittrien** [comment]
Are you sure thats not your themes fault?

The details should be in the left bottom corner but for you its in the center

**Comment by yul-oh895** [comment]
You're right, it was the theme causing this issue. Thanks.

**Comment by mwittrien** [comment]
> You're right, it was the theme causing this issue. Thanks.

What theme @yul-oh895

**Comment by yul-oh895** [comment]
@mwittrien Discord+

**Comment by yul-oh895** [comment]
> What theme @yul-oh895

@mwittrien [Discord+](https://betterdiscord.app/theme/Discord%2B)
