### ISSUE TITLE
[IMPROVEMENT] - PLUGIN - Customizable Toggle Mute

### ISSUE THREAD

**Issue by asdfmonster261** [mwittrien/BetterDiscordAddons#1117]
**Describe the solution you'd like**
A configurable hotkey to mute a specific person in a group call.

**Describe alternatives you've considered**
I've considered the shortcut to globally deafen myself, however this doesn't work in the middle of a game with a teammate who won't stop screaming, while needing to hear the rest of the team.

**Additional context**
Ideally, the plugin would appear in one of the normal menus that show up in a group call, you'd select the plugin button, select the person, and then select which key mutes them

**Comment by mwittrien** [comment]
I am not open for plugin requests
