### ISSUE TITLE
[BUG] - RemoveBlockedUsers - Errors/crash when processing deleted message with reaction(s)

### ISSUE THREAD

**Issue by QuickNET-Tech** [mwittrien/BetterDiscordAddons#1118]
**Describe the bug**
Many "Uncaught (in promise)" errors when entering a channel with deleted messages that have reactions which crashes Powercord

**To Reproduce**
Annoyingly I've not been able to consistently reproduce the issue

**Expected behavior**
The client to not crash/no errors in the log

**Screenshots**
Here's an example of the error in the console
![image](https://user-images.githubusercontent.com/23668071/135723561-7890d332-0ba3-4865-8bcc-d20a9b84edb9.png)

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**
Seems to only be an issue when used alongside a message logger

**Comment by mwittrien** [comment]
My Plugins dont work on Powrercore
