### ISSUE TITLE
Issue with BetterFriendCount

### ISSUE THREAD

**Issue by williamjcm** [mwittrien/BetterDiscordAddons#112]
The pending friend count is duplicated:
![image](https://user-images.githubusercontent.com/13572456/44174934-f056ad00-a0e4-11e8-8e81-77aacaac9a6c.png)

**Comment by mwittrien** [comment]
first number is incoming, second number is outgoing

**Comment by williamjcm** [comment]
Oh. Sorry for disturbing you, then.
