### ISSUE TITLE
[BUG] - RemoveBlockedUsers+ServerDetails guild list scrolling performance issue

### ISSUE THREAD

**Issue by Adenser** [mwittrien/BetterDiscordAddons#1120]
**Describe the bug**
When both RemoveBlockedUsers and ServerDetails are enabled in the plugins they cause the guild list to lag from time to time while scrolling, and on servers where there is a lot of channels, it lags too.

**To Reproduce**
Enable both RemoveBlockedUsers v1.3.3 and ServerDetails v1.0.9

**Expected behavior**
Smooth scrolling

**Screenshots**
https://user-images.githubusercontent.com/39248856/135881128-368ec4ad-8749-4be5-88aa-c00d57a5b313.mp4

**Discord Build (stable, ptb or canary):**
Stable 100054 (69f0658)
BetterDiscord 1.2.1
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Additional context**
None.

**Comment by mwittrien** [comment]
#1105
