### ISSUE TITLE
[BUG] - Server Columns theme

### ISSUE THREAD

**Issue by Mika-Kyubi** [mwittrien/BetterDiscordAddons#1127]
**Describe the bug**
Regardless of the number of columns specified in the .css file, Discord refuses to columnize the servers in question, but DOES pad the horizontal space appropriate.

**To Reproduce**
The bug occurs upon starting and/or restarting Discord.

**Expected behavior**
There should be a number of vertical columns equal to the number specified in the .css (default 3, I run 2)

**Screenshots**
![Discord Scereenshot](https://user-images.githubusercontent.com/87213906/136485985-03ba7275-9e47-4c83-861d-33170c4af2f8.png)
https://www.dropbox.com/s/ghsx0gg7jiagd8c/Discord%20Scereenshot.png?dl=0

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
No additional information I can think to provide at this time.

**Comment by Scraft161** [comment]
+1 similar bug likely from same source
![image](https://user-images.githubusercontent.com/19813118/136548314-9b44ded7-6cce-44e7-9240-9811b5530580.png)

I think this originates with icon-position not being set properly (I'm on canary BTW)
