### ISSUE TITLE
[BUG] - Server Folders has become broken with most recent update

### ISSUE THREAD

**Issue by meap02** [mwittrien/BetterDiscordAddons#1129]
**Describe the bug**
The plugin seems to be completely disabled and also creates a large grey box to the right of the server's column with a header that says "React Component Error" in red text.

**To Reproduce**
Occurs on startup of the app on Windows 10 64-bit with only server folders and the BDFDB plugin enabled. 

**Expected behavior**
Expected to be able to use the plugin to organize my servers

**Screenshots**
![image](https://user-images.githubusercontent.com/79549780/136499386-725633e7-d71b-4cc9-be07-5c3d54407f4f.png)

**Discord Build (stable, ptb or canary):**
On Discord Stable 100673 (eae9a45) and Better Discord 1.2.1

**Comment by JacksonFrost13** [comment]
+1 for this problem, same stuff

Discord Stable 100673 (eae9a45)
BetterDiscord 1.2.1

**Comment by Corentin-Rougeon** [comment]
Same here

stable 100673 (eae9a45)
BetterDiscord 1.2.1
