### ISSUE TITLE
ServerFolders (BD v1) v5.7.5 Broken on new update

### ISSUE THREAD

**Issue by Favna** [mwittrien/BetterDiscordAddons#113]
As stated on the title. The servers are put into the folders but the folders are not visible in the server list. This appears to be since the update to stable yesterday. 

With and without ServerFolders enabled:

<div align="center">

<img src="https://favna.s-ul.eu/kvswUBLh.png" align="middle"><span align="middle"> <-- With | Without --> </span><img src="https://favna.s-ul.eu/DqZP0lWe.png" align="middle">

</div>

Expected screenshot 1 but with folders below last server

Tried reinstalling BD, using Zere's fork with Bandaged BD Installer but to no avail.

**Comment by Favna** [comment]
Why was this issue closed? No commits were made to the plugin.

**Comment by mwittrien** [comment]
Because its working

**Comment by Favna** [comment]
Okay so I did some more testing and such and I seem to have been able to determine the issue, namely the recent update for [HideServersChannelsRedux](https://github.com/Arashiryuu/crap/tree/master/ToastIntegrated/HideServersChannelsRedux). With this plugin enabled the issue as stated above does occur (folders are there but are not visible) however when disabling it the Server Folders work perfectly fine as intended.

Do you think you could maybe work something out with @ToastIntegrated to get the plugins to be properly compatible with one another? 

His previous version, 1.0.0 ([commit hash](https://github.com/Arashiryuu/crap/commit/5265ce5cd76839ac727f2ae1c0d4e80273f66d4b#diff-1138c0138a7c84b600f7966f75bf9236)) did not have this issue

**Comment by mwittrien** [comment]
Youll have to tell Arash to fix his plugin then, it's his causing the problem not mine

**Comment by Arashiryuu** [comment]
It's actually a css conflict, you use a `.closed` class, and in the recent update to my plugin, so do I, easily remedied.
