### ISSUE TITLE
[BUG] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by DaTweaks** [mwittrien/BetterDiscordAddons#1149]
**Describe the bug**
Users disappear from the members list

**To Reproduce**
Click on any member in the members list one person will dissapear

**Expected behavior**
nothing out of the ordinary should happen.

**Screenshots**
Before
![before](https://user-images.githubusercontent.com/51744514/136991861-f01f0a7f-e9a4-4edf-bb90-5738246a4239.png)
After
![before](https://user-images.githubusercontent.com/51744514/136992335-13383add-7c3b-4493-a515-e5c6ffdfeffa.png)

**Discord Build (stable, ptb or canary):**
stable

**Comment by vylryna** [comment]
having the same issue

**Comment by mwittrien** [comment]
Still unable to reproduce this
