### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by gahtv** [mwittrien/BetterDiscordAddons#1160]
**Describe the solution you'd like**
Microsoft with the latest insider preview of Windows 11 introduced a new style of emojis.
![image](https://user-images.githubusercontent.com/20805878/137610286-c94b4890-07f4-41b0-9600-c210b5e7d51c.png)
I think there should be a new option to switch the emoji from the old emoji design to the new one, and vice versa, considering both are supported still.

**Comment by Jack5079** [comment]
The new emojis are now on Emojipedia: https://emojipedia.org/microsoft/
