### ISSUE TITLE
[BUG] - ThemeRepo crashes discord when trying to download a theme on Linux

### ISSUE THREAD

**Issue by Pokeduel** [mwittrien/BetterDiscordAddons#1163]
**Describe the bug**
When attempting to download a Theme or Plugin from either plugins, nothing downloads and discord crashes

**To Reproduce**
Install ThemeRepo
Try downloading a theme

**Expected behavior**
Theme successfully installs without crash

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Unsure if this would matter, but this is happening on Arch Linux specifically, havent tested on other distros

**Comment by mwittrien** [comment]
Crash should be fixed with BDFDB 1.9.3
