### ISSUE TITLE
[BUG] - Show Hidden Channels no longer works

### ISSUE THREAD

**Issue by GoldenChrysus** [mwittrien/BetterDiscordAddons#1165]
**Describe the bug**
Show Hidden Channels is enabled but hidden channels are not visible.

**To Reproduce**
Upgrade library to 1.9.3.

**Expected behavior**
Hidden channels should be visible in channel list.

**Screenshots**
N/A for privacy.

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Downgrading to library 1.9.2 resolves.

**Comment by toast356** [comment]
Had the same issue, fixed it by restarting the plugin.
