### ISSUE TITLE
[BUG] - SERVERDETAILS STILL BROKEN

### ISSUE THREAD

**Issue by kubo6472** [mwittrien/BetterDiscordAddons#1167]
#1128 still does not work as of today, even though the issue was closed yesterday. 1.0.9

**Comment by kubo6472** [comment]
> > Works just fine for me Make sure your BDFDB is up to date and make sure you reloaded Discord at least once
> 
> My BDFDB plugin is already update to the newest version(v1.9.4). Reloaded Discord several times and the issue still present. The workaround is right-click server icon first, then left-click.

Can confirm, that's why I opened this issue, bc. some update went thru and everything was at the newest version. @mwittrien can you reopen then, or what should we do.

**Comment by mwittrien** [comment]
What are you talking about? Servers not being clickable?

As far as i heard thats an issue with TypingIndicators

**Comment by kubo6472** [comment]
> As far as i heard thats an issue with TypingIndicators

I do have the TypingIndicators installed, but I isolated the problem multiple times to be caused entirely by ServerDetails which by itself did not receive any update. So I am continuing to experience this issue even with just that single plugin installed.
