### ISSUE TITLE
[BUG] - DM photo

### ISSUE THREAD

**Issue by Longshot133** [mwittrien/BetterDiscordAddons#1172]
**Describe the bug**
When I receive a dm from a user i have changed the icon of their dm photo is unchanged.

**To Reproduce**
Be dm'd by someone with changed photo?

**Expected behavior**
profile picture in notification icon will be different than wanted.

**Screenshots**
Wanted: https://imgur.com/vqkYc1p
Have: https://imgur.com/EpxV87v

**Discord Build (stable, ptb or canary):**
Stable 101857 (a3f9e47)
BetterDiscord 1.2.1

**Additional context**
i cri

**Comment by mwittrien** [comment]
I was fully aware that the issue was about EditUsers

**Comment by SmolAlli** [comment]
> 
> 
> I was fully aware that the issue was about EditUsers

I was saying it more as a courtesy thing so they know to do it, rather than pointing it out.
