### ISSUE TITLE
[BUG] - ServerColumns - Columns forced into one

### ISSUE THREAD

**Issue by IkeFanboy64** [mwittrien/BetterDiscordAddons#1196]
**Describe the bug**
Can't get more than one column. Any other settings only causes blank space.

**To Reproduce**
Happens whenever ServerColumns is active.

**Expected behavior**
Servers should be in more than one columns instead of just creating a gap.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/92172758/139130532-e11429f7-4e7b-4c55-9ba7-05fb97b84e32.PNG)

**Discord Build (stable, ptb or canary):**
Stable 102646 (f7c5ccb)

**Comment by coniie** [comment]
Same bug now present and reproduceable in following:

Stable 103145 (10960f2)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

Canary 103173 (80c1b44)
BetterDiscord 1.2.4
Host 1.0.42 Windows 10 64-Bit (10.0.19043)
