### ISSUE TITLE
[IMPROVEMENT] - BDFDB - Rust rewrite 

### ISSUE THREAD

**Issue by smartfrigde** [mwittrien/BetterDiscordAddons#1203]
**Describe the solution you'd like**
I really want to see BDFDB to be wasm. Rust is language that's really good for this task. I think everyone would benefit with this, it would speedup the plugins. 
**Describe alternatives you've considered**
Possible rewrite in some other way🤔
**Additional context**
https://rustwasm.github.io/docs/book/
https://developer.ibm.com/articles/why-webassembly-and-rust-together-improve-nodejs-performance/

**Comment by E-boi** [comment]
I would like this too.

**Comment by Ruthenic** [comment]
Do you think a suitable alternative would be a rewrite for [hell.js](https://github.com/hell-js/hell.js)?

**Comment by phorcys420** [comment]
z

**Comment by mwittrien** [comment]
No
