### ISSUE TITLE
[BUG] - ServerCounter

### ISSUE THREAD

**Issue by huangdangwibu** [mwittrien/BetterDiscordAddons#1204]
**Describe the bug**
Switching servers/opening and closing folders cause the server column to behave unexpectedly

**To Reproduce**
-Open a server on top of server list
-Scroll down and choose another server
Also applicable with folders

**Expected behavior**
Server switches normally

**Screenshots**
https://gyazo.com/8f07d7229ecf92827d98ba45d412286d

**Discord Build (stable, ptb or canary):**
Stable 103016 (54edf1f)

**Comment by mwittrien** [comment]
#1131
