### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications - Notification position

### ISSUE THREAD

**Issue by Apceniy** [mwittrien/BetterDiscordAddons#1205]
**Describe the solution you'd like**
I would like notifications to be a little lower so they'll cover the role name instead of the interaction area (search etc.)
Currently it's a little annoying to be interrupted by a notification.

**Describe alternatives you've considered**
I could apply custom CSS for myself, but I think other people could agree with me

**Additional context**
![image](https://user-images.githubusercontent.com/53149450/139595112-e3220e2b-08b3-4d84-b1f4-bbfdd54b845c.png)

**Comment by mwittrien** [comment]
Use css then
