### ISSUE TITLE
[BUG] - ServerColumns

### ISSUE THREAD

**Issue by coniie** [mwittrien/BetterDiscordAddons#1208]
Duplicate of https://github.com/mwittrien/BetterDiscordAddons/issues/1196#issue-1037767948 

**Describe the bug**
Server Columns forced into single list while leaving blank space for specified amount of columns. 

**To Reproduce**
Install &/or set columns. Present on all configurations.

**Expected behavior**
Specified amount of columns for servers.

**Screenshots**
https://gyazo.com/121cdb52e5b141add8ed66acb29fd35d
https://gyazo.com/9f82c797d11ec1b26bd325ea76a7a7f7

**Discord Build (stable, ptb or canary):**
Tested and reproduced on:
Stable 103145 (10960f2)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

Canary 103173 (80c1b44)
BetterDiscord 1.2.4
Host 1.0.42 Windows 10 64-Bit (10.0.19043)

**Additional context**
Duplicate of https://github.com/mwittrien/BetterDiscordAddons/issues/1196#issue-1037767948

**Comment by coniie** [comment]
Issue self resolved on following:

Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

Canary 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.42 Windows 10 64-Bit (10.0.19043)

Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 0.0.16
Linux 64-Bit (5.14.0-Kali2-Amd64)

**Comment by Andrew6rant** [comment]
I am getting this issue on:

Stable 103301 (17b3d14)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)
