### ISSUE TITLE
[BUG] - ServerDetails

### ISSUE THREAD

**Issue by zLucPlayZ** [mwittrien/BetterDiscordAddons#1209]
**Describe the bug**
I cannot click servers anymore with the ServerDetails plugin enabled, hover and everything else works just fine, but not clicking them. Reordering them, doesnt work aswell.

**To Reproduce**
Enable ServerDetails, try to click a server.

**Expected behavior**
It should be click and draggable.

**Screenshots**
None

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
None

**Comment by mwittrien** [comment]
#1131
