### ISSUE TITLE
[BUG] - ServerHider no longer functional

### ISSUE THREAD

**Issue by Maximilian1271** [mwittrien/BetterDiscordAddons#1213]
**Describe the bug**
After todays fix to #1207, which indeed fixed the "React component error" message from appearing, now the plugin just straight up no longer works without throwing any sort of error whatsoever. (also checked the javascript console for errors. There are none).
The plugin itself still loads. Submenus belonging to the plugin still get created. Only when trying to actually hide a server (either via "rclick"->"server visibility"->"hide server" or "manage server list"), discord freezes for about 5-10 seconds, after which it does not hide the server.
Additionally, the toggles in the "Managing Server List" list do toggle between different states, but again: it does not actually affect the visibility of any given server in the discord server listing.

**To Reproduce**
Toggle server visibility on or off, using the latest serverHider.plugin.js

**Discord Build (stable, ptb or canary):**
Stable 103410

**Comment by bentepper** [comment]
Having the same issue here
