### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels - Possible toggles/changes to folders in the plugin

### ISSUE THREAD

**Issue by Pr0tatoCode** [mwittrien/BetterDiscordAddons#1216]
**Describe the solution you'd like**
For folders, while they are visible, they don't really stand out. So I'm here to suggest a few ideas in regards to that to change it and maybe make it more fluid. 

**Suggestion 1: Configurable/Togglable Indent to servers inside a folder**
As seen in the screenshot below, I've drawn an arrow to where I think a default indent for servers in the folder should be. You would obviously make the final call but that's just the example point. With this though, like the width of the server lists themselves, I believe it should be not only configurable in the same way, but also togglable so those who want it can have it on and those that don't can have it off.

**Suggestion 2: Background of folders should be 0.1 alpha of the folder's color to better identify it's IN the folder**
While my friend and I were looking through the code (which we have no prior experience with as we are not too skilled in javascript (and Discord-related JS), we found the alpha value for just the folder in the server list itself as 0.2. After testing multiple different numbers there, we came to the conclusion that 0.1 is the perfect in-between on the alpha to show the color of the folder while making it visible better on people with lower screen brightness. I think this should be applied to the background of both the server tab and just the background of the folder to better identify that it's IN the folder. An example of the 0.1 alpha and where I believe it should be applied can be seen in the second screenshot under additional context.

You can tweak the alpha as you please but I found that 0.1 was best for the server tabs (I did not do testing for the actual background itself but I believe based on the normal background colors that since it will most likely be overlayed, it will take on the brightness of the color under it).

**Describe alternatives you've considered**
My friend and I have personally tried tweaking the code (we have little to no experience it was a mess) and got nowhere with it.

**Additional context**
![image](https://user-images.githubusercontent.com/10455667/140540932-160eb538-7ae0-4864-9ced-e940a8357e4b.png)
![image](https://user-images.githubusercontent.com/10455667/140542857-a45d9602-7045-4d57-a011-7c1c11119e12.png)

**Comment by mwittrien** [comment]
How is the big folder icon and colored background not enough to visibily indicate a folder?
The servers inside a folder are grouped by the expanded background, thats how its also handled in native discord
