### ISSUE TITLE
[BUG] - ServerHider now buggy. Causes server list to jump, "public" button to disappear

### ISSUE THREAD

**Issue by Maximilian1271** [mwittrien/BetterDiscordAddons#1220]
First of all, I'm sorry for nitpicking about serverHider so much. I know I'm getting annoying with this, but i still feel this needs to be addressed.
<hr>

**Describe the bug**
After todays fix for #1213 (commit: dfe61ea), the plugin seems to be working again. However, now it causes a new problem. When clicking any non hidden server, the "public" button (situated underneath the "home" button) disappears temporarily, causing the server list to "jump" up, then re-appears again, causing the server list to "jump" down again. I have recorded and attached a video of this happening and annotated it with comments, describing the issue in real time.
The first 15 seconds of the video shows the issue does not appear when serverHider.plugin.js is disabled.

**To Reproduce**
Enable "serverHider.plugin.js" -> Hide some but not all servers -> click any still visible server in the server list. The "public" button should disappear for about 1 second, causing the entire server list to move vertical position. The "public" button should then re-appear, causing the server list to again, move vertical position.

**Expected behavior**
The server list should not move upon clicking any server and the "public" button should remain visible at all times.

**Screenshots**
A video describing and depicting the issue is attached. Please excuse the heavy blurring of personal details.

**Discord Build (stable, ptb or canary):**
Stable 103981

<hr>

https://user-images.githubusercontent.com/1573345/140978512-74b4ac17-9c43-456d-b459-b26063d9ebb2.mp4

**Comment by mwittrien** [comment]
#1131
