### ISSUE TITLE
[BUG] - PLUGIN Broken

### ISSUE THREAD

**Issue by megaEDD** [mwittrien/BetterDiscordAddons#1223]
**Describe the bug**
NotificationSounds does not work at all 

**To Reproduce**
just try using it 

**Expected behavior**
can't open settings in the plugins menu

**Screenshots**
https://imgur.com/HCDvzc2

**Discord Build (stable, ptb or canary):**
stable 104276 (4adab42)
BetterDiscord 1.2.4

**Additional context**

**Comment by mwittrien** [comment]
Update your BDFDB
