### ISSUE TITLE
[BUG] - EditServers: blurred Icons

### ISSUE THREAD

**Issue by Trixlight** [mwittrien/BetterDiscordAddons#1224]
**Describe the bug**
Custom server icons are blurred.

**To Reproduce**
When I set a custom icon for the server.

**Screenshots**
The first icon is native, the second and third are custom icons.
![Discord_2021-11-11_20-59-24](https://user-images.githubusercontent.com/33410668/141329576-f8a55276-a704-417c-a435-8d3e4bd198b4.png)   ![Discord_2021-11-11_21-01-33](https://user-images.githubusercontent.com/33410668/141329596-b9fc3331-31cd-444c-97fd-33584085e9e0.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Started to occur around September.
It looks like this only happens when the zoom level is 100 (default) ?

**Comment by Trixlight** [comment]
Um, are you sure? I have the latest version of the plugin (2.3.5), but the custom icons are still blurry.
Maybe I can provide you with some additional information?

**Comment by mwittrien** [comment]
100% sure, just tested
