### ISSUE TITLE
[IMPROVEMENT] - SplitLargeMessage

### ISSUE THREAD

**Issue by OshidaBCF** [mwittrien/BetterDiscordAddons#1225]
Add the way to send the messages as a .txt by pressing Ctrl + Enter

I know it's kinda against the purpose of this plugin, but i have a very specific server that have a bot that use those message to detect errors we made

**Comment by mwittrien** [comment]
Disable the plugin then

**Comment by OshidaBCF** [comment]
i mean....

yeah

but you'll agree that disabling the plugin each time i need to send a file on that server is kinda.... dumb ?


well you're not wrong either

**Comment by mwittrien** [comment]
You can use BDContextMenu to quickly disable/enable plugins

**Comment by OshidaBCF** [comment]
what is that ?
