### ISSUE TITLE
[BUG] - PersonalPins - Reaction emoji picker resets when Shift key pressed

### ISSUE THREAD

**Issue by agnesnutter** [mwittrien/BetterDiscordAddons#1228]
**Describe the bug**
The emoji picker will reset (forgetting scroll position) the first time the `shift` key is pressed while picking a reaction emoji.

**To Reproduce**
1. Click the reaction button on a message.
2. Scroll the emoji list (not required, but helps demonstrate).
3. Press, or press and hold, the `shift` key.
4. The emoji picker will reopen, and it will put you back at the top of the list.

**Expected behavior**
Nothing should happen.

**Discord Build (stable, ptb or canary):**
Stable 104967 (c0c4401)
BetterDiscord 1.3.0
macOS 10.15.7

**Additional context**
This comes up because `shift` is necessary for applying multiple reaction emoji in a row.

**Comment by mwittrien** [comment]
Cant be fixed
