### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor

### ISSUE THREAD

**Issue by snek100** [mwittrien/BetterDiscordAddons#1230]
atm the color for when you drag your cursor over a box and the color which the box becomes when selected are the same. this is the color "backgroundaccent". i would like to make these two colors different (grey when dragging over and blue when selected), but this is impossible.

here is a photo of the behavior which i would like to see, and a photo of the behavior which i do see.

![IMG20211118224740](https://user-images.githubusercontent.com/54297927/142566663-1182d593-1764-4028-b705-828cc86c96f9.jpg)

![IMG20211118224704](https://user-images.githubusercontent.com/54297927/142566676-d3ea94ec-4a2d-4ac6-8e3f-4ff077a5b18e.jpg)

**Comment by mwittrien** [comment]
The theme doesnt change the type of color, thats how native discord styles it

They arent the same they are different shades

**Comment by snek100** [comment]
> 

they are different shades but they are based on the same color

**Comment by mwittrien** [comment]
Yes because thats how it is in native discord

**Comment by snek100** [comment]
> 

oh ok sorry for making an issue
