### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by HawksAreNeat** [mwittrien/BetterDiscordAddons#1231]
**Describe the bug**
Clicking on a dm when close folder if opening another folder is enabled makes the folder that is currently open flash like crazy

**To Reproduce**
When does the bug occur.
1 Enable closing a folder when opening another folder
2 Click on dm/group chat
3 Server Folder flashes like crazy
**Expected behavior**
Not for it to flash like crazy
**Screenshots**

![jQamkc5fYV](https://user-images.githubusercontent.com/54047268/142751784-d06e057c-32f4-4f04-9a2e-8332c69ed21e.gif)
**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
1.9004
**Additional context**

**Comment by mwittrien** [comment]
Can u Screenshot your plugin settings

**Comment by HawksAreNeat** [comment]
![image](https://user-images.githubusercontent.com/54047268/143187906-3eb3dce1-90d5-49e9-8f76-a97fb625bf98.png)
