### ISSUE TITLE
[IMPROVEMENT] show alt text in gallery view - Image Utilities

### ISSUE THREAD

**Issue by TheChilliPL** [mwittrien/BetterDiscordAddons#1236]
**Describe the solution you'd like**
I'd love to be able to easily see the image alt text in the gallery/details view of an image

**Describe alternatives you've considered**
Guess it could be shown right below the image in every single message but idk if it's really needed, details view seems like a pretty good place for that. Right now, I believe the only way to see it without DevTools if the image loads correctly is just hovering over the image and waiting for the tooltip.

**Comment by tameTNT** [comment]
This has now been added from what I can see as of v`4.5.8` so this issue can be closed.
