### ISSUE TITLE
[BUG] - NOTIFICATIONSOUNDS

### ISSUE THREAD

**Issue by RinLovesYou** [mwittrien/BetterDiscordAddons#1240]
**Describe the bug**
NotificationSounds offers you the ability to mute sounds. Since i am in hundreds of servers I've been using this for years, so i don't get spammed with the sound of 100 servers getting random messages.
On Linux, the default Message sound, while definitely being changed, also still plays the original. So even after Muting it still plays and is driving me crazy.

**To Reproduce**
Getting a Message on a server plays the default Message sound while having that sounds muted.

**Expected behavior**
No sound should occur

**Screenshots**
![image](https://user-images.githubusercontent.com/29461788/143940449-e707f094-753e-405a-ac83-a9bc6614182b.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I use Linux

**Comment by mwittrien** [comment]
Cant debug it since i got no linux
