### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by ZellsAlpha** [mwittrien/BetterDiscordAddons#1241]
**Describe the bug**
Doesn't load profile banners on startup, you have to disable and re enable the script for it to work

**To Reproduce**

Just starting the client, it doesn't load the actual png links, just blank screen.

**Expected behavior**

Obviously is supposed to load automatically

**Screenshots**

https://i.imgur.com/ydh3vlT.png

**Discord Build (stable, ptb or canary):**

Stable

**Additional context**
Disabling and re enabling the script seems to fix it, so probably an insanely easy fix

**Comment by szymon420699** [comment]
lol thx man i had this for like 2 months and i didnt do anything about it so i waited for a update and there was no update thx
