### ISSUE TITLE
[BUG] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by Ricexer** [mwittrien/BetterDiscordAddons#1242]
**Describe the bug**
In the user lists in servers, it does not work correctly.

**To Reproduce**
Have someone blocked join a server a turn the plugin on.

**Expected behavior**
Hides blocked users.

**Screenshots**
![image](https://user-images.githubusercontent.com/65427824/144572839-4a110edb-444e-4718-ae01-22cb6ff33cdf.png)
When other uses with the same role are on it will hide them too. It also shifts the users down one making them under the wrong role category.
**Discord Build (stable, PTB or canary):**
Latest Version of PTB.

**Additional context**

**Comment by mwittrien** [comment]
#1239
