### ISSUE TITLE
[BUG] - Failed to translate with DeepL

### ISSUE THREAD

**Issue by yungbeatz** [mwittrien/BetterDiscordAddons#1243]
**Describe the bug**
If I choose the DeepL translation, I get the `failed to translate. Try another Translator. Request Limit reached`

**To Reproduce**
This bug occurs every time you try to translate a message with DeepL.

**Expected behavior**
It should translate my messages, but it doesn't. 

**Screenshots**
![unknown](https://user-images.githubusercontent.com/56764505/144719779-bba7b082-0bca-483b-ac11-be5b03477eaa.png)

**Discord Build (stable, PTB or canary):**
I'm using Discord Stable 106905 (1eb8c0f)

**Additional context**
I hope this was enough information!

**Comment by mwittrien** [comment]
Try reading

**Comment by yungbeatz** [comment]
The bug doesn't exist anymore. Did you fix the bug or?

**Comment by mwittrien** [comment]
Read the error msg dude
