### ISSUE TITLE
[BUG] - DiscordRecolor / BlurpleRecolor doesn't change the Discord logo

### ISSUE THREAD

**Issue by kilickerem066** [mwittrien/BetterDiscordAddons#1248]
**Describe the bug**
Does not change the Discord button (on the top-left).

**To Reproduce**
Change the Accentcolor and it happens.

**Expected behavior**
It should change the button to whatever Accentcolor is.

**Screenshots**
![Screenshot_20211207_171956](https://user-images.githubusercontent.com/64794941/145046114-8247bb01-8b1b-4bf3-8462-bfa06769f531.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Stable 107116 (dbb89e4)
BetterDiscord 1.3.0
Host 0.0.16
Linux 64-Bit (5.11.0-41-Generic)

**Comment by mwittrien** [comment]
Looks fine for me

My icon has no snow in it tho

**Comment by kilickerem066** [comment]
there was an update to discord which adds snow to discord button

**Comment by mwittrien** [comment]
Weird dont have that
