### ISSUE TITLE
[BUG] - ShowHiddenChannels/Connect to channel bug

### ISSUE THREAD

**Issue by k1zn** [mwittrien/BetterDiscordAddons#1263]
**Describe the bug**
If you see a hidden channel and then are given access to watch/access it, you will not be able to enter it until you restart Discord (Ctrl + R)

**To Reproduce**
Join a server with a hidden channel, give the account access to this channel

**Expected behavior**
The information that the channel is unavailable should disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/46452865/145714043-c6600420-d4ab-4464-8427-a1ff3eed52c2.png)
![image](https://user-images.githubusercontent.com/46452865/145714067-283768c5-6533-45f1-8deb-82dbcbd5580c.png)

**Discord Build (stable, ptb or canary):**
Stable 107767 (ce27b01)
BetterDiscord 1.3.0

**Comment by dogthepro** [comment]
same issue

**Comment by dogthepro** [comment]
I tried to make an invite link and join using that from normal web client and it's still doesn't work. Maybe it's a feature
