### ISSUE TITLE
[IMPROVEMENT] - PersonalPins

### ISSUE THREAD

**Issue by Nextis-Plus** [mwittrien/BetterDiscordAddons#1264]
Ability to favorite/filter notes further. For example, if I want to pin a meme that I like, I would be able to do so, but not mix it with other important stuff like a moderation message. I think this could greatly help.

**Comment by mwittrien** [comment]
If you are using PersonalPins to frequently use a certain text or image in the Chat you should switch to the ChatAliases plugin which let's you use preset phrases/images via shortcuts in the chat
