### ISSUE TITLE
[IMPROVEMENT] - Image Utilities

### ISSUE THREAD

**Issue by Sertule** [mwittrien/BetterDiscordAddons#1267]
**Describe the solution you'd like**
The ability to view banners with the image actions button.

**Describe alternatives you've considered**
Maybe when you click on the image actions button, it asks if you want to use it for profile pictures or banners.

**Comment by mwittrien** [comment]
ImageUtilities already lets you interact with bannera

**Comment by Sertule** [comment]
Must not work for me anymore, how do you use it again?

**Comment by JadeMin** [comment]
same for me. and even blurs all profile pictures displayed in meber list

**Comment by JadeMin** [comment]
![캡처](https://user-images.githubusercontent.com/36400787/147826914-6f1a6523-491d-4be1-967c-81d663ab1a07.PNG)
![캡처1](https://user-images.githubusercontent.com/36400787/147826917-fbc21da9-c6ff-45b1-89e4-4ab29c21857e.PNG)

**Comment by mwittrien** [comment]
Other plugins fault
