### ISSUE TITLE
[BUG] CustomStatusPresets - Cannot read the status presets and appear as massive images

### ISSUE THREAD

**Issue by haydenfordz** [mwittrien/BetterDiscordAddons#1268]
<img width="1920" alt="Screenshot 2021-12-15 at 10 47 14" src="https://user-images.githubusercontent.com/77495158/146173126-d2ccaeca-ce59-4aa2-abec-9d689c4eaf1e.png">

**Comment by mwittrien** [comment]
Thats your themes fault

**Comment by haydenfordz** [comment]
I have no theme on here?
