### ISSUE TITLE
[BUG] - Remove Blocked Users - Unread Badges Completely Gone

### ISSUE THREAD

**Issue by dottiekh** [mwittrien/BetterDiscordAddons#1270]
**Describe the bug**
With the plugin enabled, all unread badges vanish completely for all Guilds (Servers) excluding @ mentions. 

**To Reproduce**
1. Enable the plugin
2. Unread badges will disappear. 

**Discord Build (stable, ptb or canary):**
Stable

**Comment by kamikazilucas** [comment]
im having the same issue pls fix

**Comment by toxcien** [comment]
same

**Comment by OshidaBCF** [comment]
Same issue here

**Comment by Kinomora** [comment]
can confirm, also experiencing this issue on PTB

**Comment by alterNERDtive** [comment]
Specifically, it seems to be the “Messages Notification” option. Disabled that, dots are back. With the obvious side effects of not having message notifications on channels suppressed.

![image](https://user-images.githubusercontent.com/53827887/146840189-9493dbfe-b65f-45aa-8e34-f596cbfc6a7d.png)

**Comment by kamikazilucas** [comment]
how do you fix?

**Comment by mwittrien** [comment]
By updating the plugin

**Comment by kamikazilucas** [comment]
im not getting any update

**Comment by kamikazilucas** [comment]
the update created a new issue where notification icon doesn't go away when all the channels have been read
