### ISSUE TITLE
[BUG] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by BluAxolotl** [mwittrien/BetterDiscordAddons#1271]
Server member list is messed up.

![image](https://user-images.githubusercontent.com/44180499/146651885-35621c7e-e23c-4927-b921-5e82cd964b73.png)

It's showing a loading member status instead of completely removing the slot. Somettimes it adds more loading slots than there is blocked users.

**Comment by mwittrien** [comment]
#1239
