### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by PaulCubes** [mwittrien/BetterDiscordAddons#1273]
**Describe the bug**
The button constantly shows Game Activity disabled, but it's enabled in the discord settings, clicking the button doesn't update it to show Game Activity enabled, and doesn't change anything in the game activity settings on discord.

**To Reproduce**
Click the Game Activity Toggle button.

**Expected behavior**
The button's texture updates to show Game Activity enabled, and it updates my Game Activity settings in Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/77691976/146909126-48f0678d-02fc-4c28-97f9-271fbb1f759f.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Only started happening after latest discord update.
**Might be** something to do with the new christmas themed nitro gifts, because the nitro gift button flashes as if it's being hovered over whenever the Game Activity Toggle button is pressed.
Restarting the plugin doesn't fix it, restarting discord doesn't fix it, reinstalling/repairing BD doesn't fix it.
Other gameactivitytoggle plugin also has the exact same problem.

**Comment by wilecoyote** [comment]
Same here.  The functionality is broken after the latest discord updates (it happens on all 3 clients. stable, ptb and canary)

**Comment by IamNickerson** [comment]
Same here. It kept disabled. Btw it happen after an update I had.

**Comment by FelSCoM** [comment]
I hope they will fix it soon

**Comment by poorloading** [comment]
same here

**Comment by Adelscott** [comment]
Sorry for asking (in case I'm blind) but is it really fixed ? I still have the bug after manually updating and I don't see any code change since 5 days (https://github.com/mwittrien/BetterDiscordAddons/commit/6b9fd69231d5a23aaf2fc0c961a56562e259d714)

**Comment by mwittrien** [comment]
By updating the plugin

**Comment by Jusp3** [comment]
Still not working it changes the look but doesnt function right

**Comment by JelCraft** [comment]
Can confirm that in the latest update the button visually and audibly updates correctly, but the actual activity status is not being updated.

**Comment by Adelscott** [comment]
1.0.5 seemed to work last night, or at least the icon was changing.
1.0.6 does nothing except the same sound

**Comment by Jnss98b** [comment]
It's broken again on latest discord with 1.0.6
