### ISSUE TITLE
[BUG] - GameActivityToggle not working

### ISSUE THREAD

**Issue by Adelscott** [mwittrien/BetterDiscordAddons#1274]
**Describe the bug**
Icon always showing a striked gamepad. But no effect on status when clicking (triggers the sound though)

**To Reproduce**
When does the bug occur : always

**Expected behavior**
Hide/Show playing game

**Screenshots**
![image](https://user-images.githubusercontent.com/10946454/147156356-520bb95b-b0d9-4c4a-8777-f0b63cc2f011.png)

**Discord Build (stable, ptb or canary):**
Stable 108924 (eb8c571)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

![image](https://user-images.githubusercontent.com/10946454/147156465-fc1d3e96-4124-4ea2-bc03-e7a8aaee713a.png)

**Comment by mwittrien** [comment]
#1273
