### ISSUE TITLE
[BUG] - ImageUtilities.plugin - Language failed to apply properly.

### ISSUE THREAD

**Issue by Bass-PHOX** [mwittrien/BetterDiscordAddons#1276]
[Description]
My French friend reports that the language file for the French language did not apply properly. Proof of this can be seen in the embedded image. 

[Reproduction]
When the language is set to French, open any image using ImageUtilities.

[Expected Behavior]
The options for "Open Original", "Save image as...", "Copy image", and "Zoom settings" should appear in French.

[Screenshots]
My friend showing the bug affecting their application.
![image](https://user-images.githubusercontent.com/87764384/147212036-12446c19-9a2b-416d-b541-a7e8a8c53255.png)
My friend explaining the issue having greater effect than shown.
![image](https://user-images.githubusercontent.com/87764384/147212483-1dcff9b6-6691-443b-83a4-9a2265d83d10.png)

[Used Discord Build]
My friend uses the latest Canary build.

[Additional context]
We had just updated our clients, plugins and libraries to the latest version.
My friend also states the following:
> "Well it's more that zoom settings is a wrong translation.
> It should be 'Paramètres du Zoom', and not 'Zoom Paramètres'."

**Comment by mwittrien** [comment]
They most likely changed languages

Reload after changing the language
