### ISSUE TITLE
[BUG] - GameActivityToggle - broken

### ISSUE THREAD

**Issue by TomPecs** [mwittrien/BetterDiscordAddons#1277]
Describe the bug
The button is working as should... you can toggle. But doesn't work behind so still showing the activity. (fresh v1.0.5)

To Reproduce
Click the Game Activity Toggle button.

Expected behavior
The button's texture updates to show Game Activity enabled, and it updates my Game Activity settings in Discord.

Discord Build (stable, ptb or canary):
Stable

Additional text
Thank you all your hard work, you are awesome :)

**Comment by faaaaq** [comment]
Using the current "fixed" version the button just straight doesnt even show for me now
