### ISSUE TITLE
[BUG] - BDFDB - Incredibly High CPU usage after updating yesterday

### ISSUE THREAD

**Issue by Eeveelution** [mwittrien/BetterDiscordAddons#1278]
**Describe the bug**
Ive been prompted to update BDFDB and since then instead of discord running at 0.6% CPU it just casually uses over 20%

**To Reproduce**
Litearlly have BDFDB installed and enabled

**Expected behavior**
I expect it to not take up 20% more CPU than usual, makes discord very unusable

**Screenshots**
With BDFDB enabled and scrolling past messages:
![image](https://user-images.githubusercontent.com/33634370/147235308-e4b61175-55fb-4fab-b767-10192858de9b.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None to add

**Comment by mwittrien** [comment]
Havent changed anything in that regard and cant reproduce

**Comment by Eeveelution** [comment]
bruh, ig thanks for making bd unusable for me

**Comment by AshleyGainey** [comment]
Happening to me and to many other people in the BetterDiscord Discord Server. @Eeveelution seems to be If you have RemoveBlockedUsers then there is a heavy spike in CPU usage. Disable/Delete it for now and you should be fine.

**Comment by Eeveelution** [comment]
That's the 1 plugin I want the most and it's the one making it unusable, pain
