### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by ZachFett** [mwittrien/BetterDiscordAddons#1279]
**Describe the bug**
Game Activity icon always shows that it's disabled, clicking the icon neither enables or disables the setting.

**To Reproduce**
Enable the plugin.

**Screenshots**
<img width="92" alt="Discord_HyN6ZWM0aM" src="https://user-images.githubusercontent.com/29797689/147323857-05851967-d6ee-4298-a752-59805ba07a0f.png">

**Discord Build (stable, ptb or canary):**
Stable 108924 (eb8c571)
BetterDiscord 1.3.0

**Comment by TheFollenBest** [comment]
Same

**Comment by foreA-adoxid** [comment]
same
![image](https://user-images.githubusercontent.com/72875762/147350197-9491f1af-b048-4637-a542-58bb92cb67f2.png)
