### ISSUE TITLE
Server Folders icons break easily

### ISSUE THREAD

**Issue by easyink** [mwittrien/BetterDiscordAddons#128]
The server folders plugin appears to function however upon configuring the colors of a folder or setting up a custom image for them will cause that selection to overwrite other folders upon opening them.
Attempting to reset the settings of those server folders changes nothing.

**Comment by mwittrien** [comment]
Everything works fine for me

What exactly are the steps to recreate the issue

**Comment by dexman545** [comment]
I have a similar problem after the recent BBD update (also had duplicate folders). I fixed it by deleting the folder in DS, then opening up the settings file and deleting the folders there. After that, when I remade the folders everything worked fine - until I opened a folder. At that point, the other folders took on the same appearance as the last created folder.

**Comment by mwittrien** [comment]
> I have a similar problem after the recent BBD update (also had duplicate folders). I thought I fixed it by deleting the folder in DS, then opening up the settings file and deleting the folders there. After that, when I remade the folders everything worked fine - until I opened a folder. At that point, the other folders took on the same appearance as the last created folder.
> 
> Edit: Seems like there's an issue with how it's saving the folder settings. Just remade all the folders and restarted DS without opening a folder, and all the icon/settings info was set to the last made folder's.
> Running the "check for updates" in BD for plugins does not show this plugin needing an update.
> 
> Edit: not all settings are being changed, just the icon settings. Tooltip font colour and text are still the same.

Thanks for the description, I could recreate the issue and fixed it in 5.8.1

**Comment by dexman545** [comment]
glad it helped, thanks for fixing it!
