### ISSUE TITLE
[BUG] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by a1337spy** [mwittrien/BetterDiscordAddons#1280]
**Describe the bug**
When using RemoveBlockedUsers, unread notifications in servers do not disappear when the servers are read unless I refresh Discord, which makes it seem as if the unread notifier is overlaid on top of the hover over selection. Alongside this, RemoveBlockedUsers also causes increasing slowdowns on the client unless I also refresh the program.

**To Reproduce**
These bugs occur during casual use.

**Expected behavior**
No slowdowns along with the unread message notifier disappearing.

**Screenshots**
[Attached is a .mp4 file showcasing unread notification bug in question.](https://user-images.githubusercontent.com/5660399/147422359-d66b47ef-f4dc-4f08-b1be-992584bf91db.mp4)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Earlier I saw that this bug was reported previously and said bug was labelled as fixed. However, the bug still remains on my end with both RemoveBlockedUsers and BDFDB up to date.

**Comment by mwittrien** [comment]
What version are BDFDB and RemoveBlockedUsers

**Comment by a1337spy** [comment]
RemoveBlockedUsers is on version 1.3.6.
BDFDB is on version 2.0.3.

**Comment by mwittrien** [comment]
Works fine for me

**Comment by a1337spy** [comment]
Reinstalled RemoveBlockedUsers and BDFDB, it's working fine for now.

Thank you for your time.

**Comment by borntohonk** [comment]
BDFDB 2.0.3 and 1.3.6 here, will make server notifications never go away.

have tried on canary/PTB/stable, only way to make notifications go away is to restart the discord client (disabling remove blocked users is not sufficient.)

**Comment by Vitoire** [comment]
Having very much the same issue on two particular servers of mine. BDFDB 2.0.3, RBU 1.3.6 - on Stable. I am wondering if this is connected to ServerFolders in some way, because both of the servers that have permanent unread notifications are in a folder. My ServerFolders version is 6.9.8 - not sure if it's related, but I thought I would put it out there.
