### ISSUE TITLE
[BUG] - Game Activity Toggle 1.0.6/does not work

### ISSUE THREAD

**Issue by FelSCoM** [mwittrien/BetterDiscordAddons#1282]

**Comment by FelSCoM** [comment]
plugin list
![image](https://user-images.githubusercontent.com/88301609/147445618-74a8e6c8-4acd-44e3-b08a-a51c7825a42f.png)
![image](https://user-images.githubusercontent.com/88301609/147445666-8d35c89e-4b3f-45fa-ab90-72b298709720.png)

**Comment by FelSCoM** [comment]
nothing happens when the button is pressed

**Comment by mwittrien** [comment]
Your BDFDB plugin is outdated

**Comment by FelSCoM** [comment]
exactly a plugin of the old version, usually updated itself

**Comment by FelSCoM** [comment]
updated it manually and it worked! Thank you
