### ISSUE TITLE
[BUG] - Game Activity Toggle

### ISSUE THREAD

**Issue by The-Mighty-Spoon** [mwittrien/BetterDiscordAddons#1284]
**Describe the bug**
The Game activity toggle button does not change when clicked nor does it seem to actually change the show game activity status.

**To Reproduce**
Click the game activity toggle button.

**Expected behavior**
Switch from having a red strike to not having one and vice versa and to change the game activity to on/off.

**Discord Build**
Stable.

**Comment by poorloading** [comment]
same here, it did work for a bit after an update but then broke again and hasn't worked since.

**Comment by mwittrien** [comment]
Update BDFDB ....
