### ISSUE TITLE
[BUG] - GameActivityToggle is still broken, button does nothing

### ISSUE THREAD

**Issue by demux4555** [mwittrien/BetterDiscordAddons#1286]
**Describe the bug**
The button shows that activity status is disabled (even if enabled manually in Discord settings), and clicking the button does nothing. 

**To Reproduce**
Click the GameActivityToggle button.

**Expected behavior**
GameActivityToggle should toggle game activity. But it doesnt.

**Discord Build (stable, ptb or canary):**
Stable 108924 (eb8c571)

**Additional context**
I see this issue has been posted before, but it's been closed and marked as solved, when it's apparently not.

**Comment by mwittrien** [comment]
Uodate BDFDB
