### ISSUE TITLE
[BUG] - Game Activity Toggle strikethrough does not appear immediately

### ISSUE THREAD

**Issue by smhsketch** [mwittrien/BetterDiscordAddons#1287]
**Describe the bug**
Game Activity Toggle red strike-through indicator only appears/disappears once the button is no longer being hovered over

**To Reproduce**
Using latest version of both the Game Activity Toggle and BDFDB plugins, simply click the toggle button and do not immediately move the mouse

**Expected behavior**
Strikethrough indicator appears/disappears immediately when clicked, behaving like the mute and deafen buttons

**Discord Build (stable, ptb or canary):**
Stable

https://user-images.githubusercontent.com/38465129/147613709-6d0e3dba-efb1-41f4-8f62-90dc14e36bd7.mov

**Comment by JelCraft** [comment]
The activity status switch was not working at all, just the button (after removing cursor from it). It's been fixed with the last update.
