### ISSUE TITLE
[BUG] - GameActivityToggle's toggle is stuck

### ISSUE THREAD

**Issue by brian6932** [mwittrien/BetterDiscordAddons#1288]
**Describe the bug**
Pressing the toggle does nothing, it makes the toggle noise, but does not change my status nor does the icon change

**Expected behavior**
It should toggle lol

**Screenshots**
Console Logs:
![image_87](https://user-images.githubusercontent.com/18603393/147629263-3ea0690f-b14c-4400-96f9-8319a945915e.png)
Demo:
![demo](https://user-images.githubusercontent.com/18603393/147630060-8335accd-add7-4de1-975c-c24eec136ddf.gif)

**Discord Build (stable, ptb or canary):**
Stable 108924 (eb8c571)
BetterDiscord 1.3.0
Host 1.0.9003
Windows 10 64-Bit

**Plugin Build:**
v1.0.6

**Additional context**
I can't seem to get it to fix, client restarts don't fix it either, it just seems to be stuck
It seems like even after disabling the BD plugin, that my rich presence still doesn't come back either

**Comment by HELLSNAKES** [comment]
I also got the same error

**Comment by mwittrien** [comment]
Your BDFDB isnt up to date
