### ISSUE TITLE
[BUG] - Game Activity Toggle

### ISSUE THREAD

**Issue by AndreZila01** [mwittrien/BetterDiscordAddons#1289]
**Describe the bug**
If i click in "button" enable game activity, send information about game i playing. 

**To Reproduce**
When click on button.

![image](https://user-images.githubusercontent.com/56931353/147658096-932d9cec-2a74-4788-b6a8-53b8921742a2.png)

https://user-images.githubusercontent.com/56931353/147659382-dbc7aa03-2eb9-4e02-aa33-3ee6330a13f6.mp4

**Comment by IFD3** [comment]
Having the same issue since a couple of days.
