### ISSUE TITLE
Help: where do personal pins save?

### ISSUE THREAD

**Issue by N72826** [mwittrien/BetterDiscordAddons#1290]
could you point me in the direction of where the personal pins save locally? I recently reinstalled windows and made a backup of my plugins folder including the corresponding configs but personal pins seems to have been wiped. thanks.

**Comment by mwittrien** [comment]
PersonalPins.config.json

**Comment by N72826** [comment]
> PersonalPins.config.json Copy it in your plugins folder while discord is closed

wow thank you that was extremely fast. that was probably the issue. I will let you know, if not, it's ok. I appreciate how fast you responded.
