### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities - add the ability to load larger previews in channels.

### ISSUE THREAD

**Issue by N72826** [mwittrien/BetterDiscordAddons#1293]
**Describe the solution you'd like**
If reasonable, I would like to be able to enable full resolution image loading as well as the ability to scale images to be sharper and the ability to enable the resizing of images/videos to take up more space in a channel. thank you for all your hard work.

**Describe alternatives you've considered**
I have been stuck between your ImageUtilities plugin and [BetterImageViewer ](https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/BetterImageViewer/BetterImageViewer.plugin.js)for as long as I can remember. You share a lot of features, but the only thing keeping me with BetterImageViewer is the ability to load full res images and the ability to enable larger images in the channels.

**Additional context**
![image](https://user-images.githubusercontent.com/21070431/147859240-1579bdc8-bf3c-48aa-9f83-5b0bbe014aa9.png)
![image](https://user-images.githubusercontent.com/21070431/147859243-c33ed68e-5d98-4ca7-a75f-7dacd8726830.png)

**Comment by GenesisAria** [comment]
At the very least, it would be preferable to have the images use their correct size.  If you look at the source for how they're put into frame, they're always referenced a different scale from sever than in the frame, which makes them always a bit blurry.

![Developer_Tools_-_httpsdiscord comchannels897 (2022-02-10_14-59-16)](https://user-images.githubusercontent.com/25147974/153511052-7c9155ae-1727-4a37-81bf-0042a71bd855.png)

**Comment by mwittrien** [comment]
> At the very least, it would be preferable to have the images use their correct size (especially when using the zoom option in appearance).  If you look at the source for how they're put into frame, they're always referenced a different scale from server than in the frame, which makes them always a bit blurry.
> 
> ![Developer_Tools_-_httpsdiscord comchannels897 (2022-02-10_14-59-16)](https://user-images.githubusercontent.com/25147974/153511052-7c9155ae-1727-4a37-81bf-0042a71bd855.png)
>  

Disable image resizing

**Comment by silverwings15** [comment]
quick suggestion: would it be possible to automatically hide the mouse cursor while using the zoom lens?
