### ISSUE TITLE
[Button not showing in server list] Read All Notifications Button 

### ISSUE THREAD

**Issue by rickvandijck** [mwittrien/BetterDiscordAddons#1295]
**Describe the bug**
Since the latest update(s), the "Read all" button isn't showing up in the server list for me

**To Reproduce**
After updating the plugin :\

**Expected behavior**
The button to actually show and work

**Discord Build (stable, ptb or canary):**
Canary

**Comment by mwittrien** [comment]
What version is BDFDB and ReadAllNotificationsButton

**Comment by rickvandijck** [comment]
> What version is BDFDB and ReadAllNotificationsButton

BDFDB 2.0.4 and RANB version 1.7.0

**Comment by mwittrien** [comment]
Make sure its enabled and try reloading discord via ctrl r

**Comment by rickvandijck** [comment]
Yeah, I did all that. Cleared caches, did a full reinstall of Canary.
I'm running it through BDCompat on Powercord, could that be an issue?

**Comment by mwittrien** [comment]
My plugins only work on the original version of BD, bdcompat doesnt fully emulate BD
