### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by Evo32** [mwittrien/BetterDiscordAddons#1296]
**Describe the solution you'd like**
Ability to Hide/Shrink the Server Bar
I think a button that changes the width from a set width to another would be good, so default would be 0 but you could change that in plugin settings to 100 for example. Also able to disable the button.

**Describe alternatives you've considered**
I tried HideServersChannelsRedux, which gives part of what I want, however when enabled with DisplayServersAsChannels it will re-open the server bar whenever you click on a new channel.
https://user-images.githubusercontent.com/96995161/147886328-588a6912-8cb1-4ed6-8739-3ba2ffa4b1fa.mp4
**Additional context**

**Comment by mwittrien** [comment]
You could use css to shrink it when its not hovered

**Comment by Evo32** [comment]
Right. Good solution. The problem is I don't know how to do that. So preferable you will? <3
