### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps - add D/M/YY format

### ISSUE THREAD

**Issue by breno-dupin** [mwittrien/BetterDiscordAddons#1298]
**Describe the solution you'd like**
Right now the $date formats the date to the M/D/YY form.
Request to add option to format it to D/M/YY form.

**Describe alternatives you've considered**
Changes to help clarify which form the flags will format.
1. Change "$date" -> "$dateMDYY" (keep format of old $date, M/D/YY)
2. Add "$dateDMYY" with formats date to D/M/YY 

**Additional context**
From https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html
Number 5 shows format of the current $date
Number 6 show format of this request.
![image](https://user-images.githubusercontent.com/57925021/147903658-ef5dbc97-f814-41bb-8d99-1cea601d2424.png)

On this example, if we use the requested format, it will show on the tooltip "3/1/2022, 2:56:47"
![image](https://user-images.githubusercontent.com/57925021/147903634-412daa21-62bd-4ece-be89-02e3ec77dcc9.png)

**Comment by mwittrien** [comment]
Maybe take a look at the plugin settings
