### ISSUE TITLE
[BUG] - EDITUSERS

### ISSUE THREAD

**Issue by Mayapixi** [mwittrien/BetterDiscordAddons#1301]
**Describe the bug**
The plugin doesn't work with imgbb.com.

**To Reproduce**
This happens when using the an image url from imgbb.com.

**Expected behavior**
I expected it to change my avatar locally.

**Screenshots**
https://cdn.discordapp.com/attachments/818675090450939934/929906294301794394/unknown.png

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Example for a link?

**Comment by Mayapixi** [comment]
https://i.ibb.co/1TnSzD3/758038357308866723.png Like this link it works perfectly fine but i can't set it as an avatar
