### ISSUE TITLE
[BUG] - ImageUtilities plugin context menu not working

### ISSUE THREAD

**Issue by ColdMineshaft** [mwittrien/BetterDiscordAddons#1303]
The plugin context menu not working at all

![image](https://user-images.githubusercontent.com/81839588/148871844-2dde5411-3ca1-461f-a08b-f23cf9633a2e.png)
![image](https://user-images.githubusercontent.com/81839588/148872021-2edbb49a-afca-4f80-8674-784a426558fc.png)

I've checked the settings and it's all on
![image](https://user-images.githubusercontent.com/81839588/148872140-7cdbbd9e-d950-49ab-8004-dae4bcf5aae5.png)

Discord Stable 110451 (c233a73)
BetterDiscord 1.3.0

**Comment by mwittrien** [comment]
#1314
