### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Gabiromann** [mwittrien/BetterDiscordAddons#1304]
**Describe the bug**
The feature to observe who is allowed and who is denied permissions into a hidden channel simply doesn't appear anymore

**To Reproduce**
Simply having the plugin?

**Expected behavior**
Being able to see a menu like the following
![image](https://user-images.githubusercontent.com/43472219/148873873-8947c1ac-ef19-4bd3-9e40-41a9d3af7828.png)
![image](https://user-images.githubusercontent.com/43472219/148873891-e5a62866-40a2-46fa-9421-59bda07aaff6.png)
![image](https://user-images.githubusercontent.com/43472219/148874100-c58b28ad-e290-4354-996b-270c4e877067.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/43472219/148873737-8ce085f7-968a-42a1-89f1-f7c117f0e59b.png)

**Discord Build (stable, ptb or canary):**
Discord Stable

**Additional context**
Attempted just re-installing the plugin, then attempted re-installing plugin PLUS all config files in the plugin folder. This ofcourse did not work.
Note that I am also not aware if this was intentionally removed, as I had the plugin for a long while and now the feature just vanished

**Comment by mwittrien** [comment]
#1314
