### ISSUE TITLE
[BUG] - BasicBackground

### ISSUE THREAD

**Issue by Reletr** [mwittrien/BetterDiscordAddons#1306]
**Describe the bug**
The top bar where the minimize, expand, close buttons are, and the chat bar are miscolored. The top bar is fully clear with no opaqueness, and the chat bar is the default grey

**To Reproduce**
No steps required to reproduce the bug

**Expected behavior**
The top bar should more opaque than the rest of the background and the chat bar should have transparency, like shown here (https://betterdiscord.app/theme/BasicBackground)

**Screenshots**
![image](https://user-images.githubusercontent.com/55028055/148883150-13c3fad9-3a18-454c-b19d-8a7275228641.png)

**Discord Build (stable, ptb or canary):**
Stable 110451 (c233a73)
BetterDiscord 1.3.0

**Additional context**
N/A

**Comment by Garyzan** [comment]
I have the same problem. The darkening goes away, if transparencycolor is set to something (I guess) invalid (like 0,0,0,0), but that also breaks all other transparent overlays (and for some reason puts a weird symbol between the current and max number of users in a voice chat)
![image](https://user-images.githubusercontent.com/48187279/148946089-174ff639-5b7f-4e4b-aec5-d9ec84d27fab.png)
Increasing transparencybackground still works, but none of the other options seem to work.

**Comment by Reletr** [comment]
Updating BDFDB to 2.0.5 seems to have fixed this issue.
