### ISSUE TITLE
Suggestion: Add Scrollbar Theme/Plugin

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#131]
Discord does not have a native scrollbar built in to the channel list, so it would be useful to have either a theme or a plugin that enables a scrollbar to be added to the channel list instead of having to use a non-existent scroll wheel or going to a channel where I don't have permission to write and use the keyboard to scroll.

**Comment by mwittrien** [comment]
Can be done with css ask in the css channels on the BD servers

**Comment by TheDarkBomber** [comment]
What's the CSS code?
