### ISSUE TITLE
[BUG] - Translator / right mouse click -> translate is gone

### ISSUE THREAD

**Issue by mancmanGER** [mwittrien/BetterDiscordAddons#1310]
**Describe the bug**

right mouse click -> translate is gone

I installed dc and better dc several times, but the translate function on right click is gone

plugin itself still in bar at the bottom

**Comment by mancmanGER** [comment]
auto translate does not work anymore as well for me

**Comment by mancmanGER** [comment]
![image](https://user-images.githubusercontent.com/19344871/148932652-1637ec4c-a415-4019-89d1-8ebc78f5cf2d.png)
![image](https://user-images.githubusercontent.com/19344871/148932710-dbe8f8d9-be74-4ead-8f99-4c4d66e521a2.png)

**Comment by mancmanGER** [comment]
I tried all the available dc PC programs and restarted PC several times and installed better dc several times...

**Comment by mancmanGER** [comment]
any ideas?

**Comment by mancmanGER** [comment]
auto translate works again
but right click translate is still gone

**Comment by iephesus** [comment]
some problem

**Comment by mwittrien** [comment]
#1314
