### ISSUE TITLE
[BUG] - ChatAliases - "Add to Aliases" gone in Right click menu

### ISSUE THREAD

**Issue by jericjan** [mwittrien/BetterDiscordAddons#1313]
**Describe the bug**
I used to be able to select text in the text box, right click, then I would see a button that lets me add that selected text to my aliases.

**To Reproduce**
Type any text. Select and right click. See that there is no "Add to Aliases" button.

**Expected behavior**
There should be an "Add to Aliases" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/38642145/148933054-906e9eb4-969c-4237-b33c-2c5473bcf9dd.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mancmanGER** [comment]
Translator is gone on right click as well

**Comment by mwittrien** [comment]
#1314
