### ISSUE TITLE
[BUG] - Plugins no longer add entries to right click menus

### ISSUE THREAD

**Issue by mancmanGER** [mwittrien/BetterDiscordAddons#1314]
All Plugins that add entries to the right click menues are broken

**Comment by iephesus** [comment]
it's all disable

**Comment by Limones-07** [comment]
> it's all disable

So Discord made them incapable to work or is it a config on the client? I have the plugin installed but it simply doesn't work anyway. It's like it wasn't installed, except for the "Plugins" section of Better Discord that says it's installed.

**Comment by mwittrien** [comment]
Its broken, wait for a  fix
