### ISSUE TITLE
[BUG] - NotificationSounds - The general message sound doesn't change.

### ISSUE THREAD

**Issue by iiRoy** [mwittrien/BetterDiscordAddons#1316]
**Describe the bug**
When you try to change the message sound, it does identify the audio file, and even reproduce it at notifications, but in the time to interact with Discord, the sound is set as the default sound of Discord.

**To Reproduce**
When a general message with no mention is sent to a channel.

**Expected behavior**
It should play the configured audio from the configuration menu.

**Screenshots**
- Can't screenshot the audios xD -

**Comment by iiRoy** [comment]
I am using BetterDiscord 1.3.0 & Discord version 10.0.21996

**Comment by Kurotaku-sama** [comment]
You could just look 10 seconds in the other issues to see, that there is already a report for that 
https://github.com/mwittrien/BetterDiscordAddons/issues/1308

And a emergency solution to prevent this to happen
