### ISSUE TITLE
[IMPROVEMENT] - Customize $date | CreationDate

### ISSUE THREAD

**Issue by FabioMike06** [mwittrien/BetterDiscordAddons#1317]
**Describe the solution you'd like**
Let the user choose how $date is displayed in the settings
I don't understand why $date needs to be MM/DD/YYYY instead of DD/MM/YYYY so I'd like to have something in the settings where you can choose any option you'd like so YYYY/DD/MM  YYYY/MM/DD etc...

**Describe alternatives you've considered**
Replace MM/DD/YYYY to the ISO standard date format (YYYY-MM-DD)

**Additional context**
------

**Comment by mwittrien** [comment]
You already can in the settings
