### ISSUE TITLE
New Notifications are not displaying properly

### ISSUE THREAD

**Issue by fhlox** [mwittrien/BetterDiscordAddons#132]
Recently, I've notices that new notifications on servers aren't being displayed on the server folders from your server folders plugin like they used to. See the below:

https://cdn.discordapp.com/attachments/280806472928198656/505175092125368340/notifications_not_displaying_correctly.png

The notification shows beside the server itself, but not on the folder, without reloading discord or opening the plugins menu. If I do that however, once I've resolved the notification on the server, it remains on the server folder.

**Comment by mwittrien** [comment]
Fixed
