### ISSUE TITLE
[Keyboard Server Scrolling Disabled] - ServerHider v6.2.2 by DevilBro

### ISSUE THREAD

**Issue by JulioA8** [mwittrien/BetterDiscordAddons#1320]
**Describe the bug**
Unable to scroll down server list via keyboard up and down keys. 

**To Reproduce**
when I click the server bar, I'm no longer able to scroll up or down via keyboard. Works fine when Plugin is turned off

**Expected behavior**
Should be able to scroll up and down with selected server highlighted without issues

**Screenshots**
_Scrolling with Plugin turned off; Unable to with Plugin turned on_
<img width="301" alt="Screen Shot 2022-01-12 at 4 29 50 PM" src="https://user-images.githubusercontent.com/59890933/149224272-c3513593-45cf-4860-9da0-01eac476c58b.png">
<img width="277" alt="Screen Shot 2022-01-12 at 4 22 12 PM" src="https://user-images.githubusercontent.com/59890933/149224322-4415d5a4-a4de-45f0-859f-132af96227d5.png">
<img width="281" alt="Screen Shot 2022-01-12 at 4 22 05 PM" src="https://user-images.githubusercontent.com/59890933/149224324-6e7e830a-02da-4384-8fc4-8bcac1a29f76.png">
<img width="271" alt="Screen Shot 2022-01-12 at 4 22 00 PM" src="https://user-images.githubusercontent.com/59890933/149224327-c6f59ab1-b41b-448d-b4e1-24dacf69a925.png">

**Discord Build (stable, ptb or canary):**
BetterDiscord 1.3.0

**Additional context**
Dragging mouse pointer and clicking server bar will freeze the app; This seems to no longer be an issue anymore but this occurred when I turned the ServerHider off to organize folders but turning it back on I'm unable to scroll via keyboard.

**Comment by mwittrien** [comment]
Sadly can not be fixed, since changing the server list is what breaks that
