### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by TiboriusDev** [mwittrien/BetterDiscordAddons#1323]
**Describe the bug**
The Dev Console displays the following error
"Fatal Error: "after" callback of default in Message TypeError: Cannot read property 'isFriend' of undefined"

**To Reproduce**
Every time I hover over a message

**Screenshots**
![image](https://user-images.githubusercontent.com/39419335/149620285-9dfef6a5-ba04-4a79-a0e6-c23d5bb5f5f8.png)

**Discord Build (stable, ptb or canary):**
Stable 110451 (c233a73)
BetterDiscord 1.3.0
Host 1.0.9003 
The Disord says: Windows 10 64-Bit (10.0.22000) - (Actually Windows 11)

**Comment by mwittrien** [comment]
Already fixed
