### ISSUE TITLE
[BUG] - PLUGIN/NotificationSounds

### ISSUE THREAD

**Issue by sebastienpuylaurent** [mwittrien/BetterDiscordAddons#1325]
**Describe the bug**
Normal discord message sound played hover custom song 

**To Reproduce**
when I'm not on discord, when discord is reduced, when I'm on another window than discord 

**Expected behavior**
I exept that only the custom sound played, not the discord one 

**Discord Build (stable, ptb or canary):**
discord stable

**Comment by mwittrien** [comment]
#1308
