### ISSUE TITLE
[BUG] - SpotifyControls

### ISSUE THREAD

**Issue by Error-Cezar** [mwittrien/BetterDiscordAddons#1326]
**Describe the bug**
The plugin doesnt do anything: the song doesn't display on discord, none of the button works.

**To Reproduce**
I have no idea how it happened.

**Expected behavior**
The plugin should work correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/64325581/149673610-e6138388-9de5-4199-a671-e3a73c4e0d13.png)

**Discord Build (stable, ptb or canary):**
Stable 110451 (c233a73)

**Additional context**
Reinstalling spotify or the plugin doesn't fix anything.

**Comment by mwittrien** [comment]
Reconnect your spotify account and make sure its the correct one

**Comment by Error-Cezar** [comment]
I have tried that.
No changes.

**Comment by Error-Cezar** [comment]
Half working:
Controls works but show thing is still bugged.

**Comment by Error-Cezar** [comment]
Fixed. It was a problem on my side.
