### ISSUE TITLE
[BUG] - EditUsers - Changes for avatar didn't get updated in a few areas

### ISSUE THREAD

**Issue by chiqors** [mwittrien/BetterDiscordAddons#1331]
**Describe the bug**
User Avatar changes don't appear in View Profile Modal and My Account Page (In User Settings Menu).

**To Reproduce**
Change someone's or my profile picture locally, it won't change in View Profile Modal and My Account Page.

**Expected behavior**
The user avatar should have their avatar changed in those areas as well.

**Screenshots**
How it should look (member list): https://i.imgur.com/txaDnYp.png
How it appears (View Profile Details): https://i.imgur.com/OC3HRTg.png
How it appears (My Account): https://i.imgur.com/DYV0so7.png

**Discord Build (stable, ptb or canary):**
Stable

**Comment by NotGeobor** [comment]
I noticed that if you restart the extension then it updates in the profile details. It also does not show the new profile picture when trying to watch the screen of someone who is not streaming in a call.
