### ISSUE TITLE
[IMPROVEMENT] - Auto-show Spammer message

### ISSUE THREAD

**Issue by TheMongoloid** [mwittrien/BetterDiscordAddons#1332]
**Describe the feature you'd like**
Some people have the "x message hidden from likely spammer - Show message" this gets annoying as 9 times out of 10 from my experience. They’re not spammers. Some dude just didn’t like them, so they got labelled as one. I tried making something in CSS to do this, but my brain power isn’t that good, so I’ve come here to ask you if you could do it.

**Describe alternatives you've considered**
Not 100% sure what to put here

**Additional context**
The only other thing I think you should consider adding to make it better is to make an option to hide the message pop-up and or just show everything.
Example of the pop-up:
![3qbdeNwMMI](https://user-images.githubusercontent.com/78914154/150433064-8480eb53-3a32-43d4-9e40-bbffd8beb485.png)

**Comment by mwittrien** [comment]
I am not open for plugin requests
