### ISSUE TITLE
[BUG] - CompleteTimestamps - Always showing not the right thing on discord's timestamps

### ISSUE THREAD

**Issue by Thedoczek** [mwittrien/BetterDiscordAddons#1333]
**Describe the bug**
On discord timestamp feature, I always see just the hour, instead of date.
That is only on some types of timestamps, but on other types it also shows differently

**To Reproduce**
Always

**Expected behavior**
![image](https://user-images.githubusercontent.com/69758777/150592453-41b9a342-f12e-4a78-995d-d746b1f5734e.png)
![image](https://user-images.githubusercontent.com/69758777/150592457-57cebaec-4759-4e84-8f95-0ecb36b2b6e9.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/69758777/150592569-9fb9e7e7-c8b5-40e8-baa8-ce76ddcc414a.png)
![image](https://user-images.githubusercontent.com/69758777/150592574-90c4f10f-23a3-4d91-b79b-8ff8d068cee8.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Where are these timestamps located

**Comment by Thedoczek** [comment]
One is on standard message, and that with only hour is on embed

pt., 21 sty 2022, 23:39 użytkownik Mirco Wittrien ***@***.***>
napisał:

**Comment by mjeveritt** [comment]
Is this in all timestamps, or the new embedded formatting with relative 'flag's ? I'm certainly getting incorrect functionality with the :R suffix in the <t:unixtime:R> tags...
