### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by shamshitty** [mwittrien/BetterDiscordAddons#1338]
**Describe the bug**
Plugin doesn't start at start up, only works when turned off and on again.

**To Reproduce**
Whenever discord and betterdiscord start

**Expected behavior**
The plugin to start at start up like ever other plugin and theme

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Works just fine for me with the newest BDFDB version and newest ShowHiddenChannels

**Comment by shamshitty** [comment]
hm, guess its just me then

**Comment by inbroso** [comment]
happens for me aswell

**Comment by LoSunny** [comment]
Same here. I need to restart the plugin in order for it to work
```
Stable 111699 (e8f9fb9)
BetterDiscord 1.3.0
Host 0.0.264
OS X 10.15.7 (19.6.0)
```

**Comment by velveetus** [comment]
For me, the issue seems to be caused by having the plugin "CreationDate" enabled. Disabling the plugin seems to fix the issue. I'm not sure why this happens, though.

**Comment by eckserah** [comment]
For me it's both "CreationDate" and "JoinedAtDate" That are causing the isuse

**Comment by Karbust** [comment]
Same here, disabling "JoinedAtDate" solved the issue.

**Comment by shamshitty** [comment]
bit of a shame I have to disable that plugin for another to work but I'll go with it

**Comment by KeparYTbcc** [comment]
![image](https://user-images.githubusercontent.com/67996155/152444068-a7573852-d0f2-407e-adb5-73463e8c235e.png)

**Comment by KeparYTbcc** [comment]
![image](https://user-images.githubusercontent.com/67996155/152444121-59e8a9f8-e5fa-4580-a6e5-e61fc52a9326.png)

**Comment by KeparYTbcc** [comment]
hidden channel does not working too
