### ISSUE TITLE
[BUG] - CustomStatusPresets

### ISSUE THREAD

**Issue by Lunia974** [mwittrien/BetterDiscordAddons#1339]
**Describe the bug**
There is no button to save a status as a preset.

**To Reproduce**
Happens all the time, and nothing makes it appear.

**Expected behavior**
It used to appear on the bottom of the "Set a custom status" screen, next to the cancel button and isn't appear anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/92110903/150658906-342b2b2f-42c1-4824-8407-c3983c3f0a71.png)

**Discord Build (stable, ptb or canary):**
Stable, I'm guessing.

**Additional context**

**Comment by AlystairWesley** [comment]
Seconding this issue, I'm on Stable Discord also, all other plugins including DBFDB are up to date. No compilation errors or the like.
Previous presets _do_ load, but am unable to save/create more.

**Comment by AroRez** [comment]
Thirding this issue, it just disappeared out of no where
