### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by Venomousicon** [mwittrien/BetterDiscordAddons#1340]
**When opening the translator menu, you can no longer search for languages like you used to, instead you have to scroll through the very small drop-down menu and go through hundreds of languages to find the one you want.**

**Anytime you open the translator menu**
When does the bug occur.

**Usually, i'm able to click on the language box and then type the name of a language i want, shortening the time it takes to find it.**

**[image](https://user-images.githubusercontent.com/98240235/150701791-37ee5dae-fe5f-4c8b-9a5f-db8ad39f6aac.png)**

**Discord Stable 111699**
Which build of Discord are you using.

**This used to work until about 3 or 4 months ago**

**Comment by mwittrien** [comment]
Discord removed it from their dropdowns
