### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by BlackBuyMarketplace** [mwittrien/BetterDiscordAddons#1341]
**Describe the bug**
The chat translator function does not work. It won't translate chats coming in or the chats I send out.

**To Reproduce**
When I try to send a chat or receive a chat and send a chat it never translates it

**Expected behavior**
It just send a normal chat

**Screenshots**
N/A It is fairly straight forward

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by Dracoonica** [comment]
Same here. It's rough XD. I hope the issue can get solved... maybe discord updating..
