### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by magstersnoyl** [mwittrien/BetterDiscordAddons#1343]
**Describe the bug**
Plays discord's default message sound instead of custom message sound.

**To Reproduce**
Receiving notifications.

**Expected behavior**
I expected to hear my custom message sound.

**Screenshots**
[none]

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
It is a similar issue to where both the default and custom would play simultaneously, however, this just plays the default message sound and not the custom message sound. I have also tried changing the file type of my custom sound, uninstalling BDSounds, and reinstalling it, not too sure what's going on, really. It was working normally about a week ago.

**Comment by mwittrien** [comment]
#1308
