### ISSUE TITLE
[BUG] - Translator | Updates go break

### ISSUE THREAD

**Issue by aquilacapella** [mwittrien/BetterDiscordAddons#1344]
**Describe the bug**
Plugin updates and possibly the newest BD update cause the translator button from the chat disappears completely.

**To Reproduce**
Update something in your BD and weep.

**Expected behavior**
Translator button doesn't disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/63672745/151298640-de73ad28-c6c9-4c6c-bf03-440929a8c1c7.png)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Button go screwy

**Comment by aquilacapella** [comment]
Alright, well now I'm super confused. I've done a multitude of troubleshooting steps, including but certainly not limited to:

1. Restarted Discord completely (did not fix my issue)
2. Reinstalled Translator completely (did not fix my issue)
3. Removed all plugins from my plugins folder, restarted Discord and reinstalled Translator entirely including to the point where it asked me to download it's dependency BDFDB (did not fix my issue)
4. Repaired BetterDiscord, which includes reinstalling the entire BD client (still nothing, did not fix my issue)
5. Cried (unfortunately, did not fix my issue)

Conclusion? Translator just doesn't work now, period.

**Comment by mancmanGER** [comment]
same behaviour for me
