### ISSUE TITLE
[BUG] - ReadAllNotificationsButton

### ISSUE THREAD

**Issue by kaxon-dev** [mwittrien/BetterDiscordAddons#1345]
**Describe the bug**
Read all button doesn't exist.

**To Reproduce**
I'm using powercord with bdCompat, but it could just be a problem on discord canary.

**Expected behavior**
Read all button does exist.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Canary.

**Additional context**
N/A

**Comment by mwittrien** [comment]
My plugins only work on original BD
