### ISSUE TITLE
[BUG] - ServerDetails/NOT WORKING

### ISSUE THREAD

**Issue by Retardantt** [mwittrien/BetterDiscordAddons#1347]
**Describe the bug**
Server details don't work

**To Reproduce**
Every time after new Discord/BD update

**Expected behavior**
The plugin is expected to word :D

**Screenshots**
![image](https://user-images.githubusercontent.com/68786400/151373470-59ccca0e-9d88-4f7d-a6cc-c8db02e2d25e.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by PatheticMustan** [comment]
same, the modal just doesn't show up at all

Stable 112515 (900f57b)
BetterDiscord 1.4.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Comment by RBTC** [comment]
Just recognized same issue

Stable 112644 (2dd6bce)
BetterDiscord 1.4.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Comment by Karbust** [comment]
Same issue here

Stable 112644 (2dd6bce)
BetterDiscord 1.4.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19044)

**Comment by SaeidNH** [comment]
Same here.

Stable 113007 (af69096)
BetterDiscord 1.5.0
Host 1.0.9003 Windows 10 64-Bit (10.0.22509)

**Comment by bloodhunt214** [comment]
Same here.

Stable 113007 (af69096)
BetterDiscord 1.5.0
Host 1.0.9003 Windows 10 64-Bit (10.0.22509)

**Comment by captahbvious** [comment]
> **Describe the bug** Server details don't work
> 
> **To Reproduce** Every time after new Discord/BD update
> 
> **Expected behavior** The plugin is expected to word :D
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/68786400/151373470-59ccca0e-9d88-4f7d-a6cc-c8db02e2d25e.png)
> 
> **Discord Build (stable, ptb or canary):** Stable

He is updating the plugins. he made a lot of new commits today, and he updated his library to the new class structure that broke all the plugins in the first place. When Discord updated, many things needed to be changed in plugins, and they need to be changed manually in all of them. He has a lot of them. Give it time. Now that BD is updated and the Library is updated, shouldn't be long.
