### ISSUE TITLE
[BUG] - Translator Chat Translation Options Button is missing

### ISSUE THREAD

**Issue by Siaomo** [mwittrien/BetterDiscordAddons#1349]
**Describe the bug**
Chat Translation Options Button is missing
he's gone
But it is normal that chat room messages can be translated

**To Reproduce**
In the last few days, I want to say that it has been three or four days and I have reinstalled not working.

**Expected behavior**
Can you fix this function? After all, English is not very good. This plugin is very convenient to communicate with foreigners

**Screenshots**

**Discord Build (stable, ptb or canary):**
BetterDiscord 1.4.0

![螢幕擷取畫面 2022-01-28 092845](https://user-images.githubusercontent.com/78332860/151471257-d1919994-e2fe-43ec-9121-2ce3e1b40393.png)
![螢幕擷取畫面 2022-01-28 092856](https://user-images.githubusercontent.com/78332860/151471261-fe686374-4e1d-43fc-8686-eea1a17b5980.png)

**Comment by CreeperStatic** [comment]
I've been having the exact same issue for that amount of time also

**Comment by EspenDai** [comment]
I've been having the exact same issue for that amount of time also
