### ISSUE TITLE
[BUG] - betterfriendlist - crash when click favorites/hidden button

### ISSUE THREAD

**Issue by cow03haha** [mwittrien/BetterDiscordAddons#1350]
**Describe the bug**
discord will crash when click favorites/hidden button in friend page

**To Reproduce**
1. go to friend page
2. click favroites/hidden button
3. discord crash

**Expected behavior**
can show friend that you add to favorites/hidden

**Screenshots**
![friend page](https://i.imgur.com/JUiuDSw.png)

![discord crash](https://i.imgur.com/YSHWFFt.png)

**Discord Build (stable, ptb or canary):**
Stable 112296 (15f81ca)

**Additional context**

**Comment by LiquidDevect** [comment]
Can confirm this bug

**Comment by Tsumitsuki** [comment]
yep. same here

**Comment by slushie0** [comment]
Same, I'd use this plugin if it worked.
