### ISSUE TITLE
[IMPROVEMENT] - ServerFolders

### ISSUE THREAD

**Issue by QuentinMcCarthy** [mwittrien/BetterDiscordAddons#1351]
**Describe the solution you'd like**
Folder column should be padded to align with the folder's position in the main column instead of being positioned at the top so that the user does not need to move their mouse all the way from the folder to the top of the screen to select servers.

**Describe alternatives you've considered**
N/A

**Additional context**
Current implementation:
![image](https://user-images.githubusercontent.com/36647653/151491269-92454df6-a2ea-4f79-b57c-ae22b4f70b87.png)

Suggested implementation
![Screenshot 2022-01-28 181840](https://user-images.githubusercontent.com/36647653/151491723-b982c268-27e6-4234-84c7-3e41e3b5cb7d.png)
:

**Comment by mwittrien** [comment]
No
