### ISSUE TITLE
[BUG] - EditUsers/ Changing someone avatar causes it to be low quality in chat and when clicking on them, but not in the profile and other places.

### ISSUE THREAD

**Issue by TouhouJevil** [mwittrien/BetterDiscordAddons#1353]
**Describe the bug**
Replacing someone avatar with a image, causes it to be low quality in chat and when clicking on the person, but when you see their profile for instance the avatar will be fine and high quality.

**To Reproduce**
When replacing someone avatar.

**Expected behavior**
It should be high quality avatar in all places, but it's only in some of them..

**Screenshots**
How they look: https://media.discordapp.net/attachments/435902363673296917/937149313094680586/unknown.png, https://media.discordapp.net/attachments/435902363673296917/937149361056518144/unknown.png
Yet when checking their profile page the avatar looks 100% fine no blur or low quality https://media.discordapp.net/attachments/435902363673296917/937149685695643668/unknown.png

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by mwittrien** [comment]
Thats due to StatusEverywhere/AvatarsEverywhere not EditUsers
