### ISSUE TITLE
[Hidden Channels not showing] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Ratzelfummel** [mwittrien/BetterDiscordAddons#1359]
Well, as stated. the plugin seems to be "working" but no matter which settings I use, hidden channels are not showing anymore.

Even de- and reinstalled the plugin, didn't fix it. Not to mention a clean reinstallation of both Discord and better Discord

**Comment by selbstmord** [comment]
For me it works after the first time installation, however when I restart, functionality stops.

**Comment by asusplayer** [comment]
As said here: https://github.com/mwittrien/BetterDiscordAddons/issues/1338#issuecomment-1021624351, you may need to disable CreationDate and JoinedAt

**Comment by selbstmord** [comment]
I don't use either.
