### ISSUE TITLE
ServerFolder margin problem

### ISSUE THREAD

**Issue by DrPiggy** [mwittrien/BetterDiscordAddons#136]
after the latest discord update the plugin creates this huge useless margin between the servers inside the server folder and the actual open server right now:
![image](https://user-images.githubusercontent.com/16208640/47962985-b6cf7700-e02d-11e8-915e-4e8953a45ea8.png)

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/47964781-e3d85580-e03e-11e8-9152-407684653313.png)

Thats most likely your theme doing that

**Comment by DrPiggy** [comment]
@mwittrien with all themeing options turned off the problem stays, is there some kind of log i can give you

**Comment by mwittrien** [comment]
actually there is no issue the margin is normal, i just checked the margin in the screenshot and it's the same as for me, the margin is used for the selected and unread indicator

if you want to change it, youll have to theme it yourself

**Comment by DrPiggy** [comment]
i dont think you understand which margin im talking about, sorry if my english is bad but im talking about this:
![image](https://user-images.githubusercontent.com/16208640/47965609-ebedc080-e051-11e8-8163-2513e6e25e73.png)

**Comment by mwittrien** [comment]
Oh lol, no that's not normal, try reloading and disabling all plugins/themes except for ServerFolders

Works fine on my end

**Comment by mwittrien** [comment]
Did u try to reload

**Comment by DrPiggy** [comment]
I did reload, i opened the console and it seems like the plugin creates 3 server folder containers instead of 1 and 2 of them are obviously empty.
![image](https://user-images.githubusercontent.com/16208640/48625275-6fdf6b00-e9b7-11e8-9036-3ca5c685f623.png)

**Comment by mwittrien** [comment]
Thats not an issue with the plugin but with your BD, make sure you arent running multiple files with different names of ServerFolders or anything that loads plugins multiple times
