### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by yamiM0NSTER** [mwittrien/BetterDiscordAddons#1360]
**Describe the bug**
Local usernames don't seem to be applying.

**To Reproduce**
Join voice channel with a person that has local username set and have game opened with discord overlay enabled.

**Expected behavior**
Users with local username should have their username changed in overlay.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/22958062/152006035-4e019254-f111-41c2-8092-37a28fd2c2cf.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
It's not some breaking bug and not sure if it's possible to even apply the changes to overlay.

**Comment by mwittrien** [comment]
BD doesnt touch the overlay
