### ISSUE TITLE
[BUG] - ServerFolders - React Component Error

### ISSUE THREAD

**Issue by lotushomerun** [mwittrien/BetterDiscordAddons#1365]
**Describe the bug**
When clicking on a server folder, the server does not open. If you click on it again, it causes a react component error
I have never experienced this bug until updating to Stable 113144

**Expected behavior**
Normal behavior, ability to access servers in folders

**Screenshots**
![image](https://user-images.githubusercontent.com/49370361/152248790-f9bccf79-6cdf-4a91-ab7d-6b553452d78b.png)

**Discord Build (stable, ptb or canary):**
Stable 113144
BetterDiscord 1.5.0

**Comment by JacksonFrost13** [comment]
Stable 113194 (8bfb811)
BetterDiscord 1.5.0
Windows 10 64-Bit (10.0.19044)

Confirming this issue

**Comment by Humper04** [comment]
Not working on:
Stable 113194 (8bfb811)
BetterDiscord 1.5.0
Windows 10 64-Bit (10.0.19044)

But working on:
Stable 113007 (af69096):
BetterDiscord 1.5.0
Windows 10 64-Bit (10.0.22000) (this is actually windows 11)

**Comment by Johannes7k75** [comment]
For me also not working,

Stable 113194 (8bfb811)
BetterDiscord 1.5.0
Windows 10 64-Bit (10.0.22000) (this is windows 11)

so it has to do with the releas of discord it seams for me.
All that have the issue have stable 113144 or higher but Humper04 on his system only at stable 113007
