### ISSUE TITLE
[BUG] - Server folders / cant see servers

### ISSUE THREAD

**Issue by KeparYTbcc** [mwittrien/BetterDiscordAddons#1366]
![image](https://user-images.githubusercontent.com/67996155/152256379-dbcb48fe-0440-4427-ad04-9c03a855a2e9.png)

**Comment by bbeenn1** [comment]
The setting "Moves the Servers from opened Folders in an extra Column" controls this behavior, disabling that setting allows me to see the servers at least, but if it is enabled no servers appear in the second column.

**Comment by mwittrien** [comment]
#1365
