### ISSUE TITLE
[BUG] - ShowHiddenChannels, ServerSearch, StatusEverywhere, ServerDetails, ImageUtilities

### ISSUE THREAD

**Issue by Bernnoth** [mwittrien/BetterDiscordAddons#1367]
**Describe the bug**
ShowHiddenChannels and ServerSearch share the same issue; being that they somehow need to be turned off and on to show up.
ImageUtilities and ServerDetails stopped working entirely.
**To Reproduce**
When does the bug occur.
How am I supposed to describe this?
**Expected behavior**
Every time I launch Discord, it would freeze due to the amount of plugins being loaded, and I would see the ServerSearch button for a bit until it disappears
**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable
**Additional context**
I have made attempts to find out what's the problem by disabling every other addons, but the problem persists

**Comment by KeparYTbcc** [comment]
^

**Comment by mwittrien** [comment]
#1338

**Comment by KeparYTbcc** [comment]
Bro
it aint working
