### ISSUE TITLE
EditUsers,EditChannels

### ISSUE THREAD

**Issue by khaledmoayad** [mwittrien/BetterDiscordAddons#1368]
legit just not working, only one working is EditServers

**Comment by sammiesky** [comment]
Expanding on this to provide more information: From the symptoms I got in EditUsers, loading the user edits from prior to the plugin breaking still works, but the Local User Settings menu when right-clicking a user does not appear.

**Comment by khaledmoayad** [comment]
yep exactly, same with me, and you can edit the already edited users by going to the plugin settings

**Comment by mwittrien** [comment]
No need to say "same" in an error report
