### ISSUE TITLE
ServerFolders: Custom Icons 👺

### ISSUE THREAD

**Issue by AnnanFay** [mwittrien/BetterDiscordAddons#137]
Are there any plans to let users have custom icons for their folders?

I was just thinking of something like unicode symbols and/or colours. The regular misc block gives stuff like ⚡⛔ ☕ ☭♞♬⚄ and [pictograph block](https://www.fileformat.info/info/unicode/block/miscellaneous_symbols_and_pictographs/list.htm) gives 🌛🍉🎧🎮🎭🏏🐌 etc.

I'm not familiar with the code but if someone pointed out the correct files I could muck around with it until it works.

Maybe even just using the first letter of the folder name would work. Then people can set folder names to "👺Language Learning Servers" and the folder would show the 👺 icon.

**Comment by mwittrien** [comment]
Already implemented
![image](https://user-images.githubusercontent.com/23700969/48399054-db5cda80-e722-11e8-93d5-bdbfca066e7e.png)
![image](https://user-images.githubusercontent.com/23700969/48399067-e3b51580-e722-11e8-92aa-5f189f754771.png)
![image](https://user-images.githubusercontent.com/23700969/48399125-0b0be280-e723-11e8-871e-84ecf2496a03.png)
![image](https://user-images.githubusercontent.com/23700969/48399139-165f0e00-e723-11e8-82cb-47a2a1bfc709.png)

**Comment by AnnanFay** [comment]
@mwittrien I only see this when I go to folder settings:
![image](https://user-images.githubusercontent.com/766048/48427490-bbe4a280-e760-11e8-9496-1e7e0e23966d.png)

Do I have an old version installed or something?

**Comment by mwittrien** [comment]
Ah light theme issue
I added extra styling to the my lib just now, so reloading discord in some minutes should fix it

**Comment by AnnanFay** [comment]
@mwittrien Thanks! Working perfectly now.
