### ISSUE TITLE
[no pin dm button] - Pin dms

### ISSUE THREAD

**Issue by JustDryzer** [mwittrien/BetterDiscordAddons#1371]
**Describe the bug**
Pinning a DM from the context menu doesn't work at all. They existed fine in the categories, but I accidentally cleared the Pinned DMs and now can't get them back.

**To Reproduce**
Right-click a DM
**Expected behavior**
A 'Pin DM' button

**Screenshots**
![Screenshot_7](https://user-images.githubusercontent.com/98991112/152446106-238b418c-e198-4104-85f9-cf3edb8935cf.png)

**Discord Build (stable, ptb or canary):**
Stable 112102 (7b5adfa)
BetterDiscord 1.4.0

**Comment by Luysita** [comment]
Same here

**Comment by TimestaticYT** [comment]
Same for me! I'm on linux

**Comment by ronnie123442** [comment]
This is an issue with the Library. 

[ComponentPatcher:Guilds] Error inside BDGuild: TypeError: Cannot read property 'audio' of undefined


https://i.imgur.com/qlBb9zf.png
https://i.imgur.com/Sj0bz4S.png

**Comment by jafounet** [comment]
same here. can you fix this bug, please?
