### ISSUE TITLE
[BUG] - BDFDB: LogSpam(TypeError: Cannot read property 'audio' of undefined)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#1372]
**Describe the bug**
most plugins depended on this Lib are not functioning correctly anymore as well as a large amount of log spam
TypeError: Cannot read property 'audio' of undefined

**To Reproduce**
the issue occurs as soon as the Lib loads

**Expected behavior**
for no errors?

**Screenshots**
<img width="1729" alt="Screen Shot 2022-02-04 at 21 11 42 pm" src="https://user-images.githubusercontent.com/2242880/152511514-7ab3067c-c293-4ced-9d60-9c26189d6820.png">

**Discord Build (stable, ptb or canary):**
```text
Stable 113404 (30b719d)
BetterDiscord 1.5.0
Host 0.0.264 
OS X 10.15.7 (20.6.0)
```

**Additional context**
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/8001958/debug.log)
[discord.com-1643969648111.log](https://github.com/mwittrien/BetterDiscordAddons/files/8001962/discord.com-1643969648111.log)

**Comment by mwittrien** [comment]
#1365
