### ISSUE TITLE
[BUG] - Server Folders

### ISSUE THREAD

**Issue by Nerxxy** [mwittrien/BetterDiscordAddons#1373]
**Describe the bug**
When using the "Move the servers from opened folders in an extra column" option the servers do not show up

**To Reproduce**
Use "Move the servers from opened folders in an extra column" option

**Expected behavior**
Servers to move into the extra column

**Screenshots**
![image](https://user-images.githubusercontent.com/37718547/152542420-9f223da9-0e5f-48e7-a51e-6ca5e4931271.png)

**Discord Build (stable, ptb or canary):**
Stable 113404 (30b719d)
BetterDiscord 1.5.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19044)

**Additional context**
N/A

**Comment by mwittrien** [comment]
#1365
