### ISSUE TITLE
[BUG] - Better Folders server's not showing up when opening

### ISSUE THREAD

**Issue by DraneLixX** [mwittrien/BetterDiscordAddons#1374]
**Describe the bug**
No server's visible when opening folders, not able to klick anything inside there.

**To Reproduce**
When opening folder

![image](https://user-images.githubusercontent.com/33241086/152600222-8d377eea-3989-4c76-b3b4-ff036cfba151.png)

**Discord Build (stable, ptb or canary):**
Stable 113584 (3f697f2)
BetterDiscord 1.5.0

**Comment by OmegaBlurz** [comment]
#1365
