### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by KingFishy492** [mwittrien/BetterDiscordAddons#1375]
**Describe the bug**
The plugin no longer allows you to edit user info

**To Reproduce**
Always 

**Expected behavior**
When i right click to go to the options normally for user settings the edit button is no longer there even after restarting discord and checking the version of the plugin was up-to-date along with library

**Screenshots**
![image](https://user-images.githubusercontent.com/33896199/152620481-dfa28ae0-130d-403a-9fd8-8f131c44dbb1.png)

**Discord Build (stable, ptb or canary):**
stable.

**Additional context**
The plugin is clearly working as i still have the nicks the names the tags i have added before but i just can no longer edit remove or add more 

Sorry if this has been reported before i tried looking for bug reports on the issue and wasn't getting much back regarding this.

**Comment by mwittrien** [comment]
#1368
