### ISSUE TITLE
Ok so the plugin is just completely broken now [BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by TheBirdFacedOne** [mwittrien/BetterDiscordAddons#1376]
**Describe the bug**

**To Reproduce**
When does the bug occur.

**Expected behavior**

**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

**Additional context**

**Comment by ronnie123442** [comment]
I don't think you needed to make a post for this. Especially you included zero information to help point us to this issue or **THE PLUGIN NAME** that's broken. Really just making this issue a waste of time to read. So please either close this or update the details with something that can be reproduced.
