### ISSUE TITLE
[BUG] - Edit users

### ISSUE THREAD

**Issue by Wonderkill1** [mwittrien/BetterDiscordAddons#1377]
The button to edit users is not appearing, I have reloaded discord 2 or 3 times, uninstalled and reinstalled better discord, also repaired it, hasn't fixed it
It still loads the nicknames I've giving other people in the past but It just doesn't let me do it more
![image](https://user-images.githubusercontent.com/67308027/152637220-6874a927-2f3b-4433-975b-c2b32739c4b9.png)

**Comment by mwittrien** [comment]
#1368
