### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by fearek** [mwittrien/BetterDiscordAddons#1379]
Idk why did you label the previous issue as fixed without any explanation, but it still is broken and there is no option to view permissions for that hidden channel

And yes I have both 0BDFDB and ShowHiddenChannels on newest version

`219be101175c6489dbf8.js:130 [ShowHiddenChannels] (v3.0.5) Fatal Error: "after" callback of type in ChannelListTextChannelContextMenu TypeError: Cannot read property 'splice' of null
(anonymous) @ 219be101175c6489dbf8.js:130
`

**Comment by HexedHero** [comment]
Restart your Discord and get the plugin and BetterDiscord updates. "Newest version" isn't a version.
Works for me on:
BetterDiscord 1.5.1
BDFDB v2.0.8
ShowHiddenChannels v3.0.5

**Comment by fearek** [comment]
BDFDB v2.0.8
ShowHiddenChannels v3.0.5
BetterDiscord 1.5.1
and doesnt work

**Comment by fearek** [comment]
fixed with BDFDB v2.0.9
