### ISSUE TITLE
[BUG] - ContextMenu Crash

### ISSUE THREAD

**Issue by fowlis** [mwittrien/BetterDiscordAddons#1380]
**Describe the bug**
Crashing Discord when right-clicking certain users.

**Screenshots**
Error message from when it crashes.
![](https://i.imgur.com/OsGvBKs.png)

**Discord Build (stable, ptb or canary):**
![](https://i.imgur.com/jQQikqB.png)

**Comment by sammiesky** [comment]
I get the exact same symptoms, plus an identical error log, with EditUsers enabled. Right-clicking on any user does not work.

**Comment by louay123** [comment]
same here :'((

**Comment by uptore** [comment]
This crash seems to occur for me when right-clicking on a user in a guild while the following combination of plugins are enabled:
ImageUtilities and BetterFriendsList. (and BDFDB of course)

**Comment by Willytor** [comment]
Same issue here. Happens even if it's the only plugin i have loaded

**Comment by Willytor** [comment]
Does not happen in dms, only in guilds.

**Comment by AlarkiusJay** [comment]
Yes, this has happened too for me!
