### ISSUE TITLE
[BUG] - EditUsers / ImageUtilities

### ISSUE THREAD

**Issue by BluewyWolff** [mwittrien/BetterDiscordAddons#1382]
**Describe the bug**
Discord crashes when opening user context menus

**To Reproduce**
Open a users context menu.

**Expected behavior**
The context menu should simply pop up.

**Screenshots**
Not applicable

**Discord Build (stable, ptb or canary):**
BD 1.5.1
Discord Stable 113584 (3f697f2)

**Comment by mwittrien** [comment]
#1380
