### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Gemmyyy** [mwittrien/BetterDiscordAddons#1386]
**Describe the bug**
Discord crashes when right clicking a user

**To Reproduce**
simply right click a user

**Expected behavior**
The thing that shows the profile and banning and stuff should appear

**Screenshots**
https://i.ibb.co/NC28v0V/image-2022-02-07-164400.png

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
#1380
