### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by LeonTheDev-io** [mwittrien/BetterDiscordAddons#1387]
When I set  the dm, role, @ everyone @ here, etc mentions to --- (default) I get some weird new high pitched version of it instead of the default ping, I assume its the Message1,Message2,Message3,Mention",Mention",Mention" sounds

Technical stuff:
System: Windows 10
Discord: BTD/Stable
BTD v: 1.5.1
I have no clue where the normal discord version is, is it the host?
Plugin: 3.6.3

**Comment by mwittrien** [comment]
Thats intended to differ betweem them, if you want it to be the default set it to message1
