### ISSUE TITLE
[BUG] - Better Friend List

### ISSUE THREAD

**Issue by josephisticated** [mwittrien/BetterDiscordAddons#1388]
**Describe the bug**
Can't make it work, it just crashes.

**To Reproduce**
Trying to enter any menu that came with the plugin like Hidden etc.

**Expected behavior**
It should show me inside the menus.

**Screenshots**
![image](https://user-images.githubusercontent.com/53388005/152884110-000f8ada-ac23-4fe8-9ee7-77b2f09c0108.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Non

**Comment by mwittrien** [comment]
#1350
