### ISSUE TITLE
[BUG] - DisplayServersAsChannels not working for ServerFolders popout

### ISSUE THREAD

**Issue by groundchuck** [mwittrien/BetterDiscordAddons#1391]
**Describe the bug**
When using both of these plugins together the servers in the popout for ServerFolders just show as blank lines.

**To Reproduce**
Any time you open a folder.

**Expected behavior**
The servers in the folder popout should appear in the same format as DisplayServersAsChannels.

**Screenshots**
![image](https://user-images.githubusercontent.com/1839966/153133065-8490fc46-7613-43b4-aea4-ab90ee317214.png)

**Discord Build (stable, ptb or canary):**
Stable

Thanks!

**Comment by mwittrien** [comment]
Make sure to reload

![Uploading image.png…]()

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/153274569-9c41ead4-e340-41be-8e18-5aa8d7c95b7d.png)
