### ISSUE TITLE
[BUG] - Edit Users - Crash when start up

### ISSUE THREAD

**Issue by pp0236** [mwittrien/BetterDiscordAddons#1393]
**Describe the bug**
discord crash when start plugin

**To Reproduce**
use canary build and start plugin (only crash on home screen)

**Expected behavior**
not crash

**Screenshots**
https://user-images.githubusercontent.com/54238880/153324256-201220d1-6e24-437b-a9ad-f07e9c502a98.mp4
![image](https://user-images.githubusercontent.com/54238880/153324948-ee12af5c-209c-4077-a705-4fd0864697c9.png)
![image](https://user-images.githubusercontent.com/54238880/153324961-e8733f50-9626-4dde-91b4-32c94bb2e5ad.png)
![image](https://user-images.githubusercontent.com/54238880/153324970-a3d1a290-d6f8-4276-917a-8a0334ea56b1.png)

**Discord Build (stable, ptb or canary):**
canary

**Additional context**
react error

**Comment by mwittrien** [comment]
What version is your BDFDB

**Comment by pp0236** [comment]
oh yea plugin incompatibality with my plugin
thanks
