### ISSUE TITLE
[BUG] - Pin DM's and better friends list | Plugins causing volume slider error

### ISSUE THREAD

**Issue by Tarentules** [mwittrien/BetterDiscordAddons#1396]
**Describe the bug**
Either plugin being enabled causes a issue with user volume control control in voice channels. 

**To Reproduce**
Enable either better friends list or pin dm's and then join a voice channel with another user. Try adjusting the user's volume using the slider on the right click context menu, click and drag from the "point" on the slider, clicking at random positions on the volume slider will let it "jump" to that position/level but grabbing and adjusting it more precisely does not work. 

**Expected behavior**
Volume should be able to be adjusted using the slider by clicking it and then  dragging it. 

**Screenshots**
https://i.imgur.com/iO2Yy1N.gif - Gif of the issue with pin DM's enabled and it working after the plugin was disabled. No other plugins were enabled at this time other than "BDFDB"

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
All other plugins and themes disabled at the time this error is happening.

**Comment by Metalheadinaaa** [comment]
xsdczsasaas

**Comment by mwittrien** [comment]
Sadly occures when patching the UserContextMenu, cant be evaded
