### ISSUE TITLE
[BUG] - EditUsers plugin crashes client on startup

### ISSUE THREAD

**Issue by Garyyy77** [mwittrien/BetterDiscordAddons#1398]
**Describe the bug**
Discord crashes if i try to launch it with edit EditUsers plugin

**To Reproduce**
Install EditUsers plugin from BetterDiscord.app und run it
(else edit a couple users to load on startup

**Expected behavior**
Discord crashes and prompts me ro reload

**Screenshots**
https://imgur.com/a/mKk63On

**Discord Build (stable, ptb or canary):**
Stable 114407

**Comment by mwittrien** [comment]
#1394
