### ISSUE TITLE
Showhiddenchannels broke

### ISSUE THREAD

**Issue by koxixehet** [mwittrien/BetterDiscordAddons#14]
Hidden channels don't change when we switch to the new server it keeps on showing the previous server hidden channels to the switched server. Sometimes the plugin goes down though it is on. But restarting the plugin fixes it but still, the plugin doesn't show the current server hidden channel instead it shows previous server hidden channel.

**Comment by mwittrien** [comment]
Not the case for me, works perfect, make sure you got the right version installed

**Comment by koxixehet** [comment]
I'm using 2.0.2 which is the latest version... Still same

**Comment by mwittrien** [comment]
When does it happen exactly

**Comment by mwittrien** [comment]
Ok i get the error now too with the new update, imma fix it

**Comment by koxixehet** [comment]
Well let's say I restart the script then go to a server and I see the hidden channel. Then I go to another server and it still shows the previous server hidden channel and that's it and then when we switch to DM and go back to a server (any server) the script shows nothing not even the hidden category and again we restart and again same thing

**Comment by koxixehet** [comment]
Sure thanks can I say another issue of your script which I like but will I say it here? or make another issue?

**Comment by mwittrien** [comment]
Should be fixed after a reload, for some reason the it didnt trigger when switching but i fixed it, was also the case for any other of my plugins that did stuff when you switched servers or channels

sure post it here

**Comment by koxixehet** [comment]
Alright works fine it's your toproleseverywhere ... Idk but it freezes my discord client whenever I try to switch server. I have tried experimenting all the plugins I use and it's your plugin which freezes it can you check that once? please ?

**Comment by mwittrien** [comment]
Define freeze

**Comment by koxixehet** [comment]
Um let's say I start the plugin then I switch to another server and it's just like that frozen doesn't switch to the server I want it's like stuck and then after 1-2 mins later it switches and also disconnects me from voice if I'm in voice but that's the problem. Sorry I don't know how I will define more than this-this is what I'm experiencing ..

**Comment by mwittrien** [comment]
Is your version up to date? The plugin process quite a bit of data so it can slow down discord a little bit, but it shouldnt be so bad that it freezes your discord for 1-2mins, it runs fine on my crappy laptop

**Comment by koxixehet** [comment]
I'm using your 2.4.0 version. And I'm using the stable discord version. Still, I face this issue.

**Comment by mwittrien** [comment]
Can you try turning off all your themes and other plugins except for TRE and test if the problem persists

**Comment by koxixehet** [comment]
I've might found the issue which is causing but re checking give me a bit of time sorry I'm slow. BTW its not your plugin sorry but its conflicting with other plugin give me a bit of time pls

**Comment by koxixehet** [comment]
Alright I've found it I guess the plugin which is conflicting with your plugin and it's Permissionviewer I'm not 100% sure but when TopRolesEverywhere and Permissionviewer is ON it lags but if I switch OFF TopRolesEverywhere then it's fixed also if I switch OFF Permissionviewer and keep TopRolesEverywhere ON it works fine. So this might be the issue. Still not 100% sure but this might be it.

**Comment by mwittrien** [comment]
Ah yeah that makes sense, TRE opens the userpopout when it can't find the proper role in the userdata, and PermissionViewer adds the permissions to the userpopout, when TRE opens serveral user popouts to fetch the data serveral permissions have to be added to the popouts which lags discord, you can get rid of the lag by turning permissions in the userpopout off in the settings of permissionsviewer that way you can still check permissions via the context menu of a user

**Comment by koxixehet** [comment]
Thank you so much, it's working perfectly now thanks for all the fixes and help really appreciated it thanks again. Closing the issue now its fixed thanks again.

**Comment by koxixehet** [comment]
Um I'm opening this as I was talking about Toproleseverywhere it seems like the plugin is not synching can you check that? Sorry for bothering you again :/

**Comment by mwittrien** [comment]
What do you mean with synching

Am 31.10.2017 11:33 schrieb "koxixehet" <notifications@github.com>:

**Comment by koxixehet** [comment]
Now what I mean is let's say I'm starting the plugin and I'm on my server and it shows me as Owner.. but as soon as I switch to another server it gives me owner tag also though I'm not the owner of that server at all

**Comment by koxixehet** [comment]
nvm something weird stuff going on my end it's fixed somehow :| again sorry for bothering you again and thanks again for all of this :)
