### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by Atrisce** [mwittrien/BetterDiscordAddons#1400]
**Describe the bug**
"copy, image actions" feature listed infinitely

**To Reproduce**
Just right-clicking a dm should do it.

**Expected behavior**
Not an infinite list of the features.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/96490031/153624876-cd0cd81e-dcee-4894-83b6-cce4ef154771.png)

**Discord Build (stable, ptb or canary):**
Stable 114407

**Comment by mwittrien** [comment]
Ctrl R

**Comment by Atrisce** [comment]
> Ctrl R

If it only was so easy, I'd have fixed it already D:

**Comment by mwittrien** [comment]
Well i am not having the issue

**Comment by Atrisce** [comment]
> Well i am not having the issue

That's quite unfortunate.
