### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by Fwappy** [mwittrien/BetterDiscordAddons#1401]
Love your plugins, came up with a few improvements for FriendNotifications but otherwise it works great.

The main one is a way to log changes to the "About Me" bio
Many people use the about me to explain further it would be nice to be notified of changes there

Also, it would be nice to be able to log my own profile
Along with that, a persistent log could also be nice.

**Comment by mwittrien** [comment]
The plugin isnt meant to log the behaviour of your friends, only to notify you and let you check in case you missed something, about mes are pulled from the server afaik so that would cause a spike of requests causing you to get banned
