### ISSUE TITLE
[BUG] - ShowHiddenChannels/No longer shows channel access option in the right click menu

### ISSUE THREAD

**Issue by nomaddc** [mwittrien/BetterDiscordAddons#1403]
**Describe the bug**
Chanel Access menu option is gone in its entirety.

**To Reproduce**
Installed plugins: ShowHiddenChannels, BDFDB. Right click on any channel, including hidden - no channel access menu anymore.

**Expected behavior**
Channel access menu shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/10323524/153669965-1c3ace92-0333-4c57-b243-215840781b6d.png)

**Discord Build (stable, ptb or canary):**
Stable 113194 (8bfb811)
BetterDiscord 1.5.0
Host 1.0.9003
Windows 10 64-Bit (10.0.19044)

**Comment by mwittrien** [comment]
Reload

**Comment by nomaddc** [comment]
Huh, odd, it worked. I was sure I've restarted the discord within last few days. Apologies for false alarm!
