### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by yellmehus** [mwittrien/BetterDiscordAddons#1407]
**Describe the bug**
I cannot use the slider in the user volume setting.

**To Reproduce**
Only when the plugin is active

**Screenshots**
![issue](https://user-images.githubusercontent.com/99523377/153697245-6343eaec-a1a9-454e-91f3-ed4b8dc73b39.gif)

**Discord Build (stable, ptb or canary):**
Stable 114407 (811ab09)

**Comment by SaeidNH** [comment]
I'm sorry to ask this here. I emailed you but didn't get reply. Could you please add and fix this plugin please? @mwittrien 

https://github.com/danny8376/DannyAAMBetterDiscordAddons/tree/master/Plugins/VoiceChannelUserJoinNotification
