### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Luigi534** [mwittrien/BetterDiscordAddons#1409]
idk if is a bug or no but in previous versions we could see if someone was streaming or not in a hideen voice but now you can't see. also on my phone i can see that they are streaming (on hide vocals) but not on my computer discord, so i don't think discord fixed it

I dont know if that a bug or not but if is a bug it occur when the plugins is on

I don't have a screenshot but basically it doesn't show the red button that allows you to see if someone is streaming or not, the only way to know is if the person is streaming is his name starts with Z and another B (B is not streaming), B will be below Z, so you can see that Z is streaming and B is not, because otherwise Z will be below B and not the opposite

I have discord stable

srry for my bad grammar, im french so my english is not good

**Comment by tryoutuser** [comment]
just want to comment, the plugin did not work at all per 18 February 2022

**Comment by mwittrien** [comment]
Just checked and discord no longer tells you whether someone is streaming in a hidden channel or not only thing discord tells you that someone is in a voice channel and if they are in camera mode
