### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by RobinRMC** [mwittrien/BetterDiscordAddons#1411]
**Describe the solution you'd like**
Read audio files instead of reading text to play audio (or implement another solution to avoid crashing).

**Describe alternatives you've considered**
Reducing the length of the ringtone I want to be played.

**Additional context**
BetterDiscord crashes when loading too much data from NotificationSounds. I hope this can be fixed by changing how the plugin reads the audio.

**Comment by mwittrien** [comment]
Dont use entire songs for jingles

**Comment by RobinRMC** [comment]
:(
