### ISSUE TITLE
[IMPROVEMENT] Spotify still slightly hard to access whilst gaming.

### ISSUE THREAD

**Issue by ItsMrZ** [mwittrien/BetterDiscordAddons#1414]
**solution**
it would be a nice feature to see the songs playing on Spotify, below the party list, and change the songs in overlay mode while in another application,

**alternative solutions**
The alternatives that could work are things like key binds, or a spotify panel, seperate to the discord panels but still in the discord overlay. (maybe even a browser like what steam has for that matter)

**Additional context**
This isn't a serious request, just a thing I Figured everyone might like to have.

**Comment by mwittrien** [comment]
Plugins can't interact with the overlay nor can they create new windows
