### ISSUE TITLE
[BUG] - Char counter

### ISSUE THREAD

**Issue by GaleCro** [mwittrien/BetterDiscordAddons#1416]
**Describe the bug**
Does not work, yes it is enabled, is shows 0/2000 but its not updating while typing, just stays at 0
**To Reproduce**
general use of discord, typing

**Expected behavior**
I expected it to go for example 2/2000 if I type "no" or sum like that.

**Screenshots**

![not working](https://user-images.githubusercontent.com/28599838/154349779-11d0cc2d-ebc5-4af6-96fa-796050480436.png)

**Discord Build (stable, ptb or canary):**
I'm using dicsord canary, using powercord with bd plugins

**Comment by mwittrien** [comment]
My plugins only work on original BD
