### ISSUE TITLE
PluginRepo seems very slow to fetch all the plugins

### ISSUE THREAD

**Issue by HRudy94** [mwittrien/BetterDiscordAddons#142]
I don't know why but it takes a lot of time for PluginRepo to fetch everything (sometimes like 10 minutes or more)

**Comment by TheDarkBomber** [comment]
I second this.

**Comment by mwittrien** [comment]
an error broke it, its fixed

**Comment by steampunko** [comment]
I don't think it's fixed. I've been trying to fetch plugins for the past hour and it never does
