### ISSUE TITLE
repo not fixed yet but was marked as fixed

### ISSUE THREAD

**Issue by Basic6969** [mwittrien/BetterDiscordAddons#1421]
same problem as https://github.com/mwittrien/BetterDiscordAddons/issues/1419

**Comment by mwittrien** [comment]
Cant reproduce

**Comment by Basic6969** [comment]
> Cant reproduce

means it wont work anymore?

**Comment by mwittrien** [comment]
> > Cant reproduce
> 
> means it wont work anymore?

Means it works just fine for me

**Comment by Basic6969** [comment]
> > > Cant reproduce
> > 
> > 
> > means it wont work anymore?
> 
> Means it works just fine for me

i will try reinstalling reinstalling discord

**Comment by Basic6969** [comment]
reinstalling fixed the issue

**Comment by Drflash55** [comment]
> Basic6969 said:
> i will try reinstalling reinstalling discord

Did you mean to say reinstalling Discord itself as a whole... or reinstalling BetterDiscord?

**Comment by Basic6969** [comment]
> > Basic6969 said:
> > i will try reinstalling reinstalling discord
> 
> Did you mean to say reinstalling Discord itself as a whole... or reinstalling BetterDiscord?

yes reinstalling both and deleting all files of bd fixed the issue

**Comment by Drflash55** [comment]
Well, I had found a much easier solution. Deleting the entirety of the "0BDFDB" plugin and its associated files, along with the associated files with "PluginRepo" fixed the issue for me.
