### ISSUE TITLE
[BUG] - repo button not showing

### ISSUE THREAD

**Issue by Eegeg** [mwittrien/BetterDiscordAddons#1431]
The repo menu wont show (also on theme repo)

When i go under the plugin menu, it does not show the plugin and theme repo

it should show plugin and theme repo but it does not

![image](https://user-images.githubusercontent.com/88250823/154889585-68233c73-b86c-491f-ae03-1d6a5346767f.png)

Stable 115633 (491cf7f)

i am using BetterDiscord 1.5.2

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
