### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds - add back the ability to change the Startup sound

### ISSUE THREAD

**Issue by ragingmarcel** [mwittrien/BetterDiscordAddons#1432]
I have seen on older revisions of this plugin there was an option to set a custom Discord Startup sound, however now this option is no longer available which is sad to me as I'd really love to change it.
I was thinking about using an older version of this plugin, however I am not sure whether it'd be compatible with the current version of Discord and whether it'd cause bugs.
If it's possible I'd love to have this feature back.

**Comment by mwittrien** [comment]
No point in changing it when the sound plays before the plugin is running
