### ISSUE TITLE
[BUG] - PluginRepo And ThemeRepo

### ISSUE THREAD

**Issue by MCHAMSTERYT2** [mwittrien/BetterDiscordAddons#1434]
**Describe the bug**
Plugin Repo And Theme Repo Keep Saying Failed To Load
**To Reproduce**
When does the bug occur.

**Expected behavior**

**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable
**Additional context**

**Comment by BadCoder2** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/46334485/155008278-bedf400a-5365-4b6a-9a06-9c3f6b87de83.png)
![image](https://user-images.githubusercontent.com/46334485/155008299-dde46fab-a94e-44a9-ba6f-2dfd4acb9047.png)
Stable 115633 (491cf7f)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19041)

**Comment by mwittrien** [comment]
Website is down, aint my fault

**Comment by MCHAMSTERYT2** [comment]
Website Is Back Up

**Comment by nearcatch** [comment]
Website's up but the plugins still fail to load. When I go to the site in my browser I notice it's using Cloudflare bot protection now, so probably that's messing the plugins up.

**Comment by mwittrien** [comment]
The api is down
