### ISSUE TITLE
[BUG] - Theme-Repo/Plugin-Repo

### ISSUE THREAD

**Issue by kaden-tech** [mwittrien/BetterDiscordAddons#1435]
**Describe the bug**
Look at the image

**To Reproduce**
Restart your discord.

**Expected behavior**
It enables,

**Screenshots**
![image](https://user-images.githubusercontent.com/78925970/155028891-4bdf2111-3740-4ee7-a1a8-2b218904d756.png)
![image](https://user-images.githubusercontent.com/78925970/155028913-e50a0215-113a-408e-923c-c2ae93d1c896.png)

**Discord Build (stable, ptb or canary):**
Latest

**Additional context**

**Comment by mwittrien** [comment]
#1434
