### ISSUE TITLE
[BUG] - PluginRepo/ThemeRepo

### ISSUE THREAD

**Issue by dottiekh** [mwittrien/BetterDiscordAddons#1436]
**Describe the bug**
Plugin Repo fails to load with a toast error message saying "Failed to load Plugin Store". This also applies to ThemeRepo.

**To Reproduce**
1. If Plugin Repo isn't listed, then reproduced.
2. If Plugin Repo is listed, pressing Check for Updates brings up the toast.
3. Plugin Repo is also empty if listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/34873184/155032451-77299543-233b-4d8c-b53b-ad1220a9b8fc.png)
![image](https://user-images.githubusercontent.com/34873184/155032506-868a4894-c57a-4be5-abd3-503ef04eac5d.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Tested on fresh install of BetterDiscord with only BDFDB and PluginRepo/ThemeRepo installed.

BDFDB v2.1.8
PluginRepo v2.2.8
ThemeRepo v2.2.8

**Comment by mwittrien** [comment]
#1434
