### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by iViscosity** [mwittrien/BetterDiscordAddons#1437]
**Describe the bug**
Translate Message doesn't show up in right-click context menu anymore.

**To Reproduce**
Right-click a message, translate message option no longer shows.

**Expected behavior**
The option to Translate Message should show on the context menu, but doesn't after I just updated.

**Screenshots**
![right-click context menu doesn't show translate](https://user-images.githubusercontent.com/20390370/155035536-a46edb45-6de3-4794-a9fe-9232d21d1aec.png)
![drop-down context menu does show translate](https://user-images.githubusercontent.com/20390370/155035545-a860d25c-2fd0-4eb0-9954-fbcade75b793.png)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
This option was available up until a few minutes ago when it disappeared after updating BDFDB.

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
