### ISSUE TITLE
[BUG] - Plugin Repo

### ISSUE THREAD

**Issue by camayl** [mwittrien/BetterDiscordAddons#1439]
**Describe the bug**
Nothing visible in Plugin Repo and search brings up no results.

**To Reproduce**
Plugin Repo is empty and re-enabling the Plugin Repo plugin causes error toast "Failed to Load Plugin Store"

**Comment by camayl** [comment]
Same thing with Theme Repo

**Comment by mwittrien** [comment]
#1434
