### ISSUE TITLE
EditChannels V3.7.9+ Couldn't start.

### ISSUE THREAD

**Issue by Drflash55** [mwittrien/BetterDiscordAddons#144]
It seems that from V3.7.9+ onward, every time BetterDiscord tries to start it up, it just tells me that couldn't start.

This happens on V3.8.0 too.
![image](https://user-images.githubusercontent.com/13694448/50024355-14050380-ffb0-11e8-8f7a-96eb681e1e22.png)

**Comment by mwittrien** [comment]
Still happening?

**Comment by Drflash55** [comment]
So far, it hasn't happened at all... so it's safe to assume it was fixed by itself.
