### ISSUE TITLE
[BUG] - PLUGIN-REPO/THEME-REPO (ACTUALLY READ! NOT A DUPE)

### ISSUE THREAD

**Issue by kaden-tech** [mwittrien/BetterDiscordAddons#1440]
**Describe the bug**
Image

**To Reproduce**
When does the bug occur.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78925970/155137884-c989b21f-7ace-4ba1-af64-96ccd3648b35.png)
Same thing with Theme-repo

**Discord Build (stable, ptb or canary):**
Latest
**Additional context**

**Comment by mwittrien** [comment]
Read what? You write the same shit as the 5 ppl before you. This is out of my hands and happens due to the new ddos protection

**Comment by mwittrien** [comment]
#1434
