### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by kamekku14** [mwittrien/BetterDiscordAddons#1442]
**Describe the bug**
Plugin shows incorrect max character limit for user bios.

**To Reproduce**
Enable the plugin, go to **Settings** \> **User Profile** and look for the **About Me** section.

**Expected behavior**
User bios should be at least 200 (or is it 250?) characters and CharCounter doesn't know how long the user bio is.

**Screenshots**
![image](https://user-images.githubusercontent.com/66167734/155243659-72b5f36a-4fc4-47b5-9a0d-62d58ec4cfe8.png)

**Discord Build (stable, ptb or canary):**
Stable 115633 (491cf7f)

**Additional context**
No one hasn't documented this bug for days—and I wonder why?

**Comment by IamNickerson** [comment]
And not only that Charcounter is not appearing in the bottom of text box for me
