### ISSUE TITLE
[BUG] - PinDMs pin to server list crashing

### ISSUE THREAD

**Issue by fowlis** [mwittrien/BetterDiscordAddons#1443]
**Describe the bug**
Crashing after I pin a user to the server list and hover over their avatar to go to the DM
Gives me the "Well, this is awkward" with the reload button screen

BDFDB v2.1.9
PinDMs v1.8.8
(because they're in the error message I will include these too)
FriendNotifications v1.8.1
ReadAllNotificationsButton v1.7.0

**Screenshots**
![Snipaste_2022-02-23_20-45-42](https://user-images.githubusercontent.com/84232621/155405318-c435968d-a42a-456a-a4b3-5d43b0536368.png)

**Discord Build (stable, ptb or canary):**
Tested on Stable & PTB but could only recreate on Stable

**Comment by dark-fedora** [comment]
Have seen multiple people report that only having PinDMs and BDFDB enabled will crash. Also, slightly different trigger for it, posting the stacktrace here: ![Full stacktrace involving PinDMs.start()](https://cdn.discordapp.com/attachments/410787888507256844/946313667727732746/unknown.png).

The vast majority of problems appear to be on-launch.
