### ISSUE TITLE
ServerFolders - Server logos are squares, not rounded

### ISSUE THREAD

**Issue by JacksonFrost13** [mwittrien/BetterDiscordAddons#1445]
![2022-02-24_11-08-51](https://user-images.githubusercontent.com/61029858/155484010-d9ccb90d-b8c6-4df6-be05-fd48cdd8eff7.png)

Don't know what happened, logos just changed their shape, can't find how to turn this back.

Stable 115980 (1ccc219)
BetterDiscord 1.5.2
ServerFolders v6.9.9

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload

**Comment by JacksonFrost13** [comment]
It's stays there. Didn't help

**Comment by NeonLightning** [comment]
was wondering if you could make radius in recoloured a variable to fix this for those of us that want square?
