### ISSUE TITLE
CharCounter is still not appearing in the bottom of the textbox.

### ISSUE THREAD

**Issue by IamNickerson** [mwittrien/BetterDiscordAddons#1447]
**Describe the bug**
CharCounter is still not appearing in the bottom of the textbox.

**To Reproduce**
Latest Version of Discord and BD.

**Expected behavior**
When discord released a shitty update. I tried reinstalling the plugin and BD but still it isn't appearing.

**Screenshots**
It showing a toast error when I enable it.
![image](https://user-images.githubusercontent.com/61643704/155636559-5cffd083-85f8-49f3-9e5a-50a17cfe12c3.png)

And after that it doesn't appear
![image](https://user-images.githubusercontent.com/61643704/155636680-853a8692-a14c-488e-9ac1-6470a56869bf.png)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable
**Additional context**
It could have been toast error which have caused it.

**Comment by mwittrien** [comment]
Works fine for me, might be a plugin conflict

**Comment by mwittrien** [comment]
And that Toast error is caused by BDs Toasts not mine
