### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by arinoki** [mwittrien/BetterDiscordAddons#1448]
**Describe the bug**

Some random text "__BDFDB__PLACEHOLDER__" on every youtube video. 

**To Reproduce**

On every posted YouTube video.

**Expected behavior**

I guess it shouldnt appear.

**Screenshots**

https://i.imgur.com/vn6mXCD.png

**Discord Build (stable, ptb or canary):**

Stable

**Additional context**

Not sure if this is conflict with one of my other installed plugins, but providing full list.

BDFDB v2.2.1 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Library/
Better Media Player v1.2.3 - https://github.com/unknown81311/BetterMediaPlayer
BetterFriendList v1.4.4 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/BetterFriendList/
BetterRoleColors v0.8.17 - https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/master/Plugins/BetterRoleColors/BetterRoleColors.plugin.js
BiggerStreamPreview v1.4.4 - https://github.com/jaimeadf/BetterDiscordPlugins/tree/release/src/BiggerStreamPreview
CompleteTimestamps v1.6.1 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CompleteTimestamps/
CreationDate v1.4.6 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CreationDate/
DiscordFreeEmojis v1.4.0 - https://github.com/An00nymushun/DiscordFreeEmojis
DoNotTrack v0.0.7 - https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/master/Plugins/DoNotTrack/DoNotTrack.plugin.js
Double Click to Edit v9.3.2 - https://github.com/Farcrada/DiscordPlugins/blob/master/Double-click-to-edit/DoubleClickToEdit.plugin.js
EmojiUtilities v0.0.9 - https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/master/Plugins/EmojiUtilities/EmojiUtilities.plugin.js
Freemoji v1.7.1 - https://github.com/QbDesu/BetterDiscordAddons/blob/potato/Plugins/Freemoji
GameActivityToggle v1.0.8 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/GameActivityToggle/
HideDisabledEmojis v0.0.7 - https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/HideDisabledEmojis/HideDisabledEmojis.plugin.js
ImageUtilities v4.5.8 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ImageUtilities/
InvisibleTyping v1.2.0 - https://github.com/Strencher/BetterDiscordStuff/blob/master/InvisibleTyping/InvisibleTyping.plugin.js
JoinedAtDate v1.3.3 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/JoinedAtDate/
LastMessageDate v1.2.8 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/LastMessageDate/
MemberCount v2.2.16 - https://github.com/Arashiryuu/crap/blob/master/ToastIntegrated/MemberCount/MemberCount.plugin.js
MessageLoggerV2 v1.8.13 - https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/MessageLoggerV2/MessageLoggerV2.plugin.js
MessageUtilities v1.9.2 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/MessageUtilities/
OnlineFriendCount v2.0.0 - https://github.com/Zerthox/BetterDiscord-Plugins/tree/master/src/OnlineFriendCount
QuickMention v1.0.3 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/QuickMention/
ReadAllNotificationsButton v1.7.0 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReadAllNotificationsButton/
RemoveBlockedUsers v1.3.8 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/RemoveBlockedUsers/
ServerDetails v1.1.2 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerDetails/
ShowHiddenChannels v3.0.6 - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ShowHiddenChannels/
XenoLib v1.4.4 - https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/1XenoLib.plugin.js
ZeresPluginLibrary v2.0.2 - https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

And yes, I use BetterDiscord, not some other ( https://github.com/BetterDiscord/BetterDiscord ), if this matters.

**Comment by favna** [comment]
Just chiming in that I get the same, here is a screenshot of the inspected element if it helps:

![image](https://user-images.githubusercontent.com/4019718/155837008-4be0c59a-d92a-4de6-a4b6-ce7775ec5a6e.png)

My own plugin list is:
- BDFDB v2.2.1
- Better Media Player v1.2.3
- BetterMessageLinks v1.4.9
- BetterNsfwTag v1.2.8
- CallTimeCounter v0.0.3
- CompleteTimestamps v1.6.1
- CreationDate v1.4.6
- Double Click To Edit v9.3.2
- FileViewer v1.0.2
- GrammarCorrect v1.0.0
- HideStreamPreview v0.0.5
- ImageUtilities v4.5.8
- JoinedAtDate v1.3.3
- QuickMention v1.0.3
- RemoveChatButtons v1.1.2
- ShowBadgesInChat v1.8.6
- StaffTag v1.4.9
- WhoReacted v1.2.3
- WriteUpperCase v1.3.4
- ZeresPluginLibrary v2.0.2
