### ISSUE TITLE
[BUG] - ImageUtilities 4.6.1 images behaviour

### ISSUE THREAD

**Issue by iZ3C0LD7** [mwittrien/BetterDiscordAddons#1459]
**Describe the bug**
Unable to view non-embed images

**To Reproduce**
When trying to view an image that is not an embed element

**Expected behavior**
To click into the photo like normally would

**Screenshots**
It works fine/normal when clicking into an image inside an embed:
![image](https://user-images.githubusercontent.com/72100942/156525575-c2095013-c0b4-4139-b7fb-e1b7afb8b238.png)
![image](https://user-images.githubusercontent.com/72100942/156526101-e6023646-0be1-4bc7-af5c-cbdd73adc9ab.png)

But then when you click an image that is sent directly as a message, nothing happens:
![image](https://user-images.githubusercontent.com/72100942/156525712-c35049cb-418c-4ac2-860a-7c4ceafe937e.png)

**Discord Build (stable, ptb or canary):**
Stable 117069 (ffa9cf8)

**Additional context**
Not sure if it's just me but it's kind of annoying that you can't view an image in a larger size within Discord itself

**Comment by Aaeeschylus** [comment]
Can confirm, I am having this as well. Embedded images also dont have the "save image as" option in the right click menu (when not in full screen)

**Comment by Drflash55** [comment]
The only way around this is through the context menu, but yes, this is a current issue on V4.6.2.

Images that are embedded from a link (such as Twitter) are perfectly viewable. Uploaded images however can't be clicked on to view them, and can only be seen in full through the context menu button, "View Image".

**Comment by fowlis** [comment]
I did some troubleshooting to find the actual issue of this problem (which nobody seems to have done)
Boiled it down to the "Show Image Details as Tooltip in the Chat" setting. Disabling this should fix this issue until it's fixed properly.
