### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities : Remove the margin around the chat placeholder

### ISSUE THREAD

**Issue by Kanta0611** [mwittrien/BetterDiscordAddons#1461]
**Describe the solution you'd like**
The imagedetails chat placeholder is taking way too much space, the better thing to do would be to bring it closer, and not adding so much margin to its bottom

**Describe alternatives you've considered**
- I think removing the margin like [this](https://i.imgur.com/zoN9oKz.png "Preview with 0rem margin") could be a good option. It has a margin on the top and bottom set to 0.
- Another good looking solution would be [this](https://i.imgur.com/qzoYXZc.png "Preview with 0rem margin-bottom"), where only the margin-bottom is set to 0.
In both cases, it reduces the margin, as discord already has plenty with the message gaps and the attachment gaps.

**Additional context**
- First exemple :
![First example](https://i.imgur.com/zoN9oKz.png "Preview with 0rem margin")

- Second exemple :
![Second example](https://i.imgur.com/qzoYXZc.png "Preview with 0rem margin-bottom")

**Comment by mwittrien** [comment]
The plugin doesnt add any margin

The margin is done by discords altText class which is a native class, change it with css if you dont like it
