### ISSUE TITLE
[IMPROVEMENT] - Automatic Incoming Translation

### ISSUE THREAD

**Issue by Phaedom** [mwittrien/BetterDiscordAddons#1468]
I don't know if it was intended or not but the translate from others requires you to manually right click and translate each message they send but when they send messages it does not automatically translate in chat. I checked in settings for make sure there was maybe option for it but there is not. If it wasn't intended; could we have automatic translation with out having to right click and translate each message?

**Comment by mwittrien** [comment]
Not possible
