### ISSUE TITLE
[BUG] - Editusers 

### ISSUE THREAD

**Issue by zzaria** [mwittrien/BetterDiscordAddons#1469]
**Describe the bug**
The profile picture is not changed in the user settings page

**To Reproduce**
In settings menu

**Expected behavior**
Show the new picture set by the user

**Screenshots**
For example
https://preview.redd.it/xlwx539zbrj71.png?width=1443&format=png&auto=webp&s=8de5d5bfd2e5ec5a64706989f83fd21653bfdf9c

**Discord Build (stable, ptb or canary):**
stable

**Additional context**

**Comment by mwittrien** [comment]
Why would it, thats pointless

**Comment by zzaria** [comment]
well it changes the local banner so I assumed they either want both or none
