### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels - move sidebar to the right

### ISSUE THREAD

**Issue by philpax** [mwittrien/BetterDiscordAddons#1472]
**Describe the solution you'd like**
I would like to be able to move the server list sidebar to the right, so that I can have content on the left of my screen and navigation on the right (similar to what I do for Tree Style Tab in Firefox).

Playing around in the inspector, this seems to be trivially possible by moving the sidebar `nav` to after the content:
![image](https://user-images.githubusercontent.com/707827/158056617-c2e80c1a-9c4c-4d3a-9247-cbcdd143510d.png)
![image](https://user-images.githubusercontent.com/707827/158056595-65abf2df-0bbe-4a9f-afbb-66cb37326f99.png)

**Describe alternatives you've considered**
An additional addon that does this. Not sure if it would potentially conflict with anything else, especially around layouting?

**Additional context**
I've had a look for related issues and addons and haven't found any, but I know a search is never truly comprehensive. If I've missed it, please let me know!

**Comment by mwittrien** [comment]
You can change the order of elements on the same level with the css `order` property

**Comment by mwittrien** [comment]
```
.base-2jDfDU {
    order: 1;
}
.guilds-2JjMmn {
    order: 2;
}```

**Comment by philpax** [comment]
Great, but do you have an automatic solution for doing that? Applying a CSS tweak every time I start BD is a bit rough 😅
