### ISSUE TITLE
[BUG] - ImageUtilitiesv4.6.6 by DevilBro

### ISSUE THREAD

**Issue by SSkizz** [mwittrien/BetterDiscordAddons#1473]
**Describe the bug**
Copy Link, Copy Media Link, and Open Link give mp4 links to gifs ( images-ext-2.discordapp.net ) as opposed to the expected gif link.  

**To Reproduce**
Right click a gif and select one of the aforementioned options.

**Expected behavior**
Tenor or discord gif link is copied.

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by mwittrien** [comment]
Because tenor arent real gifs

**Comment by SSkizz** [comment]
This functionality has worked completely fine until the latest update. Could an option be added to disable your plugins Copy/Open Link? Discord's works as intended.

**Comment by mwittrien** [comment]
Tenor gifa have always been mp4

**Comment by SSkizz** [comment]
I used inspect on the tenor website and the img source looks like a gif to me.
https://c.tenor.com/CczqFxpcLxQAAAAC/google-tenor.gif
