### ISSUE TITLE
The default Notif sound bug is back

### ISSUE THREAD

**Issue by Korhu** [mwittrien/BetterDiscordAddons#1476]
On the current version of both Better discord, BDFDB and NotificationSounds. It seems the bug that makes it so the default notification sound plays at the same time as your custom sound, once again. If there's a temp fix I could use that would be appreciated

**Comment by ImDini** [comment]
The only temp fix they will tell you is remove notifications sounds (default ones) in settings which is not any kind of fix let alone temp. Best to just wait and hope it won't take long for fix
