### ISSUE TITLE
Weird setting visual - ReadAllNotification

### ISSUE THREAD

**Issue by IndividualZenbo21** [mwittrien/BetterDiscordAddons#1486]
There is a visual bug on the ReadAllNotification Setting

**To Reproduce**
Just open Setting on ReadAllNotification

**Expected behavior**
weird visual bug like the one below

**Screenshots**
![image](https://user-images.githubusercontent.com/93858454/159623649-811a1712-5e56-4291-9770-70cd0e391c15.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
-

**Comment by mwittrien** [comment]
Thats an issue with your theme or custom css
