### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by cfpwastaken** [mwittrien/BetterDiscordAddons#1487]
**Describe the solution you'd like**
Feature for people to make custom emoji packs.
For example if you made your own full emoji set and want to use them in discord.
Maybe some documentation on how you can do it.

**Describe alternatives you've considered**
I have tried putting my own github link and copy the entire structure from the Google pack but it didnt work :/

**Comment by mwittrien** [comment]
Making a custom set would take ages

I am creating the sets programically,
There are over 4000 emojis

At that point you could just make your own theme
