### ISSUE TITLE
[BUG] - FriendNotifications v1.8.1

### ISSUE THREAD

**Issue by Lelaxlp** [mwittrien/BetterDiscordAddons#1488]
High CPU usage while notifications are shown.

When monitoring CPU usage, for example via Task Manager, the spike lasts exactly as long as the message is on display.
Becomes more noticeable when there are multiple messages on display at the same time.

Discord goes from about 1% CPU usage up to 20%, and with more messages even up to 40% usage.

Version: BetterDiscord Stable

I do notice that it has gotten a little better since the last update of your library (The one that stated that you switched to CSS instead of Discords native notifications), however it still is a pretty major impact on performance, which is why i'm reporting it again.

Greetings, Lelax

**Comment by mwittrien** [comment]
Cant be fixed then
