### ISSUE TITLE
Plugin repo

### ISSUE THREAD

**Issue by Varolyt** [mwittrien/BetterDiscordAddons#149]
That ![image](https://user-images.githubusercontent.com/25888742/50576443-cf3bf200-0e22-11e9-96b6-56aa4bfc5888.png)

**Comment by noammiz007** [comment]
@Varolyt make sure this is disabled
![image](https://user-images.githubusercontent.com/31467235/50626625-f89a7200-0f37-11e9-898b-e9a49778df46.png)

**Comment by Varolyt** [comment]
I thinkk update fixed it

**Comment by steampunko** [comment]
None of these are toggled on for me, but I still have 0/0 plugins...
