### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor/Old Discord Style

### ISSUE THREAD

**Issue by OlsonBolson-net** [mwittrien/BetterDiscordAddons#1490]
**Describe the solution you'd like**
The theme gives a lot of options and everything look great, but it has forced old Discord style: font, logo etc.
It would be awesome if there was an option to turn the old style on/off, just like settings icons.

**Describe alternatives you've considered**
Just get rid of the style completely from the code.

**Additional context**
N/A

**Comment by mwittrien** [comment]
Its a style choice i choose for my themes

**Comment by OlsonBolson-net** [comment]
BlurpleRecolor doesn't have forced style, I think it's pretty cool. Depends on how someone wants to their Discord look like they can change it.
