### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by Endy3032** [mwittrien/BetterDiscordAddons#1491]
**Describe the bug**
When viewing an image in a thread with gallery view on, the plugin constantly tries to search for nearby images in a thread but the thread uses the search endpoint of its parent channel, not the thread itself so the request fails and counts as api spam therefore rate-limiting the user

**To Reproduce**
Make a thread, send some images, make sure the plugin has gallery view on, prepare the network tab in devtool, view an image, see the load of failed requests (also view the image attached)

**Expected behavior**
The plugin uses the parent's channel id for the search request instead of the thread's (might make the plugin show images from other threads in the same parent channel) or just disable gallery view in threads

**Screenshots**
![image](https://user-images.githubusercontent.com/61771609/160352693-df77e808-8374-436d-bf25-1ebc25e7b95a.png)

**Discord Build (stable, ptb or canary):**
Stable 121032 (71d11bc)

**Additional context**
BetterDiscord 1.5.2
Host 0.0.266
OS X 10.15.7 (21.4.0) [12.3 Beta (21E5227a)]

**Comment by themasterswordmaster** [comment]
I have this "Resource is being rate limited" error on channels that arent threads sometimes, and i also get "Missing access" errors sometimes

**Comment by Endy3032** [comment]
just to leave some more infos, after viewing the images for a while, exiting the image doesnt actually exit it, i can still zoom in the image when clicking the middle of the screen (while im not in the img viewer anymore), navigating to other channels lead to "messages failed to load", going to discord.com/api gives me a rate limit message
