### ISSUE TITLE
[BUG] - ShowHiddenChannels - Voice Channels Jump To Top Of Category 

### ISSUE THREAD

**Issue by dottiekh** [mwittrien/BetterDiscordAddons#1493]
**Describe the bug**
VCs jump to the top of the category it's in if the visible permission is denied.

**Expected behavior**
Channel order expected to be kept. 

**Screenshots**
Channel Permission Fully Denied vs. Channel Visibility Permission Granted
![image](https://user-images.githubusercontent.com/34873184/160703197-e6160850-f8fd-4a25-a197-648159629fbb.png)

![image](https://user-images.githubusercontent.com/34873184/160702709-2eaa4dc7-0757-4fd1-b678-1504e08279ee.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by AtakaJak** [comment]
same issue

**Comment by frosty77759** [comment]
Not sure if this is what you're also experiencing but with the plugin on, I no longer have access to any of the channels in even my own servers (none of these are set to hidden in the first place and of course everyone else is able to use them just fine).

![image](https://user-images.githubusercontent.com/82679990/162586293-aba1ecc0-2a2d-4106-9f6f-282d7abaad74.png)

**Comment by kevin-pwt** [comment]
@frosty77759 this isnt the same bug, what you describe is #1506 which is now fixed

**Comment by dottiekh** [comment]
@frosty77759 different bug, you're referring to #1506 which is marked as fixed now

**Comment by frosty77759** [comment]
> @frosty77759 different bug, you're referring to #1506 which is marked as fixed now

oh my bad, ty!
