### ISSUE TITLE
[BUG] - ShowHiddenChannels Not Working

### ISSUE THREAD

**Issue by RDP8** [mwittrien/BetterDiscordAddons#1494]
**Describe the bug**
ShowHiddenChannels doesnt work. 

**To Reproduce**
Whenever I look at servers, there are not hidden channels shown. 
**Expected behavior**
To show hidden channels.

**Screenshots**
Not needed.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None

**Comment by TomasTokaMrazek** [comment]
Same, plugin stopped working after restarting BD. I tried to disable and re-enable all plugins, remove configurations, reinstall plugins, no luck. Console is full of 404 trying to download js assets from official Discord server, might be a API change on Discord side not yet reflected in the plugin, might be completely unrelated. I'm not sure if they're new or not.

```
DevTools failed to load source map: Could not load content for https://discord.com/assets/ed9d63428b4c1714bc4f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1c3f02681958cb5be657.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e6f9882eef4d1fec5ebe.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d88b85aebdfd43faba21.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2beb9088659f624ac99f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by erections** [comment]
same

**Comment by mayank31398** [comment]
Not working for me either.
