### ISSUE TITLE
[Spellcheck] no longer working

### ISSUE THREAD

**Issue by insectdude1258** [mwittrien/BetterDiscordAddons#1498]
spellcheck is not showing up in the right click menu anymore. typos are not getting marked with red line
<img width="187" alt="tyypo" src="https://user-images.githubusercontent.com/24449926/161032067-8b603526-278b-426f-8a04-98ecc866ced7.png">

**Comment by Yashirmare** [comment]
Still not working after the update?

**Comment by NoXPhasma** [comment]
Same for me, it does not work anymore with version 1.5.9.
