### ISSUE TITLE
TopRoleEverywhere - Breaks easily

### ISSUE THREAD

**Issue by OrangutanGaming** [mwittrien/BetterDiscordAddons#15]
Causes Discord to freeze, seems to be when enabled alongside other plugins (especially Permissions Viewer when it's `Show In Popouts` setting is enabled), and tags don't show after switching server

**Comment by koxixehet** [comment]
Ah yes this today also I faced but it was fixed if you turn off Show in popouts.
Also yes tags are not showing especially if you are switching from DM to server and sometimes showing wrong owner tag even though I'm not the owner of the server.
