### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications - An improvement to the Friend-list settings

### ISSUE THREAD

**Issue by TotoShampoin** [mwittrien/BetterDiscordAddons#1502]
**Describe the solution you'd like**
Have the "online, idle, dnd, etc" visible as you scroll through your friends

**Describe alternatives you've considered**
Have it fixed on top, either as they are or as little icons

**Additional context**
I have hundreds of friends on Discord, it can become hard to scroll through all of them

**Comment by mwittrien** [comment]
BetterNotifications? I got no such plugin

**Comment by TotoShampoin** [comment]
I meant FriendNotifications, sorry

**Comment by mwittrien** [comment]
Hovering the checkbox now shows what option its for, redownload BDFDB to enable that
