### ISSUE TITLE
[BUG] - Friendnotifications - Inconsistent notifications

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1507]
**Describe the bug**
Statuses are not being logged consistently.Friends can login using desktop/mobile/browser and the addon does not log their status as online/idle/dnd.Same for logging off. Randomly hours later when friend is already offline for hours,offline notifications are being generated of them going offline.Also when the skipped login happens,any subsequent login are completely ignored until close and re-opening discord

**To Reproduce**
Have friends/strangers in the addon settings

**Expected behavior**
When a user logs on/off via desktop/mobile/browser their status should be logged in the addon window

**Discord Build (stable, ptb or canary):**
PTB: 122979
BD: 1.5.2

**Additional context**
Further the addon used to show which platform was being used in the timelog menu when multiple sessions were being used. If a desktop session logged on and then a mobile session logged in the mobile session would generate a separate notification.currently the 2nd or 3rd session is completely ignored for its on/off state

**Comment by HistoricTheater** [comment]
With the update to Friendnotifications to 1.8.2,no mobile logins/logouts are being documented at all. Previously when i made the ticket,they were *sometimes* being recorded. Now an entire day has happened and there are zero logins or logouts at all after a restart of discord from the updated plugin

**Comment by HistoricTheater** [comment]
Will we ever be getting some stuff to fix this stuff? Or can you inform on what stuff you'd need to diagnose this stuff?

**Comment by mwittrien** [comment]
Ill fix it when i get the time

**Comment by HistoricTheater** [comment]
stuff

**Comment by BlueStarBRS** [comment]
i have the same problem as well nothing is logged and nothing gewt displayed
