### ISSUE TITLE
[BUG] - ShowHiddenChannels/All channels show as locked on Canary despite user permissions

### ISSUE THREAD

**Issue by xastrodyke** [mwittrien/BetterDiscordAddons#1508]
All channels will show as locked, no matter what perms the user has. This includes administrator perms.
User cannot click on channels to show channel contents, but can still use keystrokes to switch between channels.

![image](https://user-images.githubusercontent.com/103280895/162496727-b3d0bda3-84ce-4e10-b687-ffd2c35ac7d5.png)
(context for the image; I have administrator perms in the server shown in this screenshot, none of these channels should show as locked for me.)

Canary (Build 123151 (9ffe958)
BetterDiscord 1.5.2

**Comment by mwittrien** [comment]
Make sure you are using BDFDB 2.2.7 and delete  0BDFDB.data.json in your plugins folder
