### ISSUE TITLE
[BUG] - ShowHiddenChannels - every channel is locked

### ISSUE THREAD

**Issue by Kackos** [mwittrien/BetterDiscordAddons#1509]
**Describe the bug**
Every channel shows as locked and is inaccessible due to them being locked.

**To Reproduce**
With the plugin enabled every channel is locked regardless of permissions, when disabled every channel is unlocked, 
**Expected behavior**
Channels are not supposed to be locked unless role permissions are set to lock them.

**Screenshots**
https://prnt.sc/gaqj0O2t1T-4

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**

**Comment by mwittrien** [comment]
#1508
