### ISSUE TITLE
EditUsers Plugin interfering with the BBD function 'Coloured Text'

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#151]
It appears that the plugin EditUsers appears to interfere with the 'Coloured Text' function, as having the plugin enabled causes the text to be its default colour, despite the Coloured Text option being enabled.

**Comment by mwittrien** [comment]
fixed in 3.1.5

**Comment by Favna** [comment]
@mwittrien Not quite yet it seems. Using v3.1.5 throws a content error: 
![15-59-25_04-01-2019_discord](https://user-images.githubusercontent.com/4019718/50695317-9a0aec00-103c-11e9-9ecb-1490a64e9307.png)

**Comment by mwittrien** [comment]
Works fine for me, make sure to redownload it

**Comment by Favna** [comment]
@mwittrien Had to go for a while but I see you seem to have found the bug in 3.1.6? Regardless downloading that fixed it.
