### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by kobe9115** [mwittrien/BetterDiscordAddons#1510]
**Describe the bug**
Every channel is marked as a locked channel aka hidden when in fact they are not. 

**To Reproduce**
Open Discord

**Expected behavior**
All channels that are not hidden should be shown.

**Screenshots**
[![image](https://user-images.githubusercontent.com/82645171/162535844-1327bb6e-ed7c-41e3-899d-3573b61f63a1.png)
](https://prnt.sc/maRTkh-j2EHF)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I'm an admin, so I can see every channel. Tested this in browser Discord and they were all unlocked aka shown.

**Comment by KilluaYT** [comment]
Can confirm im locked out of every channel in every server im in

**Comment by pyjthon** [comment]
same here

**Comment by Banquo88** [comment]
i can 4th this as witness, i too am locked out
