### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by variablenine** [mwittrien/BetterDiscordAddons#1511]
**All channels appear to be locked, even in my own servers, it doesn't let me access my own channels**

**Just randomly happened upon starting discord just now**
When does the bug occur.

**I expected that to not happen**

**
![image](https://user-images.githubusercontent.com/103234275/162540149-16fa6f2e-f5c0-4fdc-a8f4-78469a0305ce.png)
**

**Discord Build Stable**
Which build of Discord are you using.

**it came at the exact same time that the InAppNotifications plugin broke**

**Comment by jowslive** [comment]
I'm having the same issue, +1 👍

**Comment by prototype464** [comment]
Having the same issue as well just now. All channels in all servers including my own appear to have locked channels :s

**Comment by maddpiratekidd** [comment]
+1 same

**Comment by comfuzzled** [comment]
+1

**Comment by Eartelyna** [comment]
You can navigate between the channels with ALT + Arrow Keys freely but impossible to click them, it's acting as if these were locked

**Comment by comfuzzled** [comment]
You can also type in the channels, as they are not actually locked

**Comment by maddpiratekidd** [comment]
> You can also type in the channels, as they are not actually locked

i cant even get in the channels with the plugin enabled. if i click a notification that takes me to a channel then i can type in it and see it as usual but if i try to click on one nothing happens.

**Comment by comfuzzled** [comment]
> i cant even get in the channels with the plugin enabled. if i click a notification that takes me to a channel then i can type in it and see it as usual but if i try to click on one nothing happens.

Yea, but you can alt arrow key to select other channels, you just can't click them

**Comment by mwittrien** [comment]
#1508
