### ISSUE TITLE
[BUG] - All channels show as locked

### ISSUE THREAD

**Issue by Pabsb** [mwittrien/BetterDiscordAddons#1512]
**Describe the bug**
All channels show as locked regardless if they actually are or not

**To Reproduce**
When plugin is enabled

**Expected behavior**
To be able to look into the channels I normally can see

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 123251
BetterDiscord 1.5.2

**Additional context**

**Comment by Senkodore** [comment]
yes it's is the case for me too

**Comment by giacominox** [comment]
even to me

**Comment by MutlaqAldhbuiub** [comment]
same as well.

**Comment by Xplodin** [comment]
Definitely a plugin issue. Im not seeing this with it disabled

**Comment by Mika-Kyubi** [comment]
After some testing, this seems to be traceable to the ShowHiddenChannels plugin at least on my machine, as when I disable that, and only that, plug-in all other channels unlock.

**Comment by DrMxrcy** [comment]
Same issue here

**Comment by nippanippa** [comment]
same

**Comment by Godly-Avenger** [comment]
Same here

**Comment by Misterysponge** [comment]
same

**Comment by Hayliel** [comment]
same

**Comment by dragonunitedtm** [comment]
ditto

**Comment by Debuggerz1** [comment]
Quick and dirty fix, All the channels will still show up as locked, This will only allow you to click the channels (keep the plugin useful)

Open the plugin source and comment out lines: 512, 513.

**Comment by abandon-ware** [comment]
> Quick and dirty fix, All the channels will still show up as locked, This will only allow you to click the channels (keep the plugin useful)
> 
> Open the plugin source and comment out lines: 512, 513.

He meant 511 and 512

**Comment by Anonymous6214** [comment]
![圖片](https://user-images.githubusercontent.com/44813050/162555767-c5aa7255-fefb-4907-b479-a7367d10c08d.png)
remove the lock icons and allow clicking the channels

**Comment by fadliaditama** [comment]
Same here

**Comment by mwittrien** [comment]
#1508
