### ISSUE TITLE
[BUG] - ShowHiddenChannels - all channels marked as locked

### ISSUE THREAD

**Issue by NutNutty64** [mwittrien/BetterDiscordAddons#1514]
**Describe the bug**
All channels in all servers are becoming locked and stopping me from clicking into them, meaning I can only type in whatever channel I am already in.

**To Reproduce**
Install plugin and open any server.

**Expected behavior**
Appropriate channels to be accessable.

**Screenshots**
![image](https://user-images.githubusercontent.com/36608223/162558382-de7819c6-4454-44e0-a104-83e1ca3fa10e.png)

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
#1508
