### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by someone19204** [mwittrien/BetterDiscordAddons#1515]
**Describe the bug**
when i enable showhiddenchannels for some reason all channels become hidden (locked) i cant switch between them (despite i can chat and edit messages) but if i turn it off it goes normal

**To Reproduce**
1. enable showhiddenchannels
2. go to a server

**Expected behavior**
only hidden channels should appear with a lock icon

**Screenshots**
![image](https://user-images.githubusercontent.com/88501829/162559012-ef211761-f397-42a3-8672-c5ec3f688d91.png)

**Discord Build (stable, ptb or canary):**
Stable 123305 (2d81cde)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.18363)

**Additional context**
it worked perfectly fine yesterday for me

**Comment by someone19204** [comment]
oops

**Comment by mwittrien** [comment]
#1508
