### ISSUE TITLE
[BUG] - ShowHiddenChannels/All channels show as locked

### ISSUE THREAD

**Issue by slysnake96** [mwittrien/BetterDiscordAddons#1516]
**Describe the bug**
When the plugin is turned on all channels in every server, even my own, show as locked.

**To Reproduce**
Just download the latest version and turn the plugin on then all channels will be locked.

**Expected behavior**
Only hidden channels should show up as locked and not every channel.

**Screenshots**
![2022-04-09 16_39_20-](https://user-images.githubusercontent.com/56527115/162560131-c42d16ec-dd83-4964-acb9-d6f1f6912057.png)

**Discord Build (stable, ptb or canary):**
Stable 123305 (2d81cde)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Additional context**
No additional context needed.

**Comment by slysnake96** [comment]
I see no bugs about this in the issues section and was wondering how I fix this?

**Comment by Matejko06** [comment]
Happens to me too.

**Comment by mwittrien** [comment]
#1508
