### ISSUE TITLE
[BUG] - ShowHiddenChannels - Enabling plugin locks access to all channels

### ISSUE THREAD

**Issue by njubainville** [mwittrien/BetterDiscordAddons#1522]
**Describe the bug**
After enabling the plugin, access to all channels, regardless of previous permissions, is disabled. Tested with all other plugins disabled to ensure no conflictions were causing the issue.

**To Reproduce**
Enable the ShowHiddenChannels plugin.

**Expected behavior**
Hidden channels to appear and show the lock icon prohibiting access to them as opposed to all channels becoming locked.

**Screenshots**
Prior to enabling the plugin:
![45ZWuOw](https://user-images.githubusercontent.com/64258949/162585145-8512036b-6269-4c4d-b001-a46d0056ce7b.png)

After enabling the plugin:
![Kd4BD9q](https://user-images.githubusercontent.com/64258949/162585161-70755d71-c2fb-4d2d-9247-1689b264f701.png)

**Discord Build (stable, ptb or canary):**
Ptb 123373 (c05ebe3)
BetterDiscord 1.5.2
ShowHiddenChannels v3.0.7

**Comment by mwittrien** [comment]
#1508 sigh
