### ISSUE TITLE
[BUG] - ShowHiddenChannels - All channels are marked as hidden

### ISSUE THREAD

**Issue by Jnss98b** [mwittrien/BetterDiscordAddons#1523]
**Describe the bug**
Every channel in every server, no matter actually hidden or not, is marked as hidden by the plugin

**To Reproduce**
Have the plugin enabled (my settings included below for reference)

![image](https://user-images.githubusercontent.com/24306400/162589775-d74cb4cb-56e0-4a8f-b9ec-6980e690fd6b.png)

**Expected behavior**
Non hidden channels should be in their respective categories

**Screenshots**
With the plugin disabled
![image](https://user-images.githubusercontent.com/24306400/162589790-31d41ea7-11ac-4baa-8154-6b000111d0c0.png)

With the plugin enabled
![image](https://user-images.githubusercontent.com/24306400/162589811-088b95dd-4184-492f-86b1-96cdb41d9db0.png)

**Discord Build (stable, ptb or canary):**
Stable 123305
BetterDiscord 1.5.2

**Comment by mwittrien** [comment]
#1508
