### ISSUE TITLE
[BUG] - ServerFolders : settings reset after each update

### ISSUE THREAD

**Issue by KaKi87** [mwittrien/BetterDiscordAddons#1524]
**Describe the bug**
My ServerFolders settings are : close other folder when opening one, do not display folder server count badge.
When updating ServerFolders, those settings are reset so I must redo those each time.

**To Reproduce**
Update ServerFolders

**Expected behavior**
ServerFolders settings are preserved.

**Screenshots**
None

**Discord Build (stable, ptb or canary):**
Stable 123305

**Additional context**
None

---
Thanks

**Comment by mwittrien** [comment]
Just had to reload after the last BDFDB update
