### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by oxocutable** [mwittrien/BetterDiscordAddons#1526]
_Description_
Having audio go for longer than a certain time will cause Discord to crash.  I am unsure of the exact length.  May be less of a bug and more of a limitation, if it cannot be fixed then the maximum file length should be stated somewhere.

*To Reproduce*
Add a long audio file to any notification sound by the GUI or editing the `config.json` file.  I was using a rip of music from a game that was 2:43 in length as my "incoming call" sound.

*Expected behavior*
Expected program to work.  It had worked up to this point for at least three months.

*Discord Build*
Stable 123305 - BD 1.5.2

**Comment by mwittrien** [comment]
Dont add such huge files to the plugin
