### ISSUE TITLE
ServerFolders [Feature Request]

### ISSUE THREAD

**Issue by somerandomuser1** [mwittrien/BetterDiscordAddons#153]
Folder within a Folder.

As a community manager for an online game, I am in MANY discord servers related to the game (currently almost 40 servers) and would love to be able to further organize the servers a bit.

Example: 
Top level Folder "Game Name" > "Guilds/Clans" > servers
Top level Folder "Game Name" > "Dungeon Parties" > servers
Top level Folder "Game Name" > "Other Stuff" > servers

**Comment by mwittrien** [comment]
nope not gonna happen, i am not trying to simulate a foldersystem like an OS
