### ISSUE TITLE
custom remove "by" text

### ISSUE THREAD

**Issue by reynoldyehezkiel** [mwittrien/BetterDiscordAddons#1530]
how to custom the source code to remove "by" text
![image](https://user-images.githubusercontent.com/73789263/163355214-5228490d-18ce-4608-b384-6d71378a4261.png)

**Comment by Geeblish** [comment]
I'd also like to see this. I researched a couple hours and made this code in javascript code

`var element = document.evaluate( '/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div/div/div[1]/section/div[2]/div[1]/div[2]/div[2]/div/div' ,document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null ).singleNodeValue;

  element.textContent = element.textContent.substring(3)`

it finds the element with xpath and deletes the first 3 characters which should be "by "

if anyone can improve on this i'd appreciate it, and I dont know how to turn it into a plugin.

**Comment by Geeblish** [comment]
```
div.details-ntX2k5 div.size12-oc4dx4.subtext-2HDqJ7.interpret-F93iqP div {
    left: -7px !important;
}
```

i use this in custom css, works fine for me

**Comment by reynoldyehezkiel** [comment]
thank you
