### ISSUE TITLE
Show Hidden Channels for Better Discord

### ISSUE THREAD

**Issue by DraconicEssence** [mwittrien/BetterDiscordAddons#1531]
When the "Show Hidden Channels"  is enable/on ALL discord channels are locked regardless of permissions. (Just reinstalled the plugin thinking it would re-fix it, turns out it as of now typing this wont even work regardless of it being or or not....)

**To Reproduce**
When the plugin is enabled.

**Expected behavior**
Plugin doesnt work regard of the Show Hidden Channels button is "On/Off"

**Screenshots**
https://gyazo.com/1e44fce06790bf4c04c3442a7c4afcc9 (Working last night of 4/14/2022 at 10:38PM CST)
https://gyazo.com/cd158143027c742f182968fb1c0d4ee8: before i Re-installed the plugin
https://gyazo.com/36498af0071d7f9846bb7e271a798dde Turned on
https://gyazo.com/90d3a384698c812cbad18f2028922489 ALL channels locked.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Would love to have this fixed, as i can have a better idea on how to "organize" channels( As it's interesting to see how people setup their channels)

**Comment by mwittrien** [comment]
#1508
