### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedUsers - Adding IDs for Silent Removal

### ISSUE THREAD

**Issue by Geeblish** [mwittrien/BetterDiscordAddons#1532]
I'd like to see an option for the plugin to write the ids of users into the config.js, so that I'd be able to input my own set of IDs to remove them from Discord but not show that I actually blocked them.

Looked into the code and saw it uses BDFDB to find blocked users, don't know enough js to do it on my own...
`BDFDB.LibraryModules.RelationshipStore.isBlocked` or something

![p4NqJPQXxe](https://user-images.githubusercontent.com/60635068/163525239-a946612c-fb4d-4e11-b1ea-1465e9ff05db.png)

**Comment by mwittrien** [comment]
This would be case for a new plugin, i dont take plugin requests right now
