### ISSUE TITLE
No sounds playing - NotificationSounds

### ISSUE THREAD

**Issue by Hermitcrack** [mwittrien/BetterDiscordAddons#1535]
**Describe the bug**
NotificationSounds does not work, instead removes ALL discord sounds.

**To Reproduce**
Simply have the plugin turned on, wait for a ping or a DM, or mute/deafen yourself. You will notice no sound is being played. 

I'm running stable discord, no other plugins are turned on.

**Comment by MrJktra** [comment]
Same issue here.

**Comment by Basic6969** [comment]
> **Describe the bug** NotificationSounds does not work, instead removes ALL discord sounds.
> 
> **To Reproduce** Simply have the plugin turned on, wait for a ping or a DM, or mute/deafen yourself. You will notice no sound is being played.
> 
> I'm running stable discord, no other plugins are turned on.

same issue

**Comment by Mabadman** [comment]
+1
