### ISSUE TITLE
[IMPROVEMENT] - WriteUpperCase

### ISSUE THREAD

**Issue by Saltssaumure** [mwittrien/BetterDiscordAddons#1538]
**Describe the solution you'd like**
 I type words that begin with lowercase frequently, like mATX, osu!, and variable names. It would be convenient to not have to click the button to enable/disable the plugin every time.
Possible solutions:

- A keyboard shortcut to enable/disable the plugin.
- Visible keyboard navigation ring so that Discord's included tab/shift+tab controls can be used without guesswork, as seen on the GIF button:
![image](https://user-images.githubusercontent.com/29710355/163707708-68112df2-5d1e-427b-87c2-c5fce874b7cf.png)

- User customisable list of excluded words that will never be capitalised.

**Comment by mwittrien** [comment]
Just hit space before typing something
