### ISSUE TITLE
ShowNames

### ISSUE THREAD

**Issue by Tharki-God** [mwittrien/BetterDiscordAddons#1540]
**Describe the solution you'd like**
If the role color and color of the background are similar to some level then invert the color.

**Describe alternatives you've considered**

**Additional context**
cant see names when they are same color as background and its mostly because of the role color. so need to patch the role. make it seem visually that its opposite color

**Comment by Tharki-God** [comment]
> What plugin are you talking about

this is a plugin request

**Comment by mwittrien** [comment]
I am not taking plugin requests

**Comment by Tharki-God** [comment]
I tried making the plugin but I lack the knowledge so came here.
my plugin - [ShowNames.plugin.js](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/ShowNames.plugin.js)
