### ISSUE TITLE
[IMPROVEMENT] - TRANSLATOR add configs for engines

### ISSUE THREAD

**Issue by aaronliu0130** [mwittrien/BetterDiscordAddons#1542]
**Describe the solution you'd like**
Add configs/settings to specify which engines you want to use e.g. google/deepl.

**Describe alternatives you've considered**
Edit the source code. This isn't that easy, and I have failed. editing the `engines: {` key seems to have no effect, as it still just pops out translating google for a centisecond.

**Comment by mwittrien** [comment]
Maybe use the translation settings? Click the google icon in the chat bar

**Comment by aaronliu0130** [comment]
@mwittrien I've already tried that, of course. There's no such setting.

**Comment by mwittrien** [comment]
https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Plugins/Translator/_res/screenshot5.png

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/164718405-3d6f4fa7-40f7-4634-a2a4-1b469a4f6460.png)

**Comment by aaronliu0130** [comment]
Hmm that's strange, I do not see those.
![image](https://user-images.githubusercontent.com/11874211/164718893-d79dd68c-49ab-41a4-8a26-e22023aa3b27.png)
![image](https://user-images.githubusercontent.com/11874211/164718942-8b4b65d7-eade-40f6-aa5f-6ef77d00a891.png)

**Comment by aaronliu0130** [comment]
@mwittrien is there any update on this here?

**Comment by mwittrien** [comment]
I told you to click on the GOOGLE icon in the BOTTOM RIGHT in your message bar
