### ISSUE TITLE
[Plugin is uploading file to every channel instead of just one] - Chat Aliases

### ISSUE THREAD

**Issue by GamyIan** [mwittrien/BetterDiscordAddons#1543]
**Describe the bug**
When uploading a file using alias, the file is put into all channels of every server but not sent, instead of just the channel you want to send it in.

**To Reproduce**
- Set up an alias which uploads a file 
- Use the alias in a server

**Expected behavior**
Its supposed to send the message only in that one channel

**Screenshots**
I used the alias in #bot-commands but the file upload comes onto every channel in every server.
![image](https://user-images.githubusercontent.com/73981521/164733992-cadd38ad-d755-4eea-9f53-1d1b3125d809.png)
![image](https://user-images.githubusercontent.com/73981521/164733996-93bdff82-9ed3-46a3-8504-99ae9c1ea069.png)

**Discord Build (stable, ptb or canary):**
Stable 124979 (80e9bf7)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Additional context**

**Comment by GamyIan** [comment]
its not fixed, I just checked.

**Comment by mwittrien** [comment]
Maybe update the plugin??

**Comment by GamyIan** [comment]
oh sorry, my bad the update literally just popped up for me, yeah its fixed now 👍🏻 .
Thanks for all your work, I really love the plugin ❤️
