### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds Suggestion

### ISSUE THREAD

**Issue by K-eistra** [mwittrien/BetterDiscordAddons#1545]
I want the ability to edit the "Discordo" sound effect which comes on startup if you've executed that easter egg of course, but still.

I don't know if this is either possible or very complicated so it's just a suggestion I would like for you to at least think about.

I sort of know this isn't exactly a notification sound, but it sort of counts as a notifier for discord being opened so idk. I'd say it counts.

**Comment by mwittrien** [comment]
Plugins only run after Discord booted so the sound plays before the plugin is loaded

So there is no point in changing it

**Comment by K-eistra** [comment]
I was about to add: Now if this were to be considered, but wouldn't work because that sound effect is played before the plugins properly load then id suggest for the user to turn of their "Discordo" sound effect and allow this plugin to just play its own sound from a function or something instead which would load after plugins are done loading.

**Comment by mwittrien** [comment]
Thats not the point of the plugin tho

**Comment by K-eistra** [comment]
Oh well thx for reading and replying anyway. Though could I ask if I were to make a plugin of my own that only adds this function if you have a suggestion on how I would go about doing so? If not that's completely fine and have a great rest of your day.

**Comment by mwittrien** [comment]
Just play the sound when the plugin is started

**Comment by K-eistra** [comment]
Yeah about that. Im not too experienced with it. Is it as simple as to add "var x = new Audio('example.mp3')" and "x.play()" in the start() function?

**Comment by mwittrien** [comment]
```
var audio = new Audio();
audio.src = url;
audio.play();
```

**Comment by K-eistra** [comment]
![image](https://user-images.githubusercontent.com/98384580/164894176-5e99da62-5039-46d9-b3d1-05102c7a39dc.png)
Am i doing this wrong?

**Comment by K-eistra** [comment]
anyways thanks for helping out to begin with

**Comment by mwittrien** [comment]
`/Test.mp3` isnt a valid url

**Comment by K-eistra** [comment]
does it go by online links then? or do I need to maybe get rid of the /. ill test a bit.

**Comment by mwittrien** [comment]
Online links

You cant access local files

**Comment by K-eistra** [comment]
Okay thx ill upload my sound file to some online library then.

**Comment by K-eistra** [comment]
It works! Thank you so much!

**Comment by K-eistra** [comment]
As to not waste more of your time than necessary as I want to make a small config with the option to choose one or another sound for this, where did you read up to create plugins?
