### ISSUE TITLE
[BUG] - SHOW HIDDEN CHANNELS

### ISSUE THREAD

**Issue by XHesaX** [mwittrien/BetterDiscordAddons#1547]
**Describe the bug**
when you try to open user info in locked channel you can't

**Expected behavior**
it's shows you the user info

**Discord Build (stable, ptb or canary):**
stable , last update

**Additional context**
I noticed that from the last update of the plugin

**Comment by mwittrien** [comment]
What do you mean, can you show a screenshot?

**Comment by makemedie** [comment]
> What do you mean, can you show a screenshot?

same problem, users unclickable with left click, and now you cant see if user muted

**Comment by makemedie** [comment]
> What do you mean, can you show a screenshot?
i back in 3.0.8 version and all fine

**Comment by mwittrien** [comment]
#1544
