### ISSUE TITLE
[BUG] - SplitLargeMessages

### ISSUE THREAD

**Issue by Methosss** [mwittrien/BetterDiscordAddons#1548]
**Describe the bug**
it failed to send message due to slowmode

**To Reproduce**
on chat

**Expected behavior**
popup with "message send failed, saved at: %locale%"

**Screenshots**
i don't have it happened too fast

**Discord Build (stable, ptb or canary):**
stable

**Additional context**

**Comment by mwittrien** [comment]
Well dont use it in slowmode channels

Methosu ***@***.***> schrieb am Mo., 25. Apr. 2022, 16:57:

**Comment by mwittrien** [comment]
Well dont use it in slowmode channels
