### ISSUE TITLE
[IMPROVEMENT] - User created categories

### ISSUE THREAD

**Issue by marcus-universe** [mwittrien/BetterDiscordAddons#1550]
### User created categories
Besides favourites, it would be cool if you could create your own categories to better manage long friend lists. 
Maybe as a dropdown when right-clicking a friend or with some custom roles. 😊

**Comment by mwittrien** [comment]
Maybe try PinDMs which lets you create your own categories for direct messages

**Comment by marcus-universe** [comment]
> PinDMs

Oh nice, thank you for this tip. 😊👍
