### ISSUE TITLE
[BUG] - Users informations get stacked

### ISSUE THREAD

**Issue by XHesaX** [mwittrien/BetterDiscordAddons#1551]
**Describe the bug**
Users informations get stacked & no user roles

**To Reproduce**
When you click more than user info without closing the first one

**Expected behavior**
The first user info closes before the 2nd one show & you can see the user roles
**Screenshots**
https://i.imgur.com/WHsJfpC.png

**Discord Build (stable, ptb or canary):**
stable

**Comment by XHesaX** [comment]
update : you can also can't know if the user's mic is muted or not

**Comment by mwittrien** [comment]
Thats intentional
