### ISSUE TITLE
[BUG] - ServerFolders extra column not showing up

### ISSUE THREAD

**Issue by CapoFantasma97** [mwittrien/BetterDiscordAddons#1554]
**Describe the bug**
With the extra columns settings enabled, pressing on a server folder does not show the extra column and the servers within, therefore not allowing to access them. Disabling the setting makes the folder work as intended like in vanilla.

Restarting Discord does not solve it.

**Screenshot**
![immagine](https://user-images.githubusercontent.com/9368910/166062246-15788f53-5af6-4cc9-a64e-0f70da7090a2.png)

**Discord Build (stable, ptb or canary):**
Stable 126343 (75c5ca1)
BetterDiscord 1.5.3

**Comment by kuyajoseph** [comment]
experiencing this same issue

**Comment by ollivender** [comment]
same problem

**Comment by Hexishu** [comment]
same here

**Comment by TabiZz** [comment]
same here

**Comment by YametehKudasaii** [comment]
im experiencing the same issue
