### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by zohaad** [mwittrien/BetterDiscordAddons#1556]
**Describe the solution you'd like**
Noto Emoji font added, it's a new black&white font from google: https://fonts.google.com/noto/specimen/Noto+Emoji

**Additional context**
https://fonts.googleapis.com/css?family=Noto+Emoji

**Comment by mwittrien** [comment]
EmojiReplace pulls its data from emojipedia, unless its on emojipedia there wont be support
