### ISSUE TITLE
[BUG] - Edit users

### ISSUE THREAD

**Issue by Johannes7k75** [mwittrien/BetterDiscordAddons#1557]
**Describe the bug**
Name not showing if changed and wathcing a stream of the person.

**To Reproduce**
The bug is every time i change the name and watch a stream.

**Expected behavior**
The name is the name i changed it to.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57235955/166159999-b8a1562e-3b0d-47fa-84e5-4fb1badb125e.png)
Here the bane should be "Vincent"

**Discord Build (stable, ptb or canary):**
Stable (126462)

**Additional context**
--

**Comment by Ephenia** [comment]
Edited user names also don't show up in places anymore like when searching for users through finding and searching for conversations,. It will also overload the console with errors when searching as well.
