### ISSUE TITLE
[BUG] - Translator 2.3.8

### ISSUE THREAD

**Issue by Siaomo** [mwittrien/BetterDiscordAddons#1558]
**Describe the bug**
I use DeepL will not be able to translate, and display this error

**To Reproduce**
I type Chinese text and send the text to be translated into English

**Expected behavior**
I heard others say that DeepL translates better than the narrative method, I hope to fix this problem of inability to translate

**Screenshots**
![image](https://user-images.githubusercontent.com/78332860/166177714-3459ab9c-2669-45d2-85f5-8021605c4330.png)

**Discord Build (stable, ptb or canary):**
BetterDiscord 1.5.3 & Translator 2.3.8

**Comment by mwittrien** [comment]
??

It clearly says that the Request Limit is reached
Use another engine
