### ISSUE TITLE
[BUG] - ServerFolders - Folders not showing up

### ISSUE THREAD

**Issue by Mudxiej** [mwittrien/BetterDiscordAddons#1559]
**Describe the bug**
The folders aren't showing up.

**To Reproduce**
When does the bug occur.
Idk how

**Expected behavior**
It should work normally

**Screenshots**
Here:
![Zrzut ekranu 2022-05-02 101655](https://user-images.githubusercontent.com/82979937/166205194-9f6509bb-d7b5-4b31-8c3d-00107839df5e.png)
https://user-images.githubusercontent.com/82979937/166205188-f7afffae-f24e-411b-bade-871ae3823180.mp4

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable

**Additional context**
It just happend, idk how. I wasn't touching the plugin or other things.

If logs are needed, tell me. I will send them

**Comment by mwittrien** [comment]
Update BDFDB plugin

MudxiejPL ***@***.***> schrieb am Mo., 2. Mai 2022, 10:20:

**Comment by Mudxiej** [comment]
> 

But i have it to version 2.3.4, and on your github its 2.3.0, so its outdated
![image](https://user-images.githubusercontent.com/82979937/166213069-ea344f15-090b-4b47-b719-bcc4450432a8.png)
![image](https://user-images.githubusercontent.com/82979937/166213086-09c12b07-1d06-4bdc-9dce-c9bcc4675f80.png)

**Comment by Mudxiej** [comment]
Just a proof, or om stupid or sth
![image](https://user-images.githubusercontent.com/82979937/166213242-6d65e943-07dd-4fcb-9228-c9a543768d48.png)

**Comment by mwittrien** [comment]
https://github.com/mwittrien/BetterDiscordAddons/blob/master/Library/0BDFDB.plugin.js

**Comment by Mudxiej** [comment]
As i mention, i have this plugin installed.
![image](https://user-images.githubusercontent.com/82979937/166226900-3ea1c0d6-6c52-4007-8daa-0c17ebbf174a.png)
This is the same ss as higher

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json in your plugins folder and reload

**Comment by Mudxiej** [comment]
Yay, it worked. tysm!
