### ISSUE TITLE
[BUG] - SpotifyControls React Component Error

### ISSUE THREAD

**Issue by elijaholmos** [mwittrien/BetterDiscordAddons#1561]
**Describe the bug**
"React Component Error" where spotify control panel should be

**To Reproduce**
Launch Discord
Start playing spotify

**Expected behavior**
Spotify control panel should properly appear as it has in the past

**Screenshots**
![image](https://user-images.githubusercontent.com/35435704/166831405-fad0cdc0-af0a-4939-9a44-25656d86c8e0.png)

**Discord Build (stable, ptb or canary):**
Stable 126739 (ac0c5ec)
BetterDiscord 1.5.3
Host 1.0.9004
Windows 10 64-Bit (10.0.19043)

**Additional context**
Problem began after I updated XenoLib to 1.4.7 and reloaded Discord as prompted. Unsure if that is related.
Console error:
![image](https://user-images.githubusercontent.com/35435704/166831811-25b1ac6c-4f8e-43f7-b54e-ee176086bbfd.png)

**Comment by Auron-FFX** [comment]
Having the same issue with the showhiddenchannels plugin when trying to access the channel accessibility menu

**Comment by Auron-FFX** [comment]
![bd2](https://user-images.githubusercontent.com/56524831/166837447-2d9cd659-dda6-48ab-86da-161df3261336.jpg)

**Comment by qfoxb** [comment]
Having this issue as well

**Comment by qfoxb** [comment]
@Auron-FFX might want to edit that post, pretty sure that's your spotify token in the image

**Comment by Exaed** [comment]
Also have this issue

**Comment by MastermindKirbo** [comment]
Also having this issue

**Comment by rileywilliam08** [comment]
![WaQbolQr](https://user-images.githubusercontent.com/93229552/166859762-61d24cdb-41ea-4b2d-8e65-8c55e6f58b16.gif)

**Comment by squidtoken** [comment]
also having this issue, what the heck

**Comment by MR3mbiozz** [comment]
also having this issue :(
