### ISSUE TITLE
[BUG] [FIXED] - PLUGIN EDIT USERS NOT WORKING

### ISSUE THREAD

**Issue by squidtoken** [mwittrien/BetterDiscordAddons#1563]
**Describe the bug**
REACT COMPONENT ERROR

**To Reproduce**
When you go to use the plugin "Local User Settings", it gives a react component error.

**Expected behavior**
When you go to use the plugin "Local User Settings" (by right clicking your name/persons name to open the pop out menu for "view profile, close DM" options) it would open a menu to locally edit yourself/persons.

**Screenshots** 
 ![2022-05-06](https://user-images.githubusercontent.com/50829236/167068101-0170c491-c02e-46ed-a627-bd632e13393f.png)
![2022-05-06 (1)](https://user-images.githubusercontent.com/50829236/167068248-06e38a7f-54a6-4ced-9eb3-cf600c2c3b8f.png)

**Discord Build (stable, ptb or canary):**
Stable 126739 (ac0c5ec)
BetterDiscord 1.5.3
Host 1.0.9004 
Windows 10 64-Bit (10.0.19044)

**Additional context**
console error: 
![2022-05-06 (2)](https://user-images.githubusercontent.com/50829236/167068862-6dbfb157-f049-46fb-beee-7f14020a3b8d.png)

**Comment by Auron-FFX** [comment]
having the same issue. could we possably get an update from the dev about if this is being looked at?
