### ISSUE TITLE
[IMPROVEMENT] - FRIEND NOTIFICATIONS

### ISSUE THREAD

**Issue by Ryckie** [mwittrien/BetterDiscordAddons#1566]
**Describe the solution you'd like**
For the friend notifications plugin > Toast Notification. It would be nice to see the time of the notification with $time for example showing time it happened or time ago.

**Comment by SHiFTDeL3TE** [comment]
This uses a lot of CPU power when a notification shows up and CPU power decreased when notification is gone.
