### ISSUE TITLE
[BUG] - NOTIFICATION SOUNDS CRASH

### ISSUE THREAD

**Issue by HeyItsCeleste** [mwittrien/BetterDiscordAddons#1567]
NotificationSounds plugin has been crashing my discord recently. (This week)
I'm not sure for why but I have tested with taking out and putting the plugin back in and it seems to freeze and kill my discord.

The crash usually occurs when I launch up discord, it loads all the plugins, and then the client dies. It also happened when reintroducing the plugin after having taken it out.

The standard experience before the crashes start happening was that I loaded up discord, and then it would freeze for at least 2-4 minutes. Everything would have loaded and it worked perfectly from then on. 

I'm using Stable BetterDiscord Version 1.5.3. I have ran a repair yet It did not change the outcome.

**Additional context**
I feel as though the notification sounds plugin was causing my discord to take a long time to load to begin with.
I haven't been counting but discord taking a few minutes to load and "unfreeze" itself has been happening for around a month.
Without the NotificationSounds plugin in the folder, My discord now loads almost instantly with no freezing.

**Comment by mwittrien** [comment]
Delete NotificationSounds.config.json and try to enable the plugin again, you most likely added a hugr sound file to the plugin causing it to freeze up when it tries to load it

**Comment by HeyItsCeleste** [comment]
> 

That seems to have worked! Thank you!
If I can ask, what are these hugr sound files / is there a reason as to why they cause a crash?

**Comment by mwittrien** [comment]
They are the files you added to the plugin via the settings
