### ISSUE TITLE
[BUG] - Edit User - Invisible Text

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1568]
**Describe the bug**
When setting any users local message color settings via the plugin menu,the the users text in chat will turn invisible and not be readable when changing to any color other then "Default"

**To Reproduce**
Edit a users local settings to a non default color,apply settings,go to any text entered in a channel and it will turn invisible

**Expected behavior**
Changing text color in settings should change text color and be readable in chat

**Discord Build (stable, ptb or canary):**
PTB 127539
BD 1.5.3

_this is without any themes or custom css applied_

**Comment by mwittrien** [comment]
Does not occur to me, try with only EditUsers enabled
