### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by pogrammar** [mwittrien/BetterDiscordAddons#1569]
# **Describe the bug**
In server folders, it is not possible to move the server out of the folder once dragged in

# **To Reproduce**
when you try to drag the server out of the folder.

# **Expected behavior**
I should be able to drag-and drop it out of the folder

# **Discord Build (stable, ptb or canary):**
Discord PTB

**Comment by mwittrien** [comment]
Right click > Remove from folder
