### ISSUE TITLE
[IMPROVEMENT] - Add Option to make tags on the right side of user's name in chat (Using the staff tags addon/plugin)

### ISSUE THREAD

**Issue by AbdallahMehiz** [mwittrien/BetterDiscordAddons#1582]
**Describe the solution you'd like**
Add Option to make tags on the right side of user's name in chat so it looks like the one on the member list

**Describe alternatives you've considered**
none really

**Additional context**
make this 
![Screenshot_2](https://user-images.githubusercontent.com/101192926/170453600-ca8d43a0-28e5-498b-8ed2-d1f1dc7ad668.png)

look like this
![Screenshot_1](https://user-images.githubusercontent.com/101192926/170453637-1d21fd37-0f7e-4c5a-9f44-4b2338ebdaf1.png)

**Comment by misspent** [comment]
Great request, I second this

**Comment by mwittrien** [comment]
#1581
