### ISSUE TITLE
[BUG] - SplitLargeMessages

### ISSUE THREAD

**Issue by FlorisFireball** [mwittrien/BetterDiscordAddons#1586]
**Describe the bug**
The console seems to be sending a fatal error for :before and :after in the console.

**To Reproduce**
It gives an error when you type a character in the text box, or focus/unfocus the discord app.

**Expected behavior**
I expected no fatal error ( :P )

**Screenshots**
![image](https://user-images.githubusercontent.com/65396931/171209334-26c1d9c4-dbc6-4881-8ceb-fb7258022a32.png)
![image](https://user-images.githubusercontent.com/65396931/171209382-092a5bce-869e-4cca-b706-6d8739167a01.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I have quite a bunch of plugins; I don't know if that plays a role.

**Comment by mwittrien** [comment]
SendLargeMessages is abolished
Switch to SplitLargeMessages
