### ISSUE TITLE
[SpellCheck] - Ignore language if not known

### ISSUE THREAD

**Issue by Saud-97** [mwittrien/BetterDiscordAddons#1588]
**Describe the solution you'd like**
I write in Arabic, everything I write is underlined in red. Which makes using the plugin so annoying

**Describe alternatives you've considered**
Tried to disable spellcheck for Arabic but there was no option.

**Additional context**
![image](https://user-images.githubusercontent.com/39028181/171740394-ebcfb7d8-ae1d-49cf-bc67-9cbe3d953e96.png)

**Comment by mwittrien** [comment]
There is no way to disable it for certain languages

**Comment by Saud-97** [comment]
Can you elaborate since I noticed there is an option for secondary languages and I can't seem to understand what would be so hard in checking a string if it had any non Primary or Secondary language characters?

**Comment by Saud-97** [comment]
Perhaps add Arabic as a Secondary then if it's less difficult?

**Comment by mwittrien** [comment]
There is no way to know what language someone is writting in programically

**Comment by Saud-97** [comment]
Well there is almost nothing impossible in programming it just depends on how far you are interested on going.

Currently regex and Unicode blocks matching are one of the easiest way to check for a specific language. 

For example Arabic unicode block is

(0600–06FF, 256 characters)

That is one example on regex matching.
[Regular Expression Arabic characters and numbers only](https://stackoverflow.com/questions/29729391/regular-expression-arabic-characters-and-numbers-only)

**Comment by Saud-97** [comment]
Or if you want to ignore non english strings apply a check on english letters. That would be the easier.

[regex - only allow English(lower or upper), numbers, special characters](https://stackoverflow.com/questions/57132303/regex-only-allow-englishlower-or-upper-numbers-special-characters)

```
const isValidPasswordChar = str => {
  const regex = /^[~`!@#$%^&*()_+=[\]\{}|;':",.\/<>?a-zA-Z0-9-]+$/;
  return regex.test(str)
};

console.log(isValidPasswordChar('/'))
console.log(isValidPasswordChar('`1234567890-=;:,./'))
console.log(isValidPasswordChar('HelloPasword1234~!@#$%^&*()_+'))
console.log(isValidPasswordChar('汉字'))

```

**Comment by Saud-97** [comment]
TBH in current condition the plugin is really unusable when it underlines everything and anything when written in an unrecognized language. It should be an easy fix to apply checks on supported languages and ignore non supported languages. That's should be like one of basics.

**Comment by mwittrien** [comment]
> Well there is almost nothing impossible in programming it just depends on how far you are interested on going.

Thats so wrong
