### ISSUE TITLE
[SpellCheck] - Add option to directly show suggestions on top of the context menu

### ISSUE THREAD

**Issue by Saud-97** [mwittrien/BetterDiscordAddons#1589]
**Describe the solution you'd like**
Similar to chrome, add option to directly show suggestions in the context menu. 

**Describe alternatives you've considered**
None.

**Additional context**
This is a screenshot of what I mean by chrome style.

![image](https://user-images.githubusercontent.com/39028181/171740910-d13c27c8-7d3d-4f01-8849-9a4b04b623db.png)

**Comment by mwittrien** [comment]
Not gonna happen, its in the first submenu, thats close enough
