### ISSUE TITLE
[BUG] - Theme Repo

### ISSUE THREAD

**Issue by Nirgranth** [mwittrien/BetterDiscordAddons#1592]
**Describe the bug**
Crashes BD

**To Reproduce**
Update Themerepo

**Discord Build (stable, ptb or canary):**
Stable 130900 (dec9a0b) Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Comment by Zelathis** [comment]
I'm experiencing this issue as well, you beat me to creating a thread for it!
