### ISSUE TITLE
[BUG] - CRASH LAST UPDATE

### ISSUE THREAD

**Issue by Lennskie** [mwittrien/BetterDiscordAddons#1594]
**Describe the bug**
Last update doesn't let you open discord. It crashes the client

**To Reproduce**
Download the latest update and run betterdiscord

**Expected behavior**
No crashes

**Discord Build (stable, ptb or canary):**
Stable

**Comment by 1337cookie** [comment]
Can confirm, removing this plugin stops the crashing.

**Comment by mwittrien** [comment]
#1592
