### ISSUE TITLE
[IMPROVEMENT] - STAFFTAG

### ISSUE THREAD

**Issue by Pearoo-XD** [mwittrien/BetterDiscordAddons#1596]
Maybe you should add an option to change whether or not you want to have the bot-like tag before or after the role icon.

**Comment by mwittrien** [comment]
Role icon?

**Comment by Pearoo-XD** [comment]
yeah the ones you unlock at lvl2 server boost

**Comment by mwittrien** [comment]
Made it so its behind the role icon, should have been like that from the start
