### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1597]
**Describe the bug**
Hidden channels are not visible

**To Reproduce**
Start discord with ShowHiddenChannels installed

**Expected behavior**
Hidden channels should be shown

**Discord Build (stable, ptb or canary):**
Canary 131472
PTB 131472
Plugin 3.1.2
BD 1.5.3

**Comment by fxlsehope** [comment]
I've started to have the same issue as of yesterday.  Currently working with the same discord build as @HistoricTheater

**Comment by VisibleJet** [comment]
Same issue, same build of PTB and BD

**Comment by Jamyyyy** [comment]
Having the same issue too. I use the same build on BD and PTB as the authors in this thread.

**Comment by doqfgc** [comment]
The issue has now appeared on **Stable 131540**.

**Comment by Petey567** [comment]
I am having the same issue, just downloaded it but cannot see hidden channeles

**Comment by ZakkProjects** [comment]
i was fiddling with it for a while.....
not the most optimized way, but if you really need it working before it will be fixed by dev
just replace processChannels method with this:


```
			processChannels (e) {
				if (!e.instance.props.guild || blackList.includes(e.instance.props.guild.id)) return;
				for (const category in e.instance.props.guildChannels.categories) {
					const collapsed = e.instance.props.guildChannels.categories[category].isCollapsed;
					for (const channel in e.instance.props.guildChannels.categories[category].channels) {
						e.instance.props.guildChannels.categories[category].channels[channel].canShow = true;
						if (!collapsed) {
							e.instance.props.guildChannels.categories[category].channels[channel].shouldShow = true;
						} else {
							e.instance.props.guildChannels.categories[category].channels[channel].shouldShow = false;
						}
					}
				}
			}
```

**Comment by 17sergiom2000** [comment]
> i was fiddling with it for a while..... not the most optimized way, but if you really need it working before it will be fixed by dev just replace processChannels method with this:
> 
> ```
> 			processChannels (e) {
> 				if (!e.instance.props.guild || blackList.includes(e.instance.props.guild.id)) return;
> 				for (const category in e.instance.props.guildChannels.categories) {
> 					const collapsed = e.instance.props.guildChannels.categories[category].isCollapsed;
> 					for (const channel in e.instance.props.guildChannels.categories[category].channels) {
> 						e.instance.props.guildChannels.categories[category].channels[channel].canShow = true;
> 						if (!collapsed) {
> 							e.instance.props.guildChannels.categories[category].channels[channel].shouldShow = true;
> 						} else {
> 							e.instance.props.guildChannels.categories[category].channels[channel].shouldShow = false;
> 						}
> 					}
> 				}
> 			}
> ```
> 
> new discord update moved` e.instance.props.categories` and `e.instance.props.channels` into one object `e.instance.props.guildChannels` so everything is now pretty ez. you can also delete getHiddenChannels and probably also hiddenChannelCache

didnt work for me

**Comment by ZakkProjects** [comment]
it have to work, its just not showing the lock icons. Ill just quickly reimplement cache

**Comment by Petey567** [comment]
Is it fixed?

**Comment by Kyrillos-Kamal** [comment]
> reimplement

doesn't work for me too

**Comment by codeharshil19272** [comment]
I am facing the same issue, and I thought that it's just a my device problem. Turns out the plugin doesn't work on both of my laptops.

**Comment by mwittrien** [comment]
Ill fix it once i got the time to
