### ISSUE TITLE
[BUG] - ImageUtilities chat footnote missing

### ISSUE THREAD

**Issue by Mantas-2155X** [mwittrien/BetterDiscordAddons#1598]
**Describe the bug**
Image description chat footnote does not appear

**To Reproduce**
Install imageutilities and enable the footnote option

**Expected behavior**
A footnote with the images description should appear under the image in the chat

**Screenshots**
How it looks like: 
![](https://i.imgur.com/xrJBMFp.png)

How it should look like: 
![](https://i.imgur.com/bdsGU8c.png)

**Discord Build (stable, ptb or canary):**
Discord Stable

**Additional context**
After some debugging I found that removing the 
`&& BDFDB.ReactUtils.findChild(e.returnValue, {name: ["LazyImageZoomable", "LazyImage"]})`
check on line 378 fixes the issue.

I have tried using earlier versions and it still does not work. At some point it used to work months ago but I thought this feature was simply removed until I saw it in another issue.

**Comment by w4tchdoge** [comment]
> **Additional context** After some debugging I found that removing the `&& BDFDB.ReactUtils.findChild(e.returnValue, {name: ["LazyImageZoomable", "LazyImage"]})` check on line 378 fixes the issue.

Thank you for this info, I've been struggling with this for a while now and I'm glad that I can get the image details footer back.
