### ISSUE TITLE
The plugin dosn't work.

### ISSUE THREAD

**Issue by st0lez** [mwittrien/BetterDiscordAddons#1599]
I try enabling and disabling it but it dont work. I tried reparing betterdiscord too but nothing helped. Please fix!

**Comment by ZakkProjects** [comment]
which plugin? new discord update changed some things

**Comment by Kevinyock** [comment]
Could you be more specific?

**Comment by Mikevoir** [comment]
idk which plugin OP means, but at least Hide Muted Categories doesnt work on my end, tried deleting and installing a fresh download, tried reinstalling betterdiscord, tried reinstalling discord, nothing works, all other plugins work correctly.
![image](https://user-images.githubusercontent.com/83087147/172960133-3a97d963-cb31-46fd-b67e-fcc784daa63b.png)
