### ISSUE TITLE
[BUG] - SpotifyControls play button not working

### ISSUE THREAD

**Issue by Andromeda-One** [mwittrien/BetterDiscordAddons#1600]
**Describe the bug**
Clicking the SpotifyControls play button after at least 10 minutes of not playing a song on Spotify results in:
The song not playing.
The play button not changing.
The song's progress bar and timer skipping to the end of the song as though the song finished.
These issues are only in the Discord SpotifyControls plugin, Spotify itself remains as it was.

**To Reproduce**
Click the SpotifyControls play button after at least 10 minutes of not playing a song on Spotify.

**Expected behavior**
I would expect the song to begin playing when I click the play button.

**Screenshots**
Video of bug:
https://user-images.githubusercontent.com/61443228/172955161-396c0c4b-fb64-4b36-8584-c85130998035.mp4

**Discord Build:**
Stable 131246 (fed1161)
BetterDiscord 1.5.3

**Comment by Andromeda-One** [comment]
The same thing will occasionally happen within the 10 minute time, and then very quickly return to normal and play the song.

**Comment by mwittrien** [comment]
Thats because the connection to the device is lost after a certain amount of inacitvitx

**Comment by mwittrien** [comment]
Did not fix it but made it more obvioud what happens
