### ISSUE TITLE
[BUG] - HIDE MUTED CATEGORY

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#1602]
After last updates (stable\ptb\canary) when hiding muted categories the category channels are not hiding anymore

**To Reproduce**
Hide a category

**Expected behavior**
The category channels should be hidden.

**Screenshots**
![2022-06-10_13h21_41](https://user-images.githubusercontent.com/1034673/173054752-2b597b80-3eed-4b10-ac47-27ce128f48cb.png)

**Discord Build (stable, ptb or canary):**
Doesn't work on any of the builds.

Stable 131597 (5b04163)
Ptb 131702 (9a74d11)
Canary 131702 (9a74d11)

**Comment by lts20050703** [comment]
Can confirm doesn't work
Canary 131702 (9a74d11) Host 1.0.47 Windows 10 64-Bit (10.0.25131)

**Comment by OshidaBCF** [comment]
Reeeeeeeee, discord
