### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Meredith666** [mwittrien/BetterDiscordAddons#1603]
**Describe the bug**
ShowHiddenChannels are not again visible

**To Reproduce**
Start discord with ShowHiddenChannels installed

**Expected behavior**
Hidden channels should be shown

**Discord Build (stable, ptb or canary):**
Stable 131597
BetterDiscord 1.5.3
ShowHiddenChannelsv3.1.2

**Comment by mwittrien** [comment]
#1597
