### ISSUE TITLE
[BUG] - ShowHiddenChannels Lag

### ISSUE THREAD

**Issue by Luigi534** [mwittrien/BetterDiscordAddons#1605]
**Describe the bug**
When I activate the new version of the plugins, I have a client lag, and when I deactivate it, I still see the hidden channels. and the hidden channel gives a notification like when you get the role to access it.

**To Reproduce**

1- When I enable ShowHiddenChannels

2- when I enable ShowHiddenChannels and disable it

**Expected behavior**

there should be no lag on the client side, we shouldn't receive notifications on the rooms we don't have access to, and we should make sure that when we deactivate the plugins we don't see the hidden channels anymore

**Discord Build (stable, ptb or canary):**
Stable

**Comment by EtaroX** [comment]
I had the same problem, but when i restarted discord, plugin started working properly except client lag which is still visible
