### ISSUE TITLE
[BUG] - ShowHiddenChannels makes Discord freeze

### ISSUE THREAD

**Issue by stressatoo** [mwittrien/BetterDiscordAddons#1610]
**Describe the bug**
ShowHiddenChannels makes Discord freeze.

**To Reproduce**

1. Open (Better)Discord
2. Enable ShowHiddenChannels
3. Wait 1-5 minutes
4. Discord freezed and it needs a force restart

**Expected behavior**
Obviously, Discord shouldn't randomly crash.

**Screenshots**
Console screenshot
![discordCrashes](https://user-images.githubusercontent.com/60473020/173186683-78bb77da-c2e2-446b-9801-8af103923274.png)

**Discord Build (stable, ptb or canary):**
Stable 131860 (d9eb652)
BetterDiscord 1.5.3
Host 1.0.9005

**Additional context**
.

**Comment by mwittrien** [comment]
#1605
