### ISSUE TITLE
[BUG] - ShowHiddenChannels Bottom ordering doesn't work

### ISSUE THREAD

**Issue by ExterminatorX99** [mwittrien/BetterDiscordAddons#1612]
**Describe the bug**
Sorting hidden channels to the bottom doesn't work

**To Reproduce**
1. Set sort order to bottom.
2. Look at category with hidden channels.
3. Hidden Channels are in native position.

**Expected behavior**
Hidden channels are at the bottom of their category

**Screenshots**
![image](https://user-images.githubusercontent.com/16169502/173252471-f4ad4a5e-590c-46d5-938b-cf8888b476cb.png)

![image](https://user-images.githubusercontent.com/16169502/173252449-6672da38-aec6-4cc3-b510-9b5540d79bc3.png)

**Discord Build (stable, ptb or canary):**
Stable 131860 (d9eb652)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.19043)

**Additional context**
Caused by recent update to fix lag/console spam

**Comment by ExterminatorX99** [comment]
Thank you

**Comment by Karbust** [comment]
It's still not fixed, I'm on version 3.1.5 and it's still showing each individual category in their respective positions and not a single one at the bottom (called Hidden).

**Comment by mwittrien** [comment]
Thats not what the author meant, the separate category eas discontinued

Read the changelog
