### ISSUE TITLE
[BUG] - Error while loading BDFDB

### ISSUE THREAD

**Issue by Paxion3050** [mwittrien/BetterDiscordAddons#1615]
Whenever I open betterdiscord it gives me the error "Could not initiate BDFDB Library Plugin. Check your Internet Connection and make sure GitHub isn't blocked by your Network or try disabling your VPN/Proxy." GitHub isn't blocked by my network and I don't have any VPN/Proxy enabled. I've tried deleting BDFDB and reinstalling it, and reinstalling betterdiscord entirely, yet neither worked.

**Comment by mwittrien** [comment]
If you are expierencing an Issue with BDFDB not initiating, try to download https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.data.json
and
https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.raw.css
and put them in your Plugins Folder. Afterwards reload Discord via Ctrl + R. This should fix the Issue of the Library not loading.
