### ISSUE TITLE
[BUG] - PLUGIN/ShowHiddenChannels(v3.1.7)

### ISSUE THREAD

**Issue by AndreZila01** [mwittrien/BetterDiscordAddons#1619]
**Describe the bug**
Dont show channels voice where am i allowed to see. I question other users and tell can access room.
what see on my discord:
![what see on my discord](https://user-images.githubusercontent.com/56931353/174051750-6f68b2fc-5ad8-4974-b81f-01f1e8e4e8a2.png)

what other users see on discord:
![what other users see on discord](https://user-images.githubusercontent.com/56931353/174051449-085c0875-fbae-4c00-a9cb-50e542619bb3.png)

**To Reproduce**
I have this bug when i activate the plugin ... but if turn off the plugin and reset discord i see the channel.
![reset discord](https://user-images.githubusercontent.com/56931353/174052888-cbe92015-712f-423a-b00d-0050882cf518.png)

**Comment by tryoutuser** [comment]
this could be off topic but in my case, in some servers the hidden channels did not appeared at all, i have tried turning off, reload, turning on, reload, still did not appear in some servers, while several others appeared.
please investigate!

**Comment by Luigi534** [comment]
same except I managed to fix it when I hide a complete category (like admin or news or voicechat or staff category) and re-display it after hiding it.
