### ISSUE TITLE
[BUG] - ImageUtilities - Gallery mode cannot display GIFs

### ISSUE THREAD

**Issue by bestpika** [mwittrien/BetterDiscordAddons#1625]
**Describe the bug**

In gallery mode, if the current image is a GIF, nothing will be displayed.

**To Reproduce**

1. Click on any image that is not a GIF.
1. Use the keyboard arrow keys to navigate back and forth to any GIF file that has not been opened.

**Expected behavior**

It should be displayed as if you clicked directly on the GIF image file.

**Screenshots**

Because the server is more private so I'll explain.
When visiting a GIF that has not been opened, there is nothing in the middle, just blackness.

**Discord Build (stable, ptb or canary):**

Discord | Stable 133074 (7e76a26)
BetterDiscord | 1.5.3

**Additional context**

**Comment by mwittrien** [comment]
Works just fine for me

**Comment by mwittrien** [comment]
Can u take a video

**Comment by mwittrien** [comment]
Can u screenshot your settings for ImageUtilities

**Comment by bestpika** [comment]
```json
{
	"all": {
		"detailsSettings": {
			"footnote": false,
			"tooltip": false,
			"tooltipDelay": 0
		},
		"engines": {
			"_all": true,
			"Baidu": true,
			"Bing": true,
			"Google": true,
			"ImgOps": true,
			"IQDB": true,
			"Reddit": true,
			"SauceNAO": true,
			"Sogou": true,
			"TinEye": true,
			"WhatAnime": true,
			"Yandex": true
		},
		"general": {
			"nsfwMode": true
		},
		"ownLocations": {
			"Downloads": {
				"enabled": true,
				"location": "R:\\tmp"
			}
		},
		"places": {
			"userAvatars": true,
			"groupIcons": true,
			"guildIcons": true,
			"emojis": true
		},
		"rescaleSettings": {
			"imageViewer": "WINDOW",
			"messages": "NONE"
		},
		"resizeSettings": {
			"imageViewer": true,
			"messages": false
		},
		"scaleSettings": {
			"messages": "NONE",
			"imageViewer": "NONE"
		},
		"viewerSettings": {
			"zoomMode": false,
			"galleryMode": true,
			"details": false,
			"copyImage": false,
			"saveImage": false
		},
		"zoomSettings": {
			"pixelMode": false,
			"zoomLevel": 2,
			"lensSize": 200
		}
	}
}
```

**Comment by bestpika** [comment]
In imgur's GIF directly open the URL will be in the file name after more than a mp4, direct click will become a file download, there may be because of this reason?
![image](https://user-images.githubusercontent.com/5698157/176588712-980426e5-06b5-4fad-b8e4-5e4aa3ed8b3a.png)

**Comment by mwittrien** [comment]
No clue, works fine for me

**Comment by bestpika** [comment]
I found the reason, if this setting is turned on it will cause the aforementioned problem.
![image](https://user-images.githubusercontent.com/5698157/178103271-a7062a13-5334-44c5-b3a2-587a5bb4050c.png)

**Comment by mwittrien** [comment]
Alright ill check later
