### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities - Autoblur NSFW Images off by default

### ISSUE THREAD

**Issue by Gwenily** [mwittrien/BetterDiscordAddons#1627]
It was insanely confusing on startup, I thought discord had added a dark pattern to discourage users from participating in nsfw channels, but no, it was image utilities. Secondly, it really is a needless dark pattern. I can totally understand if someone wants to enable this, but it doesn't really make sense as default. If someone clicks on an nsfw channel, typically, they want to see nsfw images unobstructed. As well, it's not so much an image utility as changing the behavior of how spoilering works, which isn't the primarily advertised feature. Lastly, those who previously had the extension installed you could kind of treat as users who have always had it off, and in a way you're kind of changing their settings by having it be automatically on.
I dont mind the feature being there. In fact, I think it may have it's uses; say if you have guests, are in public, are streaming, want to have that stuff always cw'd, etc. Just make it something you have to toggle on instead of the other way around <3

Thank you so much for your time. I know this may seem nitpicky but it genuinely did really confuse me for a second, and i think it would be an improvement to have it be a non-default feature. I had actually gotten mad at the discord for a moment there because i thought it was vanilla, lol.

**Comment by mwittrien** [comment]
Thats what the change log is for, it cleary stated that it was added and that it can be disabled
