### ISSUE TITLE
[BUG] - X Failed to translate. Try another Translator. Daily Request Limit reached. X

### ISSUE THREAD

**Issue by Auditormadness9** [mwittrien/BetterDiscordAddons#1629]
**Describe the bug**
It simply shows this error when trying to translate this message.

**To Reproduce**
Hitting Translate message.

**Expected behavior**
The message gets translated.

**Screenshots**
![image](https://user-images.githubusercontent.com/71278545/175380808-104a57d2-1bbb-4924-a720-d36efe3605ce.png)

**Discord Build (stable, ptb or canary):**
Stable 133377 (0cf2da5)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)

**Comment by mwittrien** [comment]
Not an issue, use another engine

**Comment by mwittrien** [comment]
Click the translate icon in the bottom corner

**Comment by Auditormadness9** [comment]
> Click the translate icon in the bottom corner

Ah I see, thanks!

>Not an issue, use another engine

isn't that kinda the point of Backup Engine? I want it to first try with Deepl and only if it doesn't work then do Google.
