### ISSUE TITLE
[BUG] - ImageUtilities - Embeds' Images

### ISSUE THREAD

**Issue by Duthris** [mwittrien/BetterDiscordAddons#1631]
**Describe the bug**
Due to plugin, all images are being resized as smaller than the original form. When I closed plugin, images are just fine. See on screenshots.

**To Reproduce**
Inside the Image of embeds, all other images like thumbnail, footer etc. on embeds are fine just images.

**Expected behavior**
It was okey up to now. So I'm expecting to have original image size when the plugin is closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/71668283/175652271-b775c42d-fbbb-41fc-8c01-fbe54d923b24.png)
![image](https://user-images.githubusercontent.com/71668283/175652452-39a1872d-92d6-41ce-a58e-982826ecb9b1.png)

I think clearly can be seen the difference. The gray way on the right side is the part that embed ends. On the first ss, plugin is on and cutting image from right side. On second ss, plugin is closed and since its not resizing, embed is filled by image. I've checked resizing options of the plugin and also other settings, however, nothing is on that will cause this problem. 

**Discord Build (stable, ptb or canary):**
Original discord.

**Comment by mwittrien** [comment]
Disable resizing in messages

**Comment by Duthris** [comment]
> Disable resizing in messages

Already disabled.
