### ISSUE TITLE
[`Feature`] Update All, Show/Filter: {Only Active, Only Inactive, All}

### ISSUE THREAD

**Issue by sapioit** [mwittrien/BetterDiscordAddons#1633]
**Describe the solution you'd like**
Open settings page, go to Plugins or Themes page, click an `Update All` button to update all the pending ones without having them auto-enabled. Next to `Sort By` and `Order`, have the option `Show` or `Filter` with the options `All`, `Active` or `Enabled`, and `Inactive` or `Disabled`.

**Describe alternatives you've considered**
Manually updating each and every theme and plugin, then disabling those who were automatically activated by the updating process even though I had them disabled before the updating process. Could take tens of minutes every time, depending on the numbers of themes and plugins.

**Additional context**
When there are plugin or theme updates, having an "update all" option would be nice. For example, I have 22 theme updates (which keep resetting, because my Discord keeps crashing on a certain server), and it would be nice to be able to go in the Themes page of the settings, and update them all with a single click, without needing to click 22 times to update them and 20 times to disable them after the update (since only 2 of them I actively use all the time).

Also, sometimes a plugin or theme interferes with another one and makes the experience worse until it's found, especially after an update which breaks things, so it would be nice to be able to see only the enabled or only the disabled themes or plugins. Same for having lots of inactive plugins or themes and looking for an active plugin or theme whose name you don't remember, to change it's settings. And same for accidentally disabling a plugin or theme and only realizing it after you left the Settings menu, so you have to check the whole list one by one. 

![screenshot 13807](https://user-images.githubusercontent.com/3173159/172359608-25aff267-6ae1-47f5-be80-d4052c307a0a.png)

Note: I was redirected from here: https://github.com/BetterDiscord/BetterDiscord/issues/1316

**Comment by mwittrien** [comment]
Themes page has nothing to do with the ThemesRepo plugin

Your request should be made in the BetterDiscord github

**Comment by sapioit** [comment]
As I mentioned, I was redirected here from the BetterDiscord github.

> Note: I was redirected from here: https://github.com/BetterDiscord/BetterDiscord/issues/1316

**Comment by mwittrien** [comment]
The red bar in the screenshot is from ThemeRepo yes, the "Themes" Page is from BetterDiscord, they arent related

**Comment by mwittrien** [comment]
> Disabling the ones i had disabled before the updating process

You can disable the auto enable in the ThemeRepo settings

**Comment by sapioit** [comment]
> You can disable the auto enable in the ThemeRepo settings

Thanks! I didn't know it was a setting. You might want to make it into 2 different settings, one only applying to themes which are updating, instead of downloading for the first time.
