### ISSUE TITLE
[BUG] - ChatAliases Freezes on Regex

### ISSUE THREAD

**Issue by Jordyn-gif** [mwittrien/BetterDiscordAddons#1634]
**Describe the bug**
Putting `.*` as an an filter and then sending a message to any channel will freeze Discord.

**To Reproduce**
Go to the plugin settings and add a new word, set the replace as .* and put anything in the **With** field, then go to added words and mark it as a regex filter. I disabled exact but I do not think that effects it.

**Expected behavior**
It turns characters into the word (what I thought it would do)

**Screenshots**
No errors or anything in Developer Console.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I am aware that this is kind of stupid and understand why it's freezing, but it should have some sort of method of preventing Discord from freezing because of the plugin.

**Comment by mwittrien** [comment]
No it shouldnt
Simply dont do stupid stuff
