### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps: Option to always show individual message timestamps

### ISSUE THREAD

**Issue by robmonte** [mwittrien/BetterDiscordAddons#1635]
**Describe the solution you'd like**
Currently, Discord does not show the timestamp on all messages. Timestamps either reveal themselves when mousing over a message, or always show _only_ when compact mode is used.

It would be nice to have a toggle included in the plugin settings for "Always show message timestamps on the left" - effectively removing the need to mouse over a message to see its timestamp. 

**Additional context**
It's odd discord forces compact mode for this functionality when the space under user avatars already exists and is simply empty.

**Comment by mwittrien** [comment]
Implementing sth with JS that can be done  eith a css one liner is a huge waste of resources

**Comment by robmonte** [comment]
That makes complete sense, I'm a new user of BD and didn't realize plugins were purely JS. Thanks for educating me.
