### ISSUE TITLE
[IMPROVEMENT] - SpotifyControls 

### ISSUE THREAD

**Issue by 3mptylord** [mwittrien/BetterDiscordAddons#1639]
**Describe the solution you'd like**
Would it be within scope to add a Like button to the 'controls' that are accessible in Discord? Is this even possible? I love this plugin for not having to constantly swap between windows, but I also make liberal use of the 'Heart' button. 

**Describe alternatives you've considered**
I have not considered alternatives. 

**Additional context**
I do not think I've ever seen an embedded player with this feature - so it might not even be possible.

**Comment by mwittrien** [comment]
Not possible since Discord's Spotify Integration only allows song track modification, liking songs is parg of another spotify module discord doesnt use
