### ISSUE TITLE
[BUG] - Show hiddens channels

### ISSUE THREAD

**Issue by Aoki007** [mwittrien/BetterDiscordAddons#1643]
**Describe the bug**
It just doesnt work anymore

i tried to reboot my pc , reinstalling discord and btrdiscord , even tried to reinstall the plugin

**Comment by JimMcBubbles** [comment]
Reproduced issue on my discord.
[plugins - Copy.txt](https://github.com/mwittrien/BetterDiscordAddons/files/9032095/plugins.-.Copy.txt)
