### ISSUE TITLE
[BUG] - notification sounds

### ISSUE THREAD

**Issue by vanquish1** [mwittrien/BetterDiscordAddons#1651]
**Describe the bug**
notification sounds crashes alot

**To Reproduce**
idk just try using it lol

**Expected behavior**
to not crash

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
N/A

**Comment by vanquish1** [comment]
> More Information is required

Most of the time, when attempting to use the plugin a crash will occur. Your discord window will turn gray and freeze until some time has passed and eventually crash. This does differ however.

If the crash does not occur for you, try fiddling with the plugin as a user would use it by changing the configuration etc.

**Comment by mwittrien** [comment]
You most likely added huge sound files overloading discord
