### ISSUE TITLE
hidden channels are showing others not - ShowHiddenChannels

### ISSUE THREAD

**Issue by Mirutus** [mwittrien/BetterDiscordAddons#1653]
Since the update of ShowHiddenChannels today this happened again with the exact same channels:

With the plugin enabled I see the Council of Villains, which I don't have permission to.
![grafik](https://user-images.githubusercontent.com/38052569/173600006-1af4705e-d328-490e-a078-f81fedac3f08.png)
When I disable the plugin and restart discord (in system tray on the discord icon "quit discord") I now see Heroes Feast again, which I have permissions to.
![grafik](https://user-images.githubusercontent.com/38052569/173599929-d81139cc-e14d-410a-b38b-da6c9cd7f95d.png)

Until now I only discovered this one channel that is hidden after I enable the plugin.

_Originally posted by @Mirutus in https://github.com/mwittrien/BetterDiscordAddons/issues/1614#issuecomment-1155261785_

**Comment by iceyf0x** [comment]
im having a similar issue. some channels i dont have perms to show up and i know some are not
