### ISSUE TITLE
[BUG] - Edit Channels Duplicated Menu Entry

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1657]
**Describe the bug**
Right clicking a channel shows 4 "Local Channel Settings" menu options

**To Reproduce**
Right click a channel

**Expected behavior**
Single menu entry

**Discord Build (stable, ptb or canary):**
All

**Comment by Drflash55** [comment]
![image](https://user-images.githubusercontent.com/13694448/177897289-2b5719c7-519d-4c75-9e32-eb72474758c5.png)
Posting screenshot as proof for OP.
