### ISSUE TITLE
[BUG] - Theme Repo Keeps Crashing BetterDiscord...

### ISSUE THREAD

**Issue by JawZz9** [mwittrien/BetterDiscordAddons#1658]
Anytime I have tried to run BetterDiscord it keeps crashing over and over resulting in me not being able to use it, had to go through all my plugins in windows fire explorer to find which plugin/repo was causing my discord to crash continuously and had found that when i uninstalled this repo/plugin it had ceased the crashes and i was able to use BetterDiscord again...

**Comment by mwittrien** [comment]
Doesnt crash for me
