### ISSUE TITLE
[BUG] - PLUGIN/PLUGINREPO Plugin Repo Gets stuck.

### ISSUE THREAD

**Issue by Alexxxxxxxxxxxxxxxxxxxxos** [mwittrien/BetterDiscordAddons#1659]
so basically I keep trying to use the plugin repo but it keeps getting stuck like this. 

https://user-images.githubusercontent.com/81512527/178050476-076eef08-c001-4bef-9c25-1e07fc631d65.mp4

There is a video on the problem so please help me out here.

**Comment by mwittrien** [comment]
Thats most  likely an issue with your internet connection
