### ISSUE TITLE
[BUG] - Server Counter one server off.

### ISSUE THREAD

**Issue by RiftSTW** [mwittrien/BetterDiscordAddons#1661]
**Describe the bug**
It works as intended, but the counter is one-off.

**Screenshots**
![image](https://user-images.githubusercontent.com/33435468/178113002-4545153b-ea3f-4d88-8e80-1bafc646495a.png)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
None.

**Comment by mwittrien** [comment]
No its not
