### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities

### ISSUE THREAD

**Issue by alreadypro** [mwittrien/BetterDiscordAddons#1665]
Add support for screen sharing/streams

**Comment by mwittrien** [comment]
What support

**Comment by alreadypro** [comment]
> What support

On images, it shows a left/right button to go to the previous/next image. For streams & screensharing in group calls or server voice channels, this should just switch to another stream if multiple people are streaming. Another option would be to show all of the streams vertically on the left or right side of the current stream.

![Discord_p0BnvS6pcf](https://user-images.githubusercontent.com/27824159/178775751-a59bba07-4db0-49ed-b863-f9759ec682c7.png)

My friend has an ultrawide and sometimes it is hard to look at something he is trying to show me. It would be cool if there was a 'Fit to Window' feature where it would occupy all of the Y axis and you could click & drag to pan on the X axis, and then scroll to 'Zoom In', with an option to reset

![Discord_x04Rj12N81](https://user-images.githubusercontent.com/27824159/178776286-c36036da-c008-4556-aea9-8ef25fa73009.jpg)

**Comment by mwittrien** [comment]
That sounds more likeca completely new plugin idea
