### ISSUE TITLE
[BUG] - ChatAliases (Media not uploading when using mod)

### ISSUE THREAD

**Issue by GamyIan** [mwittrien/BetterDiscordAddons#1666]
**Description:**
When Uploading a video file through an alias the chatbox just freezes and does nothing, chat box becomes unusable and nothing happens.

**To Reproduce:**
-Setup an Alias to upload media (In my case a video, I don't know if it happens with images and stuff as well).
(Note:- I have "EXACT" "AUTOC" and "FILE" boxes checked in settings and the rest unchecked).
-Send the message through the alias created.

**Expected behavior:**
-The message is supposed to send the media

**Screenshots:**
![image](https://user-images.githubusercontent.com/73981521/178786464-3cb92d36-e967-4721-b0c8-f8d256d2a3d7.png)
![image](https://user-images.githubusercontent.com/73981521/178786541-cbe31e57-5e2b-46c6-8d77-2801920279d1.png)
![image](https://user-images.githubusercontent.com/73981521/178786585-8433b8f7-045e-4866-bc10-99b28a7809f3.png)

**Discord Build:**
Stable 136240 (9a882e6)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)

**Comment by FriendlyUser1** [comment]
I have this issue too on canary

**Comment by FriendlyUser1** [comment]
I have reinstalled betterdiscord and discord and the issue is still there.
There is an error in the console when you try to send any file alias
![image](https://user-images.githubusercontent.com/41965390/179322871-d40d5260-aafe-4295-87e7-8f045e19d690.png)
![image](https://user-images.githubusercontent.com/41965390/179322895-e70d7347-2651-412e-941c-75af133900bd.png)
I only have ChatAliases(v2.3.9) and BDFDB(v2.4.6) plugins

**Comment by GamyIan** [comment]
Thanks for all the information, and for confirming that I'm not the only one having this problem,
I hope this issue gets fixed soon!

**Comment by GamyIan** [comment]
After the update I did today, the file gets stuck at uploading but doesn't actually get sent
![image](https://user-images.githubusercontent.com/73981521/182041631-d6bbec1b-4c7f-4812-83a7-a8960c2398db.png)

**Comment by FriendlyUser1** [comment]
This is also happening for me, and there aren't any errors in the console now
![image](https://user-images.githubusercontent.com/41965390/182046081-a33514fc-03f9-4477-a285-5cb01a13b189.png)

**Comment by mwittrien** [comment]
No longer possible
