### ISSUE TITLE
[BUG] - EmojiReplace doesn't replace thread titles

### ISSUE THREAD

**Issue by aaronliu0130** [mwittrien/BetterDiscordAddons#1669]
**Describe the bug**
EmojiReplace won't replace emojis in thread titles.

**To Reproduce**
Open a thread with a default emoji in its title.

**Expected behavior**
The emoji is replaced.

**Screenshots**
![image](https://user-images.githubusercontent.com/11874211/179435467-0d184bf5-7c91-4399-bcce-66fab49d3c08.png)

**Discord Build (stable, ptb or canary):**
Stable 137095 (fb67ae9)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.25158)

**Additional context**
I'm also using BasicBackground.

**Comment by mwittrien** [comment]
Those arent emojis they are ascii symbols

**Comment by aaronliu0130** [comment]
nope, it is emoji.
![image](https://user-images.githubusercontent.com/11874211/179437040-4854fafd-9168-4d7e-b75d-7955b8178cab.png)
I just reproduced it.

**Comment by aaronliu0130** [comment]
ah, I just realized that threat titles only allow symbols...
