### ISSUE TITLE
PinDMs glitches out sometimes

### ISSUE THREAD

**Issue by Aida-Enna** [mwittrien/BetterDiscordAddons#167]
Clicking on a name has a chance to hide the Pinned DMs category (and it's users) completely, as seen below:
https://gfycat.com/TenderCornyArrowcrab

**Comment by mwittrien** [comment]
Hopefully fixed now

**Comment by Aida-Enna** [comment]
Still happening after updating, sorry! D:

**Comment by Aida-Enna** [comment]
Hello?

**Comment by mwittrien** [comment]
Can't fix it, just scroll if it glichtes out
