### ISSUE TITLE
[IMPROVEMENT] - GameActivityToggle / (add Spotify activity toggle)

### ISSUE THREAD

**Issue by camayl** [mwittrien/BetterDiscordAddons#1670]
Hi, I I'd love a Spotify activity toggle, i.e. showing or hiding what songs I am listening to, without going into settings each time. I think this would be a great plugin. Thanks for reading and considering!

**Comment by mwittrien** [comment]
SpotifyControls

**Comment by camayl** [comment]
sorry! i didn't realise that plugin has this feature. i noticed that in SpotifyControls the toggle is tucked into the thumbnail preview. Could it be possible to allow an option to have it where the main main controls are?
