### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by ShawkMusic** [mwittrien/BetterDiscordAddons#1672]
**Describe the bug**
ImageUtilities makes discord freeze whenever I open an image

**To Reproduce**
Open an image with ImageUtilities enabled

**Expected behavior**
Not freezing

**Screenshots**
NA

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
NA

**Comment by ShawkMusic** [comment]
How is this invalid/impossible?

**Comment by mwittrien** [comment]
Because its not happening
