### ISSUE TITLE
[IMPROVEMENT] - PinDMs - Support for GooseMod.

### ISSUE THREAD

**Issue by MagmaBro123** [mwittrien/BetterDiscordAddons#1674]
**Describe the solution you'd like**
Support for GooseMod.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mwittrien** [comment]
What

**Comment by MagmaBro123** [comment]
See https://goosemod.com/#.

**Comment by mwittrien** [comment]
Does BD run on goosemod?

**Comment by MagmaBro123** [comment]
GooseMod has support for all the current formats, so yes.

**Comment by mwittrien** [comment]
Well i just tested and my plugins already work on goosemod

**Comment by MagmaBro123** [comment]
They don't.
![image](https://user-images.githubusercontent.com/51277766/181341623-46b68c09-bd6a-4230-b8c0-15e21d5f6093.png)
