### ISSUE TITLE
[BUG] EditUsers - An edited user's stream will duplicate when they go live

### ISSUE THREAD

**Issue by HotLaMon** [mwittrien/BetterDiscordAddons#1676]
When I view a user's stream it duplicates a preview of their stream.

![image](https://user-images.githubusercontent.com/92102266/181455725-206e521f-a3cc-4440-b159-bb363f70fb85.png)

**Comment by mwittrien** [comment]
Doesnt happen to me

**Comment by HotLaMon** [comment]
> Doesnt happen to me

Sorry, forgot to specify it seems to only happen to users I've edited with the EditUsers plugin. In this case the user "Cuz". When I undo the local edit of the user the issue disappears.

**Comment by HotLaMon** [comment]
Here's a video of the bug:
https://www.youtube.com/watch?v=v1ys6xGBZDo
