### ISSUE TITLE
[IMPROVEMENT] - Emoji Replace, animated Microsoft Teams emojis

### ISSUE THREAD

**Issue by CodedNil** [mwittrien/BetterDiscordAddons#1677]
**Describe the solution you'd like**
At the moment this plugin supports the flat new microsoft emojis, would it be possible to also support the new animated ones which look amazing?
https://emojipedia.org/microsoft-teams/
I have tried this myself and have downloaded all the animated emojis and reduced their size to 72x72, but the filenames are very different on emojipedia to what discord uses, is there a process for converting these filenames to discords standards?
There are 2997 of these emojis, 2113 of these are animated, totals 1.8gb at the original 256 resolution and 279mb at reduced size, I have tested manually renaming a few and it works fine so this should all be totally technically possible.

**Comment by mwittrien** [comment]
discord uses a stylesheet which contains all emojis at once in a matrix map, this would make it impossible to group the animated emojis together in one file

**Comment by CodedNil** [comment]
The stylesheet is just for the emoji picker I had thought, could those not be the flat designs but then once you choose one it would be the animated version?

**Comment by mwittrien** [comment]
The flat design doesnt look the same as the animated tho

**Comment by Lythium4848** [comment]
> The flat design doesnt look the same as the animated tho

Is it not possible to use the "3d" ones then?

**Comment by mwittrien** [comment]
I am not going to download over 2000 emojis and manually rename them, if they arent on emojipedia then i cant generate the stylesheet etc.

**Comment by DeveloperWOW64** [comment]
> I am not going to download over 2000 emojis and manually rename them, if they arent on emojipedia then i cant generate the stylesheet etc.

But then what about the original Fluent Emoji flat set? Wouldn't you have done too as such?

**Comment by BluePineappleCake** [comment]
I think its only the preview.
Once you download them they are the static fluent ones.

**Comment by mwittrien** [comment]
No and thats not how my grabber works

**Comment by DeveloperWOW64** [comment]
> Those are the animated ones
> 
> I need the fluent images ones

As previously explained in #1765, @mwittrien They are oss'ed at https://github.com/microsoft/fluent-emoji

**Comment by Lythium4848** [comment]
> > Those are the animated ones
> > I need the fluent images ones
> 
> As previously explained in #1765, @mwittrien They are oss'ed at https://github.com/microsoft/fluent-emoji

mwittrien previously said this:
> I am not going to download over 2000 emojis and manually rename them, if they arent on emojipedia then i cant generate the stylesheet etc.

**Comment by StarNumber12046** [comment]
I think I'm going to

**Comment by StarNumber12046** [comment]
shall I open a draft PR for this? @mwittrien

**Comment by mwittrien** [comment]
Tell me when you are done in a hundred years 😅

**Comment by StarNumber12046** [comment]
Ok
