### ISSUE TITLE
[BUG] - image utlites 

### ISSUE THREAD

**Issue by a-a3458** [mwittrien/BetterDiscordAddons#1679]
**Describe the bug**
image utilities is bugging out 
**To Reproduce**
When does the bug occur.
i open the image tab and the photos don't display correctly
**Expected behavior**
image tab to display photos correctly
**Screenshots**
https://imgur.com/a/zlMgL3c
**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable 138734 (047115f)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)
**Additional context**
the video tab works and the audio tab works to its just image tab seems to be not displaying correctly i even did a reinstall of the plugin.

**Comment by mwittrien** [comment]
Has nothing to do with ImageUtilities
