### ISSUE TITLE
Hidden Channels not working with new version of discord

### ISSUE THREAD

**Issue by RafaelLopes98** [mwittrien/BetterDiscordAddons#1684]
**Describe the bug**
New Version of Discord does not support Showhiddenchannels

**Comment by misapprehending** [comment]
I've noticed it displays channels in categories you can see but not hidden categories

**Comment by XxUnkn0wnxX** [comment]
I've noticed it works somewhat, it shows text channels but no voice or categories...

**Comment by codeharshil19272** [comment]
After the new update, facing similar issues as mentioned by @misapprehending and @XxUnkn0wnxX . Not all categories in text channels are visible and no voice channel.
