### ISSUE TITLE
[BUG] As soon as it enables it crashes discord (Not BD just discord)

### ISSUE THREAD

**Issue by VisionStudiosOF** [mwittrien/BetterDiscordAddons#1688]
**Describe the bug**
When you hit the enable button on discord (stable release)
discord immediately crashes. This doesn't crash BD as it does not display
the "BD has crashed your discord client"  

**To Reproduce**
Hit the enable button on the plugin in discord stable release 

**Expected behavior**
For discord not to crash and for the plugin to work

**Screenshots**
No screenshots but here is a video of me enabling it then discord crashes then removing it from plugins then discord works
https://streamable.com/txezdm

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
It was working a 1 day ago then it just did this

**Comment by cloudbotdiscord** [comment]
Same here, any way to fix this?

**Comment by cloudbotdiscord** [comment]
Hey @VisionStudiosOF !

Try not to use the edituser plugin, that's the main cause of the crash.

**Comment by mwittrien** [comment]
#1685
