### ISSUE TITLE
[BUG] - SpotifyControls w/AMOLED-Cord

### ISSUE THREAD

**Issue by Jarad999** [mwittrien/BetterDiscordAddons#1690]
**Describe the bug**
Display doesnt show above username

**To Reproduce**
Load into discord with *SpotifyControls* enabled.

**Expected behavior**
Should be able to see the controls.

**Screenshots**
[Screenshot](https://usercontent.catto.pictures/jarad0999/49565de2-65b8-46fe-9b6c-6a57cef78eaf.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Stable 139460 (ea9eb84)
BetterDiscord 1.5.3-Hotfix
Host 1.0.9005 Windows 10 64-Bit (10.0.22621)

**Comment by mwittrien** [comment]
Works just fine for me

If its an issue with Amoled Cord then the theme has to fix it
