### ISSUE TITLE
[BUG] - ServerDetails shows "addon error" on start

### ISSUE THREAD

**Issue by Poirot12345T** [mwittrien/BetterDiscordAddons#1691]
**Describe the bug**
On start, ServerDetails plugin refuses to load, showing "addons error" on start - "Could not be constructed". While running the app, ServerDetails plugin is not available.

**To Reproduce**
Restart the app.

**Expected behavior**
Start with no Addon error, addon GuildProfile operates normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/82270962/182367958-fa61131a-b59b-4a90-bdda-2657231d9d1f.png)
![image](https://user-images.githubusercontent.com/82270962/182368009-c3e8aa22-70f8-4308-97c8-85cef3260ee8.png)

**Discord Build (stable, ptb or canary):**
Discord Stable 139460 (ea9eb84)
BetterDiscord 1.5.3-Hotfix (BetterDiscord 1.5.3 does the same error)
Host 0.0.18
Linux 64-Bit (5.18.14-Arch1-1)

**Additional context**
Text of screenshot No. 2:
```
GuildProfile: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306843)
    at Object.loadAddon (<anonymous>:4:268333)
    at Object.loadAddon (<anonymous>:4:305881)
    at Object.loadAllAddons (<anonymous>:4:270609)
    at Object.initialize (<anonymous>:4:265058)
    at Object.initialize (<anonymous>:4:305091)
    at Object.startup (<anonymous>:4:367101)
```

**Comment by mwittrien** [comment]
Jesus

ServerDetails and GuildProfile are not the same plugin
