### ISSUE TITLE
[BUG] - BDFDB - High Memory Usage.

### ISSUE THREAD

**Issue by TheRealJake12** [mwittrien/BetterDiscordAddons#1693]
**Describe the bug**
Really fucking high memory usage when having this library installed.
**To Reproduce**
When does the bug occur.
When the library is installed
**Expected behavior**
Stay at 270MB ram not 600mb
**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable
**Additional context**

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/182479371-293da16c-65ac-41d8-ba9a-59f8f4011812.png)

With my library and plugins enabled
