### ISSUE TITLE
[BUG] - Image Utilities - GIFs background stretching too much

### ISSUE THREAD

**Issue by Satoru-1816** [mwittrien/BetterDiscordAddons#1694]
**Describe the bug**
After using the Image Resize/Messages' setting "Resize to original size" and restarting, the background of every GIF now stretches and doesn't fit the GIF. No matter if I set it to "No resize" or turn off the plugin, this bug doesn't go away. I even tried reinstalling Discord to no avail. Pretty much broke my theme (Clear Vision) affecting every emoji or GIF I send.

**To Reproduce**
Use Clear Vision theme or whichever with a background for GIFs, go to Image Utilities Settings - Resize Settings - and set Messages' to "Resize to original size". Afterwards resize any image and restart Discord. The bug should start appearing if you send a GIF.

**Expected behavior**
The background not stretching that much and fitting the GIF.

**Screenshots**
![BUG_1](https://user-images.githubusercontent.com/81326989/182472305-6ca7af47-b4e8-47f8-9dec-d2fb8584bcb6.png)
![BUG_2](https://user-images.githubusercontent.com/81326989/182472318-9ef419d6-8f8b-427b-addd-ff10fd028197.png)

**Discord Build (stable, ptb or canary):**
Stable 139553 (8950d3d)

**Additional context**
This doesn't happen using Discord's default theme, or at least it isn't visible as that theme doesn't have a background for GIFs.

**Comment by mwittrien** [comment]
Thats most likely your theme, Discord changed how embeds work adding resizing by themselves
