### ISSUE TITLE
[BUG] - Image Utilities - Multiple images gallery + zoom bug

### ISSUE THREAD

**Issue by Sneakpeakcss** [mwittrien/BetterDiscordAddons#1695]
**Describe the bug**
Image Utilities doesn't initiate gallery mode when someone sends 2+ pictures in a single message,  it only shows the single clicked image without the `< >` arrow overlay, and trying to use zoom on that image closes it after single mouse click. 

If you initiate gallery mode on a different individual set of images and come back to that single message it often (but not always) shows the overlay or at least allows you to scroll through images using left/right keyboard buttons.
Interesting thing is that it still works after discord restart, but stops the moment you send another set of images.

**To Reproduce**
1) Drag any 2 pictures to discord and send them as a single message.
2) Click on a image to open gallery/detailed view and then try to zoom.

**Expected behavior**
Multiple images send in a single message should create a gallery overlay and using zoom shouldn't close the detailed view after single click.

**Screenshots**

https://user-images.githubusercontent.com/77424331/182766508-e5ca9ba2-0323-4519-b090-b350ba35a623.mp4

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
In general Gallery mode is a bit hit or miss after one of the updates earlier this year (around february), sometimes it creates a gallery after very long delay, sometimes not at all, sometimes instantly, or it loads once and stops working in different channels/images until discord restart… It's so random that i'm unable to find any common thing to consistently reproduce it, but it seems to always  work on first set of images after discord restart, after that it might or might not work.

**Comment by Sneakpeakcss** [comment]
@mwittrien 
I've just tested IU after newest changes, and can confirm that problem with zoom on 2+ images is fixed, gallery mode showing on 2+ images also works, but there's a weird problem with duplicate images when scrolling through pictures that were send as a single message, but only while using arrow keys rather than clicking on `< >`. 

Additionally i think i found a way to reproduce that problem with gallery mode sometimes working or not, would you like me to make new individual issues for every single of those problems of just group them into a single new report?

**Comment by mwittrien** [comment]
Hete is fine
Maybe add some screenshots

**Comment by Sneakpeakcss** [comment]
Okay let's start with this one and soon i'll add next when i'll make a showcase video for them:

**Describe the bug**
Starting gallery mode on a image that was send as _multiple images in single message_, and then using arrow keys to scroll through them creates a weird "ghost image" behaviour when you hit the "edge", but if you open gallery mode from a _single image_ and scroll throgh them then everything works fine.

**To Reproduce**
1) Send 2+ images as a single message
2) Send a single image after previous 2+
3) (optional) Send another set of 2+ images
3) Open gallery mode by clicking on a image that was send as _multiple in single message_ and scroll to the either end using arrow keys (and keep scrolling).
4) Repeat 4, but this time open gallery from the single image (it works fine in this case).

**Expected behavior**
Scrolling through gallery using arrows keys shouldn't create a duplicate image when gallery was opened from an image that was send as _multiple in single message_.

**Video**


https://user-images.githubusercontent.com/77424331/183134236-5868bf4f-3f8a-43f4-8052-a22626ff609e.mp4


**Additional context**
It looks like using arrowkeys manages to scroll past the last image, even when arrows `< >` aren't avaiable anymore and toggles between last images creating this weird "ghost image" behaviour. 
Also you can see in the video at  0:07s mark that `Source` and `Image` stays the same, but it correctly catches `Size` change.

**Comment by Sneakpeakcss** [comment]
Now the first part of gallery mode not initializing in certain scenarios:

**Describe the bug**
This one is connected to what was mentioned at the start of the issue:
> Interesting thing is that it still works after discord restart, **but stops the moment you send another set of image**s.

Gallery mode stops working the moment you try to open a newly uploaded image, but works fine if you first open a previous image and then switch to the newly uploaded one.
If you try to first open your uploaded image then Gallery Mode completly stops working in the current channel (you can reset it by switching channels and opening a set of images there and then switching back)

**To Reproduce**

_Each of those (**a**/**b**) steps should be done after discord restart, because previous actions change the behaviour even more:_

**_scenario a)_**
1) Have few previously send images (individual images in my case).
2) Upload a new image.
3) Open Gallery Mode using previous image. **[0:11s]** _(At this point that newly uploaded image doesn't show, but the gallery works)._
4) Now open the uploaded Image. _(At this point Galery Mode doesn't show at all even for previous images from step 3)._
5) You can 'reset' it by changing channels and opening Gallery Mode on a different set of images and then switching back **[0:29s].**

**Video**



https://user-images.githubusercontent.com/77424331/183146274-adac7b28-e2d1-4f9e-96d1-217fca9bfe00.mp4



**_scenario b)_**
1) Start by uploading an image to one channel _(don't open it yet)._
2) Switch to a different channel and open a set of images to initialize Gallery Mode.
3) Switch back to previous channel and open newly uploaded picture _(At this point suprisingly Gallery Mode works)._
4) Upload another picture and instantly open it _(And now once again Gallery Mode doesn't work at all in current channel without doing previously mentioned 'reset', which in case of direct messages basically means reseting discord)._

**Video**

https://user-images.githubusercontent.com/77424331/183157292-920e21af-edab-435f-a29c-c4ce984daaab.mp4


**Expected behavior**
Gallery mode should initialize properly on a newly uploaded image.

**Additional context**
That 'reset' works using different channels on a server, but i'm not sure if it works on direct messages where i usually have this problem. Also i'm not sure how all of this behaves when you open an image uploaded by someone else.

**Comment by Sneakpeakcss** [comment]
Second part of gallery mode not initializing in certain scenarios:

**Describe the bug**
Gallery Mode works only as long as you open an image that was previously included in a fetched batch. Manually opening any old image that goes past the initial #⁠25 stops Gallery Mode from initializing until discord restart (this is also true for any next batch of images if you can find older ones).

**To Reproduce**
This will also require a discord restart between **a**/**b**.

**You will need at least 26 images that were individually send, because Image Utilities seems to treat _multiple images send in one message_ as a single image and in effect initially loads [a lot more ](https://user-images.githubusercontent.com/77424331/183199894-8d901be3-b641-46fb-82d7-f4d9eb647159.png)(possibly 250 max?)… And this might be another bug/feature?**

**Scenario a)**
1) Open 25th image **[0:34s]** _(At this point Gallery Mode works only for previous images and won't fetch any more, even when scrolling from previous ones)._
2) Open 26th image _(At this point Gallery Mode stops working, previously fetched images also stop)._

And like previously mentioned, if you fetch a second batch of images then the whole scenario repeats itself at image #⁠49/#⁠50 on and on.

**Scenario b)**
1) Instantly open an old image that goes past the initial #⁠25 (Gallery Mode will not work for any images until discord restart)

**Expected behavior**
Gallery Mode should initialize without previous fetching and still work after opening an image past the initial fetched batch.

**Video**

https://user-images.githubusercontent.com/77424331/183202233-49df119e-bf97-46d8-a596-3bb83d4360b5.mp4


**Additional context**
This one is probably the main reason of my problems with Gallery Mode randomly not working.
