### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by catboymyles** [mwittrien/BetterDiscordAddons#1699]
Theres a bug when enabling certain discord themes such as materialdesign by thecommieaxolotl for example where the popup for the pin list doesn't show properly. 

![image](https://user-images.githubusercontent.com/87230516/183147887-1fa02c1d-2e73-4407-86db-7dcb684b1667.png)

I'm using stable discord, I believe.

I'm not sure if this is an issue with the theme itself or an issue with this plugin, as this is the only plugin with any sort of bug i've made note of that occurs with this theme in particular.

**Comment by mwittrien** [comment]
Theme issue
