### ISSUE TITLE
ServerFolders

### ISSUE THREAD

**Issue by HYPExMon5ter** [mwittrien/BetterDiscordAddons#17]
https://gfycat.com/AggressiveSadErmine
The servers aren't showing up when I click the folders using the new ServerFolders 2

**Comment by mwittrien** [comment]
Disable your theme and try again

**Comment by HYPExMon5ter** [comment]
works now, is there a fix for this though? I don't really wanna have my theme disabled..

**Comment by mwittrien** [comment]
Check if version 5.0.1 fixes it

**Comment by HYPExMon5ter** [comment]
Nope.

**Comment by mwittrien** [comment]
Send me your theme in discord, wanna debug it tomorrow, going to bed for now 💤

**Comment by HYPExMon5ter** [comment]
Done.

**Comment by mwittrien** [comment]
Fixed in the newest version 👍
