### ISSUE TITLE
Friend Notifications, Online Counter

### ISSUE THREAD

**Issue by Deleca7755** [mwittrien/BetterDiscordAddons#170]
I click and no dialog/window pops up of the session as of the latest update.

**Comment by CodesButcher** [comment]
I can't open the log too

**Comment by CodesButcher** [comment]
> I click and no dialog/window pops up of the session as of the latest update.

I have the old plugin here
https://drive.google.com/open?id=1grDF6e-o_lRERqR9-cPn8-SmxcXZGtWj
maybe it haven't been updated for 2 months, but while waiting for them to fix it, use it instead

**Comment by mwittrien** [comment]
reload to fix the issue

**Comment by r00tarded** [comment]
Hi,

Still broken with 1.1.18.
