### ISSUE TITLE
[BUG] - showHiddenChannels / dont working anymore

### ISSUE THREAD

**Issue by sadoj-kuro** [mwittrien/BetterDiscordAddons#1701]
**Describe the bug**
the plugin do not working anymore on the lasted discord version

**To Reproduce**
update discord to lasted version

**Expected behavior**
...... working plugin lmao

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
dont ask me to open console, stable version DONT have anymore console opening.

**Comment by rollingmoai** [comment]
https://github.com/BD-MemorySeal/DevilBro-Alternatives/tree/distribution/ShowHiddenChannels
