### ISSUE TITLE
[IMPROVEMENT] - ClickableMentions

### ISSUE THREAD

**Issue by Divoret** [mwittrien/BetterDiscordAddons#1703]
So, clickable mentions allow users to click on a mentioned user, right? What about clicking on a mentioned role, and showing all the users who have the role? I am using a discord experimental feature called "Role popout" which allows me to mention roles and send them in chat, and then click on it and it shows most of the members who have the role.

However, there is one problem. Clickablementions plugin does not seem to allow clicking on mentioned roles or users in the chatbox itself (before the message is sent). 

The reason I would like to have clickablementions have mentioned roles and users clickable not only in the message box, but also in the chatbox is because if I sent a mentioned role in chat, it would end up pinging everyone with that role, and the mods would think I'm trying to break the rules of the server.

that's why, I was wondering if you could add a feature where clickable mentions works for role mentions and user mentions even in the chatbox (before the message is sent)

is this possible to add this feature?

**Comment by mwittrien** [comment]
Possible in the future

Sadly the exoeriments plugin is broken, so i cant try it out
