### ISSUE TITLE
[BUG] - OpenSteamLinksInApp

### ISSUE THREAD

**Issue by Lund1337** [mwittrien/BetterDiscordAddons#1704]
**Describe the bug**
Discord crashes after opening a steam link.

**To Reproduce**
After clicking the linking it always crashes

**Expected behavior**
So it wouldnt crash

**Screenshots**
https://i.imgur.com/MGYBtOP.gif

**Discord Build (stable, ptb or canary):**
stable, betterdiscord vers 1.6.0

**Comment by mwittrien** [comment]
Works fine for me, make sure you got the steam app installed
