### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by kendricklin** [mwittrien/BetterDiscordAddons#1709]
For users in voice chat who are blocked. Allow option to make these blocked users to be seen as blocked users and not show their names or profile picture but show a generic blocked user so we know someone is blocked in that specific voice channel. if the number of users in a voice channel isnt listed you dont know if youre jumping into a voice channel with someone who is blocked.

**Comment by mwittrien** [comment]
The plugin is meant to remove blocked users, not conceal them
