### ISSUE TITLE
Friend Notifications, Online Counter

### ISSUE THREAD

**Issue by r00tarded** [mwittrien/BetterDiscordAddons#171]
Hi, the previous issue was closed but even with 1.1.18 and reloading, I can't get the dialog window to open with the log anymore.

reload to fix the issue

_Originally posted by @mwittrien in https://github.com/mwittrien/BetterDiscordAddons/issues/170#issuecomment-466636762_

**Comment by mwittrien** [comment]
Tested on all discord builts and it works on all of them
