### ISSUE TITLE
[IMPROVEMENT] - RevealAllSpoilers/NSFW Spoilers

### ISSUE THREAD

**Issue by lynrayy** [mwittrien/BetterDiscordAddons#1711]
**Describe the solution you'd like**
I want NSFW spoilers to reveal automatically too as other spoilers
![2022 08 14 Discord r4](https://user-images.githubusercontent.com/59417884/184530583-cdd162ba-e237-4eb6-80bf-bdad1c7e9a2b.png)

**Comment by lynrayy** [comment]
*Ability to reveal all spoilers in all channels automatically

**Comment by mwittrien** [comment]
Disable nsfw spoilers in the ImageUtilities plugin if you dont want them

**Comment by lynrayy** [comment]
> Disable nsfw spoilers in the ImageUtilities plugin if you dont want them


I want NSFW spoilers to show automatically. How can i do this?

**Comment by lynrayy** [comment]
Oh i found. Thank you. This added by image utilities? Stupid function
