### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by LockBlock-dev** [mwittrien/BetterDiscordAddons#1712]
**Describe the bug**
The plugin does not appear on screen anymore with the following error:
```
[CharCounter] (v1.6.0) Fatal Error: "after" callback of render in ChannelTextAreaContainer TypeError: 'get' on proxy: property 'isStaff' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function(){return R.hasFlag(u.UserFlags.STAFF)}' but got 'function(){return R.hasFlag(u.UserFlags.STAFF)}')
```

**To Reproduce**
Open Discord, if you're unlucky you get this bug.

**Expected behavior**
The plugin does not crash and works properly without having to delete `0BDFDB.data.json`.

**Discord Build (stable, ptb or canary):**
```
Stable 141471 (8b6078f)
BetterDiscord 1.6.2
Host 0.0.18 Linux 64-Bit (5.18.16-Arch1-1)
```

**Additional context**
To fix the issue you need to delete `0BDFDB.data.json` **EACH TIME** the bug appears (like you said in #1686). It would be nice to have a real fix. Why deleting the data.json is even fixing a character counter plugin?

**Comment by mwittrien** [comment]
Cant reproduce

Sounds like you got an internet issue with an old 0BDFDB.data.json reappearing
