### ISSUE TITLE
Multiple Tags for users - EditUsers

### ISSUE THREAD

**Issue by planet-bluto** [mwittrien/BetterDiscordAddons#1714]
I just want to be able to set multiple tags for users. Similar to how bot has it's bot tag and the custom tag by a user. This could be done via some new UI component or just by simply putting a dividing character like a ', ' or a ' | '.

![example of how inputting multiple tags could work](https://i.imgur.com/vSfd0cb.png)

**Comment by mwittrien** [comment]
Nah

**Comment by planet-bluto** [comment]
That is a halarious response, lol. Would you be more willing to add it if I just implemented it myself?
