### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds - Limit Ping Sounds

### ISSUE THREAD

**Issue by EpicGazel** [mwittrien/BetterDiscordAddons#1718]
**Describe the solution you'd like**

- Add the ability to rate-limit how frequently sounds are able to play. Allow this to be set via a slider or number field for a number of seconds.
- Ex: If the "Message (Direct Message)" sound limit is set to 5 seconds and you are sent 10 messages within those 5 seconds, only 1 ping sound is played. If you are sent 13 over 10 seconds, only 2 pings are played, and so on. 
- Ideally, you would be able to apply this to each sound individually but I imagine a global setting would mostly work.
    

**Describe alternatives you've considered**
    There does not appear to be a native solution or any plugins that implement this feature.

**Comment by mwittrien** [comment]
The purpose of the plugin is to change the notification sounds/volume

Not to add extra features like that

This should be a separate plugin
