### ISSUE TITLE
Theme repo making betterdiscord to crash

### ISSUE THREAD

**Issue by TechnoClasher** [mwittrien/BetterDiscordAddons#1719]
The client loads up and after some seconds it crashes

**Comment by Masono03** [comment]
Same even tried solved from bd discord such as getting a new version of the bd data json and restarting pc but it keeps coming back after a couple hours and now it doesnt even fix with that solve anymore. 

Canary 141822 (e53c017)
BetterDiscord 1.6.2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)
