### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by StarNumber12046** [mwittrien/BetterDiscordAddons#1720]
**Describe the solution you'd like**
Since the new Microsoft 3D emojis got released, I would really like to get those emojis into discord

**Describe alternatives you've considered**
I've coinsidered doing it "manually" but that's almost impossible due to the large size of the repo and the LOTS of emojis in there

**Additional context**
https://github.com/Microsoft/fluentui-emoji

**Comment by mwittrien** [comment]
#1677
