### ISSUE TITLE
[BUG] - ShowHiddenChannels doesn't work on categories.

### ISSUE THREAD

**Issue by ShadiestGoat** [mwittrien/BetterDiscordAddons#1722]
**Describe the bug**
I'm not sure about the policy on this, but I'm using powercord + bdcompat to use this. When looking through channels, I noticed that there were basically no hidden channels shown. I saw 1, which is blocked from my view using channel permissions, not category permissions.

**To Reproduce**
1. Setup powercord + BDCompat
2. Go to a server with a hidden category & a visible category w/ a hidden channel

**Expected behavior**
All channels to be shown

**Discord Build (stable, ptb or canary):**
canary

**Comment by mwittrien** [comment]
My stuff doesnt work with Powercord even with bdcompat

**Comment by lordcyb3r** [comment]
if you go a couple of commits backwards it does. So you changed something recently that broke it. This is the way a lot of people run better discord plugins and obviously I get it, this is unsupported. So hopefully someone will make a fork specifically for bdcompat as yes, you shouldnt have to do that
