### ISSUE TITLE
[BUG] - EditUsers 

### ISSUE THREAD

**Issue by zenosiege** [mwittrien/BetterDiscordAddons#1723]
**Describe the bug**
Can't change name color, banner and avatar. It seems BetterDiscord reloads after applying settings

**To Reproduce**
It can be reproduced by applying the latest BD and EditUsers version

**Expected behavior**
I expected it's gonna work fine and I'll apply some funky settings to my profile

**Screenshots**
No screenshots

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
No additional context

**Comment by mwittrien** [comment]
Just tested and works fine for me

Take a video of what u mean

**Comment by zenosiege** [comment]
https://user-images.githubusercontent.com/64847098/185359089-004bf075-f973-47ae-95cb-d082d9048cf8.mp4

my apologies it's in russian but I guess you'll understand what's going on

**Comment by mwittrien** [comment]
You need to wait till the input you copied the gif link into turns green

**Comment by zenosiege** [comment]
OH LMAO, thank you!!
