### ISSUE TITLE
[BUG] - SpotifyControls : Can't open my account menu popout when playing music

### ISSUE THREAD

**Issue by Kanta0611** [mwittrien/BetterDiscordAddons#1724]
**Describe the bug**
Whenever the controls appear because I play music, my account menu popout (normally accessible clicking username) can't be open.

**To Reproduce**
Make sure SpotifyControls is on
Play some music on Spotify
Controls appear
Open account menu popout by clicking username

**Expected behavior**
Account menu popout should open

**Screenshots**
https://clipchamp.com/watch/2XYL3kbpSG7

**Discord Build (stable, ptb or canary):**
Stable 142350

**Additional context**
If you close spotify to make the controls disappear, you can open the popout again

**Comment by mwittrien** [comment]
![test](https://user-images.githubusercontent.com/23700969/185761021-b3d8c1c8-b232-4901-a0ce-737083348cbc.gif)
works fine for me, might be a plugin incompartibality
