### ISSUE TITLE
[BUG] - Plugin Repo - Search bar, settings, etc not showing

### ISSUE THREAD

**Issue by Sowansow912** [mwittrien/BetterDiscordAddons#1728]
**Describe the bug**
Only the cards containing the available plugins are visible, nothing else is on the "Plugin Repo" page.

**To Reproduce**
Install "Plugin Repo" and "BDFDB", go to the Plugin Repo page.

**Expected behavior**
A set of buttons and a search bar should be at the top of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/57327722/185716404-b0db2825-f80f-497d-909e-d5761bb3ce05.png)
`Screenshot taken with only Plugin Repo and BDFDB installed`

**Discord Build (stable, ptb or canary):**
Stable 142751 (d676e32)
BetterDiscord 1.6.3
Windows 10 64-Bit

**Additional context**
The same issue is present in "Theme Repo"

**Comment by Ruochenfu2011** [comment]
same issue

**Comment by Ruochenfu2011** [comment]
How to fix?

**Comment by Sowansow912** [comment]
> How to fix?

Download and install the latest version of the plugin
