### ISSUE TITLE
[BUG] -Emoji Replace

### ISSUE THREAD

**Issue by zluckytraveler** [mwittrien/BetterDiscordAddons#1729]
**Describe the bug**
Screen Transition are lagging and slower than they should be.

**To Reproduce**
Enabling the theme

**Expected behavior**
Screen transition to not lag and be smooth.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Screenshots**
https://user-images.githubusercontent.com/97180817/185724454-55066dd4-37d9-43e9-8f9c-7da12e86369b.mov

**Comment by mwittrien** [comment]
Cant be avoided, its a huge css file

**Comment by zluckytraveler** [comment]
> Cant be avoided, its a huge css file

Well this didn't use to happen at all. It only just started to happen today, and I've been using the theme for a couple months now.
