### ISSUE TITLE
MessageUtilities clears chat input when you/I don't want it to

### ISSUE THREAD

**Issue by CinnamonFreak** [mwittrien/BetterDiscordAddons#173]
When the option "Clear chat input when Escape is pressed" is enabled and you mark server as read using Shift+Esc it clears chat input

**Comment by mwittrien** [comment]
Are you trying to annoy me with your issues?
Pressing any keys focuses the textarea in discord, pressing escape clears the chat input
shift focuses the textarea and Esc afterwards clears it, scream at discord for focusing the textarea on any key stroke

**Comment by CinnamonFreak** [comment]
Didn't know that. Sorry
