### ISSUE TITLE
[BUG] - SettingsIcons showing "?"

### ISSUE THREAD

**Issue by D4rkov** [mwittrien/BetterDiscordAddons#1731]
**Describe the bug**
Settings Icons shows "?" instead of the corresponding icon.

**To Reproduce**
Open settings, all tabs have ?, after clicking on a tab, the correct settings icon shows.

**Expected behavior**
For it to show the right icon at all times, instead of "?"

**Screenshots**
https://i.imgur.com/rlU9LX1.gif

**Discord Build (stable, ptb or canary):**
Canary 142897 (89d4551)

**Additional context**

**Comment by mwittrien** [comment]
#1726
