### ISSUE TITLE
[BUG] - EDIT CHANNELS

### ISSUE THREAD

**Issue by zluckytraveler** [mwittrien/BetterDiscordAddons#1732]
**Describe the bug**
Some channels appear to be dimmed in color compared to others for no reason.
I have checked the channel settings for everything and there is no differences between the others channels under the same category.

**To Reproduce**
Selecting a color choice for changing local channel settings

**Expected behavior**
For all colors to look the same.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Screenshots**
<img width="200" alt="Screen Shot 2022-08-22 at 6 24 28 PM" src="https://user-images.githubusercontent.com/97180817/186048233-583d6d5b-8519-4975-89b9-3e7d1f3a4e74.png">

**Comment by mwittrien** [comment]
Dimmed colors are muted channels

**Comment by zluckytraveler** [comment]
> Dimmed colors are muted channels

@mwittrien I thought that have been the case, except that other channels which are muted are not dimmed whatsoever, and channels that are muted are in full color. So it is not working properly as suggested.

**Comment by mwittrien** [comment]
Example screenshot?

**Comment by zluckytraveler** [comment]
Everything shown in the screenshot are of unmuted channels.

**Comment by mwittrien** [comment]
How does it look without the plugin

**Comment by zluckytraveler** [comment]
As it's suppose to look, Discord D
default.
