### ISSUE TITLE
[IMPROVEMENT and FEATURE] - PLUGIN/TRANSLATOR

### ISSUE THREAD

**Issue by itoffie** [mwittrien/BetterDiscordAddons#1734]
this has been an annoying issue for a while now that definitely needs an improvement like everytime you translate something it doesnt stay on that specific line but instead goes to the "new" messages or the bottom of the newest messages are ... cant it stay on that specific line so you wouldnt have to scroll so you can keep up faster in a conversation?

and if possible instead of right clicking translate since the plugin already has this 
![image](https://user-images.githubusercontent.com/64309702/186954885-071b9ae5-3017-4309-a9a6-337e6b3fa032.png)
translated hover text, wouldnt it be possible if you can put that on an untranslated message and show "(Translate)" greyed out only when you hover your mouse on that line of message and when you click that since the plugin already has "auto detect" language you can just make it translate the message via a popup or hover message with the contents translated just like the google translate plugin/extension on the web browsers

else really make it google translate web extenion alike where you highlight everything you wanted translated and either button for translate pops up or change it in settings where it instant translate without clicking translate button

**Comment by itoffie** [comment]
note that sometimes the highlight search translation is not helpful as it is hard to read on how it works since its only a small box and sometimes selecting multiple lines of message even tho they are all in the same language only partial of those message gets translated and as i said not really helpful especially when you remove hover on search translation it also turns off the translated message instead of it staying

**Comment by mwittrien** [comment]
The jumping is an issue with discord and cant be fixed

If you wanna search translation for marked text do it individually for msgs
