### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Fellintron** [mwittrien/BetterDiscordAddons#1735]
**Describe the bug**
When clicked on customise color, the output throws the error "React Component error"

**To Reproduce**
-

**Expected behavior**
It should let us to customise the color of our choice and pin the DMs

**Screenshots**
https://imgur.com/tq3Hpix

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
canary

**Additional context**

**Comment by mwittrien** [comment]
Ctrl shift i
And Screenshot the errors

**Comment by Fellintron** [comment]
hey sorry for the late response, as i've mentioned above it was on discord canary not web discord
