### ISSUE TITLE
[IMPROVEMENT] - Mutant Standards for EmojiReplace

### ISSUE THREAD

**Issue by shawny43** [mwittrien/BetterDiscordAddons#1738]
**Describe the solution you'd like**
Add Mutant Standards has option of the theme EmojiReplace

**Describe alternatives you've considered**
Mutant Standards is a emoji sets made by Dzuk where you can see any of design you could find. Similar to Windows 10 Emojis is come with a ton of emoji where no others emoji was used before. 

**Additional context**
Site: https://mutant.tech/

**Comment by mwittrien** [comment]
I can only add emoji providers from emojipedia
