### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by tinkeringwithoutsuccess** [mwittrien/BetterDiscordAddons#1739]
Hello, would be great if we can include some BetterFolders (https://github.com/Zerthox/BetterDiscord-Plugins/tree/master/src/BetterFolders) functionality in here, specifically close folders when opening a new folder. I tried myself but as my username suggests... Running both plugins together gives a funny looking server list.

**Comment by mwittrien** [comment]
Use ServerFolders instead of BetterFolderd

**Comment by tinkeringwithoutsuccess** [comment]
Thank-you
