### ISSUE TITLE
[HIDE/UNHIDE FAVORITES] - BetterFriendList

### ISSUE THREAD

**Issue by Zzeyy** [mwittrien/BetterDiscordAddons#1744]
**Describe the solution you'd like**
Add the option to hide / unhide friends that are marked as **favorite**.

**Describe alternatives you've considered**
No idea man, this is just a feature that I would really like to see this plugin have,
because it would make unfriending people much much easier.

**Comment by mwittrien** [comment]
Renove them from favorites and then hide them

**Comment by Zzeyy** [comment]
Yeah, I see. Why add an additional feature when you can spend time removing favorites.
