### ISSUE TITLE
[IMPROVEMENT] - Hidden Channel

### ISSUE THREAD

**Issue by TheGoldenSun** [mwittrien/BetterDiscordAddons#1746]
**Describe the solution you'd like**
A clear and concise description of what you want to happen. I was hoping if you're able to improve the hidden channel feature a little better. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Since the hidden channel feature was made back in 2021 perhaps with improvement into a new version instead of version 3.2.5 better discord users can use this feature wisely.

**Additional context**
![68747470733a2f2f6d776974747269656e2e6769746875622e696f2f426574746572446973636f72644164646f6e732f506c7567696e732f53686f7748696464656e4368616e6e656c732f5f7265732f636f7665722e706e67](https://user-images.githubusercontent.com/104534608/187770314-e8b37148-c716-416d-9794-b5ea1f92e861.png)

**Comment by mwittrien** [comment]
??? You didnt even say what you want improved

**Comment by mwittrien** [comment]
Dead
