### ISSUE TITLE
Problem with EditUsers

### ISSUE THREAD

**Issue by IndieRockerBliss** [mwittrien/BetterDiscordAddons#175]
I tried to configure the local user settings for my own user to test and see if the newly updated plugin works, but the configure screen doesn't show up on when i right click my username and clicked the change settings option, though the Local usersettings.

so hopefully you could fix this issue ASAP.

**Comment by IndieRockerBliss** [comment]
Well never mind, i fixed the issue that that i found from earlier not too long ago.

So.. it's all good.

**Comment by WindowsShadows** [comment]
And HOW?
