### ISSUE TITLE
[BUG] - SPOTIFY CONTROLS 1.2.5 /DEFAULT THEME

### ISSUE THREAD

**Issue by HlamPhoneAung** [mwittrien/BetterDiscordAddons#1751]
**Play, Pause, Forward, and Backward buttons are not showing correctly.**

I use AMOLED-Cord Theme but in the default theme also it shows me that square box instead of buttons but they still work as buttons except not showing correctly. 

![image](https://user-images.githubusercontent.com/90708197/188153013-ba7777cc-71fe-450e-b135-0cba9229b490.png)

**Comment by mwittrien** [comment]
Internet connection issue
