### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by CarterMcCall53** [mwittrien/BetterDiscordAddons#1752]
**Describe the bug**
Whenever I load discord canary with the library installed, it seems to create an "undefined" file and I've linked this to BDFDB because whenever I open the file, it always has mentions of BDFDB

**To Reproduce**
When you load discord canary/powercord with BDFDB in bdCompat

**Expected behavior**
It should load normally

**Discord Build (stable, ptb or canary):**
Im using canary

**Additional context**
The contents of the undefined file often change but it always has a mention of BDFDB. One example has been attached via PNG
![afUemOiuFN](https://user-images.githubusercontent.com/99932092/188254268-1d2bf863-df70-460e-8f67-b2a8e0a84a31.png)

**Comment by mwittrien** [comment]
My Stuff doesnt work with powercord

**Comment by CarterMcCall53** [comment]
It's worked before though. I have a mod called bdCompat which allows me to use better discord mods on powercord and its worked for over a year. Just now started bugging

**Comment by mwittrien** [comment]
bdCompat aint doing a full Bd adaption

My stuff is only made for the original BD
