### ISSUE TITLE
[BUG] - CutomStatusPresets

### ISSUE THREAD

**Issue by SliceTheDuck** [mwittrien/BetterDiscordAddons#1758]
**Describe the bug**
Menu to select custom status preset apearing in wrong place making it hardly posible to be clicked, tested with multiple diffrent themes all yielding a similar result.

**To Reproduce**
Hover over the change status option to make selection menu appear

**Expected behavior**
Menu appearing right next to the set custom status button

**Screenshots**
![image](https://user-images.githubusercontent.com/71396941/188316025-f24f76c0-4be0-4e3a-a170-07867b0510b0.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/71396941/188316037-e8502d56-87ac-44ae-826b-05b1ef852a08.png)

**Comment by mwittrien** [comment]
Looks just fine for me, no matter which theme i use
