### ISSUE TITLE
[BUG] - ShowHiddenChannels 

### ISSUE THREAD

**Issue by FlamingHawks** [mwittrien/BetterDiscordAddons#1760]
**Describe the bug**
When people are connected to a hidden voice channel it does not show them.

**To Reproduce**
Enable show connected people
People do not show up

**Expected behavior**
The voice channel members to show that they are connected to the vc

**Discord Build (stable, ptb or canary):**
Stable

**Comment by thunderstorm010** [comment]
Because of some shit BetterDiscord rules, they decided to discontinue ShowHiddenChannels.
I'm working on a fork to fix this.

**Comment by mwittrien** [comment]
Have fun getting banned
