### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Pabsb** [mwittrien/BetterDiscordAddons#1761]
**Describe the bug**
ShowHiddenChannels deleted itself and folder/file is empty

**To Reproduce**
Right as I opened up discord

**Expected behavior**
Plugin to not randomly delete itself

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable 145429 (57a0505)

**Additional context**
Should not be deleting itself without asking the user.

**Comment by mwittrien** [comment]
Try using your brain and read
