### ISSUE TITLE
[IMPROVEMENT] - plugin/translation

### ISSUE THREAD

**Issue by MNS26** [mwittrien/BetterDiscordAddons#1764]
**Describe the solution you'd like**
Being Dutch and having dyslexia makes me really struggle with reading and writing german, this plugin really helps A LOT.
One thing that has been a bit annoying is how you have to manually click translate on every message... Is it possible to add a channel/server wide translate mode/option so it automatically does every message? 

**Describe alternatives you've considered**
couldnt find any with comparable result

**Additional context**
when having it enabled it showing the text in its original language as italic (client side) would be a great  QOL option as well for it

**Comment by mwittrien** [comment]
Not possible due to api rate limits

**Comment by MNS26** [comment]
what about only new messages that have arrived?
