### ISSUE TITLE
[IMPROVEMENT] - THEME/EMOJIREPLACE - Add Fluent Emoji 3D

### ISSUE THREAD

**Issue by DeveloperWOW64** [mwittrien/BetterDiscordAddons#1765]
**Describe the solution you'd like**

Add Microsoft Fluent Emoji 3D as a separate emoji set for EmojiReplace

**Describe alternatives you've considered**

Perhaps also monochromatic emoji could be added.

**Additional context**

Since Microsoft recently OSS'd Fluent Emoji at https://github.com/microsoft/fluent-emoji it could be useful to use for obtaining images for emoji.

**Comment by mwittrien** [comment]
#1677
