### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by nkolistvnsn** [mwittrien/BetterDiscordAddons#1767]
**Describe the bug**
Plugin refuses to be disabled

**To Reproduce**
When the plugin is disabled in the plugin menu

**Expected behavior**
I expect the plugin to be disabled and stay disabled until I decide to re-enable it.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Discord Stable 145429 (57a0505)
BetterDiscord 1.6.3
Host 1.0.9006
Windows 10 64-Bit (10.0.19044)

**Additional context**
N/A

**Comment by mwittrien** [comment]
Because it makes no difference whether its enabled or not

**Comment by nkolistvnsn** [comment]
It does matter if it's disabled or not. If I want a plugin to be disabled, that should be my choice.

**Comment by mwittrien** [comment]
No
