### ISSUE TITLE
[BUG] - HIDE MUTED CATEGORIES

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#1768]
**Describe the bug**
The plugin does not work properly. After restarting discord (stable, ptb, canary) all categories are shown again. You have to deactivate and reactivate the plugin to hide the categories for the current session.

**To Reproduce**
Install the plugin, hide some categories, restart discord.

**Expected behavior**
Hidden categories should remain hidden even after restarting Discord

**Screenshots**
![2022-09-06_12h19_53](https://user-images.githubusercontent.com/1034673/188611154-cbbd1664-0001-4dec-829b-5161b14ac208.png)

**Discord Build (stable, ptb or canary):**
This happens on stable, ptb and canary.

**Additional context**

Tested with:

**BetterDiscord:** v1.6.3
**Hide Muted Categories:** v1.1.0
**Discord Clients:**
- Stable 145429 (57a0505) 
- Ptb 145547 (4d462f5)
- Canary 145547 (4d462f5)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord
