### ISSUE TITLE
[IMPROVEMENT] - Plugin Repo

### ISSUE THREAD

**Issue by Ekibunnel** [mwittrien/BetterDiscordAddons#1769]
**Describe the solution you'd like**
Add support for 3rd party repo via a text field in the plugins settings.
It would load a json file from link.
And add a switch to not load offcial betterdiscord plugins.

**Describe alternatives you've considered**
Make an copy of the 'Plugin Repo' called '3rd Party Plugin Repo' that would do the the same thing as describe earlier but it only load from that text field.

**Additional context**
In case of conflict (plugins with same file name from different repo) always load the offical one over an 3rd party one and logs the conflict.
if two 3rd party plugins are in conflict load none and display an toast error and report the error into logs.

**Mokup** :
![Mokup](https://i.imgur.com/CTYY72x.png)

**Template** for the repo json should be the same as the betterdiscord one except for the fields `id`, `github_id`, `github_name`, `discord_name`, `discord_avatar_hash`, `likes`, `downloads` that should be ignored even if present.

```json
[
	{
		"name": "TestPlugin",
		"type": "plugin",
		"description": "test plugin",
		"version": "1.0.1",
		"author": {
			"display_name": "DisplayName",
			"guild": null
		},
		"tags": [
			"enhancement",
			"utility"

		],
		"thumbnail_url": "https://i.oumgur.com/addsfgsdfg.png",
		"latest_source_url": "https://somewebsite.com/plugins/test/TestPlugin.plugin.js",
		"release_date": "2020-00-00T01:10:00Z",
		"guild": null
	},
	{
		"name": "localtestplugin",
		"type": "plugin",
		"description": "local test plugin on my computer",
		"version": "2.2.2",
		"author": {
			"display_name": "root",
			"guild": null
		},
		"tags": [
			"enhancement",
			"members"
		],
		"thumbnail_url": "E:/release/TestPlugin.png",
		"latest_source_url": "E:/release/TestPlugin.plugin.js",
		"release_date": "2022-02-02T00:0:02Z",
		"guild": null
	}
]
```

**Comment by mwittrien** [comment]
It mirrors the official repo

So no
