### ISSUE TITLE
Remove Nicknames removing your nickname even with options set correctly

### ISSUE THREAD

**Issue by HeartlessAUS** [mwittrien/BetterDiscordAddons#177]
![c5ec1de92236a374ae9d1b809617aa52](https://user-images.githubusercontent.com/47524314/53695449-1721ca00-3e10-11e9-9532-2827ad2bd6e5.png)
![4e381b89cf72548f986eb3be5ffe9fc6](https://user-images.githubusercontent.com/47524314/53695450-19842400-3e10-11e9-85d3-48083e531d7a.png)
![40e67e05fd397350035ed6909e19d59f](https://user-images.githubusercontent.com/47524314/53695451-1b4de780-3e10-11e9-9421-e963cf85f83f.png)

**Comment by HeartlessAUS** [comment]
found this error aswell
![bad3cfae0d6b6946198d3bbf0eec9902](https://user-images.githubusercontent.com/47524314/53695939-ce6d0f80-3e15-11e9-802a-45075bbcd599.png)

**Comment by mwittrien** [comment]
Fixed in newest version
