### ISSUE TITLE
[BUG] - HideMutedCategories

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#1771]
> Delete 0BDFDB.data.json and reload discord
> 
> _Originally posted by @mwittrien in https://github.com/mwittrien/BetterDiscordAddons/issues/1768#issuecomment-1239115590_

I have completely reinstalled BDFDB and updated it to the latest version. Nothing has changed in the behavior of the plugin

**Comment by mwittrien** [comment]
Dont just open new issue reports this freely
