### ISSUE TITLE
[BUG] - DisplayServersAsChannels (BDFDB)

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#1772]
### Describe the bug
After todays updates the Home button isn't constructed correctly

### To Reproduce
Install actual version of **DisplayServersAsChannels** and BDFDB and look at the home button

### Expected behavior
Home button should be constructed correctly

### Screenshots
![2022-09-07_13h11_41](https://user-images.githubusercontent.com/1034673/188864736-3beabab4-f682-46a4-ba4c-1362f6cbda02.png)

### Discord Build (stable, ptb or canary):
Stable, ptb and canary

### Versions
**BetterDiscord:** 1.6.3
**BDFDB:** 2.5.9
**DisplayServersAsChannels:** 1.6.0
**Discord:**
- Stable 145615 (1bfcc50)
- Ptb 145737 (834caea)
- Canary 145737 (834caea)

**Windows 10 64-Bit (10.0.19045)**

**Comment by mwittrien** [comment]
Reload discord
