### ISSUE TITLE
[BUG] - BDFBD stop working

### ISSUE THREAD

**Issue by BigBoss320** [mwittrien/BetterDiscordAddons#1783]
**Describe the bug**
BDFBD crashes, with an error message saying that it cannot connect to the internet. Apparently due to the fact that I "blocked it", I don't know what. However, I haven't touched anything.

**To Reproduce**
Open discord with better discord, load BDFBD

**Expected behavior**
Load the plugin to load all other plugins installed that depend on BDFBD

**Screenshots**
![image](https://user-images.githubusercontent.com/44122706/190917814-e776c1d2-d31b-4a0b-86ae-de7de9a6de44.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
All plugins that depend on BDFBD aren't working

**Comment by mwittrien** [comment]
If you are expierencing an Issue with BDFDB not initiating, try to download https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.data.json
and
https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.raw.css
and put them in your Plugins Folder. Afterwards reload Discord via `Ctrl + R`. This should fix the Issue of the Library not loading.
