### ISSUE TITLE
[BUG] - EditUsers crash Discord

### ISSUE THREAD

**Issue by lts20050703** [mwittrien/BetterDiscordAddons#1785]
**Describe the bug**
Discord crash

**To Reproduce**
Enable the EditUsers plugin

**Expected behavior**
EditUsers working, Discord doesn't crash

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/87189679/191167961-80ddbe90-7005-4420-9142-d26899a5602b.png">

**Discord Build (stable, ptb or canary):**
Canary 147967 (d8f1ccb)
BetterDiscord 1.6.3
Host 1.0.49

**Comment by mwittrien** [comment]
Cant reproduce

**Comment by lts20050703** [comment]
After another bisect I have concluded that enabling both AccountsDetailsPlus and EditUsers crash Discord
