### ISSUE TITLE
[BUG] - SpotifyControls

### ISSUE THREAD

**Issue by iGetUploaded** [mwittrien/BetterDiscordAddons#1787]
**Describe the bug**
- I'm not 100% sure what is going on but it doesn't seem to work on the Spotify app but works when I go to Spotify's website and play music there
**To Reproduce**
When does the bug occur.
- When I load up Spotify music app it doesn't show up but when I load Spotify on the browser the controls show
**Expected behavior**

**Screenshots**
- Video proof 

https://user-images.githubusercontent.com/54633753/191602678-9ca219bd-e836-491b-a02f-aca144e0eab5.mp4

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
- Stable
**Additional context**
I could be wrong but I'm pretty sure it used to work for the app version

**Comment by mwittrien** [comment]
Not an issue with the plugin

**Comment by iGetUploaded** [comment]
Figured it wasnt an issue with the plugin but just wanted to be sure thanks anyway

**Comment by JustOptimize** [comment]
I see that you are using spicetify, which is known to cause this kind of problem.
In addition to the plugin, you cannot access what is being played even from mobile/web, it is as if you are using two different accounts.

(I have the same problem but only on windows, on linux works fine)

**Comment by iGetUploaded** [comment]
Weird thing is I was using spicetify for a while and the plugin worked fine with it.. now it just doesn't work with it anymore for me

**Comment by JustOptimize** [comment]
Forget about it
