### ISSUE TITLE
(Spotify controls) UI disappearing after clicking

### ISSUE THREAD

**Issue by Keler69** [mwittrien/BetterDiscordAddons#1788]
UI disappearing after clicking

whenever i try to pause or play it just goes bye and also it doesnt do what you want it to do? like if you want to pause, it wouldnt pause so you have to go to the spotify app itself and the ui will disappear

**Comment by mwittrien** [comment]
Video?

**Comment by Keler69** [comment]
https://user-images.githubusercontent.com/110538492/191868410-c90128a0-aa91-4eb5-9fbe-9b37781ceb5c.mp4

**Comment by mwittrien** [comment]
Thats because you are using Spicetify
