### ISSUE TITLE
ImageUtilities - Quick Dowload and Quick Search dropdown not appearing 

### ISSUE THREAD

**Issue by deusExNoir** [mwittrien/BetterDiscordAddons#1791]
It's in the title. They don't appear
![load size maximum](https://user-images.githubusercontent.com/114308325/192112029-41838b95-5bd3-4f26-afac-5ad17a4b3a44.png)
Using the latest build of Discord and this only started happening after updating BDFB.
Tried to install the plugin directly from here but that also didn't work. Reloaded it, before and after the new one. Also reloaded BDFB. Nothing.

**Comment by Inconter** [comment]
same problem

**Comment by george2781** [comment]
Same problem as well

**Comment by deusExNoir** [comment]
> Same problem as well

> same problem
update BDFB
