### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities Image Saving Date

### ISSUE THREAD

**Issue by AdamSaketume26** [mwittrien/BetterDiscordAddons#1792]
**Describe the solution you'd like**
Can you make it when saving images it sets the date modified for the file as the same date the image or video was sent on discord?

**Describe alternatives you've considered**
https://github.com/Seklfreak/discord-image-downloader-go but idk if it does that plus it is a selfbot and i dont get to choose what i want

**Additional context**

**Comment by mwittrien** [comment]
Thats not in the scope of the plugins possibilities
