### ISSUE TITLE
[BUG] - Spotify Control Plugin

### ISSUE THREAD

**Issue by AviationRam** [mwittrien/BetterDiscordAddons#1794]
**Spotify Controls Not Working**

I'm quite confused about why it's happening as there was no error when loading in better discord.
But when I loaded into discord the Spotify control wasn't there even though I'm listening to Spotify. Is this related to any way of ZeresPluginLibary since a recent update ruined most plugins using that?

If not, is there something I'm missing?
<img width="596" alt="Screen Shot 2022-09-27 at 9 34 20 pm" src="https://user-images.githubusercontent.com/89292849/192516197-c03bfb6b-b795-4f47-abf2-173ee1a23a04.png">
<img width="235" alt="Screen Shot 2022-09-27 at 9 37 39 pm" src="https://user-images.githubusercontent.com/89292849/192516224-fafda174-ea97-40dd-9ef6-c8dada2d9d2c.png">

<img width="238" alt="Screen Shot 2022-09-27 at 9 37 47 pm" src="https://user-images.githubusercontent.com/89292849/192516239-d8bfd3b8-79ef-47d8-8585-77d276fdc070.png">

I've tried to reinstall the plugin to no luck and also tried reconnecting my Spotify account.

**Comment by AviationRam** [comment]
<img width="534" alt="Screen Shot 2022-09-27 at 9 46 32 pm" src="https://user-images.githubusercontent.com/89292849/192517106-62469a4f-3cc9-46d4-b416-d1b32728295d.png">

Checked the DevTools and lots of errors.

**Comment by AviationRam** [comment]
<img width="455" alt="Screen Shot 2022-09-27 at 9 49 51 pm" src="https://user-images.githubusercontent.com/89292849/192517649-defc9795-0735-4fcf-8dc5-12223b949fbb.png">
I didn't edit any plugin but this line present with the most errors.

**Comment by Hydro001** [comment]
BDFDB dependent plugins are currently broken due to massive Discord internal changes, check the Discord, there's some more explanation about it if you want to read it 👍

**Comment by mwittrien** [comment]
all plugins are broken, wait till a mayor update comes
