### ISSUE TITLE
[BUG] - BDFDB Library

### ISSUE THREAD

**Issue by a1337spy** [mwittrien/BetterDiscordAddons#1798]
**Describe the bug**
BDFDB, and by extension all plugins that uses it refuses to initiates on the latest version of BetterDiscord, printing an error stating
that it could not initiate BDFDB Library Plugin, even though github is not blocked on my network, and I don't have a VPN, and my internet connection is fine.

**To Reproduce**
Launch Discord with BDFDB enabled.

**Expected behavior**
BDFDB loads, along with other plugins using BDFDB.

**Screenshots**
![image](https://user-images.githubusercontent.com/5660399/192613270-d65f3c95-fdc9-4ee3-8301-dc571a6397ab.png)
This is the error that BDFDB produces.

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Github has not been blocked by my network, my internet connection is stable, and I do not have a VPN/proxy on. I checked the console and nothing besides 
![image](https://user-images.githubusercontent.com/5660399/192613614-98f973a2-ed93-4ef0-bebd-3795dc674c07.png)
this is output to the console.

**Comment by mwittrien** [comment]
All plugins are broken thx to discord
