### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by lilcryte** [mwittrien/BetterDiscordAddons#18]
When i downloaded the plugin. I can't access the plugins tab in discord.

**Comment by OutDark** [comment]
I have the same problem. I don't know what causes it, but it's probably because it's outdated. If the creator ever updates this, it'll probably get fixed.

**Comment by mwittrien** [comment]
"the plugin"

**Comment by mwittrien** [comment]
Since i am using all my plugins myself and all my plugins are updated, everything works fine
