### ISSUE TITLE
[BUG] - BDFDB Library 

### ISSUE THREAD

**Issue by DualityStudios** [mwittrien/BetterDiscordAddons#1801]
**Describe the bug**
If I try to click the 'settings' button on any plugin that has it, it gives the error message: `could not open settings for <plugin>`, where `<plugin>` is the plugin I was trying to modify.

**To Reproduce**
Install the latest version of the library from the website and open any plugin's settings panel

**Expected behavior**
I expected a panel to open up allowing me options on my plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/79718937/192659715-026da796-8a0a-43ae-a430-0db9b0abf8fc.png)

**Discord Build (stable, ptb or canary):**
canary

**Additional context**
Discord Canary Build: `Canary 149674` running on Windows 11

**Comment by Auron-FFX** [comment]
None of the plugins themselves work either.

**Comment by DualityStudios** [comment]
> None of the plugins themselves work either.

I assumed that was due to something in settings - but I am also experiencing this issue. Thanks!

**Comment by MistressAshai** [comment]
You should check existing issues before posting.
Everything is broken due to Discord itself right now.

**Comment by DualityStudios** [comment]
sorry.
