### ISSUE TITLE
[BUG] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by bestpika** [mwittrien/BetterDiscordAddons#1803]
**Describe the bug**

This thing is broken and can not open the settings.

**To Reproduce**

1. Install then enabled it.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/192678182-981fdc28-89c9-4deb-a528-cfa2e129be1c.png)
![image](https://user-images.githubusercontent.com/5698157/192678539-48cacbf8-66a1-4758-9bb1-2a4c1c58bd1c.png)

**Discord Build (stable, ptb or canary):**

- stable

**Additional context**

- BDFDB | v2.6.5
- DisplayServersAsChannels | v1.6.0

**Comment by mwittrien** [comment]
all plugins are broken, wait till a mayor update comes
