### ISSUE TITLE
[no symbol] - GameActivityToggle

### ISSUE THREAD

**Issue by Elisaever** [mwittrien/BetterDiscordAddons#1804]
There is no controller symbol to toggle for game activity anymore
The bug occurred after updating BetterDiscord
Usually, after updating BetterDiscord the plugin is still working

**Discord Build (stable, ptb or canary):**
 PC stable

![Uploading Screenshot 2022-0
![Screenshot 2022-09-28 172652](https://user-images.githubusercontent.com/114564799/192715560-884fac09-3fa5-47d3-83a5-afb22b614990.jpg)
9-28 172625.jpg…]()

**Comment by mwittrien** [comment]
all plugins are broken, wait till a mayor update comes
