### ISSUE TITLE
[BUG] - All plugins

### ISSUE THREAD

**Issue by Cyberlane** [mwittrien/BetterDiscordAddons#1805]
**Describe the bug**
None of your plugins are working for me anymore.
On top of which, the Plugin Repo and Theme Repo plugins are in a constant loading state at the bottom right of Discord.

**To Reproduce**
Fresh install of Discord, apply better discord, paste all the plugins I use into the folder. They show up in the "Plugins" page, I can enable them, but none of yours work any more.

**Expected behavior**
For the plugins to work.

**Screenshots**
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1614416/192795159-30be0fce-a1f5-431b-b142-fc9a7dc1a604.png">

**Discord Build (stable, ptb or canary):**
macOS Stable: 0.0.268

**Additional context**
I have tried removing Better Discord and Discord, doing a fresh install and copying the plugins over again in hopes of fixing the issue but it remains the same unfortunately. When I try to click on the Settings button for BDFDM, I see the following:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1614416/192795635-bee7904d-187c-4a58-a1ea-7d3a6aac17f9.png">

**Comment by mwittrien** [comment]
all plugins are broken, wait till a mayor update comes
