### ISSUE TITLE
[BUG] - CustomStatusPresets not working

### ISSUE THREAD

**Issue by Masono03** [mwittrien/BetterDiscordAddons#1808]
**Describe the bug**
CustomStatusPresets doesnt appear at all and when i click on settings in the plugin menu it gives me a error that leads to the console.

**To Reproduce**
dunno really i just installed it and it aint workin.

**Expected behavior**
being able to create status presets

**Screenshots**
[https://drive.google.com/drive/folders/1BCmHiJu31dvYeUkNYLPuVjgC2pdxmB1c?usp=sharing](url)

**Discord Build (stable, ptb or canary):**
Canary 150344 (0427acf) Host 1.0.49 Windows 10 64-Bit (10.0.19044)

**Additional context**
Thought since upload said 12h ago it would work but if all are still broken sorry for opening this.

**Comment by mwittrien** [comment]
#1806
