### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by black-trush** [mwittrien/BetterDiscordAddons#1809]
**Describe the bug**
setting panel work.
but dosen't work.
don't display extra controles.

**To Reproduce**
everytime

**Expected behavior**
BD feature update or BDFDB update or this plugin update

**Screenshots**
![2022y10m01d_011108092](https://user-images.githubusercontent.com/70010919/193315853-0480beae-8adc-4c6d-814d-146427d98322.png)
![2022y10m01d_011135481](https://user-images.githubusercontent.com/70010919/193315941-a3f8b62d-8b11-4381-9ede-6a1ac733039a.png)

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
#1806
