### ISSUE TITLE
[BUG] - Translator.plugin

### ISSUE THREAD

**Issue by piercingeye** [mwittrien/BetterDiscordAddons#1811]
![1664629769273](https://user-images.githubusercontent.com/48711764/193411082-984f6b6d-d699-4479-99c8-8b86c06b5de1.png)
![1664629814726](https://user-images.githubusercontent.com/48711764/193411099-15ac5e7f-2e29-4dc9-96f5-5b489834e110.png)
![1664629905358](https://user-images.githubusercontent.com/48711764/193411156-3d1fd17b-44d9-4daf-9ffc-b974a54ecb0b.png)

**Comment by mwittrien** [comment]
#1806
