### ISSUE TITLE
[BUG] - General Error

### ISSUE THREAD

**Issue by Shachar87** [mwittrien/BetterDiscordAddons#1813]
Just add the JS file to plugin folder and get an error

![image](https://user-images.githubusercontent.com/7179322/193524294-a464891b-ddbd-4602-8942-b664d31ef0cb.png)

**Discord Build (stable, ptb or canary):**
Stable 150489 (4590418)
Host 1.0.9006
Windows 10 64-Bit (10.0.19044)

**Comment by mwittrien** [comment]
#1806
