### ISSUE TITLE
[BUG] - PluginRepo

### ISSUE THREAD

**Issue by Mujina7569** [mwittrien/BetterDiscordAddons#1818]
**Describe the bug**
PluginRepo not show in side menu, i try restart discord but it's still not show

**To Reproduce**
Right after install plugin

**Expected behavior**
PlufinRepo can access and download plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/32309057/195012793-d95bfc53-5d30-4dad-a315-9eb5b97ccad1.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
-

**Comment by mwittrien** [comment]
#1806
