### ISSUE TITLE
[BUG] - BDFDB starts uncorrectly

### ISSUE THREAD

**Issue by WingingSpace** [mwittrien/BetterDiscordAddons#1819]
**Describe the bug**
Uncorrect start

**To Reproduce**
When i start a plugin/libary BDFDB

**Screenshots**
![image](https://user-images.githubusercontent.com/115087122/195063076-492ecc85-fcc4-469b-becb-6cb6e1767802.png)

**Discord Build (stable, ptb or canary):**
Stable 151638 (3ce0196)
**Additional context**
When i start a bdfdb write: BDFDB on
BDFDB off at once moment

**Comment by Cyberlane** [comment]
@WingingSpace - check existing bugs before opening new ones.

#1806

**Comment by mwittrien** [comment]
Try reloading Discord 

It doesnt matter if BDFDB is enabled or not anyways
