### ISSUE TITLE
EditServers banner issue

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#182]
When the banner of a server is in view, the scrollbar for scrolling down the list of channels disappears for some reason.

**Comment by mwittrien** [comment]
That's discords native behaviour and not due to my plugin

**Comment by mwittrien** [comment]
discord changed how banners work on canary, this includes the scrollbar not being hidden when a banner is visible, so jsut wait for stable to get the banner fix
