### ISSUE TITLE
[BUG] - PluginRepo

### ISSUE THREAD

**Issue by CommandCracker8** [mwittrien/BetterDiscordAddons#1820]
**Describe the bug**
When I open the "Plugin Repo" tab in Discord, it gets really laggy and then after a few seconds it crashes (it does load the plugin repo though)

**To Reproduce**
Download & Install Plugin Repo
Open the Plugin Repo tab
Voila

**Expected behavior**
It not to crash

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by maxwellainatchi** [comment]
#1806

**Comment by CallMeLewis** [comment]
> **Describe the bug** When I open the "Plugin Repo" tab in Discord, it gets really laggy and then after a few seconds it crashes (it does load the plugin repo though)
> 
> **To Reproduce** Download & Install Plugin Repo Open the Plugin Repo tab Voila
> 
> **Expected behavior** It not to crash
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Discord Build (stable, ptb or canary):** Stable
> 
> **Additional context** N/A

Can also confirm that the same reported problems happen with "Theme Repo" too.

**Comment by Refrac** [comment]
This also happens for me with Plugin & Theme Repo

**Comment by AerGameChannel** [comment]
Same happens for me

**Comment by CptDinosaur** [comment]
Not sure if it's related; but my plugin repo gets stuck on 192/198, and theme repo 108/115

**Comment by reddazxfi** [comment]
it happens the same to me, it's very laggy even tho cpu is at 30%, it also happens with hardware acceleration activated, and i 
saw that discord's memory usage goes from 500 MB to 1.3 GB when trying to browse that, it goes back down to 500 mb when i close it

**Comment by ReikoTigon** [comment]
My Plugin Repo doesn't even appear, but I don't get any erros

**Comment by Dviper18** [comment]
Deleted 0BDFDB.data.json and reloaded. This fixed the issue
