### ISSUE TITLE
[BUG] - A LOT OF PLUGINS CRASHING THE CLIENT

### ISSUE THREAD

**Issue by Pejsek34** [mwittrien/BetterDiscordAddons#1823]
Describe the bug
When I put most of the plugins I use into my plugins folder, Discord crashes with this error (added in Screenshot). Earlier today, Discord booted up normally with no issues. I have tried multiple plugins and some of the ones that crash the client are CreationDate, SplitLargeMessages, GameActivityToggle, InvisibleTyping, CallTimeCounter, Freemoji and SpotifyListenAlong, I have no clue what these plugins have in common, so if there is an easy explanation, I am sorry. Plugins that don't crash my client are all the LIBs I use, ShowHiddenChannels, SpotifyControls, BetterVolume and UserVolumeBooster. 

To Reproduce
Place a certain plugin into the plugins folder (all the plugins didn't crash earlier today, they didn't work because of the longer lasting issue of all plugins not working)

Expected behavior
It does not crash with "Error Level 9000"

Screenshots
![image](https://user-images.githubusercontent.com/88139473/195172612-fc986a42-e9d1-44d9-962d-1dedcee5d93f.png)

Discord Build (stable, ptb or canary):
Stable

Additional context
N/A

**Comment by mwittrien** [comment]
#1806
