### ISSUE TITLE
[BUG] - All Plugins By DevilBro

### ISSUE THREAD

**Issue by LewdAleks** [mwittrien/BetterDiscordAddons#1824]
**Describe the bug**
addon error, i cant open discord without it crashing i had to take all my plugins out and the only that loaded/would let discord open without crashing was 0BDFDB and its saying meta was not found only happens when downloaded thought github
**To Reproduce**
When does the bug occur.
to reproduce the meta was not found download 0BDFDB off of the git hub
**Expected behavior**
for it to load without a error
**Screenshots**
https://cdn.upload.systems/uploads/78Ycijz0.png
**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
stable
**Additional context**

**Comment by LewdAleks** [comment]
(i dont remember how to make it showup as a image and not a link but thats what i see when it loads)

**Comment by mwittrien** [comment]
You didnt download thd plugin you downloaded the webpage
