### ISSUE TITLE
[BUG] - PLUGIN/Plugin Repo

### ISSUE THREAD

**Issue by nsx553** [mwittrien/BetterDiscordAddons#1827]
**Describe the bug**
When I open discord after installing the plugin and adding it to the folder, it doesn't do anything. No "PluginRepo" tab, nothing.

**To Reproduce**
Install the plugin
Put it in the Plugin folder
Open BD

**Expected behavior**
Visible and interactable PluginRepo tab allowing me to access other plugins with ease.

**Screenshots**
![image](https://user-images.githubusercontent.com/115599120/195226068-d5ce3bce-a09a-455b-b428-583591d472dc.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload

**Comment by Evoley** [comment]
> Delete 0BDFDB.data.json and reload

I did that and it's still not showing

**Comment by axcyia** [comment]
> > Delete 0BDFDB.data.json and reload
> 
> I did that and it's still not showing

Same thing here. Same issue as well.

**Comment by Ajisaii** [comment]
Having the same issue

**Comment by Williampprado** [comment]
Having the same issue

**Comment by eclipsek20** [comment]
Someone should merge this with #1820
