### ISSUE TITLE
[BUG] - PinDMs doesn't function.

### ISSUE THREAD

**Issue by MagmaBro123** [mwittrien/BetterDiscordAddons#1828]
**Describe the bug**
Plugin does not function. No Pin button appears in DM lists.

**To Reproduce**
Install this plugin.

**Expected behavior**
The plugin to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/51277766/195255902-a3855728-07b2-4b1e-bae6-b60573806027.png)

**Discord Build (stable, ptb or canary):**
Canary.

**Additional context**
N/A

**Comment by mwittrien** [comment]
#1806
