### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by owl-herd** [mwittrien/BetterDiscordAddons#1833]
**Describe the bug**
Notification sounds are played when there is no message or anything. No server shows up with messages either. Cant find any place that would produce the notification sound. (this has been happening since before the recent BD update, I disabled the addon before but I thought I'd submit an issue now since I like the addon)

**To Reproduce**
Just turn on the plugin, and it will produce notification sounds at random.

**Expected behavior**
Notification sounds only when there is a notification.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
#1806
