### ISSUE TITLE
[BUG] - BDFDB Plugin Update Notification Cut Off

### ISSUE THREAD

**Issue by JasonHorkles** [mwittrien/BetterDiscordAddons#1834]
**Describe the bug**
The notification saying plugins have updates tends to not be centered correctly

**To Reproduce**
Happens whenever one of these plugin updates are released

**Expected behavior**
It should be centered on the screen properly

**Screenshots**
![image](https://user-images.githubusercontent.com/51760372/195403442-6d1d819a-3923-49f3-9c6b-2d79baaefa79.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Also happened before Discord broke everything
Another thing to note is that BD now has a built-in plugin updater as of 1.8.0, so not sure how needed the BDFDB one is anymore

**Comment by mwittrien** [comment]
No clue what causes that, never happend to me
