### ISSUE TITLE
[BUG] - plugins that are fixed dont load nor show up on bd 1.8

### ISSUE THREAD

**Issue by LewdAleks** [mwittrien/BetterDiscordAddons#1837]
**Describe the bug**
none of the plugins you fixed work on betterdiscord v1.8.0
**To Reproduce**
When does the bug occur.
they dont showup in the plugin tab nor load
**Expected behavior**
for them to load and display in plugin tab
**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
stable
**Additional context**

**Comment by LewdAleks** [comment]
idk if u knew this or not but wanted to make a issue for it as in the discord atleast the plugins that u have in the update list that are working dont load nor work with bd 1.8.0 (the latest bd ver)

**Comment by mwittrien** [comment]
How do they not load

**Comment by derpyderpaderp** [comment]
> How do they not load

I noticed for instance plugin repo is loaded but do not show up in the settings>Betterdiscord area for instance https://i.imgur.com/KKrbNWW.png clearly pluginrepo is enabled but cannot be seen in the betterdiscord area.

**Comment by ThatXliner** [comment]
I am experiencing this bug as well

**Comment by mwittrien** [comment]
> I noticed for instance plugin repo is loaded but do not show up in the settings>Betterdiscord area for instance https://i.imgur.com/KKrbNWW.png clearly pluginrepo is enabled but cannot be seen in the betterdiscord area. 

Because you havent updated them, 2.3.7 is an old version
