### ISSUE TITLE
[BUG] - CopyRawMessage

### ISSUE THREAD

**Issue by Harnoldzen** [mwittrien/BetterDiscordAddons#1838]
**Describe the bug**
The plugin can't copy the message/etc, when you try paste no have nothing copied.

**To Reproduce**
Just turn of and try copy any embed or edited message.

**Expected behavior**
Copy the fully edited message.

**Screenshots**
no

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
no

**Comment by mwittrien** [comment]
#1806
