### ISSUE TITLE
[BUG] - Trying to expand "Friend-List" in FriendNotifications settings causes an error

### ISSUE THREAD

**Issue by ShamblesSM** [mwittrien/BetterDiscordAddons#1842]
**Describe the bug**
When trying to expand "Friend-List" in FriendNotifications' settings, the settings modal popup will notify the user of an error.

**To Reproduce**
1. Open the User Settings and find BetterDiscord > Plugins
2. Open FriendNotifications' Settings
3. Click on "Friend-List".

**Expected behavior**
Friend-List dropdown menu should expand.

**Screenshots**
![image](https://user-images.githubusercontent.com/115082072/195575813-514a68fa-2b7c-4299-8f98-12359e309c61.png)

**Discord Build (stable, ptb or canary):**
Stable `app-1.0.9006`

**Comment by mwittrien** [comment]
Update the plugin
