### ISSUE TITLE
[BUG] - 0BDFDB

### ISSUE THREAD

**Issue by barbaduk** [mwittrien/BetterDiscordAddons#1844]
**Describe the bug**
Settings for BDFDB and all other DevilBro's plugins doesn's work (as well as the plugins itself does do nothing)

**To Reproduce**
First plugins auto-updated, then downloaded it manually from #downloads channel in discord, same behavior

**Screenshots**
![изображение](https://user-images.githubusercontent.com/41954202/195587884-fdfd2a34-fa6e-4ffd-9fdf-ba759054e814.png)

**Discord Build (stable, ptb or canary):**
Stable 152131 (6ed73b9)
Host 1.0.9006
Windows 10 64-Bit (10.0.19041)

**Additional context**
Tried deleting plugins folder and re-downloading them again, still doesn't work...

**Comment by mwittrien** [comment]
If you are expierencing an Issue with BDFDB not initiating, try to download https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.data.json
and
https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.raw.css
and put them in your Plugins Folder. Afterwards reload Discord via `Ctrl + R`. This should fix the Issue of the Library not loading.
