### ISSUE TITLE
[BUG] - ServerDetails Not Working

### ISSUE THREAD

**Issue by zuzumi-f** [mwittrien/BetterDiscordAddons#1845]
**Describe the bug**
The ToolTip for ServerDetails does not appear, no matter what (Reloading, desable and enable again, redownload).

**To Reproduce**
Enable the plugin, nothing happen.

**Expected behavior**
Show a tooltip with the *ServerDetails*.

**Screenshots**
![Discord_vUMpaxfcwe](https://user-images.githubusercontent.com/79029257/195601087-761cb582-a66d-4205-9b21-aa33b450da93.gif)

**Discord Build (stable, ptb or canary):**
Stable 152131 (6ed73b9)

**Additional context**
Console Log
![image](https://user-images.githubusercontent.com/79029257/195601836-511843bc-3476-468b-aa7f-a40c14ad4d2f.png)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord

**Comment by zuzumi-f** [comment]
Working again, thank you
