### ISSUE TITLE
[BUG] - PLUGIN/Translator

### ISSUE THREAD

**Issue by kegvorn** [mwittrien/BetterDiscordAddons#1846]
**Describe the bug**
Hi! Thanks for the plugins!
I have the translator plugin installed.
But for some reason,
![2022-10-13_155945](https://user-images.githubusercontent.com/98895367/195603650-480c2393-3972-4f94-9d93-463764a88233.jpg)
![2022-10-13_160022](https://user-images.githubusercontent.com/98895367/195603654-fa4d3a98-1e10-4293-a16d-79d8fab83db0.jpg)
 I can not use it

**Comment by itoffie** [comment]
its due to the recent BDFDB update which fixed ImageUtilities partially, wait for the github update or the "xx hrs ago or days ago" else the update fix for it will pop up in discord, either way translator is one of the top priority on the discord list which means it will get fixed asap

**Comment by kegvorn** [comment]
> its due to the recent BDFDB update which fixed ImageUtilities partially, wait for the github update or the "xx hrs ago or days ago" else the update fix for it will pop up in discord, either way translator is one of the top priority on the discord list which means it will get fixed asap

Thank you for your response Mr.

**Comment by mwittrien** [comment]
Its not fixed yet #1806
