### ISSUE TITLE
[BUG] - ImageUtilities Incomplete

### ISSUE THREAD

**Issue by zuzumi-f** [mwittrien/BetterDiscordAddons#1848]
**Describe the bug**
ImageUtilities has missing features (Gallery, Zoom, Image Info, Additional buttons).
Only ContextMenus work.

**To Reproduce**
Happens with all images (Avatars, Banners, Embed, etc).

**Expected behavior**
Zoom in images, have a gallery, see for image info.

**Screenshots**
![Discord_6iDPOVM8cl](https://user-images.githubusercontent.com/79029257/195609684-6d638b6a-a247-45d7-a12b-d39d209ebbfe.gif)

**Discord Build (stable, ptb or canary):**
Stable 152131 (6ed73b9)

**Additional context**
In the screenshots i didn't open context menus, but they don't work there either.

**Comment by zuzumi-f** [comment]
I just realized what happens when you open the context menus there.
![image](https://user-images.githubusercontent.com/79029257/195611358-7e063a69-26c4-4464-aa71-3118b2787f2c.png)

![Discord_TE00g2KgMv](https://user-images.githubusercontent.com/79029257/195611882-a812f8fd-ed55-451b-a752-0ce2be0553f1.gif)

**Comment by Vad1mCSO2** [comment]
![image](https://user-images.githubusercontent.com/76803825/195646181-e4f9cb22-d583-4109-8096-6bbcbccfd2fa.png)
this is only 1st action after refreshed

**Comment by Vad1mCSO2** [comment]
![image](https://user-images.githubusercontent.com/76803825/195646436-5c048287-631e-40b5-b313-e10e7bba3d2e.png)
after refreshed Image actions is lit

**Comment by Vad1mCSO2** [comment]
then unlit

**Comment by mwittrien** [comment]
> ![image](https://user-images.githubusercontent.com/76803825/195646436-5c048287-631e-40b5-b313-e10e7bba3d2e.png)
> after refreshed Image actions is lit

There is an issue with bd context menu patches, which will be fixed soon

**Comment by mwittrien** [comment]
> **Describe the bug**
> ImageUtilities has missing features (Gallery, Zoom, Image Info, Additional buttons).
> Only ContextMenus work.
> 
> **To Reproduce**
> Happens with all images (Avatars, Banners, Embed, etc).
> 
> **Expected behavior**
> Zoom in images, have a gallery, see for image info.
> 
> **Screenshots**
> ![Discord_6iDPOVM8cl](https://user-images.githubusercontent.com/79029257/195609684-6d638b6a-a247-45d7-a12b-d39d209ebbfe.gif)
> 
> **Discord Build (stable, ptb or canary):**
> Stable 152131 (6ed73b9)
> 
> **Additional context**
> In the screenshots i didn't open context menus, but they don't work there either.
> 

Delete 0BDFDB.data.json and reload

**Comment by KingGamingYT** [comment]
This indeed fixed the features, and mostly everything seems to work...except actually copying images. There is no toast notification and nothing is added to the clipboard.
