### ISSUE TITLE
[BUG] - ServerHider

### ISSUE THREAD

**Issue by davezon02** [mwittrien/BetterDiscordAddons#1851]
**Describe the bug**
The plugin just doesnt work -- the server visibility button doesnt appear in the guild context menu and still doesn't in the folder context menu.

**To Reproduce**
Enable the latest version of ServerHider with the latest version of BDFD installed

**Expected behavior**
The addon is supposed to be fixed but it doesnt show any button to hide any server

**Screenshots**

**Discord Build (stable, ptb or canary):**
Ptb 152193 (5c375a2)

**Additional context**
ServerHider version 6.2.5
BDFDB v2.7.4
BetterDiscord v1.8.0

**Comment by davezon02** [comment]
There is no error on the developers debug console.

**Comment by mwittrien** [comment]
There is an issue with context menu patches done by BD, it should be fixed in 1.8.1 soon
