### ISSUE TITLE
[BUG] - ImageUtilities - Files download corrupted

### ISSUE THREAD

**Issue by SlamWeasel** [mwittrien/BetterDiscordAddons#1852]
First of all, thank you for your hard work to fix the Plugins

But sadly, when I download anything, its almost twice the size as when its traditionally downloaded, and cant be opened by any program (even GIMP cant open the downloaded image files

It just happens up download

![image](https://user-images.githubusercontent.com/63350349/195655058-c37e67db-4e8a-48a8-bb01-cd33740c0177.png)
![image](https://user-images.githubusercontent.com/63350349/195655119-52addfc8-2894-4a29-aa5e-f90f439383dc.png)
![image](https://user-images.githubusercontent.com/63350349/195655187-d9b15026-39fe-486e-8494-bea825104bbf.png)
(Its literally the same video, downloaded from the same place)

My DiscordBuild is Stable 152131 (6ed73b9)

**Comment by mwittrien** [comment]
Ill check tomorrow
