### ISSUE TITLE
Game Activity Toggle & Read All Notifications Bug

### ISSUE THREAD

**Issue by EasyBye** [mwittrien/BetterDiscordAddons#1853]
Hey, I have the plugin "GameActivityToggle" & the plugin "ReadAllNotificationsButton"
But both are not working at all, could you help please?
![Capture](https://user-images.githubusercontent.com/44577919/195657538-4bee5fc7-9a15-46ca-a067-5e3313601415.PNG)
![Capture1](https://user-images.githubusercontent.com/44577919/195657544-ca5e802b-3980-49a4-9dc3-8db58022dc39.PNG)
![Capture2](https://user-images.githubusercontent.com/44577919/195657546-a4337d4e-6a59-46be-bfbd-adf0a45fd6d0.PNG)

**Comment by mwittrien** [comment]
What version is your BDFDB plugin

**Comment by EasyBye** [comment]
BDFDB v2.6.5

**Comment by walshy4007** [comment]
Same issue, same version. https://gyazo.com/82133489ecf40c75096da41ef0296aec

**Comment by mwittrien** [comment]
Newest is 2.7.4
