### ISSUE TITLE
Still cant get plugins to work

### ISSUE THREAD

**Issue by SutekiRedux** [mwittrien/BetterDiscordAddons#1855]
Doing the same as what the website is telling me and what i did before discord had the update that messed up plugins. I am downloading the plug in and putting it into my plugins folder 

![f712a3c309bbb0e2b64f5baee639ea0b](https://user-images.githubusercontent.com/78438815/195711565-66ab07dc-a068-4ca8-965b-2d0dd32e1f09.png)

all of my themes work however, just cant seem to get these work.

**Comment by SweetLuna** [comment]
Same issue

**Comment by mwittrien** [comment]
How do they not work

**Comment by SutekiRedux** [comment]
they show up in "Plugins" on better discord, but things like the PluginRepo, ReadAllNotifs, just dont show up like they used too, theres no read all button above the servers, and no PluginRepo tab in settings. I could try other updated plugins? 

when i would download directly into the pluginfolder i would get the META notification so i tried downloading to my downloads folder and dragging them into the plugins folder, where i dont get any error messages but still doesnt actually let the plugins work. 

better discord is up to date, and all plugins im downloading straight from the better discord website

**Comment by SutekiRedux** [comment]
![a1068fd2bbc17c5686ae1f74d75db138](https://user-images.githubusercontent.com/78438815/195724084-77e0a9d8-b4ec-42ef-93cf-6bc1e31ccb8e.png)

**Comment by mwittrien** [comment]
Your BDFDB plugin is heavily outdated
