### ISSUE TITLE
[BUG] - User Volume Knob

### ISSUE THREAD

**Issue by michaelsucks** [mwittrien/BetterDiscordAddons#1857]
**Describe the bug**
Library bugs user volume control knob.

**To Reproduce**
Drag users volume knob either left or right. Increments only increase/decreases by +1 or -1 and stops. 

**Expected behavior**
Smooth user volume increase/decrease without stopping.

**Video of Issue**
https://user-images.githubusercontent.com/115754268/195774356-51b8c46d-c938-466c-8413-b78590ddd8af.mp4

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Deleted all plugins and found that the Library was the issue.

**Comment by MythiixLtd** [comment]
I also have this problem its very annoying
