### ISSUE TITLE
[BUG] - BDFDB Affecting Volume Slider

### ISSUE THREAD

**Issue by itoffie** [mwittrien/BetterDiscordAddons#1858]
**Describe the bug**
Volume slider on call only sliding upto 2-3% and stops after mouse is no longer around the "grabber-2GQyvM" class

**To Reproduce**
This happens if BDFDB is on the plugins folder
as disabling the BDFDB library just auto runs itself back the solution to test the issue is : 
going to Plugins Folder > Move the 0BDFDB files to a blank/different folder > Refresh Discord > the slider is fixed

*Disabling all DevilBro plugins doesnt fix the issue

**Screenshots**
as can be seen here the said class is not functioning normally
https://user-images.githubusercontent.com/64309702/195774650-f20a3a7e-5c4c-4986-8f7e-3b0d2600d013.mp4

**Discord Build (stable, ptb or canary):**
Stable 152131 (6ed73b9)

**Comment by mwittrien** [comment]
#1857
