### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by TheSuspect2306** [mwittrien/BetterDiscordAddons#1859]
Im not sure if i just cant find the feature but here it is:

- Europe Format, when i use $date, the date is Month/Date/Year, Date/Month/Year would be better if there is a setting for this, i know that there is a $donth, or $day but the problem is that there isnt a number date format like $date

- Only show specific Friends in the Toast and Timelog everything from everyone at the same time, for example: when i have friend1 as only timelog, the timelog doesnt show him at all since i dont check something like "online", friend2 i have everything and that works without any problem, but like i said i cant say that friend1 will show everything in the timelog but not in the Toast, theres only SHOW or not SHOW sadly

**Comment by mwittrien** [comment]
1. You can change the format in the plugin settings by clicking the calendar icon

2. Timelog means that the other options that are shown in the toasts will be added to the timelog, there is no option to timelog a user without showing a toast because thats not the intended behaviour
