### ISSUE TITLE
[BUG] - ImageUtilities - Image Actions in context menu is gone after 4 times open context menu in player

### ISSUE THREAD

**Issue by Vad1mCSO2** [mwittrien/BetterDiscordAddons#1860]
**Describe the bug**
After refreshed discord "Image Actions" context menu in players is have, After 4 times opening player context menu is gone.

**Screenshots**
![image](https://user-images.githubusercontent.com/76803825/195790307-b32f026d-b97c-4ef0-86e4-10d881ccc6ee.png)
![image](https://user-images.githubusercontent.com/76803825/195791973-d959c475-4daf-4e8c-8fc0-20f21ece28b9.png)

Discord build PTB 152285 (47055c8)

**Comment by mwittrien** [comment]
Known issue with BD, will be fixed in 1.8.1

**Comment by mwittrien** [comment]
Should be fixed on sunday
