### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by ilytouni** [mwittrien/BetterDiscordAddons#1861]
Just recently, I found out a bug that I'm not sure if it happens for everybody or what but it's been recurring every time I would copy an image using the ImageUtilities plugin.

It happens every time I try to copy and paste an image.

Obviously it's supposed to copy and when pasted it should be pasted but that's not what happened. Instead, it pastes nothing (within the video I had already copied an image / link **_without_** using the ImageUtilities plugin)

Copy and Pasting Using ImageUtilities Plugin:
https://user-images.githubusercontent.com/74092353/195796943-3f3ea7c7-e35c-4848-90ca-b17609012c9c.mp4

Copy and Pasting Without Using ImageUtilities Plugin:
https://user-images.githubusercontent.com/74092353/195797198-11acdc3c-2cbf-4690-bea4-57d4e12589a4.mp4

Using the standard build of Discord.

**[Disclaimer]**
I have already copied a link / image **without the use** of the ImageUtilities plugin just to reiterate.

**Comment by NextdoorPsycho** [comment]
https://github.com/mwittrien/BetterDiscordAddons/issues/1806

**Comment by mwittrien** [comment]
Yeah known, will be fixed today
