### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps - timestamps

### ISSUE THREAD

**Issue by cedrixm** [mwittrien/BetterDiscordAddons#1864]
Would be nice to have the option to display timestamps Unix format in the list of formats.

Thanks :)

**Comment by mwittrien** [comment]
Example?

**Comment by cedrixm** [comment]
1665751543
Unix timestamp in seconds (from 1/1/70) that we could copy into the Discord <t:xxx> tag

**Comment by mwittrien** [comment]
<t:XXX> only gets rendered in messages and bios and not in timestamps

**Comment by cedrixm** [comment]
I know, not asking to put the <t > tag, just asking to allow the output of the unix timestamp number, as one of the output formats of the plugin, like this we could copy this value, and put it ourselves in our <t:> tags

**Comment by mwittrien** [comment]
And what would be the point?

<t:time> doesnt magically turn into the interactive date element

**Comment by cedrixm** [comment]
I sometime need to use a date a message was sent, and use it in other messages, but using users local time, so I need to use the <t:xxx> format which require the Unix timestamp. 
As the plugin allows formatting in various formats, would be convenient to allow to use this format too, and would prevent us to have to use an external website to convert time into Unix timestamp for this use.
