### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by pronoob742** [mwittrien/BetterDiscordAddons#1870]
**Describe the bug**
My Discord is crashing 

**To Reproduce**
When i open my discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/67657872/195873979-e84ff175-571e-4d8f-8c28-5ea61dc0146c.png)
![image](https://user-images.githubusercontent.com/67657872/195874005-e1c3a939-6cbf-4360-854f-cad6df2639fb.png)
![image](https://user-images.githubusercontent.com/67657872/195874124-175c28de-30c0-411f-817a-5938ed656043.png)

**Which build of Discord are you using.**
stable,

BDFDB 2.7.7v

**Comment by mwittrien** [comment]
Nothing in that screenshot points at BDFDB

**Comment by Vad1mCSO2** [comment]
try reinstall betterdiscord to v1.8.0
