### ISSUE TITLE
[BUG] - PLUGIN/ImageUtilities

### ISSUE THREAD

**Issue by MIKSKY** [mwittrien/BetterDiscordAddons#1872]
"Search for an image with" does not work

**Screenshots**

![image](https://user-images.githubusercontent.com/49742588/195892736-e76a8c24-f463-4d96-bb32-c4a0c032b0da.png)

**Discord Build (canary):**

**Comment by mwittrien** [comment]
Make sure BDFDB is updated and delete 0BDFDB.data.json and reload discord
