### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by DerKen16** [mwittrien/BetterDiscordAddons#1874]
I have latest version of the BD + library + the plugin itself but it doesn't show the button anymore like before even if I don't use a theme

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload

**Comment by Ryonez** [comment]
This instruction broke it for me:
![image](https://user-images.githubusercontent.com/16157130/198748725-37196097-9e7a-4d29-89e6-efe0323233ae.png)

**Comment by Ryonez** [comment]
Yeah there's something wrong with the downloader function. Got it working again by manually downloading the file from here: https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.data.json
