### ISSUE TITLE
[BUG] - ImageUtilities | Saves images as corrupt files

### ISSUE THREAD

**Issue by Aaeeschylus** [mwittrien/BetterDiscordAddons#1876]
**Describe the bug**
Whenever saving an image with either "Save Image As" or in one of the preset locations from settings, the images are saved incorrectly and cannot be opened by anything.

**To Reproduce**
Save an image. Try to open it in any photoviewer or even photo editing software.

**Expected behavior**
Saved images should be usable for anything an image normally is used for (opening, editing, etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/7753205/195964327-12fab1c7-c317-42e4-8e3d-13705dbc1680.png)
![image](https://user-images.githubusercontent.com/7753205/195964343-baf3a5d2-658a-4be8-ac4b-cfd2bc60ae93.png)
(All images in the red box at the bottom are saved by the plugin and also do not work)
![image](https://user-images.githubusercontent.com/7753205/195964357-15c2b0f6-473f-4908-871b-e478d6d07bbc.png)
![image](https://user-images.githubusercontent.com/7753205/195964368-af506aef-fcab-4f5d-89a0-e26274e2622b.png)
Paint and photoshop cant open it either.

**Discord Build (stable, ptb or canary):**
Stable 152396

**Additional context**
All started since every plugin broke (as expected)

**Comment by mwittrien** [comment]
Has already been fixed in the newest Version
