### ISSUE TITLE
[Not Loading] - PluginRepo

### ISSUE THREAD

**Issue by khaledmoayad** [mwittrien/BetterDiscordAddons#1879]
**Describe the bug**
PluginRepo does not load any plugins unless i use a vpn

**To Reproduce**
Try to access the plugin without vpn

**Expected behavior**
i expect to see plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/94354651/195980683-748444f2-618f-480c-a9a7-9c9d44b36532.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
not really

**Comment by mwittrien** [comment]
Then thats an issue with your internet
