### ISSUE TITLE
[BUG] - CopyRawMessage - The Plug is isn't working

### ISSUE THREAD

**Issue by HlexNC** [mwittrien/BetterDiscordAddons#1882]
**Bug Discription**
Each time I try to use the Copy Raw Text. nothing happens

**Screenshots**
<img src="https://user-images.githubusercontent.com/66517969/195982018-98a35e88-5cf6-4806-8b09-5eda1ddae7db.png" width="500">
<img src="https://user-images.githubusercontent.com/66517969/195982031-089f8aeb-4892-4424-a164-862ad521b1f8.png" width="500">

---

**Discord Build**
Stable 152449 (3856653)
Windows 10 64-Bit (10.0.22621)

**Comment by mwittrien** [comment]
Its not fixed yet #1806
