### ISSUE TITLE
[BUG] - ImageUtilities - Embedded images are still cutoff

### ISSUE THREAD

**Issue by Novarime** [mwittrien/BetterDiscordAddons#1883]
**Describe the bug**
#1871. GIFs and Embedded image in messages section are resized to original size but cutoff (normally uploaded images don't get cutoff). 

**To Reproduce**
Any embedded image from links/GIF in messages that are very wide.

**Expected behavior**
All images should not be cutoff

**Screenshots**
https://user-images.githubusercontent.com/21150997/195887984-d8c4f3ed-de88-47cd-9acd-82845224ddee.png
https://user-images.githubusercontent.com/21150997/195890603-cea44a90-d5ba-421e-beb6-e523ba1d7fbe.png

**Discord Build (stable, ptb or canary):**
Stable 152131 (6ed73b9)

**Additional context**
Reposted because the one of the problems is not fixed yet (I'm also sorry for combining 2 bugs in 1 post) but marked as duplicate.

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord

**Comment by Novarime** [comment]
Did not fix the problem unfortunately.
Tried reinstalling BetterDiscord too, removed all other plugins and removed all config.json files and redownloaded BDFDB and ImageUtilities to no avail.

**Comment by mwittrien** [comment]
Can you give an example image link where the issue occures

**Comment by Novarime** [comment]
https://twitter.com/wizardfes/status/1581039055696822272
https://www.pixiv.net/en/artworks/95265813
Seems like right now it's mainly links with container(?) like twitter or pixiv embeds. Not sure about other sites with similar embeds. 
GIF Links that are posted into messages is not cutoff anymore.
