### ISSUE TITLE
[BUG] - Server Details

### ISSUE THREAD

**Issue by yorik100** [mwittrien/BetterDiscordAddons#1884]
**Describe the bug**
Does not show people in voice chat, except if they're streaming

**To Reproduce**
Hover cursor on server

**Expected behavior**
Show every pictures of people in voice chat

**Screenshots**
![image](https://user-images.githubusercontent.com/16320315/195996009-75666a3d-0176-45d7-99c2-4231d4165e34.png)
There are people in voice chats that I can access, their icons don't show

**Discord Build (stable, ptb or canary):**
Latest normal Discord

**Additional context**
Before Discord Thanos slapped BetterDiscord plugins, it was showing every icons

**Comment by Ryonez** [comment]
I'm also having this issues, only members streaming are shown.

**Comment by Ryonez** [comment]
Looks good now, thank you!

**Comment by iDeparture** [comment]
there's no tool tip pop up for me when i hover shift enabled. anyone else having this issue?
