### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by kegvorn** [mwittrien/BetterDiscordAddons#1885]
Hi! 
Too bad, the translator doesn't work at all.

Thank you for your hard work.

Please, if you have time, make a translator 
![2022-10-15_190206](https://user-images.githubusercontent.com/98895367/195996562-5260dd2e-1811-44f9-ae06-2a92b856ab6c.jpg)
![2022-10-15_190225](https://user-images.githubusercontent.com/98895367/195996565-e3af3c8b-37b2-485d-b914-ec39f9bfb393.jpg)

**Comment by mwittrien** [comment]
Soon #1806
