### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by Ocraftyone** [mwittrien/BetterDiscordAddons#1886]
**Describe the bug**
Plugin fails to load

**To Reproduce**
Load the plugin

**Expected behavior**
Load the plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/24759591/196018673-a9c39834-330e-4bb5-b399-fd7fa7f32ef0.png)

**Discord Build (stable, ptb or canary):**
Stable BD 1.8.1

**Comment by mwittrien** [comment]
#1806
