### ISSUE TITLE
[BUG] - PLUGIN/Notification Sounds

### ISSUE THREAD

**Issue by MassiveDew** [mwittrien/BetterDiscordAddons#1887]
When you click on the save button, in the category "add new sound", nothing happens. The duration of the file is 3 seconds.

Discord Build stable.

![изображение_2022-10-16_140501243](https://user-images.githubusercontent.com/115924476/196029669-abd07170-ee87-4e20-8bf3-4a6d4c3c6232.png)

**Comment by mwittrien** [comment]
#1806
