### ISSUE TITLE
[BUG] - Translater

### ISSUE THREAD

**Issue by ninco90** [mwittrien/BetterDiscordAddons#1888]
**Describe the bug**
For some reason the translation plugin compiles but the buttons to make it work are not shown. 

I practically can't use this amazing feature.

**To Reproduce**
That is, the translate icon does not appear in the writing area even though it is enabled in the configuration.

The translation option also does not appear in the context menu when you right click on a message.

All this stopped working with the update that Discord changed everything and all the plugins stopped working. I have also manually downloaded the latest version of the plugin and with Better Discord updated and fixed and I still have the same problem.

Is there something wrong or am I doing something wrong?

**Screenshots**
https://gyazo.com/6ee2166acd2b3c7833dfd53dd5db92c1
https://gyazo.com/46caa1b97ebd032b83f366ffa8a44580
https://gyazo.com/f947c419f917172a0649b22be90e95c2

**Discord Build (stable, ptb or canary):**
Stable 152449 (3856653)
BetterDiscord 1.8.0
Translate 2.4.1

**Comment by mwittrien** [comment]
#1806
