### ISSUE TITLE
DeepL Translation is stuck on French 

### ISSUE THREAD

**Issue by Foolspring** [mwittrien/BetterDiscordAddons#189]
Currently I am having an issue with DeepL translation on your plugin. When I am using the DeepL translator for French the first time, my messages translate to French perfectly fine. However, once I switch to German or any other language in the DeepL dropdown menu, it keeps translating my messages to French, despite having a different language selected.

I do not experience this issue with Google Translate. 

![image](https://user-images.githubusercontent.com/49375895/55689379-7d7e9880-5938-11e9-98bd-fe4d35dda480.png)

**Comment by mwittrien** [comment]
DeepL will not be removed from GTO, due to internal changes in discord webviews no longer work and those DeepL can't be run to allow it to be used as a translator.
