### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by josephworks** [mwittrien/BetterDiscordAddons#1891]
**Describe the bug**
![image](https://user-images.githubusercontent.com/18745823/196098241-8d61ca3d-d533-48cc-b8b3-677cf91a78e2.png)

**To Reproduce**
Install EditServers v2.3.8

**Expected behavior**
No console errors

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
#1806
