### ISSUE TITLE
[BUG] - PluginRepo

### ISSUE THREAD

**Issue by EPLOGx** [mwittrien/BetterDiscordAddons#1892]
**Describe the bug**
PluginRepo doesn't load.

**Screenshots**
https://prnt.sc/PbVGBy9KmBL7
https://prnt.sc/ZTRrQOTPm6_k

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
No errors except a timeout message, but don't know if this comes from PluginRepo.

**Comment by mwittrien** [comment]
Most likely an issue with your internet connection, try a vpn
