### ISSUE TITLE
[BUG] - EDIT SERVERS PLUGIN - SERVER BANNER DOES NOT SHOW

### ISSUE THREAD

**Issue by zluckytraveler** [mwittrien/BetterDiscordAddons#1894]
**Describe the bug**
When Edit servers plugin is enabled, the server banner doe snot work and is shown with a blank image.

**To Reproduce**
Enabling the plugin

**Expected behavior**
Server banners to show and work.

**Discord Build (stable, ptb or canary):**
Stable

**Screenshots**
<img width="244" alt="Screen Shot 2022-10-17 at 1 42 55 PM" src="https://user-images.githubusercontent.com/97180817/196279781-579f011a-6731-4fb8-8acb-2711ff98ff5e.png">
<img width="246" alt="Screen Shot 2022-10-17 at 1 43 26 PM" src="https://user-images.githubusercontent.com/97180817/196279784-9b59c65e-8b68-4d42-8a76-0fad8ec2a3c2.png">

**Comment by mwittrien** [comment]
#1806
