### ISSUE TITLE
[BUG] - Bdfdb

### ISSUE THREAD

**Issue by thiaguinho4** [mwittrien/BetterDiscordAddons#1895]
**Describe the bug**
Bdfdb has an unexpected error when clicking on the settings

**To Reproduce**
When u click on the settings

**Expected behavior**
There Shouldn't Be an Error Clicking on the Settings.

**Screenshots**
![1](https://user-images.githubusercontent.com/101910294/196284136-536c6478-f0b1-476d-99d6-bf7b4e7cdd19.png)
![1](https://user-images.githubusercontent.com/101910294/196288243-914f54e5-ec02-4b0a-8de7-e749fafefd57.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by thiaguinho4** [comment]
apparently the library is working perfectly, but it gives errors in the plugin settings

**Comment by mwittrien** [comment]
Thats an issue with BD
