### ISSUE TITLE
[BUG] - RemoveBlockedUsers - No Join/Leave Sounds in Voice Calls

### ISSUE THREAD

**Issue by Sonador** [mwittrien/BetterDiscordAddons#1896]
**Describe the bug**
While the RemoveBlockedUsers Plugin is running, and while you are connected to a voice call, Discord will not play notification sounds for users joining or leaving the call, regardless of if the user is blocked or not.

**To Reproduce**
1. Download and enable BDFDB 2.8.2 and RemoveBlockedUsers 1.5.4
2. Connect to a voice channel.
3. Have another user join and/or leave your channel.

**Expected behavior**
When a user connects or disconnects from a voice channel you are in, Discord will play a notification sound to inform you this has occurred.

**Screenshots**
https://www.dropbox.com/s/lzhelby3yp8xset/2022-10-17%2023-57-08.mp4?dl=0

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by MistressAshai** [comment]
Yeah, this was fixed back in June but it appears to have resurfaced. #1632
