### ISSUE TITLE
[no bug but I keep trying to find out how to use it to censered messages and block it like i keep tapping messages to try to find out to do it] - Chatfilter/

### ISSUE THREAD

**Issue by Mosquitomaxx** [mwittrien/BetterDiscordAddons#1905]
**Describe the bug**
no bug but I keep trying to find out how to use it to censered messages and block it like i keep tapping messages to try to find out to do it
**To Reproduce**
when i got it
**Screenshots**
cant add screenshots
**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
normal
**Additional context**
i cant find out how to block or censered messages

**Comment by mwittrien** [comment]
#1806
