### ISSUE TITLE
[BUG] - BDFDB 

### ISSUE THREAD

**Issue by Nirgranth** [mwittrien/BetterDiscordAddons#1906]
**Describe the bug**
Crashes on plugin download/update from plugin repo

**Screenshots**
![image](https://user-images.githubusercontent.com/48947296/196636253-fbc3b6e4-447c-4c63-ad25-7a88bc08121c.png)

**Comment by mwittrien** [comment]
it clearly shows in the screenshot that the issue is 0PluginLibrary and not BDFDB
