### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by FomalhautBravo** [mwittrien/BetterDiscordAddons#1907]
**Describe the bug**
It's partially not working, including all provided translators except DeepL.

**To Reproduce**
When you try to translate existing texts.

**Expected behavior**
Texts and messages in the typebox can be translated

**Screenshots**
![image](https://user-images.githubusercontent.com/116103073/196684103-3655cc9a-8c56-4238-9ea3-ec7475aa588c.png)
![image](https://user-images.githubusercontent.com/116103073/196683645-ecf7eaaa-de78-4c82-88f2-41962f581095.png)
![image](https://user-images.githubusercontent.com/116103073/196684549-0e1776f8-285f-4002-b498-cc1190d4e744.png)
![image](https://user-images.githubusercontent.com/116103073/196684744-cff16982-b372-4c94-8868-b4e18fea22a4.png)
![image](https://user-images.githubusercontent.com/116103073/196684978-c52fd5db-accc-428f-ab1a-afbf824c8ad8.png)
![image](https://user-images.githubusercontent.com/116103073/196685280-d25d1509-97d1-428d-8048-b38e30d27589.png)

**Discord Build (stable, ptb or canary):**
Stable 153013 (501b323)

**Additional context**
The issues are listed above:
Google translation will ping up a dialog then report failure;
*DeepL is working as I just tested while typing this;
Itranslate said the server is probably offline;
Yandex said it has reached this month's limit, this may not be the plugin's issue;
Papago said the server is probably offline, but also mentioned something about API key is out of date;
Baidu reported about Unauthorized user.

**Comment by mwittrien** [comment]
Yandex has nearly always reached its limit since its a monthly limit shared between all plugins users

But same as the issue with the other plugin this is 100% an issue with you using a VPN

**Comment by YunekoChanZ** [comment]
i see in discord you said you fixed the translator but it does not work, does not give any options to translate, using stable discord, probably just an issue with BDFDB 
![Screenshot 2022-10-19 203941](https://user-images.githubusercontent.com/56841082/196830430-46a76d9e-c4e9-465a-8f7d-bb00ca16efd2.png)
