### ISSUE TITLE
[BUG] - ImageUtilities/ Cannot Copy Spoilered Images

### ISSUE THREAD

**Issue by Rovoska** [mwittrien/BetterDiscordAddons#1908]
**Describe the bug**
When clicking on an image to open gallery view using the plugin, clicking "Copy Image" on spoilered images does not work as intended. The plugin posts a toast saying the image has been copied, but no data entered the clipboard.

**To Reproduce**
Click on a spoilered image to open the gallaery view, then click on "Copy Image". 

**Expected behavior**

The image should be copied as normal when "Copy Image" is clicked.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**

Stable 152727 (10e8836)

**Additional context**

N/A

**Comment by mwittrien** [comment]
Take a video pls

Just tested and works fine for me
