### ISSUE TITLE
[BUG] - PLUGIN REPO

### ISSUE THREAD

**Issue by carter370** [mwittrien/BetterDiscordAddons#1909]
**Describe the bug**
Cannot scroll in plugin repo.

**To Reproduce**
Go to plugin repo tab and attempt to scroll.

**Expected behavior**
For scrolling to work and to see the other plugins.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable 152532 (a118a24) Host 1.0.9006 Windows 10 64-Bit (10.0.19043)

**Additional context**
N/A

**Comment by mwittrien** [comment]
Try disabling your theme

**Comment by carter370** [comment]
Doesn't fix it.

**Comment by mwittrien** [comment]
Works fine for me and everyone else

**Comment by carter370** [comment]
bru
