### ISSUE TITLE
PluginRepo v2.3.9 never loads a list of plugins

### ISSUE THREAD

**Issue by Ketris** [mwittrien/BetterDiscordAddons#1910]
**Describe the bug**
PluginRepo v2.3.9 never loads.

**To Reproduce**
Every time Plugin Repo is enabled, the list of plugins never loads. (I've left it for hours)

**Expected behavior**
It should eventually show a list of plugins. It worked prior to the Discord rewrite and loading the list would take a few seconds at most.

**Screenshots**
![image](https://user-images.githubusercontent.com/726660/196850885-10968731-39b4-43f1-ad3d-e8024f61a0a9.png)

**Discord Build (stable, ptb or canary):**
Stable 153271

**Additional context**
I tried disabling all other plugins/themes except BDFDB v2.8.3 and PluginRepo v2.3.9
I've reinstalled Discord, BD, and the plugin but nothing has changed.

**Comment by Ketris** [comment]
I'm also seeing the exact same problem in ThemeRepo v2.4.1

**Comment by Ketris** [comment]
There's no VPN involved and, of the hundreds of things that use the internet on my machine, this is the only one to have problems. It is **absolutely not** an internet issue.

**Comment by mwittrien** [comment]
Well it works for everyone else, nothing i can troubleshoot
