### ISSUE TITLE
[BUG] - NotificationSound has no sound

### ISSUE THREAD

**Issue by benwong01f611** [mwittrien/BetterDiscordAddons#1912]
**Describe the bug**
1. No sound when NotificationSound is enabled.
2. Debug log is spammed by ```[CONSOLE:ERROR] [NotificationSounds] (v3.7.3) Fatal Error: "before" callback of dispatch in e TypeError: Cannot read property 'isBlocked' of null```
3. Sound configuration has no options.

**To Reproduce**
Got pinged or has new messages

**Expected behavior**
A sound should be played

**Screenshots**
![image](https://user-images.githubusercontent.com/23426279/197084366-d6d81156-aad9-446a-bfb0-0e2640e2fb8c.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
No additional context.

**Comment by mwittrien** [comment]
#1806
