### ISSUE TITLE
[BUG] - PinDMs still did not work

### ISSUE THREAD

**Issue by aunight** [mwittrien/BetterDiscordAddons#1913]
can not normal use this plugin,it feel like just broken

**Comment by cmd430** [comment]
confirming PinDMs is still quite broken, clicking on a DM thats not pinned doesn't work and completely breaks the DM list by removing multiple DMs at a time, if you keep clicking DMs eventually you are left with a broken blank list that can still scroll as if the DMs are there

**Comment by HueZuX** [comment]
Exactly, just updated the PinDMs plugin and it does not work. When clicking in my friend list on persons, the whole friend list is bbroken and I get a blank list. It's super weird.

**Comment by tholley7** [comment]
Can confirm, this is not working. I posted my own issue (linked right above this comment) explaining in detail.

**Comment by israaazzab1** [comment]
hello ,
can i ask about plugin show hidden channel 
Will this plugin work again?

**Comment by dan201455** [comment]
Just to note, is not ith clicking on a DM. When I go to click off onto a server, it sometimes glitches out my friendslist as I come off.

**Comment by Soulivan71** [comment]
Im still having issue

**Comment by blazebrem** [comment]
Want to add one to this that I also have an issue where most of the time, I cannot see the people within my custom folders/categories. Trying to close or expand them, just causes people to disappear and sometimes appear in the normal DM list. 

Oh, and my server list pins, aren't showing up either.

**Comment by DexLuther** [comment]
Wrote this https://github.com/mwittrien/BetterDiscordAddons/issues/1927 before seeing this. Closed the other one since everything is already being addressed here.

**Comment by JimMcBubbles** [comment]
Seems to have improved for me, but categories other than Group DMs wont expand. I'm able to pin contacts to channel list, but not to server list.

**Comment by HirschBerge** [comment]
As of 6:00 Eastern, issue is *almost* resolve for me. DMs don't disappear, but trying to rearrange categories either cause a category to temporarily disappear or not move. Cannot seem to get a category to drag to the top position. It just ends up directly below if it does move.
Adding DMs to categories have a short delay, often only updating after clicking somewhere.

**Comment by Irastris** [comment]
Just to quickly add on to the current status of this plugin, it would appear the unpinned DMs section can no longer be contracted as I am almost certain could be done before BD broke, please correct me if I'm wrong.

**Comment by cmd430** [comment]
> it would appear the unpinned DMs section can no longer be contracted as I am almost certain could be done before BD broke

iirc you never could collapse the unpinned DM section

**Comment by JimMcBubbles** [comment]
> 

i can second that

**Comment by LewShakey** [comment]
Any dm's that were assorted into pinned categories don't display when clicked on currently. If they were collapsed on load up, they're permanently collapsed, even if the arrow indicating it's meant to be revealed is shown

**Comment by HirschBerge** [comment]
> Any dm's that were assorted into pinned categories don't display when clicked on currently. If they were collapsed on load up, they're permanently collapsed, even if the arrow indicating it's meant to be revealed is shown

Can confirm

> Just to quickly add on to the current status of this plugin, it would appear the unpinned DMs section can no longer be contracted as I am almost certain could be done before BD broke, please correct me if I'm wrong.

Never was a feature in the first place.

**Comment by Irastris** [comment]
> Never was a feature in the first place.

I'm sure you're right, I'm likely mistaking another custom category I had made for unimportant DMs that I didn't want to quite outright remove and was collapsing that. Perhaps it would be a good feature addition then?

**Comment by Soulivan71** [comment]
Pin server list inc ?

**Comment by DexLuther** [comment]
> Pin server list inc ?

Nope. Pin to server list does not work.
