### ISSUE TITLE
[BUG] - PLUGIN/NotificationSounds

### ISSUE THREAD

**Issue by FrutLupes** [mwittrien/BetterDiscordAddons#1914]
The same issue is persisting even after the most recent update and on the discord it says it should be working just fine.
I try to add a new sound and it just doesn't seem to add it anywhere, I've tried with multiple different sounds and still no luck.
It doesn't give me any kind of error either it just does nothing when I press the Save button.

Anytime I try to add a new sound.

I expected the sound I wanted to be added to my Notifications section.

I'm currently using the most recent build of Discord, BetterDiscord, and all the plugins.

**Comment by Rude1ee** [comment]
Same thing as the OP. Everything else works except the custom sound additions.

**Comment by JinxieSkye** [comment]
I have a similar issue except nothing at all is working for me. I don't have any of my old sounds. I don't have any sounds at all actually. Not even normal discord join and leaving sounds D:
