### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by TheTaxPerson** [mwittrien/BetterDiscordAddons#1917]
**Describe the bug**
Every contact that isnt pinned disappears from Direct Messages

**To Reproduce**
Do anything that updates Direct Messages

**Expected behavior**
My contacts there dont change

**Screenshots**
Attached Bellow

**Discord Build (stable, ptb or canary):**
Stable 153481 (c00173e)

https://user-images.githubusercontent.com/46745609/197208389-517ac8b1-4f81-472b-ad39-1135841121b3.mp4

**Comment by mwittrien** [comment]
#1913
