### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Keler69** [mwittrien/BetterDiscordAddons#1919]
**Describe the bug**
Opening/closing or just basically interacting with the recent messages module on the left side basically slowly removes/hides the chats. even the ones not pinned or have no connection to the plugin at all.

this module below. you prob already know what this is. i wont show the rest bc of my friend's personal stuff.
![image](https://user-images.githubusercontent.com/110538492/197216642-0c049e7c-9aae-45e6-862d-eb3688230cc7.png)

**To Reproduce**
Clicking this module or opening/closing the pinned dms category slowly removes the friends below ( you have to click it everytime).

**Expected behavior**
Just the pin dms category working properly yk. whenever i click it, i expect for it to open/close the pinned dms category.

**Screenshots**
Screenshot above for the module thing im talking about.

**Discord Build (stable, ptb or canary):**
BetterDiscord v1.8.2
BDFDB 2.8.5
PinDMs 1.9.5

**Additional context**
Restarting discord fixes it like the hidden or removed chats are back.

**Comment by mwittrien** [comment]
#1913
