### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities: support ascii2d

### ISSUE THREAD

**Issue by gcobc12632** [mwittrien/BetterDiscordAddons#1920]
**Describe the solution you'd like**
ascii2d is a image search web.
it can search in pixiv and twitter.
sometimes better than saucenao.
can you support it?

**Describe alternatives you've considered**
add this code in line 253:
`ascii2d:	{value: true,	name: "ascii2d",	url: "https://ascii2d.net/search/url/" + imgUrlReplaceString}`

**Comment by mwittrien** [comment]
ascii2d has pornographic images on their sidebar, and hence ain't allow into the plugin
