### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Enrico9431** [mwittrien/BetterDiscordAddons#1922]
**Describe the bug**
When PinDMs is enabled and I try to open any dm that I haven't pinned they'll just disappear temporarily until I reload discord.

**To Reproduce**
Enable the plugin and try to open any dm that is not pinned

**Expected behavior**
For the non-pinned dms to no disappear when clicked on and actually open them

**Screenshots**
![PinDMs Bug](https://user-images.githubusercontent.com/85672311/197257449-2ba1a92e-8a64-4164-9860-5af926447aca.gif)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by Soulivan71** [comment]
Im having my first categorie and then the other are not display for me
![image](https://user-images.githubusercontent.com/36502190/197261472-5dde7fb4-125c-4e00-a0fc-b5622ee459ae.png)

**Comment by Brawlboxgaming** [comment]
Yeah this appears to be quite a major issue considering my friends list just ends up like this: 
![image](https://user-images.githubusercontent.com/71042104/197261566-2ad44364-da2e-4b5d-bdd1-ec2fe427a5ce.png)

**Comment by mwittrien** [comment]
#1813
