### ISSUE TITLE
Writing this here because there is seemingly nowhere else

### ISSUE THREAD

**Issue by RainOfPain125** [mwittrien/BetterDiscordAddons#1923]
I wouldn't write here if it wasnt messed up but clearly it is

1. nobody can write messages in any channel in your discord (despite saying that you are back to revive your plugins)
2. the link to DB's github issues page on your website is invalid, I had to go through hoops to find this
3. information channel says we are allowed to DM you, but your DMs are closed.

so there is effectively zero ways to contact and report bugs. please fix this.

**Comment by mwittrien** [comment]
This is the place to report bugs

My server is in lockdown until my stuff is fixed
