### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by drakosoldier298** [mwittrien/BetterDiscordAddons#1925]
**Describe the bug**
When collapsing a categiory it removes names from your dm list outside the category as well.
edit, while writing it became impossible to uncollapse the category, it seems to be a 30% ish chance for this part to occur
**To Reproduce**
make a category, add 2 or more people, collapse it, uncollapse it, collapse again, watch as people start vanishing  from the dm list..

**Expected behavior**
The dm list to move not be over written.
**Screenshots**
![image](https://user-images.githubusercontent.com/30358222/197272480-55e85731-0062-4c35-96e8-b4a0420171c5.png)
after collapsing 
![image](https://user-images.githubusercontent.com/30358222/197272528-9acd6b85-3971-4bfa-a3ce-ba7f17f78a86.png)
 well  new thing it wont uncollapse now.
**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by DexLuther** [comment]
Left-clicking to switch DMs or right-clicking to open the context menu appear to have the same result in the DM being clicked on and the ones above and below appear to close, which **renders the DM List practically unusable unless PinDM is disabled**.

Opening Discord Settings or switching to a server and then returning to the DM list results in the missing DMs reappearing, so the issue only appears to be temporary and purely a visual bug.

As a result, **Pin to Sever List** also no longer works: https://github.com/mwittrien/BetterDiscordAddons/issues/1927

**Comment by mwittrien** [comment]
#1913
