### ISSUE TITLE
[BUG] - StaffTag v1.5.7

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#1926]
**Describe the bug**
when staff tag is enabled and you try to click on anyones name, the user pop out hangs forever.

**To Reproduce**
have staff tag enabled & click on any user..

**Expected behavior**
the pop out to not hang & show properly.

**Screenshots**
<img width="256" alt="Screen Shot 2022-10-22 at 6 43 18 am" src="https://user-images.githubusercontent.com/2242880/197278628-042baa89-c7ef-4c79-8d1c-cdb9825390d8.png">
<img width="166" alt="Screen Shot 2022-10-22 at 6 43 28 am" src="https://user-images.githubusercontent.com/2242880/197278639-7b91aaad-d030-47da-8377-8cd6b9dd9dd8.png">

**Discord Build (stable, ptb or canary):**
Stable, PTB, Canary (happens on them all)

**Additional context**
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/9842075/debug.log)
[discord.com-1666381249766.log](https://github.com/mwittrien/BetterDiscordAddons/files/9842076/discord.com-1666381249766.log)
[Video Demo](https://replay.dropbox.com/share/CGlEln2RCqdkb76k)

**Comment by CptDinosaur** [comment]
Same issue here
