### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Chris4190** [mwittrien/BetterDiscordAddons#1928]
**Describe the bug**
Servers/ DMs have to be clicked twice after startup of the app

**To Reproduce**
once after startup

**Expected behavior**
server/dm should open immediatly

**Screenshots**
![bugreport](https://user-images.githubusercontent.com/116430374/197331128-daaf9e72-0490-4f50-b6b8-84a804b7eb63.gif)

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Sadly cant be avoided
