### ISSUE TITLE
Issue with Read All Notifications plugin

### ISSUE THREAD

**Issue by tryoutuser** [mwittrien/BetterDiscordAddons#193]
Recently new updated interface for discord caused the plugin did not work.
I saw there was a new plugin update at the top and i clicked, but the effect still nothing.
I'm using BBD and have zerebos plugin.

![bandicam20190424170027422](https://user-images.githubusercontent.com/35561383/56651761-fc532f80-66b3-11e9-954a-d342fac87d4d.gif)

**Comment by JourneyOver** [comment]
Glad to see it's not only me with this issue, hope to see an update for this plugin soon.

**Comment by tryoutuser** [comment]
I've got it updated, and now it works normally. Thank you @mwittrien
