### ISSUE TITLE
[IMPROVEMENT] Support for Local Songs - Spotify Controls

### ISSUE THREAD

**Issue by uSkizzik** [mwittrien/BetterDiscordAddons#1931]
Currently, the plugin doesn't display information such as creator or album cover of local songs even if Spotify does.  
I'm not aware of how you get the song info which you display but I can tell you local songs can have these properties in the metadata of the MP3s.

**Comment by mwittrien** [comment]
If discords spotify integration doesnt support it neither will or can the plugin
