### ISSUE TITLE
[BUG] - SpotifyControls /Cant enabel Plugin

### ISSUE THREAD

**Issue by DieInkompetens** [mwittrien/BetterDiscordAddons#1932]
**Describe the bug**
The activate button is greyed out. 

**To Reproduce**
always

**Screenshots**
![Bild_2022-10-22_220359155](https://user-images.githubusercontent.com/116461928/197360299-2251321f-3efb-4341-a15c-8fc4b9ed2c4f.png)

**Discord Build (stable, ptb or canary):**
BetterDiscord v1.8.2; SpotifyControls v1.2.9

**Comment by mwittrien** [comment]
Redownload it
