### ISSUE TITLE
BDFDB making discord lag when the plugin is loaded

### ISSUE THREAD

**Issue by haxerman123** [mwittrien/BetterDiscordAddons#1933]
BDFDB makes discord lag when the plugin is loaded (also happens on discord startup) 
I also reinstalled discord. uninstalled the electron app and deleted the discord folder in roaming. Also uninstalled openasar just to be sure and the problem still persists. 
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/9845310/debug.log)

**Comment by mwittrien** [comment]
Plugins are bound to slow down discord
