### ISSUE TITLE
Plugin Repo and theme repo not loading

### ISSUE THREAD

**Issue by haxerman123** [mwittrien/BetterDiscordAddons#1934]
For some reason Theme and Plugin repo are stuck at a particular number. Plugin repo at 194 and theme repo and 108. Couldn't find anything relating to those issues in the debug log. NOTE: This also happened  before discord rolled the switch from babel to swc and a year before it.

**Comment by CptDinosaur** [comment]
Similar issue for me

For me though its VPN related, turning off my VPN makes them load

**Comment by mwittrien** [comment]
Network and VPN issues cant be influenced by plugins
