### ISSUE TITLE
[BUG] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by DarkBroShow** [mwittrien/BetterDiscordAddons#1935]
Image servers are broken
Server names missing
Discord Build (stable, ptb or canary): Stable 153655 (4461450)

Screenshot
![image](https://user-images.githubusercontent.com/91475204/197363913-bcb95e21-9a02-4289-82fb-2f846ea93612.png)

P.S. I did not find the plugin in the list for fixing, so I am writing a bug report

**Comment by mwittrien** [comment]
#1806
