### ISSUE TITLE
[BUG] - Notification sounds

### ISSUE THREAD

**Issue by NarikoNep** [mwittrien/BetterDiscordAddons#1937]
**Describe the bug**
The Plugin refuses to work, normal notification sounds aren't playing at all, and I get an error while trying to look at the settings for the plugin

**To Reproduce**
Start plugin, and try to look at settings.

**Expected behavior**
The sounds to be working correctly and be able to change the settings

**Screenshots**
![image](https://user-images.githubusercontent.com/97272732/197406271-9241a95b-ca83-472d-9150-d9d22dc4699f.png)

**Discord Build (stable, ptb or canary):**
Discord Stable 153655 (4461450)

**Additional context**
I use OpenAsar but it worked with before this morning, and I removed one the files I used as a sound if that would do anything.

**Comment by mwittrien** [comment]
Redownload BDFDB plugin
