### ISSUE TITLE
[BUG] - Personal Pins 2.1.2

### ISSUE THREAD

**Issue by Venaf** [mwittrien/BetterDiscordAddons#1940]
**Describe the bug**
"Notes" icon is missing from individual DM windows

**To Reproduce**
Happens all the time.  Does NOT happen in group DMs, or server channels.

**Expected behavior**
"Notes" window is normally accessible in both DMs and servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/2046512/197501183-bcb4f682-3bd5-407c-bbab-aeebd840bd3b.png)
![image](https://user-images.githubusercontent.com/2046512/197501453-36021376-09bd-4d0f-8721-821d3d351565.png)
![image](https://user-images.githubusercontent.com/2046512/197501616-65468110-97b9-44db-8068-bdaea1271557.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I can still add message notes regardless, and get to them by going to a server, it's just an inconvenience.  Thanks for getting this updated! I use it heavily.

**Comment by unknownoddity** [comment]
I'd like to add to this with a similar issue. The notes icon sometimes appears when loading discord and sometimes doesn't. However when it does load, discord crashes whenever I click on it. BDFDB is the latest version, same as personal pins.
