### ISSUE TITLE
[BUG] - PersonalPins

### ISSUE THREAD

**Issue by unknownoddity** [mwittrien/BetterDiscordAddons#1941]
**Describe the bug**
PersonalPins does not load with discord startup most of the time, and if it does clicking the icon causes discord to crash.
Also, clicking on the personalpins settings in the plugins section on discord does not work and gives the text 'Could not initiate BDFDB Library Plugin! Can not create Settings Panel!

**To Reproduce**
Whenever you load discord/click the notes icon

**Expected behavior**
Loading discord would load the plugins correctly and clicking on the icon would open the notes page.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
