### ISSUE TITLE
[BUG] - PinDM's

### ISSUE THREAD

**Issue by LewShakey** [mwittrien/BetterDiscordAddons#1942]
When opening a pinned category, the pinned dm's within that category do not show. Alongside that, unpinned dm's disappear

*Edit* Alternatively clicking the friends tab seems to have unintended effects - Dm's disappear when they shouldn't making it quite inconvenient

Click a pinned category that is closed to reproduce

The category should open, leaving unpinned dm's alone whilst also revealing those within the pinned dm category

Using the most recent version of Discord on Windows

**Comment by dan201455** [comment]
#1913
