### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by Jpdelta** [mwittrien/BetterDiscordAddons#1944]
**Describe the bug**
Despite downloading the additional material required, restarting, and following many other suggestions, I simply cannot get this plugin to do anything. No matter where I try it does nothing.

**To Reproduce**
Ever since I downloaded it.

**Expected behavior**
I expected it to work at all.

**Screenshots**
NA

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord
