### ISSUE TITLE
Still no PersonalPins icon

### ISSUE THREAD

**Issue by justanediblefriend** [mwittrien/BetterDiscordAddons#1947]
**Describe the bug:**
The bugs for the Notes icon have been closed as solved, but this bug still exists for me. The icon has never shown up for me whatever the number of reloads.

**To reproduce:**
Load BetterDiscord with PersonalPins 2.1.3 and BDFDB 2.8.9.

**Expected behavior:**
The Notes icon shows up so you can see your personal pins.

**Discord Build (stable, ptb or canary):**
ptb

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload Discord
