### ISSUE TITLE
[BUG] - SplitLargeMessages

### ISSUE THREAD

**Issue by ecodz** [mwittrien/BetterDiscordAddons#1950]
**Describe the bug**
If you send a message (of any length) the plugin will send it twice 

**To Reproduce**
Write a message in any channel

**Expected behavior**
if the message is over the maximum length, it splits the message in multiple parts

**Screenshots**
![image](https://user-images.githubusercontent.com/106698407/197822476-a4a41729-f8d0-4abe-a8cb-a3eb210695a1.png)

**Discord Build (stable, ptb or canary):**
stable

**Comment by icen1** [comment]
Same issue. Got it right after updating to the newer version

**Comment by mwittrien** [comment]
#1951
