### ISSUE TITLE
[BUG] - Translator v2.4.2/Split Larger Messages

### ISSUE THREAD

**Issue by EntropicBlackhole** [mwittrien/BetterDiscordAddons#1951]
**Describe the bug**
Basically, after disabling and enabling plugins, I found out that it's Translator combined with SLM that's causing this problem, it sends your current message twice, this happens in both DMs and guilds

**To Reproduce**
It sends any message you write a second time, at first I thought it was Translator only but after disactivating SLM, it doesn't happen, when both Translator and Split Larger Messages are both on, this happens

**Expected behavior**
Basically just send a single message, I have no idea how both javascript files would interact with eachother in this way either through BDFDB or the channel's cache

**Screenshots**
![image1](https://user-images.githubusercontent.com/82614490/197832264-94cb6327-c612-4a87-aee3-30de4f9a1409.png)
![image2](https://user-images.githubusercontent.com/82614490/197832623-127bc5da-cd44-49e5-9587-8da35e33a64f.png)

**Discord Build (stable, ptb or canary):**
I'm using the stable build

**Comment by nhan000** [comment]
same here

**Comment by minhperry** [comment]
can confirm, even 1 character message can cause the bug

**Comment by Jugom** [comment]
Same here.
I didn't know about the translator, but it stopped happening after disabling SLM.
It duplicates not only in normal messages sent, but also in replies.

**Comment by DrakeFaewylde** [comment]
SLM Active | Translator Active = Double message

SLM Active | Translator Off = Single message

SLM Off | Translator Active = Double message

SLM Off | Translator Off = Single message

Based on my testing, the issue must be coming from Translator at this point, at least for me. Perhaps SLM was fixed recently?

Running stable build, if that helps at all.
