### ISSUE TITLE
[BUG] - SplitLargeMessages/ClearVision (Messages sending twice)

### ISSUE THREAD

**Issue by BenjiCS** [mwittrien/BetterDiscordAddons#1952]
**Describe the bug**
When I enable SplitLargeMessages it sends message twice

**To Reproduce**
When I enable SplitLargeMessages

**Expected behavior**
I only want to send one message

**Discord Build (stable, ptb or canary):**
latest build

**Comment by joker-119** [comment]
Also experiencing this, prior version worked fine, plugin updated and now all messages are sent twice when plugin is enabled

**Comment by iTemmy** [comment]
Also experiencing this with the update that just released today.

**Comment by mwittrien** [comment]
#1951
