### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by leonglo** [mwittrien/BetterDiscordAddons#1953]
**Describe the bug**
whenever I send a message, even if its lengh is not long, the plugin makes me send it twice

**To Reproduce**
happens whenever I send a message in any channel, any guild

https://user-images.githubusercontent.com/75845683/197877441-df6e1275-34aa-4354-a42d-07269c42caa8.mp4

**Discord Build (stable, ptb or canary):**
discord ptb

**Comment by mwittrien** [comment]
#1951
