### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Jahgoda** [mwittrien/BetterDiscordAddons#1954]
**Describe the bug**
Sends a duplicate of your message, does not translate any messages you send.

**To Reproduce**
Have the plugin enabled (ANY/EITHER settings set for the plugin such as "send original message"), text anyone.

**Expected behavior**
Supposed to send a translated message or not depending on if it is enabled for a specific channel.

**Screenshots**
[https://cdn.discordapp.com/attachments/720825621608923175/1034574386117754970/unknown.png](url)

**Discord Build (stable, ptb or canary):**
Stable 154186 (fccec91) Host 1.0.9007 Windows 10 64-Bit (10.0.22621)

**Additional context**
If anymore info is needed, contact me @ Jahgoda#5370 on Discord.

**Comment by mwittrien** [comment]
#1951
