### ISSUE TITLE
[BUG] - SplitLargeMessages v1.7.9

### ISSUE THREAD

**Issue by Thqrn** [mwittrien/BetterDiscordAddons#1955]
**Describe the bug**
The bug causes messages to be sent twice.

**To Reproduce**
Send a message.

**Expected behavior**
The message should send a single time.

**Screenshots**
[Streamable link.](https://streamable.com/l71atn)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Disabling the plugin fixed this issue, and the issue happened again upon re-enabling it.

**Comment by defaultkid99** [comment]
happens to me also

**Comment by nhan000** [comment]
duplicate of https://github.com/mwittrien/BetterDiscordAddons/issues/1951
