### ISSUE TITLE
[BUG] - Edit Users broken

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#1956]
**Describe the bug**
users are not edited also i cant edit them with the dropdown selection (its not showing himself) the only thing what works is the settings tab thats all

**To Reproduce**
right click a users to show is the edit buttun there or go to a users who you edited and check if they have another name

**Expected behavior**
that i see my edits and i can edit people with tight click -> drop drop down selection -> edit user 

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/197899784-aac15c01-c1f1-4e3a-9016-0c9e33260e76.png)
![image](https://user-images.githubusercontent.com/25110093/197899894-52b889e8-a1ba-4a1c-8353-9e3be2f369a4.png)
![image](https://user-images.githubusercontent.com/25110093/197899898-1b5f5eca-2a96-41f6-a966-dc570cd8c0cc.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/197899918-bb75cc4c-5053-496e-89bd-a83597860b0e.png)
same with stable version
![image](https://user-images.githubusercontent.com/25110093/197900419-d66e248a-5a63-4bc3-baf4-56dd981b79f9.png)

**Additional context**
**BTW same for -> edit servers and edit Channels** 

pls update and fix it im going crazy without it xD

**Comment by mwittrien** [comment]
#1806
