### ISSUE TITLE
[BUG] - BDFDB/low priority

### ISSUE THREAD

**Issue by zuzumi-f** [mwittrien/BetterDiscordAddons#1957]
**Describe the bug**
Plugin don't let you click the usernames in `Active Now` context menu

**To Reproduce**
Enable the Plugin/Library - Click the username in context menu - nothing happen

**Expected behavior**
Open the Profile Popout no matter where you click

**Screenshots**
![Discord_TyWcgrlLHA](https://user-images.githubusercontent.com/79029257/198042913-bb13dddc-8428-4c66-b4a2-ae54460e1423.gif)

**Discord Build (stable, ptb or canary):**
Stable 154186 (fccec91)

**Additional context**
All the other context menu buttons works fine

**Comment by mwittrien** [comment]
Works fine for me, might be a plugin conflict
