### ISSUE TITLE
[BUG] - BDFDB cannot operate normally

### ISSUE THREAD

**Issue by Husomeone** [mwittrien/BetterDiscordAddons#1960]
**Describe the bug**
BDFDB cannot run normally, and all plug-ins cannot be used

**To Reproduce**
From update to now

![屏幕截图 2022-10-27 103006](https://user-images.githubusercontent.com/103169156/198178356-341fe92c-13aa-4193-ac11-1b7a5f148ebb.png)

**Discord Build (stable, ptb or canary):**
Stable 154186 (fccec91)

**Comment by mwittrien** [comment]
If you are expierencing an Issue with BDFDB not initiating, try to download https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.data.json
and
https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/_res/0BDFDB.raw.css
and put them in your Plugins Folder. Afterwards reload Discord via `Ctrl + R`. This should fix the Issue of the Library not loading.
