### ISSUE TITLE
[BUG] - RemoveBlockedUsers (v.1.5.6) is hiding reactions from everyone (blocked & unblocked), including myself

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [mwittrien/BetterDiscordAddons#1961]
**Describe the bug**
The latest update to RemoveBlockedUsers ( version 1.5.6 ) is hiding all reactions if the `Reactions` plugin option is toggled on. This includes reactions from users that are not blocked, including myself.

**To Reproduce**
- React to any Discord message
- Install and enable RemoveBlockedUsers v.1.5.6
- Ensure that `Reactions` setting in plugin options is enabled
- Observe that your reaction from before is now gone, as well as reactions from anyone and everyone else

**Expected behavior**
Only the users that I've blocked should have their reactions hidden.

**Screenshots**
Before (1) - https://i.imgur.com/TNut46I.png
Before (2) - https://i.imgur.com/lCpiOjt.png
After (1) - https://i.imgur.com/htxjolf.png
After (2) - https://i.imgur.com/j0dCg81.png

**Discord Build (stable, ptb or canary):**
Stable 154750

**Comment by ProjectNemoLLC** [comment]
Beat me to it, A temporary fix for this is turning off reaction setting in plugin config, for anyone having troubles.
