### ISSUE TITLE
[BUG] - Completetimestamps

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1962]
**Describe the bug**
stuff dosent work

**To Reproduce**
do stuff with addon enabled

**Expected behavior**
stuff should work

**Discord Build (stable, ptb or canary):**
all the stuffs

**Additional context**
[CompleteTimestamps] (v1.6.2) has been started
[CompleteTimestamps] (v1.6.2) [AuditLogEntry] not found in PatchModules InternalData
(anonymous) @ fc348f33dcdb946d71d0.js:149
fc348f33dcdb946d71d0.js:149 [CompleteTimestamps] (v1.6.2) [MessageTimestamp] not found in PatchModules InternalData
(anonymous) @ fc348f33dcdb946d71d0.js:149

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
