### ISSUE TITLE
[BUG] - PLUGIN/Translator Unable to translate Chinese

### ISSUE THREAD

**Issue by piercingeye** [mwittrien/BetterDiscordAddons#1963]
Unable to translate Chinese
![1666961813426](https://user-images.githubusercontent.com/48711764/198594055-0459e99c-24fe-4619-8fe4-f987e4e1bc4b.png)

**Comment by mwittrien** [comment]
Your Internet Connection, most likely a VPN is the Issue

**Comment by Stan-SLIM** [comment]
I encountered the problem of consent, indicating that the server connection failed; I have tried to use proxies globally, but the problem still exists; Even after the translation is turned on, I cannot enter messages on the channel;

**Comment by Stan-SLIM** [comment]
I encountered the same problem, indicating that the server connection failed; I have tried to use proxies globally, but the problem still exists; Even after the translation is turned on, I cannot enter messages on the channel;

**Comment by Stan-SLIM** [comment]
![image](https://user-images.githubusercontent.com/114756785/198894690-964ba71f-c420-443e-9372-c4b8ca035dfd.png)
After opening, I will be prompted that I have no permission to enter messages; Normal after shutdown

**Comment by Stan-SLIM** [comment]
![image](https://user-images.githubusercontent.com/114756785/198894779-e4632ac1-aa2b-4595-89ea-df927cce54e5.png)
