### ISSUE TITLE
[Stops loading at ~185 ] - PluginRepo

### ISSUE THREAD

**Issue by khaledmoayad** [mwittrien/BetterDiscordAddons#1964]
**Describe the bug**
loads plugins until ~185 plugins 

**To Reproduce**
just enabling plugin

**Expected behavior**
display plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/94354651/198682224-dd261cdc-e5d1-4c1f-9d8e-06102dc218ca.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
sometimes wont load at all

**Comment by mwittrien** [comment]
Try reloading
