### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by ChapperNi** [mwittrien/BetterDiscordAddons#1968]
Plugin generates a "react component" error when clicking on the volume button.

**To Reproduce**
Click on the volume button while playing a song / listening along.

**Expected behavior**
A volume slider should show instead.

Betterdiscord 1.8.2, Regular discord

**Comment by drakosoldier298** [comment]
Theres not enough information, you were supposed to change the title to the theme or plugin name causing the problem

**Comment by mwittrien** [comment]
this has long been fixed, update your BDFDB plugin
