### ISSUE TITLE
[BUG] - BD Updater

### ISSUE THREAD

**Issue by HistoricTheater** [mwittrien/BetterDiscordAddons#1969]
**Describe the bug**
BD updater is not downloading all files needed when updates are presented.
As noted here #1962

**To Reproduce**
Update Plugin via BD updater

**Expected behavior**
All files required for plugins should be downloaded when updating plugins. In this case when updating BDFDB the secondary file BDFDB.data.json should also be updated when using the BD updater.

**Comment by mwittrien** [comment]
BDFDB.data.json gets auto updated when the file has bden changed on github
