### ISSUE TITLE
[Theme making question] how to remove the basicbackground by DevilBro?

### ISSUE THREAD

**Issue by TMZN0V4** [mwittrien/BetterDiscordAddons#197]
Yeah, I'm trying to have a BasicBackground, and trying to do it by myself, without the "BasicBackground by DevilBro" appearing, how can I do that?

**Comment by mwittrien** [comment]
Its my watermark to prevent thiefery, its not meant to be removed

**Comment by UNKNWNMOD** [comment]
Your watermark?! LOL the background image of this theme it's not yours!
