### ISSUE TITLE
[BUG] - Custom Status

### ISSUE THREAD

**Issue by angsaysroar** [mwittrien/BetterDiscordAddons#1975]
**Describe the bug**
I cannot access the settings, my prior saved status does not show up, and I cannot save statuses.

**To Reproduce**
Try to access settings.

**Expected behavior**
I expected the settings menu to load up.

**Screenshots**
[Settings](https://i.imgur.com/80eK42l.png)
[Prior Saved Statuses Missing](https://i.imgur.com/nY5zB3c.png)
[Unable to save custom status](https://i.imgur.com/J1vSfVd.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This plugin was working as intended, even after the update to Discord that broke most all plugins. I'm not sure why it is no longer working. 🤷🏾‍♀️

I appreciate your assistance and your willingness to maintain this plugin. Thank you!

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json in your plugins folder and reload discord
