### ISSUE TITLE
[BUG] - BDFDB/low priority - Better Redaction

### ISSUE THREAD

**Issue by zuzumi-f** [mwittrien/BetterDiscordAddons#1977]
**Describe the bug**
Copy of #1957. Plugin don't let you click the usernames in `Active Now` context menu
New info: The class `nameTag` starts reload whenever you hover or click it

**To Reproduce**
Enable the Plugin/Library - Click the username in context menu - nothing happen

**Expected behavior**
Open the Profile Popout no matter where you click

**Screenshots**
![Discord_MQAGJuWDwJ](https://user-images.githubusercontent.com/79029257/198879620-ae510fd2-c02d-4bdb-a009-588aa3138d7c.gif)

**Discord Build (stable, ptb or canary):**
Stable 154750 (f375f97)

**Additional context**
This is a clear install of Discord and BD deleting all the cache and folders of older versions or corrupted files.
In #1957 I forgot to show:
- BDFDB as the only existing plugin in the folder.
- Inspect the items
- Give a clear description

**Comment by mwittrien** [comment]
reloading discord should fix it
