### ISSUE TITLE
[BUG] - Translator not available

### ISSUE THREAD

**Issue by AIDA64S** [mwittrien/BetterDiscordAddons#1985]
Translation times out regardless of the API used

**Comment by mwittrien** [comment]
Issue with your Internet/VPN

**Comment by AIDA64S** [comment]
I'm sure my VPN is fine and it hasn't happened before

**Comment by AIDA64S** [comment]
> 您的 Internet/VPN 问题
Other than that everything works fine including accessing translate.google.com etc.

**Comment by AIDA64S** [comment]
> Issue with your Internet/VPN
Other than that everything works fine including accessing translate.google.com etc.
