### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by otDan** [mwittrien/BetterDiscordAddons#1987]
**Describe the solution you'd like**
Allow the folder sizes to be configured with separate sizes than the servers

**Comment by mwittrien** [comment]
Why

**Comment by otDan** [comment]
well to allow more customizability, I just feel like the folders can be smaller than the servers in my use case as the text can be less readable knowing the section.
![image](https://user-images.githubusercontent.com/59731738/199064636-864e05d3-5080-4e7d-8968-edb8bad58d83.png)
in this for example the folder could be that size and keep the servers as the current one

**Comment by mwittrien** [comment]
This would create issues with the unread messages element

Since discord uses the same height for all elements to check if the element should be shown
