### ISSUE TITLE
[BUG] - Theme Repo

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#1989]
**Describe the bug**
Previev thumpnails dont load without hover over it

**To Reproduce**
use theme repo and search for themes then you see if you hover over a picturee then it load but before not

**Expected behavior**
that the preview thumpnails load self without hover over every single item.

**Screenshots**
here a video:
https://streamable.com/j3np6e

here a screenshot:
![image](https://user-images.githubusercontent.com/25110093/199139132-fd537f5a-206c-4870-8c56-015736e97fa8.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/199139173-354f230c-fbb5-4fb5-b468-e33bb51608b1.png)

**Additional context**
hey when is edit users/servers/Channels work again ? 
also: its just a report to inform you about this spezific bug

**Comment by mwittrien** [comment]
Thats intended behaviour to reduce resource usage

**Comment by BlueStarBRS** [comment]
> Thats intended behaviour to reduce resource usage

[Improvement] maybe add on of toggle ? [for the saving option who is default on save proformance ?]
