### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by Dimeus3** [mwittrien/BetterDiscordAddons#1990]
Hi it's not really a bug but it's a personal problem that I encounter with the plugin.
I do not speak english perfectly but my pc is in english I learn like that but the problem is that the plugin translates to the display language of the pc so it is impossible to translate english!
I propose to make an option in the parameters of the pugin which asks in which language wishes your to translate the message!

**Comment by mwittrien** [comment]
Click the button in the bottom right
