### ISSUE TITLE
[BUG] - REMOVEBLOCKEDUSERS

### ISSUE THREAD

**Issue by Tomahawk27x** [mwittrien/BetterDiscordAddons#1992]
Found a bug where you can't scroll through a discord group's pins properly. For example if you scroll all the way down it goes back to the top. Discord server/user dm pins work normally.

**Comment by mwittrien** [comment]
Can u take a video

**Comment by Tomahawk27x** [comment]
https://user-images.githubusercontent.com/116083204/199325526-8561d5a7-3874-4001-b315-b8d64ac9d202.mp4

Here. I also experience frame drops when I check a group, and this is not because I'm recording. None of this happens when I turn off the plugin.

**Comment by mwittrien** [comment]
Check with all other plugins disabled

**Comment by Tomahawk27x** [comment]
It still happens :/
