### ISSUE TITLE
[BUG] - BDFDB stops working after reloading Discord

### ISSUE THREAD

**Issue by andrwmai** [mwittrien/BetterDiscordAddons#1993]
**Describe the bug**
BDFDB can't load settings panel after reloading Discord. I have to redownload all 3 files provided by Disease and put them in the plugins folder, then restart my Mac for BDFDB to load the settings panel. Everything including DB's plugins works until I reload Discord. If I want to get it to work again I have to redo everything I just listed above.

**To Reproduce**
Reload Discord while BDFDB and DB's plugins are working fine.

**Expected behavior**
Plugins and BDFDB still work and are able to load settings panel. Instead I get the message that BDFDB couldn't initiate the settings panel. I've followed the instructions listed in the prompt too but it didn't help.

**Screenshots**
![image](https://user-images.githubusercontent.com/48293860/199320672-b86c5395-b488-46a7-ad70-e965434104ef.png)

**Discord Build (stable, ptb or canary):**
Stable 155407 (4d2682d)

**Additional context**

**Comment by andrwmai** [comment]
Opening this again because it wasn't fixed. After a reload, BDFDB just stops working again plus all the other plugins.

**Comment by andrwmai** [comment]
I followed these steps from Disease#5663 and it still didn't work. @mwittrien 

> Complete quit discord
> Delete the files
> Redownload the files and place in folder
> Then without opening discord, restart pc and check

**Comment by mwittrien** [comment]
no clue anymore, not sure what else we can try
