### ISSUE TITLE
Baidu Translate is unavailable

### ISSUE THREAD

**Issue by CkeryL666** [mwittrien/BetterDiscordAddons#1994]
Please fix the problem of Baidu Translator 50023. I can provide the api and key for you to solve.

APP ID：20221009001380882
key：TOPnUKz8jJ32AZNOuUhX

**Comment by CkeryL666** [comment]
![Uploading 6B5OMH6@K%{}%G~E7U{YBS5.png…]()

**Comment by CkeryL666** [comment]
![111](https://user-images.githubusercontent.com/115634943/199395490-1fa0e0bc-b4df-41c9-84cb-6cb8f67138c3.png)

**Comment by CkeryL666** [comment]
?

**Comment by CkeryL666** [comment]
All translations are unavailable, why not resolve them?

**Comment by mwittrien** [comment]
Update the plugin

**Comment by CkeryL666** [comment]
Thanks, no more questions!
