### ISSUE TITLE
[BUG] - NOT SURE

### ISSUE THREAD

**Issue by itoffie** [mwittrien/BetterDiscordAddons#1995]
discord keeps crashing after the update of library or your plugins as other plugins installed on my pc didnt have an update before crashing starts only the library and plugins has updates

the issue is that there might be memory leak on the plugins or library itself that got recently updated 

RAM's reaching about 1.3GB+ while not doing anything else just watching a live screen share

**Comment by mwittrien** [comment]
or maybe its discord being dumb again,
your reasoning just because my plugins got an update and the issue started occuring, doesn't mean that the update caused it
