### ISSUE TITLE
[BUG] - PIN DMS

### ISSUE THREAD

**Issue by dan201455** [mwittrien/BetterDiscordAddons#1996]
**Describe the bug**
When I click any DM not part of the pined ones in folders it will scroll down my DM list quite far, with the plugin PinDMs.
I am on version 1.9.7.

**To Reproduce**
I have no idea

**Expected behaviour**
Not to scroll down the DM list.

**Screenshots**
https://gyazo.com/4e4043ac82cb646edd1033e5a78bb965 

Gyazo link to gif showing whats I mean.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I don't know if others have this bug or if its another plugin interfering with PinDms, just thought I would report it.

**Comment by DexLuther** [comment]
Do you have any other plugins because I'm not getting this issue at all.
