### ISSUE TITLE
[BUG] - ServerFolders doesn't open Folders in an extra column

### ISSUE THREAD

**Issue by nick75g** [mwittrien/BetterDiscordAddons#1998]
**Describe the bug**
The plugin ServerFolders doesn't open server folders in a seperate column after enabling the option to do so in the plugin settings.

**To Reproduce**
Install the plugin, enable option "Moves the Servers from opened Folders into an extra column", reload Discord.

**Expected behavior**
The servers from the opened folders should be displayed in a column right from the "Servers" column.

**Screenshots**
![image](https://user-images.githubusercontent.com/57896934/199971552-8bd4cc24-f9e6-43e7-9def-afe1f8fae649.png)

**Discord Build (stable, ptb or canary):**
Stable 156080 (c1142ae)

**Comment by mwittrien** [comment]
#1806
