### ISSUE TITLE
CharCounters

### ISSUE THREAD

**Issue by LexussD** [mwittrien/BetterDiscordAddons#20]
Sometimes when I click on a channel, the counter disappears, so I would have to keep clicking on other channels for it to reappear for that channel. Why is that?

**Comment by mwittrien** [comment]
Are you sure you are using mine and not jiiks version

**Comment by LexussD** [comment]
Yes. http://prntscr.com/hk62xg

**Comment by mwittrien** [comment]
Can't recreate the issue, it works fine for me
