### ISSUE TITLE
[BUG] - EditChannels - Marking channels as unmuted and removing channel categories 

### ISSUE THREAD

**Issue by Mister36MN** [mwittrien/BetterDiscordAddons#2000]
**Describe the bug**
 After updating EditChannels to the version that came out today (4.4.3) I noticed that all channels I had muted started indicating that they were unmuted and had unread messages, checked and they are still muted, unmuting and remuting still has same symptom. 

There are certain whole channel lists that got removed too - screenshots below

**To Reproduce**
Have EditChannels 4.4.3 active.

**Expected behavior**
Muted channels and unhidden categories

**Screenshots**
Categories with plugin disabled:

<img width="188" alt="image" src="https://user-images.githubusercontent.com/36009507/200072396-4d8546ac-83af-4895-b477-9f7e95fc6dfd.png">

With plugin enabled - can see that top category is gone but I am still in the same channel (also the two channels with notifs are showing the muted channel problem too)

<img width="218" alt="image" src="https://user-images.githubusercontent.com/36009507/200072488-671d044f-d6ed-43ff-8c72-e65d6778bc46.png">

-----

Muted channels with plugin enabled:

<img width="161" alt="image" src="https://user-images.githubusercontent.com/36009507/200072713-689af2af-f72f-4b13-9fac-f4d3fa5fe46e.png">

Muted channels with plugin disabled:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/36009507/200072880-a54dfbdd-0dbd-40f6-9277-880b59cd56c2.png">

**Discord Build (stable, ptb or canary):**
Stable - 156406 - Host 1.0.9007

**Additional context**
I had edited some of my own channels (color shown only) but changed no settings in the plugin

**Comment by mwittrien** [comment]
Make sure BDFDB is up to date and try reloading discord

**Comment by Mister36MN** [comment]
BDFDB was updated to 2.9.7 at the same time, and I had reloaded discord to test.

**Comment by Kxsumi** [comment]
Have reloaded BD, reinstalled BD, reinstalled BDFBD, same issue.
