### ISSUE TITLE
[BUG] - Chat Aliases

### ISSUE THREAD

**Issue by cibere** [mwittrien/BetterDiscordAddons#2001]
**Describe the bug**
I'm not able to get the plugin to work

**To Reproduce**
install the plugin, add an alias, try to use it

**Expected behavior**
for something to happen, wiether it be replacing the word with another word, or something showing up in the autocomplete menu

**Screenshots**
alias: https://i.cibere.dev/WtrMpI.png
settings: https://i.cibere.dev/xLksDC.png
proof: https://i.cibere.dev/6lgSYk.gif
the github shows it as a slash command, but it doesnt show up: https://i.cibere.dev/QYHKLP.png

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
i dunno what to say

**Comment by mwittrien** [comment]
#1806
