### ISSUE TITLE
[IMPROVEMENT] - ReadAllNotificationsButton

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2004]
**Describe the solution you'd like**
lets make it changeable to show "Read all" or "read all"

**Describe alternatives you've considered**
add a toggle to the settings with the option make the r big or not

**Additional context**
i see edit channels works again i can´t wait for edit users :D <3

**Comment by BlueStarBRS** [comment]
I find with big R it looks more aesthetic

**Comment by mwittrien** [comment]
Change it with css

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/200143223-c5bd27ce-41e1-44fd-ab07-3ee2394e5f0f.png)
for everyone who want that to:

paste this in your css section in your BD client (under options)

```
.tree-3agP2X .childWrapper-1j_1ub.button-Jt-tIg {
  text-transform: capitalize;
}Read all
```
