### ISSUE TITLE
[BUG] - Image Utilities

### ISSUE THREAD

**Issue by Gimpy3887** [mwittrien/BetterDiscordAddons#2006]
**Describe the bug**
The "copy image" option doesn't work anymore.

**To Reproduce**
When I right click an image, press "Copy Image" and when I post it in a channel: it doesn't work.

**Expected behavior**
I expect the image I copied to be saved to my clipboard. 

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
make sure the plugin and BDFDB are up to date

works fine for me

**Comment by Gimpy3887** [comment]
They are up to date; I also re-installed them, and same issue.
