### ISSUE TITLE
[BUG] - ServerFolders Extra Collumn Not Working

### ISSUE THREAD

**Issue by Rikopara** [mwittrien/BetterDiscordAddons#2007]
**Describe the bug**
Extra column is not showing up in any way. Needed setting turned on, also there's no another plugins or themes.
Creating folder does not work too, when I click "Create folder" React Component error appears.

**To Reproduce**
Just open the folder, it'll open in usual way without extra column.

**Discord Build (stable, ptb or canary):**
Stable 156540 (16ecd97) Host 1.0.9007 Windows 10 64-Bit (10.0.22621)

**Comment by mwittrien** [comment]
#1806
