### ISSUE TITLE
[BUG] - EditChannels 4.4.4 - Some Channel Categories Still Hidden

### ISSUE THREAD

**Issue by Mister36MN** [mwittrien/BetterDiscordAddons#2008]
**Describe the bug**
On certain servers, it still removes what appears to be the top server channel category in some (but not all) servers when the plugin is active. This is without any modification of those channels with the plugin.

**To Reproduce**
When EditChannels 4.4.4 is active.

**Expected behavior**
Categories shown.

**Screenshots**
Here's one server where there is nothing as it only has one category or all of them are hit by whatever this bug is.

<img width="106" alt="image" src="https://user-images.githubusercontent.com/36009507/200126922-4a3aabbd-dd98-4be2-9390-5dc5dee415ea.png">

With plugin disabled:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/36009507/200126993-0cff59fb-e2a2-460d-b5d3-7e6db6e06954.png">

**Discord Build (stable, ptb or canary):**

<img width="151" alt="image" src="https://user-images.githubusercontent.com/36009507/200127011-967940cf-85b3-41b9-a3a1-01a1e960cd37.png">

**Additional context**

**Comment by mwittrien** [comment]
Fixed in 4.4.5
