### ISSUE TITLE
UserNotes.js Doesn't Work

### ISSUE THREAD

**Issue by pkerr3** [mwittrien/BetterDiscordAddons#201]
When I try to go to settings it just shows this instead; if I click remove, its like "Are you sure?" and if I press okay it doesn't do anything.
![image](https://user-images.githubusercontent.com/47022622/57259464-5f828180-7025-11e9-9bee-145fab333007.png)

**Comment by mwittrien** [comment]
Because thats all the plugin does in the settings? If you wanna add a note to a user right click the user and press UserNotes
