### ISSUE TITLE
[BUG] - Last message date

### ISSUE THREAD

**Issue by Krazytrain** [mwittrien/BetterDiscordAddons#2010]
**Describe the bug**
The last message date dont show up in user pop out on stable discord. It only shows it on the user profile pop put.

**To Reproduce**
Have the stable discord installed and then click on someone so it pops out. 

**Expected behavior**
Users last message should be there.

**Screenshots**
[Screenshot ](https://i.postimg.cc/HLnXcK8y/screenshot-563.png)
![image_2022-11-05_175924722](https://user-images.githubusercontent.com/54170019/200134395-942efbef-0dbd-47f8-b3f8-073aac8cb33b.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
Thats because you still got the old style for the user popout

It will work once discord roled out the style for everyone
