### ISSUE TITLE
[BUG] - Personal Pins

### ISSUE THREAD

**Issue by Amuadutua** [mwittrien/BetterDiscordAddons#2011]
**Describe the bug**
When having too many notes, discord will crash and need to reload, I encountered this when trying to click on the All Servers button to view my notes from all servers, and discord froze for a second then showed the crashed unexpectedly screen.

**To Reproduce**
When having too many notes, try opening the notes menu

**Expected behavior**
Showing notes from all servers

**Screenshots**

https://user-images.githubusercontent.com/75052775/200139674-36755206-8cf0-4194-a061-c536033329e5.mp4

![Discord_2022-11-05_15-25-30](https://user-images.githubusercontent.com/75052775/200139659-82b0d915-2a63-45a5-98d4-a9240b2d715c.png)

![Discord_2022-11-05_15-23-37](https://user-images.githubusercontent.com/75052775/200139680-291bbf78-54fa-434a-8f8c-86dc5f096a88.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None

**Comment by mwittrien** [comment]
Can you send me your PersonalPins.config.json via email

**Comment by Amuadutua** [comment]
Sure, I will send an email in a few mins when I can

**Comment by Amuadutua** [comment]
There, sent
