### ISSUE TITLE
When the translation source selects Google to translate Chinese, the server is offline.

### ISSUE THREAD

**Issue by superbbttcc** [mwittrien/BetterDiscordAddons#2015]
Google Translate has stopped operating from China, so the author should not change the address again. Now the better discord plugin selects Google Translate to translate Chinese and keeps prompting the server to go offline

**Comment by AIDA64S** [comment]
On top of that it seems that addon cannot connect google translate server through proxy

**Comment by mwittrien** [comment]
> On top of that it seems that addon cannot connect google translate server through proxy

Thats an issue with your proxy and not the plugin

**Comment by awslshadowstar** [comment]
It seems not support system proxy settings，may be need to need to set it in the `0BDFDB.plugin.js`

**Comment by AIDA64S** [comment]
> It seems not support system proxy settings，maybe need to set it in the `0BDFDB.plugin.js`
My proxy network is completely fine, it may be the reason you said, I will try it

**Comment by Roshine08** [comment]
> > On top of that it seems that addon cannot connect google translate server through proxy
> 
> Thats an issue with your proxy and not the plugin

thats because he cannot swich the api to others.
there is no button for that

**Comment by AIDA64S** [comment]
> > On top of that it seems that addon cannot connect google translate server through proxy
> 
> Thats an issue with your proxy and not the plugin
I've set up the system global proxy and I'm sure it can access google translate without problems

**Comment by AIDA64S** [comment]
> 

Unfortunately, I'm not a javascript developer and I don't know where to set the proxy

**Comment by mwittrien** [comment]
> Google Translate has stopped operating from China, so the author should not change the address again. Now the better discord plugin selects Google Translate to translate Chinese and keeps prompting the server to go offline

Just tried translating text TO chinese via Google and FROM chinese via Google and both work just fine
no clue what your issue is
