### ISSUE TITLE
[Remember last file-save folder] - ImageUtilities

### ISSUE THREAD

**Issue by cherrynim0417** [mwittrien/BetterDiscordAddons#2017]
ImageUtilities plugin definitely used to remember your last saved file location any time you saved something new and now it does not do that, it just directs you to your default save location with every new picture that I want to save. I usually save pictures several at a time in a bunch of folders that aren't my "downloads" folder... It's pretty tedious to have to navigate to the correct folder every single time i want to save an image somewhere when before I could just click the "save image as" button and it would automatically load the folder in which I last saved something. Is there a setting somewhere that i'm missing that needs to be enabled for the plugin to remember where I last saved an image or was this feature just overlooked when the plugin got fixed to work with the new discord update?

**Comment by mwittrien** [comment]
The plugin now uses the internal function provided by discord to open the save file as dialog, so i cant change how it works any longer

**Comment by leellleeell** [comment]
> The plugin now uses the internal function provided by discord to open the save file as dialog, so i cant change how it works any longer

I hate to be annoying but is this 100% unfixable? A lot of the utility of this plugin was it fixed discords annoying thing of not remembering the last save folder
