### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by Avakining** [mwittrien/BetterDiscordAddons#2018]
**Describe the bug**
Toggle does not appear

**To Reproduce**
Whenever the plugin is enabled 

**Expected behavior**
The toggle game activity buttons is shown

**Screenshots**
<img width="646" alt="Screenshot 2022-11-10 at 14 30 21" src="https://user-images.githubusercontent.com/25210618/201188882-c711c5f5-59d7-4ebf-81db-3b47b32bffd8.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/25210618/201188855-580cf765-5874-4013-97eb-cf8e0659153f.png">

**Discord Build (stable, ptb or canary):**
Ptb 157642 (32125a4)

**Additional context**
Plugin version v1.1.7
BetterDiscord 1.8.2

**Comment by itsKline** [comment]
Same is happening on stable build. Was working last night and now is not

**Comment by yeahbuddy2575** [comment]
Same here !

**Comment by WIG78** [comment]
Same behavior
