### ISSUE TITLE
[BUG] - RemoveBlockedUsers / BDFDB

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2019]
**Describe the bug**
Blocked users are still to see in the chat

**To Reproduce**
look in a chat with a blocked user

**Expected behavior**
that the plugin works bro

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/201200867-d5847a8d-b3ac-42c6-bd79-64bbdd6e3051.png)
![image](https://user-images.githubusercontent.com/25110093/201200965-8203eda4-c41e-4f3c-96e8-b782b8545080.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/201201106-aaf50699-f2e5-448e-b6b3-b7a7f25a6022.png)

**Additional context**
it seems BDFDB is broken because readl all and freind count is also not work and not showing under the home button
![image](https://user-images.githubusercontent.com/25110093/201201776-9a403964-ebf6-4a3f-966d-aa0920d9033d.png)

here a video uff my full log you will see some errors related to your plugins like BDFDB and Better Discord
https://streamable.com/40bi2x <-- here the video of the **FULL** Log

**Comment by Mister36MN** [comment]
Also seeing this on stable 157708

**Comment by BlueStarBRS** [comment]
update: translator Plugin and other plugins also stopped working with this bug
![image](https://user-images.githubusercontent.com/25110093/201249188-0b128e3e-116d-4084-a49a-843b2879c7bc.png)
^ translate button is not there also its not appers in the dropdown menu

**Comment by mwittrien** [comment]
#2047
