### ISSUE TITLE
[BUG] - ReadAllNotificationsButtom

### ISSUE THREAD

**Issue by Agusss9** [mwittrien/BetterDiscordAddons#2020]
**Describe the bug**
My plugin's button ReadAllNotificationsButtom disappeared already try:
• restart discord.
• disable and re-enable the plugin.
• re-download the plugin.
And I have the latest version of the plugins.

**To Reproduce**
When starting Discord the button does not appear.

**Expected behavior**
The button should appear in the upper left part of the screen and work correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/117945051/201201520-630b83bb-f44e-467f-9d5a-61da6dee08ae.png)
![image](https://user-images.githubusercontent.com/117945051/201201652-1b8fcf8c-f375-4f61-b638-e00b95b045ee.png)
![image](https://user-images.githubusercontent.com/117945051/201201671-a17087b7-dc1a-45a0-bc40-67ee24e1c861.png)

**Discord Build (stable, ptb or canary):**
I'm using the original Discord.

**Additional context**
What seems strange to me is that yesterday I turned on the PC and had the button and today it disappeared out of nowhere.

**Comment by PixelGuy123** [comment]
By the way, this happened after the latest Discord Update

Just an additional point, every plugin that uses the BDFDB have their settings broken, when opening it, it says it couldn't load and asks for opening console (I did that, but forgot to copy the logs)

I just restarted Discord and it seems the settings are "fixed" but any plugin that uses BDFDB doesn't seems to work (Including the one above)

**Comment by Agusss9** [comment]
Ok, this problem happened yesterday, what should I do to solve this error?

**Comment by PixelGuy123** [comment]
Idk I'm not the creator, just added additional information to this post because I'm lazy to create a new one

**Comment by Agusss9** [comment]
I have nothing more to add, I explained everything in the first message.

**Comment by Styphoryte** [comment]
> I have nothing more to add, I explained everything in the first message.

Same issue here as well. I'm guessing the update broke it unfortunately. Why Discord doesn't even have this feature yet is beyond me...

**Comment by mwittrien** [comment]
#2047
