### ISSUE TITLE
[BUG] - Plugin Translator not working

### ISSUE THREAD

**Issue by SirVinFlow** [mwittrien/BetterDiscordAddons#2021]
Hello, the Translator plugin stopped working for me, it stopped translating various messages, the translator icon on the line with the message set also disappeared, I already tried to reinstall everything, it still doesn’t work.
![вйцвйвйвйцвйвй](https://user-images.githubusercontent.com/115183632/201209305-fbbdd001-96f6-4ee0-b0bf-cf4a79c93c59.jpg)
![вйцвйвйвйв](https://user-images.githubusercontent.com/115183632/201209310-408063b3-aa92-4412-ad6d-60fa0b091226.jpg)

**Comment by Merdatum** [comment]
same here, it's general default ?

**Comment by SirVinFlow** [comment]
> то же самое здесь, это общий дефолт?

Perhaps, you have the same bug?

**Comment by vrgz2022** [comment]
same here +1

**Comment by fowlis** [comment]
"same" comments are unhelpful. Either react with 👍 to the original post or provide some useful info i.e. console errors, relating to the problem.

**Comment by Roshine08** [comment]
Why u delete my reply

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
