### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by KingGamingYT** [mwittrien/BetterDiscordAddons#2023]
**Describe the bug**
Plugin and all of its features have ceased functioning. The plugin can be installed without issues or errors, however, it is nonfunctional.
(Update: The plugin's right-click context menu is semi-functional. You can copy links, use reverse image search, and save the image, but copying the image itself is broken.)

**To Reproduce**
Simply install the plugin and try to use its functionality.

**Expected behavior**
The plugin should function as intended.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by Silvia-Dragoness** [comment]
I mainly use this plugin for the image embed resizing and image viewer zoom functions.  Both have stopped working.

**Comment by leetfin** [comment]
+1

**Comment by Silvia-Dragoness** [comment]
Oh hey.  I didn't notice any update to this plugin, DB's library, or Discord itself, but this just randomly started working again.

**Comment by KingGamingYT** [comment]
> Oh hey. I didn't notice any update to this plugin, DB's library, or Discord itself, but this just randomly started working again.

I have observed no such change in functionality unfortunately.

**Comment by mwittrien** [comment]
#2047
