### ISSUE TITLE
[BUG] - Clickable mention

### ISSUE THREAD

**Issue by Soulivan71** [mwittrien/BetterDiscordAddons#2024]
**Describe the bug**
I try to mention someone in my message input and when I clic on mention, no popout

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/36502190/201220559-aeadb497-c815-4e49-ae03-60570293c7b0.png)

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by Soulivan71** [comment]
I post it before so be quiet plz

**Comment by mwittrien** [comment]
#2047
