### ISSUE TITLE
[BUG] - ServerCounter

### ISSUE THREAD

**Issue by deadmau1** [mwittrien/BetterDiscordAddons#2027]
**Bug**
ServerCounter is not working 

**Screenshots**
![image](https://user-images.githubusercontent.com/115784191/201278235-d5fd0f53-ca1b-4404-afa9-317c955f48d2.png)
![image](https://user-images.githubusercontent.com/115784191/201278246-cecf0190-6738-4565-8302-ea66c21ef0d5.png)

**Discord Build**
Stable 157708 (8899c5c)

**Comment by AsoGamer14** [comment]
having the same problem, anyone else?

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
