### ISSUE TITLE
[BUG] - BDFDB can´t set toast Position

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2028]
**Describe the bug**
i cant set toast Position in the settings

**To Reproduce**
go in settings

![image](https://user-images.githubusercontent.com/25110093/201280842-3aa402aa-2492-40aa-a4f9-f65813ed1918.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/201280908-d0d4934e-8d0a-40c7-bf8b-36b6656efa01.png)

**Additional context**
i just noticed it random

**Comment by mwittrien** [comment]
#2047
