### ISSUE TITLE
[BUG] - TRANSLATOR/N/A

### ISSUE THREAD

**Issue by ronrishadi** [mwittrien/BetterDiscordAddons#2029]
**Describe the bug**
The bug is just not showing the translator button option.

**To Reproduce**
A while ago.
**Expected behavior**
I thought it would show up 

**Screenshots**
![image](https://user-images.githubusercontent.com/80612541/201288957-97ad72b3-b999-4669-b1ca-7a2bb9a5e4d0.png)
![image](https://user-images.githubusercontent.com/80612541/201288992-9484f738-ab5a-4e54-abcf-a99d27849184.png)
![image](https://user-images.githubusercontent.com/80612541/201289012-ee6f75f3-69fd-42c7-aabb-8a51db8615b0.png)

**Discord Build (stable, ptb or canary):**
Stable.
**Additional context**
N/a

**Comment by SirVinFlow** [comment]
I have the same

**Comment by asdwsaxc2** [comment]
Same. it wont show the button to switch api then replace to another one

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
