### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Marabus69** [mwittrien/BetterDiscordAddons#2030]
When in the sound configuration menu the options to change sound and category are not there

When the plugin is enabled

I wanted to change my ringtone

Build is stable

![Unbasdsadenannt](https://user-images.githubusercontent.com/118000288/201363315-df7f5f66-aea2-404f-8e8a-409b50f3f03c.PNG)

**Comment by mwittrien** [comment]
#2047
