### ISSUE TITLE
[BUG] - NOTIFICATIONSOUNDS/THEMENAME

### ISSUE THREAD

**Issue by SimonYuuki** [mwittrien/BetterDiscordAddons#2031]
**Describe the bug**
I get message notifications when I have no new messages, the notifications pop at random times, like normal messages

**To Reproduce**
Activate the plug-in

**Expected behavior**
I don't get notifications at random times because it is very annoying

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I installed the plug in to set a custom ringtone and I took the opportunity to put a different sound when someone mentions me or when I receive a mp

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
