### ISSUE TITLE
[BUG] - NOTIFICATIONSOUNDS/THEMENAME

### ISSUE THREAD

**Issue by SimonYuuki** [mwittrien/BetterDiscordAddons#2032]
**Describe the bug**
The location where we can change the sound of each sound does not appear in "Sound configuration" anymore

**To Reproduce**
Just dl the plugin... ?

**Expected behavior**
See the parameters

**Screenshots**
![image](https://user-images.githubusercontent.com/57315555/201393195-bf290259-6c90-4d8d-8a4f-789b5747f40a.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
