### ISSUE TITLE
[BUG] - Notification Sounds / No category/sound button

### ISSUE THREAD

**Issue by BNr-SP** [mwittrien/BetterDiscordAddons#2033]
**Describe the bug**
I'm trying to change the sound scheme, but there is no category/sound button

**To Reproduce**
I tried to reinstall the plugin, install the old versions but in vain

**Expected behavior**
_I have nothing more to say, screenshots below_

**Screenshots**
![image](https://user-images.githubusercontent.com/71982930/201393801-94453fda-8f2e-4863-8d83-64edbad1ac2b.png)

**Discord Build (stable, ptb or canary):**
I use Discord PTB
![image](https://user-images.githubusercontent.com/71982930/201393610-b50c672d-0be1-4a44-bcc8-6443771df7ee.png)

**Comment by BNr-SP** [comment]
i also tried to run the program as administrator

**Comment by VYL0Z** [comment]
Same issue here, even with the stable version of discord. In my opinion it's the latests updates of discord that does this.

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
