### ISSUE TITLE
[BUG] - StaffTag

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2034]
**Describe the bug**
StaffTag does not show tags on messages in the chat anymore

**To Reproduce**
wait for someone with a staff tag to send a message in chat

**Expected behavior**
there's a Staff Tag next to their message

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/201425822-a29a13f2-27a1-4de5-9eff-363dfa6a0dfe.png)
![image](https://user-images.githubusercontent.com/48365199/201425870-2c06b135-c4eb-401a-9ffa-3b5808e4bd74.png)
this user is the owner of the server

**Discord Build (stable, ptb or canary):**
stable

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
