### ISSUE TITLE
[BUG] - Literally any plugin that uses BDFDB doesn't work properly

### ISSUE THREAD

**Issue by PixelGuy123** [mwittrien/BetterDiscordAddons#2035]
**Describe the bug**
All plugins that doesn't work includes: ReadAllNotifications (not showing button), Translator (Forgot that exists lol), BDFDB (I guess?), BetterSearchPage (Don't work on searchPage, also made me forgot that plugin was on my plugins folder), MessageUtilities (Not really sure how it works because I never really used it, but CTRL + H doesn't work, so I guess that counts too). 

Maybe there's more, but not gonna search all the plugins folder for glitches

**To Reproduce**
Use new Discord version and cry about it

**Expected behavior**
Use new Discord version... _and not cry-_ I mean, everything should be working I properly

**Screenshots**
![image](https://user-images.githubusercontent.com/89644121/201438383-4226d61b-98c5-4d44-ad11-c4016ceb8251.png)
(Showing up that ReadAllNotifications button doesn't appear on context menu)

**Discord Build (stable, ptb or canary):**
Discord Stable 157708 (8899c5c)

**Additional context**
Also using BetterDiscord, this is a huge fact, maybe it may be helpful... I guess

**Comment by Pashata105c** [comment]
Spotify controls hasn't been working as well

**Comment by PatrickSantoZZ** [comment]
FriendNotifications Button is missing too. i guess its a problem with Discords newest update. so just waiting for a fix now.

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by Pashata105c** [comment]
can you give me discord link?

**Comment by PatrickSantoZZ** [comment]
> @ALL, please check the discord server. @mwittrien sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.
thank you for forwarding the info here.

**Comment by Crypt0Beaver** [comment]
> can you give me discord link?

It is everywhere, on your plugin info in discord, on betterdiscord page, but here it is also: https://discord.com/channels/410787888507256842/Jx3TjNS

**Comment by Pashata105c** [comment]
what happened why did they delete all comments :DD

**Comment by mwittrien** [comment]
Talking offtopic shit, pinging me in over 10 issue reports and such giving me unneccesary notifications while i am on my vacation in spain, maybe?
Buzz off

**Comment by PixelGuy123** [comment]
LMAO 10 pings talking about Discord Server Link, guess that's second time I see people "discussing" over a random issue report (not yours)
Btw I think you should at least give somehow a warn about creating duplicated issues for BDFDB (Guess it's already clear you know that BDFDB and any plugin using it are having issues)

**Comment by mwittrien** [comment]
#2047
