### ISSUE TITLE
[BUG] - PinDM categories aren't showing.

### ISSUE THREAD

**Issue by MagmaBro123** [mwittrien/BetterDiscordAddons#2037]
**Describe the bug**
Title.

**To Reproduce**
Use the plugin.

**Expected behavior**
The plugin to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/51277766/201454411-94a04480-beb8-448a-8c4f-a086dda6dd0c.png)

**Discord Build (stable, ptb or canary):**
Stable, since Canary is broken.

**Additional context**
N/A

**Comment by HirschBerge** [comment]
#2022

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
