### ISSUE TITLE
[BUG] - ImageUtilities not working

### ISSUE THREAD

**Issue by Tetrax-10** [mwittrien/BetterDiscordAddons#2038]
![image](https://user-images.githubusercontent.com/75513645/201472966-0a8f5cda-6337-4c8a-9926-f9716745623e.png)

**Comment by Crypt0Beaver** [comment]
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment]
#2047
