### ISSUE TITLE
stalker notifications not working anymore

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#204]
stalker notifications doesn't work anymore

**Comment by mwittrien** [comment]
Yes it does
![image](https://user-images.githubusercontent.com/23700969/57607743-0ad28f80-756c-11e9-998b-ce7b5a5fd34e.png)

**Comment by jack652** [comment]
i said stalker notifications, not friend Friend Notifications

**Comment by mwittrien** [comment]
Yes and the screenshot shows someone I am observing via StalkerNotifications

**Comment by jack652** [comment]
that's weird i don't see non-friends status

**Comment by mwittrien** [comment]
Make sure you are using the plugin correctly
You need to add the ID to the list in the plugin settings of the people you want to observe

**Comment by jack652** [comment]
i did but it still doesn't show their status
