### ISSUE TITLE
[BUG] not have button

### ISSUE THREAD

**Issue by aPtichka** [mwittrien/BetterDiscordAddons#2043]
![image](https://user-images.githubusercontent.com/87618476/201753718-a2ca7dff-0750-489a-bc08-bbbfc3bee42d.png)

how me pick sound

**Comment by hexisXz** [comment]
same

**Comment by ArabiGucci** [comment]
same

**Comment by hexisXz** [comment]
i tried everything even reinstalling discord and better discord and it still doesn't work so it must be the plugin.

**Comment by mwittrien** [comment]
#2047
