### ISSUE TITLE
[BUG] - ServerHider

### ISSUE THREAD

**Issue by Dimmizer** [mwittrien/BetterDiscordAddons#2046]
**Describe the bug**
if you try to hide servers in or out of a folder and the icon for the server moves down but goes back to it's original place and doesn't hide.

**To Reproduce**
All the time, just trying to hide a server.

**Expected behavior**
Hide servers and be able to manage them using the menu from the plugin

**Screenshots**
![serverhide](https://user-images.githubusercontent.com/108319477/202018307-d0a1d362-40e0-4b49-bde0-e8f06e613d81.png)
![sidebar](https://user-images.githubusercontent.com/108319477/202018311-5d483675-5f62-414f-86f9-ac0e8b4b9625.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
NA

**Comment by mwittrien** [comment]
#2047
