### ISSUE TITLE
[BUG] - DiscordRecolor

### ISSUE THREAD

**Issue by shamshitty** [mwittrien/BetterDiscordAddons#2048]
**Describe the bug**
Profile picture disappears once loading an unloaded(?) profile

**To Reproduce**
Enable DiscordRecolor, click on a profile, and wait for the profile to load

**Expected behavior**
The profile loads normally and no elements disappear

**Screenshots**
Without theme
![without_theme](https://user-images.githubusercontent.com/68004605/202259977-8f53c4c1-d2fc-43d3-9972-caef951c5383.gif)

With theme
![with_theme](https://user-images.githubusercontent.com/68004605/202259996-b9a823ac-1acf-4b23-926e-6ea76dee3a9f.gif)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I don't believe this works with offline profiles nor when loading a profile from the member list. I'm not sure how to describe an "unloaded" profile but if you click on a profile and its already online, then its already loaded.

**Comment by shamshitty** [comment]
also, i know you're on vacation DevilBro, so I'm not expecting an immediate answer or anything, i don't mean to bother you ~~but hey at least its not complaining about plugins not working~~

**Comment by mwittrien** [comment]
Doesnt seem to happen to me

**Comment by shamshitty** [comment]
hm, not sure what could be causing it then. i had my plugins folder entirely empty in both gifs so maybe its just a weird caching thing unrelated to bd
