### ISSUE TITLE
[BUG] - ServerDetails doesn't work

### ISSUE THREAD

**Issue by lts20050703** [mwittrien/BetterDiscordAddons#2049]
**Describe the bug**
ServerDetails doesn't work

**To Reproduce**
Download and enable BDFDB and ServerDetails

**Expected behavior**
ServerDetails work

**Screenshots**
<img width="260" alt="image" src="https://user-images.githubusercontent.com/87189679/202422186-549959b7-2ace-46b1-8c2c-1708eeace91f.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/87189679/202422225-7a98bb6a-1897-42f0-a72e-3f3eef83fe18.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/87189679/202422628-75761a22-6319-4c76-b4a1-560bb7926960.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/87189679/202422654-2ff99187-17f1-49fe-ba44-27d795ac9dc2.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/87189679/202422703-52ef234b-31c0-4318-9678-42e6cbf1c341.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/87189679/202422714-c90d8a2b-39f2-4fb9-933b-02850751dade.png">
<img width="154" alt="image" src="https://user-images.githubusercontent.com/87189679/202423030-aeea973b-04be-4724-be64-4316e62f412b.png">

**Discord Build (stable, ptb or canary):**
<img width="146" alt="image" src="https://user-images.githubusercontent.com/87189679/202422379-19a1e920-b588-4d78-953d-20e396fa1a77.png">

**Comment by mwittrien** [comment]
#2047
