### ISSUE TITLE
[BUG] - pluginrepo menu doesn't appear anymore

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2051]
**Describe the bug**
the pluginrepo menu doesn't appear anymore

**To Reproduce**
1. open settings
2. scroll down
3. cannot see the pluginrepo menu

**Expected behavior**
the pluginrepo menu appears in the settings

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/202855831-1e43989a-acf6-4095-9a8c-ea9efd7b150b.png)

**Discord Build (stable, ptb or canary):**
Stable 159692

**Comment by mwittrien** [comment]
#2407
