### ISSUE TITLE
[BUG] - stafftag tags take the full length of the profile popout

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2052]
**Describe the bug**
stafftag tags take the full length of the profile popout

**To Reproduce**
open someone's profile popout and the tag take the full length of the profile popout

**Expected behavior**
it's less long

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/202923391-31680ef5-bd7a-4196-b15c-53d6a9591b24.png)

**Discord Build (stable, ptb or canary):**
Stable 159692

**Comment by mwittrien** [comment]
#2047
