### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by FranHUB2021** [mwittrien/BetterDiscordAddons#2054]
*how is the error*
The bug is that I can't use the plugin, to be more exact, when I press the configuration button it gives me an error that sends me to the console

*How to play* 
Press the configuration button

**Expected behavior**
Change the sounds of discord

**Screenshots**
![Captura de pantalla 2022-11-21 015222](https://user-images.githubusercontent.com/96084047/202968407-d46340bf-1f83-48b6-838b-b2a137a223e7.png)

**Discord Build**
Stable
**Additional context**

**Comment by hexisXz** [comment]
same

**Comment by hexisXz** [comment]
i actually saw this error before looking at github

**Comment by mwittrien** [comment]
#2047
