### ISSUE TITLE
[IMPROVEMENT] - PinDMs

### ISSUE THREAD

**Issue by ReikoTigon** [mwittrien/BetterDiscordAddons#2057]
**Describe the solution you'd like**
It would be amazing if you could reorder the Pin Categories

**Describe alternatives you've considered**
I tried drag and dropping them but it didn't change the order for me.
Other workaround would be creting them in order but I already have categories and would have to redo them

**Comment by mwittrien** [comment]
you can already reorder them by dragging them on top of each other
