### ISSUE TITLE
[IMPROVEMENT] - EditUsers

### ISSUE THREAD

**Issue by legacy1477** [mwittrien/BetterDiscordAddons#2059]
**Describe the solution you'd like**
Please allow pasting base64 image data directly instead of just urls or loading avatars/headers locally.

**Additional context**
I've tried manually editing the plugin config and pasting base64 image data and it works without issue. Seems only logical for this to be allowed. I'd like to store stuff locally instead directly uploading it anywhere.

**Comment by mwittrien** [comment]
added

youll need to redownload the plugin manually since i didnt change the version number for this
