### ISSUE TITLE
Char Counter - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Klicck** [mwittrien/BetterDiscordAddons#206]
The numbers are cut off of the bottom of my screen
![Screen Shot 2019-05-14 at 8 49 44 pm](https://user-images.githubusercontent.com/42634676/57692316-d5bc5f00-7689-11e9-80de-9b21b334581d.png)

**Comment by jack652** [comment]
that's becasue of your theme

**Comment by mwittrien** [comment]
Yeah your themes fault, tell your theme dev to fix it ot fix it yourself
