### ISSUE TITLE
[BUG] - PluginRepo

### ISSUE THREAD

**Issue by Zaphodjoe** [mwittrien/BetterDiscordAddons#2060]
**Describe the bug**
When all the plugins broke over a month ago and we re enabled them all, I noticed a bunch of channel lag especially when discord started and the first time you click on each channel it was sluggish then after the first time it was faster but still not like it used to be. Then earlier this month when all your plugins stopped working the lag went away. Today when the update fixed them I noticed the lag came back. I posted on the main discord server about it and someone else noticed the same thing, we found the only plugin we had in common of yours was Plugin Repo. When I disable that the lag goes away. I saw some closed thread about lag from October also when the major changes occurred and you closed it saying plugins will cause lag. I just wanted to update you to let you know, specifically Plugin Repo causes considerable channel change lag especially when discord first starts. This didn't happen before the huge discord update and mod rewrites a few months ago but seemed to come on after. I disabled plugin repo for now since that seems to be the one causing it and the lag is now gone. Hopefully you can find a way to speed that one up a little? or is this just the way that plugin works and there is no way to fix it?

**To Reproduce**
Load Plugin Repo

**Expected behavior**
Not so lagy when changing channels

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable current updated version

**Additional context**
Thanks for all your work, I really enjoy all your plugins!

**Comment by Zaphodjoe** [comment]
I think bug report 2062 is the same thing, what I am calling sluggishness or lag is the page going blank for a second before loading kind of. I was assuming it was lag from the page loading back in, the other guy is assuming its data loss and reported it with BDFDB but in his report he said he didn't know if it was that or PluginRepo. I think its the same issue I am reporting.

**Comment by mwittrien** [comment]
#2073
