### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by sssHpion007** [mwittrien/BetterDiscordAddons#2064]
**Describe the bug**
Does not work

**To Reproduce**
I use a translator of incoming messages into Russian. Nothing happens.

**Expected behavior**
I was expecting a translation from English to Russian

**Screenshots**
-

**Discord Build (stable, ptb or canary):**
Stable 159692 (79ae406)

**Additional context**
-

**Comment by mwittrien** [comment]
Yes it works
