### ISSUE TITLE
Translator is not working properly

### ISSUE THREAD

**Issue by key1202** [mwittrien/BetterDiscordAddons#2067]
**Describe the bug**
Translator cannot be used normally, and it keeps prompting that the translation failed, and sometimes after clicking the translation, it will show that the current channel does not have permission to send messages

**To Reproduce**
It started yesterday, but it was able to translate normally last night, but it was a bit slow, but it is not working today, I tried many times
I hope the translation plugin can be used normally
**Screenshots**
![image](https://user-images.githubusercontent.com/112763995/203610625-eb3f7b6a-b9b8-49ab-b952-7c3eb4816557.png)
![image](https://user-images.githubusercontent.com/112763995/203610681-6f9c486b-27e4-4fc2-860c-99247c7f7a66.png)
![image](https://user-images.githubusercontent.com/112763995/203610697-e922182a-701b-4575-8573-331337cfd03e.png)
![im
![image](https://user-images.githubusercontent.com/112763995/203610946-9aa28d6c-911e-4b3f-b0db-fb67106a8f20.png)
age](https://user-images.githubusercontent.com/112763995/203610715-ee3c946d-802c-44c3-8a3a-ae4504ed4c4b.png)

![image](https://user-images.githubusercontent.com/112763995/203610893-60f8692f-35ba-4b85-8964-68b805d9c2cb.png)
![image](https://user-images.githubusercontent.com/112763995/203611033-d7ca39be-df88-4a7e-8812-d37662c46ed5.png)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
![image](https://user-images.githubusercontent.com/112763995/203611187-71da3837-835d-4ab6-b634-068c8d5d00f4.png)
![image](https://user-images.githubusercontent.com/112763995/203611386-a82466e3-b24b-44c3-8c3d-d9f0e8d072d1.png)
![image](https://user-images.githubusercontent.com/112763995/203614468-c63f13b4-60fe-414a-929b-5d4996ccafce.png)

**Additional context**
I tried a lot of methods but it didn’t work. My vpn was originally from Japan, but it didn’t work. Then I switched to the United States, but it still didn’t work. I used a lot of positions before this.The above screenshots are all translators, and there is only one translation plug-in. The discord version is the latest version.try setting vpn to united states
then ctrl+r reload and test the the translators.Hope that can solve my problem, thank you very much！！

**Comment by key1202** [comment]
I updated the latest translator to 2.4.7 today and used papago, but it doesn't work
![image](https://user-images.githubusercontent.com/112763995/203690914-5c077dd8-e750-4766-8b8c-36d171db4ba8.png)

**Comment by mwittrien** [comment]
You need a working api key for papago to work

**Comment by key1202** [comment]
Is Google Translate not working?I don't know how to use papago api key
