### ISSUE TITLE
[IMPROVEMENT] - About Translator's Google Translate no network problem

### ISSUE THREAD

**Issue by AIDA64S** [mwittrien/BetterDiscordAddons#2070]
Regarding the problem that Translator’s Google Translate does not have a network, I think the author has misunderstood what we mean. The national gateway in mainland China has a firewall. Google Translate was directly accessible in mainland China before, but not long ago, it was not possible to directly access Google Translate in mainland China. (Because of the existence of the national gateway firewall and Google Translate is now on the blacklist of the firewall), the Google Translate function of Translator cannot be used in mainland China. The only solution at present is to provide a place where you can set your own proxy (my The proxy server is located in Singapore and can access all Google services, and I can 100% confirm that Translator will not send a request to the Google Translate API server through the Http/Https/Socks proxy, causing the connection timeout of this request)

I implore the author to provide a solution: set a setting item in the plug-in, and you can enter the user's own proxy server address and port, user name and password. After setting the proxy, the plug-in sends Http/Https requests to access through this proxy, which can guarantee the solution This problem (if a mainland Chinese user can access Discord, then he/she must have his/her own proxy server)

**Comment by mwittrien** [comment]
No
