### ISSUE TITLE
[BUG] - Plugin/ThemeRepo

### ISSUE THREAD

**Issue by NarikoNep** [mwittrien/BetterDiscordAddons#2071]
**Describe the bug**
I get a crash when opening the settings randomly after a certain amount of time.

**To Reproduce**
Wait for a while, then open settings.

**Expected behavior**
The settings should open without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/97272732/204065371-f5edd501-01e6-44b5-8759-c3edef359dcb.png)

**Discord Build (stable, ptb or canary):**
Discord Stable 160645

**Additional context**
I also get random crashes without opening settings, This crash is a hard crash and I can't get a console error of it.

**Comment by mwittrien** [comment]
redownload them
