### ISSUE TITLE
[BUG] - ShowBadgesinChat unexpected error

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2072]
**Describe the bug**
fatal error if you want using the settings in the plugin tab

**Screenshot**
![image](https://user-images.githubusercontent.com/25110093/204073589-fd0a3e89-251b-4a3a-973e-e6ebd58a1019.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/204073603-02d09504-85fa-42c3-966b-45f1840a94ae.png)
also on Stable the same

**Comment by mwittrien** [comment]
Fixed, reload Discord
