### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities, ignore discord zoom feature

### ISSUE THREAD

**Issue by Thespikedballofdoom** [mwittrien/BetterDiscordAddons#2075]
**Describe the solution you'd like**
Any discord zoom level in appearance that isn't 100% kills the clarity of small pixel images. I'd like an option to make it so that this rescaling does not apply to images, both in chat and in the image view popup.

**Describe alternatives you've considered**
Betterimageviewer. It's dead and probably never coming back.

**Additional context**
![image](https://user-images.githubusercontent.com/43627353/204118947-8100512c-4f76-4157-b104-caf20ddd6a5e.png)

**Comment by mwittrien** [comment]
sounds like somethind discord should implement themselves
IamgeUtilities is already as bloated as the plugin should max be, so i rather not add new features to it
