### ISSUE TITLE
[BUG] - SERVER COUNTER

### ISSUE THREAD

**Issue by heyyovico** [mwittrien/BetterDiscordAddons#2077]
**Describe the bug**
Server counter is off in count by 1 - I am already at max 200 servers (and I am getting the discord prompt to leave server when trying to join a new one), but Server Counter still shows 199

**Discord Build (stable, ptb or canary):**
Stable

![image](https://user-images.githubusercontent.com/119275312/204187419-8eb54210-df3e-4a50-b3fb-f1c80e070975.png)

**Comment by mwittrien** [comment]
Then its Discords fault
