### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by leellleeell** [mwittrien/BetterDiscordAddons#2081]
Description of bug:
ImageUtilities is not remembering the last folder when saving an image, this used to work normally

Reproduce:
1) Save an image anywhere that isn't the default downloads folder
2) Click save image as, it will take you to the default downloads folder

Expected Behavior:
The download location is changed to the last folder you saved to

Screenshots
N/A

Discord Build
Stable

**Comment by mwittrien** [comment]
#2017
