### ISSUE TITLE
[BUG] - ServerFolders React Component Error

### ISSUE THREAD

**Issue by q0wbx** [mwittrien/BetterDiscordAddons#2083]
**Describe the bug**
When creating a folder, an error pops up.

**To Reproduce**
the error occurs when a folder is created.

**Expected behavior**
Отключил все плагины, ошибка вылезает всё ровно.

**Screenshots**
![2022-11-29_17-57-47](https://user-images.githubusercontent.com/119417119/204523110-0f6bb046-098f-41a2-8114-3a1a5b0aacf4.png)

**Discord Build (stable, ptb or canary):**
PTB

**Additional context**
Other answers with this error do not help.

**Comment by mwittrien** [comment]
#2082
