### ISSUE TITLE
[BUG] - RemoveBlockedMessages\BetterFriendList

### ISSUE THREAD

**Issue by newaccountpleaseignore** [mwittrien/BetterDiscordAddons#2085]
**Describe the bug**
After turning on the plugins (can be only one of them) makes discord not close properly.

**To Reproduce**
Turn on RemoveBlockedMessages or BetterFriendList
Close discord from the system tray.
Reopen discord.
Close discord again after the plugins loaded.
Open task manager.
Check if discord is still open in the background

**Expected behavior**
Discord should not stay open and not use 30% of the cpu.

**Screenshots**
https://prnt.sc/lP697zzMzwqt - Bug

**Discord Build (stable, ptb or canary):**
Stable 161150 (6cd3d12)

**Additional context**
If you don't have any friends/blocked users then the bug doesn't happen.

**Comment by mwittrien** [comment]
#2073
