### ISSUE TITLE
[BUG] - Lastmessage last version

### ISSUE THREAD

**Issue by Soulivan71** [mwittrien/BetterDiscordAddons#2088]
**Describe the bug**
The new thing jump to message (last one doesn't work)

**To Reproduce**
Open popout in dm / in a server 
Clic on "# x.x.xx;"
In dm I have a little circle loading infinite
And If I try on a server no loading circle

**Screenshots**
![image](https://user-images.githubusercontent.com/36502190/204798029-f324d176-05d8-4780-8103-061a0c0e6986.png)

**Discord Build (stable, ptb or canary):**
Ptb 161313 (b77269f) Host 1.0.1020 (27412) Windows 10 64-Bit (10.0.19045)

**Comment by Soulivan71** [comment]
Ok I make some test and I can see that last message just load the last message where u are. Not checking every servers.

**Comment by mwittrien** [comment]
Obviously

**Comment by Soulivan71** [comment]
But the new thing doesn't work for me Im not jumping on any message

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload Discord

**Comment by Soulivan71** [comment]
Ok thx it's fine now
