### ISSUE TITLE
[BUG] - FriendNotifications/ServerCounter/ReadAllNotificationsButton

### ISSUE THREAD

**Issue by EPLOGx** [mwittrien/BetterDiscordAddons#2091]
**Describe the bug**
All plugins that make something under the home button make other plugins from [LoneWee](https://github.com/Tharki-God) not work anymore. Here you can find the [issue](https://github.com/Tharki-God/BetterDiscordPlugins/issues/62) from him.

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Thats LoneWee's problem

**Comment by Tharki-God** [comment]
> Thats LoneWee's problem

sounds like a "you problem" and its LoneWeeb~
