### ISSUE TITLE
[BUG] - ChatAliases Still Not Working after 12/1 Update

### ISSUE THREAD

**Issue by WiseEXE** [mwittrien/BetterDiscordAddons#2092]
**Describe the bug**
Addon still does not work. Aliases can be made, but won't run.

**To Reproduce**
Make an alias

**Expected behavior**
For example take Jockie Music bot's play command "m!play", if I set to change "play" to the said command nothing happens and vice versa.

**Screenshots**
Screen Showing Alias Made
![image](https://user-images.githubusercontent.com/105170549/205125475-0a908a30-b393-40a0-92c8-328214890ea2.png)

Screenshot showing nothing is being done with the command.
![image](https://user-images.githubusercontent.com/105170549/205125680-7bb3a09f-065b-40f2-8621-a944974ff96d.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I've tried swapping the placement of the commands in your addon but to no avail. Can only come to the conclusion the addon is still busted.

Also for a side not, when it comes to readability, I feel like the Add an Alias section can be reworded for clarity purposes. I think it would be alot easier for the end user to comprehend what they are doing if the **REPLACE** section read "Command to Replace" and the **WITH** section "New Alias", or something along those lines. Hope this didn't come off as rude, just as a native English speaker, the phrasing of that section can come off as vague.

**Comment by mwittrien** [comment]
screenshot the settings area in the settings
