### ISSUE TITLE
[BUG] - ReadAllNotifications Perfomance Issue

### ISSUE THREAD

**Issue by PixelGuy123** [mwittrien/BetterDiscordAddons#2097]
**Describe the bug**
After starting Discord, on the first time you click the "Read All" button, Discord lags a lot before the plugin actually does it's job (cleaning all notifications), but after that, it does not lag anymore, only when pressing the button after the first Discord boot

**To Reproduce**
Start Discord, and click _that_ button

**Expected behavior**
Not lag

**Screenshots**
_Screenshot of a frozen screen lmao_

**Discord Build (stable, ptb or canary):**
Discord Stable 161884

**Additional context**
Nope

**Comment by mwittrien** [comment]
Discord forces the server list to refresh once if any changes to it are done qnd yiu try to interact with it, thats what looks like lags to you

Cant be fixed

**Comment by PixelGuy123** [comment]
Wait, but instead of only refreshing after any interaction, is it possible to force refresh the list on the start instead of letting Discord do that only at interaction?

**Comment by PixelGuy123** [comment]
OH and also, I know it refreshes after the first interaction, but It didn't lag that much before, now it literally freezes my screen
