### ISSUE TITLE
ServerFolders conflicts with EditServers

### ISSUE THREAD

**Issue by Drflash55** [mwittrien/BetterDiscordAddons#210]
Issue: When a server has an edited icon, the pop-up text for the server name does not appear when inside a server folder. If taken out, the issue is fixed.

Outside Folder: 
![image](https://user-images.githubusercontent.com/13694448/58476514-eefbeb80-811e-11e9-99b0-59f09cedde44.png)

Inside Folder:
![image](https://user-images.githubusercontent.com/13694448/58476558-1652b880-811f-11e9-8e6b-23d2fd25627b.png)

Restarting the plugins does not fix the issue.

Versions: EditServers V2.0.0 | ServerFolders V6.2.6

**Comment by mwittrien** [comment]
should be fixed by updating EditServers
