### ISSUE TITLE
[BUG] - ImageUtilities save file as no longer saves the file

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2103]
**Describe the bug**
the "save file as" context menu button no longer saves the file

**To Reproduce**
1. right click on image or video file on discord
2. click on save as folder

**Expected behavior**
it saves the files in the designated folder

**Discord Build (stable, ptb or canary):**
Stable 162216

**Comment by mwittrien** [comment]
Take a video example of what you mean
