### ISSUE TITLE
[BUG] - FriendNotifications says "There was an unexpected error. Click to open console for more details"

### ISSUE THREAD

**Issue by jizzyjdog** [mwittrien/BetterDiscordAddons#2109]
**Describe the bug**
It says "There was an unexpected error. Click to open console for more details" when clicking the settings gear

**To Reproduce**
Clicking the setting gear icon

**Expected behavior**
I expected to be able to change the settings

**Screenshots**
![image](https://user-images.githubusercontent.com/109762133/206008528-84cb0fbe-c4a5-484f-b10c-633a3547a058.png)
![image](https://user-images.githubusercontent.com/109762133/206008578-ba0a18b2-49cf-4b77-bb6b-140f2b595c40.png)

**Discord Build (stable, ptb or canary):**
stable

edit: needed to update BD, fixed

**Comment by mwittrien** [comment]
743 errors, you got some mayor issues on your side and i doubt the plugin is the issue
