### ISSUE TITLE
SpotifyControls no icons

### ISSUE THREAD

**Issue by nikitaed** [mwittrien/BetterDiscordAddons#2111]
![image](https://user-images.githubusercontent.com/74512154/206374155-184c4fe9-7ff9-4e43-a0e6-2e02a2f37c09.png)

I installed font from the res folder, set the original theme, but it didn't work

**Comment by PecorinoDev** [comment]
Can confirm I have the same issue

**Comment by mwittrien** [comment]
delete 0BDFDB.data.json and reload discord

**Comment by nikitaed** [comment]
> delete 0BDFDB.data.json and reload discord

Same. Does not work
