### ISSUE TITLE
EditUsers not working

### ISSUE THREAD

**Issue by ShawnSigma** [mwittrien/BetterDiscordAddons#2113]
Full disclosure, I am not a programmer and I have no idea what this stuff I saw is

EditUsers is not working anymore. Plugin Repo tells me to update it and once I do, this pops up:
![image](https://user-images.githubusercontent.com/54847049/206586655-01cc98b5-e929-4d03-921a-7cec4438092f.png)

After the popup, the plugin is just quietly deleted and the update notification lingers on the screen, with the update button now doing nothing. None of your other plugins I have are giving me this error either, it's just EditUsers. Replacing the .js file with the one from the 30th of November makes it work perfectly again.
I of course do not have another plugin loaded called EditUsers, so I dunno what this is referring to. Any idea what happened?

I saw that the plugin was updated about six hours ago, and it worked fine before that, so it's probably this update causing this somehow

**Comment by mwittrien** [comment]
Delete EditUsers.plugin.js and redowload it
