### ISSUE TITLE
[BUG] - Edit servers 

### ISSUE THREAD

**Issue by IllidanStormrag3** [mwittrien/BetterDiscordAddons#2114]
**Describe the bug**
Cannot open threads with plugin active

**To Reproduce**
activate the plugin and try to open a thread, it simply doesn't respond

**Expected behavior**
threads should be able to be opened

**Screenshots**
![image](https://user-images.githubusercontent.com/79320096/206600666-6a9acfc6-7d4a-4ee1-97a6-fe5d6274c982.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
I've deleted the 0bdfsdb.config.json file and also deleted the plugin files and reinstalled. neither method fixed the issue

**Comment by mwittrien** [comment]
The issue is EditChannels and that issue has already been fixed

**Comment by IllidanStormrag3** [comment]
Ah, typo in the title; sorry I realized it was edit channels, I've got 4.5.0 ver of edit channels installed but the issue is still happening.

**Comment by IllidanStormrag3** [comment]
https://streamable.com/u4ha5s video proof that it doesn't work when plugin is active.
