### ISSUE TITLE
[BUG] - BetterFriendList

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2118]
**Describe the bug**
it resets all time the friend list when i want scrolling

**To Reproduce**
try to scroll down it gets random reset to the top

**Expected behavior**
that i can scroll normal and it dont jump back to the top

**Video**
https://streamable.com/uub246

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/206793160-2137e29d-aebe-46e9-8dc5-c3fa8a2293f0.png)

additional context:
its better to record it instat of just describe it to know what i mean

**Comment by adrianmarinwork** [comment]
Hello, I would like to take care of this issue!
