### ISSUE TITLE
[IMPROVEMENT] - Add i18n to all plugins

### ISSUE THREAD

**Issue by vincentwang0905** [mwittrien/BetterDiscordAddons#2120]
**Describe the solution you'd like**
Auto get bd client lang to change plugins lang

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mwittrien** [comment]
Plugins already are being translated in most places?

**Comment by vincentwang0905** [comment]
wdym?
Currently some plugins start i18n
I hope you can also join in making i18n
I can help translate Traditional Chinese and Simplified Chinese

**Comment by mwittrien** [comment]
Like i said my plugins are already translated
