### ISSUE TITLE
[BUG] - Plugin Repo not loading

### ISSUE THREAD

**Issue by rp1231** [mwittrien/BetterDiscordAddons#2126]
**Describe the bug**
Plugin repo is not loading

**To Reproduce**
Click on the get updates button on the plugin repo tab.

**Expected behavior**
Plugins load

**Screenshots**
<img width="844" alt="Screenshot_20221213_054757" src="https://user-images.githubusercontent.com/47380919/207316076-a8e18fb7-269f-4d07-bb84-7dd227f2075f.png">

Gets stuck on loading and then blank page.

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Issue with your Internet
