### ISSUE TITLE
RoleMember is broaking

### ISSUE THREAD

**Issue by AndreZila01** [mwittrien/BetterDiscordAddons#2128]
**Describe the bug**
When i do a left click on server icon, discord return a error: "Discord stop working", i try disable all plugins about rolesmembers and found the problem, the plugin RoleMembers have a error, at the moment are in version 0.1.19.
I think this bug happend after the update of BetterDiscord 1.8.3

**Screenshots**
![image](https://user-images.githubusercontent.com/56931353/207571848-57789095-500d-49e5-8e14-3df48dfb4ec4.png)

**Comment by mwittrien** [comment]
Not my plugin
