### ISSUE TITLE
[BUG] - ImageUtilities - Still occuring - Nothing happens when attempting to save images/videos, due to CORS

### ISSUE THREAD

**Issue by noopoon** [mwittrien/BetterDiscordAddons#2131]
https://github.com/mwittrien/BetterDiscordAddons/issues/2130 was closed as fixed, but it appears to still be happening in 5.0.4 (feel free to delete this, just couldn't re-open 2130). Tried with the same video and got the same result

Additionally, Fairy#6688 reported that the following twitter video resulted in an "image could not be saved" error, this may or may not be related: https://twitter.com/iseoksjin/status/1603470677583007756

**Comment by Aaeeschylus** [comment]
Would like to add on to the end, any twitter video or mp4 with an embedded version I attempt to save gives the same "Image could not be saved" error.

**Comment by mwittrien** [comment]
> Would like to add on to the end, any twitter video or mp4 with an embedded version I attempt to save gives the same "Image could not be saved" error.

twitter videos can't be downloaded throug the plugin, because they aren't loaded until they are started and when they are started they are iframes inside discords app window, which can not be accessed by the plugin

**Comment by mwittrien** [comment]
> #2130 was closed as fixed, but it appears to still be happening in 5.0.4 (feel free to delete this, just couldn't re-open 2130). Tried with the same video and got the same result

I tested it with the video `https://cdn.discordapp.com/attachments/410787888507256844/1052752659955847259/Noita_2022.12.09_-_18.55.25.86.DVR_.mp4` and it works fine for me

**Comment by noopoon** [comment]
@mwittrien 

> I tested it with the video https://cdn.discordapp.com/attachments/410787888507256844/1052752659955847259/Noita_2022.12.09_-_18.55.25.86.DVR_.mp4 and it works fine for me

As in uploading it or pasting the link? Pasting the link also worked for me, but trying to save after uploading it was broken in 5.0.4 for me and same with 5.0.6:

https://discord.com/channels/410787888507256842/410787888507256844/1052752660022951968
![image](https://user-images.githubusercontent.com/113561927/208161458-54bac37a-5c91-403a-9a92-7c05f2665fc3.png)

Just took the above screenshot. Made sure to ctrl-r after updating everything
