### ISSUE TITLE
[BUG] - Edit\w* Performance

### ISSUE THREAD

**Issue by Crypt0Beaver** [mwittrien/BetterDiscordAddons#2136]
**Describe the bug**
It took me some time to pinpoint which plugins this was coming from, but it seems that the EditXXX plugins have a higher than usual impact on performances. It varies between the 4 of them, but when enabling them all, it adds up, on my not-too-slow-machine, 3-4s load time on every server switch (compared to a total 1s usually with the other ~100 plugins enabled).

**Discord Build (stable, ptb or canary):**
Tested on PTB and Stable, can't get Canary to work with BD yet, even with latest version.

**Comment by mwittrien** [comment]
Well they have to process a lot of stuff to change everything everywhere

Its unavoidable
