### ISSUE TITLE
[BUG] - ServerFolders/ServerCounter - First click ignored

### ISSUE THREAD

**Issue by Crypt0Beaver** [mwittrien/BetterDiscordAddons#2137]
**Describe the bug**
Took a little bit of time to pinpoint which plugin(s) did that too. 
The issue happens with plugins modifying the server list, so ServerFolders and ServerCounter.
After the plugin is loaded, the first time we click on a server in the list, the click is ignored. We're waiting thinking it might take time, but nothing happens. We have to click a second time. Further clicks seem ok.

**Comment by mwittrien** [comment]
Unfixable
