### ISSUE TITLE
[BUG] - Plugin Repo - Cant update plugins

### ISSUE THREAD

**Issue by Tetrax-10** [mwittrien/BetterDiscordAddons#2138]
**Describe the bug**
Cant update plugins

**To Reproduce**
click update button

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75513645/208285123-ef721084-1f29-4b54-bf1e-3c716b3dcc2b.png)
![image](https://user-images.githubusercontent.com/75513645/208285127-fbf4afcb-4b3b-4c46-a3bd-84a621cf0abc.png)

**Discord Build (stable, ptb or canary):**
latest prob, idk where to see that

**Additional context**

**Comment by mwittrien** [comment]
Thats not a banner created by PluginRepo

**Comment by Tetrax-10** [comment]
am new to bd. so where can i post this issue? is that from core bd?

**Comment by mwittrien** [comment]
https://github.com/rauenzi/BDPluginLibrary
