### ISSUE TITLE
[IMPROVEMENT] - ChatFilter tidiness and distractions/annoyances

### ISSUE THREAD

**Issue by Roszek-Dragon** [mwittrien/BetterDiscordAddons#2139]
**Describe the solution you'd like**
This plugin is a great lifesaver but there is something important missing. An option to hide the actual effects of the censorship.
Look at this example:
![scr_1671526409](https://user-images.githubusercontent.com/89735250/208626660-ef6c9f8d-41cb-47e8-b299-7f32922b0a78.jpg)

I chose to replace the offensive word with nothing, not even a space, simply nothing, but it still shows a extra space where the racist word was located, and an annoying (censored) label at the end. I get why some people would want this feature to know if something filthy has been censored, but in my case, I'd love to simply get rid of it altogether.

Here is an example of what it would look like:

![scr_16715264092](https://user-images.githubusercontent.com/89735250/208627442-71ef9dc9-1298-4c63-8381-c7f92fa873bd.jpg)

**Describe alternatives you've considered**
Nothing can do much about it as I do not know coding.

**Comment by mwittrien** [comment]
You can hide the censored/blocked stamp with css

The double space youll have to deal with
