### ISSUE TITLE
[BUG] - CompleteTimestamps

### ISSUE THREAD

**Issue by C4J3** [mwittrien/BetterDiscordAddons#2142]
**Describe the bug**
Time display seems to completely bug out when installed alongside [BrandonXLF's Relative Timestamps](https://github.com/BrandonXLF/BetterDiscordPlugins/tree/main/src/RelativeTimestamps) plugin.

**To Reproduce**
Install both plugins and appropriate dependencies
Make sure both are enabled
Reload to make sure everything is loaded

Should see a standard time stamp immediately followed by the Complete Timestamps timestamp. Disabling then re-enabling both seems to resolve the issue (May have to hover over the timestamps to get the relative ones to show.)

**Expected behavior**
The Complete Timestamps timestamp should show followed by the relative one and no default one should be seen.

**Screenshots**
Working:

![Working](https://user-images.githubusercontent.com/13005453/209028791-8dbcd45c-42f9-487d-bdcd-52271a381197.png)

Broken:

![Discord_6I3ZcaOlXe](https://user-images.githubusercontent.com/13005453/209028931-b5294903-874b-4f35-9a97-28b6fdcea2e5.png)

**Discord Build (stable, ptb or canary):**
Stable

![Discord_aprjMGQ1if](https://user-images.githubusercontent.com/13005453/209028999-9d8f22d0-3da7-4f6e-a888-895507982cfa.png)

**Additional context**
I'm not sure if this is Complete or Relative that's causing the issue but I think it's this one. If not let me know and I'll move the issue post to them.

**Comment by mwittrien** [comment]
They simply dont work together

CompleteTimestamps also lets you add relative timestamps when configured in the plugin settings, so no point in using both
