### ISSUE TITLE
[IMPROVEMENT] - Add Option To Not Queue Desktop Notifications

### ISSUE THREAD

**Issue by spotandjake** [mwittrien/BetterDiscordAddons#2143]
When using this addon with FriendActivityNotifications if i dont dimiss the friend online notification the notification queue gets filed up and then when i go and dismiss them later i get a ton of notifications each time i close the notificaiton. I would be nice if i could just dissable the queueing feature and the notifications could just come in and then i could clear them all at once using my operating systems clear notification feature.

**Comment by mwittrien** [comment]
They would still be queued internally even if i dont queue them
