### ISSUE TITLE
[IMPROVEMENT] - OpenSteamLinksInApp opening other apps like Spotify or Notion

### ISSUE THREAD

**Issue by Davoleo** [mwittrien/BetterDiscordAddons#2145]
**Describe the solution you'd like**
This plugin is very specific but it could be renamed to `OpenLinksInApps` and used to work with other platforms that use custom protocols like Spotify and Notion.

**Additional context**
I've taken a look at the code and it's also fairly extensible, for example there is already an object containing an array of platform links [currenctly just 1 array with steam links], should be quite easy to add a new platform there and work towards building a relevant function to handle link opening
I could be taking on implementing these features in a PR, but no promise I'm fairly busy recently...

**Comment by mwittrien** [comment]
Not possible since those dont have a file explorer protocol

**Comment by Davoleo** [comment]
Actually, I'm sure spotify has it:
for example try opening this link somewhere on your pc if you have the desktop app installed: `spotify:album:0vptjQ8HaGWrQjCOIXTM2G`
Original web link: https://open.spotify.com/album/0vptjQ8HaGWrQjCOIXTM2G

And I've tested right now that even notion has it, example public page I've created:
https://www.notion.so/davoleo/Open-Source-Licences-b92f822172e84137ac0e50f6e4ac1f0a
you just need to replace https with notion in this way for it to be considered a custom protocol uri
`notion://www.notion.so/davoleo/Open-Source-Licences-b92f822172e84137ac0e50f6e4ac1f0a`
