### ISSUE TITLE
[BUG] - ReadAllNotification unable to

### ISSUE THREAD

**Issue by slh-git** [mwittrien/BetterDiscordAddons#2148]
**Describe the bug**
Unable to open setting menu for 

**To Reproduce**
When does the bug occur?
- When clicking on the gear in the plugin tab 
![image](https://user-images.githubusercontent.com/70451183/210269965-64033c43-b534-4fea-be06-e980d6ed7174.png)

**Expected behavior**
A setting UI of plugin to pop up. 

**Screenshots**
UI error message 
![image](https://user-images.githubusercontent.com/70451183/210269858-25d006ec-3c06-42fd-9e94-312da3ff9a66.png)

**Discord Build (stable, ptb or canary):**
Which build of Discord? PTB 

**Additional context**
Dev console message
![image](https://user-images.githubusercontent.com/70451183/210269805-e73d02b9-be04-43ec-9e98-f4d8ace910b4.png)

**Comment by mwittrien** [comment]
delete 0BDFDB.data.json and reload discord
