### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities - Create folder if not existing

### ISSUE THREAD

**Issue by Rakambda** [mwittrien/BetterDiscordAddons#2150]
**Describe the solution you'd like**
Currently I have several "Download Location" set up to easily save some images to various folders. However, sometimes the target directory doesn't exist anymore for some reasons and therefore the download fails without any explicit notification (just "Failed to download xxx).

Would be nice if there could be an option to automatically create the parent folder(s) if it doesn't already exists instead of failing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mwittrien** [comment]
nah, you should keep track of your file system yourself, folders dont magically vanish
