### ISSUE TITLE
[BUG] - FriendNotifications not sending subsequent notifications (macOS!)

### ISSUE THREAD

**Issue by Wever1985** [mwittrien/BetterDiscordAddons#2151]
**Describe the bug**
When _FriendNotifications_ is configured to send Desktop notifications and Discord is set to send notifications as **'Banners'** in macOS settings, only the first notification is actually sent. Subsequent notifications never show up.
Yet when Discord is set in macOS settings to send notifications as **'Alerts'**, all notifications are sent as expected (once the previous one is dismissed).

Clarification for macOS: 'Banners' are notifications that appear on the screen and disappear after a while. 'Alerts' are notifications that stay on the screen until you dismiss them.

**To Reproduce**
Configure the _FriendNotifications_ plugin to send Desktop alerts in macOS. Make sure Discord sends notifications as 'Banners'.

**Expected behavior**
All notifications should be displayed even when Discord is sending notifications as 'Banners'.

**System:**
macOS 12.6.2
Discord Build Stable 165943
FriendNotifications v1.8.7

**Comment by Wever1985** [comment]
Has this issue been fixed or was it abandoned? The notification behavior seems to be unchanged as of now.

**Comment by mwittrien** [comment]
There is no way for me to test this and i hope ita fixed

**Comment by Wever1985** [comment]
> There is no way for me to test this and i hope ita fixed

I figured as much. Thanks for the reply though.
Unfortunately, the behavior is still unchanged (Core v1.9.1, FriendNotifications v1.9.0).
