### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by shawny43** [mwittrien/BetterDiscordAddons#2153]
**Describe the solution you'd like**
Microsoft Emoji with 3D design seem execptionnal. This could being included.

**Describe alternatives you've considered**
This could implement more flavours to emoji themes that could be able to toggle 3D/2D from Microsoft emoji templates.

**Additional context**
Github: https://github.com/microsoft/fluentui-emoji

**Comment by mwittrien** [comment]
They arent on emojipedia
