### ISSUE TITLE
[BUG] - Friend Notifications

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [mwittrien/BetterDiscordAddons#2156]
**Describe the bug**
When a friend logs on only the first login is shown and the logoff is never shown. If they are logged in on desktop and login on mobile the mobile is not shown and if they log off desktop there is no log off of the desktop shown. Also no logoff notifications are being shown .

**To Reproduce**
Have a friend added in the plugin settings. They login,they login on another device or they log off.

**Expected behavior**
Their online/offline/device statuses should be notified.

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
This is how the plugin used to work for a very long time many months ago,though i cannot remember exactly when. I distinctly remember offline notifications being shown and now after many weeks there are no offline notifications at all though i can watch added friends log on and off freely in the memberlist with no notifications

**Comment by Wever1985** [comment]
Are you on macOS? Sounds very similar to my issue #2151

**Comment by ResidentSpaceDragon** [comment]
> Are you on macOS? Sounds very similar to my issue #2151

No, Linux, i am not using desktop notifications either,just within discord

**Comment by mwittrien** [comment]
Logins only show on status change

if they login on PC and then login on mobile the status doesn't change because they are still online

Login: offline -> online

In your case the user was already online on another device, that's why the plugin doesnt recognize the login on another device as a status change

this behaviour is intended
