### ISSUE TITLE
[BUG] - (DisplayServersAsChannels + ImageUtilities) - Plugin Conflict Causes Unprompted Page Scrolling

### ISSUE THREAD

**Issue by Oxiriarkana** [mwittrien/BetterDiscordAddons#2159]
**Describe the bug**
Channel and DM pages will slightly scroll up if a user clicks out of Discord.
In some cases, the page will no longer scroll with new messages as well.

**To Reproduce**
-Install both the **ImageUtilities** and the **DisplayServersAsChannels** plugins
-Go to any DM or Channel, and send a message
-Click out of Discord (either onto your desktop, or a different program)

**Expected behavior**
The page should remain at its current location

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable 167888 (660afa5)

**Additional context**
I have only observed this behavior between DisplayServersAsChannels and ImageUtilities
While it is a rather minor issue, it is quite annoying. I hope, since this appears to be a bug between two of DevilBro's plugins, that this can be resolved.

**Comment by mwittrien** [comment]
Can't replicate this

try taking a video of your issue

**Comment by Oxiriarkana** [comment]
I can no longer replicate it myself.
When I first noticed the issue, I ended up turning off ImageUtilities, so I wasn't able to track when the issue had stopped occurring.
If I had to guess, it might have been a driver or background program interfering with Discord and the issue likely cleared when my PC was rebooted.

Sorry!
