### ISSUE TITLE
Mentions in a server folder don't show until force updated

### ISSUE THREAD

**Issue by d3athrow** [mwittrien/BetterDiscordAddons#216]
The notification icon does not update on the server icon upon getting a mention or after a mention has been viewed until updated manually by collapsing and re-opening a server folder.
[example](http://ss13.moe/uploads/2019-06-02_16-23-17.webm)

**Comment by Drflash55** [comment]
Can confirm that it's happening on my end as well.

**Comment by mwittrien** [comment]
fixed
