### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps - Timestamps of second messages and "member since"

### ISSUE THREAD

**Issue by Luminous-Coder** [mwittrien/BetterDiscordAddons#2160]
**Describe the solution you'd like**
Customize the timestamps when a user sent subsequent messages and the "member since" information in user profiles.

**Additional context**
![image](https://user-images.githubusercontent.com/84374077/212538181-e442353b-edee-47bc-8d0c-ced0fe800588.png)
I know the full timestamp will display while hovering on it, but I don't want to see a 12-hour clock.

![image](https://user-images.githubusercontent.com/84374077/212538196-282c23f3-91d1-43db-903a-ad672f926636.png)

**Comment by mwittrien** [comment]
The timestamp in follow up messages wont be changed due to the limited space available, if you dont want the PM layout then choose another discord language

Tooltips with the complete timestamp formats have been added to the member since data
