### ISSUE TITLE
[BUG] - PluginRepo - Loading Images

### ISSUE THREAD

**Issue by Catif** [mwittrien/BetterDiscordAddons#2163]
**Describe the bug**
I need to hover the plugin to view the image

**To Reproduce**
1. Go in the "Plugin Repo" pannel
2. Hover the plugins

**Expected behavior**
Showing picture without needed to hover it

**Screenshots**
![Discord_y1FUZZR5yE](https://user-images.githubusercontent.com/84462178/213250942-bb6e5589-84fb-4e25-a9cd-ddcb7c05ad53.gif)

**Discord Build (stable, ptb or canary):**
Stable 168147 (2e4856d)
BetterDiscord v1.8.4
BDFDB v3.0.7

**Additional context**

**Comment by mwittrien** [comment]
Thats intended to avoid memory leaks
