### ISSUE TITLE
[BUG] - HideMutedCategories is not hiding muted categories

### ISSUE THREAD

**Issue by jonsuh** [mwittrien/BetterDiscordAddons#2164]
**Describe the bug**
`HideMutedCategories` does not hide muted categories when the plugin is enabled and the category is muted.

**To Reproduce**
Load Discord.

**Expected behavior**
Muted categories should not be visible.

**Screenshots**
<img width="234" alt="image" src="https://user-images.githubusercontent.com/359871/213282395-647f33ca-4bf1-4740-9faa-549ac5e2b5d4.png">

**Discord Build (stable, ptb or canary):**
- Discord stable `0.0.272 (0.0.272)`
- BetterDiscord `1.8.4`
- HideMutedCategories `1.1.1`

**Additional context**
- Disabling and re-enabling the plugin does not fix the issue.
- Deleting `0BDFDB.data.json` and reloading Discord does not fix the issue.
- Deleting and re-downloading the plugin does not fix the issue.
- Repairing/reinstalling BetterDiscord does not fix the issue.

**Comment by mwittrien** [comment]
You need to check the option to hide muted channels in the server

**Comment by jonsuh** [comment]
@mwittrien Still doesn’t work
<img width="231" alt="image" src="https://user-images.githubusercontent.com/359871/213477112-6cbcce56-b18c-4379-8ea2-00c7cfcf00fb.png">
<img width="209" alt="image" src="https://user-images.githubusercontent.com/359871/213477141-f2b5784f-1a49-451e-b33f-ed876f9ea88d.png">

**Comment by jonsuh** [comment]
@mwittrien Would you like me to open up a new issue since you closed this one but the bug is still valid?

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/213722333-bc5f2de3-9c03-42a7-a29e-7f441db39172.png)
![image](https://user-images.githubusercontent.com/23700969/213722383-d4ab6d24-5e29-4c42-a117-ce49868be825.png)

Works fine for me

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/213722582-a1da024e-d639-4d24-8d56-7f5e44246356.png)
