### ISSUE TITLE
[IDEA] - Checkbox

### ISSUE THREAD

**Issue by Inedable** [mwittrien/BetterDiscordAddons#2166]
Since Discord released forums, I actually use it for productivity TODO lists.

They added some new markdown features like heading and bulleted lists.
It could be nice to add additional checkboxes like the ones we can see on GitHub : 
 - [ ] Checkbox ⇽ `- [ ] Checkbox`
 - [x] Checkbox ⇽ `- [x] Checkbox`
 
As it is possible on GitHub, it could be nice to add the possibility to toggle it, on a click event, it would automatically update the message (and the markdown message).

![image](https://user-images.githubusercontent.com/123131249/213591765-850c9c80-0738-4237-92da-2a7e49c53d48.png)

**Comment by mwittrien** [comment]
I am not a discord dev?

Maybe ask discord to add it
