### ISSUE TITLE
[Issue] - Misunderstanding

### ISSUE THREAD

**Issue by Inedable** [mwittrien/BetterDiscordAddons#2167]
There was misunderstanding in the issue https://github.com/mwittrien/BetterDiscordAddons/issues/2166 @mwittrien 
I didn't think you were a Discord developer, I'm making this idea proposal as a plugin.
Markdown is handled via the [Simple-Markdown](https://www.npmjs.com/package/simple-markdown) module  so I thought it would be possible to add this functionality via a BetterDiscord Plugin.

**Comment by mwittrien** [comment]
I am not open for plugin requests/ideas
