### ISSUE TITLE
[BUG] - Notification sounds

### ISSUE THREAD

**Issue by Ferogreywolf7** [mwittrien/BetterDiscordAddons#2169]
**Describe the bug**
When enabling notification sounds plugin, better discord crashes, after freezing and has to be manually repaired by removing plugin.json to use again. 

**To Reproduce**
Download the notification sounds plugin and the devil bro plugin library. Enable both. Crash!

**Expected behavior**
No crashes

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Doesnt matter if themes are enabled or not. No other plugins where enabled when the crash happened. Happens every time.

**Comment by mwittrien** [comment]
Done use redicliously large files for the sounds
