### ISSUE TITLE
Stuck On 'Translating. Please Wait...

### ISSUE THREAD

**Issue by LarryKun420** [mwittrien/BetterDiscordAddons#217]
whenever i try to send a translated message or try to translate something it just gets stuck on the animation.

**Comment by LarryKun420** [comment]
![Screen Shot 2019-06-05 at 4 25 32 PM](https://user-images.githubusercontent.com/38389338/58991718-8fe94700-87ae-11e9-8186-f5f836271382.png)

**Comment by LarryKun420** [comment]
Pls help

**Comment by LastxAlive** [comment]
This is an issue I keep getting also. 
![image](https://user-images.githubusercontent.com/48368615/59041396-6d1f6700-8870-11e9-96da-6609bc819b85.png)

**Comment by mwittrien** [comment]
Usually happens when you are rate blocked, you can click the toasts to clear them, could try reloading too
