### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by JohnWeak1** [mwittrien/BetterDiscordAddons#2176]
**Describe the bug**
Custom closed folder icons don't show and instead show the default discord server folder icons. The open icons display like normal

**To Reproduce**
Set a custom icon for a server folder

**Expected behavior**
Display the custom icon when the folder is closed

**Screenshots**
![image](https://user-images.githubusercontent.com/42245432/214525196-48a8f5ab-fd18-4299-a230-958c7ed9afaf.png)

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
You need to enable the close icon in the folder settings

**Comment by JohnWeak1** [comment]
oh ok,
I thought it was a setting in the plugin settings and never noticed the change in the folder options,
my bad
thank you
