### ISSUE TITLE
[BUG] - EmojiReplace

### ISSUE THREAD

**Issue by flauschxger** [mwittrien/BetterDiscordAddons#2177]
**Describe the bug**

Since updating to Windows 11, Emojis only get replaced inside the chat box and messages, but not on the overall UI anymore.

**To Reproduce**
When does the bug occur.

Updating to Windows 11

**Expected behavior**

Emojis being replaced all over the UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/76179719/214642467-5b2516c4-099f-4119-9702-6ead1faceab6.png)
![image](https://user-images.githubusercontent.com/76179719/214642778-16716651-8c35-4615-b318-43d5eca7a821.png)
![image](https://user-images.githubusercontent.com/76179719/214642814-7d35b4dc-ca81-4421-9f59-352d13353ab4.png)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

Stable

**Additional context**

None

**Comment by mwittrien** [comment]
The "emojis" in channel names arent emojis they are ascii symbols looking like emojis and cant be affected by css since they are part of the font
