### ISSUE TITLE
[IMPROVEMENT] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by papokotos** [mwittrien/BetterDiscordAddons#2178]
**Describe the solution you'd like**
Would be nice to have a button that minimizes the channels back to buttons, like a collapsible sidebar.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mwittrien** [comment]
Use css to do that on hover or use BdContextMenu to toggle the plugin more quickly
