### ISSUE TITLE
[IMPROVEMENT] - Friend Notifications/Notification Position

### ISSUE THREAD

**Issue by Alicyl** [mwittrien/BetterDiscordAddons#2183]
Your 'Friend Notification' plugin has been very helpful with keeping up with my friends ongoings, but the main reason why I often find myself disabling it is due to the fact that the notifications obstruct the window commands (minimize, maximize, and close) and the search bar on Discord.

More often than not, I mistakenly click the notifications the wrong way which directs me to where they came from when I meant to close them to get to what they were covering, and this gets really irritating from time to time when it does happen. I've looked through the settings, and I couldn't find anything that looked like it would let me move where the notifications appear.

There should be a setting that allows us to reposition these notifications to prevent them from obstructing anything of importance to us similarly to this setting shown below:

![Discord_Cz4JkIMuh2](https://user-images.githubusercontent.com/13776859/215812484-ab2dfb09-e2b8-4024-8a1e-35d197f46be2.png)

**Comment by mwittrien** [comment]
You can change it in the BDFDB settings
