### ISSUE TITLE
[IMPROVEMENT] - Image Utilities

### ISSUE THREAD

**Issue by degu-Tanya** [mwittrien/BetterDiscordAddons#2185]
**Describe the solution you'd like**
A option to make so new discord embed forcefully shows up under and dosnt group up to tiny preview images
![bilde](https://user-images.githubusercontent.com/100243423/216744061-1ce35444-8e3b-49ef-9be9-09869643c4a2.png)

**Describe alternatives you've considered**
it could be a alternative embed turn on / off setting here 
![bilde](https://user-images.githubusercontent.com/100243423/216744551-c565fe18-4b99-4f47-bb97-20f5d71ca2f0.png)

**Additional context**
How the new embed forces 2 or more images to be squished together so my lazy ass gotta click images to read again
![bilde](https://user-images.githubusercontent.com/100243423/216744167-320b44e3-16ec-48c5-bfcb-a5a48703cf1f.png)

**Comment by mwittrien** [comment]
Discord should add an option to disable the mosaic view themselves
You should suggest it to them
