### ISSUE TITLE
[BUG] - GameActivityToggle.plugin

### ISSUE THREAD

**Issue by Tetrax-10** [mwittrien/BetterDiscordAddons#2186]
**Describe the bug**
when clicking `Disable game activity` the sound plays but the action is not happening like `on/off`.

**To Reproduce**
click `Disable game activity`

**Screenshots**
![image](https://user-images.githubusercontent.com/75513645/216793325-984b2ade-d548-461a-8bbb-24f310c7e6e3.png)

**Discord Build (stable, ptb or canary):**
Stable 171842 (a125c4a)
Host 1.0.9010 (29128)
Windows 10 64-Bit (10.0.22621)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
