### ISSUE TITLE
[SUGGESTION] ChatAliases

### ISSUE THREAD

**Issue by ObeyBeastJj23** [mwittrien/BetterDiscordAddons#219]
I'm just here suggesting a new feature for the ChatAliases plugin.
I'd love there to be a toggle switch for a "mode" in the settings from "Blacklist" to "Whitelist"
and also adding a ContextMenu item for guilds to "add to blacklist" and "add to whitelist".
This would be great for only censoring for shit servers with "Mee6" in them or "Dyno" which have
chat filter enabled, so I can filter all my profanity before it's sent on a "whitelist only" list of servers.

Hope this can be added :D

**Comment by mwittrien** [comment]
The plugin isnt meant to censor your own profanity, use your brain before you send a message in a server
