### ISSUE TITLE
Crash discord after turning on the plugin.

### ISSUE THREAD

**Issue by D-rol** [mwittrien/BetterDiscordAddons#2192]
After turning on the plugin discord just stops working, only the repair betterdiscord helps. This started a couple of days ago.
![image](https://user-images.githubusercontent.com/83500403/219122153-319c894b-ab78-458d-8c7b-067b94517a45.png)

**Comment by mwittrien** [comment]
What plugin

**Comment by D-rol** [comment]
> What plugin
ChannelTabs

**Comment by mwittrien** [comment]
Not my plugin
