### ISSUE TITLE
[BUG] - Read all Notifications Button

### ISSUE THREAD

**Issue by SkyKingPX** [mwittrien/BetterDiscordAddons#2195]
**Describe the bug**
I don´t know if the bug comes from BDFDB or The Notifications button, but if I´m trying to open the Settings Discord crashes.

**To Reproduce**
Tap the Settings Icon

**Expected behavior**
OPEN THE SETTINGS!

**Screenshots**
- Movie in Additional context

**Discord Build (stable, ptb or canary):**
Stable 175497 (d7cb099)

**Additional context**
(It´s on German, but I think this is not so bad)
https://clipchamp.com/watch/DDSuWuDkaE2

**Comment by mwittrien** [comment]
Not an issue from my stuff

**Comment by SkyKingPX** [comment]
It is: https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReadAllNotificationsButton

**Comment by mwittrien** [comment]
Ita my plugin, but the Plugin doesnt cause such issues
