### ISSUE TITLE
Keyboard shortcuts think servers are still there after I moved them

### ISSUE THREAD

**Issue by S-B99** [mwittrien/BetterDiscordAddons#220]
Title. 

Example: (1 is highest in list vertically)
Have server 1, 2 and 3. 
Move 2 to a folder 4, have 1 selected. 
Press Ctrl Alt Down, to go to server 3. Instead open server 2.

**Comment by mwittrien** [comment]
the native guild list isnt changed by serverfolders the icons are just hidden, tinkering with it would break other stuff
