### ISSUE TITLE
[BUG] - BDFDB + ImageUtilities has significant performance problems

### ISSUE THREAD

**Issue by ggtylerr** [mwittrien/BetterDiscordAddons#2204]
**Describe the bug**
ImageUtilities seems to be causing lag upon switching channels.

**To Reproduce**
With the plugin enabled, switch to a different text channel. The time it takes nearly quadruples (on my tests, ~2 seconds to ~8 seconds.)

**Expected behavior**
The performance hit should be minimal, or at least not as substantial.

**Screenshots**
<details>
<summary>Show screenshots</summary>

Performance before BDFDB + ImageUtilities:
![image](https://user-images.githubusercontent.com/28498877/221328747-b5035ccb-c346-45dc-9361-a20e8cf1126f.png)
Performance after BDFDB + ImageUtilities:
![Discord_uB9OvXp6Vo](https://user-images.githubusercontent.com/28498877/221328579-2f8fc5ca-6f90-4142-9ab4-4278afe714a7.png)

</details>

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This seems to be directly related to ImageUtilities - Looking in console, there's a ton of warnings:
<details>
<summary>Show screenshots</summary>

![image](https://user-images.githubusercontent.com/28498877/221328868-1c980334-14dc-44a5-ad3c-74b1ab40c6cf.png)
![image](https://user-images.githubusercontent.com/28498877/221328881-2668f6b4-f7ca-4efe-ba21-a8aa78b01080.png)

</details>

*~~(and it's probably because the function itself, processLazyImage, is huge and called like 50 times)~~*

I specifically mentioned ImageUtilities + BDFDB because only disabling BDFDB seems to improve performance a little bit. Unfortunately I haven't tested it enough to tell.

Also I know an issue was recently made for this. Wanted to make a different issue since this is more detailed and specific.

**Comment by meatspace** [comment]
yes Ive noticed this as well, just came here to make a similiar bug report. Switching channels is much faster with imageutilities disabled.

**Comment by Aaeeschylus** [comment]
I came to post the same thing. I am currently keeping ImageUtilities disabled as Discord was becoming near unusable with the amount of delay when switching channels or servers

**Comment by mwittrien** [comment]
#2203
