### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities

### ISSUE THREAD

**Issue by togreglove** [mwittrien/BetterDiscordAddons#2205]
**Describe the solution you'd like**
I'd love an option to hide images/videos.

**Describe alternatives you've considered**
There are no plugins I have found that allows you to hide images/videos. Discord has had it brought up many times over the years and ignores it.

**Additional context**
I love working with the GIFs, JPEGS, and clips folks share with me, but sometimes they post something I find unpalatable or offensive and I just don't want to see it sitting in my newsfeed till it eventually scrolls off naturally.  Having the ability to simply right click it and hide it would allow me to choose what I see.  

If you find that this doesn't fit the theme of ImageUtilities, a separate plugin would probably be popular in it's own right.

**Comment by mwittrien** [comment]
Sounds more like a new plugin idea
