### ISSUE TITLE
[BUG] - ImageUtilities - Excessive Resources Usage

### ISSUE THREAD

**Issue by auroraisluna** [mwittrien/BetterDiscordAddons#2206]
**Describe the bug**
When ImageUtilities is enabled, either after loading or by just going around discord servers and channels, after a few seconds the client begins to slow down to the point channel switching takes about 6-7 seconds. Disabling the plugin instantly brings the normal performance.

**To Reproduce**
Run BD, run this plugin alone, browse around discord or wait idle for a few minutes

**Expected behavior**
The plugin should not slow down discord

**Discord Build (stable, ptb or canary):**
Stable 177026 (2a7afac) 
Host 1.0.9011 (29584) 
Windows 10 64-Bit (10.0.22623) (W11)

**Additional context**
It seems RAM usage is also elevated, as without the plugin discord uses around 700mb, but as soon as the plugin is on and the performance slows downs, discord peaks to 1400mb, seen it reach 1900mb once.

**Comment by MagmaBro123** [comment]
This probably also happens with other 0BDFDB-based plugins as well. Discord is also quite slow for me as well.
