### ISSUE TITLE
[BUG] - BetterFriendList no longer works

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2207]
**Describe the bug**
BetterFriendList doesn't work, none of the features showcased in the README.md appear in the app

**To Reproduce**
go to the friends tab

**Expected behavior**
Adds counters and the ability to sort to the Friends Page

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/221845385-9d187d32-5ce5-4b08-a112-7218cf5c76ab.png)

**Discord Build (stable, ptb or canary):**
stable 177136 

as a side note the ability to search through your friend list now appears even without the plugin, meaning it's now built-in in vanilla discord

**Comment by mwittrien** [comment]
Library was Broken update BDFDB to 3.0.9
