### ISSUE TITLE
Display Servers As Channels: Variable width or hide option

### ISSUE THREAD

**Issue by ZdrytchX** [mwittrien/BetterDiscordAddons#221]
The width of the column is rather wide considering I have a rather narrow monitor horizontally. If I open a single layer of folders with the folders plugin, the text box becomes crushed to only a [few characters wide](https://i.imgur.com/lJySO9z.png) at default zoom without minmalistic UI enabled.

Considering that the user doesn't have to look at the server list all the time, I'd like an option to either make the column narrower, hide it entirely with a toggle button and/or shortcut, and maybe even have an [IRC server/channel tree style interface](https://i.imgur.com/19s1eV8.png) rather than side-by-side lists.

**Comment by mwittrien** [comment]
Added the feature to change the width of the DSAC changed list in the plugin settings
