### ISSUE TITLE
[BUG] - BDFDB doesn't initiate - cannot create settings panel

### ISSUE THREAD

**Issue by Yatahu** [mwittrien/BetterDiscordAddons#2210]
Bug appeared after quick fix from better discord, I replaced betterdiscord.asar file and it solve primary issue - [Primary bug report ](https://github.com/BetterDiscord/BetterDiscord/issues/1540) , [Fix file that I used](https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389) 

Plugin can't initiate, I tried reinstalling plugin, deleting file as instruction on screenshot shows, deleting all other plugins.
Probably bug exists on all platforms as I read primary bug report comments, but fyi my platform is mbp 2020 m1 macos ventura 13.1

<img width="662" alt="Screenshot 2023-02-28 at 16 14 31" src="https://user-images.githubusercontent.com/60200518/221895985-a7265b89-fd6f-45d5-b97f-c3fb36e19a1d.png">

**Comment by mwittrien** [comment]
Update BDFDB to 3.0.9 and delete your 0BDFDB.data.json
