### ISSUE TITLE
[BUG] - ImageUtilities causes crashing when attempting to fast-forward a youtube video embed

### ISSUE THREAD

**Issue by EmeraldWither** [mwittrien/BetterDiscordAddons#2211]
**Describe the bug**
When a user sends a youtube video, and an embed link appears in discord, attempting to fast-forward in the video by clicking on the timeline will result in a crash with the following stack trace in devtools. 
![image](https://user-images.githubusercontent.com/68785503/221919456-ab14867a-8e40-4f0f-adc2-2f5252cf5f24.png)

**To Reproduce**
1) Send a youtube video
2) Play the video
3) Fast forward in the video by using the timeline
4) Crashes 

**Expected behavior**
You should be able to skip ahead in the video without crashing. 

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Installed Plugins: 
* BDFDB - v3.0.9
* ImageUtilities - v5.1.6

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
