### ISSUE TITLE
[BUG] - ClickableMentions either disappears mention or doesn't work

### ISSUE THREAD

**Issue by aaronliu0130** [mwittrien/BetterDiscordAddons#2213]
**Describe the bug**
Clickable mentions causes mentions to be shown as a space. After disabling and enabling it just doesn't work.

**To Reproduce**
1. Install ClickableMentions.
2. Open discord.
3. Ping someone.
4. The mention doesn't show in the text input.
5. Send it out and notice it shows up.
6. Go to settings, disable and enable ClickableMentions.
7. Ping someone.
8. Notice it doesn't work.

**Expected behavior**
It always works and won't let the mention disappear, and thus allows me to click on the mention.

**Screenshots**
![demonstration](https://user-images.githubusercontent.com/11874211/222000653-58fd0bb2-2de7-4a64-a731-760ee3c83676.gif)

**Discord Build (stable, ptb or canary):**
Stable 177136 (f81785f) Host 1.0.9011 (29584) |

**Comment by XxUnkn0wnxX** [comment]
Same here, it's a UI Bug:

all tests were done on BD Branch: [fix/tooltip-crash (26161ec29fff2dc3649f40d20a3db8df1e0fd83b)](https://github.com/BetterDiscord/BetterDiscord/commit/26161ec29fff2dc3649f40d20a3db8df1e0fd83b) - Current BD Hotfix

disables the ability to mention anyone, just won't show in the text field.
the mention will still go through when sending the message you just don't see in the typing field. (UI Bug)

<img width="1140" alt="ConsoleLog" src="https://user-images.githubusercontent.com/2242880/222057995-7798a885-e095-4c35-a189-d7824afda138.png">

[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/10857614/debug.log)

```
Stable 177136 (f81785f) Host 0.0.273 | OpenAsar 40b27dd OS X 10.15.7 (20.6.0)
```
