### ISSUE TITLE
[BUG] - Settings Modal

### ISSUE THREAD

**Issue by Miniontoby** [mwittrien/BetterDiscordAddons#2215]
**Describe the bug**
The title bar of discord is faded away and the channel tabs not.

**To Reproduce**
Use "Discord11" theme and the addon "Channel Tabs" with this theme and open settings.

**Screenshots**
With Settings Modal enabled:
![image](https://user-images.githubusercontent.com/47940064/222109937-897eecac-c34d-444f-ad2b-fc4262aba408.png)

Without Settings Modal:
![image](https://user-images.githubusercontent.com/47940064/222110397-67f63663-d3a8-42c5-b857-5a6b8bf09230.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**

P.s. I don't know if this could be the place where I should post this, maybe discord11 should fix it, but I am not sure just yet, I will reference this issue at discord11 if you cannot fix this kind of bug but also not really bug

**Comment by mwittrien** [comment]
Neither my theme nor my plugin

**Comment by Miniontoby** [comment]
Oh shit, I now reloaded discord and it keeps on crashing
