### ISSUE TITLE
[IMPROVEMENT] - Performance issue

### ISSUE THREAD

**Issue by Zzeyy** [mwittrien/BetterDiscordAddons#2217]
**Describe the solution you'd like**
Code optimization or performance fix in any other way.

**Describe alternatives you've considered**
Disabling certain plugins.

**Additional context**
After disabling BetterNsfwTag, BetterFriendList and GameActivityToggle the performance (loading time, etc) got instantly better.

**Comment by mwittrien** [comment]
Youll have to deal with it

**Comment by Zzeyy** [comment]
Huh

**Comment by MagmaBro123** [comment]
Fix it or remove these plugins if you won't fix them then.

**Comment by aaronliu0130** [comment]
@MagmaBro123 Make your own plugins then.
Performance is a HUGE deal and it's frankly infuriating, but we are still getting all this for free. Open source developers do NOT hold any responsibility (except for not infecting your computer) and this kind of response does not help.
