### ISSUE TITLE
[ISSUE] Server folders not opening

### ISSUE THREAD

**Issue by Shadowblade901** [mwittrien/BetterDiscordAddons#222]
**Issue:** 
After creating a folder as the description says, and placing servers within said folder, that folder becomes locked and permanently unable to open. The only fix I can find for this is to constantly reset all folders. However, it seems to affect any server folders that are created after the first folder, meaning I can only have one active folder at a time. 

If there is already a closed issue report about this with a solution please link it, or you need more information, i'll see what I can do to grab what's needed. 

PS: Sorry if it has already been sorted out, I just wanted to make sure there is a recent comment about it and a solution so people can see it more clearly.

**Comment by mwittrien** [comment]
Can't reproduce it, works fine for

**Comment by Shadowblade901** [comment]
I've found that it will happen when certain applications are open in the background, so it works fine after they are closed and discord reset. Although, this issue has also come up when choosing a custom server folder icon, but again, the answer seems to disable the add-on, close discord, open discord and enable it again. 

Sorry if this took up too much of your time, it just seemed to be a case of sifting through open/running applications through task manager and closing all that may conflict.

Thank you for responding!
