### ISSUE TITLE
[BUG] - SettingsModal

### ISSUE THREAD

**Issue by bobjoerules** [mwittrien/BetterDiscordAddons#2223]
**Describe the bug**
Theme does not work. Settings is just its regular page.

**To Reproduce**
The newest update of bd and discord. 1.0.0v of the theme.

**Expected behavior**
To be a page hovering over the main discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/39201587/222311594-0b909f34-3cda-4b18-a5c8-334d09b2b94e.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
Issue on mac

**Comment by mwittrien** [comment]
#2218
