### ISSUE TITLE
[BUG] - PLUGIN/Theme and plugin repo

### ISSUE THREAD

**Issue by kirinto13** [mwittrien/BetterDiscordAddons#2224]
**Describe the bug**
Plugin repo gives error "React component error"

**To Reproduce**
Whenever i try to open the plugin repo i get the above mentioned error and theme repo just crashes discord.

**Expected behavior**
I expect the plugin and themes repo to open and give updates and such.

**Screenshots**
![image](https://user-images.githubusercontent.com/126751736/222345610-8c73c338-e36d-45f8-b67a-3463c3183470.png)

**Discord Build (stable, ptb or canary):**
I am using the stable build

**Additional context**
I had to reinstall discord as i it was hacked recently and before the reinstall both plugins were working fine. I did a clean install of discord, better discord and the plugins. I even added the plugins manually from github still the same error. All other plugins work fine.
Just as a side note is this plugin compatable with the zeres library as i know it can remove the repos.

**Comment by getkirill** [comment]
can confirm

**Comment by mwittrien** [comment]
#2219
