### ISSUE TITLE
[BUG] - PluginRepo | React Failure Error

### ISSUE THREAD

**Issue by PS2ClassicsVault** [mwittrien/BetterDiscordAddons#2225]
**Describe the bug**
When installing it, it immediate fails to run even with all the required plugins and returns with "React Component Error"

**To Reproduce**
Just installed in manually and enabled it and then fails to start

**Expected behavior**
It should enable and see the repo of plugins

**Screenshots**
https://imgur.com/gallery/WgZhG1T

**Discord Build (stable, ptb or canary):**
Stable (Latest Version)

**Additional context**
beyonf this none

**Comment by mwittrien** [comment]
#2219
