### ISSUE TITLE
[BUG] - Unexpected error in plugin settings

### ISSUE THREAD

**Issue by embry0** [mwittrien/BetterDiscordAddons#2227]
**Describe the bug**
Opening settings of BDFDB and other DevilBro plugins results in an unexpected errror. Everything was fine yesterday after the crashes from BetterDiscord after opening settings were fixed.

**To Reproduce**
Open the settings of BDFDB or any plugins that uses the library.

**Screenshots**
![image](https://user-images.githubusercontent.com/126282972/222362561-acfce084-dea5-48bf-9e43-19447a608e5f.png)
![image](https://user-images.githubusercontent.com/126282972/222362589-fdeac40e-e351-4e17-8930-68e86a0af8e1.png)

**Discord Build (stable, ptb or canary):**
Stable 177662 (311622e)
BetterDiscord v1.8.5
BDFDB v3.1.0

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
