### ISSUE TITLE
[BUG] - BDFD Lib, Plugin Repo, Theme Repo, User Notes/Pins

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [mwittrien/BetterDiscordAddons#2228]
**Describe the bug**
I suspect that the BDFD Lib is causing several of your plugins to still crash causing issues on discord after the BD V1.8.5 Update

**To Reproduce**
Try to click into theme/plugin repo, and click on user pins/notes to get errors, crash discord etc..

**Screenshots**
<img width="1741" alt="Screen Shot 2023-03-02 at 9 09 33 pm" src="https://user-images.githubusercontent.com/2242880/222399601-fd4d2fd1-4600-4097-996b-d3c4b89f676d.png">
<img width="1741" alt="Screen Shot 2023-03-02 at 9 09 36 pm" src="https://user-images.githubusercontent.com/2242880/222399621-7ef99160-cee3-4bd7-aaa9-554b814538d6.png">
<img width="1065" alt="Screen Shot 2023-03-02 at 9 09 39 pm" src="https://user-images.githubusercontent.com/2242880/222399633-a88358de-ef5a-4129-8cb7-690480019aee.png">
<img width="638" alt="Screen Shot 2023-03-02 at 9 10 41 pm" src="https://user-images.githubusercontent.com/2242880/222399640-69bf8894-df6c-4164-86d8-2886b80f01a1.png">
<img width="1142" alt="Screen Shot 2023-03-02 at 9 11 55 pm" src="https://user-
images.githubusercontent.com/2242880/222399642-d300c81e-5317-4bc3-b65d-109209b1f613.png">

Show Connections, Charcounter.
<img width="1712" alt="Screen Shot 2023-03-02 at 9 36 07 pm" src="https://user-images.githubusercontent.com/2242880/222404602-d5d1686b-4468-4a34-87aa-fe41caa5fb8b.png">

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/10870174/debug.log)

**Comment by mwittrien** [comment]
#2219
