### ISSUE TITLE
[BUG] - BDFDB v3.1.0 / CustomStatusPresets v1.1.5 fails to render custom status menu item

### ISSUE THREAD

**Issue by Fellshadow** [mwittrien/BetterDiscordAddons#2229]
**Describe the bug**
The custom status presets menu fails to render, resulting in not being able to set custom status at all

Similarly to #2228 I also suspect this is primarily the BDFDB lib causing the crash on v1.8.5 of BetterDiscord

**To Reproduce**
Install and enable BDFDB lib and CustomStatusPresets plugins, check the user menu in the lower left. No custom status option is there at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/106463662/222403129-c26bc0d3-1550-49ac-a3a9-07c23990f969.png)
![image](https://user-images.githubusercontent.com/106463662/222402903-22ede599-1bd7-40ae-863e-46ff0d1e3bf6.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/10870340/debug.log)

**Comment by MrJDucky** [comment]
_The support channel is locked down, so posting here:_
Still having the issue of the Custom Status menu item not showing after downloading the latest versions of BDFDB lib and Custom Status plugins and deleting the .data.json file.
