### ISSUE TITLE
ShowHiddenChannels is not showing users in text channels.

### ISSUE THREAD

**Issue by elax102** [mwittrien/BetterDiscordAddons#223]
It shows allowed/overwritten roles, denied roles, and voice users just fine. It never seems to show any specifically allowed or denied users of text channels though.

I'm not a super expert on this stuff but I tried figuring out what might be the cause. I noticed in the `showAccessRoles` function there are checks to see if the `permissionOverwrites` type is "role" or "member". I put a console log inside the for loop that just checked the type of the channel.

`console.log(channel.permissionOverwrites[id].type);`

It would always log "role". So the code for the users never seems to run. I also tried changing the if statements with "member" to "role" and logged the `user` and `member` vars. The code ran but both `user` and `member` are undefined.

That's about all I know. Not sure how correct all this is, or if it's only a problem with my computer.

**Comment by mwittrien** [comment]
Should be fixed in 2.5.2
