### ISSUE TITLE
[BUG] - BasicBackground

### ISSUE THREAD

**Issue by roguesensei** [mwittrien/BetterDiscordAddons#2230]
**Describe the bug**
Backdrop (blur) appears over popout making buttons unclickable.

**To Reproduce**
1. Downloaded default BasicBackground template from repo
2. Disabled all plugins to be sure
3. Apply theme and attempt to do something that requires a popout (such as viewing a users profile or deleting a message)
4. Attempt to click on buttons, cannot click any and will close popup

**Expected behavior**
Backdrop should appear behind popout and buttons should be clickable

**Screenshots**
Message in chat:
![image](https://user-images.githubusercontent.com/32780495/222408872-4ba41932-516d-4d8a-9fad-c5ca62be25a7.png)
Background will darken over popup and cannot click buttons:
![image](https://user-images.githubusercontent.com/32780495/222409029-85dc7d59-c997-425e-920c-cfda55afdd70.png)

**Discord Build (stable, ptb or canary):**
Stable (BetterDiscord Core v1.8.5)

**Additional context**
If it's applicable, my OS is Linux.

**Comment by TheBeeThat** [comment]
i have the same issue, but also with a really annoying looking scrollbar for the server list that appeared like 3 days ago and i couldnt find any way to disable it
![image](https://user-images.githubusercontent.com/96020070/222415412-555100f3-726d-427d-ba84-57961630d189.png)
