### ISSUE TITLE
[BUG] - SERVERCOLUMNS

### ISSUE THREAD

**Issue by rom4ster** [mwittrien/BetterDiscordAddons#2231]
**Describe the bug**
Server Columns does not obey config for sizing and amount of columns

**To Reproduce**
When doing anything except the bog standard default server columns

**Expected behavior**
I expect 10 colss of size 32, I get 7 of some size thats NOT that. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19560977/222483143-3e8f65f2-7170-4205-9b31-981fa29aafe4.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
no

**Comment by D3SOX** [comment]
Additionally, the `--guildgap` setting also seems to be broken

**Comment by D3SOX** [comment]
I can confirm that it's working again. Thanks for the fix!
