### ISSUE TITLE
[Improvement] - NotificationSounds - Port out volume control to separate plugin

### ISSUE THREAD

**Issue by Reenuip** [mwittrien/BetterDiscordAddons#2238]
I found your NotificationsSounds plugin and got it solely for the notification volume control. I'd love to see a standalone plugin that takes care of that because I don't like the custom sounds supplied with this plugin.
Maybe it's just on my end, but for some reason, even when I reset all sounds, the DM notification blip is different than the Discord original sound.

**Comment by mwittrien** [comment]
Ask on the BD servers for someone to make it
