### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds/Split call ringing same as direct/group message

### ISSUE THREAD

**Issue by l-Nuril-l** [mwittrien/BetterDiscordAddons#2239]
**Describe the solution you'd like**
I want to disable group calls or set a very short beep.
And it will be possible to understand whether the call is important or not.
DND is not suitable as it disables personal calls.
And in the group itself I should be, but I never participate in conversations.

**Describe alternatives you've considered**
This is not possible at the moment

**Additional context**
![image](https://user-images.githubusercontent.com/49325887/222975074-7a60bf81-c935-455a-98b5-a816dea30080.png)
Mute incoming calls from specific groups is a good idea for a plugin, but the ability to set a short sound for group calls is also a good solution.

**Comment by mwittrien** [comment]
Ask on the BD servers for it
This should be a new plugin
