### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds/Split the "Call Ringing" element, just like the message (direct/group)

### ISSUE THREAD

**Issue by l-Nuril-l** [mwittrien/BetterDiscordAddons#2240]
**Describe the solution you'd like**
Split the "Call Ringing" element, just like the message (direct/group)

**Additional context**
Last time I described the proposed improvement only in the title of the thread, perhaps you didn't quite understand what I meant to write or is it just "won't be added" and I need a new plugin?
Sorry for the duplicate
[Past topic](https://github.com/mwittrien/BetterDiscordAddons/issues/2239#issue-1610284968)

**Comment by mwittrien** [comment]
I told you that i wont add it
Period
