### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by RainbowSimon** [mwittrien/BetterDiscordAddons#2242]
**Describe the bug:**
Discord Hotkeys not working anymore after plugin loads.
I have a hotkey to mute the mic, set normally in the Discord settings. 
These hotkeys do not work anymore once the plugin loads, meaning after every start of BD.
You can get them back to work though by opening the hotkeys settings tab in the normal Discord settings, after that they work until Discord is restarted (or probably when the plugin is loaded again).

**To Reproduce**
Set any hotkey in Discord, load the plugin, it should not work anymore.
Alt-F4 Discord and restart, still does not work.
Go where you set the Hotkey and leave without touching anything, it will work.

**Discord Build:**
stable, on Win10 x64

**Comment by mwittrien** [comment]
dont use the same hotkey for the plugin and your mic toggle

it works fine for me if you use two different hotkeys

**Comment by RainbowSimon** [comment]
Well duh, I dont. It seems to be a problem with the Key I want to use. I use F13/F14 with Corsair iCUE, but as soon as the Plugin has either of those set, the Mic hotkey is not working anymore. 
Is this a problem with the plugin or some general BD or even vanilla Discord issue?

**Comment by mwittrien** [comment]
Cant be a plugin issue since the plugin adds the hotkey the same way Discord adds theirs

**Comment by RainbowSimon** [comment]
Actually this issue still remains for many keys I tried, could you tell me what keys you used for your test?
I tried SCROLL LOCK for mute and BREAK for game activity (both on the left of the numpad) and it does not work.
Same thing for NUMPAD8 + NUMPAD9, also doesn't work.
