### ISSUE TITLE
[BUG] - PluginRepo - Not Showing

### ISSUE THREAD

**Issue by dudeedud4** [mwittrien/BetterDiscordAddons#2243]
**Describe the bug**
Plugin Repo is not showing

**Screenshots**
[https://i.imgur.com/cxBe7Wm.png](https://i.imgur.com/cxBe7Wm.png)

**Discord Build (stable, ptb or canary):**
Stable 178850 (ce63c6e)

**Additional context**
I have tried reinstalling the plugin and turning it on/off

**Comment by mwittrien** [comment]
Redownload BDFDB and try deleting 0BDFDB.data.json
