### ISSUE TITLE
[BUG] - FriendNotifications - Timelog not working as intended

### ISSUE THREAD

**Issue by andochronic** [mwittrien/BetterDiscordAddons#2246]
**Describe the bug**
Sometimes when I launch Discord and click on the Friend Notifications timelog to open it, nothing pops up and I get the error in console as seen in my first screenshot below.
Other times, the FriendNotifications timelog will be working perfectly fine and I can open and close it as normal, but then after some time it will just break and then a little message will pop up with red text saying "React Component Error".

**To Reproduce**
Just click on the timelog, or have the plugin running for some period of time before it starts erroring.
One time I started getting the "React component error" right after I clicked to clear the timelog.

**Expected behavior**
The timelog should just open as intended.

**Screenshots**
The error that shows up when the timelog never wants to open when I click on it:
![The error that shows up when the timelog never wants to open when I click on it](https://user-images.githubusercontent.com/127494241/224293046-aefb53a5-53df-4f56-bb6e-d4e778159a4a.png)

The error that shows up when the timelog is working, but then breaks:
_<coming soon, the timelog isn't working at all for me right now>_

**Discord Build (stable, ptb or canary):**
Stable 179718 (02dd321)

**Additional context**
This issue only started occurring yesterday after I installed the BDFDB 3.1.5 update, so it might even be a plugin library bug.

**Comment by mwittrien** [comment]
delete 0BDFDB.data.json and reload discord

**Comment by andochronic** [comment]
This is the error that shows up when the timelog was working fine, but then suddenly breaks and shows the "React Component Error" message:

![The error that shows up when the timelog was working fine, but then suddenly breaks and shows the "React Component Error" message](https://user-images.githubusercontent.com/127494241/224331526-1a3c28e8-6816-4e0f-b616-93d310dc98b5.png)

The timelog completely broke and wouldn't re-open again after I clicked on the clear timelog button.
