### ISSUE TITLE
[IMPROVEMENT] - Plugin which lets you display local music played (like with Spotify)

### ISSUE THREAD

**Issue by NeatFennec** [mwittrien/BetterDiscordAddons#2252]
**Describe the solution you'd like**
A plugin which lets you share the artist and title of the current music-file you listen to from your current local music playing for example in a rich presence, similar to the original Discords Spotify share-function

**Describe alternatives you've considered**
Spotify, soundcloud

**Additional context**
If this is possible I would be really happy and would give the creator a tip :)

**Comment by mwittrien** [comment]
Not possible and i am not making new plugin
