### ISSUE TITLE
[BUG] - EditUsers - cant open local user setting menu

### ISSUE THREAD

**Issue by pp0236** [mwittrien/BetterDiscordAddons#2254]
**Describe the bug**
cannot open local setting menu

**Screenshots**
![image](https://user-images.githubusercontent.com/54238880/225591378-c74e6432-1387-4f7c-a6b9-ab465b4d4a89.png)

**Discord Build (stable, ptb or canary):**
canary

**Comment by mwittrien** [comment]
delete 0BDFDB.data.json and reload discord

**Comment by polocatfan** [comment]
still doesn't work
