### ISSUE TITLE
[BUG] - React Component Error

### ISSUE THREAD

**Issue by b11115042** [mwittrien/BetterDiscordAddons#2258]
![image](https://user-images.githubusercontent.com/113367386/226112283-e826ac5f-9fa6-420e-b78b-63a185a448be.png)
When i try to see the log of FriendNotifications it pop a React Component Error

**Comment by b11115042** [comment]
![image](https://user-images.githubusercontent.com/113367386/226113110-bdd03de7-098d-44d7-b741-b202605c9b36.png)
![image](https://user-images.githubusercontent.com/113367386/226113121-c687ec41-d012-494c-b3c4-7a3ab508e32e.png)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
