### ISSUE TITLE
[IMPROVEMENT] - VISUAL BUG AFTER PUT 2 COLUMNS

### ISSUE THREAD

**Issue by GTREBLA** [mwittrien/BetterDiscordAddons#2266]
Hi!

First of all, thanks for your work. After that i want to ask you something.

Any modification to hide this? since when putting 2 columns, this is bugged (if you put a column it does not come out) and if you select a server when it is focused it does not look bad.

![image](https://user-images.githubusercontent.com/46114777/227042265-62093d8b-5112-43b0-8be9-446cc7c0391d.png)

**Comment by mwittrien** [comment]
its not a visual bug, thats the intended behaviour

if you wanna hide it add

```
.wrapper-1_HaEi .pill-L_aLMQ {
	display: none;
}```
