### ISSUE TITLE
[BUG] - PLUGIN/Translator

### ISSUE THREAD

**Issue by wqjuser** [mwittrien/BetterDiscordAddons#2267]
**Baidu Translator do not work**
<img width="613" alt="Snipaste_2023-03-23_14-56-38" src="https://user-images.githubusercontent.com/19888942/227127386-64bb9b2d-9244-4d47-9e84-8e14a72249b0.png">

 **I have the latest version**
<img width="514" alt="Snipaste_2023-03-23_14-57-28" src="https://user-images.githubusercontent.com/19888942/227127586-f55088da-919f-49d8-a07f-cf1e6f0b6ec9.png">

**I have set the appId and key**
<img width="486" alt="Snipaste_2023-03-23_14-57-45" src="https://user-images.githubusercontent.com/19888942/227127781-8fbed936-d6e6-4440-94c0-9dc7c337f6c6.png">

**Comment by mwittrien** [comment]
Format is XXXXXXXXXXXX YYYYY
first being the app id and second the secrer
