### ISSUE TITLE
[IMPROVEMENT] - Add a hover option for the folder plugin

### ISSUE THREAD

**Issue by foxnoobkite** [mwittrien/BetterDiscordAddons#2270]
when you hover over the folder with your mouse, it opens, and when you exit, it closes

if that is impossible maybe add a set timer for it to close when opened. 

i felt like this plugin made my screen smaller and i always mistaken the folder bar as the main one. so it would be nice for it to automatically close

**Comment by mwittrien** [comment]
You can set the folder to auto close if you select a server in it in the plugin settings
