### ISSUE TITLE
[BUG] - GameActivityToggle

### ISSUE THREAD

**Issue by Lrogan** [mwittrien/BetterDiscordAddons#2271]
**Describe the bug**

Installing the plugin causes discord to crash

**To Reproduce**
When does the bug occur.

On first load after install

**Expected behavior**

Discord to load

**Screenshots**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/37965234/227697004-9875eb43-4a38-4514-8706-02d147fcc3ba.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/37965234/227697006-fbaa7ab8-9b68-4e0c-8751-9f237602818a.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/37965234/227697013-d6418c01-d7d4-4b1d-8202-53c3cd3d99c4.png">

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

Stable

**Additional context**

**Comment by mwittrien** [comment]
You are missing the BDFDB plugin library
