### ISSUE TITLE
PluginRepo - "Some Plugins Are Outdated" for Up-to-date plugins

### ISSUE THREAD

**Issue by jetblackrx89** [mwittrien/BetterDiscordAddons#2275]
Seen in the latest 2.4.6. PluginRepo is claiming there are updates for plugins even if none exist. I noticed it only happens on plugins that are currently broken and awaiting rewrites. For example:

[StatusEverywhere](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/StatusEverywhere/StatusEverywhere.plugin.js)
[WhoReacted](https://raw.githubusercontent.com/jaimeadf/BetterDiscordPlugins/release/dist/WhoReacted/WhoReacted.plugin.js)

Both plugins have a "could not compile" error at start  but are indeed already the latest versions available from the dev.

**Comment by OmegaBlurz** [comment]
What was the fix for this?
