### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities overrides corner radius

### ISSUE THREAD

**Issue by 43615** [mwittrien/BetterDiscordAddons#2276]
Line 284 overrides the `border-radius` property that users might want to set to 0 in BD's custom CSS injector to remove rounded corners. The corresponding section seems to be designed to restore some properties to the vanilla default, but I believe this should be left up to the user.

**Comment by mwittrien** [comment]
You can still change it with custom css even if the plugin changes it

**Comment by 43615** [comment]
No, the plugin overrides it. I wouldn't submit an issue report if it was that simple.

**Comment by mwittrien** [comment]
And?

Overwrite it again with a stronger selector

It IS that simple

**Comment by 43615** [comment]
- rude
- don't know CSS that well, but `*` seems quite strong. Maybe it's the load order of BD? Actual suggestions please.
