### ISSUE TITLE
Translation failed. Try another translator. The daily request limit has been reached.[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by lonnywood** [mwittrien/BetterDiscordAddons#2277]
**Describe the bug**

**To Reproduce**
When does the bug occur.

**Expected behavior**

**Screenshots**

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

**Additional context**

**Comment by mwittrien** [comment]
Not a bug?
