### ISSUE TITLE
[Displaying 99 when user is in 100 servers] - ServerCounter Plugin

### ISSUE THREAD

**Issue by foursplaysroblox** [mwittrien/BetterDiscordAddons#2279]
**Describe the bug**
Hey when I reach a 100 server limit it shows Servers - 99

**To Reproduce**
When 100 server limit is reached

**Expected behavior**
Shows Server - 100 rather than Servers - 99

**Screenshots**
![image](https://user-images.githubusercontent.com/82078139/228096291-0000b70b-bad7-4a43-b299-48f23b36b2cc.png)

**Discord Build (stable, ptb or canary):**
Discord PTB 1.0.1026 Windows 11 10.0.25324

**Additional context**
Video Here

https://user-images.githubusercontent.com/82078139/228096803-d390881f-4a41-45ce-be03-6c75a54dc009.mp4

**Comment by mwittrien** [comment]
Because the actual limit is 99

**Comment by foursplaysroblox** [comment]
![FpnTWFyXgAEChwM](https://user-images.githubusercontent.com/82078139/228215517-33b3b15e-f5b9-4864-bf8a-35a99e637159.png)

shocking moment
