### ISSUE TITLE
[Ugly discord emojis shown rather than the emoji I choose to replace] - EmojiReplace

### ISSUE THREAD

**Issue by foursplaysroblox** [mwittrien/BetterDiscordAddons#2281]
**Describe the bug**
Hello all I was opening the emoji panel to send a goofy ahh emoji but it shows Discord's ugly emojis rather than the Microsoft one but when I click the emoji it goes back to the Microsoft emojis
**To Reproduce**
When I open the emoji icon
**Expected behavior**
Show the Microsoft emojis

**Screenshots**
![image](https://user-images.githubusercontent.com/82078139/228437897-cdd6847d-6e70-4319-94f8-5d231a37ff2f.png)
![image](https://user-images.githubusercontent.com/82078139/228438285-0545108e-7a9f-43f8-9e9f-f8e4a66d036a.png)

**Discord Build (stable, ptb or canary):**
Discord PTB 184621 (7b414a6) Host 1.0.1026 

**Additional context**
That is all

**Comment by mwittrien** [comment]
Use stable
