### ISSUE TITLE
[IMPROVEMENT  NEEDED] - Fix message "message"

### ISSUE THREAD

**Issue by LoganWolfie** [mwittrien/BetterDiscordAddons#2285]
So the message it says before you type something says this
![Screenshot 2023-03-31 023140](https://user-images.githubusercontent.com/72407034/229041501-26c0a70e-0e9f-49d6-8398-db4267dead37.png)
or something similar
but with some specific colors it makes it look like this
![Screenshot 2023-03-31 023111](https://user-images.githubusercontent.com/72407034/229041589-8f788627-323c-488e-bb86-282c2de2482d.png)
can someone add a color changing feature for that little message thing so its not almost invisible? pls and ty :)

**Comment by mwittrien** [comment]
you can already change it via `--channel-text-area-placeholder`

**Comment by LoganWolfie** [comment]
> you can already change it via `--channel-text-area-placeholder`

can i have some help with it? i changed it an nothing happend :/ 
![Screenshot 2023-03-31 153408](https://user-images.githubusercontent.com/72407034/229212915-06ade2b5-ec5d-4933-bb4c-81f86f5ca71f.png)
