### ISSUE TITLE
Recolor not working for new added settings

### ISSUE THREAD

**Issue by LoganWolfie** [mwittrien/BetterDiscordAddons#2287]
> you can already change it via `--channel-text-area-placeholder`

can i have some help with it? i changed it an nothing happend :/ 
![Screenshot 2023-03-31 153408](https://user-images.githubusercontent.com/72407034/229212915-06ade2b5-ec5d-4933-bb4c-81f86f5ca71f.png)

_Originally posted by @LoganWolfie in https://github.com/mwittrien/BetterDiscordAddons/issues/2285#issuecomment-1492494388_

**Comment by mwittrien** [comment]
Its `rgb(255, 255, 255)`

**Comment by LoganWolfie** [comment]
![Screenshot 2023-03-31 213614](https://user-images.githubusercontent.com/72407034/229259516-4bfa872b-a162-4550-86b0-a70fb7754928.png)
still nothing...

**Comment by mwittrien** [comment]
Screenshot your whole Code

**Comment by LoganWolfie** [comment]
> Screenshot your whole Code

![Screenshot 2023-04-01 175953](https://user-images.githubusercontent.com/72407034/229315914-12badd3f-f032-4097-89dd-52f3bfa8e8c8.png)

**Comment by mwittrien** [comment]
Change the value to `rgb(255, 255, 255) !important;`

**Comment by LoganWolfie** [comment]
> Change the value to `rgb(255, 255, 255) !important;`

this worked thank you so much 🙏
