### ISSUE TITLE
App Unexpectedly Switching to Light Theme - PluginRepo

### ISSUE THREAD

**Issue by DekiSystem** [mwittrien/BetterDiscordAddons#2289]
**Describe the bug**
When opening Aliucord on April 1, the theme is set without user consent to light mode and a toast message appears rom PluginRepo

**To Reproduce**
Open app on April 1 for the first time, user theme is force set to light mode

**Expected behavior**
User theme is left unchanged from what the user has set

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Maybe its Discord's april fools joke?

My plugins dont do stuff like that
