### ISSUE TITLE
[IMPROVEMENT] - BDFDB : allow updating from settings

### ISSUE THREAD

**Issue by KaKi87** [mwittrien/BetterDiscordAddons#2291]
**Describe the solution you'd like**
BDFDB would be updatable from BetterDiscord settings, like other plugins are.

**Describe alternatives you've considered**
BDFDB would be updatable from anywhere else than an overlaying element like banners and popups.

**Additional context**
Since updating plugins always freezes the UI for some time, I don't do it when banners appear at startup (i.e. when I need to use Discord), but from settings just before shutting down my computer (i.e. when I don't need to use Discord anymore).

---
Thanks

**Comment by mwittrien** [comment]
It is

Updates need to be manually approved by the plugin mod team for them to appear in BDs Update check. That's why my update check is faster
