### ISSUE TITLE
[edit users dont show context menu entry] - Edit users

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2296]
**Describe the bug**
it dosnt show it in the right click menu and crashes you in some cases

**To Reproduce**
right click a user 

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/229897588-dd937607-9e9e-4727-b2c0-12c9d35968b6.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/25110093/229896956-5096d732-70d1-411b-9552-e0972bd29119.png)

**Additional context**
your ds crash when you right click a user in the server member list and in voice channels
crash log when it crashes:
![image](https://user-images.githubusercontent.com/25110093/229898042-fe225b71-1c4e-4792-bb71-a37d8de44b46.png)

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
