### ISSUE TITLE
[BUG] Translator Plugin missing right click translator

### ISSUE THREAD

**Issue by Firesparq** [mwittrien/BetterDiscordAddons#2298]
Right clicking a message doesn't provide the option to translate message using configuration since the latest update.
Enabling the translate option when sending a message translates as expected.

![image](https://user-images.githubusercontent.com/5128869/229957171-e287ced0-26fc-4004-b527-b105c0d5b2d3.png)

![image](https://user-images.githubusercontent.com/5128869/229957201-c2790071-aa71-458b-ad73-fc8145327e16.png)

**Comment by Cy9oz** [comment]
I suddenly can't translate either!
When I send a message, I have translation turned on, but nothing comes up!

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
