### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by YexyIsSexy** [mwittrien/BetterDiscordAddons#2300]
**Describe the bug**
The ImageUtilities plugin doesn't display the options it should when clicking an image (eg 'Save Image', 'Copy Image') and the zoom function doesn't work.

**To Reproduce**
Use any recent version of ImageUtilities (I've gone back a few versions to see if that was the problem, it was not. I originally thought this was a Library problem, turns out it is not. I thought 0BDFDB ver 3.2.5 was the problem, went back to ver 3.2.3 and it worked _once_ and stopped showing up again.)

**Expected behavior**
Images should have plugin Save/Copy options on right-click, zoom should work when clicking on an image.

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher

**Comment by YexyIsSexy** [comment]
thank you!
