### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by panos78** [mwittrien/BetterDiscordAddons#2302]
**Describe the bug**
The option to translate the context menu disappeared.

**To Reproduce**
After the last update of BDFB, the option disappeared.

**Expected behavior**
The Context menu used to have an option to translate the text under cursor but this option disappeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/3087817/230363239-d0a5d84c-c7ae-44be-b2d8-9abb53fe51a1.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/3087817/230363408-0490b119-98c1-49ad-b66f-be2f5d7fad8a.png)

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
