### ISSUE TITLE
[BUG] - ServerHider

### ISSUE THREAD

**Issue by wikibamxd** [mwittrien/BetterDiscordAddons#2304]
**Describe the bug**
The menu that normally appears to be able to use the plugin dosen't appear

**To Reproduce**
right clicking any server

**Expected behavior**
for the UI of the plugin to appear

**Screenshots**
If applicable, add screenshots to help explain your problem. https://i.imgur.com/7dXAI0n.png, and im using the devilbro library as supposed.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
-

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
