### ISSUE TITLE
[BUG] - CopyRawMessage not working

### ISSUE THREAD

**Issue by jericjan** [mwittrien/BetterDiscordAddons#2305]
**Describe the bug**
When I right click, I do not find the option to copy a message's raw contents.

**To Reproduce**
1. Install BDFDB
2. Install CopyRawMessage 
3. Right click any message

**Expected behavior**
An option to copy raw contents should pop up.

**Screenshots**
![image](https://user-images.githubusercontent.com/38642145/230597263-38725817-7b57-4026-9e63-b3e9be22db93.png)

**Discord Build (stable, ptb or canary):**
Stable 187377 (f9a878e)

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
