### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by amitraviverma** [mwittrien/BetterDiscordAddons#2306]
**Describe the bug**
Pin DM option not showing.

**To Reproduce**
installed PinDMs plugin. installed supported library too.

**Expected behavior**
no option to PinDM.

**Screenshots**
![image](https://user-images.githubusercontent.com/64060423/230691143-5e33ae0c-1514-4d6a-8a88-af0f52ffcc46.png)
![image](https://user-images.githubusercontent.com/64060423/230691152-49c49ea6-7dab-464a-8528-a4e0bf204450.png)

**Discord Build (stable, ptb or canary):**
Stable 187599 (c2dd678)
Windows 10 64-Bit (10.0.19044)

**Additional context**
tested on 08/04/2023

**Comment by mwittrien** [comment]
Issue with BD that i cant fix

Wait till BD fixes it context menu patcher
