### ISSUE TITLE
Crashes on content load - ImageUtilities

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [mwittrien/BetterDiscordAddons#2308]
Having the plugin crashes BD when joining a chat with visible images/gifs

Occurs every time, afais. Originally I thought it could be due to a conflicting plugin (I daily drive 20~), but even attempting to run it in isolation leads to a crash.

Using the latest BD 1.9.2 build & Stable discord build & IU V5.2.2

Let me know if there's any more information you need. Cheers.

**Comment by mwittrien** [comment]
Got an example gif?

**Comment by Shaniquaniminiquani** [comment]
>Got an example gif?

Any of them work. Doesn't even have to be a gif, images work as well. Its an insta crash when the image is visible upon opening the dm/server. If it's not visible on opening it won't crash however scrolling into it none of the features will visibly work (ie, quick download link & file size/name) and clicking on it leads to a crash as well. 

I can include a video if you'd like, but It'd literally just show the client crashing

**Comment by mwittrien** [comment]
Just tested and it does not crash for me

mioght be a plugin conflict

**Comment by Shaniquaniminiquani** [comment]
Hmm was prompted to update today to V5.2.4 and it seems to work fine now, whatever got changed was probably the cause. 
No worries
