### ISSUE TITLE
ServerFolders 10th folder not showing up in add list

### ISSUE THREAD

**Issue by parkerlreed** [mwittrien/BetterDiscordAddons#231]
10th folder doesn't show up in list of folders that can be added to. I've tried many different names with no luck.

![image](https://user-images.githubusercontent.com/841440/60847961-af5eff80-a1b2-11e9-97a8-b403a92cd63f.png)

**Comment by mwittrien** [comment]
Scroll down .........

**Comment by parkerlreed** [comment]
Oh... derp. Couldn't see the scrollbar and I haven't run into a menu list that scrolls before (In hindsight add reaction does but I always use the dedicated button)

Thanks!
