### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME baidu api  error

### ISSUE THREAD

**Issue by linlinglin** [mwittrien/BetterDiscordAddons#2311]
**Describe the bug**
default setting and  return back: Invalid Sign

then i edit the js .
delete credentials . rebuild new as this
//-----
line 1148:
const salt = BDFDB.NumberUtils.generateId();
const appid = ("20211029000985666"); //20211029000985666   my account
const passwd = ("vl4ZUv5FFh5BN7uL4x_7"); //vl4ZUv5FFh5BN7uL4x_7 account's passwd
//-----
sign: this.MD5(appid + data.text + salt + passwd)
//-----

then it works .

**Comment by mwittrien** [comment]
can't replicate your issue,
if i try the baidu translator with the credentialsin my JS version the result is
Error: 54004 please recharge
because too many ppl already used the baidu version with the default credentials

**Comment by linlinglin** [comment]
may u try my account? i hava posted.
20211029000985666 my account
vl4ZUv5FFh5BN7uL4x_7 account's passwd

**Comment by mwittrien** [comment]
With your account it says invalid sign

**Comment by linlinglin** [comment]
yes. i rewrite ur code and it works.
so i guess that may it get account or passwd error .
 split "credentials" and rewrite "appid" and "passwd"  will work.

 rebuild new
//-----
line 1148:
const salt = BDFDB.NumberUtils.generateId();
const appid = ("20211029000985666"); //20211029000985666 my account
const passwd = ("vl4ZUv5FFh5BN7uL4x_7"); //vl4ZUv5FFh5BN7uL4x_7 account's passwd
//-----
sign: this.MD5(appid + data.text + salt + passwd)
//-----

**Comment by linlinglin** [comment]
thanks.
