### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor - Light mode support

### ISSUE THREAD

**Issue by zulc22** [mwittrien/BetterDiscordAddons#2322]
**Describe the solution you'd like**
As it is now, DiscordRecolor on default settings doesn't have any alternate light color scheme. Changing Discord to light mode just forces it to DiscordRecolor's default dark colors.

The default .css could contain an optional section for light colors, including sane defaults and labels for them.

Along with this, a few of hardcoded values defined in BlurpleRecolor will need to be changed to be based on user-facing variables.

Specifically, things that jump out at me in BlurpleRecolor are `--info-help-text` (white) and `--brand-(100..300, 700..900)` (a light and dark color ramp, `experiment` and `new` as well)

**Describe alternatives you've considered**
all of this can be done manually by the user, but it ends up kind of detracting from the entire point that it's a CSS file you just import and set a few variables for, and requires a lot of manual work from the user which necessitates they know how to style things with CSS already, and it's very very likely they will do it worse and in a less clean and reliable way than you.

**Comment by mwittrien** [comment]
The whole point of the theme is it to allow you to recolor discord (no matter which theme mode) 

Saying DiscordRecolor doesn't support light themes is simply false just change the variables to a light color sheme

**Comment by mwittrien** [comment]
I dont see how difficult it is to change a few variables

**Comment by zulc22** [comment]
the reason I had said it "doesn't", is because several elements are hardcoded for dark, despite having set all the colors to a light scheme

**Comment by mwittrien** [comment]
Well the theme changes colors that change when you switch between light and dark mode

Some stuff is bound to be forced to white or black font because it wouldnt be readable otherwise

**Comment by zulc22** [comment]
...but is that not exactly what using the text color variables would solve? because `--textbrightest` will be the brightest on dark, and the darkest on light.
