### ISSUE TITLE
[BUG] - ServerDetails - Don't adapt popup with the bottom of the screen

### ISSUE THREAD

**Issue by PixelGuy123** [mwittrien/BetterDiscordAddons#2324]
**Describe the bug**
Basically the popup that shows up all the server info don't adapt with the position it is currently in, leaving a very unpleasant popup with details I literally can't see

**To Reproduce**
Just have a whole list of servers that reaches the bottom, and hover the mouse on a server that is near the bottom of the screen

**Expected behavior**
To the popup go a little up, so I could read it

**Screenshots**
![Discord_oUI3jSAMGz](https://user-images.githubusercontent.com/89644121/232162875-d4ec46ec-6611-4e18-b6b8-55adb6d81367.gif)

(Note: I'm using the shift option)
On the first attempt, I first hover the mouse over the icons, and press shift, you see how the bottom ones are unreadable
On the second attempt, I first hold shift and again hover the mouse on the icons, but this time they do function properly

**Discord Build (stable, ptb or canary):**
Stable 189494

**Comment by mwittrien** [comment]
Have you tried without a theme?

**Comment by PixelGuy123** [comment]
Yup, just disabled all themes and tried out again, same issue

**Comment by PixelGuy123** [comment]
I just downloaded the v1.1.5 you released there, and I literally see no changes on this bug, which seems like you didn't really fixed it.
So just to rewind here, the issue is: enable shift option, go to the server list and find an icon which is near the bottom of the screen, hover the mouse over it and press shift, it should go way under the screen making it unreadable
