### ISSUE TITLE
[BUG] Some Plugins Are Outdated" for Up-to-date plugins - PluginRepo

### ISSUE THREAD

**Issue by jetblackrx89** [mwittrien/BetterDiscordAddons#2325]
**Describe the bug**
Reopening #2275 as it was closed without much explanation and doesn't appear to be resolved in PluginRepo 2.5.0. This may need to be split into two bugs but:

1) If a plugin was abandoned by a dev and raises a "could not compile" error, PluginRepro repeatedly claims an update exists when one does not. The red top banner appears constantly.

2) If the update banner is disabled, the "check for updates" button becomes completely non-functional for manually checking for updates and doesn't fetch even legitimate updates.

**To Reproduce**
Simply install an abandoned plugin like:
* [StatusEverywhere](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/StatusEverywhere/StatusEverywhere.plugin.js)
* [WhoReacted](https://raw.githubusercontent.com/jaimeadf/BetterDiscordPlugins/release/dist/WhoReacted/WhoReacted.plugin.js) (**Update**: Plugin has since been updated by the dev.)

**Expected behavior**
For issue 1, no banner should appear claiming there are updates. For issue 2, a user should be able to manually check for updates and it should fetch legitimate updates for plugins that have new versions available.

**Screenshots**
![Screenshot 2023-04-14 at 9 23 02 PM](https://user-images.githubusercontent.com/7515801/232176487-53011eed-1f8f-4457-8972-31657da436ee.png)
![Screenshot 2023-04-14 at 9 23 24 PM](https://user-images.githubusercontent.com/7515801/232176490-43f11d10-8a44-4a70-9f27-a5f5f7478690.png)

**Discord Build (stable, ptb or canary):**
Stable 0.0.274.

**Additional context**
N/A.

**Comment by mwittrien** [comment]
I can't reproduce your first bug as I already mentioned in the bug report by other users

**Comment by mwittrien** [comment]
Second issue was fixed just now
