### ISSUE TITLE
[BUG] Crashing Discord - BetterFriendList

### ISSUE THREAD

**Issue by StellarWitch642** [mwittrien/BetterDiscordAddons#2327]
**Describe the bug**
Discord gives the crash page when opening the "hidden" tab with a status filter active. 

**To Reproduce**
Activate a status filter before swapping to the hidden friends tab. 

**Expected behavior**
The Discord crash page should show up. 

**Discord Build (stable, ptb or canary):**
I'm using the stable Discord build.

**Comment by mwittrien** [comment]
Can you take an example video
