### ISSUE TITLE
[IMPROVEMENT] - Translator setting to auto translate received messages

### ISSUE THREAD

**Issue by Firesparq** [mwittrien/BetterDiscordAddons#2329]
I often spend a lot of time on non-english speaking discord servers, so having the ability to set a setting that will automatically translate messages I receive in channel would be very handy.

I had thought that this was already a feature using this section in the settings
![image](https://user-images.githubusercontent.com/5128869/232279021-2f785c98-17a2-4a05-822d-84669e451864.png)

However it doesn't seem to work. Am I perhaps using it incorrectly? And if not, then could we add this functionality?

**Comment by mwittrien** [comment]
Not posaible due to api request limits
