### ISSUE TITLE
[IMPROVEMENT] - NotificiationSounds: Toggle Sounds on/off

### ISSUE THREAD

**Issue by Detet** [mwittrien/BetterDiscordAddons#2342]
**Describe the solution you'd like**
Function to toggle the sounds on/off for Discord for those who are in offline mode and do not want to get disturbed :)

**Describe alternatives you've considered**
Keybind, a switch in discord like a button or something like that

Also thanks for this awesome addon, finally I can respond when someone mentions me swiftly, and set a specific sound for dm's while removing the annoying general message sounds 👍

**Comment by mwittrien** [comment]
Ill add an option to mute sounds in offline similar to the dnd and streaming options
