### ISSUE TITLE
[BUG] - BasicBackground - Conflicts with Nitro colour theme

### ISSUE THREAD

**Issue by roguesensei** [mwittrien/BetterDiscordAddons#2344]
**Describe the bug**
BasicBackground conflicts with discord Nitro's Themes, more noticeable when using a transparent image for background.
The theme takes priority in the settings menu, but gets overridden when using the rest of the application.

**To Reproduce**
Select any of the nitro colour themes and leave settings menu.

**Expected behavior**
BasicBackground should take priority over Nitro's theme. This happens in the settings menu but not anywhere else.

**Screenshots**
Settings menu (any):
![image](https://user-images.githubusercontent.com/32780495/233694377-9003d9d1-cfa9-4cdb-8287-2e9b47b6a650.png)

Elsewhere in app (Some elements, such as the highlighted "Hidden" tab, respect theme):
![image](https://user-images.githubusercontent.com/32780495/233694746-8d61c4ad-4b96-42ae-8333-de6471244549.png)

**Discord Build (stable, ptb or canary):**
Stable 191026 (a46172d)
Host 0.0.26
Better Discord Core v1.9.2

**Additional context**
If it's applicable, my OS is Linux 64-Bit (6.2.10-Arch1-1).

**Comment by mwittrien** [comment]
Don't use Nitro Theme while using a BD Theme, why would you use something that isnt compartible

that's like using two BD Themes at the same time

**Comment by roguesensei** [comment]
It's just something I noticed, I'm not fussed either way, no need to be rude about it.
