### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by shawny43** [mwittrien/BetterDiscordAddons#2346]
**Describe the bug**

**To Reproduce**
Add custom sound
Make a call
Hear the sound

**Expected behavior**
Sound are buggy and cut anytime. Such like restart sounds.

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 191743 (b61e73b)
**Additional context**

**Comment by mwittrien** [comment]
Works fine for me
