### ISSUE TITLE
[BUG] - CopyRawMessage and ImageUtilities breaks reaction picker from right-click menu

### ISSUE THREAD

**Issue by TheOpponent** [mwittrien/BetterDiscordAddons#2347]
**Describe the bug**
When the CopyRawMessage and ImageUtilities plugins are enabled, the behavior of the reactions dialog changes negatively. The picker opens as normal, but it forcibly reopens when the mouse cursor moves over the post. This is disruptive when the user searches for an emoji by name, then moves the cursor to pick a matching emoji, only for it to be lost when the dialog refreshes irrespective of any input given to it before that point. The only workaround is to move the mouse over the post first before searching for emojis, which is counter-productive to the common workflow of typing before picking an emoji. 

**To Reproduce**
Enable CopyRawMessage and ImageUtilities, then right-click on a message and click Add Reaction. The reactions menu will open. Type some text to search for an emoji. Move the cursor toward the reaction dialog, then the menu will close and reopen. Any search results are lost. 

**Expected behavior**
The reaction dialog does not close and reopen when the mouse moves over the post it is focused on.

**Screenshots**
n/a

**Discord Build (stable, ptb or canary):**
Stable 191743 (b61e73b) Host 1.0.9012 (31760) Windows 10 64-Bit (10.0.19045)

**Additional context**
This does not occur when only one of these plugins are enabled, or if the reaction picker is opened with the button that appears in the top-right area when hovering over a post.

**Comment by mwittrien** [comment]
The Issue is unrelated to ImageUtilities and happens even with only CopyRawMessage enabled

Ill try to fix it someday

**Comment by Mefuuu** [comment]
is it fixed?

**Comment by mwittrien** [comment]
Closed since CopyRawMessage is discontinued
