### ISSUE TITLE
[Server Folders] It suddenly went WTF

### ISSUE THREAD

**Issue by TotoShampoin** [mwittrien/BetterDiscordAddons#235]
Hello! 
So, this is what happens now : 
Closed folder ![image](https://user-images.githubusercontent.com/41761945/61336985-c4cbcd80-a833-11e9-9ad0-26babb24fde5.png) Open folder ![image](https://user-images.githubusercontent.com/41761945/61337018-e5942300-a833-11e9-9601-9780eb94f515.png)

We can slightly see the servers. We can move the folder to the servers so it looks normal, but nothing appear when you open the folders.

It happened suddenly, after my first time using Ctrl+R. 
I tried rebooting discord, deactivating every plugins and themes, reinstalling the plugins, deleting the config file... Nothing helps! 

What suddenly happened??

**Comment by Reshiram110** [comment]
Can confirm, server folders are currently broken.
![image](https://user-images.githubusercontent.com/26460940/61337629-3429c900-a804-11e9-8b4e-b22a9d7db3c0.png)

**Comment by Barisukan** [comment]
This seems to be the issue: 
![image](https://user-images.githubusercontent.com/52223727/61338717-9d531180-a7ef-11e9-99ec-f93c9688ab44.png)

**Comment by SDCore** [comment]
Can confirm, I'm having the same issue.
![Discord_BjuG09OhoT](https://user-images.githubusercontent.com/5140203/61346581-f4240f80-a81e-11e9-9c22-2157a43939ef.png)
![Discord_hXkXtCNhuQ](https://user-images.githubusercontent.com/5140203/61346582-f4240f80-a81e-11e9-8972-a38f8cc0c69b.png)

**Comment by Infinidoge** [comment]
Can confirm as well
![image](https://user-images.githubusercontent.com/22727114/61347712-f2147d80-a82b-11e9-99ed-964799cb02c5.png)
![image](https://user-images.githubusercontent.com/22727114/61347747-107a7900-a82c-11e9-96c5-52398817004a.png)

**Comment by FiireWiinter** [comment]
Can confirm
![Screenshot_1](https://user-images.githubusercontent.com/53000324/61366761-7e558d80-a88a-11e9-88de-c5911ab34e16.png)
