### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities: keyboard shortcut for saving images

### ISSUE THREAD

**Issue by 4xMSAA** [mwittrien/BetterDiscordAddons#2351]
**Describe the solution you'd like**
Be able to press a modifier key or combination of modifier keys to save images/image URLs on left or right click without navigating the context menu or opening up the popup view.

**Describe alternatives you've considered**
I haven't noticed any alternatives or any related functionality in the code regarding `downloadFile`, so I'd be open for suggestions how to do the process faster.

**Additional context**
I have a mass amount of images I'd like to save, atleast ~200 and opening the context menu for each or having to click the buttons with inconsistent positions specifically is rather tedious.

**Comment by mwittrien** [comment]
Too much effort for an action that shouldnt occur so often
