### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by Fumi8481** [mwittrien/BetterDiscordAddons#2354]
**Describe the bug**
There was an unexpected error. Click to open console for more details

**To Reproduce**
clicking on the gear Icon 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/122705538/236387805-78678b58-7c90-4925-9d6f-c423f2478f0f.png)

This also happens to ShowConnections

![image](https://user-images.githubusercontent.com/122705538/236388170-362b5792-795c-4f2d-b9bd-917e142794b9.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I have also re opened discord many times but still it does not work

**Comment by mwittrien** [comment]
Redownload BDFDB and delete 0BDFDB.data.json in your plugins folder
