### ISSUE TITLE
[BUG] - Notifications sounds/Laggy and looping sound

### ISSUE THREAD

**Issue by TakenMC** [mwittrien/BetterDiscordAddons#2355]
**Describe the bug**
Everytime I would try to use my call sound it would stop playing then start playing again and again. Sometimes it also would lag.

**To Reproduce**
For me it just breaks with no tweaking at all of the default better discord settings. You just hit call and it occurs

**Expected behavior**

**Screenshots**
For the sound to play from start to finish

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I don't have anything to mention as of rn.

**Comment by mwittrien** [comment]
Use a shorter Sound File
