### ISSUE TITLE
[IMPROVEMENT] - Plugin for adding more forum tags locally

### ISSUE THREAD

**Issue by Rueby** [mwittrien/BetterDiscordAddons#2356]
**Describe the solution you'd like**
I'm not sure if it's in a similar vein to editing users/servers locally. However, I'm wondering if it's possible to have a plugin that allows more than 5 tags (the limit) per post? Or does that impossible functionally speaking?

**Describe alternatives you've considered**
If functionally it's impossible, is it possible to add extra tags that are purely cosmetic?

**Additional context**
Abit like this? This is rough idea/suggestion, but it'd let you select emotes like the regular tags but local tags can be separated by something? Perhaps be on a different line?

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/92205577/8ea5f5d2-2433-439b-8867-14b98520ad69)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/92205577/cddfb37f-b758-4e35-8130-85c9835d5588)

**Comment by mwittrien** [comment]
I am not making new plugins
