### ISSUE TITLE
preview messange after the send impostation - translator

### ISSUE THREAD

**Issue by speedlorenzo12** [mwittrien/BetterDiscordAddons#2358]
**Describe the solution you'd like**
a useful setting to have a preview or as a warning before sending the translated message to understand first if there are errors and correct them as soon as the message has been sent and decide whether to send it or not(If anyone wants to understand better I can send a screenshot from a another client)

**Comment by mwittrien** [comment]
You can already highlight the whole message in your chat input and then right click the highlight and press `search translation`
this will kinda give you a preview of what the translated text will be
