### ISSUE TITLE
[IMPROVEMENT] - BDFDB laggy switches

### ISSUE THREAD

**Issue by Werfire** [mwittrien/BetterDiscordAddons#2359]
When BDFDB is in plugins folder, servers and channels are switched much slower.
Sad, because it's only downside of using BetterDiscord currently with all your awesome by themselves plugins.

**Describe the solution you'd like**
Channel and server switch is optimized when BDFDB is present

**Comment by mwittrien** [comment]
Plugins do have an inpact on resource usage
