### ISSUE TITLE
Server Folders feature request - Don't close when in a server inside the folder

### ISSUE THREAD

**Issue by Two-Tone** [mwittrien/BetterDiscordAddons#236]
The idea is pretty simple: When I move into a server inside a folder I don't want the folder to close, but if I move to a server or DM outside the folder I'd like it to automatically close.

**Comment by Chosen-Fate** [comment]
And why the hell do you comment this on a plugin pack?? Just write the discord support

**Comment by Two-Tone** [comment]
You do know that server folders has been a BD plugin long before it was an
official feature? It's one of the plugins that is maintained in the git
repo.

**Comment by Chosen-Fate** [comment]
Yeah I know, but whats the point in using a plugin then?

**Comment by Two-Tone** [comment]
When I made this feature request the plugin was the only way to get
folders.

And if you knew, why did ask why I was commenting this here, like this is
somehow not the appropriate place to request a feature for a plugin
maintained in this git?

**Comment by mwittrien** [comment]
Enable: Close All Folders when selecting a Server.
Enable: Force a Folder to open when switching to a Server of that Folder.

This will close all folders except for the folder of the selected server when selecting a server
