### ISSUE TITLE
Assign badges for local viewing - Edit Users

### ISSUE THREAD

**Issue by Vezifer** [mwittrien/BetterDiscordAddons#2362]
**Describe the solution you'd like**
Add the ability to add all badges locally with a toggle for each one, Edit Users currently allows you to change basically everything about the user popout letting you set custom avatars, banners & Profile Themes. Although this is for local viewing only it'll still be a nice feature to have implemented.

**Describe alternatives you've considered**
There was a plugin called "AssignBadges" that used to work but with Discord past updates it broke the plugin and the Developer has been MIA for a good year now.

**Additional context**

**Comment by mwittrien** [comment]
Thats something i never wanted to add to EditUsers

Youll need to wait till someone  fixes AssignBadges
