### ISSUE TITLE
[IMPROVEMENT] - Plugin Repo | Verified plugin icon

### ISSUE THREAD

**Issue by Mantas-2155X** [mwittrien/BetterDiscordAddons#2363]
**Describe the solution you'd like**
Display a verified symbol/icon next to installed plugins that came from [https://betterdiscord.app](https://betterdiscord.app), making sure that the files are unmodified from the currently verified version on the website.

**Describe alternatives you've considered**
/

**Additional context**
This will help quickly knowing which plugins are verified to be safe, allowing users to easier find plugins that were manually installed from unverified sources.

**Comment by mwittrien** [comment]
All plugins are from the BD  website and unmodified

**Comment by Mantas-2155X** [comment]
Oh, my bad. 
Meant to make this issue on the BetterDiscord repo as viewing installed plugins is a feature of BD. :laughing:
