### ISSUE TITLE
[BUG] - CompleteTimestamps no option to omit seconds

### ISSUE THREAD

**Issue by jojo2357** [mwittrien/BetterDiscordAddons#2367]
This is as much a feature request as it is a bug report.

What I *want* is for chat message timestamp to be of the form `H:i` (php format string) instead of the clunky `H:i:s`. 

Turning off chat messages gives me `h:i a` which is also unacceptable. The workaround that I currently have is to switch my language to "proper english" but then i get red squiggles for omitting extra letters from the likes of colo***u***r, which is also undesirable. 

A better way to fully customize the timestamp (including leading zeros on the hour) would be much appreciated.

**Comment by mwittrien** [comment]
You can fully customize the timestamp in the plugin settings

**Comment by jojo2357** [comment]
I disagree, the only customization i have is `$time` and `$time12`. I want to have `$time` but without the seconds.

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/66704796/375eba85-ff82-4506-b7d0-63267571a97c)

Please tell me how to do that then, as it is not clear

**Comment by jojo2357** [comment]
In OBDFDB.plugin.js, line 5853, it is clear that I can only pass `$date`, `$time`, `$time12`, `$monthS?`, `$dayS?`, and a few others

```js
return (data.formatString || Internal.LibraryComponents.DateInput.getDefaultString(language))
	.replace(/\$date/g, date)
	.replace(/\$time12/g, data.timeString && typeof data.timeString == "string" ? Internal.LibraryComponents.DateInput.formatTime({timeString: data.timeString, language: language}, timeObj, true) : timeObj.toLocaleTimeString(language, {hourCycle: "h12"}))
	.replace(/\$time/g, data.timeString && typeof data.timeString == "string" ? Internal.LibraryComponents.DateInput.formatTime({timeString: data.timeString, language: language}, timeObj) : timeObj.toLocaleTimeString(language, {hourCycle: "h23"}))
	.replace(/\$monthS/g, timeObj.toLocaleDateString(language, {month: "short"}))
	.replace(/\$month/g, timeObj.toLocaleDateString(language, {month: "long"}))
	.replace(/\$dayS/g, timeObj.toLocaleDateString(language, {weekday: "short"}))
	.replace(/\$day/g, timeObj.toLocaleDateString(language, {weekday: "long"}))
	.replace(/\$agoAmount/g, daysAgo < 0 ? "" : daysAgo > 1 ? Internal.DiscordObjects.Timestamp(timeObj.getTime()).fromNow() : BDFDB.LanguageUtils.LanguageStrings[`SEARCH_SHORTCUT_${daysAgo == 1 ? "YESTERDAY" : "TODAY"}`])
	.replace(/\$agoWeekdayS/g, daysAgo < 0 ? "" : daysAgo > 1 ? timeObj.toLocaleDateString(language, {weekday: "short"}) : BDFDB.LanguageUtils.LanguageStrings[`SEARCH_SHORTCUT_${daysAgo == 1 ? "YESTERDAY" : "TODAY"}`])
	.replace(/\$agoWeekday/g, daysAgo < 0 ? "" : daysAgo > 1 ? timeObj.toLocaleDateString(language, {weekday: "long"}) : BDFDB.LanguageUtils.LanguageStrings[`SEARCH_SHORTCUT_${daysAgo == 1 ? "YESTERDAY" : "TODAY"}`])
	.replace(/\$agoDays/g, daysAgo < 0 ? "" : daysAgo > 1 ? BDFDB.LanguageUtils.LanguageStringsFormat(`GAME_LIBRARY_LAST_PLAYED_DAYS`, daysAgo) : BDFDB.LanguageUtils.LanguageStrings[`SEARCH_SHORTCUT_${daysAgo == 1 ? "YESTERDAY" : "TODAY"}`])
	.replace(/\$agoDate/g, daysAgo < 0 ? "" : daysAgo > 1 ? date : BDFDB.LanguageUtils.LanguageStrings[`SEARCH_SHORTCUT_${daysAgo == 1 ? "YESTERDAY" : "TODAY"}`])
	.replace(/\(\)|\[\]/g, "").replace(/,\s*$|^\s*,/g, "").replace(/ +/g, " ").trim();
```

Any other formats are consumed by the trailing regexes.

### What I want
is to expose `formatTime` which *does* have exactly what i want!

```js
let string = data.timeString
	.replace(/\$hh/g, hours < 10 ? `0${hours}` : hours)
	.replace(/\$h/g, hours)
	.replace(/\$mm/g, minutes < 10 ? `0${minutes}` : minutes)
	.replace(/\$m/g, minutes)
	.replace(/\$ss/g, seconds < 10 ? `0${seconds}` : seconds)
	.replace(/\$s/g, seconds)
	.replace(/\$uu/g, milli < 10 ? `00${seconds}` : milli < 100 ? `0${milli}` : milli)
	.replace(/\$u/g, milli).trim();
```

If I had access to this, I would use the format `$hh:$mm` with the `hour12` flag unset.

So, do I have to edit the plugin as described to get what I want, or can this be made an option? Can there be a secret menu so i can add my own data format? Can this issue please be reopened?

PS: [`String.prototype.padStart`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) is a thing, so you could do `` `${hours}`.padStart(2, '0')``, or to make ``milli < 10 ? `00${seconds}` : milli < 100 ? `0${milli}` : milli`` into `` `${milli}`.padStart(3, '0')``

**Comment by mwittrien** [comment]
Maybe click the clock icon
