### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by Hi-ImKyle** [mwittrien/BetterDiscordAddons#2368]
**Describe the bug**
Errors on load

**To Reproduce**
Install 2.5.5, load, error

**Expected behavior**
For it to load

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/25551312/1e1d04e7-0f10-491e-967b-9293f46beb58)

**Discord Build (stable, ptb or canary):**
Stable 201332 (10d1e45) 
Host 1.0.9013 (32266) 
Windows 10 64-Bit (10.0.19043)

**Additional context**
enhancecodeblocks, ImageUtilities, LinkBanner, NoReplyPing, PermissionsViewer, PluginRepo, ReadAllNotificationsButton, removeTrackingURL, SecretRingTone, SplitLargeMessages, StickerEmojiPreview, ThemeRepo, Timezones and Translator are the plugins I have installed.

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord
