### ISSUE TITLE
Server Folders Bug

### ISSUE THREAD

**Issue by T0xicFX** [mwittrien/BetterDiscordAddons#237]
Yesterday i got a bug that glitches the position of the folders i made
Preview: http://prntscr.com/og5pyf

**Comment by KaKi87** [comment]
This is not a bug, but an incompatibility due to the last Discord client update.
However, I can confirm this is happening.

**Comment by silent** [comment]
#235 already exists

**Comment by KaKi87** [comment]
Duplicate of #235

**Comment by TotoShampoin** [comment]
I don't really mind being duplicated, that only shows it being an actual issue easier... 
But yeah, you duped my post #235
