### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities : append ?size= to profile banner view image

### ISSUE THREAD

**Issue by GenesisAria** [mwittrien/BetterDiscordAddons#2374]
Title says it - images load the straight .png and don't append ?size=4096 (or other) so they load the smallest variant it seems.

**Comment by mwittrien** [comment]
Size 4096 images cant be loaded within Discord

**Comment by GenesisAria** [comment]
The avatar images load the 4096 version if you click view image.  Appending the size tag should cause it to fetch the larger res image which could be showed in the panel too.

**Comment by GenesisAria** [comment]
Perhaps you misunderstood what i was suggesting.

**Comment by mwittrien** [comment]
They arent fetchable

Try it yourself you will run into a CORS issue
