### ISSUE TITLE
[BUG] - Personal Pins - Not showing "Save message" button

### ISSUE THREAD

**Issue by Rayjacker** [mwittrien/BetterDiscordAddons#2375]
**Describe the bug**
The button in the right-click context menu to save or delete pins no longer shows.

**To Reproduce**
Right click on a message to save it.

**Expected behavior**
"Save message" button appears so I can save messages.

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 203670 (1d87dbe) Host 1.0.9013 (32266) Windows 10 64-Bit (10.0.19045)

**Additional context**
You can still see previous saved messages, it's only in the right-click context menu where it doesn't show. And before it stopped showing altogether, the button showed on top of the Reactions instead of a standard position.

Edit : Might be a BetterDiscord issue, there is an open issue here [https://github.com/BetterDiscord/BetterDiscord/issues/1631](url) for context menu patching issues.

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631

**Comment by Rayjacker** [comment]
I manually installed the asar file from the fix : https://github.com/BetterDiscord/BetterDiscord/actions/runs/5217657866 and PersonalPins still does not show in the context menu
