### ISSUE TITLE
[BUG] - EditChannels, EditUsers, EditRoles, EditServers

### ISSUE THREAD

**Issue by IlyaSr07** [mwittrien/BetterDiscordAddons#2376]
**Describe the bug**
The "Local Channel/User/Role/Server settings" option doesn't appear in the context menu upon right clicking the channel/user/role/server.

**To Reproduce**
This bug occurs when I right click the channel/user/role/server.

**Expected behavior**
I expected the "Local Channel/User/Role/Server settings" option to appear in the context menu, as showed by the screenshots in the README.txt file in the plugins' repositories.

**Screenshots**
Channel
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/112248447/778fbf4b-1060-40c9-b182-5a84fbb70ce7)
User
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/112248447/926f1c3a-4973-461b-8724-9e6ee6b45828)
Role
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/112248447/c1b9ebf1-84d8-4ad9-b109-2751579edc81)
Server
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/112248447/ebbc29b2-a185-4a73-ae3a-a3cdddbb59d5)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
