### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by eddisch** [mwittrien/BetterDiscordAddons#2377]
**Bug**
I can't edit it! the menu just doesn't exist and I can't see it.

**To Reproduce**
Try installong. Done. Reproduced.

**Expected behavior**
I think the button that leads to the editor should be visible... right?

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/dba42e96-b62a-4f64-9a35-9335bc59255b)
![Screenshot 2023-06-09 214149](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/60500d2c-9617-4e4d-b381-bfeccc6da941)
![Screenshot 2023-06-09 214154](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/18eda098-73a2-4771-933f-b8357123b7a0)
![Screenshot 2023-06-09 214201](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/17706d32-45ad-4858-adf1-e3e788beda66)
![Screenshot 2023-06-09 214208](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/6f168b17-6cb0-404b-bb58-b980439beb82)
![Screenshot 2023-06-09 214212](https://github.com/mwittrien/BetterDiscordAddons/assets/73175017/2a15e6ed-ff5c-41e5-b175-a90756f770d1)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Mhm.

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
