### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by Firesparq** [mwittrien/BetterDiscordAddons#2379]
**Describe the bug**
"Translate message" in message context menu is missing

**To Reproduce**
Right click a message for translation

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/5128869/1cc799bd-7176-4af5-aa1b-f6b8c6c68fba)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/5128869/a0020add-0c39-48a1-82ba-78a3ff756e2b)

**Discord Build (stable, ptb or canary):**
Stable 204204 (942e9ba) 
Host 1.0.9013 (32266) 
Windows 10 64-Bit (10.0.19045)
BetterDiscord Core v1.9.2

**Comment by anjinnan** [comment]
我也是这个问题
I'm the same with this issue

**Comment by anjinnan** [comment]
https://discord.com/channels/86004744966914048/1116779967951425687
discord上面好像说要等修复

**Comment by Boschy69** [comment]
for me the translate option when holding shift on a message is gone, its still there when i click on the 3 dots but not in the quick menu.

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
