### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by Korgi2** [mwittrien/BetterDiscordAddons#2380]
**Describe the bug**
ImageUtilities doesn't appear on right click context menu when right clicking on media.

**To Reproduce**
1. Install ImageUtilities
2. Right click on image or video.

**Expected behavior**
Right clicking on image causes context menu from plugin to appear.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/61196219/13f95cc4-43ec-43c4-bdb6-59b584a39601)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/61196219/0e92acf9-799a-4c57-bf71-274516e8005a)

**Discord Build (stable, ptb or canary):**
Stable 204091 (06f8dd8)

**Additional context**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/61196219/6acd2ef6-6739-4e0d-84a9-3092bbe3c130)

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
