### ISSUE TITLE
[BUG] - PersonalPins

### ISSUE THREAD

**Issue by Grify** [mwittrien/BetterDiscordAddons#2381]
Dev, don't mark as duplicate, this describes a new issue.

**Describe the bug**
Context menu patch doesn't succeed, which prevents the "Note message" context menu option from rendering and therefore from being usable

**To Reproduce**
Clone and manually build and patch Discord with /master@latest from BD and make sure that your pull includes PR BD#1632. Complete the manual installation process and install and enable PersonalPins. Right click on a message and take note of the lack of a button with which to add messages to the personalpins list.

**Expected behavior**
The contextmenu to be patched as it always has been.

**Screenshots**
<img width="165" alt="image" src="https://github.com/mwittrien/BetterDiscordAddons/assets/44591128/5f31251c-7365-4c90-b7c4-e9ced74a58a6">

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Bug manually confirmed on both stable AND ptb with latest personalpins and /master@latest BD 1.9.2i
**Additional context**
The contextmenu patcher bug on BD was fixed in BD#1632 but the plugin remains broken

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
