### ISSUE TITLE
[BUG] - Multiple plugins are unable to add context menu items

### ISSUE THREAD

**Issue by TheOpponent** [mwittrien/BetterDiscordAddons#2382]
**Describe the bug**
Plugins that add their own right-click menu items, such as GoogleSearchReplace and ImageUtilities, are no longer able to change the right-click menu.

**To Reproduce**
Enable GoogleSearchReplace or ImageUtilities, and enable options that change right-click menu options, such as multiple search engines or download locations for images. The options are not present in the current Discord stable client.

**Expected behavior**
The "Search with Google" option should be replaced, and the Save Image option should be replaced with a submenu.

**Screenshots**
n/a

**Discord Build (stable, ptb or canary):**
Stable 204204 (942e9ba) Host 1.0.9013 (32266) Windows 10 64-Bit (10.0.19045)

**Additional context**
This client update is the first to request Discord username updates without the four-digit code.

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
