### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Violet-Scarelli** [mwittrien/BetterDiscordAddons#2386]
**Describe the bug**
Ability to pin or unpin user DMs has vanished, but previously pinned groups are still editable.

**To Reproduce**
Install latest PinDMs, attempt to right-click a user's icon to open their menu, so you can click the 'Pin DM' option.

**Expected behavior**
'Pin DM' option is available. 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/33497956/ff66aea8-5339-42d8-a16d-7183fbdd31c9)
Existing DMs working
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/33497956/ac2039af-1bad-4baf-b0e2-8dff34fa6c03)
Lack of 'Pin DMs' option
**Discord Build (stable, ptb or canary):**
latest stable

**Comment by JoaoJardim** [comment]
I'm observing the same issue. I've tested on 3 different machines: Windows, Linux native and Linux flatpak.
I would also add that when hovering my mouse on a pinned conversation, the pin icon appears and I can unpin it. 
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/7734026/6198e466-227b-4f8f-9c67-9fd97106800b)

However, I cannot find a way to pin an uncategorized DM.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/7734026/d26a1ecc-efc1-40f5-9a7f-3c9522a6f5c5)

**Comment by mwittrien** [comment]
Context menues are broken 

https://github.com/BetterDiscord/BetterDiscord/issues/1631
