### ISSUE TITLE
[IMPROVEMENT] - Translate

### ISSUE THREAD

**Issue by Rajbir98** [mwittrien/BetterDiscordAddons#2387]
**Describe the solution you'd like**
I am a Vencord User, The Translate Plugin in Vencord has a handy little button to translate message
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/84771149/5faea13c-b4bf-4871-85c2-a010ce8dadaf)
Adding a simple button there wouldn't be a hassle for you. So, could you please do so? I'm looking forward to your actions
Also, an extra improvement to make the translation look like this just cause this looks way cooler
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/84771149/fa406560-6851-4d1a-85c8-a20e1aff42d8)

**Describe alternatives you've considered**
For now, I would stick to Vencord for the Translation, but my friend who is a Better Discord user has to go through the menu to translate each message which seems very ineffective

**Comment by mwittrien** [comment]
Hold shift
