### ISSUE TITLE
[IMPROVEMENT] - TRANSLATOR    | auto-translating messages in guilds & dms that arent the language

### ISSUE THREAD

**Issue by Woosh9129** [mwittrien/BetterDiscordAddons#2389]
**Describe the solution you'd like**
For example, you're a moderator at a server and you speak english. You're trying to speak with someone else so you enable the "Translate incoming messages to (certain language)" option. Now you have to right click on every single message to translate it, which can be annoying. make an option to auto-translate all incoming msgs.

**Describe alternatives you've considered**
Enabling  & disabling things in the plugin did not work

**Comment by mwittrien** [comment]
Not possible
