### ISSUE TITLE
[BUG] - Translator/When directly right-clicking on a message in a channel, the original "Translate Message" button at the top of the menu is missing

### ISSUE THREAD

**Issue by KinomotoKi** [mwittrien/BetterDiscordAddons#2390]
**Describe the bug**
I updated the plug-in "Translator" to version v2.5.6 today. Before the update, right-click a message in the channel, and there will be a "Translate Message" button at the top of the menu, but now this button is missing. (not the menu of the … button in the upper right corner of the message, the menu of the … button still has “translate message” in it)

**To Reproduce**
When right-clicking on a message in a channel, the "Translate message" button is missing.

**Expected behavior**
When you right-click a message in a channel, a "Translate Message" button appears at the top of the menu.
Just like the menu that appears when you click the "…" button in the upper right corner of the message, in both menus, I want the "Translate Message" button to appear

**Comment by mwittrien** [comment]
Reload discord
