### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by Soulivan71** [mwittrien/BetterDiscordAddons#2393]
**Describe the bug**
I don't have local user settings option

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/36502190/b2ca9fb5-b7cc-470c-aa85-ac0cc630d9d4)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/36502190/46d88d8e-bbbe-497f-83eb-5fa12edf1611)

**Discord Build (stable, ptb or canary):**
Ptb

**Comment by iGetUploaded** [comment]
Same for me & I'm on stable version
