### ISSUE TITLE
[BUG] - gameactivitytoggle

### ISSUE THREAD

**Issue by FroggyRaven** [mwittrien/BetterDiscordAddons#2395]
**Describe the bug**
the button isnt appearing and i cant open the plugins settings

**To Reproduce**
install the mod and it does not work

**Expected behavior**
the button is supposed to appear and the settings page is supposed to appear instead of saying "there was an unexpected error"

**Screenshots**
![Screenshot_2612](https://github.com/mwittrien/BetterDiscordAddons/assets/85956701/d627652c-0a04-48fb-9837-c846f580d27f)

**Discord Build (stable, ptb or canary):**
Stable 208166

**Comment by FroggyRaven** [comment]
imageutilities isnt working either

**Comment by FroggyRaven** [comment]
servercounter and serverdetails too

**Comment by mwittrien** [comment]
Delete 0BDFDB.DATA.JSON and reload discord
