### ISSUE TITLE
DeepL doesn't want to work

### ISSUE THREAD

**Issue by JaxOrSmthng** [mwittrien/BetterDiscordAddons#2396]
It just doesn't work, says I've reached limit

To reproduce, just choose DeepL translator

I expected the DeepL translation to work, but it doesn't.

Canary

**Comment by mwittrien** [comment]
Well limit reached means limit reached

**Comment by JaxOrSmthng** [comment]
i havent used it before, weird.

**Comment by mwittrien** [comment]
Its shared between all plugin users
