### ISSUE TITLE
Edit User ERROR???

### ISSUE THREAD

**Issue by Shadow322** [mwittrien/BetterDiscordAddons#2398]
how do i fix this and no i only have one in the plugin folder
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/15938645/992bc90b-88b4-485f-8811-6132814f4363)

**Comment by Ikatzuki** [comment]
I have the same issue. Whenever Discord is opened it gives me this error.

**Comment by mwittrien** [comment]
Delete text.plugin.js
