### ISSUE TITLE
[BUG] - ServerFolders - FolderIconPickerComponent element stays extended after fast mouse hovers

### ISSUE THREAD

**Issue by DavidCano98** [mwittrien/BetterDiscordAddons#2402]
**Describe the bug**

The folder picker element to the left of the folders that is supposed to indicate if a user is hovering over the folder tends to stay extended if user passes over it fast enough, even if not currently hovering. This causes the folders to get stuck in incorrect stat and cause confusion.  It appears the component is not catching _onMouseEnter_ and onMouseLeave properly.

**To Reproduce**
This behavior is caused by passing over a closed folder icon quickly. Doesn't happen for open folders obviously.

**Expected behavior**
I expect the picker element to not stay open, when user is not currently hovering over the server icon. 

**Screenshots**

![ezgif com-resize (1)](https://github.com/mwittrien/BetterDiscordAddons/assets/63115730/e38899ae-d94c-4182-9e10-8af19cddb44d)

**Discord Build (stable, ptb or canary):**
Stable 208319 (cd49f91) 
Host 1.0.9013 (34160) 
Windows 10 64-Bit (10.0.22621)

**Additional context**
The tooltips appear to handle quick passes correctly, always capturing the mouseOut. I don't know if this information is usefull in any way, just mentioning.

**Comment by mwittrien** [comment]
This cant be avoided thanks to discord
