### ISSUE TITLE
[IMPROVEMENT] - Force image previews 

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2405]
**Describe the solution you'd like**
let the plugin replace / rewrite spotify links to show them again in discord 

example:
https://open.spotify.com/intl-de/track/43OMUa5jouGCZEz9k9vooo?si=ce09962882fd4df0
to
https://open.spotify.com/track/43OMUa5jouGCZEz9k9vooo?si=ce09962882fd4df0

**Additional context**
the new spotify api share links with "intl-de" in the link maybe also with other languages like GR or ES.

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/25110093/5b6c13af-ced6-4b89-bcbc-d6d579ff5fca)
you see if this "intl-de" is in the link it will not be Displayed it can be that in other languages it is called then "intl-gr" or " intl-es"

**Comment by BlueStarBRS** [comment]
this should be a nice additional function to "Force a Preview"

**Comment by BlueStarBRS** [comment]
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/25110093/b96a2e72-ab0c-4d32-8dea-58124f221945)
maybe also a spotify.link fix then as well ?

**Comment by mwittrien** [comment]
Which plugin are you talking about

**Comment by BlueStarBRS** [comment]
> Which plugin are you talking about
Force image previews
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/25110093/a7f9f347-be27-4b04-89e1-bc6acfb23664)

**Comment by mwittrien** [comment]
ForceImagePreviews is discontinued
