### ISSUE TITLE
[BUG] - ImageUtilities No Resize setting

### ISSUE THREAD

**Issue by Ryanicus2002** [mwittrien/BetterDiscordAddons#2406]
**Describe the bug**
When setting the image resizing setting to 'No Resize', the plugin still locks images in at what would be their default size if Discord were fullscreen, rather than reverting to Discords default behavior. This means if Discord is not occupying the whole screen (only half in my case), images will be cut-off at the right side.

**To Reproduce**
Simply use ImageUtilities with image resizing set to 'No Resize', and set Discord to only the left half the screen.

**Expected behavior**
The No Resize setting should prevent the plugin from touching image resizing, allowing default Discord behavior. 

**Screenshots**
Discord default behavior (half-screened):
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/71451851/cb1e345f-a7aa-4acc-bb21-b7d3cc964a0f)
 
ImageUtilities with 'No Resize':
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/71451851/bbdc8f7d-455c-4ef8-9b21-af04bb18dc45)

**Discord Build (stable, ptb or canary):**
Stable 210566 (fc3ede1) 

**Additional context**
Only plugins I have active are ImageUtilities and BDFDB. If this is not technically a bug, then I'd at least recommend making 'No Resize' use default Discord behavior. At half screen the 'resize to window' and 'resize to original size' choices both make images comically large, with a single image sometimes taking up 80% of visible space, leaving no good options.

**Comment by mwittrien** [comment]
Doesn't happen due to the resize module

This happens due to the image details being added as a footnote, change it to the tooltip option
