### ISSUE TITLE
[BUG] - ReadAllNotificationsButton

### ISSUE THREAD

**Issue by ChloeTheBitch** [mwittrien/BetterDiscordAddons#2408]
**Describe the bug**
The plugin removes other buttons created through other plugins when it loads

**To Reproduce**
Run a plugin that creates another button in either the little bottom left area (where the deafen, mute, etc) or in the server list.

**Expected behavior**
The Read All button appearing and the other plugins's buttons appearing

**Screenshots**
Without ReadAllNotificationsButton plugin on:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/90904118/1ef6c62a-b264-444c-a92e-f0d1fc7fba57)
After turning it on:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/90904118/35d32550-34da-477f-9042-5832be4aaf57)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Irrelevant

**Comment by mwittrien** [comment]
Thats an issue with the other plugins
