### ISSUE TITLE
[BUG] - NotificationSounds v3.8.0

### ISSUE THREAD

**Issue by Fizzys** [mwittrien/BetterDiscordAddons#2414]
The User Join and User Leave notification does not reflect the settings in the plug-in

I had expected the volume to be lowered to the setting I had in the plug-in settings. All other notification sounds that I have tested 
still work perfectly. 

Better Discord Core v1.9.3

This seems to be the only ones that are currently not working. After testing the call/join setting also does not work to change the
actual sound of the notification as well as the volume slider not functioning.

**Comment by mwittrien** [comment]
You need to change `User Join`/`User Leave` not `Acitvity User Join`/`Activiy User Leave`
