### ISSUE TITLE
Voice Channel User Join/Leave/Moved settings not properly adjusting volume

### ISSUE THREAD

**Issue by Fizzys** [mwittrien/BetterDiscordAddons#2415]
You need to change `User Join`/`User Leave` not `Acitvity User Join`/`Activiy User Leave`

_Originally posted by @mwittrien in https://github.com/mwittrien/BetterDiscordAddons/issues/2414#issuecomment-1630248082_
            

I am well aware of the proper categories, I have had it functioning for the past year+ as normal, and it only recently became an issue. I have inserted a screenshot (hopefully) this time to illustrate the settings. As stated previously the others that have been lowered like "Undeafen" and "Unmute" work fine, but "Voice Channel User Join" and "Voice Channel User Leave" and "Voice Channel User Moved" no longer properly adjust the volume, or the notification sound (I tested changing the actual sound as well, and it also did not work).

![pRAbYKv](https://user-images.githubusercontent.com/38084520/252763008-d3279484-cbdd-45d8-9020-6d5345777020.png)

Yes, I have also updated to the most recent version as of today as well, and it is still not functioning properly. 

Thank you

EDIT: After more testing today, other people joining and leaving properly uses the volume settings, however my own joining and leaving of channels ignores the setting and plays at full volume.

**Comment by ovapico998** [comment]
Currently have the same issue.
When joining/leaving a voice channel, the custom sounds I've set up do not play.  They work for (un)muting, and (un)deafening, but not for joining/leaving.  I've tried setting the Voice Channel User Leave and Voice Channel User Joined to different settings multiple times, but nothing worked.
If this _is_ a bug, I hope it will be fixed soon, as NotificationSounds is definitely an improvement over the regular Discord experience.
If there is a quick-fix out there, please let me know!
