### ISSUE TITLE
[BUG] - CustomerQuoter

### ISSUE THREAD

**Issue by theapathyimp** [mwittrien/BetterDiscordAddons#2417]
**Describe the bug**
Compiler error on start.

**To Reproduce**
After starting or refreshing the app, with the plugin active and attempting to load.

**Expected behavior**
Plugin loads and doesn't error.

**Screenshots**
Error:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/8020193/b7b841e5-f7f7-4af0-a659-1d5bbffd8c08)

Plugins folder sorted alphabetically, showing there is no other file than the one I added earlier today:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/8020193/81853468-f537-47d9-98b8-c38a24e70bfb)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
It went away when I manually replaced the file in my plugin folder with the raw CustomQuoter.plugin.js downloaded from here, but then reappeared as soon as I restarted the app. I believe it started on the second most recent version of 1.3.3, possibly even as far back as 1.3.2 but I'm not 100% sure.

**Comment by mwittrien** [comment]
you most likely got another file that uses the same plugin name in the plugin meta inside the file, check all plugins for copies, might be a whole different filename

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/23700969/80bf3b8d-ecd3-40e5-83b5-064a196573e5)

**Comment by theapathyimp** [comment]
thanks for clarifying, there was a file named "TestChannel.js" which seems to have been a beta/prerelease file the shipped with an update for some reason, i was able to find it with a regex search using powershell and deleted it. the error is now gone.
