### ISSUE TITLE
[BUG] - NotificationSounds: Ping sound issue

### ISSUE THREAD

**Issue by Venus5687** [mwittrien/BetterDiscordAddons#2420]
**Describe the bug**
Sometimes the plugin plays the ping sound when there isn't a notification from Discord and it's a bit annoying.

**To Reproduce**
When there isn't a notification from Discord.

**Expected behavior**
I expected it not to play the ping sound.

**Screenshots**
No screenshots cuz it's impossible to show the problem with screenshots.

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
No additional context.

**Comment by mwittrien** [comment]
Can't reproduce this
