### ISSUE TITLE
[BUG] - Theme/Plugin Repo might be broken 

### ISSUE THREAD

**Issue by Matt0040** [mwittrien/BetterDiscordAddons#2426]
When loading discord, this notification comes up, and the same with the Plugin Repo. Betterdiscord's website now has a captcha function, if I had to guess that was implemented overnight. 

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/42654785/7343327b-8516-4512-b4e0-7c10d2c528ce)

Edit: I put this in here instead of the respective plugin's page because this likely affects more than the Repo plugins.

**Comment by Mattem300** [comment]
I have the same issue. Probably because PluginRepo and ThemeRepo use some DDoS stuff (I don't know if they really use it) to access the Websites Plugin API, and since they have installed DDoS Protection into the website (https://betterdiscord.app/), it does not work.

**Comment by K3NOXOFFICIAL** [comment]
I had the same issue then the message didn't show again, but now my discord is crashing every 5 minutes because of it, 
its really annoying.
I tried turning the plugin and theme repo off as well as turning off BDFDB but nothing helps.

**Comment by mwittrien** [comment]
This is duw to the DDoS protection of the website

The plugins will work again once the protection calmed down again
