### ISSUE TITLE
[IMPROVEMENT] Add 3D Microsoft Emojis - EmojiReplace

### ISSUE THREAD

**Issue by foursplaysroblox** [mwittrien/BetterDiscordAddons#2427]
**Describe the solution you'd like**
I want Emojis Replace to support 3d Emojis to discord from Microsoft
**Describe alternatives you've considered**
Using the Microsoft Emoji import in the Emoji replace theme
**Additional context**
(Left) Microsoft Emoji (Right) the Expected result
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/82078139/481a22a4-d96d-4e41-908d-84344970e516)

**Comment by mwittrien** [comment]
They arent on empjipedia so cant add them
