### ISSUE TITLE
[BUG] - Display Servers As Channels

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#2430]
**Describe the bug**
When activated Discord crashes.

**To Reproduce**
Activate the plugin and click on some channel.

**Expected behavior**
Discord client shouldn't crash.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
This behavior occurs on all current client builds.

**Additional context**
It first happend after I installed todays Windows 10 Updates (KB85028244 and KB5028412)

**Comment by mwittrien** [comment]
Doesn't crash for me
Can you record a video

**Comment by wilecoyote** [comment]
I reactivated the plugin on all clients and the crash doesn't happen anymore. The only way I can explain this is that the DDOS protection that was active for the Better Discord website had something to do with it. I also could not open the BDFDB settings and got an error message. This also doesn't happen anymore. So, I think the issue can be closed.
