### ISSUE TITLE
[BUG] - BDFDB massive lag with v3.3.1

### ISSUE THREAD

**Issue by re11ding** [mwittrien/BetterDiscordAddons#2439]
Just wanted to give the warning but the new version of BDFDB (v3.3.1) lags much more severely when used with ServerFolders compared to the previous version (v3.3.0). The biggest thing that makes it noticeable is by doing the following, but is not exclusive to just this:

Open an image preview by clicking an image
Alt tab or click on another window, one that will completely overlay Discord.
Click Discord again and attempt to click on the side of the image to close the preview. 
Discord will severely lag for over a second and a half before the image preview closes. 

I noticed the only change was the addition of `replace(/[\n\t\r]/g, "")` to `toString()`, `funcString`, and `renderFuncString`, so it means whatever this piece does makes it far less optimized.

I have somewhat older hardware (Intel Gen 6 i7) so this may not be prevalent with newer systems. However, I downgraded back to 3.3.0 and the issue no longer exists, so it's definitely not my imagination. If needed, I can add some video recordings of both 3.3.0 and 3.3.1 to demonstrate the difference. Please let me know if this is needed.

**Comment by YukariShinoki** [comment]
+1 to issue. Also occurring on 3.3.1. Specifically with Server Folders and to a lesser extent Server Details.

**Comment by Nox13last** [comment]
+1.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/1292492/480b7c6b-780c-40b2-a06d-f031aa34e633)
After one minute, RAM balloons to about 361 MB. I have an AMD Ryzen 7 5800X and 32G of DDR4-2666 RAM.
It takes fifteen seconds for a message I tap out with the keyboard to get on the screen. It's so laggy that I can't even open the dev-tools.
It wasn't this bad before.
