### ISSUE TITLE
[Badges Everywhere][Request] Choose between global and current guild boost badge

### ISSUE THREAD

**Issue by OrangutanGaming** [mwittrien/BetterDiscordAddons#244]
So you would have an option that overwrites both of the normal toggles and shows:
- The current server boost badge if they are boosting the current server
- Their global boost badge if they are not boosting the current server
- None if they are not boosting

This would allow you to easily tell if someone is boosting but also give more information if they are without having 2 boost badges.

**Comment by mwittrien** [comment]
disable the global badge to only show the local badge and if you wanna know if someone boosts at all then visit their profile
