### ISSUE TITLE
[BUG] - Translator Plugin not recognizing api key

### ISSUE THREAD

**Issue by GodlyBDS** [mwittrien/BetterDiscordAddons#2444]
**Describe the bug**
Api key isnt recognized

**To Reproduce**
when trying to use deepl translate with my free api key to translate it says the api key is old/wrong

**Expected behavior**
being able to use deepl with my api key

**Screenshots**
![Anmerkung 2023-08-06 123205](https://github.com/mwittrien/BetterDiscordAddons/assets/90688190/ef12fbcd-c776-4fa2-afa6-62a483ab464f)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
i made a deepl account to get a free api key to translate things but it doesnt get recognized even looked int othe code if the api link is still the right one which seemed like the right one

**Comment by mwittrien** [comment]
well without knowing your api key, i wont be able to test it
