### ISSUE TITLE
[IMPROVEMENT] - ShowBadgesInChat

### ISSUE THREAD

**Issue by Soulivan71** [mwittrien/BetterDiscordAddons#2450]
**Describe the solution you'd like**
Add the automod badge : 
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/36502190/70018f57-3358-4073-9d5b-263ecc750f0c)

**Comment by mwittrien** [comment]
Can't find a bot with that badge

**Comment by Soulivan71** [comment]
Saphire for example is id :
<@678344927997853742>
