### ISSUE TITLE
[BUG] - settings icons

### ISSUE THREAD

**Issue by vilchu** [mwittrien/BetterDiscordAddons#2451]
**Describe the bug**
When having Openasar installed same time with settings icons, the last few icons are bugged

**To Reproduce**
Openasar and settings icons enabled together

**Expected behavior**
Only the openasar icon being ? mark or possibly with own icon

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/55512609/74b877e2-eed7-4740-b8eb-34ea9e890fd2)

**Discord Build (stable, ptb or canary):**
Discord Ptb 219767 (073ef81)

**Additional context**
Hopefully can be fixed

**Comment by mwittrien** [comment]
I can't make SettingsIcons compartible with everything that adds a new entry in the settings menu
