### ISSUE TITLE
[IMPROVEMENT] - Translator | Auto translation only with custom API key

### ISSUE THREAD

**Issue by hahagu** [mwittrien/BetterDiscordAddons#2452]
**Describe the solution you'd like**
I would like there to be an option to be there to enable auto translation,
but only when custom API keys have been used.

**Describe alternatives you've considered**
Manually translating all the messages I receive.

**Additional context**
Previous requests have been denied due to API limits, but having the option only for custom API key users,
this limitation could be bypassed.

**Comment by mwittrien** [comment]
Still a no
