### ISSUE TITLE
[IMPROVEMENT] - UserNotes

### ISSUE THREAD

**Issue by gitzec** [mwittrien/BetterDiscordAddons#2453]
Hi, thank you for this really useful plugin!

I would like to have UserNotes load user notes in a configurable interval like every 5 minutes instead only on startup because I use two Discord clients simulanously (normal and PTB because of development purposes).

That would make it more comfortable to sync the user notes between both clients.

Cheers

**Comment by mwittrien** [comment]
It doesn't load them on start

The configs are simply cached in your client, that's why making changes on one client won't affect the other until your reload

**Comment by gitzec** [comment]
Ty for the fast response. Any chance to change it to make both clients use the same database?

Or should I just hit Ctrl+R to make Discord flush data to files and reload on startup?
