### ISSUE TITLE
[BUG] - Personal Pins - Needs Update For Compliance (Crashing)

### ISSUE THREAD

**Issue by Sebastianroczz** [mwittrien/BetterDiscordAddons#2457]
**Describe the bug**
while trying to look at your personal pins discord crashes providing you with the "you unlocked discord minus actually discord crashed"

**To Reproduce**
Go into any chat so you can open the notes click on the notes and see the app provides a crash message

**Expected behavior**
Expected behavior: the notes load without issue

**Screenshots**
N/A i dont think its nessiary to screenshot the crash page

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by Sebastianroczz** [comment]
uh im pretty new to github and have no idea how to dm you also would the config.json be in the mods folder? Thanks.

**Comment by mwittrien** [comment]
You can dm me on discord via my Support  server and yes in the plugins folder

**Comment by Sebastianroczz** [comment]
nvm i did a library update and now it seems to be working fine
