### ISSUE TITLE
[BUG] - BDFDB "Could not initiate BDFDB Library Plugin! Can not create Settings Panel"

### ISSUE THREAD

**Issue by DashingRiggs** [mwittrien/BetterDiscordAddons#2460]
**Describe the bug**
I woke up to half of my plugins suddenly not working. I think I narrowed the problem to the BDFDB plugin. When I open the BDFDB plugin's settings, I am met with an error, 
"Could not initiate BDFDB Library Plugin! Can not create Settings Panel! 
Try deleting the 0BDFDB.data.json File in your C:\Users\(username)\AppData\Roaming\BetterDiscord\plugins Directory and reload Discord afterwords!"
I have done this multiple times, including manually updating the plugin and replacing the raw.css and data.json files shown here: https://www.reddit.com/r/BetterDiscord/comments/q8cdb8/comment/ik7zcaj/?utm_source=share&utm_medium=web2x&context=3 

**To Reproduce**
I have no clue since I haven't changed anything that would've caused the BDFDB plugin.

**Expected behavior**
Any plugin that depends 0BDFDB.plugin.js should work, instead nothing works.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/54649036/38bae942-678b-4728-96f4-1d70c3c0d899)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/54649036/79da01e4-3a01-4eda-90f5-479ab1b1ce77)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/54649036/bc7ba361-dafd-4e3a-b99b-460fffdc421e)

**Discord Build (stable, ptb or canary):**
Stable. 

**Additional context**
Plugin Repo doesn't even work right now so I can't auto update.

**Comment by mwittrien** [comment]
Redownload 0BDFDB.plugin.js
