### ISSUE TITLE
[IMPROVEMENT] - Themes/EmojiReplace - Add Microsoft 3D

### ISSUE THREAD

**Issue by slimberton** [mwittrien/BetterDiscordAddons#2463]
Add Microsoft's new improved 3D version of the flat windows 11 emotes. They've been released to the public, currently in test of the canary build of Microsoft. I'd like to see them in discord as well. 

For reference: https://github.com/microsoft/fluentui-emoji

**Comment by mwittrien** [comment]
If they arent on emojipedia then i cant add them
