### ISSUE TITLE
[IMPROVEMENT] - ServerFolders - QoL changes

### ISSUE THREAD

**Issue by ffernn-dev** [mwittrien/BetterDiscordAddons#2465]
**Describe the solution you'd like**
SVG files added as custom icons should have a background colour and text colour set from the primary and secondary colours. Also have the svgs not turned into png Base64 when saved.

**Describe alternatives you've considered**
One could add a rect into each svg file but that's a pain in the ass

**Additional context**
N/A

**Comment by mwittrien** [comment]
denied, sorry
