### ISSUE TITLE
[IMPROVEMENT] - ServerFolders - Icon margins

### ISSUE THREAD

**Issue by ffernn-dev** [mwittrien/BetterDiscordAddons#2466]
**Describe the solution you'd like**
Wow! Two feature requests in 5 minutes! Just the ability to pad the icons in a bit.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/69182455/015a3be4-4c01-4c17-9fa9-235785b8e9fb)
becomes
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/69182455/bca4ea74-8ac5-492e-83e2-00a07277bd43)
(It's cut off but you get the idea)

**Comment by mwittrien** [comment]
Use css if you wanna add a padding
