### ISSUE TITLE
[TopRoleEverywhere 2.8.1] Tags now underlap content as a result of #245

### ISSUE THREAD

**Issue by Maximilian1271** [mwittrien/BetterDiscordAddons#247]
Unfortunately as a result of #245 , Tags now underlap text content in the chat, rendering the plugin useless in this state. However, tags now correctly render text in the member list, hence why i did not reopen #245 

![Untitled-2](https://user-images.githubusercontent.com/1573345/61999790-0e84a580-b0c9-11e9-94c7-b1a79166e26f.png)

**Comment by wefalltomorrow** [comment]
Can confirm, happening to me as well.

**Comment by wefalltomorrow** [comment]
Working now with latest updates :)
