### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by glagla00** [mwittrien/BetterDiscordAddons#2471]
**Describe the bug**
a dancing cat shows up when you right click

**To Reproduce**
right clicking on an image when highlighted

**Expected behavior**
a list of various things to do with the image. 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/36730244/28b9dc58-b474-463c-bdc2-abe9694a3de0)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Update BDFDB
