### ISSUE TITLE
[IMPROVEMENT] - PinDMs - Potentially collapse the unpinned category?

### ISSUE THREAD

**Issue by TimeBender25** [mwittrien/BetterDiscordAddons#2474]
**Describe the solution you'd like:**
It's not a massive change, but I'm unsure how feasible it would be. Is it possible to make the unpinned section where DMs appear also collapsible? If I pin a DM it's usually because I want ready access to it, and I'd like to be able to tuck away or hide all the DMs where only one or two messages have been sent, or active conversation is not happening.

**Describe alternatives you've considered:**
Could it be a setting to automatically pin new incoming DMs to a collapsible "Misc" category? Or Select a default category for new incoming DMs to be placed into? Maybe a option to filter DMs pinned to the server list out of the channel list?

**Additional context:**
I ask for this mostly because I like being able to deselect a DM when I'm not talking in any of them, and the only way i have to do that is to click on the "Friends" button at the top of the DM Channel list. It's not hard to scroll up to, but discord scrolling down every single time I click on a DM if the list goes below the screen regardless of how high up in the list the one I clicked is gets annoying. Being able to collapse the DMs I don't care as much about would not only make Discord stop doing this but it would also help the clutter.

**Comment by mwittrien** [comment]
Tried it in the past and wasn't feasable, because discords scroller hated being messed with like that
