### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by RainbowCreamPie** [mwittrien/BetterDiscordAddons#2475]
**Describe the bug**
The color in profile theme doesn't sync, just see the color profile theme on the borders

**To Reproduce**
Remake color profile theme

**Expected behavior**
Right click on profile to see color theme like the Nitro

**Screenshots**
With Nitro:
![Screenshot 2023-09-04 093554](https://github.com/mwittrien/BetterDiscordAddons/assets/136293817/62c106b8-237b-41a0-8aa5-6650062072ac)

Edit User (Plugin):
![Issue 3](https://github.com/mwittrien/BetterDiscordAddons/assets/136293817/ab05b817-8f4e-4b62-9638-d27feb71f2ed)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Works just fine for me, might be a conflict with a theme of yours
