### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace - Update JoyPixels

### ISSUE THREAD

**Issue by D3SOX** [mwittrien/BetterDiscordAddons#2477]
**Describe the solution you'd like**
Update JoyPixels to the most recently released [version 8.0](https://blog.joypixels.com/joypixels-8-0-now-available/)

**Comment by mwittrien** [comment]
Since EmojiPedia completely restructured their webpage, my emoji grabber no longer works and maintaining EmojiReplace is no longer possible

**Comment by D3SOX** [comment]
Can you post the source code for your emoji grabber somewhere because I may work on this, and it might come in handy as a base

**Comment by aaronliu0130** [comment]
The URL structure for joypixel emojis appears to be `https://em-content.zobj.net/source/joypixels/369/<hyphenated-all-lowercase-emojipedia-emoji-name>_<unicode-codepoint-without-U+>.png`. For example, "Grinning Face with Big Eyes" is https://em-content.zobj.net/source/joypixels/369/grinning-face-with-big-eyes_1f603.png and "Egg"is https://em-content.zobj.net/source/joypixels/369/egg_1f95a.png . The "#__NEXT_DATA__" script element contains a JSON representation of everything you need. Here's an excerpt for :smiley::
```json
{
    "props": {
        "pageProps": {
            "dehydratedState": {
                "queries": [
                    {},
                    {},
                    {},
                    {
                        "state": {
                            "data": {
                                "slug": "grinning-face-with-big-eyes",
                                "codepointsHex": [
                                    "U+1F603"
                                ],
                                "shortcodes": [
                                    {},
                                    {},
                                    {},
                                    {
                                        "code": ":smiley:",
                                        "vendor": {
                                            "slug": "discord",
                                            "title": "Discord"
                                        },
                                        "source": "discord"
                                    }
                                ]
```

@mwittrien If all else fails, you could maybe also contact emojipedia to ask if you could use their API, which has a small chance, but the scraping method I described above doesn't have much of a chance of failing either.

**Comment by mwittrien** [comment]
No need to I fixed it myself

**Comment by D3SOX** [comment]
Thank you!
