### ISSUE TITLE
[BUG] - Plugins/NotificationSounds

### ISSUE THREAD

**Issue by Chriss1056** [mwittrien/BetterDiscordAddons#2479]
**Describe the bug**

I uploaded a 3 minute long song, for when I call someone, but the song doesn't play through, it always restarts afer a few seconds.

**To Reproduce**
When does the bug occur.

Every time I try to call someone, after a few seconds.

**Expected behavior**

I expected it to work the same as when I'm being called. It plays the entire song and then restarts.

**Screenshots**

I don't know any way to capture Images of a sound problem, but I can give you a recording if it helps.

It didn't let me upload mp3 files, so I ziped it.
[recording.zip](https://github.com/mwittrien/BetterDiscordAddons/files/12612581/recording.zip)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

Stable

**Additional context**

File Format: MP3
Song Lenght: 3:06 minutes

Same as above, this is the song.
[Ping! 2.zip](https://github.com/mwittrien/BetterDiscordAddons/files/12612277/Ping.2.zip)

**Comment by mwittrien** [comment]
the plugin isnt meant to be used with such long sound files
