### ISSUE TITLE
[BUG] - PinDMs error in displaying DMs

### ISSUE THREAD

**Issue by Violet-Scarelli** [mwittrien/BetterDiscordAddons#2486]
**Describe the bug**
PinDMs makes all my DMs disappear.

**To Reproduce**
It only just started happening but: 
- Load PinDMs
- Look at DMs area

**Expected behavior**
DMs should be visible

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/33497956/7518fc0d-8183-41e7-8109-f160bac7d868)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by ExoticButterszs** [comment]
i have the same issue 
https://cdn.discordapp.com/attachments/789683911419887646/1159667428175921243/image.png?ex=6531db74&is=651f6674&hm=a84e26b75ca44f380174cf4a8efd350fb03e6a77f399793c98e11ef4d1300de8&

**Comment by dev-alto** [comment]
Can also confirm this issue, only noticed it today:

![Discord_89jOmtVvmS](https://github.com/mwittrien/BetterDiscordAddons/assets/51037255/8a6844f2-b091-4ee9-bba4-79b324e54b8b)

**Comment by ExoticButterszs** [comment]
> Can also confirm this issue, only noticed it today:
> 
> ![Discord_89jOmtVvmS](https://user-images.githubusercontent.com/51037255/273084925-8a6844f2-b091-4ee9-bba4-79b324e54b8b.png)

same

**Comment by BroOtti** [comment]
Also happens with the PTB Client
