### ISSUE TITLE
React Component Error

### ISSUE THREAD

**Issue by bloodonmywrists** [mwittrien/BetterDiscordAddons#2490]
React Component Error on search with image utilities for all searches

https://cdn.discordapp.com/attachments/1158668790444339241/1160521545450541056/image.png?ex=6534f6e9&is=652281e9&hm=9f10ad1b84de04568d7bf27cef315dbf9a240092a3fc064d4caaf377f4c61173&

**Comment by mwittrien** [comment]
Redownload BDFDB and delete 0BDFDB.data.json and then reload discord
