### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by Brutalbic** [mwittrien/BetterDiscordAddons#2492]
**Describe the bug**
Channel Lists that include a DM that has no messages will stop the entire list from sorting by most recent.

**To Reproduce**
Enable recentOrder in the channelList. Create a channel list with a few DMs, it will sort as normal, as soon as you add a DM with no messages it will pin this to the top of that list and stop sorting any other DMs in that list.

**Expected behavior**
DMs to continue to be sorted, any DMs without any messages should appear at the bottom of that channel list.

**Discord Build (stable, ptb or canary):**
Stable & Canary

**Additional context**
This bug doesn't occur when using the inbuilt "Friends" category and having DMs in there with no messages

**Comment by mwittrien** [comment]
Just tried with a custom category and it works just fine for me

**Comment by Brutalbic** [comment]
I just reset the config file and ensured only this plugin is enabled and it still occurred
Screenshot: https://i.imgur.com/er9hoQ3.png
I pinned 5 people in this category (2nd one in the screenshot has no messages and only added them as a friend), I then got a message from the 3rd person which should have moved them to the top of that category

Happy to provide more information or I can screenshare if you have the time, I am on your support server with the same username
