### ISSUE TITLE
[IMPROVEMENT] - PinDMs

### ISSUE THREAD

**Issue by Brutalbic** [mwittrien/BetterDiscordAddons#2493]
**Describe the solution you'd like**
Ability to re-order channelLists.

**Additional context**
Currently you are able to do this by manually editing the "pos" value in the config file (this also requires discord to be refreshed to apply)
I believe the easiest method would be to add a position field in the category settings UI.

**Comment by mwittrien** [comment]
Was possible until discord broke it, no longer possible
