### ISSUE TITLE
Idea: Thread Manipulation

### ISSUE THREAD

**Issue by Obskyur** [mwittrien/BetterDiscordAddons#2495]
Preamble aside, Discord has very few features allowing manipulation of Threads. Discord currently allows the starting of Threads, and that's about it.

### Proposition:
I propose a plugin that allows threads to be created from **multiple** messages, instead of just one. This would ideally allow a server admin to take a bunch of on-topic messages and bundle them into a thread to keep a chat organized.

I'd also like to propose the ability to change the origin of a thread. This would allow an off-topic thread created in one channel to be an on-topic thread in another by 1st: doing the above, and then editing its origin to be another channel.

Please let me know what you think / if this is possible!
~Tristan

**Comment by mwittrien** [comment]
I am not making new plugins
