### ISSUE TITLE
[BUG] - ShowBadgesInChat dm list slow

### ISSUE THREAD

**Issue by GenesisAria** [mwittrien/BetterDiscordAddons#2497]
**Describe the bug**
Dm list becomes much less responsive when scrolling and re-draws the list, including any animations relevant to theme.  These redraw delays happen when typing animations or any other changes happen.  Have to disable the plugin to restore smooth function.

**To Reproduce**
Always occurring.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Cant be fixed, thanks to Discords dumn internal changes
