### ISSUE TITLE
[IMPROVEMENT] - Chat Filter - Apply censor to past messages which have already been sent

### ISSUE THREAD

**Issue by EmSixTeen** [mwittrien/BetterDiscordAddons#2499]
**Describe the solution you'd like**
Add an option to also let a filter apply to previously sent messages, once the user looks at them. I'm aware this may have a performance hit. For example, if the user were to view an old pinned message, or scroll back in chat history.

**Describe alternatives you've considered**
This plugin appears to be the only which does this sort of thing.

**Additional context**
I'm using the 'censor' functionality currently, to replace strings which mean the same thing with my preferred style, but it would be more appropriate to just call this a 'filter' and a message triggering it would be marked 'filtered'.

**Comment by mwittrien** [comment]
The plugin should already do that
