### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by Spyrois2cool** [mwittrien/BetterDiscordAddons#2501]
**Describe the bug**
Notifications from threads do not play sound. 

**To Reproduce**
Receive a notification from a thread that has notifications turned on.

**Expected behavior**
Notifications should play a sound. 

**Screenshots**
Cannot screenshot a sound. (Or lack thereof)

**Discord Build (stable, ptb or canary):**
Stable 237546 (c8efe13)

**Additional context**
There is also no option to customize notifications from threads as well. I do tend to rely on sounds when watching stuff in fullscreen, as Discord notifications do not show when my web browser is in fullscreen. I believe I have always had this problem, so it is not just from any recent updates.

**Comment by LCFjive** [comment]
I have same problem, I think it's cuz discord recent update

**Comment by Sam-Man16** [comment]
Could not initiate BDFDB Library Plugin! Can not create Settings Panel!
Try deleting the OBDFDB.data.json File in your
C:\Users\samue\AppData\Roaming\BetterDiscord\plugins
Directory and reload Discord afterwards!

same here for me, this is the error I get, also assume it's from the recent Halloween update discord pushed

**Comment by Spyrois2cool** [comment]
This has actually been the case for me since the beginning, I think. I know I’ve had the issue for quite some time.

**Comment by Spyrois2cool** [comment]
I am still having this issue. It was working just fine yesterday. But now it isn't working anymore. I can _see_ the notification on my screen, but no sound plays.
