### ISSUE TITLE
[BUG] - BDFDB "Could not initiate BDFDB Library Plugin! Can not create Settings Panel"

### ISSUE THREAD

**Issue by boooooooaq** [mwittrien/BetterDiscordAddons#2502]
**Describe the bug**
I have what appears to be  the same issue as #2460 
BDFDB does not load and neither does any plugin depending on it. When clicking on the gear icon in the plugins tab it gives me: "Could not initiate BDFDB Library Plugin! Can not create Settings Panel!
Try deleting the 0BDFDB.data.json File in your /home/(myuser)/.config/BetterDiscord/plugins Directory and reload Discord afterwords!"

**Build:**
Stable  0.0.32-1

**Additional information** 
 I have deleted 0BDFDB.data.json, 0BDFDB.plugin.js and 0BDFDB.raw.css and reinstalled the plugin but that didn't fix it. I am running Linux but that shouldn't be a problem as in the past it worked fine on it.

**Comment by boooooooaq** [comment]
Plugins that aren't dependent on BDFDB seem to work fine

**Comment by CaseyWhiting** [comment]
I'm also having this issue, Discord has only just been updated for the Halloween update so it might just be that the BDFDB & Discord versions aren't compatible

**Comment by Erlonealpha** [comment]
also the translator can not work which dependent on BDFDB

**Comment by Leah96xxx** [comment]
I'm not getting any specific error for BDFDB, but none of the plugins that rely on it are working. I am however getting errors relating to the preload.js script in betterdiscord.asar. There's an [issue open](https://github.com/BetterDiscord/BetterDiscord/issues/1676) on the main BetterDiscord Github for that. I wonder if maybe the 2 issues are related?
