### ISSUE TITLE
[BUG] - FriendNotifications "React Component Error"

### ISSUE THREAD

**Issue by Hooriza10** [mwittrien/BetterDiscordAddons#2506]
**Describe the bug**
FriendNotifications plugin not working, it only give "React Component Error" message.

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/148476220/13d749f2-215d-44f6-ab99-b7183dedc4e6)

**To Reproduce**
Opening the notification log as usual.

**Expected behavior**
The notification log would give log user status window as usual instead of "React Component Error" message.
 
**Discord Build (stable, ptb or canary):**
Stable

**Comment by Anadovnik** [comment]
This error occurs only if the log is empty. As soon as there are some data in the log, it works correctly. Yesterday BDFDB had an update. It seems they changed something.
