### ISSUE TITLE
[BUG] - SpotifyControls "lost connection" loop

### ISSUE THREAD

**Issue by Leah96xxx** [mwittrien/BetterDiscordAddons#2507]
**Describe the bug**
SpotifyControls floods the in-app notifications with error "Discord lost the connection to the last device that was playing Spotify, open Spotify again and manually resume the song."

Issue persists after reloading Discord and after restarting Discord. No errors are logged in the console, though the warning below is logged once for each time the notification shows (not sure if it's the plugin or the notification causing that):
```
bb368a4151a4532c3fda.js:539 [BetterDiscord] [Deprecated] Usage of the Buffer global is deprecated. Consider using web standards such as Uint8Array and TextDecoder/TextEncoder.
```
The warning and notification spam continues for as long as there is a song playing, then stops when playback is stopped. It also occurs regardless of what device is playing Spotify (tested with my PC and my Android phone, both running the latest version of Spotify). Thankfully the warning just increments a counter, but the notifications flood the screen.

The control itself still shows and updates the track details, artwork and time, but the controls themselves don't work.

I've disabled the plugin for now so I can use Discord, but I can re-enable for testing if needed.

**To Reproduce**
Play song on Spotify with Discord open

**Expected behavior**
No error notifications, controls should work

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/88419550/85b693e1-d02c-4503-8baf-b3404800ddf8)

**Discord Build (stable, ptb or canary):**
Stable 238545 (dd9e385)

**Additional context**
Only noticed after updating BetterDiscord to 1.9.4 and BDFDB to 3.3.8 (ref my last issue), but I'm not sure if this issue existed prior to that, as I haven't used Spotify with Discord open in a few days.
SpotifyControls version 1.3.6, BD and BDFDB versions as above.

**Comment by Enrico9431** [comment]
Same happening for me

**Comment by ImMALWARE** [comment]
Same
