### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by Hooriza10** [mwittrien/BetterDiscordAddons#2511]
**Describe the solution you'd like**
It would be nice to have FriendNotification feature with auto backup of the timestamp log, and ability to see the log of those backup timestamp

**Describe alternatives you've considered**
I didn't think of any alternatives yet.

**Additional context**
Sometime discord will crashed (probably because of the timestamp overloaded or something) so the log would be gone. 
Adding an auto backup to it for every x minutes/hours, and some way to be able to see those backup log, in a way that is UI friendly,
 maybe like separate window to open those backup timestamp log. 
Thank you very much.

**Comment by mwittrien** [comment]
The plugin isnt meant to log your friends behaviour over long time
