### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by Gavin-TnT** [mwittrien/BetterDiscordAddons#2512]
**Describe the bug**
Baidu Translate doesn't work, even with my own API, but Google does
 
**To Reproduce**
This problem occurs when the BDFDB plug-in is updated to V3.4.0

**Expected behavior**
Translation not available after updating BDFDB

**Screenshots**
![1](https://github.com/mwittrien/BetterDiscordAddons/assets/80191175/5d73c1a0-a0a8-46aa-a0e9-16f928b649e3)

**Discord Build (stable, ptb or canary):**
Stable 239004 (405d7a8)
Host 1.0.9020 x86 (38517)

**Additional context**

**Comment by AIDA64S** [comment]
same

**Comment by alfredarcifa** [comment]
Me too

**Comment by mwittrien** [comment]
#2515
