### ISSUE TITLE
[BUG] - PLUGIN BDFDB & Translator are broken

### ISSUE THREAD

**Issue by HDL34** [mwittrien/BetterDiscordAddons#2516]
The 2 plugins have been broken since this morning. Yesterday they were still working.
When I click on the little gear of one of the 2 plugins, I get this error message at the bottom.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/61374058/3efa2b1b-f36d-44f5-bfcf-e9dab4d27a72)
I don't know what's going on. I even downgraded the plugins but with no effect. Yet I'm still on Discord version 1.0.9020 which was updated 5 days ago.

**Comment by mwittrien** [comment]
#2515
