### ISSUE TITLE
[BUG] - NotiflicationSounds

### ISSUE THREAD

**Issue by AteebXYZ** [mwittrien/BetterDiscordAddons#2517]
**Describe the bug**
The settings wont open when I click it

**To Reproduce**
click the settings button

**Expected behavior**
The sound settings are supposed to open but it doesn't, it gives an error

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/130910481/13bc3e52-e896-48dd-90ba-8543eaa8aa03)

**Discord Build (stable, ptb or canary):**
Stable 240237 (a1ba594)

**Comment by mwittrien** [comment]
#2515
