### ISSUE TITLE
[BUG] - BDFDB (I think)

### ISSUE THREAD

**Issue by Humper04** [mwittrien/BetterDiscordAddons#2518]
**Describe the bug**
When I open discord there is a grey bar with the red colored text "React Component Error" above the small hud in the bottom left.

**To Reproduce**
When I have discord at front, I see the error.

**Expected behavior**
I expected to open discord and not see the error.

**Screenshots**
![react component eror](https://github.com/mwittrien/BetterDiscordAddons/assets/69055766/b90e612e-a940-481e-8d79-cd930a1108df)

**Discord Build (stable, ptb or canary):**
I use the stabe build version 240237 (a1ba594)

**Comment by Humper04** [comment]
Side note: everything is on the latest version. My discord, BetterDiscord and all my other plugins.

**Comment by mwittrien** [comment]
#2515
