### ISSUE TITLE
BDFDB is not working, can not open settings...

### ISSUE THREAD

**Issue by Pauweltje** [mwittrien/BetterDiscordAddons#2519]
**Describe the bug**
none of the plugins for A better discord / BDFDB from DevilBro works, and when it worked, it is buggy as hel.

**To Reproduce**
Always

**Expected behavior**
I use the plugin a lot, for translation and images 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/2523468/6f849d10-d964-4748-a96e-3860bde16b94)

**Discord Build (stable, ptb or canary):**
Stable 240372 (63f8ac7) Host 1.0.9020 x86 (38517) Windows 10 64-Bit (10.0.22621)

**Comment by Renari** [comment]
https://github.com/mwittrien/BetterDiscordAddons/issues/2515
