### ISSUE TITLE
BadgesEverywhere issue

### ISSUE THREAD

**Issue by Grey421** [mwittrien/BetterDiscordAddons#252]
![image](https://user-images.githubusercontent.com/52113147/62701688-d04a8880-b9dc-11e9-8efd-58aa362370fe.png)

Might be due to having a short name, or it specifically affects the user of the plugin.

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/62708407-9fc21900-b9f3-11e9-9dc4-0eed1c7afea6.png)
nope, make sure its up to date
