### ISSUE TITLE
[BUG] - PluginRepo Not Showing Up / Freezes discord

### ISSUE THREAD

**Issue by Aircat1gif** [mwittrien/BetterDiscordAddons#2520]
**Describe the bug**
I feel like sometimes the plugin doesn't show up, or it shows up and freezes my discord until then.
And rarely shows up "Found 204 Plugins for PluginRepo" or something like that. (and still freezes my discord)

**To Reproduce**
When does the bug occur.
Installing betterdiscord and the plugin (including library)
**Expected behavior**
I expected it to show all of the plugins

**Screenshots**
Here i only have when its not shown
![NotShowingUp](https://github.com/mwittrien/BetterDiscordAddons/assets/143176761/f50a5d0b-9b57-4be9-91e2-490d9244a9be)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
It seems like it has been fixed back in 2022 but it broke for me since yesterday. i tried reinstalling discord, Including betterdiscord, restarting my computer and etc. It just doesn't shows up

**Comment by Renari** [comment]
#2515
