### ISSUE TITLE
[BUG] - Translator option not showing up on messages anymore

### ISSUE THREAD

**Issue by BenDol** [mwittrien/BetterDiscordAddons#2521]
**Describe the bug**
When right clicking on messages now the translate option doesn't appear.

**To Reproduce**
Right clicking on messages

**Expected behavior**
Show translate option

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/1935706/3ad8199c-cd9a-4b45-bd52-8689099d63ea)

**Discord Build (stable, ptb or canary):**
```
Stable 240372 (63f8ac7)
Host 1.0.9020 x86 (38517)
Windows 10 64-Bit (10.0.19045)
```
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/1935706/31b37aca-b461-42d2-ad67-6f56fcabcb92)

**Comment by Renari** [comment]
#2515

**Comment by BenDol** [comment]
Resolved as of the latest update
