### ISSUE TITLE
[BUG] - Hotkey Notes Not Work

### ISSUE THREAD

**Issue by frk1720** [mwittrien/BetterDiscordAddons#2522]
**Describe the bug**
The notes hotkey doesn't work when I click on it, it doesn't bring up the messages I've saved as notes before.

**To Reproduce**
Hotkey notes

**Expected behavior**
The page of my previously saved messages appears when I click the notes hotkey 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/86409871/e1ceaa1a-6851-4b24-9995-202f173746e0)

**Discord Build (stable, ptb or canary):**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/86409871/9f35ab68-abba-492a-8079-ac24d00bcb88)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/86409871/845bff88-6c51-4a13-af2f-e6dae19b7204)

**Comment by Renari** [comment]
#2515

**Comment by frk1720** [comment]
i already update core betterdiscord to latest update 1.9.5

**Comment by Renari** [comment]
Good now you wait because that doesn't fix the addon, if you would have read the better discord patch notes it says that it will not fix addons that you need to wait. The issue I linked shows that mwittrien is aware many things are broken.

**Comment by frk1720** [comment]
I hope that the dev who made personal pins can update the plugin so that personal pins can be used properly again.

**Comment by mwittrien** [comment]
#2515
