### ISSUE TITLE
[BUG] PinDM - Category header text have wrong style

### ISSUE THREAD

**Issue by orblazer** [mwittrien/BetterDiscordAddons#2523]
**Describe the bug**
The header text for pinned category is black and have different style then "Direct Message" section.

**To Reproduce**
1. Install plugin
2. Create new category
3. See text

**Expected behavior**
Correct look like "Direct Message" section

**Screenshots**
![Screenshot_20231027_155453](https://github.com/mwittrien/BetterDiscordAddons/assets/1344792/ed7c3b3d-a3d8-42df-97e8-d1f00a0b2472)

**Discord Build (stable, ptb or canary):**
Stable 240884 (d20955f)
Host 0.0.32 x64

**Additional context**
This is due to wrong "container" class, in custom category is use "container_q97qHp" but in "Direct Message" this is "container_de798d".

**Comment by mwittrien** [comment]
#2515
