### ISSUE TITLE
[BUG] - PLUGIN/Translator----Failed to translate(baidu) 

### ISSUE THREAD

**Issue by robindiy** [mwittrien/BetterDiscordAddons#2524]
**Describe the bug**
Today, I updated BDFDBv3.4.4 and Translator2.5.8, and found that Baidu's translation is invalid. I don't know if Baidu updated its AIP or is it due to BDFDB issues? Because it seems that the Translator did not affect the code update for Baidu translation

**To Reproduce**
When I use the translation function, I am prompted that I cannot connect to Baidu

**Expected behavior**
Please check if BDFDB has affected Baidu's translation function

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/1089382060550017154/1167484941349691483/Xnip2023-10-27_23-27-17.jpg?ex=654e4c14&is=653bd714&hm=07e28662fcd5b6981b101330c4d2fb20735f51d0f5946a4e4ee573b2a4995890&)

**Discord Build (stable, ptb or canary):**
Stable 240884 (d20955f) Host 0.0.281 arm64 OS X 10.15.7 (23.0.0)

**Additional context**
![Xnip2023-10-27_23-27-06](https://github.com/mwittrien/BetterDiscordAddons/assets/125145244/52db51d6-f674-48fa-bf45-d8a8eab2b603)
![Xnip2023-10-27_23-27-17](https://github.com/mwittrien/BetterDiscordAddons/assets/125145244/432c83a9-f7bb-46b6-9439-8e8ec412cb58)

**Comment by AIDA64S** [comment]
same
