### ISSUE TITLE
[BUG] - PinDMs

### ISSUE THREAD

**Issue by iiNekoMattyii** [mwittrien/BetterDiscordAddons#2525]
there are 2 issues i'm having with it on the latest version, its lagging my discord to the point of not being usable and the catagorys themselves look very broken

install the plugin and enable it

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/69323445/32e0f888-bca8-4884-88e5-13645e6e5665)

ptb and stable

**Comment by mwittrien** [comment]
#2515
