### ISSUE TITLE
[BUG] - PersonalPins not working as expected

### ISSUE THREAD

**Issue by andrwmai** [mwittrien/BetterDiscordAddons#2528]
**Describe the bug**
The plugin can save messages but the menu can't be opened. Clicking on the plugin icon doesn’t do anything. I know most plugins are broken but I'm just reporting so you're aware.

**To Reproduce**
Just enable the plugin and try opening the menu when in a chat.

**Discord Build (stable, ptb or canary):**
Discord stable 0.0.281 (0.0.281)

**Comment by mwittrien** [comment]
#2515
