### ISSUE TITLE
[BUG] - PLUGIN/BETTERFRIENDLIST

### ISSUE THREAD

**Issue by Kagetora120903** [mwittrien/BetterDiscordAddons#2529]
**Describe the bug**
Hidden and Favorites tab making discord crash and "React component error" appearing on the left of the message icon in the Friends tab

**To Reproduce**
Click on Hidden or Favorites tab and it instantly crashes discord and the "React component error" appears in the Friends tab whenever the plugin is enabled

**Expected behavior**
Shouldn't crash discord (hidden and favorites tab), i'm not sure what should appear instead of the error message

**Screenshots**
https://imgur.com/IkkxMPH

**Discord Build (stable, ptb or canary):**
Stable, latest version

**Additional context**

**Comment by mwittrien** [comment]
#2515
