### ISSUE TITLE
[BUG] - PLUGIN/DisplayServersAsChannels is broken

### ISSUE THREAD

**Issue by Pharaoh2k** [mwittrien/BetterDiscordAddons#2530]
**Describe the bug**

![GtNa7vv](https://github.com/mwittrien/BetterDiscordAddons/assets/5753365/bfc49027-68a8-44c1-879d-7efc1bfa3e99)

**To Reproduce**
See screenshot.

**Expected behavior**
See screenshot.

**Screenshots**
See screenshot.

**Discord Build (stable, ptb or canary):**
Latest stable and latest BD 1.9.5

**Comment by mwittrien** [comment]
No shit
#2515
