### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by raithebest** [mwittrien/BetterDiscordAddons#2531]
**Describe the bug**
**upon selecting the translate button. i dont see any options its broken**

**To Reproduce**
When does the bug occur.
**anytime you click the translate button to go into the settings**

**Expected behavior**
click the translate button and it doesn't display any settings

**Screenshots**
https://i.imgur.com/ZP6ZWoo.png

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Betterdiscord Core v1.9.5

**Additional context**

**Comment by mwittrien** [comment]
#2515
