### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by JohannKili** [mwittrien/BetterDiscordAddons#2538]
**To Reproduce**
When does the bug occur.

Random

**Expected behavior**

It Shows this:

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/139029143/56ce9002-c536-4ffd-b79a-b77628abb96a)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

PTB

**Additional context**

No

**Comment by mwittrien** [comment]
Issue with website and not the plugin
