### ISSUE TITLE
NotificationSounds v3.3.3

### ISSUE THREAD

**Issue by isaacay** [mwittrien/BetterDiscordAddons#254]
with NotificationSounds v3.3.3 enabled even with a 100% reset config discord crashes if you use go live

**Comment by mwittrien** [comment]
just tested and it didnt crash for me, must be another plugin

**Comment by xdMatthewbx** [comment]
Having this issue as well (tested without ANY other plugins).

**Comment by isaacay** [comment]
can confirm that my discord is crashing when i use golive with ONLY NotificationSounds enabled
