### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by DankMemeGuy** [mwittrien/BetterDiscordAddons#2540]
**Describe the solution you'd like**
I want to hide users messages, without blocking them. 

**Describe alternatives you've considered**
There is no alternative to the idea I'm suggesting.

**Additional context**
Blocking users allows the other user to know they're blocked since they can't react to your messages. This can cause some uncomfortable situations, and enable the blocked user to create alt accounts rto evade the block just to message you. I would like the ability to just select users to hide messages, without blocking them. 

The current code can stay the same, and you can just add a setting panel that lets people include users to hide, as if they were blocked.

**Comment by mwittrien** [comment]
Not the point of the plugin
