### ISSUE TITLE
[BUG] - Pligin/theme repo

### ISSUE THREAD

**Issue by thedevouttrout** [mwittrien/BetterDiscordAddons#2541]
**Describe the bug**
Cannot pull repo due to DDoS protection

**To Reproduce**
any time attempting to load plugin/theme repo

**Expected behavior**
error message describingh issue

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 240884 (d20955f)

**Additional context**

**Comment by mwittrien** [comment]
Issue with the website and not the plugin
