### ISSUE TITLE
[BUG] - ImageUtilities: Images load forever when opened to view in full

### ISSUE THREAD

**Issue by IAmToastyGhost** [mwittrien/BetterDiscordAddons#2543]
**Describe the bug**
When I open an image for a bigger view of it, the loading icon stays forever, as if the image won't load when opened. I also can't use the ImageUtilities zoom when this happens.

**To Reproduce**
Open an image while ImageUtilities is enabled.

**Expected behavior**
The image loads, allowing me to view it and use the ImageUtilities zoom tool.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/70232680/92a1a542-6fa5-48c5-96fc-fc81016de191)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/70232680/248f4db2-d6f7-4d10-a56e-693fcd9123b9)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/70232680/971b3288-2348-4216-925a-4b3a13df948f)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This does not occur when ImageUtilities is disabled.

**Comment by mwittrien** [comment]
#2515
