### ISSUE TITLE
[BUG] - ServerFolders v7.2.0 update makes servers within folders inaccessible

### ISSUE THREAD

**Issue by liam-edwards** [mwittrien/BetterDiscordAddons#2546]
**Describe the bug**
Updated the ServerFolders plugin to 7.2.0 just now from 7.1.9 and have noticed that the folder column will open up however nothing is displayed except the divider between folder groups. v7.1.9 had issues but it otherwise worked.

**To Reproduce**
After updating to v7.2.0, open a folder.

**Expected behaviour**
After opening a folder, the list of servers within that folder should be visible as per previous versions of the plugin.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/82093519/0951c6c6-93db-4f1c-98d9-617f0ba1ad87)
You can see in the screenshot, two folders are open however nothing is displayed, just the divider.

**Discord Build (stable, ptb or canary):**
Stable 241602 (86f279e)

**Additional context**
I have attempted this with all other plugins disabled and uninstalled in addition to just using it regularly.  
BDFDB version is v3.5.1

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord
