### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by Spyrois2cool** [mwittrien/BetterDiscordAddons#2547]
**Describe the bug**
Notification sounds from threads do not play at all.

**To Reproduce**
Receive a notification from a thread that has notifications turned on.

**Expected behavior**
Notifications should play a sound.

**Screenshots**
I still cannot screenshot a sound. (Or lack thereof)

**Discord Build (stable, ptb or canary):**
Stable 242566 (12901f7)

**Additional context**
Deleting 0BDFDB.data.json and reloading does not fix the problem. I am STILL having the issue. Again, it was working just fine for me yesterday. 

Am also curious if there is a way to add it in the sound configurations. Maybe that could get it to work?

**Comment by mwittrien** [comment]
Playing just fine for me

**Comment by Spyrois2cool** [comment]
It isn't working on my end...maybe I did something wrong?

**Comment by mwittrien** [comment]
screenshot your settings

**Comment by Spyrois2cool** [comment]
Which settings? For the specific plugin? Sound config where I customize each individual sound? Or just the global volume setting? Or default discord notification settings?

**Comment by mwittrien** [comment]
sound config for threads

**Comment by Spyrois2cool** [comment]
That's just it. There IS no sound config for threads. There is for servers, getting mentioned, someone replying for you, DMs, group chats, etc. But none for threads specifically. 

I checked for updates and the most up to date version is from Oct 21 this year.

**Comment by mwittrien** [comment]
Well Threads use the same sound as normal channels so (Message)

**Comment by Spyrois2cool** [comment]
Those work perfectly fine. Here's a screenshot of that if ya need. I still get notifications from channels perfectly fine, but not threads. And yes, I have notifications for the threads set to all.

![Threads Settings](https://github.com/mwittrien/BetterDiscordAddons/assets/50086538/ecdfd694-d3e4-46b7-acaa-686e188be253)

**Comment by mwittrien** [comment]
Honestly. No Idea. It works fine for me and anyone else I asked to try.
