### ISSUE TITLE
[BUG] - Server Hider : Crash - freeze when using quick switcher (CTRL + K)

### ISSUE THREAD

**Issue by Lisandra-dev** [mwittrien/BetterDiscordAddons#2548]
**Describe the bug**
Discord totally froze when using the quick switcher to find and open a server that was hidden.

**To Reproduce**
- Hide a server
- Use the CTRL + K to open the quick switcher
- Try to go in the hidden server

**Expected behavior**
- Opening the hidden server as normal

**Screenshots**
/

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**
/

**Comment by mwittrien** [comment]
Seems to be working fine for me, BetterDiscord Server is hidden and I used Ctrl + K to switch to it.

![test](https://github.com/mwittrien/BetterDiscordAddons/assets/23700969/abb30a9f-e0ce-470f-8a7a-89b7f279e326)

**Comment by Lisandra-dev** [comment]
Do you think a discord experiment can cause that?

**Comment by mwittrien** [comment]
No clue

**Comment by Lisandra-dev** [comment]
It seems that the bug occurs on server where the entire folder was hidden.
The folder can be hidden because all folder in it are hidden, but also if it was hidden manually enterly.
