### ISSUE TITLE
[BUG] - Edit Users

### ISSUE THREAD

**Issue by MiahFuta** [mwittrien/BetterDiscordAddons#2549]
**Describe the bug**
When the plugin is enabled, when you try to click on someone's name in chat, you have to click the name twice to open the user popup modal. 
Also, once the users popup modal is open, if you move your mouse over in and out of it, it shakes the popup modal which is annoying. You also have to click outside of the modal more than once for the modal to close.
Also, if you click on a users mention in a chat message it does not open the popup modal at all, like it should.

**To Reproduce**
Any time the plugin is enabled. Did not happen before the big discord update was released that broke everything.
I tried disabling all other plugins to see if maybe it was caused by something else, but nothing seems to be interfering with it. Without being able to get into dev tools without discord crashing, it makes it harder for me to narrow down the exact issue.
Hopefully this information/report helps you resolve the issue.

**Expected behavior**
Single clicks on usernames and user mentions should open the users popup modal, and the user popup modal should not shake when you move your mouse in and out of the element. Also, clicking outside of the modal should close the modal with a single click, not two. Also, clicking on a users mention in chat should open the modal.

**Screenshots**
PLUGIN ENABLED:
![ScreenRecording-11-03-2023_19_53_58](https://github.com/mwittrien/BetterDiscordAddons/assets/5152979/2b228ad8-a5b0-4745-9e34-91e9e019e325)

PLUGIN DISABLED:
![ScreenRecording-11-03-2023_19_59_08](https://github.com/mwittrien/BetterDiscordAddons/assets/5152979/29cbe50a-63cb-4308-805c-84453f47892a)

**Discord Build (stable, ptb or canary):**
Stable (latest updates for discord and the plugin)

**Additional context**
I love this plugin because I'm an admin in a server that has many foreign users, and renaming those users to a name that I can understand really helps. Thanks for all your hard work on this plugin and all of your others, you're a life saver!

**Comment by ElRaphik** [comment]
Hey, just here to add that I have the exact same issue when enabling ShowBadgesInChat.
(Wont open a new issue for it as the bug may come from the same place.)

**Comment by MiahFuta** [comment]
Thanks for the fix, however, the other part of the issue still exists (clicking on mentions in messages does not open the profile modal like it should)

example
![ScreenRecording-11-04-2023_18_11_31](https://github.com/mwittrien/BetterDiscordAddons/assets/5152979/8c3879f5-384c-4348-a527-d1f7480851a6)
