### ISSUE TITLE
[BUG] - ImageUtilities not working

### ISSUE THREAD

**Issue by Mattem300** [mwittrien/BetterDiscordAddons#2552]
**Describe the bug**
When I view a image, ImageUtilities does not even do anything, nothing related to ImageUtilities shows up, only "Open in browser". Tried reinstalling ImageUtilites or checking if BDFDB is installed (it was installed), but nothing was able to fix it!

**To Reproduce**
Every time I view a image.

**Expected behavior**
I expected that ImageUtilities was going to give a Zoom button, Copy button and etc. But no nothing, No copy or zoom

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/118678848/5011815b-309f-4be8-8dcc-8f96eab7c18d)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
ImageUtilities just doesn't work at all. The plugin is enabled, BDFDB is installed and still nothing.

**Comment by mwittrien** [comment]
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/23700969/e51fe114-3e91-4de3-a4de-2a631336ecf7)

works fine,

try deleting 0BDFDB.data.json and reload discord
