### ISSUE TITLE
[BUG] - NotificationSounds/Bug

### ISSUE THREAD

**Issue by Cloufers** [mwittrien/BetterDiscordAddons#2553]
Hello. My friend and I decided to put a custom song on the Discord call, and we can't load any files into the plugin because of this error:
![Screenshot_2](https://github.com/mwittrien/BetterDiscordAddons/assets/69718347/712551fe-e5a0-49c1-9cef-dac86ff5b940)

No matter what song we're putting into it, it's showing the same error.

**Comment by MegaMegera800** [comment]
Having the same issue. Cannot upload custom .mp3 files into NotificationSounds no matter the directory the source is stored in.

How to replicate:
1. Literally just try to upload any sound.
