### ISSUE TITLE
[BUG] - Complete Timestamp make Discord lagging

### ISSUE THREAD

**Issue by Traktool** [mwittrien/BetterDiscordAddons#2554]
**Describe the bug**
When CompleteTimestamp is enabled, if you change servers or focus Discord, it will lag for about 5 seconds.
No error in the console

**To Reproduce**
Change server of focus Discord

**Expected behavior**
No lag when changing server / focus Discord

**Discord Build (stable, ptb or canary):**
CompleteTimestamp v1.6.7
Better Discord 1.9.5
Discord Stable 243588

**Comment by mwittrien** [comment]
Some Plugins will bound up to cause a performance reduction due to additional code being executed. Nothing i can do about it.

And the lag is hardly a 5 second lag. Maybe half a second.
