### ISSUE TITLE
[BUG] - RemoveBlockedUsers 

### ISSUE THREAD

**Issue by abandon-the-flesh** [mwittrien/BetterDiscordAddons#2556]
**Describe the bug**
When a blocked user message occurs on a channel, the channel buffers up to "last unread message" even though you've clicked "marked as read" or scrolled all the way down and read every message.

**To Reproduce**
Opening a channel to send a message, when no other messages are present. I believe this is due to the last message being sent is from the blocked user.

**Expected behavior**
I expect to enter the channel scrolled to the bottom most recent message.

**Screenshots**
Wouldn't make sense to post any and it's difficult for me to reproduce.

**Discord Build (stable, ptb or canary):**
Stable 244133 (351234d)
Windows 10 64-Bit (10.0.19045)

**Additional context**
Is this a general discord setting I am missing? I'd rather have chat always scrolled to the bottom instead of being hung up on the "last unread message" - but it seems to force scroll up to the last "new unread" line even though I've already read/scrolled down when a blocked user sends a message if that makes sense.

Edit* Additional info, I just confirmed it bumps you back to the first message of that DAY. I don't get any "new" redline or highlight.

**Comment by mwittrien** [comment]
Sadly I can't fix this due to how discords scroller works
