### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by PadreJesus** [mwittrien/BetterDiscordAddons#2557]
**Describe the bug**
Makes Discord increasingly slow to use.
Changing server, channels or clicking to view a user profile is painsly slow.

**To Reproduce**
Enabling "CharCounter"

**Expected behavior**
Discord running smoothly.

**Screenshots**
None

**Discord Build (stable, ptb or canary):**
Discord Stable

**Additional context**
I tested with only the BDFBD plugin and the CharCounter enabled and themes disabled, so I concluded being the CharCounter (could be the library implementation too) to be causing the problem.

**Comment by mwittrien** [comment]
Some plugins might cause a slight delay on certain GUI interactions, the worst being EditUsers, due to the cheer amount of elements it interacts with

None such issue occur to me with CharCounter tho
