### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Brain20101** [mwittrien/BetterDiscordAddons#2558]
plugin StaffTagv1.6.0 does not work the reason is not known The Discord build is stable
![Снимок экрана 2023-11-11 092920](https://github.com/mwittrien/BetterDiscordAddons/assets/150506305/dbe938f7-2f69-47a8-a882-6bc4335dcfba)
![Снимок экрана 2023-11-11 092942](https://github.com/mwittrien/BetterDiscordAddons/assets/150506305/60c785c4-da0d-45ec-9720-644fa9242bd1)

**Comment by mwittrien** [comment]
Works just fine
