### ISSUE TITLE
[BUG] - Settings Icons

### ISSUE THREAD

**Issue by HRTK92** [mwittrien/BetterDiscordAddons#2559]
**Describe the bug**
Icons become different icons when selecting items in settings

**To Reproduce**
Add the following code to your custom CSS and save it
```
@import url(https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/SettingsIcons.css);
```

**Expected behavior**
Icons should not change before and after selecting an item.

**Screenshots**
https://github.com/mwittrien/BetterDiscordAddons/assets/70054655/e8506d64-aa4a-4ada-ab64-c42f43ace09d

**Discord Build (stable, ptb or canary):**
Stable 245361 (e26278f)

**Comment by mwittrien** [comment]
What's `請求` for a section? I don't have that in my Discord

**Comment by HRTK92** [comment]
I tried changing the app to English.
This section shows a user’s payment settings page.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/70054655/30481fb0-825a-459e-898c-4270919a75a1)

**Comment by mwittrien** [comment]
Ahh Clips is new, ill check
