### ISSUE TITLE
[BUG] - Plugin Repo not loading any Plugins

### ISSUE THREAD

**Issue by GrPK** [mwittrien/BetterDiscordAddons#2562]
**Describe the bug**
Title. No plugin is loaded when I open the Plugin Tab or Check updates

**To Reproduce**
Just try to open Plugin Repo Menu

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/31523635/fe3cade9-1b40-4a49-8782-ad555db4c025)

**Discord Build (stable, ptb or canary):**
Stable 247232 (a5bd24a)

**Comment by OrionAF** [comment]
I have the same.  Literally 5 minutes ago I installed BD, and 3 minutes ago I installed Plugin Repo 2.5.3 from the website.  I received a banner at the top to update to 2.5.4, which I did, and now no plugins are showing in Plugin Repo.  I don't know if there were plugins before I updated.

**Comment by mwittrien** [comment]
Website might have some issues
