### ISSUE TITLE
[BUG] - PluginRepo/No plugins showing up.

### ISSUE THREAD

**Issue by Sebbog1** [mwittrien/BetterDiscordAddons#2564]
**Describe the bug**
I can't see any of the plugins using plugin repo. It also says 0/0 plugins. I have not searched for anything when this happens. The settings tab still shows the settings.

**To Reproduce**
When I open the PluginRepo tab.

**Expected behavior**
That the plugins show up.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/100369203/5a6e457d-9554-4bdf-b995-cea91d98be59)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/100369203/8ca5e27e-2446-4f2c-9394-69d74da0d634)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
BDFDB v3.5.3
PluginRepo v2.5.4
Stable 247929 (393c680)
Host 1.0.9024 x86 (40010)
Windows 10 64-Bit (10.0.22621)
I don't actually use Windows 10, I don't know why it says that, I have Windows 11.

**Comment by mwittrien** [comment]
Website is down

**Comment by Sebbog1** [comment]
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/100369203/5903ac62-8736-4290-9640-b6545e72dac6) It works now
