### ISSUE TITLE
[BUG] - EmojiReplace: Doesn't work on super emojis

### ISSUE THREAD

**Issue by aaronliu0130** [mwittrien/BetterDiscordAddons#2565]
**Describe the bug**
Currently, when a super emoji's animation plays, the emoji is still in Twemoji. It suddenly goes to the replaced version after the animation ends.

**To Reproduce**
Hover over a super emoji that was originally a Twemoji.

**Expected behavior**
Always replaced emoji

**Comment by mwittrien** [comment]
Sadly impossible, since the emojis in the burst effect aren't real images that can be altered via CSS

**Comment by aaronliu0130** [comment]
Perhaps a plug-in can be made to compat in this feature?

**Comment by mwittrien** [comment]
Possible maybe

I am not going to make my theme plugin relied tho
