### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications: Add Voice Channel Join Notifications

### ISSUE THREAD

**Issue by cheese3066** [mwittrien/BetterDiscordAddons#2566]
Describe the solution you'd like:
I would like to suggest an enhancement for the "FriendNotifications" Discord plugin. It would be great if the plugin could notify users when a friend or observed user joins a voice channel on Discord. Specifically, the notification should trigger regardless of the user's microphone status or online status. This feature would be particularly useful for knowing when friends are available in voice channels for potential group activities or gaming sessions.

Describe alternatives you've considered:
As an alternative, if integrating this feature directly into the plugin is too complex, perhaps a separate, lightweight plugin that focuses solely on tracking and notifying voice channel activity could be developed. This could work in tandem with the existing "FriendNotifications" plugin.

Additional context:
This feature would enhance the user experience by providing more immediate and relevant information about friends' activities on Discord, especially for those who frequently use voice channels for communication or gaming.

**Comment by mwittrien** [comment]
This was suggested before and I decided against it, feelsnto invasive
