### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by FinnTheDrox** [mwittrien/BetterDiscordAddons#2567]
**Describe the bug**
copy paste when image highligted just shows nothing in copy history despite saying "image copied" 

**To Reproduce**
clicking on image and in the bottom clicking "copy image" shows text but dosnt work. 

**Expected behavior**
an image to be copied. 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/87833032/2c4d7351-c517-4aca-8eb9-af7240e1cffc)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/87833032/8d0f9488-eab7-4224-ae17-4e6fb1327b3c)

**Discord Build (stable, ptb or canary):**
stable

**Comment by lurts** [comment]
Happens to me as well. Using right click -> copy image only works for .png and .jpg since I assume discord itself handles that but .webp and similar don't work with the right click menu. The "copy image" button below the image does not work for either format.

**Comment by logan97alexander** [comment]
> Happens to me as well. Using right click -> copy image only works for .png and .jpg since I assume discord itself handles that but .webp and similar don't work with the right click menu.

This is continuing for me even after updating. The "copy image" link beneath a selected image works just fine, but right-clicking and copying the image from the context menu doesn't work at all, regardless of filetype. The green "copied to clipboard" toast pops up, but there is in fact nothing in my clipboard-- doing this seems to actually delete whatever was _previously_ in my clipboard as well.

Very strange and annoying, as I'm used to copying from the context menu (I use this plugin for other features, not this; it took some trial-and-error & searching to even discover it was this plugin causing it).
