### ISSUE TITLE
[BUG] - BDFDB/ClearVision

### ISSUE THREAD

**Issue by RhenaudTheLukark** [mwittrien/BetterDiscordAddons#2572]
**Describe the bug**
The Settings Panel cannot be opened, even after deleting the plugin's data json file.

**To Reproduce**
1. Install and enable BDFDB
2. Try opening the plugin's Settings Panel

**Expected behavior**
The Settings Panel should be visible.

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 250833 (84e28a2)

**Additional context**
I wanted to open NotificationSounds' Settings Panel at first but it didn't work, so I investigated BDFDB and that's how I found this issue.

**Comment by mwittrien** [comment]
Update BDFDB to 3.5.5
