### ISSUE TITLE
[BUG] - BDFBD PLUGIN KEEPS CRASHING

### ISSUE THREAD

**Issue by AdamHubert13** [mwittrien/BetterDiscordAddons#2574]
**Describe the bug**
BDFBD is not working and keeps crashing even after restarting/reinstalling.
And plugins made by DevilBro that need the BDFBD plugin aren't working.

**To Reproduce**
Whenever I try to launch any plugin Made by DevilBro that needs BDFBD, 
It shows this. **(see attached picture)**

**Expected behavior**
The plugins should work and not crash

**Discord Build (stable, ptb or canary):**
I'm using the Stable Build

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/69331848/62ae9e44-9ab2-4420-bcc4-515c69a02ca6)

**Comment by mwittrien** [comment]
Update BDFDB to v3.5.5
