### ISSUE TITLE
[BUG] - NotificationSounds/ClearVision

### ISSUE THREAD

**Issue by RhenaudTheLukark** [mwittrien/BetterDiscordAddons#2575]
**Describe the bug**
Trying to open the Settings panel of the plugin NotificationSounds triggers an error, which only says "Could not open settings for NotificationSounds".

**To Reproduce**
1. Install BDFDB 3.5.5 & NotificationSounds 3.8.8.
2. Enable both plugins.
3. Try opening NotificationSounds' Settings panel.

**Expected behavior**
The plugin's Settings panel should be visible.

**Discord Build (stable, ptb or canary):**
Stable 250836 (84e28a2).

**Comment by mwittrien** [comment]
Delete NotificationSounds.config.json and reload discord

**Comment by RhenaudTheLukark** [comment]
...nevermind, I guess a restart did the trick, how odd. Thanks!
