### ISSUE TITLE
[BUG] - EditUsers non-functional

### ISSUE THREAD

**Issue by Nermal242** [mwittrien/BetterDiscordAddons#2577]
**Describe the bug**
The EditUsers plugin is no longer functional.

**To Reproduce**
After enabling the plugin, you will notice that the option to edit a user is missing when you right-click. If you attempt to modify the plugin settings, an error message will appear.

**Expected behavior**
The user should be able to edit the user and change the plugin settings without encountering any error messages.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/56689711/4eae732d-f82b-47ff-9bf4-3ee722f7444f)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/56689711/15323bde-1b2d-4576-b0a7-7886dd211e5d)

**Discord Build (stable, ptb or canary):**
Ptb 251390 (e7fdd14) Host 1.0.1046 x86 (40753) Windows 10 64-Bit (10.0.22631)

**Comment by mwittrien** [comment]
Update BDFDB
