### ISSUE TITLE
AB:CD:EF.00EF Timestamps (CompleteTimestamps v1.6.7)

### ISSUE THREAD

**Issue by Catzrule5** [mwittrien/BetterDiscordAddons#2581]
Milliseconds seem to have 2 zeroes when the second count and millisecond count are the same (i.e. 16:57:23.0023). I assume this because all 4 instances I found of this bug were of the form AB:CD:EF.00EF. Surprised and not surprised that no one else seemed to notice ^w^'

**Comment by Catzrule5** [comment]
If E=0, the bug does not happen. I.e. 15:25:**0**8.0**0**8 is represented as it should be.

**Comment by acendvgnt** [comment]
https://github.com/mwittrien/BetterDiscordAddons/blob/80aa8daee4255a2759f886f5609973b2ddd3d4b6/Library/0BDFDB.plugin.js#L6007

It seems that `seconds` should be `milli` instead.

**Comment by Catzrule5** [comment]
Thank you, can I assume this bug will be fixed in v1.6.8?

**Comment by Catzrule5** [comment]
Ah ok, thank you ^w^
