### ISSUE TITLE
[BUG] - Image Utilities

### ISSUE THREAD

**Issue by HoltzFan10** [mwittrien/BetterDiscordAddons#2583]
**Describe the bug**
copy function for image isnt working, image saving as wrong filetype.
also looks like the latest bdfdb update broke the little info bar under the image. 

**To Reproduce**
open right click menu while image is open and use respective menu options

**Expected behavior**
the image to be copied, and the image to be saved as its original file type.

**Screenshots**
https://cdn.discordapp.com/attachments/997168121683124304/1182703507510399057/www_screencapture_com_2023-12-8_10_19.webm?ex=6585a979&is=65733479&hm=9072e34cc923012fcb2e6b0cb21ce4b453b8edf675c981ba61a10f8cba786cbc&
this is a video showing the bug, please watch it before closing this and saying its fixed.

**Discord Build (stable, ptb or canary):**
stable discord, no plugins used other than BDFDB and ImageUtilities

**Comment by HoltzFan10** [comment]
I am using the latest version of both BDFDB and Image utilities. BDFDB is at 3.5.6 and image utilities is 5.3.6

in the video i am showing that the image doesnt copy, and that it saves as the wrong file type. 
the image is in the video, it is a JPG

**Comment by HoltzFan10** [comment]
So what do i do? why is this broken for me? did you make sure that you click the image so it pops up first like in the video? because the video shows it not working when i do it

**Comment by mwittrien** [comment]
Yes i did, no clue why its broken for you

**Comment by mwittrien** [comment]
Maybe post your ImageUtilities.config.json in here

**Comment by mwittrien** [comment]
Should be working now
