### ISSUE TITLE
[BUG] - ImageUtilities/Videos and GIFs restart on mouseover

### ISSUE THREAD

**Issue by SlamWeasel** [mwittrien/BetterDiscordAddons#2584]
**Describe the bug**
Both on the mouse enter and the leave event of a video or gif it restarts

**Expected behavior**
To not do that

**Screenshots**
![Bug](https://github.com/mwittrien/BetterDiscordAddons/assets/63350349/edceb02e-0087-43bf-9623-87411e2142b6)

**Discord Build (stable, ptb or canary):**
Stable 252966 (b583bea)
**BD Build:**
1.9.6

**Comment by HyperHitystic** [comment]
I have the same problem as well, though I never found the solution yet

**Comment by Leah96xxx** [comment]
I can confirm I have this issue too.

It seems to only affect direct uploads, not link embeds. No errors in console when it happens.

Also, the restart happens when the cursor enters the post's boundary, not just the player itself. SlamWeasel's screencap does show this, but it's not the clearest so I thought I'd highlight that in case it's relevant.

**Comment by MiahFuta** [comment]
Quick Fix: Downgrade to version 5.3.4 and manually change the version number to 5.3.7 to regain normal functionality until the plugin is updated to fix this issue.

**Comment by MelloLuvsPeen** [comment]
> Quick Fix: Downgrade to Version [5.3.4](https://github.com/mwittrien/BetterDiscordAddons/blob/b1422ee36d36a9bc0127aa691207dfc09db30021/Plugins/ImageUtilities/ImageUtilities.plugin.js) and manually change the version number to 5.3.7 to regain normal functionality until the plugin is updated to fix this issue.

this works, thank you

**Comment by SlamWeasel** [comment]
nuh-uh
The issue still persists on gifs

**Comment by MiahFuta** [comment]
> nuh-uh
> 
> The issue still persists on gifs

I make another bug report about it, he wants a video of it but I'm not able to do that atm, if you wanna help out and give him the video in that other report I made that would be amazing. I don't think he checks the closed reports.

**Comment by SlamWeasel** [comment]
I can even make a new one, since its not only with gifs

**Comment by Leah96xxx** [comment]
It is still doing it, but nowhere near as bad as before
