### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by winnmods** [mwittrien/BetterDiscordAddons#2585]
**Describe the solution you'd like**
add MSN/Windows Live Messenger emojis

**Describe alternatives you've considered**
nothing

**Additional context**
like this 
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/152745386/20c237ae-e54b-4d91-b142-00dfc75f3c6c)

**Comment by mwittrien** [comment]
Doesn't exist on EmojiPedia

**Comment by zencodes1** [comment]
why use emojipedia💀
