### ISSUE TITLE
[BUG] - ImageUtilities - Gifs causing scroll bounce

### ISSUE THREAD

**Issue by Leah96xxx** [mwittrien/BetterDiscordAddons#2586]
**Describe the bug**
Gifs seem to be causing the screen to bounce when trying to scroll, but only when the gif starts playing (sometimes when it stops too, but mostly when it starts).

For me, I'm sometimes only able to move it from the edge of the screen using the scrollbar, as using my mouse wheel isn't fast enough to overcome the bouncing.

Issue persists after restarting Discord.

When the gif is eventually allowed to play, the following error will be logged in the console:
`ImageUtilities.plugin.js:1216 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22`

**To Reproduce**
Someone posts a gif, try to scroll it onto the screen, get bouncy.

**Expected behavior**
Normal scrolling.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by Leah96xxx** [comment]
Edited my post to be a little more clear.

I've also confirmed that it's not due to the mouse enter/exit issue reported in #2584, as it happens even if my cursor isn't near the post. I may still be related though

**Comment by edo9300** [comment]
Can confirm it also happens with videos that are directly uploaded to discord, but not on videos that are reproduced from links, the restart is actually happening while hovering the message containing the video

**Comment by ShadowT3mplar** [comment]
So I've just done some digging into this, and it looks like having the "Show Image Details In the Image Description" option enabled causes GIFs to bounce. 

This does not happen while using the Hover Tool Tip option. Disabling the offending option stops the bouncing so hopefully someone else can confirm this is the probable cause.
