### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace - Blobmoji

### ISSUE THREAD

**Issue by gaussandhisgun** [mwittrien/BetterDiscordAddons#2587]
I mean, just [look at this thing](https://github.com/C1710/blobmoji). They are small, and squishy, and very emotional. 
![изображение](https://github.com/mwittrien/BetterDiscordAddons/assets/63512006/8a96d6ee-2fc6-4b6c-aa46-e05ea1dc875d)

I got to making a replacement emoji sheet for this stuff some time ago but stopped halfway and never got it finished. You seem like the kind of person to do it right.
![discord-emote-sheet-general](https://github.com/mwittrien/BetterDiscordAddons/assets/63512006/3b16f4e0-653d-41c2-b536-73d41f1f8205)

**Comment by nanopone** [comment]
seconding. i really badly want this since its already my system emoji font
