### ISSUE TITLE
[BUG] - Translator

### ISSUE THREAD

**Issue by RoyDubnium** [mwittrien/BetterDiscordAddons#2588]
**Describe the bug**
If you try to translate a message in a channel after having previously clicked a reply (taking you to the original message), upon the translation finishing successfully, it will jump to the message of the reply, regardless of how far it may be from the translated message

**To Reproduce**
1. Click on a reply to take you to its original message.
2. scroll to a different part of the same channel to a message that needs translating
3. Translate the message
4. You should get pulled back to the message from earlier

**Expected behavior**
The translation operation should not jump to any message at all, or it should jump to the message that is actually being translated

**Screenshots**
![Recording](https://github.com/mwittrien/BetterDiscordAddons/assets/72664566/7d368762-1501-491e-8607-6ff04c16b5e5)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Sadly cant be fixed
