### ISSUE TITLE
[BUG] - EmojiReplace - input field emotes are broken

### ISSUE THREAD

**Issue by gaussandhisgun** [mwittrien/BetterDiscordAddons#2591]
**Describe the bug**
It seems, Discord has broke something again. This time its the... emoji picker icon? Seems like the new icons patch made it so the emoji picker icon is now an *icon* and not an emoji. 

**To Reproduce**
Open a chat, look at the emoji picker icon. Try hovering it, too.

**Expected behavior**
It should look fine.

**Screenshots**
![изображение](https://github.com/mwittrien/BetterDiscordAddons/assets/63512006/44c32a4f-9141-48b3-af2b-1e62d32309c5)
![изображение](https://github.com/mwittrien/BetterDiscordAddons/assets/63512006/30333d1f-60ea-4790-a26e-c4c1c18258b8)

**Discord Build (stable, ptb or canary):**
stable (Vencord)

**Additional context**
-

**Comment by Avakining** [comment]
Can confirm this happens on PTB (BetterDiscord) as well.
