### ISSUE TITLE
[BUG] - UserNote

### ISSUE THREAD

**Issue by black-trush** [mwittrien/BetterDiscordAddons#2592]
**Describe the bug**
1)User menu not display "User Note"
2)in Pluginlist, can't open preference
**To Reproduce**
every time

**Expected behavior**
Not available as it does not appear in the menu

**Screenshots**
![usernote1](https://github.com/mwittrien/BetterDiscordAddons/assets/70010919/b2bdc8f9-9708-4749-b22c-907035236b18)
![usernote2](https://github.com/mwittrien/BetterDiscordAddons/assets/70010919/d01df57e-4118-4529-93f6-af6ee104d8b4)

**Discord Build (stable, ptb or canary):**
stable,PTB,Canary ALL

**Additional context**

**Comment by mwittrien** [comment]
What version is your BDFDB plugin

**Comment by black-trush** [comment]
I am very sorry. It was caused by a plugin called bdfdb-s that I had installed previously.
I removed this plugin and confirmed that it works correctly.
