### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by isnt-one** [mwittrien/BetterDiscordAddons#2593]
**Describe the solution you'd like**
Add options to block all stream and activity notification sounds from blocked users. Add option to hide blocked users from stream spectators list.

**Comment by mwittrien** [comment]
What sounds?

**Comment by isnt-one** [comment]
the notification sounds that discord plays when the events happen for those mentioned notification sound events that are listed on the notifications settings page in settings.
the events are named stream_started, stream_ended, stream_user_joined, stream_user_left, activity_launch, activity_end, activity_user_join, activity_user_left.

**Comment by mwittrien** [comment]
nothing i can do about it, since there is no information on these event on who triggered these sounds

**Comment by isnt-one** [comment]
based off of how you previously checked current and cached voice users, you can very easily determine who triggered the events the same way.

**Comment by mwittrien** [comment]
If it's that easily feel free to do it yourself and do a PR
