### ISSUE TITLE
[BUG] - ImageUtilities Scrolling Bug

### ISSUE THREAD

**Issue by MiahFuta** [mwittrien/BetterDiscordAddons#2594]
**Describe the bug**
Version 5.3.8 Scrolling when there are gifs in the chat, causes the scroll to now work correctly and jump around.

**To Reproduce**
Install the latest update Version 5.3.8 and scroll around, if your mouse is over a gif, it causes scrolling issues

**Expected behavior**
Normal scrolling like in Version 5.3.4

**Discord Build (stable, ptb or canary):**
Stable 254888 (4d180e8)
ImageUtilities v5.3.8

**Additional context**
Temp fix = install version 5.3.4 and change the version number to 5.3.8

**Comment by mwittrien** [comment]
This issue was already fixed with 5.3.8

If it still occures with 5.3.8, record a video for me

**Comment by SlamWeasel** [comment]
The issue persists
![gif bug](https://github.com/mwittrien/BetterDiscordAddons/assets/63350349/ecaa9b5c-2def-4afc-8810-baab197639a7)

**Comment by MiahFuta** [comment]
[Link to a GIF of the issue](https://cdn.discordapp.com/attachments/1167238455009484862/1186741664555995248/ScreenRecording-12-19-2023_13_32_08.gif)

The scrolling issue seems to happen almost always when hovering gifs and scrolling, sometimes not, it's weird
So this only happens on the latest version, the last version that worked correctly for me is 5.3.4
Also the gifs still restart as well when you hover them and exit out of them
But yeah, idk 5.3.4 works flawlessly, so I'll be downgrading to that again
