### ISSUE TITLE
[BUG] - GameActivityToggle Black When Off (Dark Theme)

### ISSUE THREAD

**Issue by deepspaceaxolotl** [mwittrien/BetterDiscordAddons#2595]
**Describe the bug**
The new version of GameActivityToggle makes the gamepad in the toggle black when it's turned off when using the dark theme, which makes it near invisible.

**To Reproduce**
Switching the toggle to off while in dark mode.

**Expected behavior**
The icon being as before, brighter on the dark mode background.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/50278439/9bf66db1-855c-4d50-8526-9d7c38443b7b)

**Discord Build (stable, ptb or canary):**
Stable 253462 (2d42f59)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
