### ISSUE TITLE
[BUG] - PinDM's

### ISSUE THREAD

**Issue by Sellexie** [mwittrien/BetterDiscordAddons#2596]
Whenever I click a chat that's not in a Pinned channel, it will scroll my DM's wheel down more then half way and I have to scroll back up to get to the top again. 
This happens every time I click a chat/DM thats not in a pinned channel. 

This is the only addon I have for Discord and only PlugIn I use. 

I'm at the top with the 2nd DM open
![screenshot1](https://github.com/mwittrien/BetterDiscordAddons/assets/154392400/8206ebbc-d0bd-40d7-a5c9-a09144055bf8)

I click the top DM' and this is where it auto scrolls too
![screenshot2](https://github.com/mwittrien/BetterDiscordAddons/assets/154392400/252a17e1-a6bf-41da-9154-9434ecae5843)

You can see my scroll wheel here
![screenshot3](https://github.com/mwittrien/BetterDiscordAddons/assets/154392400/beb9d029-89b4-46c6-bdac-acf89644c031)

**Comment by mwittrien** [comment]
Happens due to the closed categories with a lot of DM channels in them on top, since discord thinks these DM channels are in the list and adds them to the scroll amount, sadly nothing i can do about it, since i can't figure out where the scrolling happens
