### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by DariusSanguna** [mwittrien/BetterDiscordAddons#2598]
The lastest update of ImageUtilities to 5.3.9 broke the Preview Images of Link Embeds.

![grafik](https://github.com/mwittrien/BetterDiscordAddons/assets/154528312/c5cbc4a5-f518-4843-a597-d851de7e5cb6)

Versions
Better Discord 1.9.7
Discord Stable 255949 (85ad063) 
Host 1.0.9028 x86 (41936) 
Windows 10 64-Bit (10.0.19045)

**Comment by mwittrien** [comment]
Already fixed in 3.4.0
