### ISSUE TITLE
[BUG] - SettingsIcons

### ISSUE THREAD

**Issue by SJ-Tom** [mwittrien/BetterDiscordAddons#2600]
**Describe the bug**
The images are not displaying anymore because the GitHub Page is down

**To Reproduce**
Some weeks ago on GitHub pages

**Expected behavior**
Icons appear as before

**Discord Build (stable, ptb or canary):**
every build and version because external

**Comment by mwittrien** [comment]
It's not down?

**Comment by SJ-Tom** [comment]
But it's showing me 404 error

**Comment by mwittrien** [comment]
https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/svgs/settingsicons/questionmark.png

**Comment by SJ-Tom** [comment]
Oh I have a .svg link has this changed in the past

**Comment by mwittrien** [comment]
yeah i changed them
