### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by SeongGyu1216** [mwittrien/BetterDiscordAddons#2601]
**Describe the solution you'd like**
I'd also like to add a notification sound that occurs when I activate the same channel message notification.

**Describe alternatives you've considered**
Maybe I didn't find it in that plug-in, but I'd like you to let me know if there's a way

**Additional context**
![translated_image_en](https://github.com/mwittrien/BetterDiscordAddons/assets/124080614/70bdd872-ea9f-432b-8f9d-5e7e4864e8be)

**Comment by drewthechatter** [comment]
this plugin has a virus
luckily i have a antiti-virus that uninstalled it so dont install this i downloaded it from betterdiscord plugins 
so please dont install.
