### ISSUE TITLE
[BUG] - ServerFolders not working

### ISSUE THREAD

**Issue by re11ding** [mwittrien/BetterDiscordAddons#2605]
**Describe the bug**
Likely due to a discord update, opening folders with BDFDB and ServerFolders active will cause a massive lag spike and then eventually open a new bar (if an existing folder isn't already opened) and no servers will be inside.

**To Reproduce**
This bug occurs any time when opening a folder of servers in Discord. Does not matter if a folder is already open or not.

**Expected behavior**
It should be opening the list of folders in the second bar without the lagspike.

**Screenshots**
![Capture5](https://github.com/mwittrien/BetterDiscordAddons/assets/69743944/7ce6d2be-cbe3-4e05-8990-090cace728cf)

**Discord Build (stable, ptb or canary):**
Stable 257867

**Additional context**
I have deleted all plugins except BDFDB and ServerFolders. I also deleted all files related to BDFDB and let them recreate. I additionally deleted the config setting for ServerFolders. None of these managed to resolve the problem.

**Comment by Saloframes** [comment]
Temporary fix:
Replace line 224 in 0BDFDB.data.json in your local plugins folder with the following:
`"GuildItem": {"strings": ["guildNode:", "useShouldShowInvitesDisabledNotif"]},`

Looks like the "clearGuildBurstPreview" variable was removed in the latest version of Discord.
