### ISSUE TITLE
[BUG] - PLUGIN/ServerFolders

### ISSUE THREAD

**Issue by n1c3c0d3** [mwittrien/BetterDiscordAddons#2608]
**Describe the bug**
When using the second column feature, all icons appear blank with only the default grey background color showing.

**To Reproduce**
Occurs when trying to open any folder.

**Expected behavior**
Should be showing the icons of servers, was working previously.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/23188653/b2c5d814-2072-4e6f-a226-e65d332284a5)

**Discord Build (stable, ptb or canary):**
Latest Build, Stable

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload
