### ISSUE TITLE
[Feature Request] Clickable scroll bar in server folders.

### ISSUE THREAD

**Issue by Kederan** [mwittrien/BetterDiscordAddons#261]
**Describe the feature you'd like.**

My suggestion is that you add an option in the ServerFolders settings to add a clickable scroll bar in server folders.

![2019-09-02_22-49-07](https://user-images.githubusercontent.com/19885815/64141448-0a3d5d80-cdd6-11e9-9a13-ac02c3064899.gif)

**Comment by mwittrien** [comment]
This can easily be done with custom css and is not part of the plugin itself, if people want a clickable scroller i nthe serverlist then they should look up the css that achieves it
