### ISSUE TITLE
[BUG] - EditUsers throws warnings and errors

### ISSUE THREAD

**Issue by yani** [mwittrien/BetterDiscordAddons#2612]
EditUsers makes my whole Discord extremely slow, almost unusable. Looking at the log shows thousands of these warnings and errors:

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/6956790/9e6101be-d632-431e-8191-6aaf3c87893a)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/6956790/031a5dc6-322b-4562-8356-271ab546453b)

I enabled and disabled plugins until I figured out it was EditUsers.

**Comment by EvanCarroll** [comment]
Let's all thumbs up the top post rather than "me-tooing" without additional information. I'm sure it'll get fixed.
