### ISSUE TITLE
[BUG] - PersonalPins "React Component Error"

### ISSUE THREAD

**Issue by SoggyBurritoVR** [mwittrien/BetterDiscordAddons#2613]
Bug: Getting "React Component Error" when trying to view personal pins.  

Reproduce: Click the "Notes/Personal Pings UI Icon.

Expected: Display Personal Pins

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/69495940/0bac2561-2191-47f1-8266-08c0550d54fe)

Discord Build: Stable 260101 (e220e75)

**Comment by QuentinMcCarthy** [comment]
+1 on this, hoping it was just a fluke, noticed it yesterday. Discord Stable 260101 (e220e75)

Quite bothersome.
