### ISSUE TITLE
[BUG] - SpotifyControls doesn't display current song in Status if it's not from Liked playlist

### ISSUE THREAD

**Issue by kastentop2005** [mwittrien/BetterDiscordAddons#2614]
**Describe the bug**
If I play a song from my liked songs playlist - it's fine. If I listen to some song outside of it - player is still displaying the previous one and even the status is not being updated (but controls still work)

**To Reproduce**
Play a song not from liked playlist

**Expected behavior**
Current song in status

**Screenshots**
![Screenshot 2024-01-20 124601](https://github.com/mwittrien/BetterDiscordAddons/assets/98401886/45271978-4bfc-4e88-ac29-124224d86a8c)
![Screenshot 2024-01-20 124608](https://github.com/mwittrien/BetterDiscordAddons/assets/98401886/3c97df93-5631-429d-a38d-71b681718b0a)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
No

**Comment by mwittrien** [comment]
Is it a local file? Local files cant be displayed via the plugin

**Comment by kastentop2005** [comment]
> Is it a local file? Local files cant be displayed via the plugin

No

**Comment by mwittrien** [comment]
If the status isnt being updated either then its an issue with Discord the plugin simply displays the data which discord has
