### ISSUE TITLE
[BUG] - Edit Users

### ISSUE THREAD

**Issue by ZmaZes** [mwittrien/BetterDiscordAddons#2616]
**Describe the bug**
Switching channels can cause Discord to hang for 5-6 seconds, and the plugin just overall slows down Discord greatly. The time it hangs for seems to be directly related to how many users are in the selected channel, meaning the DMs tab hangs for an especially long time.

**To Reproduce**
Enable the plugin, and close settings. After closing the settings page there will be a very long wait due to the plugin... doing something. Then every time you switch channels or DMs, discord will hang for a few seconds, presumably to change the profiles of all of the users.

**Expected behavior**

**Discord Build (stable, ptb or canary):**
Using the stable build.

**Additional Context**
I use this plugin to overwrite custom nicknames in servers to just show the friend nicknames instead. This results in me having a nickname for basically everyone in my friends list. I don't know if this is related to my computer specifically, or if there is some RAM allocation issue with Discord. I'm kind of just looking for help solving this, because I would assume that this is not an intentional behavior.

**Comment by Auron-FFX** [comment]
the plugin in question is editusers I believe. they supposedly fixed the issue earlier but I don't see such a change in the commits.

**Comment by ZmaZes** [comment]
Sorry, I didn't realize the preset title was supposed to be edited. I fixed it now. In general GitHub always confuses me.
Replacing the library does seem to have fixed the issue. Thanks for your help :)

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord
