### ISSUE TITLE
[BUG] - ClickableMentions

### ISSUE THREAD

**Issue by RickGotTaken** [mwittrien/BetterDiscordAddons#2620]
**Describe the bug**
I can hover over the mentions, but clicking just flashes them like a phone camera.

**To Reproduce**
Click on a mention.

**Expected behavior**
Clicking on the mention to open the profile of the user in the mention.

**Screenshots**
A video would be better, but by human nature I'm lazy and don't want to open OBS.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
~~It's a pretty simple bug, not much context needed. (Might not be simple to fix, but it's the core functionality so it's pretty important.)~~
It seems to work when I click the mention in the send message box, but not in actual messages. (Maybe it's because I'm using InvisibleTyping?)

**Comment by mwittrien** [comment]
The whole point of the plugin is to make mentions in the send message box clickable, mentions not being clickable in messages in the chatwindow is an issue with another one of you plugins
