### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by SadMastiff** [mwittrien/BetterDiscordAddons#2621]
A toggleable option to put the original message as a spoiler when sending a translated message. 
----------------------------------------------
Example: 
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/29665139/d6f4d712-db64-4e1c-afaf-588362b31c17)
----------------------------------------------

**Comment by mwittrien** [comment]
added in the plugin settings
