### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by SeongGyu1216** [mwittrien/BetterDiscordAddons#2622]
**Describe the solution you'd like**
Right-click - I'd like to see a pop-up translation when you hover over the cursor, not during the translation process, like in 2.58?

**Describe alternatives you've considered**
This brings back functionality that was present in version 2.58.

**Additional context**
In 2.58, it was only possible to translate via popup and right-click-translate didn't work, but I would like to have both. (I would like to be able to enable or disable it with an on off function).

**Comment by mwittrien** [comment]
No clue what you are talking about

**Comment by SeongGyu1216** [comment]
> No clue what you are talking about

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/124080614/4974769d-5bfa-4418-b013-6cef3bf1cf8a)


Can you add the above functionality?

**Comment by mwittrien** [comment]
This isn't implemented
