### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor

### ISSUE THREAD

**Issue by rejedai** [mwittrien/BetterDiscordAddons#2626]
**Describe the solution you'd like**
Ability to change font size

**Additional context**
At the moment, when I set the Inter font, the font looks too large and bold. I would like to be able to adjust this.

gg-sans:
![Screenshot_2024_01_28_13_18_04](https://github.com/mwittrien/BetterDiscordAddons/assets/92713267/6c9df601-7b71-4a30-92e7-c431dd72d4b7)

Inter:
![Screenshot_2024_01_28_13_19_00](https://github.com/mwittrien/BetterDiscordAddons/assets/92713267/b3b2e9f3-3ff0-45c0-9ad9-070d0379d595)

**Comment by mwittrien** [comment]
Change it in Discords appearance settings

**Comment by rejedai** [comment]
> Change it in Discords appearance settings

Discord appereance only affects the font size in messages. Already tried it. Besides, it doesn't allow to change the font thickness.
![Screenshot_2024_01_28_14_25_54](https://github.com/mwittrien/BetterDiscordAddons/assets/92713267/a3d686c3-50c9-47ce-a7cc-3c938a21097f)
