### ISSUE TITLE
[BUG] - MessageUtilities shows emoji menu

### ISSUE THREAD

**Issue by rikusen0335** [mwittrien/BetterDiscordAddons#2630]
**Describe the bug**
When MessageUtilities enabled, after a bit time of reloading, emoji menu shows up even I didn't anything

**To Reproduce**
Not sure but using v1.9.8 of MessageUtilities 

**Expected behavior**
emoji menu not shows up

**Screenshots**
Discord is bugged, curerntly I can't put gifs

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
_Nothing_

**Comment by mwittrien** [comment]
Most likely a wrong setup with your keybinds in the plugin settings
