### ISSUE TITLE
[BUG] - NotificationSounds, Message notifications don't play in your current channel.

### ISSUE THREAD

**Issue by TeddyBearKilla** [mwittrien/BetterDiscordAddons#2631]
**Describe the bug**
If current channel notifications are off on discord I get no notifications for normal messages in the channel I'm in. If I toggle on same channel notifications then set a sound in NotificationSounds then turn it off it still doesn't play sounds for the channel I'm in. I know same channel notifications has to be on for the sound to play in the channel I am in with whatever specific sound I set but I want sounds for all messages anywhere I have notifications enabled.

**To Reproduce**
Run the latest plugin update 3.9.2 (3.8.8 also did this), have notification sounds set for messages and get a message in the channel you are in. You get the message popup on the system with no audio.

**Expected behavior**
Play the notification sound I have set for Messages wherever I receive messages.

**Discord Build: Stable**

**Additional context**
I thought it would be an issue with it just not having audio selected for current channel notifications in the backend or something but it still plays no audio for my current channel. I could also just put the same sound on for Messages & Messages (Current Channel), but then it plays the notification even if I'm on a server with muted notifications (Server notification settings: Nothing & also muted serverwide)

**Comment by TeddyBearKilla** [comment]
Also, I have a backup of the NotificationSounds.plugin.js from in November and I can use that until it's resolved.
On it, since there's no setting for Current Channel notifications it defaults to the stock discord sound but it is effected by the global sound level. With the new update it just deletes all sound from the Current Channel.

**Comment by mwittrien** [comment]
Enable same channel notifications in discords native notification settings
