### ISSUE TITLE
NotificationSounds, Message notifications don't play in your current channel.

### ISSUE THREAD

**Issue by TeddyBearKilla** [mwittrien/BetterDiscordAddons#2632]
Enable same channel notifications in discords native notification settings

_Originally posted by @mwittrien in https://github.com/mwittrien/BetterDiscordAddons/issues/2631#issuecomment-1923446566_
            
That's not the issue. 
I want Messages notifications everywhere I have message notifications on. 
If I turn on Same Channel notifications it should prioritize that sound or audio level and not play the Messages sound for the current channel, instead it is completely silent for the channel I am on if I don't turn on Same Channel notifications.

**Comment by mwittrien** [comment]
Discord does not play notification sounds for the currently opened channel

**Comment by mwittrien** [comment]
Yes it used to and that was incorrect

It now behaves the same as native discord without the plugin
