### ISSUE TITLE
[BUG] - SpotifyControls

### ISSUE THREAD

**Issue by VedatAlpGoktepe** [mwittrien/BetterDiscordAddons#2633]
**Describe the bug**
When Spotify is closed the Spotify Controls bar does not disappear and continues staying on discord until spotify is reopened.

**To Reproduce**
Open Spotify and play a song, then quit Spotify.

**Expected behavior**
The Spotify Controls bar should still be on Discord and pressing the controls will give an error.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/77364512/7ce1dbe0-6555-4582-b9d8-a8955c36d85b)
No Spotify open
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/77364512/1ea14539-c4fa-43b5-872c-b219296adb85)

**Discord Build (stable, ptb or canary):**
Discord Stable

**Additional context**
No additional context.

**Comment by mwittrien** [comment]
Yes and? What do you want the plugin to do instead
