### ISSUE TITLE
[BUGs] - SplitLargeMessages

### ISSUE THREAD

**Issue by SpoogLord** [mwittrien/BetterDiscordAddons#2634]
The "Try to split Messages on Newlines instead of Spaces" setting doesn't seem to work, or at least not very well

When sending a 3k character message to a friend I noticed it the plugin split the message in a very awkward spot. I'm not comfortable sharing the contents of the message but it was basically 20 characters after a new line instead of on the new line, after trying it again with a different message to test, it seems to consistently not split on new lines

I would expect it to find the last new line before the character count hits 2k, then split the message there instead of at a space, like the name of the setting implies

Second bug (bc I found it while testing the first one)
Setting the number for "Maximum number of split pages" to zero does not make it infinite as the window says, it simply prevents the sending of all messages over 2k characters with no popup. 
The box to input the number for "Maximum number of split pages" also seems to copy the other box upon opening the settings menu for the plugin (arguable 3rd bug in one report)

Up to date Discord on stable branch (wish I knew how to give a version number)
Better Discord 1.9.7
SplitLargeMessages 1.8.1
Windows 10 Pro

**Comment by SpoogLord** [comment]
I would like to dispute this, setting the number for "Maximum number of split pages" to zero still does not make it infinite, and still prevents the sending of all messages over 2k characters with no popup.

**Comment by SpoogLord** [comment]
The other things are fixed tho, so kudos

**Comment by mwittrien** [comment]
> I would like to dispute this, setting the number for "Maximum number of split pages" to zero still does not make it infinite, and still prevents the sending of all messages over 2k characters with no popup.

Hmm i tested and it works fine for me
