### ISSUE TITLE
Change translation source location

### ISSUE THREAD

**Issue by Whbgz** [mwittrien/BetterDiscordAddons#2636]
May I ask where to change the translation source? I couldn't find this setting in the plugin settings

![图片](https://github.com/mwittrien/BetterDiscordAddons/assets/123636481/6929d2ce-984a-44a5-9b53-83bd9be10b7c)
![图片](https://github.com/mwittrien/BetterDiscordAddons/assets/123636481/1ff85786-51c9-47f7-9d4c-810391ebe70d)

May I take a screenshot to demonstrate? I've been searching for a long time but couldn't find it. I'm very sorry 😭

**Comment by mwittrien** [comment]
Left click the icon in the message input area
