### ISSUE TITLE
[BUG] - CompleteTimestamps / `$agoDate` doesn't show anything for future timestamps

### ISSUE THREAD

**Issue by lumynou5** [mwittrien/BetterDiscordAddons#2638]
**Describe the bug**
`$agoDate` doesn't show anything for future timestamps.

**To Reproduce**
1. Set the timestamp format to something using `$agoDate`, e.g. `$agoDate $time`.
2. Send a message with a timestamp which has a time in the future, e.g. `<t:1735660800>`.
3. See the timestamp missing date.

**Expected behavior**
Show dates for timestamps, and will be nice to show "tomorrow" for timestamps of tomorrow.

**Screenshots**
![screenshot](https://github.com/mwittrien/BetterDiscordAddons/assets/84374077/ece8216e-2b36-4f1c-8d13-8a7a0f42bd61)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Redownload BDFDB plugin
