### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor ability to change the color of message selection (Tab + Arrow)

### ISSUE THREAD

**Issue by s-liwka** [mwittrien/BetterDiscordAddons#2639]
This blue color

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/116428267/8e9f8875-744c-4dfa-8b1c-e088d99e999f)

**Comment by mwittrien** [comment]
add 
`--focuscolor: 255, 0, 0;`
into the css
