### ISSUE TITLE
[BUG] (ServerColumns) 2-column-config doesn't work

### ISSUE THREAD

**Issue by Marcus5408** [mwittrien/BetterDiscordAddons#2642]
**Describe the bug**
Setting `--columns: 2` shows up as only one column of servers when applied.

**To Reproduce**
1. Set `--columns` as `2`
2. Save/ apply changes

**Expected behavior**
Two columns of servers show.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/46655509/22c045fc-e5c8-41da-b51a-0b58bdc7321a)

**Discord Build (stable, ptb or canary):**
Stable 264913 (ae72f64)

**Additional Context**
Issue seems to only occur when `--columns` is set to `2`.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/46655509/d5c6a0c5-7e0e-4f66-9663-bc2c7285c0b1)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/46655509/1cccc510-a26d-46f1-91b9-715c23f2d619)

**Comment by mwittrien** [comment]
Works fine for me, issue seems to be  your other theme, which theme are you using

**Comment by Marcus5408** [comment]
I'm using [Dark Matter](https://betterdiscord.app/theme/Dark%20Matter)
