### ISSUE TITLE
[IMPROVEMENT] - EditUsers

### ISSUE THREAD

**Issue by IlyaSr07** [mwittrien/BetterDiscordAddons#2643]
**Describe the solution you'd like**
I think there should be an option to choose whether the Plugin overrides Discord's friend nicknames or not.
For example if I edit "Person A" to be "Person B" through the plugin, and give them the friend nickname "Person C", they will be displayed as "Person B" in servers and as "Person C" in DMs.

**Comment by IlyaSr07** [comment]
Edit: I meant override only the text. For example, when I edit "Person A" into "Person B" with a green name color, in DMs they'd appear as "Person C" with the same green name color.

**Comment by mwittrien** [comment]
Don't add a friend nickname if you don't wanna see it?
