### ISSUE TITLE
[*FIXED* BUG] CompleteTimestamps - Timestamps Disappear

### ISSUE THREAD

**Issue by Catzrule5** [mwittrien/BetterDiscordAddons#2644]
**Describe the bug**
Ever since downloading Discord v1.0.9033 x86, the CompleteTimestamps plugin now makes the timestamps disappear.

**To Reproduce**
This occurs everywhere -- servers, group chats, DMs.

**Expected behavior**
Timestamps shown in desired format.

**Screenshots**
https://github.com/mwittrien/BetterDiscordAddons/assets/41124086/e74a0791-cd07-4663-9ad3-2287186d8869

**Discord Build (stable, ptb or canary):**
Discord v1.0.9033 x86; Stable.

**Comment by HoltzFan10** [comment]
yeah, this has been happening to me too
