### ISSUE TITLE
[BUG] - ImageUtilities zoom not working

### ISSUE THREAD

**Issue by ScrubN** [mwittrien/BetterDiscordAddons#2646]
**Describe the bug**
When zooming on an image in the image popup, the zoomed version of the image is not present

**To Reproduce**
- Click an embedded image in chat to open the image popup
- Click the image modal to zoom
- Observe the zoom lens appearing, but the image 

**Expected behavior**
A zoomed-in version of the image is present inside the zoom lens.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/72096833/bea456d7-ae27-415e-86cf-b0353ea89f8c)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
- I live in a country that seems to get discord experiments at a higher rate than others. If the issue cannot be reproduced, that may be why.
- I have tried restarting discord several times

**Comment by Pauweltje** [comment]
Hi Yes, I use the zoom 10000000x times a day, and it is not working anymore! Boeheheheheoeoeeeooeoeeoe...please fix! Love the plugin!
