### ISSUE TITLE
[IMPROVEMENT] - EmojiReplace

### ISSUE THREAD

**Issue by CreepsoOff** [mwittrien/BetterDiscordAddons#2647]
**Describe the solution you'd like**
Hello! Is it possible to update it so emojis of Unicode 15.1 works as in Apple ones doesn't work.

**Describe alternatives you've considered**
None - I've searched over Github and Reddit but no solution was found.

**Additional context**
Rendering like this rn:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/51055703/cf21cb75-442a-402a-a30d-26d7a0920d17)
Should look like this:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/51055703/12cdb1cb-6e5a-42f4-8f51-06898f902383)

Thanks in advance.

**Comment by mwittrien** [comment]
Discord doesnt support unicode 15.1 yet does it?
