### ISSUE TITLE
Reverse Image Search dosnt work properly

### ISSUE THREAD

**Issue by claire-rouge** [mwittrien/BetterDiscordAddons#265]
the plugin option is there but when clicking saucenao or google it wont open/search the img in browser, nothing happens.
The reason may be since they updated how right click looks?
![bilde](https://user-images.githubusercontent.com/15875197/64572996-e2b43b00-d369-11e9-840a-80cab9f4712e.png)
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReverseImageSearch

**Comment by mwittrien** [comment]
I am aware, wait till the update....
