### ISSUE TITLE
[BUG] - ServerColumns Theme not working anymore

### ISSUE THREAD

**Issue by BluTree** [mwittrien/BetterDiscordAddons#2650]
**Describe the bug**
With the latest Discord update, the ServerColumnsTheme seems to not work.

**To Reproduce**
Enable the theme with a custom number of columns and notice it doesn't work

**Expected behavior**
It should work as intended

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/11920536/d60c656d-3579-41f7-846c-59ca3f9c9a04)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/11920536/ad9401be-8c24-48c4-9d4d-7d6d2e957a5e)

**Discord Build (stable, ptb or canary):**
stable 271015 (1b072b3) Host 1.0.9034 x86 (44142) Windows 11 64-bit (10.0.22631)

**Comment by sruPL** [comment]
The issue appeared again on latest version of Discord:

```md
## Discord Info
stable 279382 (5c40119)

## BetterDiscord
stable 1.10.1
```
