### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by SeongGyu1216** [mwittrien/BetterDiscordAddons#2651]
**Describe the solution you'd like**
Add 2 shortcuts to the translation function of the selected word or sentence!

**Describe alternatives you've considered**
If you press the shortcut on the keyboard and click! or drag the message, I hope it will be translated easily.

Shortcuts + Drag translate selected words or sentences
Shortcut + Message Click to translate the message

**Additional context**
If there are multiple sentences or messages, I think it's cumbersome to right click - translate one by one.
Of course, I'm using it more conveniently than I don't have, but I think it would be good to have the same convenience function as above

**Comment by mwittrien** [comment]
Use the MessageUtilities plugin to add a shortcut

**Comment by wmkai** [comment]
Wish there was a way to automatically translate all incoming messages
