### ISSUE TITLE
[BUG] - No notification sound while discord is focused

### ISSUE THREAD

**Issue by matterpie** [mwittrien/BetterDiscordAddons#2654]
**Describe the bug**
Whenever discord is focused, no notification sounds play. For example, i set a custom message sound, and it plays whenever im focused on a game or other window, but if i have discord focused and Im in another dm or in a server chatroom, the sound does not play

**Expected behavior**
I expected the sound to play like normal discord would have it.

**Discord Build (stable, ptb or canary):**
Whatever the most recent one is

**Comment by mwittrien** [comment]
Sounds never play in a focused chat in Discord

**Comment by matterpie** [comment]
@mwittrien Please re-read the issue. Obviously they don't playing a focused chat. But if I'm in one dm, and someone else messages me, the toast pops up but no sound plays.
