### ISSUE TITLE
How do I add downloaded BD plugins onto Vencord?

### ISSUE THREAD

**Issue by T4M1L0S** [mwittrien/BetterDiscordAddons#2659]
Hello, I downloaded some of your BD plugins on https://mwittrien.github.io/ but I don't know how to add them onto Vencord.

Also I'm on Chromebook (ChromeOS) so I use Vencord as an Extension for Chrome.

And I can't find anything or a button that I can click on to add BD plugins.

Thanks in advance for your help!

**Comment by T4M1L0S** [comment]
(Not a bug (I think) so I don't know why the bug label would be added)

**Comment by mwittrien** [comment]
Ask on the vencord Server
