### ISSUE TITLE
[BUG] - DiscordRecolor - Theme

### ISSUE THREAD

**Issue by ichi-obi** [mwittrien/BetterDiscordAddons#2666]
**Describe the bug**
After recent Discord update theres a 0 or an O in top-left corner of the app.

**To Reproduce**
Just turn on the theme.

**Expected behavior**
It should not be there.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/92340186/8286fe2d-e297-4865-ab19-28351466225a)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None

**Comment by mwittrien** [comment]
Caused by BD and no the theme
