### ISSUE TITLE
[IMPROVEMENT] - Server Folders

### ISSUE THREAD

**Issue by Quaantt** [mwittrien/BetterDiscordAddons#2668]
I suggest the background for an open server folder be customizable and/or set to the folder color itself.

Hope that's not just a duplicate request. I just discovered BD and I'm super pumped about all your plugins!

**Comment by Quaantt** [comment]
The background referred to by the setting "Adds a folder background behind a group of servers in the extra column."

**Comment by mwittrien** [comment]
Its set to the folder color

**Comment by Quaantt** [comment]
Hmm perhaps something isn't working, then. While using the default theme, the background is grey. I noticed another plugin called PrettyFolders also doesn't work in this regard.
