### ISSUE TITLE
[IMPROVEMENT] - SettingsModal

### ISSUE THREAD

**Issue by cbogolin** [mwittrien/BetterDiscordAddons#2673]
**Describe the solution you'd like**
include an override to account for themes that cancels any animations for the settings close button. (theme example: midnight)

**Additional context**
Noticed that for whatever reason, clicking outside of the modal to close it was acting inconsistently. Did a bit of debugging (made local copy of `SettingsModal.css` and changed background colors) and then saw that it was due to the "close button" in the background playing its animation before allowing it to be clicked on. Going into the Theme's css and commenting out these 2 properties that had some tranforms/transitions being done to them made it work 100% of the time.
 
`.closeButton__8177f /* settings exit button `
`.closeButton__8177f:hover, `

**Comment by mwittrien** [comment]
added
