### ISSUE TITLE
[BUG] - IMAGEUTILITIES: Image cutting off

### ISSUE THREAD

**Issue by movieslol** [mwittrien/BetterDiscordAddons#2679]
**Describe the bug**
When previewing images in channels with the ImageUtilities plugin on, about 1/6th of the image cuts off. This seems to only happen with the "Show Image Details in the Image Description" setting on.

**To Reproduce**
When does the bug occur.
1. Install ImageUtilities
2. Have "Show Image Details in the Image Description" setting on
3. Go in a channel and preview image
Bug replicated.

**Expected behavior**
The image to not cut off.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/144293482/44ca6869-730d-42c5-a391-201c8b43329a)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
[plugins.json](https://github.com/mwittrien/BetterDiscordAddons/files/15018018/plugins.json)

**Comment by Leah96xxx** [comment]
Can confirm I also have this issue. Can't see anything in the console that could be related
