### ISSUE TITLE
[BadgesEverywhere] Discord Theme Update - Badges on user column

### ISSUE THREAD

**Issue by celiken** [mwittrien/BetterDiscordAddons#268]
With the latest discord light theme update, the badges on user column disappears.
Seems like some badges on "Current Nitro Guild Boost" are missing, or that they are a space between them (don't really remember how it was before as I didn't touch to settings).
![image](https://user-images.githubusercontent.com/9248358/64596433-30559580-d3b4-11e9-9ca2-73241bf31d36.png)
![image](https://user-images.githubusercontent.com/9248358/64596468-3d728480-d3b4-11e9-980a-8bd7a5dbda04.png)

**Comment by mwittrien** [comment]
I am aware, wait till the update....
