### ISSUE TITLE
Error Could not initiate BDFDB Library Plugin. Check your Internet Connection and make sure GitHub isn't blocked by your Network or try disabling your VPN/Proxy.

### ISSUE THREAD

**Issue by MSmo0n** [mwittrien/BetterDiscordAddons#2681]
how to solve this error? I tried reinstalling the discord and the better discord did not help, I do not use vpn
![2024-04-20_18-31-56](https://github.com/mwittrien/BetterDiscordAddons/assets/164044381/1c24c05f-0a49-4e75-8cff-68d5b6ea007d)

**Comment by mwittrien** [comment]
delete 0BDFDB.data.json in your plugins folder and reload discord
