### ISSUE TITLE
[BUG?] - ImageUtilities Resizing Bug

### ISSUE THREAD

**Issue by EaglePPP** [mwittrien/BetterDiscordAddons#2682]
**Describe the bug**
Using resizing causes partial image, no matter using "origial size" or "window size"

The width of the resized img is as wide as the width before using this plugin.(the original img discord shows)

When I use maximized window it shows merely 2/5 width of the img(resolution 1920*1080),
but if I make the window smaller, it shows more(but still not all)...

**To Reproduce**
I dont know how, all of my pics look like this one day week ago.

**Expected behavior**
picture looks whole in chat message.

**Screenshots**
so the pic look like this as a whole(4K img)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/19349338/6ce093a8-39e0-42e2-b51a-005595164e86)

but since some day of last week or the week before, it suddenly look like this. I did not mess with any other settings before this happens.(only set resizing to original size for message)
All I want is picture looks whole in chat window
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/19349338/1a263729-2f6a-4975-9532-684196fc1907)

**Discord Build (stable, ptb or canary):**
~~stable 286349~~

```md
## Discord Info
stable 286654 (b3db605) Host 1.0.9142 x64 (46947) Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.1

### Plugins (2 Enabled):
- BDFDB (Enabled)
- ImageUtilities (Enabled)

### Themes (0 Enabled):

```
**Additional context**
I have tried: 
reinstalling Discord(stable), didnt help.
Using Discord PTB, didnt help.
reinstalling the plugins and the BetterDiscord, didnt help.
using last version of plugins and libs, didnt help.
clearing the plugin folder, didnt help.

Idk if this matters, its in the debug.log
`[2024-04-23 13:12:09.177][CONSOLE:WARN] Unable to determine render window for element {"location":{"ancestorOrigins":{},"href":"https://discord.com/channels/xxx/xxx","origin":"https://discord.com","protocol":"https:","host":"discord.com","hostname":"discord.com","port":"","pathname":"/channels/xxx/xxx","search":"","hash":""},
[2024-04-23 13:24:47.089][CONSOLE:WARN] [BDFDB] (v3.6.4) mediaAttachmentsContainer not found in ImageMosaic in DiscordClassModules`

If you need more infos please let me know.

**Comment by mwittrien** [comment]
fixed by reloading
