### ISSUE TITLE
[BUG] - ImageUtils restarts gifs from the start when your mouse goes outside of it's borders

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#2683]
**Describe the bug**
when your mouse is hovering over a gif, and you move it outside of the border of the gif, the gif restarts

**To Reproduce**
1. hover mouse over a gif
2. move mouse outside of the border of the gif
3. the gif restarts

**Expected behavior**
the gif does not restart when you move your mouse outside of the border of the gif

**Screenshots**
https://github.com/mwittrien/BetterDiscordAddons/assets/48365199/e11068b8-8d56-43e5-af75-91fab2d6086b

**Discord Build (stable, ptb or canary):**
```md
## Discord Info
stable 288065 (2e640e8) Host 1.0.9143 x64 (46952) Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.1
```

**Comment by mwittrien** [comment]
Sadly can't be fixed
