### ISSUE TITLE
[BUG] - PersonalPins

### ISSUE THREAD

**Issue by rasuy** [mwittrien/BetterDiscordAddons#2684]
**Describe the bug**
Whenever I click on the notes button my Discord Crashes. I've already installed BDFDB and it still happens.

**To Reproduce**
For me today, but there are people who already reported yesterday on the Better Discord server.
Report Link: https://ptb.discord.com/channels/86004744966914048/1233701246767071264/1233701246767071264
![imagem_2024-04-28_023638032](https://github.com/mwittrien/BetterDiscordAddons/assets/154269995/a1204c68-2615-441c-8935-9825d09f4949)

**Expected behavior**
It should open the notes menu.

**Screenshots**
![imagem_2024-04-28_023446458](https://github.com/mwittrien/BetterDiscordAddons/assets/154269995/4378a5d3-7380-4c89-8529-32d70728b62a)

**Discord Build (stable, ptb or canary):**
Version PTB

**Comment by mwittrien** [comment]
fixed
