### ISSUE TITLE
[BUG] - ShowBadgesInChat not working properly in one specific server

### ISSUE THREAD

**Issue by andrwmai** [mwittrien/BetterDiscordAddons#2685]
**Describe the bug**
Per title, the badges aren't showing for my profile in the members sidebar in one specific server. I notice that this is the only server where I use a different profile (avatar, banner, name). Badges still showed in this server before so I'm assuming this is a bug.

**To Reproduce**
Not sure. I guess maybe try using a different server profile for any server.

**Expected behavior**
Badges still show everywhere in the server. They still show up in the chat but not in the members sidebar.

**Screenshots**
![CleanShot 2024-04-29 at 11  41 29@2x](https://github.com/mwittrien/BetterDiscordAddons/assets/48293860/be3924d1-1a91-472e-9fff-2f5fd27b4d4b)

**Discord Build (stable, ptb or canary):**
Stable 288460 (c8280c6)

**Additional context**

**Comment by mwittrien** [comment]
Saldy can't reproduce this
