### ISSUE TITLE
[MessageUtilities] No Longer Functions After Update

### ISSUE THREAD

**Issue by McCovican** [mwittrien/BetterDiscordAddons#269]
Howdy,

Seems that MessageUtilities straight-up doesn't work anymore after the most recent stable update to Discord (Changelog dated 9th Sept 2019). No obvious errors, nor is it causing issues with anything else. It just doesn't *do* anything anymore. BandagedBD, Win7x64.

**Comment by mwittrien** [comment]
I am aware, wait till the update....
