### ISSUE TITLE
[BUG] - RemoveBlockedUsers v1.6.8, user profiles fail to load

### ISSUE THREAD

**Issue by Prometheus3375** [mwittrien/BetterDiscordAddons#2690]
**Describe the bug**
When plugin is disabled, upon clicking a user their profile is loading with no issues and does not disappear when I move my cursor.
When plugin is enabled, upon clicking a user their profile sometimes does not load or loads to disappear once I move my cursor. It takes several clocks from me to view profile.

I do not use any other plugin or custom CSS. Just this one and a required library, BDFDB v3.6.5.

**To Reproduce**
1. Enable plugin with its default settings.
2. Block a bunch of people.
3. Start clicking on users inside voice channels.

**Expected behavior**
No issues with profile loading. If load takes too long, then I should see loading animation.

**Screenshots**

https://github.com/mwittrien/BetterDiscordAddons/assets/35541026/3a8d2709-5747-42e9-befa-b1b7ffb09c29

**Discord Build:**
Stable.

**Comment by fuckawuefguueag** [comment]
Is this ever gonna get fixed? It's been like that for months already.
