### ISSUE TITLE
[BUG] - Translator Plugin causing Discord crash

### ISSUE THREAD

**Issue by zzinggame** [mwittrien/BetterDiscordAddons#2691]
**Describe the bug**
Translator plugin causing Discord crash immediately after the Translator plugin loaded

**Expected behavior**
Discord open normally

**Discord Build (stable, ptb or canary):**
Stable

**Comment by WlSDXM** [comment]
same here

**Comment by AlphaDoug** [comment]
same here

**Comment by chaixshot** [comment]
same same

**Comment by heartdeadz** [comment]
yup, same here.

**Comment by Emanon01001** [comment]
yes, same here.

**Comment by xmevik** [comment]
In the console, it looks like this.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/92307558/5c91670b-874f-4866-9808-546f4fc52089)

**Comment by GIGABAIT93** [comment]
I have the same

**Comment by Ghostoptimal** [comment]
the same

**Comment by NyteWL** [comment]
same here

**Comment by yellowteaegg** [comment]
same here

**Comment by FunnyWay1985** [comment]
the same, but when I open DM

**Comment by DenarQ2** [comment]
same here

**Comment by Warryor3D** [comment]
I thought it was my app, I deleted it completely and reinstall and the error persists, I even posted the problem to Discord, I hope they can solve this problem soon.

**Comment by NyteWL** [comment]
After updated BDFDB, it don't crash anymore. I think it has been fixed.
