### ISSUE TITLE
[BUG] - FriendNotifications and other BDFDB plugins not working on DiscordPTB

### ISSUE THREAD

**Issue by mocha156** [mwittrien/BetterDiscordAddons#2692]
FriendNotifications plugin not working with DiscordPTB. im pretty sure this is a BDFDB problem at its core since other plugins that dont rely on it work. but just pointing it out.
ive tried to uninstall and reinstall both DiscordPTB and BetterDiscord but still get the same issues. happened after i clicked the green update button in the top right. i will attach console logs if that helps with anything
![image_2024-05-22_220413066](https://github.com/mwittrien/BetterDiscordAddons/assets/170589903/b057776b-ddc8-443e-ac3a-e60336614791)

**Comment by corvus2606** [comment]
I'm getting the same for any BDFDB related stuff too on 
```md
## Discord Info
stable 295694 (ffb1a11) Host 1.0.9147 x64 (48018) Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.1

### Plugins (6 Enabled):
- BDFDB (Enabled)
- BetterChatNames (Enabled)
- PluginRepo (Enabled)
- ReadAllNotificationsButton (Enabled)
- SpellCheck (Enabled)
- ThemeRepo (Enabled)

### Themes (1 Enabled):
- BasicBackground (Enabled)
- DiscordRecolor
```

**Comment by corvus2606** [comment]
DBFDB updated to v3.6.6 this morning and the error is no longer happening for me.
