### ISSUE TITLE
[Request a new Plugin] - Full Screen &  Current Channel Chat Window Shortcut Plugin

### ISSUE THREAD

**Issue by SeongGyu1216** [mwittrien/BetterDiscordAddons#2693]
**Describe the solution you'd like**
I want a shortcut to switch the chat window to the lower right of the current voice channel and to the right.

**Additional context**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/124080614/e28aba8d-a714-4a33-8b40-c6c2f7b89fc6)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/124080614/102203f5-b333-47ee-a62d-e66f51e2cada)

**Comment by mwittrien** [comment]
I am not makign new plugins
