### ISSUE TITLE
[BUG SOLVED WITH FIX] - SpotifyControl version 1.4.0 not working on Discord PC client

### ISSUE THREAD

**Issue by Infogenesys** [mwittrien/BetterDiscordAddons#2694]
**Describe the bug**
SpotifyControl sv 1.4.0 does not work even when the Discord / PC / BetterDiscord is restarted even when the plugin is enabled.

The bug has recently been noticed after Discord got updated (note: I have a Spotify Premium subscription if that matters)
Instead of showing the song name and other common music player controls, it shows the following error: 

![image_2024-05-23_154607643](https://github.com/mwittrien/BetterDiscordAddons/assets/164736792/28ce71a3-acf4-44a1-bb40-0f1f9eeba6ee)

Given above error states: "React Component Error"

**Comment by DenarQ2** [comment]
same here

**Comment by Infogenesys** [comment]
Thank you, the code finally works! 👍
