### ISSUE TITLE
[IMPROVEMENT] - MessageUtilities: allow setting triple click as activator

### ISSUE THREAD

**Issue by SKProCH** [mwittrien/BetterDiscordAddons#2697]
**Describe the solution you'd like**
Currently I've use doubleclick as the activator for "Edit message" action. But sometimes I've want just select a message text to copy it, but entering the edit mode.

It will be nice if I can setup triple click as the activator of action.

**Describe alternatives you've considered**
As alternative - I've like to allow select (or just have) an modifier key, which allows ignoring action invocation. For example, while Alt pressed none of the actions will not triggered (as it currently done in browsers, when i've want to select part of hyperlink text).

**Additional context**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/29896317/666654e1-6213-4c33-8a36-25c434ac2c51)

**Comment by mwittrien** [comment]
There is no tripple click event in Javascript

**Comment by SKProCH** [comment]
Yes. But on click handler we can check the event.details to determine the third click. 

If I implement it will you accept PR?
