### ISSUE TITLE
[BUG] - FriendNotifications v2.0, Stranger status not (always) being updated

### ISSUE THREAD

**Issue by Bennobear** [mwittrien/BetterDiscordAddons#2701]
**Describe the bug**
I added 3 strangers on the FriendNotifications Plugin they are from a bigger server (around 6.000 people) the plugin tracks some but not all status updates. When i open the profile it updates to the correct status.

**To Reproduce**
Deactivated all people on Friend-List.
Added 3 people from a big discord server as Stranger - tracking every status and logging it.
I have the Discord they are on in focus and i saw that they went offline but the plugin didn't realize.
If the plugin doesnt realize the status change opening their profile fixes it

**Expected behavior**
All status updates being logged in the Login/-Out Timelog

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
The plugin can only observe cached users, friends are always cached, strangers only when the user was loaded due to a GUI interface like the memberlist or a message

Cant be fixed
