### ISSUE TITLE
[BUG] - ImageUtilities - Low Resolution Copy

### ISSUE THREAD

**Issue by KingGamingYT** [mwittrien/BetterDiscordAddons#2705]
**Describe the bug**
When pasting a copied image (copied either by right-clicking the chat preview or right-clicking in the photo carousel), the copy is smaller and has a lower resolution than the source image. This makes copying images inconvenient as you must open it in an external browser or other viewer to copy it at full resolution.

**To Reproduce**
When copying an image.

**Expected behavior**
The image is copied and re-sent at its original resolution and should look identical to the source image.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/45918062/2a1eba33-20ae-4cac-989d-212ae8ec89f6)
(on the left is the source image, and on the right is the copied image)

**Discord Build (stable, ptb or canary):**
stable 301920 (198d4c4) Host 1.0.9149 x64 (48589) 

**Additional context**
This was reported in the support server back in April, but it looks like nothing was yielded from it.

**Comment by mwittrien** [comment]
Upload the source image somewhere and link it in here, also show me your plugin settings for ImageUtilities so i can try to reproduce the issue

**Comment by KingGamingYT** [comment]
The original image is uploaded here: ![image](https://pacoandchucko.com/wp-content/uploads/random/wiiumenucemu.png)

Here are my currently configured settings:
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/45918062/2663b4f6-f559-4759-8222-709a3836f821)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/45918062/c5043494-215e-42a3-b407-afde13057c69)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/45918062/d927e77a-d678-4ba1-8319-b20d6668c754)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/45918062/0f579860-844f-4c0e-9b3a-e9ef105a2a42)

**Comment by KingGamingYT** [comment]
Adding that the post-break fixes to the plugin did not magically fix the issue somehow.
