### ISSUE TITLE
[BUG] - Server Details Plugin

### ISSUE THREAD

**Issue by GSonicZ** [mwittrien/BetterDiscordAddons#2706]
**Describe the bug**
Server details don't show detail list when hover over server icon.

**To Reproduce**
Fresh install BetterDiscord. Only have BDFDB and Server Details enable. Hover over server icon

**Expected behavior**
Show server details as intend.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/56105213/a6dfa75a-8c2e-4dc0-bdad-bfe4da468946)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/56105213/0fedf893-425a-4b0b-82b8-0ec6f900c3dd)

**Discord Build (stable, ptb or canary):**
Stable 302556 (366c746)

**Additional context**

**Comment by HoltzFan10** [comment]
having the same issue

**Comment by K3rhos** [comment]
Yep looks like it has been recently broken for some reasons.

**Comment by TheOppaiDragon** [comment]
i have same issue, maybe need wait author need to fix it
