### ISSUE TITLE
[BUG] - Game Activity Toggle v1.2.4, button missing

### ISSUE THREAD

**Issue by whataboutism-alos** [mwittrien/BetterDiscordAddons#2710]
**Describe the bug**
The Game Activity toggleable button has failed to appear.

**To Reproduce**
Enable BDFDB and Game Activity Toggle, check where the button should be, see that it is not there. Thanks, Discord update!

**Expected behavior**
The Game Activity toggleable button smiling and waving at us from its little nook in the UI.

**Screenshots**
None required.

**Discord Build (stable, ptb or canary):**
stable 303105 (1897d8a) Host 1.0.9151 x64 (48891) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Additional context**
Hope it is an easy fix! The latest discord updates seems to have broken a lot!

**Comment by whataboutism-alos** [comment]
Strangely, it is now spontaneously working several hours later. I'll leave this unclosed since the discord update broke a lot of things and there still might be something wrong under the hood, but if something being broken isn't immediately obvious then there we go.

**Comment by brunorurz** [comment]
For me the button is there but it doesn't seem to work. It seems that updating BDFDB made it reappear again but it may need an update on it's own to be fully functional again.
