### ISSUE TITLE
[BUG] - Notificationsounds

### ISSUE THREAD

**Issue by cjanger** [mwittrien/BetterDiscordAddons#2717]
**Describe the bug**
the plugin no longer works in general. The global notifications sounds volume slider does not change the sound level of discord notifications nor does setting the sound individually per sound work. 

**To Reproduce**

A) global notification slider test
1. have someone send you a test message

B) individual sound configuration test
1. move global notifications sounds volume slider for mute/unmute action
2. press done
3. join a discord voice channel
4. mute and unmute

**Expected behavior**

A) message notifications should scale based on plugin global slider
B) mute and unmute notification sounds should scale based on individual slider picked in plugin

**Discord Build (stable, ptb or canary):**
stable 303105 (1897d8a) Host 1.0.9151 x64 (48891) Build Override: N/A Windows 10 64-bit (10.0.19045)
BD 1.10.2
Notificationsounds 3.9.6

**Comment by oxp** [comment]
regular pings in a server dont work at all

**Comment by jdramirez165** [comment]
Also the replaced sounds doesn't work. It just plays the Discord default sounds instead of the sounds from the plugin.
