### ISSUE TITLE
[BUG] - BDFDB Spamming error

### ISSUE THREAD

**Issue by ViLiDi230** [mwittrien/BetterDiscordAddons#2721]
**Describe the bug**
BDFDB spamming error

**To Reproduce**
Starting discord until BDFDB is deleted

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/99673250/34982d47-9509-4884-b138-ef16c9c1f5c5)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/99673250/66ec749e-197e-42e5-b6b4-aa12eb5698a7)

**Discord Build (stable, ptb or canary):**
Stable 303105

**Additional context**
While BDFDB spamming error Discord have lags

**Comment by Spawn3601** [comment]
Same issue here on my end I seem to be able to get rid of the errors by disabled 
EditChannel & TopRoleEverywhere Plugins which currently seem to be the culprit or at least part of the problem.

**Comment by Spawn3601** [comment]
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/3155860/63cb3e99-d2bd-4938-8426-889e3c8a6473)
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/3155860/89623064-3fb2-45db-b0bd-fc5e7666ec3d)
