### ISSUE TITLE
[BUG] - GameActivityToggle quickbutton missing

### ISSUE THREAD

**Issue by Andy76swe** [mwittrien/BetterDiscordAddons#2729]
**Describe the bug**
the quickbutton to toggle doesnt show up anymore

**To Reproduce**
when Discord is running, with plugin enabled

**Expected behavior**
a button to quickly toggle it on/off, but its not there anymore

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/71151970/a46261d5-eb44-4b54-9f95-c6bdacc23a94)

**Discord Build (stable, ptb or canary):**
stable 304106 (9764fd5) Host 1.0.9151 x64 (48891) Build Override: N/A Windows 11 64-bit (10.0.26241)

**Additional context**

**Comment by mwittrien** [comment]
Update BDFDB and delete 0BDFDB.data.json
