### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by aer0aa** [mwittrien/BetterDiscordAddons#2735]
**Describe the bug**
When I click on an image in a gallery, the image is in the top left instead of the centre

**To Reproduce**
Click on an image in a gallery with ImageUtilities turned on

**Expected behavior**
The image displays in the top left instead of the centre

**Screenshots**
![Screenshot 2024-06-22 192524](https://github.com/mwittrien/BetterDiscordAddons/assets/166466538/a053380a-8c3d-4026-8440-075b770ff751)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Using BetterDiscord Core v1.10.2 and ImageUtilities v5.4.4
A similar, although much less severe version of this problem happens to single images

With ImageUtilities on:
![Screenshot 2024-06-22 193333](https://github.com/mwittrien/BetterDiscordAddons/assets/166466538/2b7233da-2054-4c7a-9f5e-d9f2a69eb864)

With ImageUtilies off:
![Screenshot 2024-06-22 193429](https://github.com/mwittrien/BetterDiscordAddons/assets/166466538/2a107706-c1b8-4763-8665-0b02fe17bf12)

**Comment by mwittrien** [comment]
Can you paste your ImageUtilties.config.json in here

**Comment by HoltzFan10** [comment]
I have the same issue, here is my config 
[ImageUtilities.config.json](https://github.com/user-attachments/files/15942408/ImageUtilities.config.json)

**Comment by huskyon9** [comment]
same, here is my config
[ImageUtilities.config.json](https://github.com/user-attachments/files/15943826/ImageUtilities.config.json)
