### ISSUE TITLE
[BUG] - [THEME ISSUE]  - Theme: BasicBackground

### ISSUE THREAD

**Issue by TylerAustInW** [mwittrien/BetterDiscordAddons#2740]
**Describe the bug**
Seems to be some strange  z-indexing issues with the Profile pop out not displaying the contents inside of it. 

**To Reproduce**
Load the theme, click on the avatar where you would change your status 

**Expected behavior**
I expect to see the contents of the user content allowing to change my status, as well as rest of the settings within the User Profile pop out as normal. 

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/63419902/60843eff-7482-4d70-b7bc-79988d2cfa3f)

**Discord Build (stable, ptb or canary):**
stable 304187 (1dc5757) Host 1.0.9151 x64 (48891) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Comment by mwittrien** [comment]
This should already have been fixed, try reloading discord
