### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by Czerwony150** [mwittrien/BetterDiscordAddons#2741]
**Describe the bug**
Breaks rendering of text entry field.

**To Reproduce**
Open any conversation/server anything.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/165290741/f88def07-a998-4666-9d26-9c4d3b1004a5)

**Discord Build:**
Stable 306187 (2019a96)

**Comment by TheEmbracedOne** [comment]
Same happening to me since tonight, until now it was working fine.

**Comment by Oururis** [comment]
Same question

**Comment by TheRealKn1ghtSp1der** [comment]
Also here to confirm this, it loads fine but as soon as you click the message box the bug happens.

**Comment by Br3nnabee** [comment]
Same here, unfortunately. Doesn't happen when send message perms are disabled.

**Comment by Nox13last** [comment]
Same here. Setting the percent threshold ("Only show counter after Certain[sic] %") to an arbitrarily high number (so as not to appear immediately) doesn't help. Even if the counter is not visible at the moment, the issue occurs.
