### ISSUE TITLE
[IMPROVEMENT] - OBFDB Performance improvement

### ISSUE THREAD

**Issue by nicola02nb** [mwittrien/BetterDiscordAddons#2747]
**Describe the solution you'd like**
Adding only basic library, It decreases a lot the discord loading perfrmance

**Describe alternatives you've considered**
I know that by adding plugins, the performance and loading time of discord could decrease, but sometimes it blocks the program for 5-10 seconds which is quite bad for the user experiencee

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/61830443/acc04fa1-6d71-486f-ab50-de003bdf4406)

In the screenshot you can see how much time the library is taking to load

**Comment by mwittrien** [comment]
Can't be changed
