### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by bob-carter** [mwittrien/BetterDiscordAddons#2749]
**Describe the bug**
The user icons next to messages are all messed up, and covering up parts of their messages, when the basic background theme is on, and nothing else.

**To Reproduce**
As far as I can tell works with fresh install on most up to date client.

**Expected behavior**
Normal user icons.

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/46971019/7c771fd7-f35d-47c8-abca-b53774a933e7)

**Discord Build (stable, ptb or canary):**
Theme: BasicBackground.theme.css

**Additional context**
I reinstalled discord and better discord to check that this was still the case.

**Comment by bob-carter** [comment]
stable 307392 (6818046) Host 1.0.9152 x64 (49057) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Comment by SafeNut** [comment]
also getting this with vencord
