### ISSUE TITLE
[BUG] - BlurpleRecolor breaks white mode

### ISSUE THREAD

**Issue by nicola02nb** [mwittrien/BetterDiscordAddons#2750]
**Describe the bug**
When I set white discord to white mode, it remains black instead of becoming white

**To Reproduce**
While switching form dark to white mode

**Expected behavior**
Discord color shuld become white

**Screenshots**

**Discord Build (stable, ptb or canary):**
stable 304187 (1dc5757)
Host 1.0.9151 x64 (48891)
Build Override: N/A Windows 11 64-bit (10.0.22631)

**Additional context**
Using Betterdiscord Core v1.10.2

**Comment by mwittrien** [comment]
You are using DiscordRecolor and not BlurpleRecolor

BlurpleRecolor itself doesnt change the background-colors

**Comment by nicola02nb** [comment]
Yeah sorry
