### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by AlarkiusJay** [mwittrien/BetterDiscordAddons#2752]
**Describe the bug**
It starts out when I enable the plugin. All the server folders have slid  to the left and I can't scroll to get my other servers to appear!

**To Reproduce**
Install the plugin and enable it.  I've even tried disabling and enabling its features via the plugins section

**Expected behavior**
It's supposed to show all my server lists / pinned DMs, but somehow it doesn't! 

**Screenshots**
![#┇🎪❝chat _ Cultured Room - Discord 7_9_2024 4_41_58 PM](https://github.com/mwittrien/BetterDiscordAddons/assets/84819182/96a92d7e-62ca-4e6f-a615-b1b20121fc06)

**Discord Build (stable, ptb or canary):**
1.10.2 of BetterDiscord Stable

**Additional context**

**Comment by mwittrien** [comment]
What theme are you using

**Comment by AlarkiusJay** [comment]
I'm just using a horizontal server theme for the top. Custom CSS! 

[Gibbu](https://betterdiscord.app/theme/Horizontal%20Server%20List)

**Comment by mwittrien** [comment]
Issue with the Theme and not the plugin
