### ISSUE TITLE
[BUG] - ImageUtilities Thumbnails from videos not showing up in gallery layout.

### ISSUE THREAD

**Issue by Jugom** [mwittrien/BetterDiscordAddons#2753]
**Describe the bug**
A channel in forum format working as a gallery. pictures will be previewed as thumbnails correctly, but videos won't.
Disabling the plugin let videos appear as thumbnails too as exxpected.

**To Reproduce**
Have ImageUtilities enabled.
Upload a picture and a video to a gallery channel (forum type with gallery layout)
Notice how the picture post displays the thumbnail but the video post doesn't
Toggle ImageUtilities off and see the video thumbnail show up.

**Expected behavior**
For videos to show up too.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Works fine for me
