### ISSUE TITLE
[BUG] - ImageUtilities; Blank screen when message contains multiple images

### ISSUE THREAD

**Issue by AlienFreek** [mwittrien/BetterDiscordAddons#2754]
When a message contains multiple images, clicking an image results in a blank screen.

**To Reproduce**
Send message with multiple images, click one of the images

**Expected behavior**
ImageUtilities' image viewer should open

**Screenshots**
Clip provided: 
https://github.com/user-attachments/assets/a62b2d02-8e1a-4ee8-aba2-040586605baf

**Discord Build (stable, ptb or canary):**
Stable 310102 (4666fcc) 
Host 1.0.9153 x64 (49397) 
Build Override: N/A 
Windows 10 64-bit (10.0.19045)

**Additional context**
Images properly display when clicking an image sent by itself and using the arrow keys to navigate to the grouped images (shown in clip). Reinstalling plugin and deleting its config causes no change

**Comment by AlienFreek** [comment]
Issue remains after updating to [23515d5](https://github.com/mwittrien/BetterDiscordAddons/commit/23515d573972129ac442c270699cceeb5f65f343) @mwittrien

**Comment by mwittrien** [comment]
Share your ImageUtilities.config.json

**Comment by AlienFreek** [comment]
[ImageUtilities.config.json](https://github.com/user-attachments/files/16277684/ImageUtilities.config.json)

**Comment by mwittrien** [comment]
Working fine for me, try delete 0BDFDB.data.json and reload discord

**Comment by AlienFreek** [comment]
Deleting 0BDFDB.data.json didnt fix it but wiping the betterdiscord folder worked. Appreciate your work!
