### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by IAmToastyGhost** [mwittrien/BetterDiscordAddons#2755]
**Describe the bug**
Image/video is not visible when opened in the gallery on multi-image/video messages

**To Reproduce**
Click on image/video in a multi-image/video message

**Expected behavior**
The image/video opens and is visible in the gallery

**Screenshots**
![image](https://github.com/user-attachments/assets/1b6a79b2-2864-4632-b951-ab6ca9b32041)
![image](https://github.com/user-attachments/assets/f97cfadd-96b9-4438-9ffb-98c15f23fafd)

**Discord Build (stable, ptb or canary):**
stable 310927

**Additional context**
N/A

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and 0BDFDB.plugin.js  and reload then redeownload the library
