### ISSUE TITLE
[BUG] - ReadAllNotificationsButton Does Not Work

### ISSUE THREAD

**Issue by SoggyBurritoVR** [mwittrien/BetterDiscordAddons#2756]
**Describe the bug**
Button appears but does not do anything on press.

**To Reproduce**
Press the "read all" button.

**Expected behavior**
On button click all messages should be marked as read. 

**Discord Build (stable, ptb or canary):**
stable 311885 (0ae8466) Host 1.0.9154 x64 (49586) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Comment by mwittrien** [comment]
Working just fine
