### ISSUE TITLE
[BUG] - CustomStatusPresets

### ISSUE THREAD

**Issue by meimemi** [mwittrien/BetterDiscordAddons#2763]
**Describe the bug**
After the new Discord update we no longer have the custom status as a label, instead it's a thought bubble beside one's profile picture.

**To Reproduce**
Have Discord updated

**Expected behavior**
Be able to hover over the custom status label and choose a saved custom status

**Screenshots**
![image](https://github.com/user-attachments/assets/92d19e64-5ebe-4e6a-afd8-c5274c85ba99)
![image](https://github.com/user-attachments/assets/6df24be2-0278-4b15-b4eb-e15b04824f11)

**Discord Build (stable, ptb or canary):**
stable 318966 (48a348b) Host 1.09158 x64 (50841)

**Additional context**
It seems they're changing where the custom status setting is, so may need more coding to replace or add an extra button

**Comment by mwittrien** [comment]
Right click the label
