### ISSUE TITLE
[BUG] - CustomStatusPresets no longer works since a status update on PTB

### ISSUE THREAD

**Issue by Lusiiky** [mwittrien/BetterDiscordAddons#2767]
**Describe the bug**
CustomStatusPresets no longer works and is simply no longer displayed on PTB versions.

**To Reproduce**
Just use PTB version

**Screenshots**
Stable:
![image](https://github.com/user-attachments/assets/e75fc6c8-9b4f-4963-9fb7-b21ca4849640)

PTB, new status system:
![image](https://github.com/user-attachments/assets/df4007d8-10d0-432c-b8ac-f32da2ebc440)

**Discord Build (stable, ptb or canary):**
ptb 320490 (fe80de9)
Host 1.0.1097 x64 (51077)
Build Override: N/A
Windows 11 64-bit (10.0.22631)

**Additional context**
Cause the PTB versions have introduced the status modification in a new small bubble.

Thank you!

**Comment by mwittrien** [comment]
Rught click the status bubble
