### ISSUE TITLE
[IMPROVEMENT] - REMOVE BLOCKED USERS SETTINGS

### ISSUE THREAD

**Issue by Zeyyagga** [mwittrien/BetterDiscordAddons#2771]
I'm just seeking clarification on what a few of the toggle settings actually do, specifically:
"Members in Voice List vs Members in Voice Chat" (more so list than chat, just wondering the relation)
"Channel/Group List"
"Group Notifications"

Every other toggle is pretty self explanatory and works as one would expect them to. 

If all this is already documented somewhere I apologize I must have missed it if not I'd like to suggest documenting it for clarity. 

![image](https://github.com/user-attachments/assets/705f28ce-6256-4542-8e0f-49996c5039d4)

**Comment by mwittrien** [comment]
Voice List -> In the List of connected Voice Users under the Voice Channel

Voice Chat -> Inside an open Voice Channel (Member List, Connected Users, etc.)

Channels/Groups -> In the Channel List/Direct Messages List (Groups)

Group Notifications -> In the Server List (recent DM Groups)
