### ISSUE TITLE
[IMPROVEMENT] - PinDMs: Allow collapsing Direct Messages

### ISSUE THREAD

**Issue by ungive** [mwittrien/BetterDiscordAddons#2777]
**Describe the solution you'd like**
I would like to be able to collapse "Direct Messages", just like I am able to collapse custom categories, as if direct messages were a custom category. This would allow me to hide all except a few selected conversations.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by mwittrien** [comment]
Not the purpose of the plugin
