### ISSUE TITLE
[IMPROVEMENT] - ShowUserJoinDateInPopout

### ISSUE THREAD

**Issue by thatpanda0** [mwittrien/BetterDiscordAddons#2779]
**Describe the idea you'd like**

Since it's possible to use JavaScript to show Connections in the user popout, could the same be possible for the user join date?

**Describe alternatives you've considered**

**Additional context**

N/A

**Comment by mwittrien** [comment]
The join date should already be displayed in the user popout

And i am not open for new plugins
