### ISSUE TITLE
FriendNotifications table headers spacing broken

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [mwittrien/BetterDiscordAddons#278]
![Discord_jXbEJ4wxXP](https://user-images.githubusercontent.com/44043300/65289816-eede8c00-db11-11e9-93ca-6bc5badeaa2e.png)

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/65346823-ee132c00-dbdd-11e9-9535-6f7bd312b49b.png)
working fine for me

**Comment by AdovinOFFICIAL** [comment]
damn, pulled the "works on my machine" card on me

guess something went wrong and reinstalling the plugin will fix it, hoping so at least.
