### ISSUE TITLE
[BUG] - CustomStatusPresets: can't Select Presets

### ISSUE THREAD

**Issue by iazmDEV** [mwittrien/BetterDiscordAddons#2782]
**Describe the bug**
Can't Select my Preset Status/Can't find the Button to select Custom Presets Due to new Discord's New Profile Change

**To Reproduce**
When opening my Profile (Profile on Down left)

**Expected behavior**
a New Button added to view your Custom Presets

**Screenshots**
![image](https://github.com/user-attachments/assets/3e5449a3-2522-466b-9761-421150122f4d)
Cant/No Button for Custom Presets

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
No. adding a Preset works its just Selecting it

**Comment by mwittrien** [comment]
Right click it ...
