### ISSUE TITLE
[BUG] - PLUGIN/Translator

### ISSUE THREAD

**Issue by Latom-alex** [mwittrien/BetterDiscordAddons#2784]
Hello, I ran into a translator problem, It seems this problem occurred yesterday at about 18:00 (I don't remember exactly the time) UTC +3 It seems that after updating the discord, I am using v1.10.2.

The translator plugin stopped translating messages before sending, I tried to reinstall the plugin several times, as well as BetterDiscord itself (I also deleted the translator settings configs) it did not fix the gap. I also checked several times whether the plugin settings were specified correctly, the settings were without any changes and worked until the discord update or until 09/25/24

Unfortunately, I cannot provide any additional information as I do not know where the log files from BetterDiscord are located.
Discord version app-1.0.9164

**Comment by SigmanautNZ** [comment]
Same here.

I've freshly installed both Discord and the plugin alongside better discord and am not getting messages translated before transmission. 

My partner is sending messages back okay currently but I'm not sure if they will encounter the issue soon.

**Comment by mwittrien** [comment]
fixed
