### ISSUE TITLE
[IMPROVEMENT] - SERVERFOLDERS: Ability to drag servers into the second column to add them to folders

### ISSUE THREAD

**Issue by antrobot1234** [mwittrien/BetterDiscordAddons#2789]
**Describe the solution you'd like**
Similarly to how you can re-order folders from within the second column, you should be able to drag servers from the first column (un-catagorized servers) into the second column to add them to the server

**Describe alternatives you've considered**
While you can drag servers into the folders on the first column, this feature would allow you to add the server in the desired order in one step, rather than adding it and organizing it in two separate steps.

**Comment by mwittrien** [comment]
Too much a bother to implement just to save people two seconds of their life
