### ISSUE TITLE
[BUG] - ImageUtilities makes discord response slow

### ISSUE THREAD

**Issue by huskyon9** [mwittrien/BetterDiscordAddons#2792]
**Describe the bug**
ImageUtilities cause discord response slow, the response time has been slower than a few days ago.
when ImageUtilities is disable, it will back to normal response speed.

**To Reproduce**
enable it

**Expected behavior**
work normaly

**Discord Build (stable, ptb or canary):**
stable 335959 (feced0f) Host 1.0.9166 x64 (53429) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Comment by Aaeeschylus** [comment]
Can confirm this is happening to me as well. As soon as imageutilities gets enabled, switching between channels/servers/dms takes several seconds and discord completely freezes while loading.

Build:
stable 335959 (feced0f) Host 1.0.9166 x64 (53429) Build Override: N/A Windows 11 64-bit (10.0.22000)
