### ISSUE TITLE
[BUG] - EditUsers v.4.9.3: Comes up as error after launching discord 

### ISSUE THREAD

**Issue by BubblyBreadysi** [mwittrien/BetterDiscordAddons#2795]
**Describe the bug**
This bug appears when I launch Discord. It says there is another plugin with edit users, even though that is the only edit users file. I have reinstalled this plugin multiple times, and it still comes up.

**To Reproduce**
When I launch discord, it comes up.

**Expected behaviour**
To not show up as a start-up error 
**Screenshots**
![image](https://github.com/user-attachments/assets/6bcf18bc-897a-48eb-b6d5-f27394e071d8)
![image](https://github.com/user-attachments/assets/a4345bd7-d690-4991-ac0b-b1fea7de2f9b)
`[2024-10-21 19:17:40.335][CONSOLE:ERROR] [EditUsers] (v4.9.3) Fatal Error: "after" callback of t in FocusRingScope TypeError: Cannot read properties of undefined (reading 'indexOf')
`

**Discord Build (stable, ptb or canary):**
stable 337154 (65fd300) Host 1.0.9166 x64 (53429) Windows 11 64-bit

**Comment by mwittrien** [comment]
Delete Test.plugin.js

**Comment by BubblyBreadysi** [comment]
In my plugins folder, there is no file called Test.plugin.js

**Comment by BubblyBreadysi** [comment]
I have figured out that you meant text.plugin,js. I have now deleted it and it now longer comes up. Thank you for replying,
