### ISSUE TITLE
[BUG] - StaffTag and PinDMs entirely broken on PTB

### ISSUE THREAD

**Issue by iiNekoMattyii** [mwittrien/BetterDiscordAddons#2796]
**Describe the bug**
they don't show up after discord launch at all

**To Reproduce**
install better discord slap em in the plugins folder and launch discord

**Expected behavior**
them to work i guess?

**Screenshots**
N/A they literally just don't exist

**Discord Build (stable, ptb or canary):**
PTB

**Additional context**
they just didn't work when i opend discord this morning i've tried redownloading the plugins and reinstalling betterdiscord.

**Comment by BubbliBlu** [comment]
Not on PTB, on stable release currently, and having the same issue (I think)- PinDMs shows up in my plugin list and is enabled but has no effect on my client citing inabillity to initiate BDFDB Library Plugin and Create Settings Panel.  I don't use StaffTag so I can't verify if the same issue is happening with that one, but PinDMs is nonfunctional at the moment.
