### ISSUE TITLE
[BUG] - RemoveBlockedUsers not working with newest update

### ISSUE THREAD

**Issue by kamikazilucas** [mwittrien/BetterDiscordAddons#2798]
updated better discord and now the plugin has stopped working

**Comment by MegaShinySnivy** [comment]
Can confirm. Disabling and reenabling the plugin does nothing. Nothing relevant in my logs either.

**Comment by kamikazilucas** [comment]
why was it closed as fixed? its not fixed?

**Comment by mwittrien** [comment]
Update BDFDB

**Comment by kamikazilucas** [comment]
dosent fix anything, i have 3.8.2 and dosent do anything

**Comment by Lishenntser** [comment]
Still doesn't work.

**Comment by kamikazilucas** [comment]
you have to download the version on github apparently  the website hasent been updated yet
