### ISSUE TITLE
[BUG] - PLUGIN/Translator

### ISSUE THREAD

**Issue by SigmanautNZ** [mwittrien/BetterDiscordAddons#2800]
**Describe the bug**
Translator App functionality removed

**To Reproduce**
Update to latest Better Discord

**Expected behavior**
To see the translator Icon and functionality within Discord

**Screenshots**
![image](https://github.com/user-attachments/assets/ad4adf38-f169-4706-80fb-a885f4177af4)

**Discord Build (stable, ptb or canary):**
Latest

**Comment by cocoflan** [comment]
Just the same here, no longer works after updating the translate plugin.

**Comment by cocoflan** [comment]
https://discord.com/channels/410787888507256842/410788958277074944/1303789986017050708

**Comment by cocoflan** [comment]
It works again with the explanation in link on discord.
