### ISSUE TITLE
[BUG] - CustomStatusPresets no longer working

### ISSUE THREAD

**Issue by XM0ni** [mwittrien/BetterDiscordAddons#2805]
**Describe the bug**
After latest discord update, the customstatuspresets plugin no longer works. when right clicking the status, the menu doesn't pop up.

**To Reproduce**
Trying to right click the status to open the presets, nothing happens.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by KogaSilvercloud** [comment]
It always happen on discord update, we need to wait an BD/Plugin Update
