### ISSUE TITLE
[BUG] - EmojiReplace Emojis wrong due to new emojis added

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [mwittrien/BetterDiscordAddons#2807]
**Describe the bug**
When rendering Apple emojis, the emojis work but some of them are wrong. (Alien emoji replaces Skull emoji)
The index of emojis to replace is off because Discord has apparently added new emotes (head shaking emote) as shown below.

**To Reproduce**
When does the bug occur.
Load the CSS with this theme, go to emoji selector, there's your problem.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ab27cda-0652-463c-8aae-383ee9b1b14f)
![image](https://github.com/user-attachments/assets/e003a5d1-59b6-4132-96c1-778049e4e66b)
![image](https://github.com/user-attachments/assets/dd441205-f7f1-4ea6-b466-86eff1c268b2)
![image](https://github.com/user-attachments/assets/ffef024f-3bee-4216-8bf0-0619980713e8)
![image](https://github.com/user-attachments/assets/5f0518ad-307d-4c30-92d7-5348b3ef3092)

**Discord Build (stable, ptb or canary):**
Latest stable build

**Comment by Lamparter** [comment]
@mwittrien why'd you close this?
It's not fixed.

**Comment by mwittrien** [comment]
Because the fix is being uploaded right now?
