### ISSUE TITLE
[BUG] - Could not initiate BDFDB Library Plugin

### ISSUE THREAD

**Issue by embry0** [mwittrien/BetterDiscordAddons#2808]
**Describe the bug**
Issue started after an update to BDFDB and Discord. Every DevilBro plugin is broken incl. repos. Persists even after deleting 0BDFDB.data.json and restarting Discord.

**To Reproduce**
Update Dicord, BetterDiscord and BDFDB and try opening/using any DevilBro plugin.

**Screenshots**
![Screenshot 2024-11-07 115548](https://github.com/user-attachments/assets/9d8e2103-507f-4da0-9346-bb4d83e5aa6a)

**Discord Build (stable, ptb or canary):**
Stable 342245 (47f50da)

**Comment by xaenerys0** [comment]
Same here.

**Comment by NoSc0ped** [comment]
having this issue too, also all of my BDFDB plugins dont work

**Comment by NoSc0ped** [comment]
> NoSc0ped

update , issue solved (idk how tho i just re-downloaded everything)

**Comment by xaenerys0** [comment]
> > NoSc0ped
> 
> update , issue solved (idk how tho i just re-downloaded everything)

Does not work for me.

**Comment by xaenerys0** [comment]
Weird, downloading from BetterDiscord did not work for redownloading, had to grab it directly from the repo and save the file and that worked.

**Comment by embry0** [comment]
I tried reinstalling everything. Discord, BD and BDFDB. Still no luck. BDFDB still broken

**Comment by xaenerys0** [comment]
> I tried reinstalling everything. Discord, BD and BDFDB. Still no luck. BDFDB still broken
> 

I had the same issue, I had to download the file directly from the repo and delete the plugins other files like *.data.json.

**Comment by embry0** [comment]
So delete all other plugins and only download [this](https://betterdiscord.app/plugin/BDFDB) right?

**Comment by xaenerys0** [comment]
I had to download from [here](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Library%2F0BDFDB.plugin.js). Downloading from Better Discords site did not work either.

**Comment by embry0** [comment]
I thought both places have the same file. I didn't think about downloading it from the repo here but yeah that fixed the issue. Thanks for walking me through it.
