### ISSUE TITLE
CompleteTimestamps feature request: Option to enable leading zeroes in milliseconds

### ISSUE THREAD

**Issue by Titanic4** [mwittrien/BetterDiscordAddons#281]
Right now the milliseconds don't have leading zeroes. This will make the timestamp stand out when the millisecond is within range of 0 to 99.  I think you should add the option to enable leading zeroes in milliseconds in order to make the timestamp look better.

**Comment by mwittrien** [comment]
leading zeros option now properlly adds zeros to milliseconds
