### ISSUE TITLE
[BUG] - GameActivityToggle Item Toggle does not appear in the user menu

### ISSUE THREAD

**Issue by XM0ni** [mwittrien/BetterDiscordAddons#2810]
**Describe the bug**
The GameActivityToggle plugin doesn't show the toggle item in the user menu. The button toggle does show up, but there isn't a lot of space there.

**To Reproduce**
Turn on the Toggle Item in the settings of GameActivityToggle and click on the user profile.

**Expected behavior**
There should be (at least, it used to be) the button to turn on and off your game activity in the little menu. Nothing happens with the Toggle Item setting anymore.

**Screenshots**
![image](https://github.com/user-attachments/assets/d11e6542-5a53-482d-91b8-2fef5783239a)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by Patcheresu** [comment]
Could you post your version of the library? Is it 3.8.2?

**Comment by XM0ni** [comment]
![image](https://github.com/user-attachments/assets/7615a8e6-2bb2-496d-8ec1-85ea1388ca67)
It is 3.8.5
