### ISSUE TITLE
[BUG] - "Could not initiate BDFDB Library Plugin! Can not create Settings Panel!" Error

### ISSUE THREAD

**Issue by walnutsoap** [mwittrien/BetterDiscordAddons#2811]
It stops the other DevilBro plugins from working. 

BetterDiscord, Discord, and the plugin are updated. as well.

![image](https://github.com/user-attachments/assets/f944334c-a6ff-4195-808c-f61c772268e4)
 
Error pops up when clicking on the BDFDB library plugin settings icon.

I reinstalled Better Discord and it didn't fix anything and I also tried to troubleshoot but there wasn't a fix.

**Comment by mwittrien** [comment]
Redownload BDFDB and delete 0BDFDB.data.json
