### ISSUE TITLE
[BUG] - ReadAllNotificationsButton

### ISSUE THREAD

**Issue by TheKrush** [mwittrien/BetterDiscordAddons#2815]
**Describe the bug**
Settings won't open and no button appears for marking all read.

**To Reproduce**
Anytime you start BetterDiscord

**Expected behavior**
Button should appear and plugin should work.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
stable 342136 (3fdae72) Host 1.0.9168 x64 (54039) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Additional context**
N/A

**Comment by mwittrien** [comment]
Update BDBFDB and delete 0BDFDB.data.json
