### ISSUE TITLE
[BUG] - TRANSLATOR

### ISSUE THREAD

**Issue by BenJ3D** [mwittrien/BetterDiscordAddons#2816]
Hello, I think the translation plugin is great, but it has a small bug that makes it unpleasant to use to translate threads. 

When I try to translate a message that is not at the end of the thread, the position in the thread moves by several messages, even a lot, making it difficult to follow a conversation smoothly and complicated to find the message that has just been translated.

Thank you in advance

**Comment by mwittrien** [comment]
This sadly cant be fixed
