### ISSUE TITLE
[BUG] - PluginRepo and ThemeRepo - React Component Error when viewing banner/screenshot

### ISSUE THREAD

**Issue by Miniontoby** [mwittrien/BetterDiscordAddons#2819]
**Describe the bug**
Clicking on the image banner of an plugin in the Plugin Repo and in Theme Repo shows "React Component Error"

**To Reproduce**
Just click on the banner of any plugin in the Plugin Repo and in Theme Repo.

**Expected behavior**
I was expecting to see a bigger view of the banner/screenshot.

**Screenshots**
![image](https://github.com/user-attachments/assets/b3c4aac2-0057-4bb0-ba8a-c3d69ab6bdad)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by Miniontoby** [comment]
No more react component error yeah, but the image doesn't seem to be showing big tho when I click on it...

Not sure if that's just me...

**Comment by mwittrien** [comment]
It shows in the original quality. If the preview pic is tiny then the fullview is also tiny

**Comment by Miniontoby** [comment]
It seems it was a glitch... I reloaded discord (because it wanted to update) and now it works fine.

And no: it wasn't that is was tiny, cause it showed NOTHING. but yeah its fine now
