### ISSUE TITLE
Reverse search menu isn't showing up when right click on an image anymore

### ISSUE THREAD

**Issue by ajtpak** [mwittrien/BetterDiscordAddons#282]
![Discord_2019-09-29_03-00-06](https://user-images.githubusercontent.com/8887956/65828109-4a70ee00-e265-11e9-88d9-7f82fb6a9bfa.png)

After the new discord update, I can't reverse search anymore from the menu.

**Comment by mwittrien** [comment]
Works on my end
Don't use messageloggers

**Comment by ajtpak** [comment]
I turned message logger off and it's still not available. Reinstalled the reverse search plugin and it's still not available. Why shouldn't I use messagelogger?

**Comment by mwittrien** [comment]
Disable all other plugins and make sure you are right clicking an image

ajtpak <notifications@github.com> schrieb am Mo., 30. Sep. 2019, 15:39:
