### ISSUE TITLE
[BUG] - Making it so my fullscreen game are my background image

### ISSUE THREAD

**Issue by charleypepito11** [mwittrien/BetterDiscordAddons#2821]
**Describe the bug**
So when I launch games, it makes it that I can only see the background image for my discord in fullscreen? I can only click stuff if I alt-tab and click very fast

**To Reproduce**
everytime I launch a game with the background theme on.

**Expected behavior**
Make it so I can launch games without having this problem ig

**Screenshots**
what I see when alt-tab:
![image](https://github.com/user-attachments/assets/fc8e5e4e-296e-4459-bb7f-8fd8295738af)
what I see when clicking on my game window: 
![image](https://github.com/user-attachments/assets/c76968e6-9e19-4d34-b121-5b6f867cab6a)

**Discord Build (stable, ptb or canary):**
canary

**Additional context**
It did it for multiple games; rust, dbd etc... And it is 100% this theme because when I turn it off and launch the game it doesn't happen

**Comment by mwittrien** [comment]
How is this related to my plugins?

**Comment by charleypepito11** [comment]
what do you mean? It's when I turn off your plugin it stops doing that? So its your plugin causing it? I'm confused

**Comment by charleypepito11** [comment]
like I literally have to turn off your plugin every time I launch a game, I like the plugin and want to keep using it but having to close it everytime is very annoying, I updated discord etc and it keeps doing it.

**Comment by mwittrien** [comment]
"Your plugin" what plugin

**Comment by charleypepito11** [comment]
[BetterDiscordAddons] (https://github.com/mwittrien/BetterDiscordAddons/tree/master) / [Themes](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Themes)
/BasicBackground 

this one the basicbackground one, when I launch a game it puts the background image I choose in fullscreen like in the provided screenshot and I can hear the game like menu but cannot see unless I alt-tab or open another window, whenever I turn off the plugin the problem dissapears so right now I have to turn off the plugin, launch games and then turn on the plugin. Just for information the image isn't my desktop image so it's not that.

**Comment by charleypepito11** [comment]
you want a video or?
