### ISSUE TITLE
[BUG] - "Could not initiate BDFDB Library Plugin"

### ISSUE THREAD

**Issue by ArgentVASIMR** [mwittrien/BetterDiscordAddons#2822]
The following error message shows up when attempting to run BetterDiscord with the BDFDB library plugin:
![image](https://github.com/user-attachments/assets/5564d0d3-e24d-486d-9d02-c9cd42f966af)

While the problem is similar in nature to [this](https://github.com/mwittrien/BetterDiscordAddons/issues/2681), I do not have a `0BDFDB.data.json` file to delete, if that would have even fixed the problem. Multiple reloads have not worked, either.

Here is my Discord build and Windows version:
```
stable 346031 (55ed91d) 
Windows 10 64-bit (10.0.19045)
```

edit 1:
I attempted to download from both the BetterDiscord website, and tried `0BDFDB.plugin.js` when downloaded directly from this repo, as well as trying to reload Discord through both CTRL + R, and by closing and reopening the app. No luck.

**Comment by ArgentVASIMR** [comment]
I attempted to download from both the BetterDiscord website, and tried `0BDFDB.plugin.js` when downloaded directly from this repo. No luck.
I reloaded Discord through both CTRL + R, and by closing and reopening the app. No luck.

**Comment by wznmickey** [comment]
Same issue.

**Comment by mwittrien** [comment]
Delete 0BDFDB.data.json and reload discord

**Comment by wznmickey** [comment]
I do not have this file.

**Comment by mwittrien** [comment]
Its in your plugins folder
