### ISSUE TITLE
[FEATURE] - NOTIFICATIONSOUNDS custom per chat?

### ISSUE THREAD

**Issue by masterofcaribou** [mwittrien/BetterDiscordAddons#2825]
**Describe the solution you'd like**
Something similar to how on mobile devices you can set a contact to have a custom text tone, it would be cool to have them on an individual basis so i can quickly know when certain people message me!

**Describe alternatives you've considered**
Presumably implementing it to check the name of a sender is easiest and I would not mind that at all, but it could cause problems for people who change their display name often. if it checks actual username that wouldn't be an issue nearly as often I'd assume, but I don't know how easy or hard any of this is on the backend!

**Additional context**

![image](https://github.com/user-attachments/assets/81b4f337-5a5f-4f78-874b-0e62c35ea296)

thank you in advance for your time :)

**Comment by mwittrien** [comment]
Not planned, as its too much to implement
