### ISSUE TITLE
[BUG] - PINDMS

### ISSUE THREAD

**Issue by Lannyferd** [mwittrien/BetterDiscordAddons#2827]
**Describe the bug**
Clicking on a dm chat causes the dms bar to scroll down excessively

**To Reproduce**
Download and turn on PinDMs

**Expected behavior**
No scrolling issue when changing between DMs

**Screenshots**
https://youtu.be/Q4BSLbb5ulI

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
n/a

**Comment by mwittrien** [comment]
Sadly can't be fixed due to a discord issue
