### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedUsers

### ISSUE THREAD

**Issue by zabersan** [mwittrien/BetterDiscordAddons#2831]
**Describe the solution you'd like**
Support/Version for VenCord

**Describe alternatives you've considered**
none, haven't found any.

**Additional context**
What is VenCord?
A web/chromium extension that does what Better Discord does.
https://github.com/Vendicated/Vencord

**Comment by mwittrien** [comment]
My plugins arent for vencord, i am not adding support
