### ISSUE TITLE
[IMPROVEMENT / BUG] - Change to the recently added triple click to open web browser translate

### ISSUE THREAD

**Issue by grannyd15** [mwittrien/BetterDiscordAddons#2832]
**Describe the solution you'd like**
When you triple click the translate button to open the google translate ina  browser, it opens it with the message already in the box, which is possible with added the message to the link that is opened as a parameter "text"
**Describe alternatives you've considered**
If you triple click, the contents of the message is added to the clipboard instead to paste into the google translate text box

**Additional context**
I am unsure if this is a bug that it isnt happening or should be a sugestion to be added

**Comment by mwittrien** [comment]
It already does that
