### ISSUE TITLE
[BUG] - THEME/BASICBACKGROUND Theme wont show up

### ISSUE THREAD

**Issue by Web-mainiac** [mwittrien/BetterDiscordAddons#2833]
**Describe the bug**
https link to image on deviantart wont show up as my backround anymore
**To Reproduce**
added this "@import url(https://www.deviantart.com/vadymar/art/Shadow-the-Hedgehog-Wallpaper-957905687);"
**Expected behavior**
image should be new background
**Discord Build (stable, ptb or canary):**
stable
**Additional context**
it worked last time but NOW it doesnt

**Comment by mwittrien** [comment]
The link has to be a direct image link

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b5c62879-e2d3-49a5-9e0f-f65450fbff7f/dfub8rb-349e533e-73db-4ba0-a0ca-49d12e09e410.png/v1/fit/w_828,h_466,q_70,strp/shadow_the_hedgehog_wallpaper_by_vadymar_dfub8rb-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjE2MCIsInBhdGgiOiJcL2ZcL2I1YzYyODc5LWUyZDMtNDlhNS05ZTBmLWY2NTQ1MGZiZmY3ZlwvZGZ1YjhyYi0zNDllNTMzZS03M2RiLTRiYTAtYTBjYS00OWQxMmUwOWU0MTAucG5nIiwid2lkdGgiOiI8PTM4NDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.c6gzScp3x7DjhdPZ8kFD-BpJ54-77AtPG89GVKQ3YZs

**Comment by Web-mainiac** [comment]
> The link has to be a direct image link
> 
> https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b5c62879-e2d3-49a5-9e0f-f65450fbff7f/dfub8rb-349e533e-73db-4ba0-a0ca-49d12e09e410.png/v1/fit/w_828,h_466,q_70,strp/shadow_the_hedgehog_wallpaper_by_vadymar_dfub8rb-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjE2MCIsInBhdGgiOiJcL2ZcL2I1YzYyODc5LWUyZDMtNDlhNS05ZTBmLWY2NTQ1MGZiZmY3ZlwvZGZ1YjhyYi0zNDllNTMzZS03M2RiLTRiYTAtYTBjYS00OWQxMmUwOWU0MTAucG5nIiwid2lkdGgiOiI8PTM4NDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.c6gzScp3x7DjhdPZ8kFD-BpJ54-77AtPG89GVKQ3YZs

It still doesnt work
