### ISSUE TITLE
[BUG] - ImageUtilitiesv5.5.0

### ISSUE THREAD

**Issue by Wernouxe** [mwittrien/BetterDiscordAddons#2838]
**Describe the bug**
I cannot copy image .webp

**To Reproduce**
Essaiyer de copier une image en format .webp

**Expected behavior**
Allow to copy an image .webp

**Discord Build (stable, ptb or canary):**
Stable, last update

![image](https://github.com/user-attachments/assets/ae402ef1-08c8-458c-ad4d-7b55f5f45fb3)

**Comment by mwittrien** [comment]
Because webp images aren't copyable, nothing i can do about it
