### ISSUE TITLE
The double-toasts were fixed, now they are broken again with the alleged "fix"

### ISSUE THREAD

**Issue by Chosen-Fate** [mwittrien/BetterDiscordAddons#284]

**Comment by mwittrien** [comment]
no

**Comment by Chosen-Fate** [comment]
You cant just close this man why did you break it again??

**Comment by mwittrien** [comment]
Broke it just for you

ChosenFate <notifications@github.com> schrieb am Mi., 2. Okt. 2019, 12:11:

**Comment by Chosen-Fate** [comment]
Seriously man, it was fixed and now you broke it again.. i reinstalled it, reinstalled BD as a whole, nothing works after the """"fix""""

**Comment by mwittrien** [comment]
It's not broken, you are eihter using it wrong or got a duplicate plugin file, now stop spamming closed issues
