### ISSUE TITLE
[BUG] - ImageUtilities | Right-Click Menu Buttons are Non-Functional

### ISSUE THREAD

**Issue by KingGamingYT** [mwittrien/BetterDiscordAddons#2841]
**Describe the bug**
In chat and/or when the image is open in the viewer, context menu buttons for copying its link or the image itself to your clipboard do not function, and copy nothing to the clipboad.

**To Reproduce**
1. Right click an image
2. Attempt to copy its link/media link, or image
3. Nothing happens except a toast saying it was successful, when it wasn't.

**Expected behavior**
The image or image link should be copied to the clipboard.

**Screenshots**
![image](https://github.com/user-attachments/assets/de0c5cea-9847-496f-9009-aba16d663109)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Works fine for me

https://media.discordapp.net/attachments/806454158605418506/1322978135456743455/1.webp?ex=6772d6e7&is=67718567&hm=9b6e9ae1b64c5df95df8ee515a7f0a8d3cda574a5b33cc9f1c45c5b4219868d1&=

https://cdn.discordapp.com/attachments/806454158605418506/1322978135456743455/1.webp?ex=6772d6e7&is=67718567&hm=9b6e9ae1b64c5df95df8ee515a7f0a8d3cda574a5b33cc9f1c45c5b4219868d1&

https://cdn.discordapp.com/attachments/806454158605418506/1322978135456743455/1.webp?ex=6772d6e7&is=67718567&hm=9b6e9ae1b64c5df95df8ee515a7f0a8d3cda574a5b33cc9f1c45c5b4219868d1&
