### ISSUE TITLE
Automatic Translating | Feature Request 

### ISSUE THREAD

**Issue by Rckke** [mwittrien/BetterDiscordAddons#291]
For example the language you have selected, if a person that talks that language. It auto translates it for you instead of right-clicking it.

I love to have that as an option if possible.

**Comment by mwittrien** [comment]
There is no way to determine a language someone else is is writting in without using gogoles API, automated API requests to Googles API will result in Google banning your IP from being able to use the Translation API after just a few seconds.
So the short answer is no, not possible
