### ISSUE TITLE
[Bug] ServerFolders

### ISSUE THREAD

**Issue by Kederan** [mwittrien/BetterDiscordAddons#293]
**Which plugin is this about?**
ServerFolders

**Describe the Bug**
Close All Folders when selecting a Server does not work with new update

**Expected Behavior**
Before the update you were able to select a server out side of the server folders to close the folder.

**Screenshots**
![2019-10-08_16-02-26](https://user-images.githubusercontent.com/19885815/66429915-0e692600-e9e7-11e9-876d-8fe13fd0dce2.gif)

**Discord Version**
Stable

**Comment by mwittrien** [comment]
Fixed in 6.5.6
