### ISSUE TITLE
[Bug] ServerFolders

### ISSUE THREAD

**Issue by Kederan** [mwittrien/BetterDiscordAddons#294]
**Which plugin is this about?**
ServerFolders

**Describe the Bug**
You are unable to select another server within the server folder. When you do all the servers in the folder disappear.

**Expected Behavior**
Before the update you were able to select servers within the folders without them disappearing. 

**Screenshots**
![2019-10-08_16-01-44](https://user-images.githubusercontent.com/19885815/66430058-5425ee80-e9e7-11e9-85dc-3cc813c88af5.gif)

**Discord Version**
Stable

**Comment by mwittrien** [comment]
What is your settings config for this behaviour, servers are removed when closeAllFolders is enabled, this should shrink the foldecontent down to a width of 0 again tho, works fine in my tests

**Comment by Kederan** [comment]
I disabled my theme and the majority of my plugins to test again. Here is my results and my settings config.

![2019-10-09_06-41-07](https://user-images.githubusercontent.com/19885815/66474790-01d4e400-ea60-11e9-9901-a9a269ae1f65.gif)

![Discord_2019-10-09_06-41-39](https://user-images.githubusercontent.com/19885815/66474795-06999800-ea60-11e9-81bb-19dd50f4e3bc.png)

**Comment by mwittrien** [comment]
Should be fixed in the update
