### ISSUE TITLE
EditUsers not working

### ISSUE THREAD

**Issue by Auron-FFX** [mwittrien/BetterDiscordAddons#299]
today editusers has stopped working properly. seems to launch but doesnt actualy do anything. not experienced with code myself but possably connected to issues others are having with other plugins.

**Comment by abyssnetserver** [comment]
From what I can see it looks to be an issue with a dependency called "BDFDB.js" which has been broken somehow, causing all of DevilBro's plugins to stop functioning.

**Comment by Auron-FFX** [comment]
dang that sucks. hopefuly they fix it soon, i use that plugin alot since rainbow names distract me.

**Comment by SnowyHuskybutt** [comment]
I just made a pull request too about how Server Folders was no longer working, thanks for the info though Abyss. Hopefully he gets it fixed up so his plugins function again as normal!
