### ISSUE TITLE
Pinning Issue

### ISSUE THREAD

**Issue by Ownsin** [mwittrien/BetterDiscordAddons#30]
Hello, there's a bug in the plugin that sometimes whatever I click gets pinned. Even though I have it disabled and remove all the shortcuts for it. It still happens. It literally pins everything I click on chat without even pressing anything. Please check it out! 

Thank you.

**Comment by mwittrien** [comment]
Setting a shortcut to "Single None None" won't disable it, it will trigger the keybind on a single click with no keys pressed

**Comment by mwittrien** [comment]
Added an option to disable keybinds in 1.2.5
