### ISSUE TITLE
Server Folders can't create custom folders

### ISSUE THREAD

**Issue by SnowyHuskybutt** [mwittrien/BetterDiscordAddons#300]
Server Folders appears to have broken and now no longer lets you edit any of the settings tied to the plugin, it's just using default discord folders and I can no longer make custom folder images for them like I used to be able too yesterday.

Update, pretty much every single one of your plugins have stopped working for some reason.

**Comment by Fen1xMonk3y** [comment]
same all plugins no longer working here. i have reinstalled, deleted everything in any directory related to discord/bdd etc with and without admin perms. nothing
