### ISSUE TITLE
[PinDMs] Pin DM in DMs list not working ?

### ISSUE THREAD

**Issue by Glaived** [mwittrien/BetterDiscordAddons#306]
![ScreenToGif](https://user-images.githubusercontent.com/1835170/67099634-9f49b980-f1be-11e9-85c7-6f18f6611cc3.gif)

**Comment by mwittrien** [comment]
Works on my end, might be because you don't have enough DMs not make the list scrollable which shouldnt be an issue, try again when you got more DMs there is no point in pining DMs if you only got 3
