### ISSUE TITLE
How do i change the sounds?

### ISSUE THREAD

**Issue by KittyCatGamersDiscord** [mwittrien/BetterDiscordAddons#31]

**Comment by KittyCatGamersDiscord** [comment]
Please reply how to your readme dosen't really explain

**Comment by KittyCatGamersDiscord** [comment]
Ok i know how to edit it now but eveytime i put in a url this happends 
![image](https://user-images.githubusercontent.com/34783778/34316664-f765ad7e-e7e6-11e7-8c08-fc1c3008adfa.png)

**Comment by mwittrien** [comment]
Use a direct url

**Comment by KittyCatGamersDiscord** [comment]
I have tried that it dose the same

**Comment by mwittrien** [comment]
Contact me on Discord DevilBro#4401
