### ISSUE TITLE
Edit User Plugin - NameColor / TagColor Options Inaccessible 

### ISSUE THREAD

**Issue by BiBi88** [mwittrien/BetterDiscordAddons#312]
![image](https://user-images.githubusercontent.com/47702528/67907649-8c48c900-fb70-11e9-8014-09ac9af7f5bb.png)

The **black text** shown above are the unclickable options that one can't select and thus unable to use the plugin fully. The options saved from previous installations seem to still keep active but any additional things which one would like to add which need to be placed beyond this main page shown below, can not be done. Please help. Thank you.
![image](https://user-images.githubusercontent.com/47702528/67907778-01b49980-fb71-11e9-8128-2af7b8b72013.png)

**Comment by mwittrien** [comment]
fixed
