### ISSUE TITLE
NotificationSounds crashing discord

### ISSUE THREAD

**Issue by ardittristan** [mwittrien/BetterDiscordAddons#313]
since today NotificationSounds has been crashing my discord whenever any notification sound played. I tried reinstalling betterdiscord, disabling all plugins except zerespluginlibrary, lib discord internals and notification sounds, and I tried deleting the notification sounds config, and it still crashed whenever I got a new message notification or even with the sound of deafening/undeafening.

**Comment by 1tim64** [comment]
Same here, Crashing also occurs in Servers when people move and join channels.

**Comment by mwittrien** [comment]
fixed
