### ISSUE TITLE
[Old Title bar] New react rendering doesn't seem to be compatible with themes

### ISSUE THREAD

**Issue by NitroxydeX** [mwittrien/BetterDiscordAddons#316]
The newest update seems to have problems when a theme is used alongside this addon

![image](https://user-images.githubusercontent.com/9305576/68253025-30c28380-0027-11ea-9fae-a7fa98d380fa.png)

I'm using this theme if it does help you track the problem: https://github.com/CapnKitten/Material-Discord

**Comment by mwittrien** [comment]
Tell the theme dev
