### ISSUE TITLE
BDFDB breaking plugin settings page

### ISSUE THREAD

**Issue by Xenorio** [mwittrien/BetterDiscordAddons#317]
Whenever i'm trying to go to the plugin settings page of BetterDiscord it stays completely blank and i get these errors in console: https://ibb.co/cCzNr6B

Versions:
BD: 0.3.2
BBD: 0.2.17
Discord Build: 48470

**Comment by mwittrien** [comment]
move all your plugins out of your plugin folder, reload discord, adn put them in the folder again
