### ISSUE TITLE
Server Folders v5.4.4

### ISSUE THREAD

**Issue by Thewishmaker** [mwittrien/BetterDiscordAddons#32]
I can create folder but I can't make the folder do anything.
For example, the readme says that any servers/guilds below the folder until the next folder/end are automatically in the folder but the mark as read option is always grayed out.
https://i.gyazo.com/a3409541e91d476c8705b14ab5139f0c.png

**Comment by AlexHaber** [comment]
I think the readme needs updating. Here is the plugin description from pluginRepo:

Adds the feature to create folders to organize your servers. Right click a server > 'Serverfolders' > 'Create Server' to create a server. To add servers to a folder hold 'Ctrl' and drag the server onto the folder, this will add the server to the folderlist and hide it in the serverlist. To open a folder click the folder. A folder can only be opened when it has at least one server in it. To remove a server from a folder, open the folder and either right click the server > 'Serverfolders' > 'Remove Server from Folder' or hold 'Del' and click the server in the folderlist.

**Comment by Thewishmaker** [comment]
Thank you very much. That solves all of my issues.
