### ISSUE TITLE
Resize button not properly working on secondary monitor (old title bar plugin)

### ISSUE THREAD

**Issue by edo9300** [mwittrien/BetterDiscordAddons#320]
As the title says, when maximizing the window in my 2nd monitor, the button doesn't update, and keep behaving as the maximize one, instead of resizing the window back to windowed

**Comment by mwittrien** [comment]
the buttons use the native modules to resize/maximize/minimize the window
if its not resitzing properly then the fault is in the native module

**Comment by edo9300** [comment]
> the buttons use the native modules to resize/maximize/minimize the window
> if its not resitzing properly then the fault is in the native module

i don't think it's 100% fault of the native module, here https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/OldTitleBar/OldTitleBar.plugin.js#L269 it's checking for screenX and screenY to be a 0,0, but on a multi monitor setup, that's true only on the first monitor, the others will have the value offetted according to the resolution of the ones next to them
