### ISSUE TITLE
ShowHiddenChannels produces blank space above name and profile picture

### ISSUE THREAD

**Issue by Huddlect** [mwittrien/BetterDiscordAddons#321]
when sorting in native order is active

**Comment by mwittrien** [comment]
where?

**Comment by Huddlect** [comment]
Above your own name and profile picture in the bottom left at the bottom of the channel list. Apparantly it only happens when the channel list is scrolled up as far as possible.

**Comment by mwittrien** [comment]
not for me

**Comment by Huddlect** [comment]
Nevermind, I was too shure of ShowHiddenChannels being the cause because it started happening right after an update of the plugin and therefore didn't verify it by disabling the plugin.

**Comment by Huddlect** [comment]
Ok seems like it actually is the cause. It just persisted after disabling the plugin but disappeared after a restart with the plugin disabled.

**Comment by Huddlect** [comment]
![grafik](https://user-images.githubusercontent.com/47282036/68945847-ab229e80-07b1-11ea-9db8-d8879309dc28.png)
This is how it looks. The size of the blank space varies.

**Comment by BuIlDaLiBlE** [comment]
Can confirm, happens for some servers (not all) for me as well.
This is the most empty space I've ever seen:
![image](https://user-images.githubusercontent.com/12040085/69081525-3c627100-0a4f-11ea-911b-2e4788f53bed.png)
Try one of the official servers, it'll happen there for sure.

**Comment by mwittrien** [comment]
Finally fixed in 2.6.4,
thanks for the hint with the official servers
