### ISSUE TITLE
Duplication of badges

### ISSUE THREAD

**Issue by TheOriginalSeeGreatness** [mwittrien/BetterDiscordAddons#323]
The plugin duplicates badges in the profile menu for a user
it also cuts into a messages
also turning off the plugin it crashes discord, and wont turn off
![Capture](https://user-images.githubusercontent.com/24819269/68964518-ccc25c80-0796-11ea-9934-8f0ce5e57044.PNG)
![Capture](https://user-images.githubusercontent.com/24819269/68964551-e06dc300-0796-11ea-9bcc-8a89bc3667d5.PNG)

**Comment by mwittrien** [comment]
dont use old or outdated versions of the plugin
