### ISSUE TITLE
[IMPROVEMENT] - OldTitleBar Icons too heavy

### ISSUE THREAD

**Issue by RikuKawai** [mwittrien/BetterDiscordAddons#324]
I've just started using OldTitleBar after getting the new update and the new titlebar clashing with my theme. However the icons are weighted too heavily and attempts to adjust their weight didn't look correct.

Icons from plugin
![image](https://user-images.githubusercontent.com/13458480/69261032-d977f380-0b8e-11ea-8b5d-69acc630cdef.png)

Original titlebar icons from Discord
![image](https://user-images.githubusercontent.com/13458480/69261088-f44a6800-0b8e-11ea-9508-d1b40e49a6c5.png)

**Comment by mwittrien** [comment]
thats your personal taste, if you want them to look differently then style them with css

**Comment by RikuKawai** [comment]
No it's not personal taste it's a failed attempt at emulating the old title bar.

**Comment by mwittrien** [comment]
No

Quinlan McNellen <notifications@github.com> schrieb am Sa., 23. Nov. 2019,
21:18:
