### ISSUE TITLE
Bug that overlaps images in image gallery

### ISSUE THREAD

**Issue by briank6932** [mwittrien/BetterDiscordAddons#325]
![image](https://user-images.githubusercontent.com/18603393/69374449-10740500-0c74-11ea-9650-ecb82d835bd8.png)
It's really annoying and makes certain images completely unintelligible

**Comment by mwittrien** [comment]
thats most likely your theme

**Comment by briank6932** [comment]
@mwittrien the same issue occurs when my theme is disabled aswell
![image](https://user-images.githubusercontent.com/18603393/69490416-808db100-0e55-11ea-8da2-cd19908be25b.png)

**Comment by briank6932** [comment]
After testing out plugin combinations the culprit seems to be with [Better Image Popups](https://github.com/Orrielel/BetterDiscordAddons/tree/master/Plugins/BetterImagePopups)
