### ISSUE TITLE
[BUG] - ShowHiddenChannels locks are gone

### ISSUE THREAD

**Issue by Huddlect** [mwittrien/BetterDiscordAddons#327]
**Describe the bug**
The locks next to hidden channels that used to mark hidden channels when sorting hidden channels in the native order is active don't appear anymore

**To Reproduce**
/

**Expected behavior**
Have the locks indicate hidden channel

**Screenshots**
/

**Discord Built (stable, ptb or canary):**
stable

**Additional context**
/

**Comment by Huddlect** [comment]
It seems like they stop appearing when Discord has been running for a while

**Comment by mwittrien** [comment]
appears fine for me even after running discord all day

**Comment by Huddlect** [comment]
also couldn't reproduce it for now. i'll reopen if it happens again
