### ISSUE TITLE
[BUG] - FriendNotfications

### ISSUE THREAD

**Issue by funkytown777** [mwittrien/BetterDiscordAddons#328]
**Describe the bug**
Can no longer add non-friends to the Friend Notification plugin.

No matter what USER ID is put in, error shows up saying "User is already being observed as a 'Non-Friend'."

**To Reproduce**
Try adding new Non-Friend to plugin

**Expected behavior**
Non-friend gets added to notification list.

**Screenshots**
/

**Discord Built (stable, ptb or canary):**
Stable.

**Additional context**
Plugin was working in past. Stopped last week sometime. Already tried full reinstall.

**Comment by mwittrien** [comment]
fixed in new version
