### ISSUE TITLE
[IMPROVEMENT] - PersonalPins

### ISSUE THREAD

**Issue by TheSweetLily** [mwittrien/BetterDiscordAddons#329]
**Describe the solution you'd like**
Would it be possible to expand "PersonalPins" to locally back-up the content as well? 
Could be as simple as copying the text and dumping it into a text file. 

**Describe alternatives you've considered**
Manually copying the text/link over every time. 

**Additional context**
I am just a girl that likes her backups, and since I've started using that plugin a bunch I am kinda worried if it stops working, or my internet drops out for some reason when I really needed something, or the message gets deleted or server dies etc etc.. >~<;;

If too hard to code, then I guess I can manually copy over stuff and do that from now on as well. ^^; 
Don't want to overburden! 

Thank you!

**Comment by mwittrien** [comment]
the contents of the pins are backedup in the PersonalPins.config.json
