### ISSUE TITLE
ImageGallery does not put the main image in front

### ISSUE THREAD

**Issue by jacobmix** [mwittrien/BetterDiscordAddons#330]
**Name**
In which plugin or theme does the bug occur:
__ImageGallery__

**Describe the bug**
A clear and concise description of what the bug is:
The images on the left, and right go over the main one in the middle.

**To Reproduce**
When does the bug occur:
When you brows images in a message with 2 or more images while using the plugin.

**Expected behavior**
A clear and concise description of what you expected to happen:
To let you brows images without the side images getting in the way.

**Screenshots**
If applicable, add screenshots to help explain your problem:
http://prntscr.com/q181zl

**Discord Built (stable, ptb or canary):**
Which built of discord are you using:
Stable "app-0.0.305"

**Additional context**
Image Plugins i use:

> Better Image Popups v1.5.3 by Orrie
> CollapsibleEmbeds v2.1.1 by shtrih
> Direct Media v0.1.0 by samfun123
> ImageGallery v1.6.0 by DevilBro
> ImageToClipboard v0.3.3 by Zerebos
> ResizeX v0.1.2 by Anxeal
> ReverseImageSearch v3.4.8 by DevilBro

Full list of plugins i have installed (Few i have disabled tho):

> 0PluginLibrary.plugin.js
> 1lib_discord_internals.plugin.js
> AutoStartRichPresence.plugin.js
> AvatarIconViewer.plugin.js
> BadgesEverywhere.plugin.js
> BDContextMenu.plugin.js
> BetterEmoteSizes.plugin.js
> BetterImagePopups.plugin.js
> BetterNsfwTag.plugin.js
> BetterReplyer.plugin.js
> BetterSearchPage.plugin.js
> BotsMutualGuilds.plugin.js
> changingBackground.plugin.js
> CharCounter.plugin.js
> CheckAllPluginsButton.plugin.js
> Citador.plugin.js
> clock.plugin.js
> CollapsibleEmbeds.plugin.js
> copyCode.plugin.js
> dateViewer.plugin.js
> DeveloperUtils.plugin.js
> directMedia.plugin.js
> DiscordCakeDay.plugin.js
> discordexperiments.plugin.js
> DiscordLogger.plugin.js
> DoNotTrack.plugin.js
> EmoteBlacklistRedux.plugin.js
> emoteSorter.plugin.js
> FriendNotifications.plugin.js
> full_offline_list.plugin.js
> GuildAndFriendRemovalAlerts.plugin.js
> HorizontalCodeScroll.plugin.js
> ImageGallery.plugin.js
> ImageToClipboard.plugin.js
> KawaiiEmotes.plugin.js
> lazyload_patcher.plugin.js
> LineNumbers.plugin.js
> LineNumbersRedux.plugin.js
> localFileServer.plugin.js
> mediaSupport.plugin.js
> messageTimestamps.plugin.js
> OwnerTag.plugin.js
> PermissionsViewer.plugin.js
> PinPluginsAndThemes.plugin.js
> PluginRepo.plugin.js
> RepoControls.plugin.js
> RepoUtils.plugin.js
> ResizableCSS.plugin.js
> ResizeX.plugin.js
> restartNoMore.plugin.js
> ReverseImageSearch.plugin.js
> SendBDEmotes.plugin.js
> SendButton.plugin.js
> SendLargeMessages.plugin.js
> serverscreenshare.plugin.js
> serverTheme.plugin.js
> ShowHiddenChannels.plugin.js
> ShowImageDetails.plugin.js
> SilentTyping.plugin.js
> SpellCheck.plugin.js
> SteamProfileLink.plugin.js
> suppressmentions.plugin.js
> ThemeCustomizer.plugin.js
> ThemeRepo.plugin.js
> VoiceChatNotifications.plugin.js
>

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/69499721-9baffd80-0ef5-11ea-997a-d69e146df426.png)

does fine for me, if its another plugin causing the issue, then it's outside of my responsebility
