### ISSUE TITLE
[FEATURE] - Dynamic Statuses

### ISSUE THREAD

**Issue by ImSkully** [mwittrien/BetterDiscordAddons#331]
**Feature Request - Dynamic Statuses**
Would love to have a plugin which takes advantage of the new Discord Status feature, the plugin can consist of a few simple settings in the plugins settings context or a pop-up modal style settings interface which allows you to input two different statuses (or more than two!) and an interval.

The plugin that handles switching the user's Discord status between the provided prewritten statuses in the provided interval.

The overall feature of this plugin would be changing the user's status automatically at a set interval.

**Comment by mwittrien** [comment]
My issue section isnt a place to request new plugins
And no a dynamic status plugin would not be allowed, statuses use the API and anything that interacts with the API in such a way would be banned by our BD policies due to high API traffic and the possibility to get banned from using it
