### ISSUE TITLE
[IMPROVEMENT] - TopRolesEverywhere v2.9.3

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [mwittrien/BetterDiscordAddons#332]
**Describe the solution you'd like**
Please allow an option that ignores, where if the highest role is colorless, and you have colorless roles turned off, that the role displayed is the next highest colored role.

**Describe alternatives you've considered**
Essentially, "Displayed role defaults to highest colored role" 

**Additional context**
I'm an admin on a school server and my admin role is color less. This makes it weird for when admins and mods speak, cause nothing appears next to them.

**Comment by mwittrien** [comment]
Done
