### ISSUE TITLE
[BUG] ShowHiddenChannels channels inaccessible after permissions were granted

### ISSUE THREAD

**Issue by Huddlect** [mwittrien/BetterDiscordAddons#333]
**Describe the bug**
ShowHiddenChannels won't allow you to access channels for which you have just been granted the permission without switching the server when sorting in native order is active.

**To Reproduce**
View a server while another account grants permissions for previously hidden channels to the first account.

**Expected behavior**
The channels should be accessible without switching the server.

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Fixed in 2.6.6
