### ISSUE TITLE
[BUG] - serverfolder

### ISSUE THREAD

**Issue by d3athrow** [mwittrien/BetterDiscordAddons#335]
**Describe the bug**
Servers in a server folder that have enough boosts for an animated server picture but don't end up going blank on mouse hover and require multiple clicks sometimes to properly select the server

**To Reproduce**
Be in a server that is boosted to level 1 but does not have an animated server pic and try to click on it.

**Expected behavior**
Static image and it selects fine.

**Screenshots**
[webm](http://game.ss13.moe/uploads/2019-12-03_00-23-42.webm)

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Fixed in my library, a reload should make the fix noticeable

**Comment by d3athrow** [comment]
Thanks is fixed.
