### ISSUE TITLE
[IMPROVEMENT] - GoogleTranslateOption - Alternative API Suggestion

### ISSUE THREAD

**Issue by BannerBomb** [mwittrien/BetterDiscordAddons#336]
**Describe the solution you'd like**
If you would like a way better alternative to google's translation services that will allow the GoogleTranslateOption plugin to be much faster and much much more accurate than google's translating service then you should give iTranslate a try. iTranslate is always my first choice when it comes to translations, because it's usually always on point with its translations. Although they do not have a public API, you can get the [iTranslate WebApp](http://www.itranslate.com/app "iTranslate") API Key from filtering through it's JavaScript file (the api key is hardcoded and I assume changes whenever the developers generate a new key to use for the webapp so just in case I would send a `GET` request to the JavaScript and filter to find the currently set API key) and use it to send a `POST` request to their translation API. I have included an example of how you can use this method to get translations from their API. I have used [Axios](https://npmjs.com/axios "Axios") to demonstrate the example for getting the translations below.

As side notes the max input text length for this api is currently 1,000 and currently support the following languages `['sq', 'ar', 'bs', 'bg', 'zh-CN', 'zh-TW', 'hr', 'cs', 'da', 'nl', 'en', 'et', 'fi', 'fr', 'de', 'el', 'he', 'hi', 'hu', 'is', 'id', 'it', 'ja', 'ko', 'lv', 'lt', 'mk', 'ms', 'no', 'fa', 'pl', 'pt-BR', 'pt-PT', 'ro', 'ru', 'sr', 'sk', 'sl', 'es', 'sv', 'th', 'tr', 'vi']` **you may also set the input language to `auto` to automatically detect the input language.**

**Describe alternatives you've considered**
`none`

**Additional context**
```js
const axios = require("axios");
// var textlimit = 1000; // the max input length is 1000 characters
/*
	supported input/output languages at this time include:
	['sq', 'ar', 'bs', 'bg', 'zh-CN', 'zh-TW', 'hr', 'cs', 'da', 'nl', 'en', 'et', 'fi', 'fr', 'de', 'el', 'he', 'hi', 'hu', 'is', 'id', 'it', 'ja', 'ko', 'lv', 'lt', 'mk', 'ms', 'no', 'fa', 'pl', 'pt-BR', 'pt-PT', 'ro', 'ru', 'sr', 'sk', 'sl', 'es', 'sv', 'th', 'tr', 'vi']
*/
const js = (await axios.get('https://www.itranslate.com/themes/itranslate2016/assets/webapp/js/main.js')).data;
const api_key = js.match(/var API_KEY = "(.+)"/);
await axios({
	method: 'POST',
	timeout: 60000,
	url: 'https://api.itranslate.com/translate/v1',
	headers: {
		"Accept": "application/json",
		"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
	},
	data: {
		"key": api_key[1],
		"source": {
			"dialect": "auto", // input text language
			"text": "hi" // input text (just so you know the input text can also be full sentences.
		},
		"target": {
			"dialect": "es" // output text language
		}
	}
})
```
The resulting resource output will be in the format of
```js
{
	"source": {
		"detected": "en", // this is only present if the dialect for the input language was set to `auto`
		"dialect": "auto",
		"text": "hi"
	},
	"target": {
		"dialect": "es",
		"text": "Hola"
	},
	"times": {
		"total_time": 0.024 // how long the translation took
	}
}
```

**Comment by mwittrien** [comment]
Integrated, will soon be pushed as an update

**Comment by BannerBomb** [comment]
Thanks, and yea iTranslate I have installed on my iPhone as a keyboard that translates messages as you type. I used to play with it and send messages to my uncle since he knows french and he would make sure the translations were good, anytime I did this it was always at least 95% to 100% correct all the time which is why I suggested iTranslate.
