### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/EditUsers

### ISSUE THREAD

**Issue by Reinbowsaur** [mwittrien/BetterDiscordAddons#337]
**Describe the solution you'd like**
Addition of the option to apply a custom status/hide users statuses/hide gameplay presence for particular users for whatever reason. Mainly statuses can be annoying/problematic people/spoiling movies in a few cases for me.

**Describe alternatives you've considered**
Blocking the person.
Asking the person to change their status.

**Additional context**
With the recent addition with custom statuses, it makes sense for this addon to eventually allow customization of users statuses aswell. I have found myself being spoiled for a movie a few times "x dies hahaha" very random stuff which can be annoying. Thanks for reading.

**Comment by mwittrien** [comment]
added
