### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by BannerBomb** [mwittrien/BetterDiscordAddons#338]
**Describe the bug**
You might want to filter out mentions from iTranslate otherwise it gives an incorrect translation.

**To Reproduce**
Type a message with a mention (any mention will work and provide the same output translation) in it example `@BannerBomb this is a test message` will translate to `a0_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _` some other languages will fail to translate if there is a mention.

**Expected behavior**
It was expected to not attempt to translate the mention because this removes the mention from the translation and breaks the output translation.

**Screenshots**
![image](https://user-images.githubusercontent.com/11788894/70566940-fb97dc80-1b62-11ea-8a9c-e49eeefada07.png)
![image](https://user-images.githubusercontent.com/11788894/70566963-03f01780-1b63-11ea-9179-c2192e45b9b2.png)

**Discord Built (stable, ptb or canary):**
`Stable`

**Additional context**
`none`

**Comment by mwittrien** [comment]
not really a bug with the plugin and more an issue with iTranslates way of simply removing placeholders from a text to be translated,
i kinda fixed it by forcefully readding mentions and stuff that wasnt properly readded after translation
