### ISSUE TITLE
[BUG] - OldTitleBar

### ISSUE THREAD

**Issue by BlancBestGirl** [mwittrien/BetterDiscordAddons#339]
**Describe the bug**
When OldTitleBar 1.6.3 loads, discord freezes

**To Reproduce**
load oldtitlebar 

**Expected behavior**
discord not to crash

Stable

**Additional context**
OldTitleBar is the only thing that freezes discord

**Comment by mwittrien** [comment]
Fixed, enable the plugin again and download the update
