### ISSUE TITLE
[IMPROVEMENT] - THEME/BasicBackground

### ISSUE THREAD

**Issue by ChrisopherU08** [mwittrien/BetterDiscordAddons#340]
**Describe the solution you'd like**
 Would it be possible to add a customization option of some degree for mention/ping text or backgrounds?

**Describe alternatives you've considered**
For example a possible ability to set the color or change the background "box" color/transparency around mentions against the background.

**Additional context**
Although these mentions are not hard to see at all, they blend into all other text for the most part, making it hard to differentiate the two weather it is normal text or an actual mention of some kind.
![Example](https://user-images.githubusercontent.com/47951950/70856227-b3dbc280-1e8c-11ea-920d-e89a5325e820.PNG)

**Comment by mwittrien** [comment]
change it yourself with custom css
