### ISSUE TITLE
[BUG] - Spellcheck

### ISSUE THREAD

**Issue by ryaniskira** [mwittrien/BetterDiscordAddons#345]
**Describe the bug**
The plugin just flat out doesn't work at all, it's as if I don't have the plugin installed at all. The only indication that it is installed is a popup about the english dictonary on Discord startup. I don't know how to better describe it so a screenshot is provided below.

**To Reproduce**
?

**Expected behavior**
For misspelled words to be underlined and the right click menu option to suggest correct spelling to return.

**Screenshots**
[No right click option to spell check on misspelled word](https://postimg.cc/R6bmRS1R)

**Discord Built (stable, ptb or canary):**
[Stable](https://www.archlinux.org/packages/community/x86_64/discord/)

**Additional context**

**Comment by mwittrien** [comment]
Yes because it's broken right now due to the new chattextbar its on my to do list on my server
