### ISSUE TITLE
[BUG] - PluginRepo Stuck at 149/189 (Loading Plugins) & Promise Error

### ISSUE THREAD

**Issue by explasion** [mwittrien/BetterDiscordAddons#346]
**Describe the bug**
When loading, PluginRepo.plugin.js gets stuck loading at 149/189. (See Screenshot 1)
When stuck as above PluginRepo.plugin.js throws a Promise Error. (See Screenshot 2)

**To Reproduce**
Always occurs, resulting in unsuccessful load of Plugins.

**Expected behavior**
Plugin Loaded >> Loading Plugins >> Finished >> Possible "Plugins Outdated Please Update."

**Screenshots**
Screenshot 1: https://puu.sh/ERi28/ccce5a64d5.png
Screenshot 2: https://puu.sh/ERhT0/b94123c56b.png

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
PluginRepo.plugin.js version: 1.8.7

**Comment by mwittrien** [comment]
fixed
