### ISSUE TITLE
[BUG] - GoogleTranslateOption (Error)

### ISSUE THREAD

**Issue by BannerBomb** [mwittrien/BetterDiscordAddons#347]
**Describe the bug**
When attempting to translate with the iTranslate engine all it does is output the error `DFDB.NotificationUtils.toast("Failed to translate text. Translation Server is down or API-key outdated. Try another Translate Engine.", {type:"error"});`

**To Reproduce**
When does the bug occur.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11788894/71264733-b9b12800-2312-11ea-91a8-402cd7ed7576.png)

**Discord Built (stable, ptb or canary):**
`Stable`

**Additional context**

**Comment by mwittrien** [comment]
well due, because 
https://web-api.itranslateapp.com/v3/texts/translate
 returns a server error

**Comment by BannerBomb** [comment]
it seems to be working perfectly fine with axios when I tested it https://runkit.com/embed/ocrt8980fdkh. But then if I test it with BDFDB.LibraryRequires.request it returns the server error :man_shrugging:

**Comment by mwittrien** [comment]
well discord has no axios
