### ISSUE TITLE
[BUG] - BasicBackground - Server icons disappearing under certain conditions

### ISSUE THREAD

**Issue by aCluelessDanny** [mwittrien/BetterDiscordAddons#348]
**Describe the bug**
Sometimes (in a seemingly random manner), the server icons disappear (and reappear) in a weird way when certain hover events happen. It also seems to act differently when on the Home page or on a server.

**To Reproduce**
Open up Discord & hover over and away from the server icons

**Expected behavior**
Server icons remain visible and behave normally

**Screenshots**
![servers](https://user-images.githubusercontent.com/21282515/71292280-90f05900-2339-11ea-9aa4-e0aacb1dbb6f.gif)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
When in a server, hovering above the home icon causes some or all of the server icons to disappear. And on the other hand, when in the home page, some or all the icons are invisible until you hover over them (but then disappear after a small period of time hovering). The gif above explains it better than I can type it.
Oddly enough, going into full screen fixes this, but toggling Dev Tools when on full screen makes the problem appear again.

**Comment by mwittrien** [comment]
BasicBackground doesn't change anything related to opacity/visibility of server icons, so it's most likely something else causing the issue for you when BasicBackground is enabled

**Comment by aCluelessDanny** [comment]
Odd, when I toggle off BasicBackground, the problem goes away and vice-versa (I have no other theme enabled other than BlurpleRecolor). I'll try looking into what else could be causing this
