### ISSUE TITLE
[BUG] - PLUGIN/ServerFolders

### ISSUE THREAD

**Issue by Norveftch** [mwittrien/BetterDiscordAddons#349]
**Describe the bug**
After leaving all servers inside of a folder, Discord constantly crashes.

**To Reproduce**
The bug occurs when you leave all servers inside of a folder while the folder is opened, causing discord to crash.

**Expected behavior**
When leaving the servers, I expected the folder to delete itself and Discord to continue working normally.

**Screenshots**
![Discord_Y0N67gG1jX](https://user-images.githubusercontent.com/54639034/71326392-4fda7f00-24c8-11ea-8137-ce8952bdeec7.png)
![KBXiSjRcfc](https://user-images.githubusercontent.com/54639034/71326398-7698b580-24c8-11ea-88f8-59da6114d15a.gif)

**Discord Built (stable, ptb or canary):**
I am using the **Stable** build of Discord.

**Additional context**
As far as I'm aware, all there is to it is leaving all servers inside of a specific folder while it's opened.

Edit at 14:52 - After deleting the plugin from the BetterDiscord folder and re-installing it, it works again. But I fear that if you leave servers directly from the folder before deleting the folder will still cause Discord to crash.

_Plugins I have installed are:

SendLargeMessages
FriendNotifications
LastMessageDate
Citador
ServerFolders
TopRoleEverywhere
CreationDate
OwnerTag
BetterSearchPage
BadgesEverywhere
ReadAllNotificationsButton
CompleteTimestamps
ImageZoom
BetterFriendCount
GuildAndFreindRemovalAlerts
EditUsers
0PluginLibrary
GuildCounter
ViewGuildRelationships
WordNotifications
UserBirthdays
LineNumbers
RemoveMinimumSize
ReplySystem
MentionAliases
BetterRoleColors
DiscordCakeDay
ImageToClipboard
Quicksave
HideDisabledEmojis
CharacterCounter_

I am unsure if these have anything to do with Discord crashing.

**Comment by mwittrien** [comment]
has been fixed in an unversioned patch some days ago, redownload the plugin if you want it fixed
