### ISSUE TITLE
Add some search engines 

### ISSUE THREAD

**Issue by ObserverOfTime** [mwittrien/BetterDiscordAddons#35]
I believe GoogleSearchReplace could use a few more search engines:

`Qwant:  {value:true,  name:"Qwant",  url:"https://www.qwant.com/?t=all&q=" + this.textUrlReplaceString}`

`Searx:  {value:true,  name:"Searx",  url:"https://searx.me/?q=" + this.textUrlReplaceString}`

`YouTube:  {value:true,  name:"YouTube",  url:"https://www.youtube.com/results?q=" + this.textUrlReplaceString}`

**Comment by mwittrien** [comment]
Added
