### ISSUE TITLE
[BUG] - PLUGIN/RepoControls: searching bar not working

### ISSUE THREAD

**Issue by CubicFace** [mwittrien/BetterDiscordAddons#350]
**Describe the bug**
When trying to search plugins,  set order type or sortkey, it does nothing. (except Enable/Disable all buttons)

**To Reproduce**
Type in the search bar, click the sortkey or order type menu.

**Expected behavior**
When typing in the search bar: show plugins/theme matching the keyword typed.
When choosing sortkey or order type: shows a "context menu" to choose which optioI want.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39100084/71384781-94a70880-25e3-11ea-945b-0415fc16be86.gif)

**Discord Built (stable, ptb or canary):**
Using latest stable (at the moment I'm writing this issue)

**Additional context**
Using Midnight UI v.2.6.2 (by Tropical), I have a lot of plugins, otherwise I have no additional context.

**Comment by mwittrien** [comment]
Works fine for me make sure you are using the most recent version (1.3.3)

**Comment by CubicFace** [comment]
![image](https://user-images.githubusercontent.com/39100084/71697085-2b7b7e00-2db7-11ea-9696-116df1825d9b.png)
So it's either my theme is the problem, one or multiple plugins are conflicting with RepoControls, or my whole BetterDiscord is damaged.
