### ISSUE TITLE
[IMPROVEMENT] - better friend count should show numbers past 1k

### ISSUE THREAD

**Issue by MastaNub** [mwittrien/BetterDiscordAddons#351]
**Describe the solution you'd like**
Pretty much it just shows 1k+ instead of the actual number for friends. I wanna see the actual number.

**Describe alternatives you've considered**
Make it an option.

**Comment by jack652** [comment]
Agreed that's a good idea

**Comment by mwittrien** [comment]
it uses discords native numberbadge component. and discord doesn't display full 4 digit numbers in the numberbadge
