### ISSUE TITLE
[BUG] - EditServers no Banner image

### ISSUE THREAD

**Issue by Trixlight** [mwittrien/BetterDiscordAddons#352]
**Describe the bug**
There is no banner image in the Guild sidebar unless the server has a native one (from Nitro Boost).
If this is a server with Nitro Boost and it has a banner, you can change or delete it.

**To Reproduce**
Update plugin to v2.1.3 or later
[commit from December 1] 
[https://github.com/mwittrien/BetterDiscordAddons/commit/a5d59ee087dc5ca5f75d2a878942fd0b9da69bdd#diff-848ce7df65d650c1e10d3b76232e206e](https://github.com/mwittrien/BetterDiscordAddons/commit/a5d59ee087dc5ca5f75d2a878942fd0b9da69bdd#diff-848ce7df65d650c1e10d3b76232e206e)

**Expected behavior**
Banner picture in the Guild sidebar on servers w/o Nitro Boost.

**Screenshots**
Server with Nitro Boost
![image](https://user-images.githubusercontent.com/33410668/71586912-94f05800-2b3d-11ea-87f8-36627713a896.png)
w/o
![image](https://user-images.githubusercontent.com/33410668/71586793-3a56fc00-2b3d-11ea-99b9-b38996e684e7.png)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Expected this block, but it's missing.
![image](https://user-images.githubusercontent.com/33410668/71587344-1eecf080-2b3f-11ea-824a-df9d776d86d6.png)
No errors in console related to EditServers.plugin.js
I'm a noob in JS, can't identify the problem for you.
Maybe just a typo.

**Comment by mwittrien** [comment]
fixed
