### ISSUE TITLE
[BUG] - OwnerTag

### ISSUE THREAD

**Issue by 13ace37** [mwittrien/BetterDiscordAddons#353]
**Describe the bug**
The Owner Tag is still showing for mutual friends after clicking on them.

**To Reproduce**
Click on the guild owner's profile and navigate to the "Mutual Friends" tab. After that click on one of the mutual friends listed below. After that, the tag is still there even if the user has no admin.

**Expected behavior**
The tag should disappear if you leave the owner's/admin's profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/29045525/71786265-d84d3980-3009-11ea-8d26-33cbb52664bf.png)
![image](https://user-images.githubusercontent.com/29045525/71786275-ef8c2700-3009-11ea-8d39-a677d1bd6c6b.png)

**Discord Built (stable)**
DB v0.3.2 | BBD v0.2.19 | OwnerTag v1.2.3

**Comment by mwittrien** [comment]
fixed
