### ISSUE TITLE
[BUG] - ShowHiddenChannels crashing

### ISSUE THREAD

**Issue by MozarteanChaos** [mwittrien/BetterDiscordAddons#354]
**Describe the bug**
When the ShowHiddenChannels plugin is enabled, right-clicking the text box (to spell-check your message in advance, for example) crashes Discord.

**To Reproduce**
1. Download and enable ShowHiddenChannels
2. Right-click the text box you use to send messages
3. Discord will crash

**Expected behavior**
Discord will not crash, and I will be able to spell-check, copy+paste, etc. freely.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
All of my other active plugins cause no issues.

As nobody else has reported this, it may be on my end. Thought I'd say something just in case.

**Comment by mwittrien** [comment]
Either only happens to you or happens because of a plugin conflict.
Doesn't happen to me, the plugin doesn't even interact with the contextmenu.
