### ISSUE TITLE
[BUG] - Edit Users / Doesnt edit name in Text Area

### ISSUE THREAD

**Issue by Nathidraws** [mwittrien/BetterDiscordAddons#355]
**Describe the bug**
Doesnt edit name in the Text Area (Where messages are sent).
It used to work perfectly, and still changes the name everywhere else, other than there...

**Expected behavior**
Change colour or name in text area.

**Screenshots**
![image](https://user-images.githubusercontent.com/34476257/73596632-cd5bcb00-451b-11ea-9bf5-7e73f717fe1a.png)
![image](https://user-images.githubusercontent.com/34476257/73596644-e5cbe580-451b-11ea-8a38-430cef57d569.png)

**Discord Built (stable, ptb or canary):**
Ptb 53736 (fd644dc)

**Comment by Nathidraws** [comment]
I might try it on the default discord instead of the ptb.

**Comment by mwittrien** [comment]
it is known, due to the message update, these bugs won't be fixed till the update hits stable
