### ISSUE TITLE
[BUG] - PLUGIN/EditUsers

### ISSUE THREAD

**Issue by cinabrese** [mwittrien/BetterDiscordAddons#360]
**Describe the bug**
Running EditUsers causes interference with certain bots (Tupperbox). All instances of Tupperbox appear the same instead of whatever has been called.

**To Reproduce**
Use Tupperbox bot while EditUsers is running.

**Expected behavior**
No interference between the bot and EditUsers.

**Screenshots**

Without EditUsers running:
![image](https://user-images.githubusercontent.com/60265678/74091193-f1229200-4a82-11ea-8ad6-5fd27a3260a2.png)

With EditUsers running:
![image](https://user-images.githubusercontent.com/60265678/74091169-b6205e80-4a82-11ea-9e87-d60ecb6b1ba4.png)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
The interference began after EditUsers was update to 3.7.0; had no issues with previous versions. Uncertain of what may be interacting with what to cause this issue?

**Comment by mwittrien** [comment]
Fxed in 3.7.4
