### ISSUE TITLE
[BUG] - ShowImageDetails

### ISSUE THREAD

**Issue by river58** [mwittrien/BetterDiscordAddons#361]
**Describe the bug**
Clicking on the link above the image does not direct me to the link, instead, it seems to be an about: link, checking in Inspect Element seems to show that it does not have a link at all, it is just an <a> tag without an href.

**To Reproduce**
1. Send an image in a chat.
2. Click the image name.

**Expected behavior**
It should open up the image in your preferred browser.

**Screenshots**
https://i.imgur.com/z32QilE.png

https://i.imgur.com/YP3MZB4.png

**Discord Built (stable, ptb or canary):**
Stable 54177

**Additional context**

**Comment by mwittrien** [comment]
fixed in 1.2.9
