### ISSUE TITLE
[BUG] BetterNsfwTag position

### ISSUE THREAD

**Issue by Trixlight** [mwittrien/BetterDiscordAddons#362]
**Describe the bug**
The NSFW tag is added before "Create Invite" and "Edit Channel" buttons.

**To Reproduce**
Hover over or select the channel with the NSFW tag.

**Expected behavior**
The NSFW tag stays on the right when you hover over or select the channel.
Similar to the "@mention" icon.

**Screenshots**
![2020-02-12_04-51-11](https://user-images.githubusercontent.com/33410668/74290385-80fe5f80-4d53-11ea-80c4-d10152d0c414.gif)

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
changed
