### ISSUE TITLE
[BUG] - Friend Notification, Friends-list chooser

### ISSUE THREAD

**Issue by Auvere** [mwittrien/BetterDiscordAddons#368]
The plugin lags and hangs like crazy due to the sheer amount of friends that I have (2,384)
It eventually loaded, but changing settings also makes it lag, so I can't realistically set anything for all users.

**To Reproduce**
Have a lot of friends

**Expected behavior**
Compact a list or have filters beyond a certain amount, maybe 100. There is only a few friends I'd like to track.

**Discord Built (stable, ptb or canary):**
Stable 55068 (de98cf1)

**Additional context**
A bulk select or select all would also be nice. The list is also not sorted alphabetically, so it is very difficult to find a user.

**Comment by mwittrien** [comment]
How about not having 2000+ friends
