### ISSUE TITLE
[BUG] [BasicBackground] - Avatars are not being displayed in the message area.

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#369]
**Describe the bug**
In the message area, next to the messages of users, avatars do not display at all.

**To Reproduce**
Having BasicBackground enabled in any area that contains messages.

**Expected behavior**
The avatars next to messages to be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/17354045/75569970-12591b80-5a4e-11ea-8123-9d96b3fe9e40.png)

**Discord Built (stable, ptb or canary):**
Stable 55236 (52bd1b8)

**Additional context**
Host 0.0.306
Windows 10 64-Bit (10.0.14393)

**Comment by mwittrien** [comment]
fixed
