### ISSUE TITLE
[BUG] [BasicBackground] - Avatars inside messages

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#374]
**Describe the bug**
Avatars are pushed into the messages, overlaying part of the message.

**To Reproduce**
Have BasicBackground enabled.

**Expected behavior**
The avatars to appear in their usual place: to the left of the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/17354045/75607021-c7411600-5aea-11ea-8b0e-5c3cfbfb02a8.png)

**Discord Built (stable, ptb or canary):**
Stable 55393 (b3019e6)

**Additional context**
Host 0.0.306
Windows 10 64-Bit (10.0.14393)

**Comment by mwittrien** [comment]
tested in stable and tested on canary, not the case for me

**Comment by TheDarkBomber** [comment]
This is still a clear issue, the only solution to this is to disable BasicBackground.

**Comment by mwittrien** [comment]
As i said i tested it on stable and canary, both up to date

The issue no longer exists, so either your discord is outdated or some other css is screwing it up
