### ISSUE TITLE
[BUG] [BasicBackground] - Avatars still inside messages

### ISSUE THREAD

**Issue by TheDarkBomber** [mwittrien/BetterDiscordAddons#375]
**Describe the bug**
Avatars are pushed into the messages, overlaying part of the message.

**To Reproduce**
Have BasicBackground enabled.

**Expected behavior**
The avatars to appear in their usual place: to the left of the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/17354045/75613429-8e726280-5b25-11ea-8cd4-01ee3cb3d098.png)
![image](https://user-images.githubusercontent.com/17354045/75613484-21130180-5b26-11ea-9609-308e96f0af5a.png)

**Discord Built (stable, ptb or canary):**
Stable 55393 (b3019e6) - ***The latest version of Discord.***

**Additional Context**
I have tested each theme and custom CSS. This issue is only present with BasicBackground. I have the latest version of Discord and it is still a persistent issue. Please rectify this issue.

**Comment by TheDarkBomber** [comment]
**UPDATE**
Looking at the fix for the timestamp location, I have found and tried a test which resolves this issue. I will submit a PR accordingly.

**Comment by mwittrien** [comment]
The issue isn't BasicBackground, it's the fact that you are either using an additional theme next to BasicBackground or you are using some CustomCSS that also changes the avatars
Like i said before, I have tested it on both canary and stable and the issue is not present
