### ISSUE TITLE
[BUG] - ChatAlias

### ISSUE THREAD

**Issue by rocky1928** [mwittrien/BetterDiscordAddons#378]
**Describe the bug**
ChatAlias refuses to add any new images and does not send old images due to an [object HTMLDivElement] error. No response from plugin when turned on either.

**To Reproduce**
1. Go to ChatAlias plugin settings.
2. Open settings for ChatAlias.
3. Create new alias.
4. Enter alias text. (This works)
5. Enter alias image. (This sends to [object HTMLDivElement] error and does not save)

**Expected behavior**
Expected behavior is plugin to save alias and to function properly (replacing text with image when sending messages)

**Screenshots**
![image](https://user-images.githubusercontent.com/43506958/75693225-a5739a80-5c74-11ea-9900-ea0e949145cd.png)
Entering Chat Alias Settings page.
![image](https://user-images.githubusercontent.com/43506958/75693264-b1f7f300-5c74-11ea-984a-3bcb6c39646c.png)
Creating new Alias.
![image](https://user-images.githubusercontent.com/43506958/75693509-04391400-5c75-11ea-9093-707f024a6dde.png)
Error when uploading image via browsing.

Note: added a filepath as a plugin without specifying file type then manually changed the replacement to a filepath.
![image](https://user-images.githubusercontent.com/43506958/75693725-609c3380-5c75-11ea-9e9c-7b6389d58151.png)
Changed to file.
![image](https://user-images.githubusercontent.com/43506958/75693779-7ad61180-5c75-11ea-974a-6535700c148d.png)
Response sent before specifying filepath and then after filepath. :XD: is replacement text.

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Having additional [object HTMLDivElement] errors randomly as well, will report in a separate issue report. Updated chatalias.plugin.js, BDFDB.js, and BDFDB.min.js to try and solve this on my own—I failed.

**Comment by mwittrien** [comment]
Works fine for me, the HTMLDivError is caused by another plugin which tries to refresh the settingspanel no clue what it was called, but it's heavily outdated and not needed anymore
