### ISSUE TITLE
[BUG] - PLUGIN/CompleteTimestamp

### ISSUE THREAD

**Issue by kevinsujanto** [mwittrien/BetterDiscordAddons#380]
**Describe the bug**
In the screenshot, the complete timestamp only appears in the embeds, not in the discord timestamp.

**To Reproduce**
Everytime.

**Expected behavior**
The discord timestamp should also be complete, as it is complete when ran on MacOS Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/32500262/75928267-06010400-5e3c-11ea-9819-fb0b95821130.png)

**Comment by mwittrien** [comment]
Issue was a plugin conflict
