### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by JohnWeak1** [mwittrien/BetterDiscordAddons#382]
**Describe the bug**
Still hear @here and @everyone notification while @here and @everyone are supressed in the server notification settings

**To Reproduce**
when someone does a @here or @everyone while ping is suppresed

**Expected behavior**
expect to have no @here/@everyone notification on servers where @here/@everyone is suppressed

**Screenshots**
no screenshots can explain this (since its sound related)

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Fixed
