### ISSUE TITLE
[IMPROVEMENT] - friendnotifications

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#383]
**Describe the solution you'd like**
a way to moove where the toast notifications shows up

**Describe alternatives you've considered**
either being able to choose anywhere on the screen or just left/right/up/down

**Additional context**
it's annoying when you're trying to read a message but toast notifications keep showing up and block you from reading a part of the message

**Comment by mwittrien** [comment]
switch to desktop notifications then
toasts use the BBD native toast element, you can change the position with css if you dont like it
