### ISSUE TITLE
Unable to parse Meta

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [mwittrien/BetterDiscordAddons#388]
When trying to add this to Better Discord i just get a unable to Parse Meta: Compilation Failed Error

**Comment by mwittrien** [comment]
Then you didn't download them correctl or downloaded an empty file

**Comment by DeinAlbtraumTV** [comment]
I didn't download an empty file and i am pretty sure i downloaded it correctly, i directly got it from the Better Discord Hub.
