### ISSUE TITLE
[BUG] - ForceImagePreviews

### ISSUE THREAD

**Issue by DesertSnak3** [mwittrien/BetterDiscordAddons#389]
**Describe the bug**
All YouTube links duplicate the video

**To Reproduce**
When a YouTube link embeds the video

**Expected behavior**
A single embedded YouTube Preview

**Discord Built (stable, ptb or canary):**
Stable 55808 (c5e3ef1)

![Discord_aJIkpI5oYD](https://user-images.githubusercontent.com/49217115/76800985-d03f2080-6828-11ea-95b0-0c5c162f6d6c.png)

**Comment by mwittrien** [comment]
fixed
