### ISSUE TITLE
SeverFolders - Notify Status of the folder not updating

### ISSUE THREAD

**Issue by marcussacana** [mwittrien/BetterDiscordAddons#39]
After Read all notifications of all servers the folder don't update the status.
![https://comfy.moe/lsdvtx.png](https://comfy.moe/lsdvtx.png)

And also, thanks for adding the feature that I requested in that other issue.

**Comment by mwittrien** [comment]
Are you sure it wasn't a one time thing? Tried it several times and it always updated it.
Also what's your plugin version and what type of Discord are u using (stable, canary, ptb)

**Comment by marcussacana** [comment]
Yep, continue the problem, i'm using the zere's fork
![https://comfy.moe/wcmaww.gif](https://comfy.moe/wcmaww.gif)

my settings:
![https://comfy.moe/uttxai.png](https://comfy.moe/uttxai.png)
![https://comfy.moe/ykchoi.png](https://comfy.moe/ykchoi.png)

my plugins:
![https://comfy.moe/gfwodc.png](https://comfy.moe/gfwodc.png)

BD Version:
![https://comfy.moe/oasoii.png](https://comfy.moe/oasoii.png)


Maybe this a problem with my theme? just in case this is the status of the folder in the element inspector:
![https://comfy.moe/rmxwyt.png](https://comfy.moe/rmxwyt.png)

**Comment by mwittrien** [comment]
You could try disabling your theme and check if it works, settings should be fine and other plugins shouldn't be a problem

**Comment by marcussacana** [comment]
looks isn't problem of the theme
![https://comfy.moe/syryjd.png](https://comfy.moe/syryjd.png)
