### ISSUE TITLE
[IMPROVEMENT] - CustomQuoter

### ISSUE THREAD

**Issue by tacusin** [mwittrien/BetterDiscordAddons#390]
**Describe the solution you'd like**
Force the quote option to show up on messages that are in channels you don't have access to (like an announcement channel). And upon clicking it'll copy the quote to your clipboard so you can post it somewhere else.

**Describe alternatives you've considered**
A second option called "Quote to clipboard" that when clicked copies the quote to your clipboard.

**Additional context**
One thing that would also be cool but isn't necessary is if there was a second 'Custom Format' Field in the plugin options where one could include placeholders such as $ChannelName, $ServerName, $channel, etc. for when planning to copy the quote to another channel. In my opinion, this works better with the alternative option so you can copy it to the clipboard even if you do have permission to write on that channel.

**Comment by mwittrien** [comment]
not the point of the plugin, the plugin is only meant to allow you to change the quote format, not to add new ways of quoting

**Comment by tacusin** [comment]
Oh well, thanks for taking the time to read my suggestion :)
