### ISSUE TITLE
[BUG] - SpellCheck Not Loading

### ISSUE THREAD

**Issue by McCovican** [mwittrien/BetterDiscordAddons#394]
Seems SpellCheck isn't loading at all for me (I have several other plugins from you that are loading fine, however).

The console error: 
![200327163451](https://user-images.githubusercontent.com/11760565/77778483-f6df3180-7048-11ea-848d-b2fff2ceda82.png)

The full log: https://x.brutix.uk/discordapp.com-1585326475690.log

**Comment by mwittrien** [comment]
fixed
