### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by tacusin** [mwittrien/BetterDiscordAddons#396]
**Describe the solution you'd like**
A setting for the timelog to save only the previous X instances. Sometimes the timelog gets so large discord basically freezes trying to load it all.

**Comment by mwittrien** [comment]
Caped the timeLog to 200 entries, that's the most my discord could handle without havign a too long wait time or crashing when the log was shown

**Comment by tacusin** [comment]
Cool, works for me ^^, I'll pop with feedback after trying out the new cap :3
