### ISSUE TITLE
[BUG] - ServersFolders

### ISSUE THREAD

**Issue by vugi99** [mwittrien/BetterDiscordAddons#397]
**Describe the bug**
ServerFolders Not working as expected

**To Reproduce**
just load the last version of serverfolders

**Expected behavior**
it should work as expected

**Screenshots**
https://i.imgur.com/5APlsSE.png

**Discord Built (stable, ptb or canary):**
stable

**Additional context**
Since last update

**Comment by mwittrien** [comment]
restart the plugin
