### ISSUE TITLE
Plugin Repo - Update All function

### ISSUE THREAD

**Issue by tegenton** [mwittrien/BetterDiscordAddons#40]
I've been using these plugins, and I'm glad that you update them so frequently, but sometimes I'd rather be able to just "update all" instead of updating each plugin individually.
I was wondering if you had any plans on implementing this, as I would rather not go through the hassle of doing it myself if it's a planned feature.
Thanks again for making these.

**Comment by mwittrien** [comment]
I might take a look in the future

**Comment by tegenton** [comment]
Thanks!
