### ISSUE TITLE
[BUG] - ChatFilter v3.4.0

### ISSUE THREAD

**Issue by toastido** [mwittrien/BetterDiscordAddons#402]
**Describe the bug**
ChatFilter v3.4.0 forces the chat window to stay scrolled to the bottom, until you hit the "previous messages" banner.  Once you scroll past that it stops forcing you to the bottom, but all interaction with the previous messages no longer works.

**To Reproduce**
Install ChatFilter v3.4.0, set filter word(s) and attempt to scroll back through the conversation.

**Expected behavior**
To be able to scroll back through the messages without issue.

**Screenshots**
n/a

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Let me know if you need anything else.  Currently running Stable discord on MacOS 10.15.4.

**Comment by mwittrien** [comment]
Not the case for me,
try disabling all other plugins and check if it still occures

**Comment by toastido** [comment]
I disabled all other plugins and the problem persists.  This problem only exists apparently when there are words that chatfilter takes action on.  If there are no matches on in the current chat, the issue isn't present, but if you add a word that exists currently in the current chat, then try to scroll up, it will constantly reset to the bottom of the current chat until you scroll up so far you hit the 'load more' barrier, after which you can scroll again.

**Comment by mwittrien** [comment]
Please record a video of the behaviour you are refering to since, I can't reproduce it

**Comment by toastido** [comment]
Sorry for the delay; things have been a bit crazy due to the pandemic.  As of the lastest discord for mac update (which also required a re-installation of BD) this is no longer occurring, so I'm going to close it as it seems to possibly have been a mac specific bug that can no longer be reproduced.
