### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by TheHDCrafter** [mwittrien/BetterDiscordAddons#403]
**Describe the bug**
Getting a notification sound when a user that is blocked mentions you (the user)

**To Reproduce**
Block someone and get pinged by him :)

**Expected behavior**
The pluging should notice that the user is blocked and then not play the notification sound

**Screenshots**
N/A

**Discord Built (stable, ptb or canary):**
Canary 57177 (a2a33bd)

**Additional context**
N/A

**Comment by mwittrien** [comment]
fixed
