### ISSUE TITLE
[IMPROVEMENT] - New plugin idea

### ISSUE THREAD

**Issue by BannerBomb** [mwittrien/BetterDiscordAddons#404]
**Describe the solution you'd like**
Could you make a plugin that makes it so when one of your servers has an outage instead of the default outage button bringing you to discords twitter page, could you make it show you what servers have outages? It'd be fine if it can at least show the server ids. I know you can get them from the developer console but it's only posted there when you connect to discord. It would be pretty useful to know which of your servers have an outage and I haven't seen any plugins made to do anything like that.

**Describe alternatives you've considered**

**Additional context**
This is the outage button I am talking about btw It would be useful to know the servers instead of it bringing you straight to the discord twitter page.
![image](https://user-images.githubusercontent.com/11788894/78460094-03d4d400-768c-11ea-9649-207f0a2da217.png)

**Comment by mwittrien** [comment]
This is neither the place to request new plugins nor am I taking requests
