### ISSUE TITLE
[BUG] ServerFolders : no unread badges

### ISSUE THREAD

**Issue by KaKi87** [mwittrien/BetterDiscordAddons#405]
**Describe the bug**
Since the latest version of ServerFolders, unread badges no longer works on folders.

**To Reproduce**
Enable ServerFolders.

**Expected behavior**
Unread bages are visible just like when ServerFolders is disabled.

**Screenshots**
| ServerFolders disabled  | ServerFolders enabled |
| ------------- | ------------- |
| ![2020-04-06 00_49_54-Discord](https://user-images.githubusercontent.com/21284089/78511949-e5acc800-77a0-11ea-8fee-e2f1ad8f2c24.png) | ![2020-04-06 00_51_09-Discord](https://user-images.githubusercontent.com/21284089/78511948-e5143180-77a0-11ea-9668-6a8d60445ce4.png) |

**Discord Built (stable, ptb or canary):**
![2020-04-06 00_54_52-Discord](https://user-images.githubusercontent.com/21284089/78511999-4805c880-77a1-11ea-8b5f-00ab6d48ae7d.png)

**Additional context**
None

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/78530305-b3708a00-77e3-11ea-9dfd-7afe917346fb.png)
Works fine for me, Most liekly your theme's fault

**Comment by KaKi87** [comment]
Well, it seems you're right. However, I don't know why would the theme have a specific incompatibility with ServerFolders. I'll ask the theme dev, thanks !
