### ISSUE TITLE
[IMPROVEMENT] - Pin DM's

### ISSUE THREAD

**Issue by Ashteroide** [mwittrien/BetterDiscordAddons#406]
I love this plugin but had to do some CSS editing in the Custom CSS to line it up better (Probably just colliding with other themes), a great improvement would be folders for pinned to guild DM's

**Comment by mwittrien** [comment]
It fits fine with the native theme, it's a theme dev's job to style plugins to fit the overal theme

guild like folders for recent DMs might be added in the future
