### ISSUE TITLE
[BUG] - DisplayLargeMessages - Larger messages cause jump to the bottom

### ISSUE THREAD

**Issue by jack1142** [mwittrien/BetterDiscordAddons#407]
**Describe the bug**
Plugin causes jumping to the bottom when message takes whole screen.

**To Reproduce**
1. Go to lipsum.com
2. Generate 20 paragraphs of Lorem Ipsum
3. Copy whole text
4. Paste into Discord's text box.
5. Send the message using `message.txt` attachment.
6. Switch to another channel and go back (needed to cause the message in `message.txt` to display)
7. Try scrolling up.

**Expected behavior**
Plugin shouldn't cause jumping to the bottom.

**Screenshots**
![2020-04-15_14-53-13](https://user-images.githubusercontent.com/6032823/79339247-e07e1480-7f28-11ea-98fe-3770d6acf03c.gif)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
None

**Comment by mwittrien** [comment]
fixed
