### ISSUE TITLE
[IMPROVEMENT] - DisplayLargeMessages - Option to display message.txt on demand

### ISSUE THREAD

**Issue by jack1142** [mwittrien/BetterDiscordAddons#408]
**Describe the solution you'd like**
I would want a setting that would make the plugin only show the `message.txt` on a click of some button or something like that.

**Describe alternatives you've considered**
None

**Additional context**
Very long messages can require a lot of scrolling when whole `message.txt` is always displayed.

**Comment by mwittrien** [comment]
Added
