### ISSUE TITLE
Folders are broke?

### ISSUE THREAD

**Issue by HYPExMon5ter** [mwittrien/BetterDiscordAddons#41]
After loading up BD today (I updated last night), it seems that the folders have broke, they aren't showing up anymore. Are they read/stored differently now? Do I need to re-make them?

**Comment by mwittrien** [comment]
No idea why this is happening to some ppl, Plugin works fine and nothing changed

**Comment by HYPExMon5ter** [comment]
It's working now after the update I just downloaded

**Comment by HYPExMon5ter** [comment]
Folders are gone again, re-opening issue

**Comment by mwittrien** [comment]
Seems like it was an issue with the plugin loading too fast, i delayed the loading of the folders on start a bit, should fix it
