### ISSUE TITLE
[BUG] - PinDMs - Scrolling through DMs causes the DM list to flicher/flash.

### ISSUE THREAD

**Issue by EnderBro123** [mwittrien/BetterDiscordAddons#410]
**Describe the bug**
When using PinDMs, and going throughout DMs within categories you create, the DMs start flickering and you can't scroll down/anywhere throughout the list. I don't even know how to say this lol... Only way to stop this from occurring is to click and go to a random server/page besides your DM list.

**To Reproduce**
Scroll through DMs.

**Expected behavior**
For none of this to happen...

**Screenshots**
![image](https://user-images.githubusercontent.com/51277766/79379287-8cb50080-7f13-11ea-8cc9-151642afa7d9.png)
Normally this would be flickering/flashing, but I screenshotted this so it won't.

**Discord Built (stable, ptb or canary):**
Stable.

**Additional context**
None.

**Comment by mwittrien** [comment]
fixed

**Comment by EnderBro123** [comment]
Thank you.
