### ISSUE TITLE
[IMPROVEMENT] - PLUGIN EditUsers

### ISSUE THREAD

**Issue by Dethkiller15** [mwittrien/BetterDiscordAddons#411]
I have many people added to EditUsers and I have Color coded them and have set names to them.

I have knowledge that after a while of setting people up like that I have continued to slow down while That specific plugin is enabled.

For instance if I switch from 1 Server/DM or even booting up. It takes a LOT longer to load VS not having the plugin enabled, and even scrolling gets affected. by this as well.

I have like... 7537 lines in the config file for this plugin as well if that helps you.

**Comment by mwittrien** [comment]
Can't really fix that, try to edit less people
