### ISSUE TITLE
[BUG] - Google Translate Option. Won't open the popup when clicked

### ISSUE THREAD

**Issue by StrikerFRFX** [mwittrien/BetterDiscordAddons#414]
**Describe the bug**
It will not open the popup at all

**To Reproduce**
Whenver I click the button

**Expected behavior**
Opens the popup

**Screenshots**
https://www.youtube.com/watch?v=JcOR-LtAMrU

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Worked fine before man

**Comment by mwittrien** [comment]
fixed
