### ISSUE TITLE
PluginRepo: Downloading an addon with a changelog update takes you back to the top of the PluginRepo

### ISSUE THREAD

**Issue by flleeppyy** [mwittrien/BetterDiscordAddons#416]
Currently running BandagedBD on DiscordPTB, on Kubuntu 19.10

When your scrolled down the pluginrepo, and you download an addon that has a changelog, it will take you back up to the top of all the addons, causing you to have to go back down to where you just were.

Here is a recording of me recreating the issue
![simplescreenrecorder-2020-04-25_14 16 37](https://user-images.githubusercontent.com/18307183/80291147-d9f95500-86ff-11ea-95fb-59fb8a874c7d.gif)

**Comment by mwittrien** [comment]
Can't be fixed, that's how the modal stack in discord works
