### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by BiBi88** [mwittrien/BetterDiscordAddons#417]
When using **Edit User v3.8.3** I get lag. I have tested this by only running this plugin and nothing else and it makes it very tough to scroll through text, typing, changing vc channels. Not sure why this is happening. It has been going on for the past 2 weeks. I really love this plugin please take a look at this. <3

I am running Better Discord Bandage  0.3.4.

Thank you kindly.

**Comment by Kojouro** [comment]
I get lag with just EmojiReplace theme turned on. Very annoying as it's kinda nice to use.

**Comment by mwittrien** [comment]
3.8.4 should be running faster
