### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by MerlinCooper** [mwittrien/BetterDiscordAddons#418]
**Describe the bug**
Settings Dialog does not open after clicking on button "Settings"

**To Reproduce**
Always

**Expected behavior**
Settings dialog does open

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3088879/80861084-9c02b080-8c6c-11ea-8931-d23642dd0d30.png)
![grafik](https://user-images.githubusercontent.com/3088879/80861094-a6bd4580-8c6c-11ea-8043-03b7d035f163.png)

**Discord Built (stable, ptb or canary):**
stable

**Comment by MerlinCooper** [comment]
Was able to get the previous version from the history running in my discord.

**Comment by mwittrien** [comment]
close discord, delete NotificationSounds.config.json, retry
you are using an old config
