### ISSUE TITLE
ShowHiddenChannels - See allowed and disallowed roles in a channel you're already in

### ISSUE THREAD

**Issue by ImmortalZypther** [mwittrien/BetterDiscordAddons#42]
In the [ShowHiddenChannels](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ShowHiddenChannels) plugin, it shows the roles that are allowed and disallowed to see a channel.
![screenshot 1](https://user-images.githubusercontent.com/21045587/35407849-26f9e114-01db-11e8-806f-3ec60da8fa94.png)
I was wondering if you could make it possible to see these roles in channels we are already allowed into since they don't show up if you're allowed in the channel.
![screenshot 2](https://user-images.githubusercontent.com/21045587/35407917-51a75982-01db-11e8-8ac8-de36f74956ae.png)
You can add it into the original plugin or make a separate plugin, I just want the feature somewhere, thanks!

**Comment by mwittrien** [comment]
Added the option
