### ISSUE TITLE
[BUG] - Edit Users v3.8.4.

### ISSUE THREAD

**Issue by BiBi88** [mwittrien/BetterDiscordAddons#420]
**Describe the bug**
Under Local User Settings, if one goes to change the color for any option via the text box it can not be accessed. One can't click it or tab into the text box. Colors can only be changed via the color picker. User is therefore not able to add their own hex code into the text area.

**To Reproduce**
Try to select the text box in any of the options where one is allowed to change color under Local User Settings be that Tags, Names, Text etc.

**Expected behavior**
Users will not be able to access the text area when trying to do so via mouse clicks or tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/47702528/81474350-bdc7de80-91fc-11ea-8935-f61d402a9138.JPG)

**Discord Built (stable, ptb or canary):**
Discord PTB & Stable both exhibit this behavior.

**Comment by mwittrien** [comment]
Yes i am aware, i am already working on a fix
