### ISSUE TITLE
[BUG] - No settings for NotificationSounds?

### ISSUE THREAD

**Issue by skryy99** [mwittrien/BetterDiscordAddons#421]
**Describe the bug**
No settings for NotificationSounds

**To Reproduce**
Every time my discord is open, since this morning.  Last night upon

**Expected behavior**
To hear my custom discord sounds, but I hear nothing.

![Screenshot_10](https://user-images.githubusercontent.com/65282548/81918612-9c853a80-95ce-11ea-90e1-99964cd5de0c.png)

**Comment by orblazer** [comment]
This is same for every plugins its because the url `https://mwittrien.github.io/BetterDiscordAddons/Plugins/BDFDB.min.js` return 404, but now this is work.
