### ISSUE TITLE
[BUG] - ChatAliases

### ISSUE THREAD

**Issue by fmpreferences** [mwittrien/BetterDiscordAddons#422]
This doesn't even have anything to do with the context menu broken but actually has been going on for a while.

So whenever you have two or more different aliases in one single "word" (which is just a series of characters not separated by spaces, and you send it in chat, it only replaces one chat alias, and that alias I believe is the topmost in ChatAliases.config.json out of the aliases sent, if that helps. If you only have two or more of the same alias it works as expected.

![image](https://user-images.githubusercontent.com/57734230/82346247-d7ff7a80-99bb-11ea-9d56-c226ea5c7e3f.png)
this is expected to replace =/= with ≠ and ^deg with °, however it will do this instead when sent in chat:
![image](https://user-images.githubusercontent.com/57734230/82346492-257be780-99bc-11ea-9782-07e7866b3dcd.png)
and only replace =/= with ≠. If we click edit and press enter again it works as expected:
![image](https://user-images.githubusercontent.com/57734230/82346776-81df0700-99bc-11ea-8299-45e1107d253d.png)

I am using the stable build, and I am using ChatAliases v2.1.3

**Comment by mwittrien** [comment]
Yeah words are only get caught once by an alias to avoid aliases being affected by other aliases
