### ISSUE TITLE
[BUG] - server folder

### ISSUE THREAD

**Issue by JohnWeak1** [mwittrien/BetterDiscordAddons#423]
**Describe the bug**
cannot open the context menu of a server inside a server folders

**To Reproduce**
put a server in a folder then open the folder then right click and then the context menu won't appear

**Expected behavior**
a context menu should appear when right-clicking a server in a folder

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Should be fixed after a reload
