### ISSUE TITLE
[QUESTION] - BDFDB

### ISSUE THREAD

**Issue by Flam3rboy** [mwittrien/BetterDiscordAddons#424]
Hello mwittrien,

I'm porting Better Discord to the web and currently doing plugin support, unfortunately your lib BDFDB.js
has some errors.
Where do you have the full source code for it BDFDB.js, so that I can patch the relevant parts to work in the web?

**Comment by mwittrien** [comment]
BDFDB.js is the full source code

**Comment by Flam3rboy** [comment]
I mean the proper project structure. With files and imports etc. or did you write the lib in one file?

**Comment by mwittrien** [comment]
It's written in one file

**Comment by Flam3rboy** [comment]
Wow, you need definitely look into Webpack

**Comment by mwittrien** [comment]
No thanks
