### ISSUE TITLE
[BUG] - GoogleTranslateOptions

### ISSUE THREAD

**Issue by RyRyDiscord** [mwittrien/BetterDiscordAddons#427]
**Describe the bug**
Every time I turn it on, I have even made sure that the logo is red, indicating the plugin is on, and I switch to something obvious, let's say, Russian. I type, it says it's translating for a second, then it sends. But, the sent message, isn't in Russian and it's in English?

**To Reproduce**
After clicking enter to send the message.

**Expected behavior**
The message to be sent out in the selected language.

**Screenshots**
http://prnt.sc/sqmeqv  |  |  http://prnt.sc/sqmery  |  |  http://prnt.sc/sqmete

**Discord Built (stable, PTB or canary):**
Stable.

**Additional context**
I've tried restarting discord normally and going through task manager, ending it, then launching it as admin. Please help.

**Comment by mwittrien** [comment]
Works fine for me,

Make sure you set up the input/utput languages correctly
