### ISSUE TITLE
[BUG] - EditUsers in calls

### ISSUE THREAD

**Issue by DorCoMaNdO** [mwittrien/BetterDiscordAddons#435]
**Describe the bug**
Renamed users via EditUsers in ~~group~~ calls will often cause the ~~group call~~ sorting of members in the call to freak out, this seems to be since the ~~group~~ call sorting of members is done alphabetically by member names, and the renamed user seems to momentarily have their name changed back to their actual username and then again back to the renamed username.

**To Reproduce**
Edit someone's name in a ~~group~~ call of 2 or more people so that the alphabetical order would be affected.

**Expected behavior**
EditUsers should either reinforce the sorting order based on the new username or avoid affecting it.

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Sorting of the user avatars in group calls are based on the "last time spoken" not alphabetically, if you think there is still a bug related to EditUsers pls record the behaviour your expect to be a bug

**Comment by DorCoMaNdO** [comment]
The issue was resolved when I reset the name, and was back again when I renamed again, and the sorting order flickered quickly when it was happening, multiple times a second, so it does seem to be alphabetical, even in one-on-one DM calls, which might be affected too.
I'll try to record a clip soon.

**Comment by DorCoMaNdO** [comment]
I haven't been able to record a clip yet, but the order of people in a call is definitely alphabetical, I took a couple of screenshots to describe the issue better, the issue I described is reproducible in DM calls too, not just groups, I only noticed it in a group since the alphabetical order with my name and the person I renamed was not affected. My name starts with C, their original name with O, I renamed them to a name that starts with D, which is still after C.

Renamed but alphabetical order unaffected, my icon is on the left, theirs on the right: https://i.imgur.com/IGbYkTz.png
Prefixed their name with A and now the order reversed: https://i.imgur.com/8AGVVdo.png

The issue is that the order does not remain consistent, the order of the icons momentarily reverts based on the original name and changes back to the rename, causing the icons to shift rapidly every so often.

**Comment by mwittrien** [comment]
Try the new update

**Comment by DorCoMaNdO** [comment]
Seems to no longer affect the order of icons, using the sorting order based on the original names.

I completely forgot the plugin had settings, I've got them all enabled and there are still 3 places where names do not get renamed, I could open a new issue if you'd like but here's where:
Picture in picture (when there's a screenshare in a call and you swap to another chat/server) back arrow
Title bar/taskbar (there's a setting for this so I'm guessing it's broken)
The title/header at the top of the screen (@ NAME) when changing a call to play in full screen (works outside of full screen)
