### ISSUE TITLE
[BUG] - EditUsers unaffected

### ISSUE THREAD

**Issue by mwittrien** [mwittrien/BetterDiscordAddons#436]
I completely forgot the plugin had settings, I've got them all enabled and there are still 3 places where names do not get renamed, I could open a new issue if you'd like but here's where:
Picture in picture (when there's a screenshare in a call and you swap to another chat/server) back arrow
Title bar/taskbar (there's a setting for this so I'm guessing it's broken)
The title/header at the top of the screen (@ NAME) when changing a call to play in full screen (works outside of full screen)

_Originally posted by @DorCoMaNdO in https://github.com/mwittrien/BetterDiscordAddons/issues/435#issuecomment-648356517_

**Comment by DorCoMaNdO** [comment]
The link label to the call (below "Voice Connected", above your own name and status) isn't always affected too.
