### ISSUE TITLE
[BUG] - Read All Notifications

### ISSUE THREAD

**Issue by tryoutuser** [mwittrien/BetterDiscordAddons#438]
**Describe the bug**
Same as what i posted for chatfilter. Plugin stopped working and read all button disappear.

**To Reproduce**
Bug occurred today. Can't reproduce since the plugin did not load.

**Expected behavior**
Plugin loaded and read all button appear.

**Discord Build (stable, ptb or canary):**
v0.0.306 Stable 62330

**Comment by mwittrien** [comment]
works on stable for me same as any other built

**Comment by tryoutuser** [comment]
Really really weird, after you closed this issue, both plugin i find did not load magically loaded.

I have tried reinstalling bandaged BD, clearing discord cache folder. But it wasn't worked.
