### ISSUE TITLE
[BUG] - ServerColumns

### ISSUE THREAD

**Issue by jack652** [mwittrien/BetterDiscordAddons#439]
**Describe the bug**
there's only one column now, and there's a space where the second one is supposed to be

**To Reproduce**
just use the theme

**Expected behavior**
the servers should be split in two columns

**Screenshots**
![servercolumns bug](https://user-images.githubusercontent.com/48365199/86166271-d07fd500-bb14-11ea-928c-b15d376acc94.png)

**Discord Built (stable, ptb or canary):**
stable

**Additional context**
disabling and re enabling theme doesn't fix

**Comment by solonovamax** [comment]
Bump on this, changing the amount of columns makes it so that the server folders take up `columns - 1` columns.

**Comment by mwittrien** [comment]
Most likely a theme incompartibility

Works fine for me 
Left canary, right stable
![image](https://user-images.githubusercontent.com/23700969/86172864-5143ce80-bb1f-11ea-871c-45e5029dec02.png)

**Comment by solonovamax** [comment]
Idk what happened, but it seems fixed now. I guess some recent discord update changed something and suddenly it works. /shrug.
