### ISSUE TITLE
[BUG] - BadgesEverywhere/NEUTRON

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [mwittrien/BetterDiscordAddons#440]
**Describe the bug**
Badges appear inside names while chatting.

**To Reproduce**
Inside the chat window.

**Expected behavior**
The badges should appear at the end of the name.

**Screenshots**
https://imgur.com/XCuNVEG - https://imgur.com/a/BPfSDup
https://imgur.com/w95L0il - https://imgur.com/a/FKOFQXW

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
fixed in 1.6.0
