### ISSUE TITLE
[BUG] EditUsers renamed users unaffected

### ISSUE THREAD

**Issue by DorCoMaNdO** [mwittrien/BetterDiscordAddons#441]
**Describe the bug**
Renamed users do not get renamed in their reactions (both the tooltip hover and in the reactions menu), they also do not get renamed in the DMs context menu "Mute @NAME"

**To Reproduce**
Rename a user

**Expected behavior**
The user to be renamed in all places that reference their name or nickname.

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
I would prefer if colors weren't applied to these areas as darker names could be difficult or impossible to read.
In general having the option to choose where to apply renames and where to apply colors rather than a single toggle for both in the settings would be really nice.

**Comment by mwittrien** [comment]
Added support for the mentioned areas.

Additional settings for more variety on color placement won't be added since the plugin is already bloated enough, if you don't want dark colors to mess with readability, then use lighter ones

**Comment by DorCoMaNdO** [comment]
I use colors that I find to be readable, it's just that when colors apply in darker areas, they do become harder to read at times, as would be the case if colors were applied to the context menu or the tooltip.
I brought this up since the fix to the link label below "Voice Connected" also applied colors, which wasn't the case before, and since the background is a bit darker, darker than anywhere colored names typically appear in, it can be harder to read and generally just feels "off" even if there's little value to checking that label in a DM call.
