### ISSUE TITLE
[IMPROVEMENT] - GoogleTranslateOption

### ISSUE THREAD

**Issue by JezzaProto** [mwittrien/BetterDiscordAddons#444]
**Describe the solution you'd like**
Allow users to add/remove prefixes that are ignored.

**Additional context**
![image](https://user-images.githubusercontent.com/54776821/87191387-3a099b80-c2ec-11ea-90c6-4802403799a3.png)
Let people change this maybe for bots that don't have ! prefixes.

**Comment by zhouhuichen741** [comment]
Can you increase the overall translation function?It is inefficient to click on every sentence

**Comment by zhouhuichen741** [comment]
can you add a function to translate all sentence in same time? 
confronting screen that full of untranslated sentences and clicking them one by one makes me a little headeache.
thanks

**Comment by mwittrien** [comment]
Added
