### ISSUE TITLE
[BUG] - OwnerTag

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [mwittrien/BetterDiscordAddons#447]
**Name**
OwnerTag

**Describe the bug**
The owner tag and admin tag doesnt show in chat.

**To Reproduce**
Inside the channel text, there is no owner or admin tags.

**Expected behavior**
Admin and Owner tags should show next to usernames.

**Screenshots**
![No owner tag or admin tag](https://user-images.githubusercontent.com/54776821/87666943-6d6f7e80-c761-11ea-8786-b6c54dc7db2e.png)
![My OwnerTag settings](https://user-images.githubusercontent.com/54776821/87667003-8b3ce380-c761-11ea-91a8-a467ec21a192.png)

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Works fine for me, try reloading or try disabling all other plugins and reloading
