### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps

### ISSUE THREAD

**Issue by AdWasTaken** [mwittrien/BetterDiscordAddons#448]
When having two messages by the same user back to back, only the default discord time stamp appears.
I request adding the CompleteTimestamp for back to back messages.

**Comment by mwittrien** [comment]
the complete timestamp can be seen by hovering over the mini timestamp to the left in back to back messages
![image](https://user-images.githubusercontent.com/23700969/87728937-6fb6f480-c7c4-11ea-9495-887f579a1461.png)
