### ISSUE TITLE
[BUG] - ServerFolders (servers within folders not opening)

### ISSUE THREAD

**Issue by Fentist1x** [mwittrien/BetterDiscordAddons#453]
**Describe the bug**
Click on Folder, Folder opens to reveal servers within folders, click on server, cannot open server.

**To Reproduce**
Any time you do the above when you have the ServerFolders Plugin enabled
Stable 63737 (3c8c7a4)
BBD 0.3.5 (9d31dfe)
Host 0.0.306
Injector 0.5.1

**Expected behavior**
Click on Server Folder, Folder opens to reveal servers, Click on Server to reveal channels within Server, Click on channel to see messages within channel.

**Discord Built (stable, ptb or canary):**
Stable 63737 (3c8c7a4)
BBD 0.3.5 (9d31dfe)
Host 0.0.306
Injector 0.5.1

**Additional context**
Server Folders Changelog image for version info:
https://i.imgur.com/VArAd5z.png

Have to disable to the plugin to be able to see/read anything in any current folders. Please advise what I have done wrong

**Comment by doqfgc** [comment]
Also experiencing this issue.

**Comment by mwittrien** [comment]
Fixed in newest version

**Comment by Fentist1x** [comment]
newest fix did not fix, multiple reloads (ctrl+r)
