### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds 

### ISSUE THREAD

**Issue by BaalEvan** [mwittrien/BetterDiscordAddons#454]
**Describe the solution you'd like**
Way to select specific sound per Server/Chat.
Could be added as Context Menu to server, or as textSearch (if servername.contains("work") or ServerID in settings

Customizing sounds per channel also will be great, but server context is more important for me right now.

I want to be able to recognize if message is from important Server like my Work or not

**Comment by mwittrien** [comment]
The plugin simply changes the sound that discord plays, discord does not provide any information on which server/channel the sound comes from
