### ISSUE TITLE
[BUG] - CUSTOM INCOMMING CALL DOSNT WORK

### ISSUE THREAD

**Issue by lapatatedouce59** [mwittrien/BetterDiscordAddons#456]
Hello
I just installed the CustomNotificationSounds plugin, which works well, but I have a problem. I can't change the basic incoming call ringtone into the remixed ringtone. Yet I went well in the category Implanted Sounds/Incomming call and selected Incomming Call beat, but when a friend calls me the ringtone is the basic one. When I put the beat in the outgoing call, it worked. But not the outgoing call. Who has a sollution?

**Discord Built:**
Better Discord Stable 64507 (3412288)

**Plugin version**
NotificationSounds v3.4.6

Who can respond me? Thx ^^

![image](https://user-images.githubusercontent.com/69109114/89122109-0114af00-d4c5-11ea-855d-0deab1b589c4.png)

**Comment by mwittrien** [comment]
should be fixed
