### ISSUE TITLE
[New Addon/Plugin] discord.bio 

### ISSUE THREAD

**Issue by barbiehunter** [mwittrien/BetterDiscordAddons#457]
**Describe the solution you'd like**
discord.bio is a good alternative for normal status, which is why a status/baris displayed as an advertisement under the profile of a person who has an account there (Like spotify and co.)

**Additional context**
I got the idea, because a buddy of me did it himself but at Powercord, and he doesn't want to do it for Betterdiscord and let it private.

**Comment by mwittrien** [comment]
Why not use AutoStartRichPresence

**Comment by barbiehunter** [comment]
I think that dont would be the same, because it dont will get updated itself and the thing is that it would be nice to see the discord.bio from other people. With the AutoStartRichPresence im just do it for myself

**Comment by mwittrien** [comment]
Well i am currently not looking for new projects
