### ISSUE TITLE
[BUG] - BasicBackground

### ISSUE THREAD

**Issue by Vandesm14** [mwittrien/BetterDiscordAddons#458]
**Describe the bug**
Weird/unknown shadow for message box and membercound (plugin) when using the theme

**To Reproduce**
Install membercount and dateviewer plugins
Set the transparencyalpha value to `0.5`

**Expected behavior**
There should be a clear and distinct light shadow around the message box which surrounds it's 

**Screenshots**
![image](https://user-images.githubusercontent.com/23623276/89204244-cb82cb00-d583-11ea-81de-f54eb549cebf.png)
![image](https://user-images.githubusercontent.com/23623276/89204263-d178ac00-d583-11ea-867e-3834f22e00ae.png)
![image](https://user-images.githubusercontent.com/23623276/89204415-10a6fd00-d584-11ea-91c5-5458e986d91d.png)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
I've tried to locate the CSS issue, but it does not seem like the suspected elements have a `box-shadow` property set, even though there is in fact a light shadow.

**Comment by mwittrien** [comment]
Message box was fixed;
MemberCount can't be fixed due to how the plugin insert the counter

the issue occures because you set neither an image nor a color for the background variable in the theme
