### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities, different zoom modes

### ISSUE THREAD

**Issue by Glaived** [mwittrien/BetterDiscordAddons#463]
## **Describe the solution you'd like**
1. **Lens** (With more options, like shape, or click + scroll to change the zoom)
2. **ScrollToZoom** (ScrollUp to zoom x2 x3 x4…, with margin)

Add zoom with +/- for 1. and 2.

## **Additional context**
![ScrollToZoom](https://user-images.githubusercontent.com/1835170/90294167-1656e980-de86-11ea-9d4b-e5bd5caf189b.png)
*Zoom with margin for reset*

**Comment by mwittrien** [comment]
No to the shape, a lense is always round in my book, you can set the lense size to the maximum to fake a fullscreen zoom

Yes to controls, i added +/- and mousewheel controls

**Comment by BanementI** [comment]
> No to the shape, a lense is always round in my book

It was an option before, why not implement it again? A round lense was optional before, with the settings descrption as "why".
