### ISSUE TITLE
[IMPROVEMENT] - ImageUtils/FullZoom

### ISSUE THREAD

**Issue by Spazzlo** [mwittrien/BetterDiscordAddons#464]
**Describe the solution you'd like**
I'd much rather have a full image zoom - as in, holding down click on the image zooms in the entire image and moving around the mouse will move around the image - than a small circle showing me part of the image

**Describe alternatives you've considered**
I've considered making the lens size larger than the image, but that seems like a hacky solution.

**Additional context**

**Comment by mwittrien** [comment]
Just set the lense size to it's maximum
