### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities

### ISSUE THREAD

**Issue by DxRaider099** [mwittrien/BetterDiscordAddons#467]
Add the possibility to change destination folder for the option of downloading image, 
currently this function seems to be lock to a user default folder.
I think's changing the download location folder may be a usefull option,
a kind of QoL option ^^

**Comment by mwittrien** [comment]
Can be changed in the plugin settings

**Comment by DxRaider099** [comment]
Sorry but, i just test again and no the setting get back to defaut shortly after any change ???
