### ISSUE TITLE
[IMPROVEMENT] - Image Utilities on Users

### ISSUE THREAD

**Issue by Lucasamiel0406** [mwittrien/BetterDiscordAddons#470]
`Feature for Image Utilities`
> Add the "Image Utilities" context menu for user too who works on DM, server lists, etc, allowing the same things of the server IU context menu.

**Comment by bhrazor** [comment]
Le lun. 17 août 2020 6:17 p.m., Lucasamiel0406 <notifications@github.com> a
écrit :

**Comment by mwittrien** [comment]
You can already enable the entry in the plugin settings
