### ISSUE TITLE
[IMPROVEMENT] - cleaner $quote 

### ISSUE THREAD

**Issue by leafax** [mwittrien/BetterDiscordAddons#472]
**Describe the solution you'd like**
An option to do $quote without having the > in front of each line 

**Describe alternatives you've considered**
add $rawquote which does the exact same thing as quote without the > in front of each line 

**Additional context**
Would be pretty useful [here.](https://i.imgur.com/cjF06Ks.png)

**Comment by mwittrien** [comment]
added
