### ISSUE TITLE
[IMPROVEMENT] - Friend notifs

### ISSUE THREAD

**Issue by Aniperk** [mwittrien/BetterDiscordAddons#477]
**Describe the solution you'd like**
Under the Login/Out log, give option to log the tag of users.
Under the setting page of the plugin, add the option to show user tags.

**Describe alternatives you've considered**
Havent thought of any, dont really think theres any alternative

**Additional context**
<img width="536" alt="Screen Shot 2020-08-28 at 19 59 39" src="https://user-images.githubusercontent.com/32599075/91623322-03094b00-e969-11ea-93db-66f5b200d682.png">
<img width="481" alt="Screen Shot 2020-08-28 at 19 59 57" src="https://user-images.githubusercontent.com/32599075/91623329-0e5c7680-e969-11ea-98c1-2d642c52ea2d.png">

**Comment by mwittrien** [comment]
added
