### ISSUE TITLE
[IMPROVEMENT] - Theme Repo

### ISSUE THREAD

**Issue by ZaneDragonBorn** [mwittrien/BetterDiscordAddons#479]
**Describe the solution you'd like**
The icon for Theme Repo. I’m not sure if this has to be supported by the Clearvision author or u
You but the plugin Repo does have an icon beside it but this doesn't making it look weird.

**Additional context**
Nothing really just love the repo plugins and hope they get this small change.

**Comment by mwittrien** [comment]
Thats the themes fault
