### ISSUE TITLE
[Request] Option to disable unread

### ISSUE THREAD

**Issue by TheReaperr** [mwittrien/BetterDiscordAddons#48]
So I think almost everyone uses this plugin to hide their emoteservers... and is it possible to have an event listener for unread message. So when it triggers the unread message dot, you run the "mark as read" function?

**Comment by mwittrien** [comment]
"this plugin"?

**Comment by TheReaperr** [comment]
oh woops.. I meant ServerFolders. Didn't realize it was a collective git.

**Comment by mwittrien** [comment]
Added in 5.5.5
