### ISSUE TITLE
[IMPROVEMENT] - ImageUtilites

### ISSUE THREAD

**Issue by fadedmax** [mwittrien/BetterDiscordAddons#482]
**Describe the solution you'd like**
This probably isnt needed but would be nice, it also might go under some other plugin.
Whenever clicking on "Open original" it might show a "Hold Up!" Message, it would be nice for the plugin to bypass that if it contains a common ending? .img, .png, It might be insecure, but it would be nice as just a setting.
**Describe alternatives you've considered**
i mean.. not doing it at all?

**Additional context**
<img width="406" alt="Screen Shot 2020-08-31 at 17 47 18" src="https://user-images.githubusercontent.com/32599075/91772024-06434780-ebb2-11ea-91fb-78edc04e2d4b.png">
<img width="215" alt="Screen Shot 2020-08-31 at 17 48 44" src="https://user-images.githubusercontent.com/32599075/91772114-38ed4000-ebb2-11ea-8b50-7d65b61dc0d0.png">

**Comment by mwittrien** [comment]
You can now hold shift to skip it
