### ISSUE TITLE
[BUG] Image utilities 

### ISSUE THREAD

**Issue by fadedmax** [mwittrien/BetterDiscordAddons#483]
**Name**
Image utilities 

**Describe the bug**
Whenever having a image open, you have the standerd click to zoom, however if you click on "Open Original" And the "Hold up!" Box appears, if you click on the outside of it, you can still zoom in on the original image.

**To Reproduce**
When zooming in on the message
**Expected behavior**
Nothing. or it might click off. im too lazy to check lol.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-08-31 at 18 18 38" src="https://user-images.githubusercontent.com/32599075/91774262-6805b080-ebb6-11ea-9e4d-ed6d6c08a5a7.png">
<img width="1440" alt="Screen Shot 2020-08-31 at 18 19 21" src="https://user-images.githubusercontent.com/32599075/91774306-7fdd3480-ebb6-11ea-91cd-0395a5b0f1fa.png">

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
nothing have a good day ig :)

**Comment by mwittrien** [comment]
fixed
