### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME (about getting ringtone)

### ISSUE THREAD

**Issue by ReTordEdd** [mwittrien/BetterDiscordAddons#484]
So i was thinking if it would be possible to make the calling sound to start over when someone calls you immediately after the first call

**Comment by mwittrien** [comment]
added

**Comment by ReTordEdd** [comment]
Thank you bro!

pe 4. syysk. 2020 klo 15.25 Mirco Wittrien <notifications@github.com>
kirjoitti:
