### ISSUE TITLE
[IMPROVEMENT] - PluginRepo and ThemeRepo (Settings)

### ISSUE THREAD

**Issue by ZaneDragonBorn** [mwittrien/BetterDiscordAddons#486]
**Describe the solution you'd like**
A Options to disable Auto Enable in its settings. The Thing keeps bugging out my Discord and when I Disable it it won't Disable.

**Comment by mwittrien** [comment]
Auto Enable of newly downloaded plugins/themes can be done in the repo settings in the settings  tab
