### ISSUE TITLE
Image Utilities > Search Image with ... > React Component Error on all engines

### ISSUE THREAD

**Issue by d1st4nt** [mwittrien/BetterDiscordAddons#488]
Image Utilities v4.1.3

![image](https://user-images.githubusercontent.com/1766581/92422256-9a7d5380-f14a-11ea-83ac-c04f5eeaa612.png)

Other plugins installed:

ServerDetails v1.0.2
Word Notifications v0.0.9
ZeresPluginLibrary v1.2.22

**Comment by mwittrien** [comment]
Open the console by clicking **ctrl shift i** and pressing the console tab
Next try to search something so the react component error shows again
There should be an error message in the console about the component error
Screenshot it and send it in here

**Comment by mwittrien** [comment]
Closed due to inactivity
