### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by CrimsonMiralis** [mwittrien/BetterDiscordAddons#489]
**Describe the bug**
The translation option shows up twice while clicking on someones message and causes problems, when trying to click on translate it can either click on both and do nothing, or it will use the bottom option which does nothing then you have to click on top for it to actually go through. (first one causes second button to change to untranslate, then when you click the top it translates with no button changes)
![test](https://user-images.githubusercontent.com/52976980/92635748-59995200-f2a4-11ea-8402-381984998985.PNG)

**To Reproduce**
Not sure how you can reproduce, but I've tried reinstalling the plugin numerous times and restarting discord so might just be part of it at the moment?

**Expected behavior**

**Screenshots**
Already added a screenshot above but heres another
![image](https://user-images.githubusercontent.com/52976980/92635934-98c7a300-f2a4-11ea-903c-b4226e52edef.png)

**Discord Built (stable, ptb or canary):**
The stable build of discord.

**Additional context**
The Note plugin had this double icon problem at first to but resolved itself after using and restarting.

**Comment by mwittrien** [comment]
That's not an issue with the plugin but caused by something else, like running two copies of the plugin or sth, make sure you are only using one  copy of the plugin and try reinstalling BD and the plugin again
