### ISSUE TITLE
List doesn't blend well with theme.

### ISSUE THREAD

**Issue by BegunHarbor811** [mwittrien/BetterDiscordAddons#490]
The list shows up with the same color as default discord and doesn't work well with me theme at all (screenshot below)
Is there any way for me to fix this?

![image](https://user-images.githubusercontent.com/48876669/92642279-d15f8080-f294-11ea-84f9-09ae0a1ad04a.png)

**Comment by mwittrien** [comment]
thts the fault of the theme you are using, you can either ask the theme dev to add support for the plugin or fix it with your own css
