### ISSUE TITLE
[BUG] - MessageUtilities

### ISSUE THREAD

**Issue by QyuriLa** [mwittrien/BetterDiscordAddons#491]
**Describe the bug**
A keycombo hint of the "Mark Unread", ALT+C, shown even when the 'add keycombo hints ...' option turned off.

**To Reproduce**
This occurs always when the plugin enabled.

**Expected behavior**
It should not be shown when option turned off, and I think there should be an option of showing hints of default keycombo(s?).

**Screenshots**
<img src="https://user-images.githubusercontent.com/68494132/92951280-118f5080-f499-11ea-8127-30cb17e4407e.png" width="25%" height="25%"></img>
(It's Korean but this occurs regardless of discord language setting)

**Discord Built (stable, ptb or canary):**
Stable 66695 (d31c628)

**Comment by mwittrien** [comment]
fixed
