### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by hackaholic5069** [mwittrien/BetterDiscordAddons#495]
**Describe the bug**
if you click-zoom on an image and hit esc, the zoom thing stays open until you let go of click. after taking a screenshot while holding click down, it will stay open until you click again

**To Reproduce**
it can occur on any image, when you hold rclick and hit escape at the same time

**Expected behavior**
for the zoom window to go away
**Screenshots**
![image](https://user-images.githubusercontent.com/37553921/93517436-ed3bd580-f8d7-11ea-8bba-47e58f7ef846.png)

**Discord Built (stable, ptb or canary):**
Which built of discord are you using.
stable
**Additional context**

**Comment by mwittrien** [comment]
fixed
