### ISSUE TITLE
[BUG] - CharCounter

### ISSUE THREAD

**Issue by kamekku14** [mwittrien/BetterDiscordAddons#498]
**Describe the bug**
Although CharCounter adds character counters for messages, the character counter for server nicknames doesn't show up.

**To Reproduce**
Enable CharCounter, go to the server/guild you're currently in, then select "Change Nickname" from the dropdown menu.

**Expected behavior**
Was supposed to show the character counter for server nicknames, but now it's gone.

**Discord Built (stable, ptb or canary):**
Stable 67364 (0d1db82)

**Comment by mwittrien** [comment]
fixed
