### ISSUE TITLE
[IMPROVEMENT] - TopRoleEverywhere -  Add UserName

### ISSUE THREAD

**Issue by arefiq09** [mwittrien/BetterDiscordAddons#499]
Adding UserName would be very useful since discord always display Nickname of user. Currently there is already an option for displaying UserID, but it displays number.

```
			injectIdTag (children, user, type, config = {}) {
				if (!BDFDB.ArrayUtils.is(children) || !user) return;
				children.push(this.createTag({
					name: user.id
				}, type, config));
			}
			
			injectNameTag (children, user, type, config = {}) {
				if (!BDFDB.ArrayUtils.is(children) || !user) return;
				children.push(this.createTag({
					name: user.username
				}, type, config));
			}
```

![image](https://user-images.githubusercontent.com/19814380/93693762-b44d6c00-fb36-11ea-826f-f4498ccc9585.png)
![image](https://user-images.githubusercontent.com/19814380/93693771-d6df8500-fb36-11ea-8048-7250855234fc.png)

**Comment by mwittrien** [comment]
use the plugin RemoveNicknames

**Comment by arefiq09** [comment]
I would like to see both of them. So removing the nickname is not an option.

**Comment by mwittrien** [comment]
RemoveNicknames  can be configured to show both

**Comment by arefiq09** [comment]
Thank you, I'll give it a try.
