### ISSUE TITLE
[CreationDate] Italian translation issue

### ISSUE THREAD

**Issue by cashcka** [mwittrien/BetterDiscordAddons#50]
I really can't figure out how to make a PR so i post it here. is just a really small issue. instead of "Creata il" it should be "Creato il". "Creata" is a female term instead "Creato" is a male term and "Account" is a male term not female. i don't really know how to explain this in english. sorry

**Comment by mwittrien** [comment]
Fixed it, but I won't change the version number for a translation fix, so youll have to manually redownload it.
Telling me about translation issues like this is fine ;)
