### ISSUE TITLE
[IMPROVEMENT] - ServerDetails

### ISSUE THREAD

**Issue by fadedmax** [mwittrien/BetterDiscordAddons#501]
**Describe the solution you'd like**
Add a option to show the server icon, you already see it in the sidebar, whats the point of seeing it bigger?

**Describe alternatives you've considered**
none.

**Additional context**
<img width="231" alt="image of server" src="https://user-images.githubusercontent.com/32599075/93730871-cb687a00-fb87-11ea-9fee-2222db26eb3b.png">

**Comment by mwittrien** [comment]
You can disable the icon in the plugin settings
