### ISSUE TITLE
[BUG] - CopyRawMessage

### ISSUE THREAD

**Issue by kamekku14** [mwittrien/BetterDiscordAddons#503]
**Describe the bug**
The plugin has been started, but the "Copy Raw Message" menu command seems to be missing.

**To Reproduce**
Enable CopyRawMessage from Plugins, head to the server/guild you're in, then right click on the message or use the message's dropdown menu.

**Expected behavior**
Was supposed to see the "Copy Raw Message" menu item, but now it's gone.

**Discord Built (stable, ptb or canary):**
Stable 67364 (0d1db82)

**Comment by mwittrien** [comment]
Delete 0BDFDB.plugin.js, reload and click the Download Now button in the missing lib modal
