### ISSUE TITLE
[BUG] - serverdetails

### ISSUE THREAD

**Issue by JohnWeak1** [mwittrien/BetterDiscordAddons#504]
**Describe the bug**
tooltip is getting cut out when near the window border

**To Reproduce**
hover a server at the top of the window

**Expected behavior**
that the tooltip repositions in order to not get cut out

**Screenshots**
![image](https://user-images.githubusercontent.com/42245432/93874850-46d74200-fcd4-11ea-9894-b106f4cbe160.png)

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Pretty sure thats an issue with your theme
