### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by JSharpie** [mwittrien/BetterDiscordAddons#506]
**Describe the bug**
See screenshot of my settings
If I select a different folder it will not open the folder unless I select a server first.
If I click on the folder that's already opened, it will not close the selected folder.

**To Reproduce**
1. See screenshot for my settings
2. Have Two folders with multiple servers in each folder
3. Select a Folder, it should open the servers
4. Select another folder, it will not close the currently opened folder and also not open the selected folder
5. Select a server on the previously selected folder
6. Notice that the previously selected folder closes after doing that and it will open the newly selected folder

Closing the currently selected folder 
7? Select the folder you have opened
8? Notice that the folder no longer closes.

**Expected behavior**
Be able to open other folders when selected and it should close the other folders.

**Screenshots**
![image](https://user-images.githubusercontent.com/53364876/93946242-9a09be80-fced-11ea-92bc-d936991d430a.png)

**Discord Built (stable, ptb or canary):**
Stable 67562 (ba11425)

**Additional context**
No Themes
Other plugins installed
![image](https://user-images.githubusercontent.com/53364876/93946670-b1957700-fcee-11ea-9e27-a41ab3583baa.png)

**Comment by mwittrien** [comment]
![aaaa](https://user-images.githubusercontent.com/23700969/93976950-0af6b800-fd7a-11ea-8633-4bfd0deaabb9.gif)
no issues on my end,
make sure to close discord, remove 0BDFDB.plugin.js and ServerFolders.plugin.js and reinstalling both
