### ISSUE TITLE
[BUG] - PLUGIN - Send Large Messages

### ISSUE THREAD

**Issue by master3395** [mwittrien/BetterDiscordAddons#509]
When discord starts, this popup box comes
It shows these plugins, and the Send Large Messages is one of them.

![image](https://user-images.githubusercontent.com/4199669/94044319-4327e600-fdce-11ea-8dc0-64ade26dec91.png)

**Comment by alsoGAMER** [comment]
Try to update all of them

**Comment by mwittrien** [comment]
Manually redownload the plugin
