### ISSUE TITLE
[BUG] - BDFDB.min.js

### ISSUE THREAD

**Issue by alsoGAMER** [mwittrien/BetterDiscordAddons#513]
**Describe the bug**
```
[EnhancedDiscord] Failed to load BDFDB.min.js: Error: Plugin must have a name and load() function.
Error: Plugin must have a name and load() function.
    at process.<anonymous> (/home/USER/Documents/EnhancedDiscord/dom_shit.js:107:23)
    at Object.onceWrapper (events.js:291:20)
    at process.emit (events.js:208:15)
warn @ /home/USER/Documents/EnhancedDiscord/dom_shit.js:31
```

**To Reproduce**
Start Discord with EnhancedDiscord injected and BDFDB.min.js enabled

**Expected behavior**
The plugin would load normally

**Discord Built (stable, PTB or canary):**
Stable 0.0.12

**Comment by alsoGAMER** [comment]
There's also this warn in the console:

```
[BDFDB] "ChannelAutoComplete" [name] not found in WebModules
(anonymous) @ 202cf4cccacc9609a8bc.js:16
```

**Comment by mwittrien** [comment]
BDFDB.min.js is no plugin get BDFDB.plugin.js from my library folder

**Comment by alsoGAMER** [comment]
I've dowloaded this: https://www.github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins%2FBDFDB.min.js

You've uploaded this, so I've to think that is a plugin.

**Comment by mwittrien** [comment]
No its not thats my old library
