### ISSUE TITLE
[IMPROVEMENT] - Notification Sounds plugin

### ISSUE THREAD

**Issue by Nareonith** [mwittrien/BetterDiscordAddons#515]
Notification sounds plugin switches where notification sounds come from. Normally discord notifications come from what I have selected as my preferred output device in discord but with the plugin it changes it to what my system wide default is. A fairly large annoyance as I use a mixer and if I'm playing a game or watching a video that is very quiet I will turn up my system sounds and it can be very jarring if i get a notification.
An option to have it play through the same output as discord(or just having that as the default. I don't see much reason not to) would be wonderful. Thanks for the amazing work and awesome plugins!

**Comment by mwittrien** [comment]
fixed
