### ISSUE TITLE
[BUG] - NotificationSounds - Streamer Mode Sounds

### ISSUE THREAD

**Issue by DarkWolfInsanity** [mwittrien/BetterDiscordAddons#516]
**Describe the bug**
Sounds continue to play with streamer mode on.

**To Reproduce**
Turn on streamer mode

**Expected behavior**
Streamer mode should block sounds if "Disable Sounds" is on under its settings.

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
fixed
