### ISSUE TITLE
[BUG] - PinDMs - Unable to Add/Remove

### ISSUE THREAD

**Issue by CrawfordK** [mwittrien/BetterDiscordAddons#517]
**Describe the bug**
I'm unsure when the issue began but I wanted to remove some pinned DMs from my server list and the option was gone from the right-click menu. Tested my pins within the DM window as well and it's the same issue. I'm able to remove them by clicking the pin to the right but that isn't an option for the server list. This seems to happen frequently as this is not the first time I've encountered this issue.

**To Reproduce**
Rick-click a pinned DM either in DM group or Server list, option to add/remove from either is not available in the menu.

**Expected behavior**
Right-click > Add/Remove DM from group or server list

**Screenshots**
[Example](https://i.imgur.com/7j1HZUX.png)

**Discord Build (stable, ptb or canary):**
Stable (Latest)

**Additional context**
Should I be holding off updating discord? I'm confused why this happens so often.

**Comment by mwittrien** [comment]
Reload your discord with Ctrl R
