### ISSUE TITLE
[BUG] - Image Utilities

### ISSUE THREAD

**Issue by dmaahs2017** [mwittrien/BetterDiscordAddons#518]
**Describe the bug**
Zoom Settings don't do anything:
  * Zoom Size
  * Lense
**To Reproduce**
When does the bug occur.
Never worked for me.
**Expected behavior**
I'd expect the zoom bar to zoom and and out as I drag it
I'd expect the lense size bar change the viewport size for the image
**Screenshots**

**Discord Built (stable, ptb or canary):**
Which built o discord are you using.
Stable, linux version
**Additional context**

**Comment by mwittrien** [comment]
The zoom settings are related to the zoom lense which opens if you gold down on the image
