### ISSUE TITLE
[BUG] - Plugin Repo & Message Logger

### ISSUE THREAD

**Issue by QuentinMcCarthy** [mwittrien/BetterDiscordAddons#520]
**Describe the bug**
Both of these plugins have stopped appearing in the plugins list. Similarly, both of these plugins show an error saying META not found when Discord starts.

**To Reproduce**
Place plugins in plugin folder, start Discord.

**Expected behavior**
The plugins should startup with no errors and run as normal.

**Screenshots**

**Discord Built (stable, ptb or canary):**
Stable 68558
BFD 0.3.5

**Additional context**
The "META not found" error has shown up for a few days now since the library change. I ignored it as I expected it to be rapidly fixed.

**Comment by mwittrien** [comment]
Message Logger aint my plugin and its not a supported plugin because it will get your account terminated

Just redownload PluginRepo
