### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by iblowmymind** [mwittrien/BetterDiscordAddons#522]
**Describe the bug**
The notification sounds don't play at all.

**To Reproduce**
Just open Discord.

**Expected behavior**
Sounds to play.

**Screenshots**
Well, I don't think it would be that useful in this case, since it's literally sounds.

**Discord Built (stable, ptb or canary):**
Discord 0.0.308 Stable 68640, BBD 0.3.5

**Additional context**
The console suggests this's the culprit since it's thrown whenever a sound's supposed to play: "Uncaught TypeError: Cannot read property 'getOutputVolume' of undefined"

**Comment by mwittrien** [comment]
You simply need to reload discord with Ctrl R
