### ISSUE TITLE
[IMPROVEMENT] - TUTORIALS ON HOW TO RUN THE PLUGINS

### ISSUE THREAD

**Issue by jaydenkoh** [mwittrien/BetterDiscordAddons#523]
I think it is fair to everyone who doesn’t understand on this and how to get it working properly. I also don’ know how to run the plugin. Do I have to execute node filename.plugins.js to run it?

**Comment by mwittrien** [comment]
No read the BD wiki or follow the guide in the BD server

**Comment by jaydenkoh** [comment]
May I ask what is a BD Wiki or server?
