### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by afarley4** [mwittrien/BetterDiscordAddons#524]
**Describe the bug**
Since the update today, which "No longer plays sound while in streamer mode." and "Now uses your choosen output device same as native discord.", no sounds play in discord at all. I have to disable the plugin just for normal discord connect/disconnect sounds.

**To Reproduce**
When the plugin is enabled, whenever a sound is supposed to play in discord, nothing plays.

**Expected behavior**
To play discord sounds normally unless otherwise specified which the custom sounds aren't working either.

**Screenshots**
No screenshots required.

**Discord Built (stable, ptb or canary):**
Stable 68558

**Additional context**
It only started happening after the update today.

**Comment by mwittrien** [comment]
Ctrl R
