### ISSUE TITLE
Incompatibility with GameActivityToggle

### ISSUE THREAD

**Issue by jameszie44** [mwittrien/BetterDiscordAddons#525]
Hi,
This plugin and GameActivityToggle currently aren't compatible on launch I am required to manually to disable then reenable Gameactivtytoggle due to Spotify controls. I would love to see a fix but understand if it's unreasonable; appreciate your time -James

https://github.com/Egrodo/DiscordPlugins/blob/master/GameActivityToggle.plugin.js

**Comment by Lucasamiel0406** [comment]
Observation: Even not using Spotify Controls I need to disable and renable this plugin...

**Comment by mwittrien** [comment]
The fault here is at GameActivityToggle
Report it to the dev
