### ISSUE TITLE
[BUG] - ImageUtilities Lense

### ISSUE THREAD

**Issue by tipakA** [mwittrien/BetterDiscordAddons#528]
**Describe the bug**
It's possible to get stuck with zoom lense opened without ability to close it other than reloading discord.

**To Reproduce**
When using lense, hold RMB and move the cursor - small image preview should appear under cursor.
In this state, when RMB is released, lense stays open despite releasing LMB. If you click LMB on the picture lense gets permanently stuck in place.
However, if you click outside of the image, it properly closes

**Expected behavior**
Lense should not get permanently stuck.

**Screenshots**
Video: https://sucks-to-b.eu/v8wZYo.mp4

Screenshot (on the bottom) shows stacked stuck lenses

**Discord Built (stable, ptb or canary):**
Canary 69144

**Additional context**
Issue itself probably isn't the biggest problem - just remember to not accidentally press RMB - but the fact that lenses *can* get permanently stuck is a problem.

![image](https://user-images.githubusercontent.com/31581159/95659064-f0189780-0b1e-11eb-8496-093104e19885.png)

**Comment by mwittrien** [comment]
Fixd once you redownload the plugin
