### ISSUE TITLE
[BUG] - Image Utilities does not take into account the custom location of the download folder

### ISSUE THREAD

**Issue by Huddlect** [mwittrien/BetterDiscordAddons#529]
**Describe the bug**
I moved my Downloads folder to another drive using the Path tab in its properties. Browsers etc. recognize this change, but ImageUtilities continues to download images to the old location of the download folder C:\Users\User\Downloads

**To Reproduce**
Change the path of the download folder and download an image with ImageUtilities.

**Expected behavior**
ImageUtilities should take into account the custom location of the download folder.

**Screenshots**
/

**Discord Built (stable, ptb or canary):**
stable

**Additional context**
/

**Comment by mwittrien** [comment]
ImageUtilities doesnt use the default download folder if you wanna change it then change it in the plugin settings
