### ISSUE TITLE
Request to add a search option for Derpibooru

### ISSUE THREAD

**Issue by Ryonez** [mwittrien/BetterDiscordAddons#53]
Hey there. I end up browsing servers a lot that post images from Derpibooru, but they often don't upload the full rez image with tags and I have to go find it.

I've started using Better discord and found this plugin. I was wondering if you'd be able to add it to the list of search providers please?

Some API info if needed:
https://www.derpibooru.org/pages/api

**Comment by Bluscream** [comment]
You mean the GoogleSearchReplace plugin?

**Comment by Ryonez** [comment]
Sorry, forget there's a lot of other plugins here.

No, the ReverseImageSearch plugin:
https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/ReverseImageSearch/ReverseImageSearch.plugin.js

**Comment by mwittrien** [comment]
As far as i can tell, that's specifically a site to search MLP stuff right? Seems like a way too specific for 99,9% of the users, also a bunch of NSFW content

**Comment by Ryonez** [comment]
You're right, it is. It also does contain a lot of NSFW material.

While I can understand if you wish not to add it, would you mind assisting me with adding it myself?

I don't understand enough about the search system to figure out the search url. There's a lot about json formatting there.

**Comment by mwittrien** [comment]
```
this.defaults = {
	engines: {
		Ask: 			{value:true, 	name:"Ask", 			url:"https://ask.com/web?q=" + this.textUrlReplaceString},
		Bing: 			{value:true, 	name:"Bing", 			url:"https://www.bing.com/search?q=" + this.textUrlReplaceString},
		DerpiBooru:		{value:true,	name:"DerpiBooru",		url:"https://www.derpibooru.org/search?q=" + this.textUrlReplaceString},
		DogPile:		{value:true, 	name:"DogPile", 		url:"http://www.dogpile.com/search/web?q=" + this.textUrlReplaceString},
		DuckDuckGo:		{value:true, 	name:"DuckDuckGo", 		url:"https://duckduckgo.com/?q=" + this.textUrlReplaceString},
		Google: 		{value:true, 	name:"Google", 			url:"https://www.google.com/search?q=" + this.textUrlReplaceString},
		GoogleScholar: 	{value:true, 	name:"Google Scholar", 	url:"https://scholar.google.com/scholar?q=" + this.textUrlReplaceString},
		Quora: 			{value:true, 	name:"Quora", 			url:"https://www.quora.com/search?q=" + this.textUrlReplaceString},
		Qwant: 			{value:true, 	name:"Qwant", 			url:"https://www.qwant.com/?t=all&q=" + this.textUrlReplaceString},
		Searx: 			{value:true, 	name:"Searx", 			url:"https://searx.me/?q=" + this.textUrlReplaceString},
		WolframAlpha:	{value:true, 	name:"Wolfram Alpha", 	url:"https://www.wolframalpha.com/input/?i=" + this.textUrlReplaceString},
		Yandex: 		{value:true, 	name:"Yandex", 			url:"https://yandex.com/search/?text=" + this.textUrlReplaceString},
		Yahoo: 			{value:true, 	name:"Yahoo", 			url:"https://search.yahoo.com/search?p=" + this.textUrlReplaceString},
		YouTube: 		{value:true, 	name:"YouTube", 		url:"https://www.youtube.com/results?q=" + this.textUrlReplaceString}
	}
};
```

**Comment by Ryonez** [comment]
I changed it to fit in with the image searcher, but funny enough it tries a text search with the url >.<

Any suggestions?

**Comment by mwittrien** [comment]
Oh for ReverseImageSearch, there is no way to search on DerpiBooru with a simple url as far as i can tell

**Comment by Ryonez** [comment]
Ahh, bugger. Thank you for taking some time to look into it though.
