### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by icefirex09** [mwittrien/BetterDiscordAddons#530]
**Describe the bug**
When trying to look at personal pins for all servers it redirects it immediately to channel category.
**To Reproduce**
The bug occurs in dm's, not servers

**Expected behavior**
It'll do what this gif tells you https://gyazo.com/8a8f91f6ec11a10b2cad474ccd0dc4cd

It didn't work on PTB nor on the stable version

**Comment by mwittrien** [comment]
ctrl shift i, open the console tab and then try it again
there should appear a red error in the console, post the contents in here

**Comment by mwittrien** [comment]
Closed due to inactivity
