### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by 2dgeneralspam1** [mwittrien/BetterDiscordAddons#531]
Allow people to use their own keys as the keys expire way too quickly. Also add microsoft translator.

**Comment by mwittrien** [comment]
no clue what you are talking about, next time use the report template provided by my github

**Comment by mwittrien** [comment]
only one API uses a key, if you want to use your own key then youll need to edit the plugin code
