### ISSUE TITLE
[BUG] - FriendNotifications

### ISSUE THREAD

**Issue by Auvere** [mwittrien/BetterDiscordAddons#534]
**Describe the bug**
Enabling the plugin causes Discord to crash

**To Reproduce**
Enable the plugin

**Expected behavior**
not crash

**Screenshots**
![2020-10-30_20-50-22](https://user-images.githubusercontent.com/27517093/97706998-925de680-1af1-11eb-9831-f569d61b447c.gif)
![image](https://user-images.githubusercontent.com/27517093/97707542-64c56d00-1af2-11eb-8804-196c777d03ba.png)

**Discord Built (stable, ptb or canary):**
Ptb 70710 (e57ab02)
BBD 0.3.5
Host 0.0.55
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Additional context**
no theme

**Comment by mwittrien** [comment]
fixed
