### ISSUE TITLE
[BUG] - ServerColumns v1.0.6

### ISSUE THREAD

**Issue by jpie726** [mwittrien/BetterDiscordAddons#535]
**Describe the bug**
When enabled, the servers will not change place, but the "spot" where they would normally go is still occupied, just with no useful items

**To Reproduce**
Enable ServerColumns v1.0.6 in Canary

**Expected behavior**
Fold every three servers to make a three column wide server list

**Screenshots**
![image](https://user-images.githubusercontent.com/53590846/97723362-b261bb80-1a99-11eb-8610-10a49d85beeb.png)
![image](https://user-images.githubusercontent.com/53590846/97723430-c60d2200-1a99-11eb-8945-4aa9f22c6e35.png)
![image](https://user-images.githubusercontent.com/53590846/97724086-7da23400-1a9a-11eb-8bda-aff8a8d9af37.png)

**Discord Built (stable, ptb or canary):**
Canary 70710 (e57ab02)
BBD 0.3.5
Host 0.0.284
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Comment by mwittrien** [comment]
Fixed
