### ISSUE TITLE
[BUG] - BDFDB

### ISSUE THREAD

**Issue by asorel1942** [mwittrien/BetterDiscordAddons#536]
Plugin is described as "account stealer" by Lightcord and refuses to load.
![image](https://user-images.githubusercontent.com/33983895/97748183-70e60600-1ac3-11eb-84f0-83912d75ae4a.png)

Build information:
![image](https://user-images.githubusercontent.com/33983895/97748208-7b080480-1ac3-11eb-8d7e-60d103f6f3bf.png)

**Comment by mwittrien** [comment]
Not my fault that their detection is flawed my plugins are made for BD
