### ISSUE TITLE
SeverHider does not work. 

### ISSUE THREAD

**Issue by moneybags-cloud** [mwittrien/BetterDiscordAddons#537]
The plugin seems to not work anymore. I turned my computer on and discord could not run as it was crashing and giving me an error. It would load for a sec then crash. I figured out it was this plugin. When I went to install the plugin again, discord stopped crashing, but now the plugin doesn't work. 

I tried resintalling betterdiscord. I then redownloaded SeverHider.plugin.js, 0BDFDB.plugin.js, and BDFDB.data.json, and it still did not work. 

I even tried it on the public beta testing discord client and still nothing.

**Comment by mwittrien** [comment]
Will be fixed tomorrow

**Comment by mwittrien** [comment]
Fixed
