### ISSUE TITLE
[BUG] - BDFDB 1.1.1 causes Discord to crash a few seconds after loading

### ISSUE THREAD

**Issue by 23Aaron** [mwittrien/BetterDiscordAddons#538]
Upon the initial load of Discord, the client is usable for a few seconds before crashing and giving me a reload button. The error doesn't occur on the initial discord screen, but will occur if you click on a server. Subsequent reloads will then bring you to the server, then crash after a few seconds.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/36976487/97765406-e70d5b80-1b09-11eb-8bb5-b8bd84551c86.png">

**Discord Build (stable, ptb or canary):**
Stable, 0.0.259 (macOS 11.0 DB9)
BandagedBD v1.0.5

**Additional context**
My setup was completely functional on BDFDB v1.0.9

**Comment by Jnss98b** [comment]
Can confirm this happens on Windows 10 20H1 too

**Comment by BobbyWibowo** [comment]
It's universal then, as it happens on Linux too

**Comment by BobbyWibowo** [comment]
Oh yeah to be specific, for me this only happens with Google Translate Options plugin (for some reason I thought OP already mentioned it).
I use a bunch of other DevilBro's plugins (definitely not all of them, but still a bunch), and disabling Google Translate Option plugin alone solved it for me.
The other plugins such as Badges Everywhere, Complete Timestamps, Created/Join Dates, et cetera, remain functional with BDFDB v1.1.1.

**Comment by StrahR** [comment]
> disabling Google Translate Option plugin alone solved it for me.
If I disable just the translate button in the text bar it starts working again.

**Comment by BobbyWibowo** [comment]
> If I disable just the translate button in the text bar it starts working again.

Can confirm, thanks for the input!

**Comment by yui-123** [comment]
ya disabling the button works it took me a second to figure out how to fix it as you cant access the setting without turning the mod on but you cant turn it on without crashing. you have to open the .json file for it and change "addTranslateButton" to false there for anyone coming here trying to fix it at least till a update comes out

**Comment by louga31** [comment]
The crash also occur with the BetterFolders plugin

**Comment by mwittrien** [comment]
Known and will be dealt with soon

**Comment by mwittrien** [comment]
Fixed
