### ISSUE TITLE
ServerFolders.plugin.js META not found

### ISSUE THREAD

**Issue by MidnightMarauder** [mwittrien/BetterDiscordAddons#54]
I'm sure this is just a problem with me but I don't know how to fix it. Every time I start up discord it gives me a startup error window for my plugins and themes, it says META not found for server folder pugin. Please help.

**Comment by mwittrien** [comment]
You didnt download it correctly

**Comment by MidnightMarauder** [comment]
That doesn't really help.

**Comment by Dapperboi** [comment]
im having the same problem but i copied the code instead of downloading it.

**Comment by mwittrien** [comment]
You didnt download it correctly either also make sure you arent in the V2 branch... read before u download something

**Comment by MidnightMarauder** [comment]
You didn't download it using Microsoft edge premium
