### ISSUE TITLE
[BUG] Crash error with most recent update

### ISSUE THREAD

**Issue by CharlieBuns** [mwittrien/BetterDiscordAddons#541]
Seems the most recent patch to have the plugin work again now causes discord to crash when selecting servers/right clicking servers in the server list

**Comment by SpicySalad** [comment]
I'm having the same issue

**Comment by mwittrien** [comment]
which plugin

**Comment by derrobin154** [comment]
When I delete the 0BDFDB.plugin.js it does not crash anymore. Either this is the reason or a plugin connected to it.

**Comment by mwittrien** [comment]
Then your stuff isnt up to date

**Comment by derrobin154** [comment]
That can't be because Discord / BD updates this automatically through Git.

**Comment by mwittrien** [comment]
Plugins are NOT updated automatically you need to click the update prompt

**Comment by derrobin154** [comment]
Only when I click on "Check for Updates" he says that all plugins are up to date.

**Comment by derrobin154** [comment]
I have to say, in my case Discord does not crash when selecting a server but directly at startup.

**Comment by mwittrien** [comment]
Redownload them all manually
