### ISSUE TITLE
[BUG] - Seems like GoogleTransalte and ServerHider still crash even after latest update.

### ISSUE THREAD

**Issue by fwenny** [mwittrien/BetterDiscordAddons#542]
**Describe the bug**
Clicking on random servers/channels crashes discord.

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
make sure to update them and make sure BDFDB is updated

**Comment by fwenny** [comment]
everything auto updates, so yes, its all latest. still crashes.
