### ISSUE TITLE
[BUG] - 0BDFDB

### ISSUE THREAD

**Issue by jcndenton** [mwittrien/BetterDiscordAddons#543]
**Describe the bug**
Enabling this plugin causes it to crash discord (window is left open and the error message is shown)
Disabling this plugin causes it to make all other plugins dysfunctional.
Other plugins will prompt me to download BDFDB, but even trying to do so will cause an error telling me to try that at a later time.

**To Reproduce**
Upon starting Discord, it will crash for a few seconds IF plugin if left on.
If OFF, then Discord works fine with all other plugins.

**Expected behavior**
Start normally or ask for an update.

**Screenshots**

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Only this plugin causes a crash. I have already attempted to load this plugin without all the others by removing them from my folder, yet only BDFDB causes Discord to crash.
![can't](https://user-images.githubusercontent.com/73757486/97787860-8f73fc00-1bac-11eb-96c4-37678908a478.PNG)

**Comment by mwittrien** [comment]
download it manually then
https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/0BDFDB.plugin.js
