### ISSUE TITLE
[BUG] - DisplayServersAsChannels

### ISSUE THREAD

**Issue by ColorfulPanda12** [mwittrien/BetterDiscordAddons#545]
I think this is a bug or something, or could just be a new feature, but next to the folder name there is the folder icon from the default discord. In case this is a feature it would be nice to have an option to disable it. I'll attach a screenshot.
![Screenshot 2020-11-01 001613](https://user-images.githubusercontent.com/73724386/97791116-8ba99f00-1bd7-11eb-877a-3154a31a0495.png)

**Comment by mwittrien** [comment]
Fixed
