### ISSUE TITLE
[IMPROVEMENT] - Emoji Replace - Add Support for Blobmoji

### ISSUE THREAD

**Issue by bgiesing** [mwittrien/BetterDiscordAddons#546]
[Blobmoji](https://github.com/C1710/blobmoji) is a fork of Google's old Blob emotes updated to support newer Unicode versions with new custom-made ones. It would be a nice addition to have alongside the current Google font since many people prefer the old Blob style.

**Comment by mwittrien** [comment]
Emojis used by EmojiReplace are pulled from the emojipedia and converted to the layout used by discord
So any sources other than emojipedia won't work since I won't manually download over 3000 emojis and place them in discord emoji grid format

**Comment by bgiesing** [comment]
You don't need to manually download them, all the PNG files are in the repo so if you clone the full repo or use GitHub's ZIP download, they will all be there https://github.com/C1710/blobmoji/tree/master/png/128

**Comment by mwittrien** [comment]
Yes i would need to manually download them becsuse they are 
A) not named correctly
and
B) does discord use a map png with a certain layout that would take hours to manually create
