### ISSUE TITLE
[BUG] Received messages are not translated

### ISSUE THREAD

**Issue by CWKevo** [mwittrien/BetterDiscordAddons#547]
**Name**
GoogleTranslateOptions

**Describe the bug**
Received messages are not translated

**To Reproduce**
Set your input and output language in received messages

**Expected behavior**
Messages are translated and displayed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/39010496/97851304-7dea3b80-1cf5-11eb-954e-5a8986ada0e0.png)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
This happens on a fresh install of BetterDiscord with only the Google Translate plugin & its dependency and no additional plugins

**Comment by mwittrien** [comment]
Right click a message and press translate

**Comment by CWKevo** [comment]
I figured it out, but I thought that they're supposed to be translated automatically, as they arrive. Sorry for misunderstanding, looks like another feature request then
