### ISSUE TITLE
[IMPROVEMENT] - Automatically translate incomming messages

### ISSUE THREAD

**Issue by CWKevo** [mwittrien/BetterDiscordAddons#548]
**Describe the solution you'd like**
All messages are translated automatically without the need of doing it manually.

**Describe alternatives you've considered**
The rate limit might be a problem for servers with big traffic, so at least we could make it translate messages only in channel we're in, or translate only incomming ones (new ones).

**Additional context**
🤷

**Comment by mwittrien** [comment]
No not possible
