### ISSUE TITLE
[BUG] - Showhiddenchannels stopped working

### ISSUE THREAD

**Issue by Dschogo** [mwittrien/BetterDiscordAddons#549]
**Describe the bug**
Plugin doesnt show hidden channels. This broke over night

**To Reproduce**
Just try to use the Plugin.

**Expected behavior**
Show hidden channels again

**Discord Built**
![image](https://user-images.githubusercontent.com/36862419/98303784-03544100-1fbf-11eb-89a8-5c10d7cc239c.png)

**Additional context**
Tried older plugin versions but nothing worked. I think Discord changed some names.

**Comment by Kallen-Code** [comment]
Broke for me a few minutes ago too.

**Comment by Kimimanjaro** [comment]
Same here

**Comment by Dschogo** [comment]
Update: Im on the official Betterdiscord-server. Developer (devilbro) is aware of this issue. 

He said: "Just broken till i fix it"

**Comment by Kimimanjaro** [comment]
Ok
