### ISSUE TITLE
[IMPROVEMENT] - RemoveBlockedMessages

### ISSUE THREAD

**Issue by KokYotsum** [mwittrien/BetterDiscordAddons#552]
**Describe the solution you'd like**
I would like the plugin to automatically mute blocked people who enter the channel and not play the sound of entering and exiting the channel by them.

**Describe alternatives you've considered**
If this is not possible, I would ask you to just mutate the blocked people.

**Comment by KokYotsum** [comment]
Could it be done so that the sound of the blocked people entering and exiting was not heard? Because now it's so that you can't hear everyone exiting the channel

**Comment by mwittrien** [comment]
Should be like that

**Comment by KokYotsum** [comment]
I also can't hear unlocked people exiting and entering the channel

**Comment by KokYotsum** [comment]
I mean the sound of going in and out by normal people
