### ISSUE TITLE
Plugin Does Not Work In Voice Chats

### ISSUE THREAD

**Issue by David-hosting** [mwittrien/BetterDiscordAddons#555]
The Plugin works fine in chat mention and typing, but in voice, it does not work

**Comment by mwittrien** [comment]
What plugin

**Comment by Dziq84** [comment]
he's probably after `notification sounds`,    for me either not works lately as before - I can't hear direct messages for example

**Comment by Dziq84** [comment]
I found some of these sounds are still on website, maybe just paths are changed, not sure

**Comment by mwittrien** [comment]
Has nothing to do with the issue described by the issue author

**Comment by mwittrien** [comment]
Closed due to inactivity
