### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/Personal Pins

### ISSUE THREAD

**Issue by ZLex12342** [mwittrien/BetterDiscordAddons#556]
**Describe the solution you'd like**
I would like a way to import/export all notes.

**Describe alternatives you've considered**
Other than that I don't think there could be anything else except maybe some kind of cloud save? Or just a direct file that automatically saves every note and you can just copy and have a backup of it.

**Additional context**
If the second alternative I suggest is already there can you tell where that file is located at?
Thanks

**Comment by ZLex12342** [comment]
![image](https://user-images.githubusercontent.com/74323248/98857106-3edf8700-2467-11eb-863d-752c282ebf84.png)
It seems like this file actually does that.
Just making sure, it will have every possible note I keep in there without limit right?
If yes, please answer so and also give some more info about this plugin if there is and then close the thread, Thank you.

**Comment by mwittrien** [comment]
PersonalPins.config.json contains the messages yes
