### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by DKnightX91** [mwittrien/BetterDiscordAddons#559]
**Describe the bug**
No longer works

**To Reproduce**
Just turn on the plugin and shows nothing

**Expected behavior**
To show hidden channels

**Discord Built (stable, ptb or canary):**
Stable 71447 (29091ef)

**Comment by mwittrien** [comment]
Press Ctrl R

**Comment by DKnightX91** [comment]
Have doesnt do anything
