### ISSUE TITLE
[BUG] Cant View What is In Hidden Channel.

### ISSUE THREAD

**Issue by Newcoolboys** [mwittrien/BetterDiscordAddons#562]
**Name**
In which plugin or theme does the bug occur.
ShowHiddenChannels
**Describe the bug**
You can click on the channel put it does not promt anything up
**To Reproduce**
When does the bug occur.
when you try to click on a hidden channel
**Expected behavior**
I expected for it to show chats inside the hidden channel
**Screenshots**

**Discord Built (stable, ptb or canary):**
Which built o discord are you using.
Stable

**Additional context**
No

**Comment by mwittrien** [comment]
Thats exactly how it should be since its impossible
