### ISSUE TITLE
[BUG] - PLUGIN/PINDMS

### ISSUE THREAD

**Issue by TwineAffix** [mwittrien/BetterDiscordAddons#565]
**Describe the bug**
hello, whenever I start the pin DMS plugin all my dms that are not pinned disappear I tried reinstalling the plugin reinstalling better discord but nothing helped.
**To Reproduce**
When does the bug occur?
every time i start the plug in
**Expected behavior**
to my dms which i selected to be pinned and the others stay where they are
**Screenshots**
![image](https://user-images.githubusercontent.com/74402185/99222876-b6a10f00-27e3-11eb-8baa-abddd8c096de.png)

**Discord Built (stable, ptb or canary):**
Which built o discord are you using.
stable
**Additional context**
not really

**Comment by epicfacethe3rd** [comment]
I have this issue as well
