### ISSUE TITLE
[BUG] - PLUGIN/PINDMS

### ISSUE THREAD

**Issue by roy-basmacier** [mwittrien/BetterDiscordAddons#566]
**Describe the bug**
Users are not hidden/ not shown in the dm tab (when you press the home button on discord).

**To Reproduce**
Not sure I disabled every plugin/theme but Pin DMs and the problem still persists, when I disabled the Pin DMs plugin I was able to view the users.

**Expected behavior**
I expect to see the users and my pinned users in my dms.

**Screenshots**
![image](https://user-images.githubusercontent.com/42835471/99222712-2cad7200-27f4-11eb-8825-41dbc9bc7e8a.png)

**Discord Built (stable, ptb or canary):**
Stable 71615 (583a822)
BBD 0.3.5
Host 0.0.308
Injector 0.6.2
Windows 10 64-Bit (10.0.18363)

**Comment by mwittrien** [comment]
Duplicate #565
