### ISSUE TITLE
[BUG] - ServerFolders

### ISSUE THREAD

**Issue by JohnWeak1** [mwittrien/BetterDiscordAddons#567]
**Describe the bug**
Doesn't work anymore (no icon and no second row but still has the context menu options).

**Expected behavior**
The plugin version of server folders showing up

**Discord Built (stable, ptb or canary):**
stable

**Comment by JohnWeak1** [comment]
update the server folder row shows up at the same time a the vanilla server folder like so :
![image](https://user-images.githubusercontent.com/42245432/99239289-24a50080-27fb-11eb-9edd-53b90ae7071b.png)

**Comment by mwittrien** [comment]
Fixed by updating BDFDB

**Comment by JohnWeak1** [comment]
still doesn't work after BDFDB update and reload
