### ISSUE TITLE
[BUG] - PLUGIN/PINDMS

### ISSUE THREAD

**Issue by xaikosis** [mwittrien/BetterDiscordAddons#568]
**Describe the bug**
I cant see my pins or dms whenever I open up discord.

**To Reproduce**
When does the bug occur.
Open discord.
**Expected behavior**
pins wont show up at all no matter if you reinstall everything.
**Screenshots**
![2020-11-16](https://user-images.githubusercontent.com/74550255/99264420-6da28800-27ee-11eb-8d0d-16713a716da1.png)

**Discord Built (stable, ptb or canary):**
Which built o discord are you using.
stable.
**Additional context**
its happened before, thats all.

**Comment by mwittrien** [comment]
Dulplicate #565
