### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by AshleyHunter01** [mwittrien/BetterDiscordAddons#570]
Button to toggle translate does not show anymore, (https://ashleyhunter01.com/ss/8vywb.png) I use this plugin to translate my messages to Spanish, the Translate button shows to translate back to English (https://ashleyhunter01.com/ss/13ge4.png)

**Comment by mwittrien** [comment]
Make sure its not caused by your theme or custom css
