### ISSUE TITLE
[BUG] - Image Utilities

### ISSUE THREAD

**Issue by justanothernoob4648** [mwittrien/BetterDiscordAddons#571]
**Describe the bug**
When trying to use zoom, nothing happens

**To Reproduce**
Click on an image, press the zoom button and move the scroll thing

**Expected behavior**

**Screenshots**

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**

**Comment by mwittrien** [comment]
To zoom you need to hold down on the image in the image popup

**Comment by justanothernoob4648** [comment]
I did that, nothing happened. What use to happen was a circle with the magnified area would pop up, but nothing happens now
