### ISSUE TITLE
[IMPROVEMENT] - Char Counter

### ISSUE THREAD

**Issue by NeverEndingCycle** [mwittrien/BetterDiscordAddons#573]
I wanted to request some type of setting to invert the color or add some kind of configurable shading to the counter. When using a custom theme, the counter can easily become hard to read.

![image](https://user-images.githubusercontent.com/42754840/99736270-f9c8df80-2a7a-11eb-878e-82e8b11c4acf.png)

**Comment by mwittrien** [comment]
You can style it as much as you like with css
