### ISSUE TITLE
[BUG] - LIBRARY ERROR 

### ISSUE THREAD

**Issue by Yato202010** [mwittrien/BetterDiscordAddons#575]
**Describe the bug**
the plugin manager said there are a virus in this plugin 0BDFDB

**To Reproduce**
today

**Expected behavior**
be able to load the library for use badge everywere and image utility again 

**Screenshots**
![image](https://user-images.githubusercontent.com/61349049/99783992-727f7880-2b1b-11eb-9c0d-3ac3d1712f64.png)

**Discord Built (stable, ptb or canary):**
i'm using lightcord stable

**Additional context**
yesterday everything work perfectly and today the plugin just won't load

**Comment by mwittrien** [comment]
My plugins are for BetterDiscord  not for LightCord
