### ISSUE TITLE
No Sounds

### ISSUE THREAD

**Issue by axman4711** [mwittrien/BetterDiscordAddons#576]
Hi,
I don´t really know why but I cant hear a single sound while using this Plugin. I checked everything, my sound settings, the settings in the plugin, the little mute in dnd buttons, everything, but I don´t have a single sound in Discord while this plugin is active.
Could you please help me ;-;

**Comment by mwittrien** [comment]
Just tested and works fine for me, ,make sure the global volumne isnt set to 0 in the plugin

**Comment by ROBOVirus25** [comment]
I am also having this problem and the Global sound is up all the way

**Comment by axman4711** [comment]
> Just tested and works fine for me, ,make sure the global volumne isnt set to 0 in the plugin

I did check that it’s up too 100 and I don’t hear anything

**Comment by mwittrien** [comment]
Screenshot your settings

**Comment by 123awm** [comment]
So, who knows how to fix that?

**Comment by axman4711** [comment]
> Screenshot your settings

![3](https://user-images.githubusercontent.com/74794791/99900967-71814f00-2cb3-11eb-84d3-a7533e77194e.jpg)
![4](https://user-images.githubusercontent.com/74794791/99900968-7219e580-2cb3-11eb-90d5-c18226feeb03.jpg)
![5](https://user-images.githubusercontent.com/74794791/99900969-72b27c00-2cb3-11eb-8dd5-e811a31292b3.jpg)
![6](https://user-images.githubusercontent.com/74794791/99900971-72b27c00-2cb3-11eb-81b4-3b1234d2961e.jpg)
![1](https://user-images.githubusercontent.com/74794791/99900973-734b1280-2cb3-11eb-978c-e1a6f4f12767.jpg)
![2](https://user-images.githubusercontent.com/74794791/99900974-734b1280-2cb3-11eb-9adc-9751e9a6d746.jpg)

tell me if u need more

**Comment by mwittrien** [comment]
Fixed
