### ISSUE TITLE
[BUG] - MessageUtilities v1.8.0

### ISSUE THREAD

**Issue by Maximilian1271** [mwittrien/BetterDiscordAddons#577]
**Describe the bug**
Odd behaviour concerning the saving of plugin settings. Seemingly, plugin settings rarely get saved properly. Some default behaviour cannot be changed directly from the plugin settings and requires editing of the config file itself.
Many default settings will never clear or change, as can be observed by checking the config.json itself. Objects such as "settings":{"Copy_Link":true,}) cannot be changed for instance (or so i believe? It is really hard to get consistent results with this)

**To Reproduce**
Enter "settings" of the plugin -> try to set any setting -> some parameters (such as any toast settings) won't be properly saved. 

**Expected behavior**
The settings should be written to the config files properly and the default values should be overwritten by custom set values

**Screenshots**
These errors _should_ be linked to Message Utilities. Although, i am not 100% sure.
![unknown (4)](https://user-images.githubusercontent.com/1573345/99891145-014cdc00-2c67-11eb-90f1-fc0c4d570ed0.png)

These are most certainly linked to Message Utilities.
![image](https://user-images.githubusercontent.com/1573345/99891166-453fe100-2c67-11eb-902f-e3fd7e2e133b.png)

**Discord Built (stable, ptb or canary):**
Stable 72071 (6cb1462)

**Comment by mwittrien** [comment]
Redownload BDFDB and MessageUtilities
The red errors are not related to my stuff

**Comment by Maximilian1271** [comment]
> Redownload BDFDB and MessageUtilities
> The red errors are not related to my stuff

cheers mate, will do
