### ISSUE TITLE
[BUG] Custom Quoter: Quote Button Not appearing

### ISSUE THREAD

**Issue by DraconicNEO** [mwittrien/BetterDiscordAddons#579]
**Name**
Custom Quoter - DevilBro

**Describe the bug**
The Quote button does not appear in the right click menu

**To Reproduce**
Always

**Expected behavior**
The Quote button is supposed to show up in the right click menu.

**Screenshots**

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**

**Comment by mwittrien** [comment]
Just tested

Quote button is there when
Right clicking a message
Using the 3-dot message option button
Holding shift while hovering over a message

**Comment by HRudyPlayZ** [comment]
This issue seems to happen to me as well, i cannot see the button when right clicking the message, using the 3-dot option button or holding shift near a message.
