### ISSUE TITLE
[Creation Date] White over white, wut

### ISSUE THREAD

**Issue by yorik100** [mwittrien/BetterDiscordAddons#58]
White creation date over white them, even tho I changed the color to black in the plugin it doesn't matter, I even changed the color to "kek" and it didn't change anything uhhh
Edit : If I change 			
".theme-light .topSectionNormal-2LlRG1 .creationDate {
				color: hsla(216,4%,74%,.6); "
to
".theme-light .topSectionNormal-2LlRG1 .creationDate {
				color: hsla(0,0%,0%,.6); "
the problem stands still in the popout but no longer when you see someone's profile

**Comment by Bluscream** [comment]
Who uses white themes anyway?

**Comment by yorik100** [comment]
Me?

**Comment by Bluscream** [comment]
smh
