### ISSUE TITLE
[BUG] - BetterFriendList - mutual servers not showing anymore 

### ISSUE THREAD

**Issue by gibmadikka** [mwittrien/BetterDiscordAddons#582]
**Describe the bug**
Mutual servers are not shown anymore. Probably Discord updates breaking it.

**To Reproduce**
Install the BetterFriendsList addon, check if "Add mutual servers in friend list" is enabled.

**Expected behavior**
Should show the mutual servers at the friends list like it used to.

**Screenshots**

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Was working a while ago, didn't notice which update broke it.

Thank you in advance!

**Comment by zaphod77** [comment]
discord itself has borked this.  it's not even working in discord unless you right click on the person IN A SERVER first.
