### ISSUE TITLE
[BUG] - PLUGIN/wontshowuporwork

### ISSUE THREAD

**Issue by BirdGaming** [mwittrien/BetterDiscordAddons#583]
**Describe the bug**
The bug is when I had it installed I used it a lot but now it's just not working. It wont let me save sounds to discord and now i deleted it and reinstalled it and it wont show up
**To Reproduce**
When does the bug occur.
every day
**Expected behavior**
i expect it to actually work properly
**Screenshots**
![image](https://user-images.githubusercontent.com/75148006/100490280-23af8100-30cf-11eb-97b4-ede7ab874312.png)
![image](https://user-images.githubusercontent.com/75148006/100490288-2f9b4300-30cf-11eb-970a-8c83866d7736.png)

**Discord Built (stable, ptb or canary):**
Which built o discord are you using.
stable
**Additional context**
nothing more

**Comment by mwittrien** [comment]
Remove the (1)
