### ISSUE TITLE
[Not working] - SendLargeMessages & FriendNotofocations

### ISSUE THREAD

**Issue by abstraverse** [mwittrien/BetterDiscordAddons#586]
**Describe the bug**
SendLarge messages - no longer working, only discord alert pops up (ss)
FriendNotofocations - LOG List  button isnt here, settings broken

**To Reproduce**
Try sending msg over 2k characters / use your eyes

**Expected behavior**
as described in plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/75224771/100554266-cfa1c980-3293-11eb-957f-567fd5bc8f14.png)
![image](https://user-images.githubusercontent.com/75224771/100554289-04158580-3294-11eb-94af-b3a42d4290a7.png)
![image](https://user-images.githubusercontent.com/75224771/100554308-23141780-3294-11eb-9c6c-276e3f557ee9.png)

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Make sure your BDFDB is up to date (v1.2.2)

**Comment by abstraverse** [comment]
Thanks, i did, but switching to BD Beta did the trick.
