### ISSUE TITLE
[IMPROVEMENT] - DisplayLargeMessages - Any .txt files

### ISSUE THREAD

**Issue by arc25275** [mwittrien/BetterDiscordAddons#587]
**An Option to allow any .txt files to be displayed**
Right now it is only "message.txt" files that work, but I think it would be beneficial to optionally allow users to have any .txt files show as text

**Comment by mwittrien** [comment]
The purpose of the plugin is to allow ppl to see messages sent via the "too large" warning
there also is no good way to check if a file is a text file or not since .txt isnt the only file type for text files
