### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by FlurinBruehwiler** [mwittrien/BetterDiscordAddons#589]
**Describe the bug**
When you open / close the settings Menu, the animation that plays in between is lagging.

**To Reproduce**
This bug occurs allways

Smooth animations like in other Themes

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
What plugin or theme are you talking about

**Comment by mwittrien** [comment]
Closed due to incorrect usage of issue template
