### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by underscore11code** [mwittrien/BetterDiscordAddons#591]
**Describe the bug**
Tags not respecting Compact Mode.
*I'm not sure if this is a feature request or a bug, feels more like a bug though*

**To Reproduce**
1. Set a tag on a user
2. Switch your UI to Compact Mode

**Expected behavior**
Tag should appear *before* the name.

**Actual behavior**
Tag appears *after* the name

**Screenshots**
Here's a tag set on myself compared with an "official" tag on a bot: https://i.imgur.com/c0xbFoX.png

**Discord Built (stable, ptb or canary):**
Stable 72814 (ef77e5c)

**Additional context**
This is a completely visual bug, tags still function, just doesn't match with bots having their tag before their name in compact mode.

**Comment by mwittrien** [comment]
Fixed

**Comment by underscore11code** [comment]
Update just got received, confirmed working as expected. Thank you very much!
