### ISSUE TITLE
[FEATURE] - NEW PLUGIN - BETTERGROUPS

### ISSUE THREAD

**Issue by hawsel** [mwittrien/BetterDiscordAddons#595]
**Describe the solution you'd like**
Seperate groups and dms

**Describe alternatives you've considered**
Ideally a tab near the top like friends for groups

**Additional context**
https://www.reddit.com/r/discordapp/comments/kb33m6/always_had_an_hard_time_locating_all_the_groups_i/

**Comment by mwittrien** [comment]
PinDMs does that
