### ISSUE TITLE
[BUG] GoogleTranslateOption

### ISSUE THREAD

**Issue by HRudyPlayZ** [mwittrien/BetterDiscordAddons#597]
**Name**
GoogleTranslateOption

**Describe the bug**
When trying to translate your own message to another language, it will end up sending the original message instead.

**To Reproduce**
1 - Configure GoogleTranslateOption to translate using the normal Google translator.
2 - Enable translation of your messages to any language
3 - Send a message, it will say "Please wait..." and end up sending the original one instead

**Expected behavior**
Using the normal Google translator, it should send the translated version instead of the normal message

**Discord Built (stable, ptb or canary):**
Discord Stable.

**Comment by mwittrien** [comment]
Then try another Translation Engine

**Comment by HRudyPlayZ** [comment]
Other translation engines work, but they don't give a translation as good as Google or TapL (even though TapL isn't in GTO anymore). The closest would be GoogleApi, but it will have a problem with some syntaxes and stuff, so it's still far from Google.

**Comment by HRudyPlayZ** [comment]
Ok it seems there's a similar error happening with the Yandex and Papago translators, though this time, they return a server error popup in addition to sending the original, where Google doesn't. It seems like only iTranslate and GoogleApi work for now...

**Comment by mwittrien** [comment]
Google was fixed
Yandex rate limit was reached since all users share the same key
Papago has a limited amount of languages so switching to it changes the set up languages and input and output can't be the same
