### ISSUE TITLE
Server Folder not showing

### ISSUE THREAD

**Issue by Ashleyz4** [mwittrien/BetterDiscordAddons#60]
Restarted discord, and one of my 3 folders is no longer shown.

This could be a possibility to the server outage that happend in one of the servers since the folder was at the bottom but I'm not sure

edit:
after the server outage went away, the folder seems to have completely deleted itself.

double edit: 
after restarting discord 3 times in a row due to some editing of stuff, the folder is suddenly back???

the issue should still be fixed none-the-less so this doesn't happen anymore

**Comment by mwittrien** [comment]
Can't fix sth that randomly happens without proper error logs
