### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by ev3nvy** [mwittrien/BetterDiscordAddons#608]
**Describe the bug**
Thumbnail of an embed is not even shown, if the width (or size in general not sure) of an image is too big. Thumbnail is top right while image is at the bottom. If the image specified is too wide, the thumbnail is not shown.

The problem seems to be the div with the class "embedWrapper-lXpS3L da-embedWrapper", which is wrapping the image (bottom), upon removal of that div, the thumbnail reappears.

**To Reproduce**
Creating a embed with discord bot allows you to add an image and a thumbnail. Setting a picture that is too wide as an image makes the thumbnail disappear.

**Expected behavior**
The thumbnail should not disappear.

**Screenshots**
Screenshot of an embed with ImageUtilities enabled (picture size: 512 x 512): https://i.imgur.com/mHuuRJP.png
Screenshot of an embed with ImageUtilities disabled (picture size: 512 x 512): https://i.imgur.com/9NwelGm.png

Screenshot of an embed with ImageUtilities enabled (picture size: 222 x 165): https://i.imgur.com/oOrL0Pl.png
Screenshot of an embed with ImageUtilities disabled (picture size: 222 x 165): https://i.imgur.com/miFSqk5.png

**Discord Built (stable, ptb or canary):**
Stable

**Comment by ev3nvy** [comment]
some further testing shows that by adding "display: contents;" to that previously mentioned problematic div, the issue is resolved, might need further testing as to not break something else

**Comment by mwittrien** [comment]
not the case for me 
might be caused ba another plugin or your theme
![image](https://user-images.githubusercontent.com/23700969/103302729-99777700-4a04-11eb-8091-9d755fa53cae.png)
