### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by iancoguz** [mwittrien/BetterDiscordAddons#613]
**Describe the solution you'd like**
Add a "Mute when Channel focused" toggle to the "New Chatmessage" sound.

**Additional context**
I would like the option to hear all messages in the current channel while Discord is focused. Currently, this option is available for all of the other message sounds (mentions, DMs) but not for regular messages. I sometimes miss new messages while using VR because the Discord client remains focused and I don't hear new message sounds.

![image](https://user-images.githubusercontent.com/15041225/103467440-19f7e980-4d1d-11eb-9b66-b3f25de5c80b.png)

**Comment by mwittrien** [comment]
I can mute sounds when discord tries to play them but i cant force discord to play them when discord doesnt play it
