### ISSUE TITLE
[BUG] - OldTitleBar Native titlebar option breaks resizing the window when the user is running an up to date copy of Windows 7 or 8

### ISSUE THREAD

**Issue by asdf2345** [mwittrien/BetterDiscordAddons#614]
If the system has the latest updates, specifically from the Security Monthly Quality Rollups sent out through Windows Update, resizing the Discord window with the native titlebar option enabled breaks, and the maximize button is greyed out.

This doesn't appear to happen if the user uses Security Only Quality updates from the Microsoft Update Catalog instead.

**Comment by mwittrien** [comment]
The behaviour of the native titlebar isnt controlled by the plugin so the issue loes somewhere else

**Comment by asdf2345** [comment]
Found this, which works as a partial fix.
http://www.digitallis.co.uk/pc/downloads/ResizeEnable.zip
