### ISSUE TITLE
[BUG] - CustomStatusPresets - No-Body Statuses not useable

### ISSUE THREAD

**Issue by Variapolis** [mwittrien/BetterDiscordAddons#618]
**Describe the bug**
Switching from any status to a preset status that has no text-body and only an emoji does not change the status.

**To Reproduce**
1. Save status with no text, just an emote as preset.
2. Switch to preset status.
3. Status doesn't change.

**Expected behavior**
1. Save status with no text, just an emote as preset.
2. Switch to preset status.
3. Status switches to chosen status.

**Screenshots**
https://i.imgur.com/LFWzaxU.gif

**Discord Built (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Fixed in 1.0.4
