### ISSUE TITLE
[BUG] - PLUGIN/SendLargeMessages

### ISSUE THREAD

**Issue by QuentiumYT** [mwittrien/BetterDiscordAddons#619]
**Describe the bug**
The plugin is not useful anymore because Discord implemented text file sending

**To Reproduce**
Write more than 2000 chars

**Expected behavior**
Should send multiple messages instead of the text file

**Screenshots**
![image](https://user-images.githubusercontent.com/35229942/104239939-92685400-545b-11eb-94ce-77e32be24629.png)

**Discord Built (stable, ptb or canary):**
stable

**Additional context**
None

**Comment by mwittrien** [comment]
It does send multiple msgs
