### ISSUE TITLE
[IMPROVEMENT] - ServerDetails - Members and bots separated 

### ISSUE THREAD

**Issue by Simoniezi** [mwittrien/BetterDiscordAddons#620]
**Describe the solution you'd like**
If possible, I would like to see a separation of bots and members on the details.

**Describe alternatives you've considered**
If not possible to separate and show both, then maybe just remove the bots from the total member count.

**Comment by mwittrien** [comment]
Not possible since discord does not separate them in their internal count

**Comment by Simoniezi** [comment]
Fair enough.
