### ISSUE TITLE
[IMPROVEMENT] - ShowHiddenChannels v2.8.7 - always closes the HIDDEN category

### ISSUE THREAD

**Issue by JadeMin** [mwittrien/BetterDiscordAddons#621]
**Describe the solution you'd like**
I would like to add a feature that always closes the HIDDEN category.

**Describe alternatives you've considered**
Add the "Always close the HIDDEN category" check box in the plugin's settings.

**Additional context**
I'm always using your plugin well. 2021 Happy new year :)

**Comment by mwittrien** [comment]
What do you mean always close it?
After you switched servers?

**Comment by JadeMin** [comment]
I mean it's a function that always collapses the "HIDDEN" category in the channel list on the servers.

**Comment by mwittrien** [comment]
Added
