### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by abstraverse** [mwittrien/BetterDiscordAddons#622]
**Describe the solution you'd like**
1. An ability to also see Custom status changes, as for
**username** changed status to **Online** *(timestamp)*
**username** changed status to **Custom: (their custom status)** *(timestamp)*
**username** changed status to **Offline** *(timestamp)*

2. An ability to differenciate between Offline and Invisible
 (ignore if impossible to do, just would be a nice feature)

3. An ability to export the list (login/out timelog) to a text file and/or backup it (so it doesnt clear with each discord restart)

**Additional context**
Thank you for your service, the plugins are amazing.

**Comment by mwittrien** [comment]
2. Not possible since that would make the invisible status pointless if discord would tell other users about it

3. Not gonna happen, the plugin isnt meant to be used to log the login behaviour of users in the log run that would be straight up stalking

**Comment by abstraverse** [comment]
Thanks for the reply, yes thats understandable. I'd still love to see #1 at some point! Feel free to close the thread, thanks again.

**Comment by mwittrien** [comment]
Done
