### ISSUE TITLE
[BUG] - Image Utilities 

### ISSUE THREAD

**Issue by leellleeell** [mwittrien/BetterDiscordAddons#625]
When moving to the next image in a series of images, when saving that image, it saves a very small version of that image

**To Reproduce**
The bug occurs every time you move to the next image and download the image.

**Expected behavior**
I expect it to save a normal size version of the image.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/62001644/104822682-5d208500-5812-11eb-8991-c8a56ff44825.PNG)
![Capture2](https://user-images.githubusercontent.com/62001644/104822688-60b40c00-5812-11eb-8fc8-511dab74e9ec.PNG)
This is what the picture saves as.
![Capture3](https://user-images.githubusercontent.com/62001644/104822691-63aefc80-5812-11eb-86cb-434a3d03e45f.PNG)
This is what the picture saves as normally.
![Capture4](https://user-images.githubusercontent.com/62001644/104822697-73c6dc00-5812-11eb-8405-4936f9ffda88.PNG)

**Discord Built (stable, ptb or canary):**
Discord Stable

**Comment by leellleeell** [comment]
Any update on this?

**Comment by mwittrien** [comment]
Ill check it tomorrow

**Comment by mwittrien** [comment]
fixed
