### ISSUE TITLE
Message color bugged - EditUsers v4.1.1 by DevilBro

### ISSUE THREAD

**Issue by Aiwenora** [mwittrien/BetterDiscordAddons#627]
**Describe the bug**
The message color is either back to the Discord basic (aka black or white depending on the theme) when in the private message and back to the role color in the server.
The name, the tag seem to work properly, though I also noted that if I hover the name of newly modified people, their name turns to white, I noticed that it is only for a single role which color is light pink, but not the others.

**To Reproduce**
The bug occurs all the time, at least for me, I tried to reinstall the plug-in, updated it, etc. The bug remains.

**Expected behavior**
With the options I selected and didn't change, the color of the text is supposed to be the same as the avatar, would it be in the private message or in the server, I checked several times and my settings don't seem to be the problem.
Beside, for some reasons for one of my tag which is light pink, the name changes color to white when I over their name in the friend list and only there

**Screenshots**
Pink name hover > http://prntscr.com/xatozv - http://prntscr.com/xatqfc
Private messages, the text should be the same color as the name > http://prntscr.com/xatrnk here are the settings > http://prntscr.com/xatueh
Server messages, the test should be the same color as the names > http://prntscr.com/xatzjp here are the settings > http://prntscr.com/xau1ln

**Discord Built (stable, ptb or canary):**
Stable 74741 (e356242)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.18363)

**Additional context**
The problem began around a week ago.

**Comment by mwittrien** [comment]
Fixed the message coloring bug

The pink to white is not a bug, the color is brighter on hover because thats the same as the native behaviour, so really bright colors will look white-ish

**Comment by Aiwenora** [comment]
Thank you so much for fixing it, my eyes feel far better ♥ !
Could you consider the possibility to change the color of a role on a server as a whole ? At times the colors picked are either too dark, too flashy or almost illisible, that would be great if we could change the color of a role directly on a server so everybody having that role have their color changed instantly.
If the feature already exists, I didn't find it yet, and I apologize for making such request.

**Comment by mwittrien** [comment]
That would be a whole new plugin idea, maybe in the future

**Comment by Aiwenora** [comment]
Thank you ! It would be like edit user with the same possibility buy like edit role, that would be amazing (people pick such weird colors for their roles I swear !
