### ISSUE TITLE
Sort by Newest?

### ISSUE THREAD

**Issue by Vastrix** [mwittrien/BetterDiscordAddons#63]
Hey, I would very much like a `Sort by Newest` option? :)

**Comment by mwittrien** [comment]
I guess you are talking about PluginRepo/ThemeRepo, i don't keep track of when plugins are uploaded to the repo channels so there is no way for me to sort it by Newest

**Comment by Vastrix** [comment]
I was indeed yes, should've mentioned, my bad :s
