### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/GoogleTranslateOption

### ISSUE THREAD

**Issue by itoffie** [mwittrien/BetterDiscordAddons#630]
**Describe the solution you'd like**
auto space on ignore texts "!"
![image](https://user-images.githubusercontent.com/64309702/105568129-02d37700-5d72-11eb-9539-7ccaba6e4b2d.png)

like the photo above. the highlighted text is the one with ignore prefix but still sticks on to the last word making translation a lil bit confusing

**Comment by mwittrien** [comment]
Just add the space yourself?

**Comment by itoffie** [comment]
> Just add the space yourself?

![image](https://user-images.githubusercontent.com/64309702/105935568-273e9480-608d-11eb-816e-855d49ff0dee.png)
i mean this happens even if i put double space in the text same thing happens

**Comment by itoffie** [comment]
@mwittrien one last tag...

**Comment by mwittrien** [comment]
Fixed

**Comment by itoffie** [comment]
thanks finally thank you very much :3
