### ISSUE TITLE
[BUG] - RemoveBlockedMessages

### ISSUE THREAD

**Issue by Vitoire** [mwittrien/BetterDiscordAddons#631]
**Describe the bug**
This plugin seems to clash with another plugin called "Send Button" by Zerebos. Once I add a Reaction to a message, it magically vanishes the very same moment. This is entirely clientside, as once either Send Button or RemoveBlockedMessages are deactivated, the Reaction shows up properly.

**To Reproduce**
Have both "Send Button" and "RemoveBlockedMessages" activated. Go to any message of your choice, can be your own, your friend's, a stranger's, in DMs or on a server. React to a message, either react to an already existing react (the counter then goes up but immediately down again) or add a new reaction. It should now vanish. Deactivate it and the reaction should display the way it should.

**Expected behavior**
With both plugins enabled, reactions should not vanish, that should be self-explanatory.

**Screenshots**
I'm not good at making gifs, it's best if you try this out yourself. https://i.imgur.com/bdlvpaf.gif

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**

**Comment by mwittrien** [comment]
Should be fixed now

**Comment by TheTrueForce** [comment]
I've had this just now without the "Send Button" plugin being present. I'm running version 1.2.1 of the plugin. I found that unchecking the Reactions slider in the Remove Elements settings stopped the problem from happening.
