### ISSUE TITLE
[BUG] BDFDB causing Crash loop

### ISSUE THREAD

**Issue by UltraBlackLinux** [mwittrien/BetterDiscordAddons#632]
Describe the Bug
The BDFDB library is recently causing a crash loop when starting up discord. It's trying to load the library, and is instandly crashing, and restarting. It works when starting discord via the terminal, for some weird reason.

To Reproduce
Install BDFDB

Expected Behavior
Just start up

Discord Version
Stable

Additional Context
Manjaro Linux, 64 Bit
BBD 0.3.5 Stable

**Comment by mwittrien** [comment]
Console logs?

**Comment by UltraBlackLinux** [comment]
> Console logs?

How am I supposed to access the console, if it's crashing all the time? It works when I run it via the terminal, so I guess there will be no errors then...
Anyways - Discord really seemed to have a stroke yesterday, it seems to work now. I will reopen this, in case of another occurrence.
Thanks!
