### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ChaoticStallion** [mwittrien/BetterDiscordAddons#637]
**Name**
Show Hidden Channels plugin

**Describe the bug**
A windows pop up that describes an issue as a syntax error on line 12 char 22. The error code is 800A03EA

**To Reproduce**
Upon installation

**Expected behavior**
An injection into BD.exe

**Screenshots**
![Capture](https://user-images.githubusercontent.com/36802437/105641874-e6a40880-5e4b-11eb-93f8-975d07978e03.PNG)

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**

**Comment by mwittrien** [comment]
Thats not how you install plugins just put them in your plugins folder, read the guide on the bd servers
