### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by patrickh39** [mwittrien/BetterDiscordAddons#638]
**Describe the bug**
The text that shows roles allowed and roles blocked is invisible.

**To Reproduce**
Right click on a hidden voice or text channel and click on channel accessibility.

**Expected behavior**
You can select which roles are allowed and blocked, etc.. The top info bar.

**Screenshots**
![df2fc90dee83335a253fa9cb9d93471a](https://user-images.githubusercontent.com/61527626/105769356-8e840980-5f12-11eb-9e9f-904cb4de78ca.gif)

**Discord Built (stable, ptb or canary):**
Stable 75056 (ead3483)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Additional context**
N/A

**Comment by mwittrien** [comment]
Thats because of your theme
