### ISSUE TITLE
[BUG] - VoiceUsersCounter

### ISSUE THREAD

**Issue by patrickh39** [mwittrien/BetterDiscordAddons#639]
**Describe the bug**
The spacing between connected users while you hover over the number, clashes with the number itself.

**To Reproduce**
1. Join a voice channel
2. Hover over connected users

**Expected behavior**
The message should be more above the number of connected users. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61527626/105769659-ff2b2600-5f12-11eb-9b18-ea289d0c030b.png)
![image](https://user-images.githubusercontent.com/61527626/105769639-f89cae80-5f12-11eb-82ab-76bd6ac96332.png)

**Discord Built (stable, ptb or canary):**
Stable 75056 (ead3483)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Additional context**
N/A

**Comment by mwittrien** [comment]
Not my plugin
