### ISSUE TITLE
[BUG] - ServerFolder

### ISSUE THREAD

**Issue by Corentin-Rougeon** [mwittrien/BetterDiscordAddons#649]
**Describe the bug**
2nd row doesn't appear upon opening a folder

**Expected behavior**
2nd row should appear with the server in the folder

**Screenshots**
https://user-images.githubusercontent.com/70999237/106355174-a84c9480-62f6-11eb-88e0-0a4314986ec6.mp4

**Discord Built (stable, ptb or canary):**
stable

**Comment by RinLovesYou** [comment]
*this issue still persists on canary for me
