### ISSUE TITLE
[IMPROVEMENT] - ShowHiddenChannels / Permissions modal

### ISSUE THREAD

**Issue by Dschogo** [mwittrien/BetterDiscordAddons#650]
**Describe the solution you'd like**

- [ ] Add a List with all users which have the view access to the channel (with search) and if you click a user it shows the exact permissions for him (enable right click of users for role changes / profile view etc.)
- [ ] When clicking a role which is permitted shows the permissions list of that role (with channel overrides (maybe in brackets behind))

**Describe alternatives you've considered**
Iam open for alternatives with similar functionality
Maybe make this a seperate plugin? (almost same as permissionsviewer by zerebos/raunzi)

**Additional context**
Should be self explaining

**Comment by mwittrien** [comment]
PermissionsViewer is already a plugin
