### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by ddivito** [mwittrien/BetterDiscordAddons#652]
today the translator button next to send disappears 

![imagen](https://user-images.githubusercontent.com/25613305/106364961-c6bb8b80-6308-11eb-9bc3-b59049b03fd3.png)

![imagen](https://user-images.githubusercontent.com/25613305/106365006-0aae9080-6309-11eb-9f6c-54aaca0c32ad.png)

Stable 75603 (8689edd)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.14393)

**Comment by mwittrien** [comment]
Fixed by updating BDFDB and reloading
