### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by mertinkotr** [mwittrien/BetterDiscordAddons#655]
**Screenshots**
![image](https://user-images.githubusercontent.com/30036432/106391778-10d36880-6400-11eb-8808-e9337f1a8880.png)

Text does not appear in the write box.

**Comment by mwittrien** [comment]
Text?

**Comment by mertinkotr** [comment]
The setting icon was displayed next to the gift box icon, but now it is missing

**Comment by mertinkotr** [comment]
Translation icon is missing

**Comment by mwittrien** [comment]
Duplicate #652
