### ISSUE TITLE
[BUG] - NotificationSounds  The Library Plugin needed for NotificationSounds is missing

### ISSUE THREAD

**Issue by ramboi234** [mwittrien/BetterDiscordAddons#658]
**Describe the bug**
The Library Plugin needed for NotificationSounds is missing.
Please click Download Now to install it.

When I click Download now, nothing happened..

**To Reproduce**
after install NotificationSounds plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/65648767/106452812-f6aa9080-64ba-11eb-844b-141337481fe8.png)

**Discord Built (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
You need to reload discord afterwards

**Comment by CRONIX228** [comment]
> You need to reload discord afterwards

download button not worked

**Comment by CRONIX228** [comment]
> You need to reload discord afterwards
![image](https://github.com/user-attachments/assets/873edf66-9087-48bd-b668-75d96a5d4c42)

**Comment by mwittrien** [comment]
> > You need to reload discord afterwards
> ![image](https://github.com/user-attachments/assets/873edf66-9087-48bd-b668-75d96a5d4c42)
> 
> 

Aint my Plugin
