### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Sekiomin** [mwittrien/BetterDiscordAddons#661]
Incoming calls don't play custom sound

trying to call someone on dms will result in the default discord sound
Using discord stable build

**Comment by mwittrien** [comment]
If you call someone then the outgoing sound plays not the incoming
Incoming plays when someone else calls you

**Comment by Sekiomin** [comment]
I asked my friend to call me and it didn't work
i checked if i set incoming call as the custom sound at it was

**Comment by Xomsi** [comment]
my friend called me to check the plugin installed everything as it should but it does not work

**Comment by mwittrien** [comment]
Make sure the plugin is up to date

**Comment by Xomsi** [comment]
plugin is up to date

**Comment by Xomsi** [comment]
don't working

**Comment by mwittrien** [comment]
whats the version number of the plugin

**Comment by Xomsi** [comment]
notification sounds 3.5.8 bdfdb 1.3.5

**Comment by mwittrien** [comment]
well try redownloading both and then reload discord,

i tried it on all discord builds and with bd stable and bd beta, works on all for me

**Comment by Xomsi** [comment]
please send me your scripts in discord Sokol# 4766

**Comment by mwittrien** [comment]
All my scripts are in this github

**Comment by Jamy-Dojer** [comment]
I've been having the same issue.
I change the incoming call sound to whatever, it even plays the correct sound when I test it in the 'notifications' tab in settings,
but whenever someone calls me, I get the default discord incoming call jingle, idk why.

**Comment by DNTRSTJM** [comment]
having the same issue

**Comment by mwittrien** [comment]
Fixed in 3.5.9
