### ISSUE TITLE
[IMPROVEMENT] - ServerDetails - Allow Hiding Users Connected to Hidden Voice Channels

### ISSUE THREAD

**Issue by Ryonez** [mwittrien/BetterDiscordAddons#664]
**Describe the solution you'd like**
Similar to issue #663, this plugin shows users who are connected to hidden voice channels in the pop out. This can lead to some confusion when you go to the server and can't see them. It would be nice to see a option to disable showing users who are in hidden voice channels from this popout as well.

**Describe alternatives you've considered**
There is no alternative other than to disable the plugin to not see them currently.

**Comment by mwittrien** [comment]
That actually wasn't even intended, was fixed in BDFDB, redownload it if you want it changed

**Comment by Ryonez** [comment]
Ahh sweet. Thank you!
