### ISSUE TITLE
[IMPROVEMENT] Top Role Everywhere - Hide "Color Roles"

### ISSUE THREAD

**Issue by Eclassic32** [mwittrien/BetterDiscordAddons#666]
Most servers have roles that places on top to just change their nicknames color, and because of that plugin can show, for example, Elite leveled people and Newbie leveled people (MEE6) having same role near them. So I suggest add a function, where we can select _color/real_ roles and plugin will _ignore/show only_ them.

**Comment by mwittrien** [comment]
What are "real" roles?

**Comment by Eclassic32** [comment]
For example, on Opera GX discord server we have stuff roles, MEE6 level roles and Achievement roles.
![image](https://user-images.githubusercontent.com/69078595/107136161-0139af80-692b-11eb-9e1f-c0f18592b102.png)
![image](https://user-images.githubusercontent.com/69078595/107136167-1282bc00-692b-11eb-9714-953130b00da7.png)

And we have Theme roles (what theme on Opera GX you use), but they don't give any new permissions or important info about user (like achievements):
![image](https://user-images.githubusercontent.com/69078595/107136224-8f159a80-692b-11eb-8d3b-9e04e9dc3666.png)

And because of Theme (Color) roles I can't understand that I'm talking with Elite/Pro role people.
![image](https://user-images.githubusercontent.com/69078595/107136352-7b1e6880-692c-11eb-8b47-cf60288f683d.png)
(Swy has Elite role color, nyoooooooo... has Pro role color)

**Comment by Eclassic32** [comment]
Oh, now when checked other servers, I don't think it is really plugin issue. It more looks like bad server design...

**Comment by mwittrien** [comment]
There is no way for the plugin to know what you see as a "real" role so this isnt something i can implement

Its a bad server design choice as you mentioned
