### ISSUE TITLE
[BUG] - BDFDB/CustomStatusPresets/EditChannels/PluginRepo/RemoveBlockedMessages/ThemeRepo/TypingIndicator

### ISSUE THREAD

**Issue by efindus** [mwittrien/BetterDiscordAddons#667]
**Describe the bug**
Plugins are not compiling because of optional chaining used in them

**To Reproduce**
Load discord with these plugins

**Expected behavior**
Plugins loading correctly

**Screenshots**
![Photo](https://user-images.githubusercontent.com/48939809/107153670-133d4180-696f-11eb-93be-7deaf8265de1.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Update your discord so it supports optional chaining

**Comment by NooberPlays** [comment]
> Update your discord so it supports optional chaining

Discord is already updated, should we change to canary?

**Comment by mwittrien** [comment]
No reinstall discord

**Comment by NooberPlays** [comment]
> No reinstall discord

Thx, it worked, sorry for creating the same ticket, I'm new to github and didn't saw there was one already created.
