### ISSUE TITLE
[BUG] - plugin Unexpected token '.'

### ISSUE THREAD

**Issue by NooberPlays** [mwittrien/BetterDiscordAddons#668]
when you try to install the plugin this appears "0BDFDB.plugin.js Could not be compiled. Unexpected token '.'"

It happens when trying to install "BadgesEverywhere

It should just install the dependency
![image](https://user-images.githubusercontent.com/62673966/107156074-bf683380-6941-11eb-9c89-f986cce17a2c.png)
![image](https://user-images.githubusercontent.com/62673966/107156077-c55e1480-6941-11eb-967e-887a4bca9e56.png)

**Discord Build (stable, ptb or canary):**
Stable discord

**Comment by mwittrien** [comment]
#667
