### ISSUE TITLE
[IMPROVEMENT] - CreationDate Date format customisation

### ISSUE THREAD

**Issue by blaise2g** [mwittrien/BetterDiscordAddons#670]
**Describe the solution you'd like**
Be able to change the date format to a different one instead of the default Discord format (e.g. ISO 8601.)

**Describe alternatives you've considered**
Being able to change the date notation in the .js file would be great although I've tried it and couldn't find anything.

**Additional context**
The ability to easily change the date format (in the settings for example) would also be great.

Thanks guys, I really enjoy using BD.

**Comment by mwittrien** [comment]
You can do that in the plugin settings
