### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by JadeMin** [mwittrien/BetterDiscordAddons#673]
**Describe the solution you'd like**
The ability to change the order in the plugin's context menu entries. 
Ex) Before: Open Link, Copy Link, View Image, Copy Image
After: View Image, Copy Image, Open Link, Copy Link

Also, the ability to Download Locations sort by drag and drop

**Describe alternatives you've considered**
Ability to change the location of desired entries and disable them by creating a grabber button to the left of entries by adding context menu entries to the plugin settings as they are.

**Additional context**
![Capture](https://user-images.githubusercontent.com/36400787/107868709-cc4cd000-6ec9-11eb-991c-bc06536c54cf.PNG)

**Comment by mwittrien** [comment]
Just no
