### ISSUE TITLE
[BUG] - Friendnotifications plugin

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#674]
**Describe the bug**
toast cards have no more a color (evrytime black)

**To Reproduce**
let a friend do something to chnage his status like online offline etc

**Expected behavior**
normal is that the card takes the color of the state (online/dnd/offline etc. before the plugin gets a update it wokrs but no more yet btw thx for the close button fix <3

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/108001700-7cffc000-6fed-11eb-8438-4287167a36a3.png)

**Discord Build (stable, ptb or canary):**
up to date

**Comment by mwittrien** [comment]
The bar has the color
