### ISSUE TITLE
[BUG] - NotificationSounds  / DefaultTheme

### ISSUE THREAD

**Issue by JayRain2** [mwittrien/BetterDiscordAddons#675]
NotificationSounds plugin crashes on Powercord when adding new sounds, plugin loads fine but crashes after opening the MP3 file.

While making a new sound and clicking "Browse" and opening the MP3 file, it crashes your entire Discord.

Your Discord will crash and the whole process will end.

Discord Canary

**Comment by mwittrien** [comment]
I am not actively supporting powercord
