### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities

### ISSUE THREAD

**Issue by Sp0lky** [mwittrien/BetterDiscordAddons#676]
**Describe the solution you'd like**
For the file type to be automatically selected when saving images/gifs/etc

**Additional context**
When saving an image, I have to manually type in the file type.
![image](https://user-images.githubusercontent.com/78141255/108172549-172c4900-7151-11eb-81ef-df6979a854b0.png)

**Comment by mwittrien** [comment]
Where exactly?

No matter which element i try they all got a filetype

**Comment by mwittrien** [comment]
Closed due to inactivity
