### ISSUE TITLE
[BUG] - Themes/BasicBackground message hover background

### ISSUE THREAD

**Issue by DragonGodGrapha** [mwittrien/BetterDiscordAddons#678]
**Describe the bug**
When variable `--messagetransparency` is set to 0, message boxes are completely invisible but message hover background (BasicBackground.css lines 895-900) remains visible. Setting the variable value to a small but nonzero number corrects the behaviour. 

**Discord Build (stable, ptb or canary):**
PTB

**Comment by mwittrien** [comment]
When you set messagetransparency to 0 the theme wont use chat bubbles ans instead will use the native behaviour and natively msgs got a slighr shade when being hovered

**Comment by DragonGodGrapha** [comment]
Prior to the last 24 hours, this behaviour could be overridden via the custom css menu in betterdiscord, but now the theme option is always loaded. Perhaps an option to disable hover background separately could be added

**Comment by mwittrien** [comment]
You can still overwrite it with css

Just need a stronger selector
