### ISSUE TITLE
[DOESN'T WORK] - ReadAllNotificationsButton

### ISSUE THREAD

**Issue by sonitaaaaa** [mwittrien/BetterDiscordAddons#679]
**Describe the bug**
Nothing happened when I clicked the button "Read all"

**To Reproduce**
Clicked "Read all"

**Expected behavior**
It should read all notifications

**Screenshots**
None

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Already reinstall, already try all settings, restart discord client.

**Comment by mwittrien** [comment]
What version is your ReadAllNotificationsButton and BDFDB

**Comment by sonitaaaaa** [comment]
> What version is your ReadAllNotificationsButton and BDFDB

ReadAllNotificationsButton is **1.6.6**
BDFDB is 1.3.9

I always keep them up to date

**Comment by sonitaaaaa** [comment]
**Updated:** I found and fixed it my self, it's just a conflic with my other plugin. The plugin it self just find, nothing broken.

**Comment by mwittrien** [comment]
What plugin
