### ISSUE TITLE
[BUG] - PLUGIN two red circles at "pending instead of one"

### ISSUE THREAD

**Issue by arfanvlk** [mwittrien/BetterDiscordAddons#683]
I
![Screenshot 2021-03-01 095814](https://user-images.githubusercontent.com/64288748/109474501-e1526300-7a74-11eb-970b-66b59a7cfaf5.png)
 don't know if it is intentional but every time I start discord there are two red circles next to 'pending' instead of one like the others
and if I have a pending request it will update the first circle and not the second one

**Comment by mwittrien** [comment]
Those are incoming and outgoing
