### ISSUE TITLE
[BUG] - multiple plugins

### ISSUE THREAD

**Issue by abstraverse** [mwittrien/BetterDiscordAddons#687]
**Describe the bug**
Multiple plugins seem to not be working, examples i found are Red all notification plugin, FriendNotifications, Creation date, Last message date, Badges Everywhere but i think theres more. Only plugin i see working rn is Toggle game activity, additionally a few setting menus disappeared (SS of what happens when i click on SETTINGS under friendnotifications):
![image](https://user-images.githubusercontent.com/75224771/109957523-5a57f180-7ce5-11eb-817b-f70a9c5dc21e.png)

![image](https://user-images.githubusercontent.com/75224771/109957506-562bd400-7ce5-11eb-8961-2308771c617e.png)
![image](https://user-images.githubusercontent.com/75224771/109957710-9f7c2380-7ce5-11eb-9a1f-aed579eb65f3.png)
![image](https://user-images.githubusercontent.com/75224771/109957752-ab67e580-7ce5-11eb-9cd5-9880bcee399e.png)
![image](https://user-images.githubusercontent.com/75224771/109957761-aefb6c80-7ce5-11eb-9e95-2f229350dfc4.png)

Badges not working: 
![image](https://user-images.githubusercontent.com/75224771/109957679-98edac00-7ce5-11eb-8e62-ea204fb52c16.png)

**To Reproduce**
check if these work for you. I dont think its a user-based error as these worked yesterday and i reinstalled BD a few times.

**Discord Build (stable, ptb or canary):**
Stable 78454 (77fa498)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
BDFDB v1.4.0
Windows 10 64-Bit (10.0.19042)

**Comment by mwittrien** [comment]
Redownload BDFDB
