### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by naziemiec** [mwittrien/BetterDiscordAddons#688]
**Describe the bug**
This is a major bug. It involves it's settings. They do not appear at all, which makes the plugin useless.

**To Reproduce**
Go to the Discord settings > "Plugins" > "Settings" on "NotificationSounds" plugin.

**Expected behavior**
The plugin settings should appear normally.

**Screenshots**
https://user-images.githubusercontent.com/71344841/110016472-5a77e180-7d25-11eb-8930-62c63a8f4fc8.mp4

**Discord Build (stable, ptb or canary):**
Discord Stable 78454 (77fa498)

**Comment by mwittrien** [comment]
Update BDFDB

**Comment by naziemiec** [comment]
@mwittrien Actually, BetterDiscord reinstallation fixed this issue.
