### ISSUE TITLE
BDFDB v1.4.3

### ISSUE THREAD

**Issue by Blade23445** [mwittrien/BetterDiscordAddons#690]
**Describe the bug**
New update causing certain keyboard shortcuts to completely crash discord

**To Reproduce**
When does the bug occur.

Yesterday it was Ctrl+V although today it's Shift+Enter

**Expected behavior**
Discord to not crash while using keyboard shortcuts Ctrl+V to paste and Shift+Enter to change lines for messages

**Screenshots**

N/A

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

Stable branch

**Additional context**

N/A

**Comment by mwittrien** [comment]
Not an issue of BDFDB
Just reinstall BD
