### ISSUE TITLE
[Links show up black] - BasicBackground

### ISSUE THREAD

**Issue by appeal0400** [mwittrien/BetterDiscordAddons#692]
**When links are sent in discord channel the text color of them is very dark**
With any link sent in a text channel, the text is very hard to read because the text color is dark

**To Reproduce**
When A link is sent

**Expected behavior**
The link should show up the same color as regular message text

**Fix**
Add `--text-link: 255,255,255; /*Link color*/` under the root in `BasicBackground.theme.css`

**Screenshots**
![image](https://user-images.githubusercontent.com/79180961/110250916-98eae780-7f43-11eb-8ad0-72ce121e58c3.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Links use the accentcolor thats intended

If you want a different color set --text-link manually
