### ISSUE TITLE
[IMPROVEMENT] - GoogleTranslateOption

### ISSUE THREAD

**Issue by itoffie** [mwittrien/BetterDiscordAddons#695]
**Describe the solution you'd like**
automatically change Output or Input on specific channel option.

**Additional context**
like we have something like this... switching to other channel will change output/input into last known setting on that channel.

![image](https://user-images.githubusercontent.com/64309702/110450909-9da7cb00-80fe-11eb-830b-e6ddd5133ba1.png)

close if you think its not doable :/ thanks for hard work~

**Comment by TheAgs123** [comment]
How do I install it to the pc?

**Comment by mwittrien** [comment]
Added
