### ISSUE TITLE
[BUG] - Friendnotifications Plugin

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#697]
**Describe the bug**
if the option open dm if you click the status pop up dont work its just nothing happens

**To Reproduce**
you click the status pop up if someone set his status online/offline etc.

**Expected behavior**
if you click @ it its open dms if you have activate it

**Discord Build (stable, ptb or canary):**
Newest one (10.3.2021)

**Comment by mwittrien** [comment]
What version is your plugin

**Comment by mwittrien** [comment]
Just tested and works fine, redownload BDFDB and FriendNotifications

**Comment by BlueStarBRS** [comment]
i have used the last version but i see you have now relased a bug fix for that thank you
