### ISSUE TITLE
[BUG] - NotificationSounds removing BD settings

### ISSUE THREAD

**Issue by MysteriouslyMythica** [mwittrien/BetterDiscordAddons#699]
**Describe the bug**
BetterDiscord crashes right after enabling the plugin.  It makes it so I can no longer see plugins option via better discord. Even if I relaunch I still cannot see the folder.
**To Reproduce**
When launching discord
**Expected behavior**
Discord is meant to launch, I should be able to go to the plugins folder to customize

**Screenshots**
<img width="262" alt="Screen Shot 2021-03-11 at 1 50 50 AM" src="https://user-images.githubusercontent.com/80446724/110747370-455eef00-820c-11eb-8804-1c338371abd4.png">
**Discord Build (stable, ptb or canary):**
78937
BDD.0.3.5

**Comment by mwittrien** [comment]
"The plugin"?

**Comment by MysteriouslyMythica** [comment]
Yes, the plugin.. (NotificationSounds)

**Comment by MysteriouslyMythica** [comment]
Oh so sorry, I was given a direct link, and thought this whole file was for it.  But I do think you would still know what to do?

**Comment by mwittrien** [comment]
Move the plugin out of the folder `%appdata%/BetterDiscord/plugins`, reload, enabled BD beta in the bd settings and put the plugin back into the folder

**Comment by MysteriouslyMythica** [comment]
Where do I enable beta

**Comment by mwittrien** [comment]
In the bd settings

**Comment by MysteriouslyMythica** [comment]
Now the sounds play over eachother

**Comment by mwittrien** [comment]
Redownload BDFDB and NotificationSounds

**Comment by MysteriouslyMythica** [comment]
Can you send me a link to bdfdb?

**Comment by MysteriouslyMythica** [comment]
Never mind, I got it!


Thank you so much for all the help you have provided me

**Comment by mwittrien** [comment]
https://mwittrien.github.io/downloader/?library
