### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by Derasiel** [mwittrien/BetterDiscordAddons#700]
**Describe the bug**
Discord crash when clicking on someone that you block

**To Reproduce**
• Make sure the person you gonna block is connected to a voice chat
• Block that person, it disappear on the right side list but not in the voice chat channel
• click on that person
• crash

**Expected behavior**
The blocked person should disappear

**Screenshots**

**Discord Build (stable, ptb or canary):**
Stable 78937

**Additional context**
Have a great day !

**Comment by mwittrien** [comment]
The user vanishes after clicking him in the voice channel list, but it doesn't cause a crash for me

Try again and if it crashs, press ctrl shift i and check the console for any errors at the bottom
