### ISSUE TITLE
[BUG] - MessageUtilities

### ISSUE THREAD

**Issue by pie-flavor** [mwittrien/BetterDiscordAddons#702]
**Describe the bug**
Double-click editing does not work anymore.

**To Reproduce**
Set double-click to edit, and note that it does not work anymore.

**Expected behavior**
Editing.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable, latest update

**Comment by mwittrien** [comment]
Works just fine for me,
Make sure 
a) the plugin uis up to date (1.8.8) and the library bdfdb is up to date (1.4.7)
b) the plugin is enabled
c) the option to edit is enabled
d) the option to edit has no keybind registered additionaly to the dbl click bind
