### ISSUE TITLE
[BUG] - Completetimestamps/24Hours format didn't work

### ISSUE THREAD

**Issue by Nymfya** [mwittrien/BetterDiscordAddons#703]
**Describe the bug**
$time and $time12 return the same result has 12 hours system, and it's impossible to set-up 24 hours system

**Expected behavior**
i imagine $time return 24 hours system

**Screenshots**
![image](https://user-images.githubusercontent.com/30203285/111162516-818fa800-859c-11eb-8625-be89f60d68a1.png)

**Discord Build (stable, ptb or canary):**

Stable 79500 (0a6057d)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

sorry per advance for my poor english

**Comment by mwittrien** [comment]
Try redownloading BDFDB

**Comment by Nymfya** [comment]
it work ^^"

sorry for disturbing you
