### ISSUE TITLE
[BUG] - CompleteTimeStamps/Customization Options?

### ISSUE THREAD

**Issue by GamingCoookie** [mwittrien/BetterDiscordAddons#704]
Before update 1.5.5, or whichever version was up to date at 20:00 UTC, 14th of March 2021, I had my timestamps in a format like:
"$dd.$mm.$yyyy, $time" 
-> "15.03.2021, 15:48" as an example

But now all that's available is $date for the date part and that's exactly why I even installed this plugin in the first place because I don't want an American style date. I want the day, month, year not month, day, year and the dots instead of slashes.
It was previously possibly but now not anymore. I hope you can fix this :)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Press the date button

**Comment by GamingCoookie** [comment]
Oh god I am sorry. I thought it would just paste $date... Thank you for your help :)
