### ISSUE TITLE
PluginRepo notification bar broken

### ISSUE THREAD

**Issue by Chris92de** [mwittrien/BetterDiscordAddons#71]
PluginRepo says "1 of your Plugins is outdated. Check PluginRepo" but the notification bar is broken and the button doesn't work.

I have the latest version from GitHub installed.

![image](https://user-images.githubusercontent.com/5523125/39396776-e9989cee-4af4-11e8-8efc-69abe051fc61.png)

**Comment by Firecul** [comment]
Strange, it worked fine for me last night

**Comment by Gunnter** [comment]
having the same issue also better discord is out of date so we cant access the plugins menu XD

**Comment by BarterClub** [comment]
+1

**Comment by Gunnter** [comment]
This has been fixed now
