### ISSUE TITLE
[BUG] - Plugins not working

### ISSUE THREAD

**Issue by strobsund** [mwittrien/BetterDiscordAddons#710]
**Describe the bug**
Plugins load as expected, but never function, this is the same case with every other Devilbro plugin I have installed. And the BDFDB library couldn't be initiated

**Expected behavior**
The plugins should work, and it should be possible to tweak the settings. Blocked message should not be shown

**Screenshots**
![N5Zve5qBoT](https://user-images.githubusercontent.com/80835748/111482887-9acb5c80-8734-11eb-859b-325e1102647a.gif)
![Untitled](https://user-images.githubusercontent.com/80835748/111482910-9f901080-8734-11eb-95ad-9c2308022a91.jpg)

**Discord Build (stable, ptb or canary):**
Stable
![image](https://user-images.githubusercontent.com/80835748/111482998-b0408680-8734-11eb-8e0e-7e766314bc7d.png)

**Additional context**
From what I've seen, it's almost as if the library itself doesn't load, I checked for updates and nothing changed from what I can see. Thus making every plugin inoperable, thanks in advance

**Comment by mwittrien** [comment]
Ctrl R
