### ISSUE TITLE
[BUG] - EditUsers

### ISSUE THREAD

**Issue by SlastyonArtyom** [mwittrien/BetterDiscordAddons#714]
**Describe the bug**
Discord crashing by this plugin.

**To Reproduce**
After plugin load.

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
Disable AutoPlayGifs.plugin.js

**Comment by mwittrien** [comment]
Not the case for me

Make sure BDFDB and EditUsers are up to date
