### ISSUE TITLE
[BUG] - BDFDB v1.5.0/Frosted Glass v2.0.0

### ISSUE THREAD

**Issue by med9999** [mwittrien/BetterDiscordAddons#715]
**Describe the bug**
Discord crashes after the latest update for some reason

**To Reproduce**
when using text formatting syntax or going to the custom CSS in the settings

**Expected behavior**
Discord keeps crashing

**Discord Build (stable, ptb or canary):**
latest stable

**Additional context**
I think it is happening because of the BDFDB v1.5.0 plugin, not sure.

**Comment by mwittrien** [comment]
Has nothing to do with either addon you listed, simply reinstall BD to fix it
