### ISSUE TITLE
[BUG] -ImageUtilities/No longer Appearing

### ISSUE THREAD

**Issue by goldsonic** [mwittrien/BetterDiscordAddons#716]
**Describe the bug**
The drop-down for the plugin does not appear on any image anymore

**To Reproduce**
Right-clicking on any image.

**Expected behavior**
A menu to appear at the bottom of the image. This also does not work on profile images anymore.

**Screenshots**
https://i.gyazo.com/68b9e48dc8d544004f0537db4b192a6c.png
https://gyazo.com/1b6e7d40b202059167e8496518db0e3a

**Discord Build (stable, ptb or canary):**
Stable 80041 (7ea92cf)
BD 1.0.0 (086482f)
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)
ImageUtilitiesv4.3.4

**Additional context**

**Comment by mwittrien** [comment]
Your BD is heavily outdated, you need to use BBD

**Comment by mwittrien** [comment]
What version is your BDFDB

**Comment by goldsonic** [comment]
I am using the BD Beta rewrite which could be also why it doesn't work anymore.

**Comment by goldsonic** [comment]
@mwittrien Updating my BDFDB to 1.5 fixed the issue. Sorry for the bug report I thought it used to tell you when plugins were out of date...
