### ISSUE TITLE
[BUG] - PluginRepo - Updating a plugin automatically enables it

### ISSUE THREAD

**Issue by Luke18033** [mwittrien/BetterDiscordAddons#717]
**Describe the bug**
When updating a plugin through PluginRepo, it will be automatically enabled if it was turned off before. This does not happen with the built-in plugin updater.

**To Reproduce**
When a notification appears from PluginRepo that plugin updates are available, go and disable one of the listed plugins. Then go to the PluginRepo page and update it. The plugin will be re-enabled.

**Expected behavior**
Updated plugins should remain disabled if they were previously.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Then disable it in the settings in the plugin repo window

**Comment by Luke18033** [comment]
OH, I did not realize there was a separate settings window there, I just checked the normal BD settings menu. That's a little confusing.
