### ISSUE TITLE
[IMPROVEMENT] - GoogleTranslateOption

### ISSUE THREAD

**Issue by MeowMC** [mwittrien/BetterDiscordAddons#718]
**Describe the solution you'd like**
I think it would be good if there was a way to add custom languages(yes I know this may be quite difficult).

**Describe alternatives you've considered**
I have edited the actual plugin and added languages myself, but it's annoying when there's an update and it just overwrites the whole file.

**Comment by mwittrien** [comment]
What is a custom language?

**Comment by MeowMC** [comment]
Like a custom translation for something. Like for example: Adding Rot13

**Comment by mwittrien** [comment]
Sorry but i wont add make believe languages
