### ISSUE TITLE
[BUG] - PLUGIN/PERSONAL PINS

### ISSUE THREAD

**Issue by supertrio17** [mwittrien/BetterDiscordAddons#719]
**Describe the bug**
Personal pins don't work, I tried to ctrl+r

**To Reproduce**
When trying to go to settings and clicking on note icon

**Expected behavior**
Expected it to work lol

**Screenshots**
![bug1](https://user-images.githubusercontent.com/57882120/112152221-592e2c00-8be2-11eb-8079-24b5e75d0175.PNG)
![bug2](https://user-images.githubusercontent.com/57882120/112152267-677c4800-8be2-11eb-9acf-d449ac969a50.PNG)
The second screenshot is when trying to open Personal Pins

**Discord Build (STABLE):**
Latest build

**Comment by mwittrien** [comment]
What version is your BDFDB and > PersonalPins

**Comment by supertrio17** [comment]
> What version is your BDFDB and PersonalPins

Hey, It started working for some reason now, I have no Idea how,
