### ISSUE TITLE
[BUG] - Message Utilities

### ISSUE THREAD

**Issue by wilecoyote** [mwittrien/BetterDiscordAddons#731]
**Describe the bug**
Within the settings panel the CTRL key is called UNK17 and i think the SHIFT key UNK16. Even if i change them manually they revert to UNK17 and UNK16 after reopening the settings panel

**To Reproduce**
This happens on reopening the settings panel

**Expected behavior**
As you can see the keybinding in the discord context menu they should be calles CTRL and SHIFT

**Screenshots**
![BD_Message_Utilities](https://user-images.githubusercontent.com/1034673/113910088-bb894e00-97d8-11eb-95a8-1da798f4ded7.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I'm using the new BD Beta injector from here [https://github.com/BetterDiscord/Installer/releases/latest](url)

**Comment by mwittrien** [comment]
Redownload BDFDB
