### ISSUE TITLE
[IMPROVEMENT] - EditUsers

### ISSUE THREAD

**Issue by deep0d0** [mwittrien/BetterDiscordAddons#733]
**Describe the solution you'd like**
Be able to provide any image url or upload a local picture to the custom profile picture field in Edit Users 

**Describe alternatives you've considered**
Changing an alt-accounts profile picture temporarily to provide a URL to Edit Users. Works for a week or so, and then breaks when discord deletes its cache or whatever.

**Additional context**
Currently, the plugin does not accept any urls not from a discord domain. Maybe allow any url here, or allow uploading a picture directly from the clients PC

**Comment by mwittrien** [comment]
Upload your image on imgur

**Comment by deep0d0** [comment]
Imgur URL is invalid when put into Avatar field. Screenshot below.

![Screenshot 2021-04-09 091152](https://user-images.githubusercontent.com/60404672/114185493-c8f72300-9913-11eb-9c6b-90e3a26ffc86.png)

**Comment by deep0d0** [comment]
NVM, needs to be an i.imgur.com link instead of imgur link
