### ISSUE TITLE
[BUG] - CompleteTimestamps

### ISSUE THREAD

**Issue by MozarteanChaos** [mwittrien/BetterDiscordAddons#737]
**Describe the bug**
Attempting to open the plugin's settings menu results in an error, making it impossible to edit without some kind of sneaky workaround.

**To Reproduce**
Attempt to open the plugin's settings menu. The menu will fail to open properly, resulting in an error. Disabling all other plugins doesn't help, nor does uninstalling and reinstalling BD itself.

**Expected behavior**
The settings menu opening properly, allowing for the plugin to be customized.

**Screenshots**
![what the heck](https://user-images.githubusercontent.com/59808961/114249079-74928880-9991-11eb-958a-5a863905a8d4.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This is occurring in version 1.5.7. I don't know if it's present on older versions.
I'm not familiar with the console, so I don't know where the necessary information is.

**Comment by mwittrien** [comment]
Show the console output

**Comment by MozarteanChaos** [comment]
Did a bit of digging around in it; I'm pretty sure this is the error message.
![error console](https://user-images.githubusercontent.com/59808961/114269633-19e44580-9a00-11eb-977b-09625c12b971.png)
Let me know if you need more information.

**Comment by mwittrien** [comment]
Your BDFDB isnt up to date

https://mwittrien.github.io/downloader/?library

**Comment by MozarteanChaos** [comment]
Oh, that's weird.
Thanks for the help, updating that seems to have solved the issue.
