### ISSUE TITLE
[IMPROVEMENT] - BDFDB: Make the Lightcord warning less annoying

### ISSUE THREAD

**Issue by AtlasC0R3** [mwittrien/BetterDiscordAddons#738]
**Describe the solution you'd like**
Okay, I know you may hate Lightcord for many reasons, and warn its users that it may render their plugins incompatible, but this is excessive. And annoying. Just one warning should be enough, not **every time I open Lightcord to check what my friends are up to**. I think the "Okay" button should act more like a "I acknowledge" button *(THEN it would be the user's responsibility)*, and then save it in the `config.json` and never talk about it again

**Describe alternatives you've considered**
Editing the plugin file to remove the warning, but let's be honest, it's a tedious process. Every update it resets anyways.

**Additional context**
uhh, well in case you don't know what the warning looks like
![image](https://user-images.githubusercontent.com/39468657/114269233-c5c36c00-99d3-11eb-87c5-891c9dd10320.png)
also, this isn't *just* "not providing help or support", this is just screwing up someone's experience, let them use whatever they want, and not decide for them. I agree with warning users that plugins won't run perfectly on Lightcord, but I don't agree with telling them "stop lightcord and use betterdiscord", as it is their decision.
plus, talking about "breaking ToS" is unrelated to "our plugins won't run flawlessly on lightcord".

**Comment by mwittrien** [comment]
Dont use my Plugins if you use LightCord
Thanks
