### ISSUE TITLE
[BUG] - Basic Background, transparency

### ISSUE THREAD

**Issue by HeavenAintClose** [mwittrien/BetterDiscordAddons#740]
Back a few months ago, I used discord to host an image for the link to put into the file so it would be the background, but the image got deleted and my discord was transparent.

I want to know how to do this again because it won't. I assume it was a bug that got fixed, but I want a transparent discord.

**Comment by mwittrien** [comment]
Upload your image on imgur or sth silmilar

**Comment by HeavenAintClose** [comment]
What I mean is, I want to make it transparent again.
