### ISSUE TITLE
[Problem] - NotificationSounds

### ISSUE THREAD

**Issue by RealTimmy** [mwittrien/BetterDiscordAddons#741]
**Describe the bug**
A clear and concise description of what the bug is: user join and leave sounds not working.

**To Reproduce**
When does the bug occur: its not something that happenes out of the blue but just doesn't work in general.

**Expected behavior**
A clear and concise description of what you expected to happen: There is just a major problem with user join and leave not working propperly so no sound come out.

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using: Stable.

**Comment by mwittrien** [comment]
Make sure you didnt mute them in discords notification sound settings and also didnt set the volume to 0 in the plugin settings
