### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by kelvinwl** [mwittrien/BetterDiscordAddons#746]
**Describe the bug**
Previously the context menu was showing inside servers, but right now it is not.

**To Reproduce**
Right click a user profile picture inside a server.

**Expected behavior**
It is expected that the submenu for 'Image Actions' to be shown inside servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/12598286/114467440-4f379180-9bc0-11eb-9980-80ef1eeb8687.png)

**Discord Build (stable, ptb or canary):**
Stable 81648 (183bc30)
BD 1.0.0 (stable)
Host 0.0.309
Injector 0.6.0
Windows 10 64-Bit (10.0.19042)

**Additional context**
Is is shown at the friends list, as the screenshot above.
But inside a server it is not.

**Comment by mwittrien** [comment]
Delete your MessageLogger and Ctrl R

**Comment by kelvinwl** [comment]
They won't work together? 
Is it sort of incompatibility?

**Comment by mwittrien** [comment]
We do not allow MessageLoggers
