### ISSUE TITLE
[BUG] - FriendNotifications

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#749]
**Describe the bug**
multiple activitys this bug is a long time in this plugin look it my screenshots so i have waited and maked screenshots sometimes i can not chat with people because there so many pop ups multiple times and its rly anoying my friends who have this plugins to have the same problem. this problem is not only on online its on all types dnd, playing etc.

**To Reproduce**
just stay online and have friends who are active 

**Expected behavior**
i see only 1 entire and only 1 pop up no 6 or 4 or 2 fromn the same stuff

**Screenshots**
![Screenshot 2021-04-14 063046](https://user-images.githubusercontent.com/25110093/114657324-1c8cb680-9cf0-11eb-8ddf-8bff1dab7f16.png)
![image](https://user-images.githubusercontent.com/25110093/114657458-69708d00-9cf0-11eb-84ae-545dd00b5c21.png)
![image](https://user-images.githubusercontent.com/25110093/114657491-7e4d2080-9cf0-11eb-9260-89f0f128c83c.png)
![image](https://user-images.githubusercontent.com/25110093/114657512-8a38e280-9cf0-11eb-85c0-67600eed0665.png)
![image](https://user-images.githubusercontent.com/25110093/114657565-a3da2a00-9cf0-11eb-9e0c-b0245425e9b1.png)

**Discord Build (stable, ptb or canary):**
latest version

**Additional context**
sometimes some friends are 10 or more times in the log and pop ups but i have no screenshot for that 
but i hope for a fix here a many screenshots who show the bug is real since months and i tried to reinstall all and clear config and all but its still happening and my friends have the same problem

**Comment by mwittrien** [comment]
Pls send my your FriendNotifications.config.json

**Comment by BlueStarBRS** [comment]
here:
[FriendNotifications.config.zip](https://github.com/mwittrien/BetterDiscordAddons/files/6310651/FriendNotifications.config.zip)

**Comment by mwittrien** [comment]
Might be fixed with 1.6.7
