### ISSUE TITLE
[Mobile BUG] - friendnotificationsplugin

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#752]
**Describe the bug**
People who are not online with mobile shown as mobile

**To Reproduce**
A friend must go online with pc and sometimes its show up as mobile

**Expected behavior**
online as online and mobile as mobile pls

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/114770196-741c3800-9d6b-11eb-985f-6a0cc43102e7.png)
^ says mobile
![image](https://user-images.githubusercontent.com/25110093/114770214-79798280-9d6b-11eb-9fe1-7ecbe1f3d2d9.png)
^but he is  on pc online 

![image](https://user-images.githubusercontent.com/25110093/114771955-7ed7cc80-9d6d-11eb-8055-98e3f376c587.png)
^ listen to spotify on pc
![image](https://user-images.githubusercontent.com/25110093/114771993-8dbe7f00-9d6d-11eb-90ed-19a2d1e365f6.png)
^plugin says he is on mobile and listen to it (i ask him he whas only on pc and his mobile is off because his bettery is empty since some hours)

**Discord Build (stable, ptb or canary):**
latest one

**Additional context**
90% of the online alerts flagt as mobile maybe this problem is present on mobile and normal online Acounts from Friends or a glitch between that
its looks like users who have no Discord on mobile have not the bug

**Comment by mwittrien** [comment]
Fixed
