### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/SPOTIFY CONTROL

### ISSUE THREAD

**Issue by PoloNX** [mwittrien/BetterDiscordAddons#755]
Spotify is good but can you do this plugin for deezer (https://www.deezer.com) or for Freezer (one gui of deezer http://freezer.life) Freezer is very good because you can use .flac

I think you can use the api of deezer and freeze will works with it

![Capture d’écran 2021-04-17 141849](https://user-images.githubusercontent.com/57038157/115112899-da7da200-9f87-11eb-8b9f-4c561a7a3ebe.png)
freeze have a rpc on discord

**Comment by mwittrien** [comment]
No since discord has no Integration with them
