### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications/Add user changed status to online via mobile

### ISSUE THREAD

**Issue by Dragonisser** [mwittrien/BetterDiscordAddons#757]
**Describe the solution you'd like**
Currently the plugin can't distinguish between "user changed status to online via pc" and "user changed status to online via mobile". It would be nice to have latter.

**Describe alternatives you've considered**
Never heard of any other alternative

**Additional context**
-

**Comment by mwittrien** [comment]
The icon shows you whether its mobile or not

If the is online on mobile the status in the notification is the phone Symbol

**Comment by Dragonisser** [comment]
I found the issue. If the person is on idle on their pc and goes online via mobile it doesn't show "(mobile)" in the notification.

**Comment by mwittrien** [comment]
Yeah Desktop overweights mobile thats normal

**Comment by Dragonisser** [comment]
Fair enough, thanks for the explanation.
