### ISSUE TITLE
[BUG] - JoinedAtDate - Option to disable "on" in "Joined on"

### ISSUE THREAD

**Issue by Eegras** [mwittrien/BetterDiscordAddons#758]
**Describe the solution you'd like**
I use JoinedAtDate to display the number of days ago a user joined, and don't use the datetime stamp.  The phrasing is awkward.  "Joined on today", "Joined on 6 months ago".  I would like a way to customize the phrasing

Examples: 
![image](https://user-images.githubusercontent.com/6810622/115246880-e71b0b00-a0eb-11eb-91af-38dd20022e92.png)

![image](https://user-images.githubusercontent.com/6810622/115246914-ed10ec00-a0eb-11eb-96ad-ec5643275916.png)

**Comment by mwittrien** [comment]
You can already remove the "Joined on" text, disable it and add "Joined" to timestamp format
