### ISSUE TITLE
[IMPROVEMENT] - Server Hider | Only hide in Streamer Mode

### ISSUE THREAD

**Issue by VFDan** [mwittrien/BetterDiscordAddons#759]
An option in Server Hider's settings that makes the servers only hide in Streamer Mode would be helpful. This would pair perfectly with [mihabozic123's streamerModeOnGoLive](https://github.com/mihabozic123/BDplugins/blob/master/streamerModeOnGoLive/streamerModeOnGoLive.plugin.js).

**Comment by mwittrien** [comment]
Added
