### ISSUE TITLE
[BUG] - OldTitleBar

### ISSUE THREAD

**Issue by paz** [mwittrien/BetterDiscordAddons#760]
**Describe the bug**
No longer shows native title bar

**To Reproduce**
Option no longer works, and in the last update from 5 hours ago the option isnt even there

**Discord Build (stable, ptb or canary):**
Stable 82866 (d02d7ca)
BD 1.0.0 (stable)
Host 1.0.9001
Injector 0.6.0
Windows 10 64-Bit (10.0.19042)

**Comment by mwittrien** [comment]
No longer possible
