### ISSUE TITLE
[IMPROVEMENT] -Show Hidden Channels- Button to refresh the plugin

### ISSUE THREAD

**Issue by ImmortalTerror** [mwittrien/BetterDiscordAddons#761]
**Describe the solution you'd like**
A way to bind a button to refresh This plugin

**Describe alternatives you've considered**
Idk if this happens to anyone else but when I first start Discord
 the plugin does not work unless I refresh Discord. I was thinking you could add a way to bind like F4 or something to refresh just the plugin. Idk if this will fix the problem but it's worth the try and should be easy to make.
**Additional context**
I have no idea if you can even make a plugin refresh itself so if you can't, that's understandable

**Comment by mwittrien** [comment]
"The" plugin?

**Comment by ImmortalTerror** [comment]
> "The" plugin?

crap sorry i meant to post this on a certain plugin and not here

**Comment by mwittrien** [comment]
You cant post issues on certain sub folders

Issues are always repo wide

**Comment by ImmortalTerror** [comment]
> You cant post issues on certain sub folders
> 
> Issues are always repo wide

Yea sorry im new to GitHub

**Comment by mwittrien** [comment]
So which plugin

**Comment by ImmortalTerror** [comment]
> So which plugin

Just updated the title of the Issue. It's for Show Hidden Channels

**Comment by mwittrien** [comment]
What do you mean refresh?

**Comment by ImmortalTerror** [comment]
like reload the plugin

**Comment by mwittrien** [comment]
For what reason

**Comment by ImmortalTerror** [comment]
Because sometimes the hidden channels fail to load and refreshing discord fixes it and it would be cool if you could just reload the plugin

**Comment by mwittrien** [comment]
Then disable and reenable the plugin
