### ISSUE TITLE
PLUGIN/CompleteTimestamps: Add $yy and $yyyy for year

### ISSUE THREAD

**Issue by Frorran** [mwittrien/BetterDiscordAddons#762]
**Describe the solution you'd like**
Currently time displays like this for me: `4/20/2021, 5:06:25PM`, what I'd like to see would be the date and month flipped like `20/4/2021, 5:06:25PM`

**Describe alternatives you've considered**
I've tried formatting it on my own but I can't find any way to put in year. When customizing so I'm left with only day, month and time.

**Comment by mwittrien** [comment]
You can change the date as much ad you like kn the date formater
