### ISSUE TITLE
[IMPROVEMENT] - CompleteTimestamps for unread banner

### ISSUE THREAD

**Issue by asorel1942** [mwittrien/BetterDiscordAddons#764]
**Describe the solution you'd like**
Would it be practical to make the plugin modify the timetamps on the unread messages banner (see image below) to match the customized format?
![image](https://user-images.githubusercontent.com/33983895/115947235-51d59900-a494-11eb-8317-cd066aee982f.png)

**Comment by mwittrien** [comment]
Not possible since that time format is formated via a language string formater that formats it differently in every possible language so there is no way for me to safely replace only the date part  without possible messing it up for other languages
