### ISSUE TITLE
0BDFDB plugin is not working

### ISSUE THREAD

**Issue by Ferixy** [mwittrien/BetterDiscordAddons#766]
hey 
I'm experiencing a problem since 2 months ago , the problem is 0BDFDB.plugin is not working... 
the error that shows up:
Could not initiate BDFDB Library Plugin. Check your Internet Connection and make sure GitHub isn't blocked by your Network or try disabling your VPN/Proxy.
im not using vpn and github is not blocked here(at least for now)
it's newest version of this plugin and i got it from this repo
i tried everything , reinstalled discord , reinstalled better discord or using just 1 plugin but it's not working in any way
any idea how to fix this?
thanks

**Comment by mwittrien** [comment]
Make sure you got the version 1.6.0

Try to disable your firewall and antivirus
