### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds

### ISSUE THREAD

**Issue by raffel080108** [mwittrien/BetterDiscordAddons#767]
**Describe the solution you'd like**
The plugin currently uses the same sound for when you connect to a channel and when someone else joines your channel. Please split them up into 2 seperate sounds, that you can customize seperately.

**Describe alternatives you've considered**
Just using the same sound, I guess. But it doesn't sound very good, as the sound is only ment, for when you connect and not when other users join...

**Additional context**
Nothing else to say, from my side

**Comment by mwittrien** [comment]
discord doesnt separate those two events

**Comment by raffel080108** [comment]
I know that, that is the point of my suggestion, that you try adding it seperately...

**Comment by mwittrien** [comment]
The event has no info on what User triggered the sound
