### ISSUE TITLE
[BUG] - SendLargeMessages

### ISSUE THREAD

**Issue by TheCuteFoxxy** [mwittrien/BetterDiscordAddons#768]
**Describe the bug**
Messages sent within a code block exceeding 2000 characters, fail to send the first portion of the message, messages following still succeed

**To Reproduce**
1. Ensure `SendLargeMessages` is enabled with newline separation toggled
2. Attempt to send a DM with a message over 2000 characters *INSIDE* a codeblock
3. Observe the first message fail to send
4. Observe remaining messages send normally

**Expected behavior**
The message should be broken up and sent normally

**Screenshots**
Network Tab: https://cdn.thecutefoxxy.com/uvuUVE.png
Failed Message vs Successful Message and Clyde Notice: https://cdn.thecutefoxxy.com/Rh9bNj.png

**Discord Build (stable, ptb or canary):**
Stable 83040 (f19e353)

**Additional context**
BetterDiscord 1.1.0

Messages without the code block, still send without failing. Only messages inside a codeblock fail.

**Comment by mwittrien** [comment]
Can you send me the message you are trying to send in here

all my test with random code snippets sent just fine

**Comment by TheCuteFoxxy** [comment]
I put the code into my hastebin, it's the exact message I was sending minus the code block.

https://haste.thecutefoxxy.com/iwxqqkdyju.js

**Comment by mwittrien** [comment]
Weird it works fine for me
![image](https://user-images.githubusercontent.com/23700969/116571458-62aa6280-a90b-11eb-834c-0fc64736ce1e.png)

**Comment by mwittrien** [comment]
What Version are you using?
Can you also try it with any other Plugin disabled

**Comment by TheCuteFoxxy** [comment]
I was unable to reproduce it again after the day it was reported. Might have been a Discord API issue.

**Comment by mwittrien** [comment]
Yeah seems like it
