### ISSUE TITLE
Crashing Discord

### ISSUE THREAD

**Issue by gunacorn** [mwittrien/BetterDiscordAddons#770]
Ends up crashing discord as soon as I changed the color of a role so I could see it better with my theme. It also changed the name of the role to a bunch of numbers. 
![image](https://user-images.githubusercontent.com/62181389/116558150-20fac700-a8cd-11eb-9c64-909a33614b42.png)

**Comment by mwittrien** [comment]
No crash issue for me
If it crashes again, press Ctrl Shift i and check the console tab for red errors
