### ISSUE TITLE
[BUG] - PersonalPins

### ISSUE THREAD

**Issue by VilotStar** [mwittrien/BetterDiscordAddons#773]
**Describe the bug**
When you have a lot of pins in the JSON file saved and you open the note viewer in discord, discord will straight up crash and reopen NOT opening the menu

**To Reproduce**
I believe that it is the surplus of pins in my JSON file but cannot be sure because tests I have done do not show a difference,
using powercord with compactBD but I have tried to do this on normal BD and the same issue came up

**Expected behavior**
I expected the notes/pins menu to open up and show me my pins (also we a quite a few pins it still does lag a lot)

**Screenshots**
https://streamable.com/5kujru

**Discord Build (stable, ptb or canary):**
canary

**Additional context**
I am also using powercord with compactBD but I have tried to do this on normal BD and the same issue came up

**Comment by mwittrien** [comment]
My plugins dont work with bdCompat

Send me your .json file on discord or via email
