### ISSUE TITLE
[BUG] - ChatAliases

### ISSUE THREAD

**Issue by Kodykthx** [mwittrien/BetterDiscordAddons#775]
**Describe the bug**
When using commands like /tenor and /giphy to send a gif, discord crashes.

**To Reproduce**
Use the /giphy or /tenor command and send a gif.

**Expected behavior**
Gif is sent without crash

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I've disabled all my other themes & plugins to isolate the issue and it appears that just this plugin causes the issue.

**Comment by mwittrien** [comment]
Tested with both /tenor and /giphy, no crashs
