### ISSUE TITLE
[IMPROVEMENT] - ShowHiddenChannels

### ISSUE THREAD

**Issue by minhngoc25a** [mwittrien/BetterDiscordAddons#777]
**Describe the solution you'd like**
Make the text in the Channel Accessibility window selectable and copyable. Make the link in channel description a hyperlink (clickable link) as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/33834488/116866454-a071f880-ac35-11eb-8108-9cc2da931b01.png)
This is a hyperlink. We can only see a hidden channel's description by using the Channel Accessibility window.

**Comment by minhngoc25a** [comment]
@mwittrien Thanks for implementing but the text in the window is still not copyable or selectable.

**Comment by mwittrien** [comment]
You can make text selectable with css

**Comment by minhngoc25a** [comment]
Even if I'm able to do that with CSS, won't this be a good quality of life
feature for many users?
