### ISSUE TITLE
[BUG] - PluginRepo/ThemeRepo

### ISSUE THREAD

**Issue by PreciousWarrior** [mwittrien/BetterDiscordAddons#778]
**Describe the bug**
The plugin and theme repos don't get formatted correctly and look odd, probably because of missing CSS

**To Reproduce**
Download and install the latest versions of PluginRepo and ThemeRepo, then upon the Plugin/Theme repo in settings and the repo cards don't appear correctly.

**Expected behavior**
The repo cards should be easily readable

**Screenshots**
![image](https://user-images.githubusercontent.com/61111041/116908078-0197cd00-ac32-11eb-8bf3-c91926977eb4.png)
![Screenshot_20210503_223851](https://user-images.githubusercontent.com/61111041/116909096-3bb59e80-ac33-11eb-805a-a605ab8b7a2d.png)
![Screenshot_20210503_223905](https://user-images.githubusercontent.com/61111041/116909104-407a5280-ac33-11eb-9330-179c3e5da4c5.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by PreciousWarrior** [comment]
Github broke so Im posting imgur link for the screenshot-: https://imgur.com/a/rQmNAnR

**Comment by mwittrien** [comment]
Press Ctrl R
