### ISSUE TITLE
[BUG] - PluginRepo/ThemeRepo

### ISSUE THREAD

**Issue by Avakining** [mwittrien/BetterDiscordAddons#779]
**Describe the bug**
Version 2.2.0 crashes BetterDiscord as the plugins/themes load

**To Reproduce**
1. Make sure PluginRepo/ThemeRepo 2.2.0 is in the plugin folder
2. Start Discord with BetterDiscord enabled
3. Wait a few seconds as the plugins/themes load
4. BetterDiscord crashes with error message 
> "BetterDiscord seems to have crashed your Discord client. BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord."

This does not happen without PluginRepo and ThemeRepo. It does happen if _either_ of them are enabled.

**Expected behavior**
Discord loads as normal, with both/either plugin loading the plugins/themes

**Discord Build (stable, ptb or canary):**
Stable (0.0.262)

**Additional context**
I'm running macOS 11.3, if that matters?

**Comment by mwittrien** [comment]
Your BDFDB Plugin is not up to date, redownload it

**Comment by mwittrien** [comment]
As mentioned in the reference issue your BD might also not be up to date reinstall and make sure you are using BD 1.1.0
