### ISSUE TITLE
How do you install these plugins?

### ISSUE THREAD

**Issue by bastiel** [mwittrien/BetterDiscordAddons#78]
Before all I had to do was download the .js/.json files and place them in my plugin folder, but I can't get any of these to work. It won't show up and when I edit it to have the same extensions as my older plugins it says that the META isn't found.

**Comment by mfsoup** [comment]
Are you installing the right versions?

Try the non-V2 plugins.

**Comment by bastiel** [comment]
That might be the problem. I'll take a look at it soon.
