### ISSUE TITLE
[BUG] - PluginRepo / ThemeRepo

### ISSUE THREAD

**Issue by SoyRA** [mwittrien/BetterDiscordAddons#781]
**Describe the bug**
Literally #779, I downloaded `PluginRepo.plugin.js`, `ThemeRepo.plugin.js` and `0BDFDB.plugin.js` again and the same error still occurs.

**To Reproduce**
1. Have only PluginRepo, ThemeRepo and BDFDB installed (In my case I moved all the "plugins" content to another place and left only the 3 .js files mentioned above).
2. Start Discord with [BetterDiscord](https://github.com/BetterDiscord/Installer) installed.
3. Wait for [this](https://i.imgur.com/uEcQW9F.png) to appear in the bottom right corner.
4. After a few seconds, [this error](https://i.imgur.com/7Fm1LRC.png) appears (almost at the same time that the messages that X plugin has been started disappear, top right).

**Expected behavior**
The same thing that happened a few days ago, let PluginRepo and ThemeRepo finish loading (what appears at the bottom right) and continue using Discord normally.

**Discord Build (stable, ptb or canary):**
Stable 83364 (9af39da)
BD 1.0.0 (stable)
Host 1.0.9001
Injector 0.6.0
Windows 10 64-Bit (10.0.17763)

**Comment by mwittrien** [comment]
What version are the 3 plugins

**Comment by SoyRA** [comment]
> What version are the 3 plugins

- PluginRepo : 2.2.0
- ThemeRepo : 2.2.0
- BDFDB : 1.6.0
  - I downloaded them 15 minutes before making the issue from https://mwittrien.github.io/

**Comment by mwittrien** [comment]
Try reinstalling BD

**Comment by SoyRA** [comment]
> Try reinstalling BD

I used the Repair option, then clicked "Yes, install BD again" and now everything works. 🥳
The only change I see, besides that everything works, is that my version changed from `BD 1.0.0 (stable)` to `BetterDiscord 1.1.0`.

Restarting, closing, etc. and it still works...and after 15 minutes using Discord normally, everything works.
So solved, I should have tried that before making the issue. 😅

**// Closed & Solved.**
