### ISSUE TITLE
[BUG] - RemoveBlockedMessages - Scroll issue

### ISSUE THREAD

**Issue by Franckyi** [mwittrien/BetterDiscordAddons#783]
**Describe the bug**
It seems that when there's a new blocked (and removed) message in a channel, when clicking on the channel, the channel scrolls upwards a certain amount instead of being at the bottom of the channel. That's probably due to a broken anchor, since the channel is supposed to scroll down to a message that was removed. 

**To Reproduce**
- User 1 blocks User 2.
- User 1 goes to channel A.
- User 2 sends a message to channel B.
- User 1 goes to channel B.
- The channel is scrolled upwards.

**Expected behavior**
The channel should be scrolled to the bottom.

**Screenshots**
I don't really have any screenshots, but feel free to ask me if you need more info

**Discord Build (stable, ptb or canary):**
Stable 83364 (9af39da)

**Comment by mwittrien** [comment]
Sadly found no way to fix that
