### ISSUE TITLE
[BUG] - Notification Sounds Could Not Be Compiled

### ISSUE THREAD

**Issue by HSAK5G** [mwittrien/BetterDiscordAddons#786]
**Describe the bug**
When i download and put the js file into my discord plugins it says on discord could not be compiled.

**To Reproduce**
Install the plugin

**Expected behavior**
It works

**Comment by mwittrien** [comment]
Thats not an issue with the plugin but an issue with your BD or your local version of the plugin, if you download the plugin correctly then it should be working
