### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications

### ISSUE THREAD

**Issue by Devrill** [mwittrien/BetterDiscordAddons#788]
### Describe the solution you'd like

I think you should add feature for users to observe themselves.

### Additional context

In every older version of this plugin I could easily add myself to the observed list in this plugin. It required just one comment in the right place in plugin's code.
In fact, I used this plugin every day to look up my activity, for example when I went AFK, how much time did I spend playing x game or something. It was pretty cool to know that.
Now I don't know how to edit this plugin anymore. I'm not really good at JavaScript. I tried many many times to fix that.

### Describe alternatives you've considered

So please just add a new feature, so every user could observe their activity.
I think stalking others is stranger than stalking yourself.

> You will never have a greater or lesser dominion than that over yourself...the height of a man's success is gauged by his self-mastery

~DA VINKI

**Comment by mwittrien** [comment]
Not the point of the plugin
