### ISSUE TITLE
CompleteTimestamps plugin displaying incorrect timemode when using custom timestamp format

### ISSUE THREAD

**Issue by w4tchdoge** [mwittrien/BetterDiscordAddons#79]
This problem only occurs when timemode is changing from AM to PM and is only present when using a custom format as displayed in [this image](https://i.gyazo.com/bae03a8a20c24543c4d52dd4e4e22c2f.png). Is there a fix?

**Comment by mwittrien** [comment]
What does your custom format look like

**Comment by w4tchdoge** [comment]
What I've input into the custom format box is
`$weekdayS, $day/$month/$year, $hour:$minute:$second $timemode`

**Comment by w4tchdoge** [comment]
English, US

**Comment by mwittrien** [comment]
ah found the issue, it only occured on 12 PM, fixed in 1.1.9
