### ISSUE TITLE
[IMPROVEMENT] - SpotifyControls - Song name scrolling

### ISSUE THREAD

**Issue by KinteLiX** [mwittrien/BetterDiscordAddons#793]
**Describe the solution you'd like**
Add option to disable song name scrolling when hovered over with the mouse. Additionally also disables author name scrolling as well.

**Additional context**
![image](https://user-images.githubusercontent.com/82413444/117575645-6009f300-b0eb-11eb-81a4-b4b2d4e9e394.png)

**Comment by mwittrien** [comment]
Fixed the scrolling issues
