### ISSUE TITLE
[BUG] - Edit server fatal plugin error (no more loading)

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#794]
**Describe the bug**
the plugin can no more loaded after update

**To Reproduce**
update the plugin

**Expected behavior**
the plugin loads

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/117615606-4065df80-b16a-11eb-9908-c2a456df2ee5.png)

**Discord Build (stable, ptb or canary):**
current discord version and BD version

**Additional context**
idk whats going on i just updated and its happening after redownload too

**Comment by mwittrien** [comment]
Fixed you beed to manually redownload

**Comment by BlueStarBRS** [comment]
@mwittrien it works but BDicord savs update and if i press again on update its corupted again
