### ISSUE TITLE
[IMPROVEMENT] - EditUsers Default PFP Override

### ISSUE THREAD

**Issue by Ryonez** [mwittrien/BetterDiscordAddons#797]
**Describe the solution you'd like**
I have some friends that remove their pfp and use the default pfp. I could apply a custom avatar, but that is applied at all times. I'd like to see an option for a custom avatar to only apply when a default pfp is in use.

**Describe alternatives you've considered**
I do not currently have any alternative ideas.

**Comment by mwittrien** [comment]
The avatar of a user is same everywhere if you no longer want it to get changed by ths plugin then remove the custom icon

**Comment by Ryonez** [comment]
The point is it's selective applied if a default pfp is used. At the moment you have to manually set it, then take it off now and then to see if they've added one back.
This would be something better managed by code than doing it manually.
