### ISSUE TITLE
Not working on Powercord - ShowHiddenChannels v.2.9.7

### ISSUE THREAD

**Issue by JunjoSick** [mwittrien/BetterDiscordAddons#798]
**Describe the bug**
The plugin no longer works on Powercord (Via BetterDiscord compatibility plugin)

**Discord Build (stable, ptb or canary):**
Canary (Powercord v2)

**Additional context**
It no longer works since 2.9.7

**Comment by mwittrien** [comment]
My plugins are for BD only
