### ISSUE TITLE
[IMPROVEMENT] - PluginRepo - Option to remove "New Plugin added" Notification

### ISSUE THREAD

**Issue by datWeazel** [mwittrien/BetterDiscordAddons#799]
**Describe the solution you'd like**
![Screenshot 2021-05-11 182431](https://user-images.githubusercontent.com/3285115/117857196-cc702800-b28c-11eb-8bd6-22d699197f51.png)
It would be nice if there was an option to hide this message.
Most of the time I really don't care about new Plugins. 
If I want to know if there are new plugins I could activate the notification or simply check the plugin repo and sort by new.

**Describe alternatives you've considered**
It would at least be helpful if the notification would vanish automatically after a while.

**Comment by mwittrien** [comment]
Disable it in the repo settings
