### ISSUE TITLE
Username to the Right of the Timestamp (CompleteTimestamps plugin)

### ISSUE THREAD

**Issue by TravisS01** [mwittrien/BetterDiscordAddons#80]
![image](https://user-images.githubusercontent.com/25331987/39793041-3e55cdd0-5309-11e8-996a-b6da24f5710f.png)
![image](https://user-images.githubusercontent.com/25331987/39793079-7623b826-5309-11e8-99a1-944ee99b83fa.png)
The user with this nickname (same user both times) told me it was the first letter of the Aramaic language.
I suspect this occurs because Aramaic is read right to left, because "Campanella' in the second screenshot is still to the left of the timestamp.

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/39872444-4a2b107e-5468-11e8-817a-0f3bef9d3a8b.png)

Happens in base discord too, it's not an issue with CompleteTimestamps.
This should be reported to Discord as a Bug.

**Comment by TravisS01** [comment]
Odd, when I looked without the plugin on that specific character (aleph) displayed the character to the left of the timestamp.
When I get a chance I will look at some other RTL text in nicknames and see how it functions with and without the plugin. I will report it to Discord as a bug if it continues to display as you have shown.
