### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds Talking Start/Stop Mic Clicks

### ISSUE THREAD

**Issue by Talven81** [mwittrien/BetterDiscordAddons#800]
**Describe the solution you'd like**
Include two triggers for those who do not use Push2Talk.
Talking Start
Talking Stop

**Describe alternatives you've considered**
No alternatives for this other than Push2Talk which is redundant.

**Additional context**
I would like TeamSpeak style mic clicks for Discord so I know when I'm activating my mic, I do not use Push2Talk and mic clicks with Push2Talk is redundant, I know I'm pressing the key and it is very inconvenient with wireless mics.

**Comment by mwittrien** [comment]
The point of the plugin is to change the sounds
Not to add new sound events
