### ISSUE TITLE
Windows Script Host Syntax Error 800A03EA

### ISSUE THREAD

**Issue by TisAndrew** [mwittrien/BetterDiscordAddons#801]
**Describe the bug**
When attempting to run the plugin.js file (duoble click) I get the following error:
![image](https://user-images.githubusercontent.com/84047195/117889118-e7ea2b80-b2aa-11eb-909b-fbc4046acd5b.png)

**To Reproduce**
When opening the file. I don't know if i'm running it wrong I'm so new to this and can't even find something simple on the internet about how to actually run this.

**Expected behavior**
The program meant to be installed and allow me to view hidden channels? (as in see their names)

**Screenshots**
![image](https://user-images.githubusercontent.com/84047195/117889215-136d1600-b2ab-11eb-9a68-1b8002d39e49.png)

**Discord Build (stable, ptb or canary):**
Newest (updated)

**Comment by mwittrien** [comment]
Thats not how you install plugins 
Read the guide on https://betterdiscord.app
