### ISSUE TITLE
[IMPROVEMENT] - BetterFriendList - Change Colours

### ISSUE THREAD

**Issue by JayDwee** [mwittrien/BetterDiscordAddons#804]
**Describe the solution you'd like**
The colours are currently red and look like an alert, and ngl makes me feel anxious that I'm missing something important. Ideally only Pending will be red if greater than 0. All others should be a different colour.

**Describe alternatives you've considered**
I suggest the colours should be the discord blue/ purple (e.g. the colour behind the bot tag) or possibly green.

**Additional context**
![image](https://user-images.githubusercontent.com/30408869/118006139-ebc98c80-b342-11eb-8575-b95c1c7f0761.png)

**Comment by mwittrien** [comment]
You can change them with css
