### ISSUE TITLE
[Error 503 on preview image loading] - ThemeRepo & PluginRepo

### ISSUE THREAD

**Issue by GoudronViande24** [mwittrien/BetterDiscordAddons#805]
The preview image in the settings tab are mostly not showing up and there is only chromium's image not available icon.
Chromium console shows a load of 503 errors on loading these images.
When I open the image link in Chrome, it appears correctly.

**To Reproduce**
Open *Plugin Repo* or *Theme Repo* in the settings

**Expected behavior**
Most of the image won't load, and throw a 503 error in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/42936037/118043743-c5f0b780-b343-11eb-8f37-c7e87eba9aa8.png)

**Discord Build (stable, ptb or canary):**
Official Discord (stable) for Windows, latest version
Windows 10 latest version
No VPN or anything that could modify the connection to the server.

**Comment by mwittrien** [comment]
Will fix itself once the new api is running
