### ISSUE TITLE
[BUG] - BDFDB won't disable when I want it to.

### ISSUE THREAD

**Issue by Morthodox** [mwittrien/BetterDiscordAddons#806]
Whenever I try to disable this plugin, it won't let me. It will keep saying "BDFDB has been enabled" and "BDFDB has been disabled" simultaneously when I only clicked the on/off switch button once. This is quite annoying when I only want to use some of the plugins seldomly, rather than have them on all the time. 

**To Reproduce**
To reproduce it, all you have to do is be on the latest version of BDFDB (1.6.2) and try turning it on and off.
1. Try turning off the plugin
2. Look below and see that the plugin has been enabled and disabled simultaneously (for some reason)
3. Exit the settings
4. Go back into settings, more specifically your plugins settings
5. See that it still remains on

**Expected behavior**
I expected it to be turned off, not to be turned on all the time.

**Screenshots**
![image](https://user-images.githubusercontent.com/83331542/118265046-3e45ad00-b4eb-11eb-83f6-84760291c251.png)

**Discord Build (stable, ptb or canary):**
I'm using the stable version of Discord, latest update.

**Comment by mwittrien** [comment]
BDFDB is a Library it doesnt run on start it runs always, thats why disabling/enabling does nothing and it stays enabled
