### ISSUE TITLE
[BUG] - SHOW HIDDEN CHANNELS

### ISSUE THREAD

**Issue by Wosiu6** [mwittrien/BetterDiscordAddons#807]
**Description**
Channels that are hidden by default but allow you as particular user access to them due to the roles you have are still not accessible. Only when you turn the plugin off you can access the channels. 

**To Reproduce**
On any server where the permissions are denied to everyone but you gain a 'View Channel' permission in your specific role.

**Expected behavior**
You should be able to see the channels content if you have permission to do so without having to turn the plugin off.

**Screenshots**
![image](https://user-images.githubusercontent.com/56123376/118366090-3d6a5500-b597-11eb-9cd8-ba68520ad163.png) - view with plugin on
![image](https://user-images.githubusercontent.com/56123376/118366104-49eead80-b597-11eb-81b9-f0302add0fd6.png) - permissions on the channel
![image](https://user-images.githubusercontent.com/56123376/118366123-596df680-b597-11eb-81dc-5abe634808c5.png) - my roles as a proof
![image](https://user-images.githubusercontent.com/56123376/118366150-6ab70300-b597-11eb-8353-82acc73fadbb.png) - view with the plugin turned off

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
-

**Comment by mwittrien** [comment]
in your screenshot are two different channels

high-keys-grp and high-keys-group

I justed tested it and can't reconstruct your issue

**Comment by Wosiu6** [comment]
True, there was an ambiguity of channel naming in the server I was testing it in.
