### ISSUE TITLE
[BUG] - PLUGIN/SpotifyControls

### ISSUE THREAD

**Issue by evka745** [mwittrien/BetterDiscordAddons#809]
**Describe the bug**
Name of the song and also the artist name keep on scroll even after going on big mode

**To Reproduce**
When going from small to big mode

**Expected behavior**
Left in the middle

**Screenshots**
https://user-images.githubusercontent.com/82726788/118416773-420a3880-b67f-11eb-8846-d46af094b3b1.png

**Discord Build (stable, ptb or canary):**
stable

**Comment by mwittrien** [comment]
#793
