### ISSUE TITLE
[IMPROVEMENT] - ReadAllNotificationsButton add option to change position

### ISSUE THREAD

**Issue by Akorian** [mwittrien/BetterDiscordAddons#811]
I just installed this plugin for better discord. But I noticed that it adds its button after some information which is added through another plugin. This doesn't look nice.
So it would be nice if there was an option to change the position manually. 
![button](https://user-images.githubusercontent.com/37375458/118480083-11271380-b712-11eb-9e23-75f1cb96703b.PNG)

I am not familiar with js. If I were I would have edited the plugin myself.

**Comment by mwittrien** [comment]
change the position with css using the `order` property
