### ISSUE TITLE
[IMPROVEMENT] - BlurpleRecolor

### ISSUE THREAD

**Issue by PimpUigi** [mwittrien/BetterDiscordAddons#813]
I was hoping the BlurpleRecolor could also get a few features from DiscordRecolor.
The DiscordRecolor import makes selected text orange for some reason, both DiscordRecolor and BlurpleRecolor make the checkboxes in settings Blurple instead of Green like they're supposed to be.

Trying to come up with a ClassicDiscord Theme basically, but neither Import lets that happen at the moment.
Basically just trying to do the following:
```
        --font:						Whitney, Helvetica Neue, Helvetica, Arial, sans-serif;					/*	General Font				*/
	--settingsicons:			1;						/*	Use Settings Icons in User/Server/Channel Settings: 1 = yes, 0 = no			*/
	
	--accentcolor: 				114,137,218;
```

**Comment by PimpUigi** [comment]
OK then, maybe a better name for what I'm saying is OG Discord?
Because (if it wasn't clearly expressed from the code) the point is to use OG Blurple instead of the new color.

**Comment by PimpUigi** [comment]
I guess it might be easier to just ask this: what CSS code do I need to type in the DiscordRecolor CSS for the checkmarks to be green, and for text I highlight with the Mouse to have the default blue highlight around it instead of an orange highlight?

**Comment by mwittrien** [comment]
Well its how i decided i want the themes go look like 

Highlight can be changed with ::selection

Checkboxes are difficult to revert you will need to check the source code

**Comment by mwittrien** [comment]
Well its how i decided i want the themes go look like 

Highlight can be changed with ::selection

Checkboxes are difficult to revert you will need to check the source code
