### ISSUE TITLE
[BUG] - GoogleTranslateOption Can't change settings

### ISSUE THREAD

**Issue by asorel1942** [mwittrien/BetterDiscordAddons#815]
**Describe the bug**
With latest update, most configuration options for the plugin (which TL service to use, fallback TL, etc) are not visible in the settings menu. Have attempted uninstalling and reinstalling plugin, as well as restarting Discord, issue persists.

![image](https://user-images.githubusercontent.com/33983895/118858951-ac052680-b8a7-11eb-82d5-0fce73c8a0b5.png)

**Comment by mwittrien** [comment]
The settings are in translation settings popup when you click the button in the chat
