### ISSUE TITLE
[IMPROVEMENT] - DiscordRecolor compatibility

### ISSUE THREAD

**Issue by Kippenhof** [mwittrien/BetterDiscordAddons#819]
**Describe the solution you'd like**
I think the New Version moved the Image and Text to the Left, thats great, but sadly it destroys the Harmony with Dusk to Down, which is my Favorite Discord Skin-Combination

**Describe alternatives you've considered**
Recoloring Dusk to Down myself, but that takes to long, besides that the DiscordRecolor is Perfect

**Additional context**
I took a screenshot of what i am meaning.
![image](https://user-images.githubusercontent.com/54744977/119164327-98e78780-ba5c-11eb-9366-65a9a1ab8153.png)

Also i took a Screenshot of what its doing to Dusk to Down
![image](https://user-images.githubusercontent.com/54744977/119164411-b288cf00-ba5c-11eb-9d13-de72e993025e.png)

It would be nice if you could provide an other Version of the Theme, that have the Harmony with other Addons back Again :)

**Comment by mwittrien** [comment]
DiscordRecolor is a full theme and shouldnt be used with another full theme, this is also how the userpopout will natively look in a future update by discord that will soon get released

**Comment by Kippenhof** [comment]
> DiscordRecolor is a full theme and shouldnt be used with another full theme, this is also how the userpopout will natively look in a future update by discord that will soon get released

Oh, thats Sad. I used the combination half a Year now and loved it. Is there any way to get the Old Version?

**Comment by mwittrien** [comment]
Could import from an old raw file from the History Log in github
But as i said Discore is on the verge of changing it themselves as its part of the new nitro custom banner feature

**Comment by Kippenhof** [comment]
> Could import from an old raw file from the History Log in github
> But as i said Discore is on the verge of changing it themselves as its part of the new nitro custom banner feature

Okay, that Banner-Feature is completely New To me, maybe i have to Tweak Dusk to Dawn a bit, that it Harmonys with that Feature.

Thx for the help
