### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by wllpwr** [mwittrien/BetterDiscordAddons#821]
**Describe the bug**
Missing options to change the translation engine.

**To Reproduce**
Open plugin settings

**Expected behavior**
The settings menu should show all my options, so I can change to the clearly superior Deepl translation engine.

**Screenshots**
![Screenshot_20210521_163951](https://user-images.githubusercontent.com/47020362/119195786-2d4cec80-ba53-11eb-928a-b4dd675bd007.png)

**Discord Build (stable, ptb or canary):**
Stable on Linux

**Additional context**
This started happening once the Deepl engine was added.

**Comment by mwittrien** [comment]
Its in the translation settings where it always has been

**Comment by wllpwr** [comment]
It's isn't though. If you look at my screenshot you'll see that the translation settings aren't there.

**Comment by mwittrien** [comment]
The translation settings arent the plugin settings

Press the google translate icon to open the translation settings

**Comment by wllpwr** [comment]
I see, they got moved. I should've looked around a little more :) Thank you!
