### ISSUE TITLE
[BUG] - DisplayServersAsChannels : UI problem

### ISSUE THREAD

**Issue by Adelscott** [mwittrien/BetterDiscordAddons#823]
**Describe the bug**
Problem on top of the list : home is not displayed like other servers

**To Reproduce**
Always

**Expected behavior**
No bug

**Screenshots**
![image](https://user-images.githubusercontent.com/10946454/119223955-72792900-bafc-11eb-864e-aff348085670.png)

**Discord Build (stable, ptb or canary):**
Stable 85712 (10a9883)
BetterDiscord 1.1.1
Host 1.0.9001
Windows 10 64-Bit (10.0.19043)
DisplayServersAsChannelsv1.4.9by DevilBro
BDFDBv1.6.5by DevilBro

**Additional context**
![image](https://user-images.githubusercontent.com/10946454/119224081-1662d480-bafd-11eb-9cf7-34ce4110cfbd.png)

**Comment by Adelscott** [comment]
BTW, is there any way to get rid of the "Public" button, I've never used it, and don't plan to ...

**Comment by mwittrien** [comment]
in the BD settings

**Comment by Adelscott** [comment]
Thanks !
