### ISSUE TITLE
[IMPROVEMENT] - GoogleTranslateOption

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [mwittrien/BetterDiscordAddons#825]
**Add a function to disable the automatic translation input/output for specific people/servers**
i guess there is a function that would be very useful which is to enable/disable automatic translation for input/output for specific DMs/servers ..etc as example when i enable the translation it automatically translate my messages into the language i select, but when i switch the DM i always forget to disable the translator which makes a lot of issues.

**Describe alternatives you've considered**
if this can't happen, then at least make the automatic translate for input strict only on the language i select as input, because it doesn't matter which language i write with it gets translated as long as the translator is activated

**Additional context**
this is for the alternative solution.
![Image 1](https://user-images.githubusercontent.com/30704271/119265439-07f0e780-bbe7-11eb-9255-c5452d03d795.png)

**Comment by mwittrien** [comment]
There is no way to check what language you are writting in

**Comment by Ahmed-Elrayes** [comment]
oh, then at least i hope you can add the feature to allow the auto translate for specific people, servers ..etc 
since most of the time people forget to disable the translator when they switch DMS..etc

**Comment by mwittrien** [comment]
Added

**Comment by Ahmed-Elrayes** [comment]
thanks a lot <3
