### ISSUE TITLE
[BUG] - Image Utilities "Previous/Next" images not correctly ordered on Twitter embeds

### ISSUE THREAD

**Issue by Guildes** [mwittrien/BetterDiscordAddons#828]
"Display previous/next Images in the same message in the image modal" is ordered from top to down first instead of left to right on Twitter embed images.

![image_2021-05-24_054759](https://user-images.githubusercontent.com/58702287/119321997-97cc7b00-bc53-11eb-8d91-85d9802e352c.png)
![image_2021-05-24_054809](https://user-images.githubusercontent.com/58702287/119322026-9dc25c00-bc53-11eb-87cd-68c42fc9bdd3.png)
![image_2021-05-24_054818](https://user-images.githubusercontent.com/58702287/119322045-a31fa680-bc53-11eb-8c02-cec0c1b795b9.png)
![image_2021-05-24_054843](https://user-images.githubusercontent.com/58702287/119322090-b2065900-bc53-11eb-8038-2e075534e043.png)
![image_2021-05-24_054906](https://user-images.githubusercontent.com/58702287/119322145-bfbbde80-bc53-11eb-83b7-6080e2b3413d.png)

**Comment by mwittrien** [comment]
That is the correct order
