### ISSUE TITLE
[SUGGESTION] Spetial token for nick

### ISSUE THREAD

**Issue by elsamukita** [mwittrien/BetterDiscordAddons#829]
Hey!
So I was wondering if it's possible to make a "token"  that when entered in either the status or name it could display the nickname next to the custom name, for example: 
![image](https://user-images.githubusercontent.com/67649765/119580636-643e3d80-bd86-11eb-91bf-6f2a1d250ecf.png)
This would be displayed in the chat:
![image](https://user-images.githubusercontent.com/67649765/119581072-779dd880-bd87-11eb-82d7-e579ea3062cd.png)
But in dms or in places where the person doesn't have a nick it wouldn't display the nick obviously. The same could be done also with the username.

Thanks, I love ur plugins. :)

**Comment by mwittrien** [comment]
Added a switch to append the server nickname

**Comment by elsamukita** [comment]
Yes, but theres no way to have both

**Comment by mwittrien** [comment]
Yes, if you enable "show nickname", it will also show the nickname with the local nickname

**Comment by elsamukita** [comment]
oh sorry ytsm

**Comment by elsamukita** [comment]
where can I find that optiopn? Srry I cant find it¿

**Comment by mwittrien** [comment]
In the local user settings 
Make sure you got the newest version of EditUsers

**Comment by elsamukita** [comment]
amma check
