### ISSUE TITLE
[BUG] - Transparent Channels Visible

### ISSUE THREAD

**Issue by EtreniumTeam** [mwittrien/BetterDiscordAddons#830]
**Describe the bug**
Transparent channels are visible if they are clicked

**To Reproduce**
Make a channel Transparent, click on the transparent channel and click on another channel

**Expected behavior**
The channel still transparent

**Screenshots**

![channel 1](https://user-images.githubusercontent.com/83910469/119644756-8a62ec80-be1d-11eb-8d30-71d9dcac3548.JPG)
![Channel 2](https://user-images.githubusercontent.com/83910469/119644760-8afb8300-be1d-11eb-9abe-560ec41327a9.JPG)
![channel 3](https://user-images.githubusercontent.com/83910469/119644762-8afb8300-be1d-11eb-9924-6500f17c3502.JPG)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Fixed by updating BDFDB
