### ISSUE TITLE
[IMPROVEMENT] - Edit Messages (PLUGIN)

### ISSUE THREAD

**Issue by Aiden-12114** [mwittrien/BetterDiscordAddons#831]
**Describe the solution you'd like**
I would like a plugin like Edit Servers, channels and all that but for messages. I'm too lazy to use inspect 😂

**Describe alternatives you've considered**
Inspect element ig.

**Additional context**

**Comment by mwittrien** [comment]
My plugins are not to fake conversation, troll ppl or scam
