### ISSUE TITLE
[BUG] - QuickMention/MinimalCord

### ISSUE THREAD

**Issue by Ant-28** [mwittrien/BetterDiscordAddons#832]
**Describe the bug**
When enabling the ShowAllMessageButtons plugin, the mention button no longer shows up.

**To Reproduce**
Enabling ShowAllMessageButtons v1.0.0 by Kyza

**Expected behavior**
The mention button should show up alongside all the message buttons

**Screenshots**

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
None.

**Comment by mwittrien** [comment]
Sounds like an issue on kyzas part
