### ISSUE TITLE
[BUG] - Image Utilities / Extra context menu for servers, and avatars not working

### ISSUE THREAD

**Issue by Jalepers** [mwittrien/BetterDiscordAddons#833]
The context menu is not working for the server icon, people's avatars, or chat messages, rest of the plugin is working fine

When i right click 

Should have the context menu

![image](https://user-images.githubusercontent.com/31570609/119699344-4ec12600-be0f-11eb-81cd-90dbe27a959f.png)

Discord ptb

**Comment by mwittrien** [comment]
Try disabling and enabling the plugin
