### ISSUE TITLE
[BUG] - GoogleTranslateOption

### ISSUE THREAD

**Issue by QuartzWarrior** [mwittrien/BetterDiscordAddons#835]
Can't choose other engines, such as DeepL, you can only use Google Translate.

If this is not a bug, tell me.

**Comment by mwittrien** [comment]
Works just fine for me, make sure your version is up to date

**Comment by QuartzWarrior** [comment]
Huh, where does it say to change it ![here](https://user-images.githubusercontent.com/74436633/120051794-5b947400-bfdf-11eb-994c-f86f34e6fbdd.png) ?
