### ISSUE TITLE
[IMPROVEMENT] - CreationDate

### ISSUE THREAD

**Issue by Official-Darkn** [mwittrien/BetterDiscordAddons#836]
**Describe the solution you'd like**
Move CreationDate to be in the middle when viewing a profile by simply just clicking: https://i.imgur.com/l0v66kR.gif

**Describe alternatives you've considered**
Simply just move CreationDate more to the right.

**Additional context**
Picture of CreationDate being on the left and not middle: https://i.imgur.com/rcEQehs.png
Also yes I know, I'm being picky, but hey, it looks nicer when it's in the middle.

**Comment by mwittrien** [comment]
Change it yourself with css

The normal userpopout is left bounded
