### ISSUE TITLE
[BUG] - NotificationSounds - Settings Menu Unusable

### ISSUE THREAD

**Issue by Braal** [mwittrien/BetterDiscordAddons#838]
**Describe the bug**
The Settings Menu is unusable, dropdowns are squished down to ~3 characters wide, "Sound" dropdown shows no results for every Category, only default addon sounds work, can upload custom sounds, they appear under "Category" but not under "Sounds".

**To Reproduce**
When does the bug occur.
Every time I open the settings menu.

**Expected behavior**
Function as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/10623066/120061500-96bc9480-c02b-11eb-865f-4be068470d47.png)

**Discord Build (stable, ptb or canary):**
Current Stable

**Additional context**
Have uninstalled addon, Better Discord, Discord itself, removed all files related to each, redownloaded and used new, fresh files and installs, problem persists. Looked through NotificationSounds Issues, did not see this listed, apologies if it has been reported/fixed before and I just missed it.

**Comment by mwittrien** [comment]
What version is your BDFDB plugin

**Comment by Braal** [comment]
Says version 1.1.1, which is the most recent update I've received.

**Comment by mwittrien** [comment]
BDFDB not BD

BDFDB is my Library Plugin

**Comment by Braal** [comment]
Whoops, sorry! 1.6.6, although when I opened Discord after work today, it seems to be fine again. Whatever it was, it seems to have fixed itself. I appreciate the help!
