### ISSUE TITLE
[BUG] - OldTitleBar - No option to display native title bar

### ISSUE THREAD

**Issue by R3n001** [mwittrien/BetterDiscordAddons#839]
**Describe the bug**
In version 1.6.9 of OldTitleBar, the option to display the native title bar is gone.

**To Reproduce**
Use version 1.6.9

**Expected behavior**
The option to use the native title bar should be listed

**Screenshots**
I've already rolled back to 1.6.7, and I really don't want to break my config.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Its not longer possible and hence removed
