### ISSUE TITLE
[SUGGESTION] - Regex search

### ISSUE THREAD

**Issue by antonii1357** [mwittrien/BetterDiscordAddons#840]
Hi!
So I love the "Better Search" plugin and I was wondering if it was possible to implement a regular expressions-like syntax mode to search for a certain pattern more effectively than with a regular plaintext search. I don't know if it's possible but it would be an amazing feature for searching through specific messages.

Thanks, I love your plugins :D

**Comment by mwittrien** [comment]
Sadly there is no way to change how the actual search works since its handled server sided
