### ISSUE TITLE
[BUG] - Badges Everywhere

### ISSUE THREAD

**Issue by SlightlyPeckish** [mwittrien/BetterDiscordAddons#841]
**Describe the bug**
Badges aren't appearing in chat after latest update even though it's enabled

**To Reproduce**
Latest update of Badges Everywhere v1.7.3 

**Expected behavior**
With the update I expect it to not display
Before the update it displayed

**Screenshots**
Works in sidebar members list:
![image](https://user-images.githubusercontent.com/21175434/120085123-63324680-c0cd-11eb-8a30-5eef58cccaa5.png)
Not in chat:
![image](https://user-images.githubusercontent.com/21175434/120085135-7218f900-c0cd-11eb-8918-1265efef866e.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Was working fine before the latest update v1.7.3

**Comment by mwittrien** [comment]
Ctrl r

**Comment by SlightlyPeckish** [comment]
That didn't work and I've tried restarting Discord too
