### ISSUE TITLE
[IMPROVEMENT] - Allowing to keep both messages after translation

### ISSUE THREAD

**Issue by tsbreuer** [mwittrien/BetterDiscordAddons#842]
**Describe the solution you'd like**
Add an option so that when you click on a message and translate it, it adds the translation under the original message and keeps both instead of replacing the original

**Describe alternatives you've considered**
I don't think theres really any alternatives

**Additional context**
As someone learning how to read/write japanese hiragana/katakana, it would be nice to be able to see both side by side without having to hover the message itself to see the original

**Comment by mwittrien** [comment]
Added
