### ISSUE TITLE
[IMPROVEMENT] - EditUsers

### ISSUE THREAD

**Issue by evka745** [mwittrien/BetterDiscordAddons#844]
**Describe the solution you'd like**
Stops gif profile pictures from playing when mouse is not over on the profile picture/clicked on

This might already be a thing and I'm stupid, but I'm not sure

**Comment by mwittrien** [comment]
Yeah there is no good way to do that since i cant add a listener to it

**Comment by evka745** [comment]
alright thats fair thanks for replying
