### ISSUE TITLE
Auto translate incoming messages - GoogleTranslate Plugin

### ISSUE THREAD

**Issue by millysecurity** [mwittrien/BetterDiscordAddons#845]
**Describe the solution you'd like**
When I set the language for received messages, it'd be useful if it'd automatically translate all incoming messages in that specific server to the language I want. That way I don't have to click each message and can just read them.

**Describe alternatives you've considered**
N/A

**Additional context**
Being able to have received messages in specific servers be translated automatically into the language of your choice.

**Comment by mwittrien** [comment]
Not possible due to api Limits
