### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by tryingtofixdiscord** [mwittrien/BetterDiscordAddons#846]
Full user popouts 
when clicking on user profile pictures, the user's avatar will show a bigger avatar above the user information etc. 

Dusk to Dawn theme by Asteria 
Used to have this as a feature of the theme, however since the new update to discord it doesn't work. Image Utilities is good but doesn't provide the same experience. 

**Additional context**
https://i.imgur.com/YHamenJ.png Example of it how it was before the discord update
original code that allowed for the bigger avatars - https://asteria5675.github.io/addons/full_popout_avatars.css
Don't know how it could be fixed, very inexperienced with coding :(

**Comment by mwittrien** [comment]
I am not open for plugin/theme requests
