### ISSUE TITLE
[BUG] - RemoveBlockedMessages

### ISSUE THREAD

**Issue by ZinniaBelle** [mwittrien/BetterDiscordAddons#848]
**Describe the bug**
When a blocked user sends a message in a channel as the last message in that channel and you open that channel it will scroll to the top of the messages

**To Reproduce**
Open any channel where the last person to reply is blocked, channel has to be full of messages

**Expected behavior**
The channel should not move to the first loaded top message.

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
#783
