### ISSUE TITLE
Spotify Controls not working

### ISSUE THREAD

**Issue by CDNinjaWarrior** [mwittrien/BetterDiscordAddons#849]
The plugin "Spotify Controls" doesn't work. I have used this plugin in the past and it has worked. However, it seems to crash BD and whenever I turn it on again, it crashes BD. 
![image](https://user-images.githubusercontent.com/83045087/120726272-b3325400-c4a5-11eb-9aed-710691b856f6.png)

**Comment by mwittrien** [comment]
Remove the (1) in the filename
