### ISSUE TITLE
[BUG] - ServerFolders/Frosted Glass

### ISSUE THREAD

**Issue by DefiantBurger** [mwittrien/BetterDiscordAddons#851]
**Describe the bug**
The bug is that custom server icons don't show up when I open the folder. The default discord ones that just have the letters do, but ones with custom icons don't. I can hover over where the icons should be but only the names show up.

**To Reproduce**
This bug occurs whenever I open a server folder.

**Expected behavior**
I expect that the server icons show because they show in the collapsed folder, just not the opened one.

**Screenshots**
![image](https://user-images.githubusercontent.com/37152232/120807112-97ff2d00-c515-11eb-9d8e-9b799186e951.png)
![image](https://user-images.githubusercontent.com/37152232/120807134-9e8da480-c515-11eb-87bd-3219154e08f6.png)
![image](https://user-images.githubusercontent.com/37152232/120807159-a51c1c00-c515-11eb-94a3-2454d7ba39a4.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
This isn't additional context, just a comment. I love this plugin so much, tbh it looks so great I'm confused why discord hasn't added it yet.

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/120809822-c1867b80-c54a-11eb-9e17-473949fc3042.png)
looks fine for me, can you share your theme file so i can check

**Comment by DefiantBurger** [comment]
sure, btw it doesn't show even when I turn off the theme.
[theme_in_txt_format.txt](https://github.com/mwittrien/BetterDiscordAddons/files/6599658/theme_in_txt_format.txt)
i had to convert it to txt btw

**Comment by mwittrien** [comment]
if it happens even with your theme disabled then something else is causing it

disable all themes and remove your custom css
