### ISSUE TITLE
[IMPROVEMENT] - WriteUppercase - Capitalize I's, countries, etc.

### ISSUE THREAD

**Issue by pugshot** [mwittrien/BetterDiscordAddons#852]
If the intention is to help the user to automatically write in uppercase for the first letter of the sentence, may I suggest that it would also automatically capitalize I's, countries and possibly even names. Even further, words like "thats" could be automatically converted to "that's".

**Comment by mwittrien** [comment]
If you wanna change thats to that's use ChatAliases

There is no way for the plugin to know what a name or country is
