### ISSUE TITLE
[IMPROVEMENT] - SpotifyControls - Like Button

### ISSUE THREAD

**Issue by k-gaia** [mwittrien/BetterDiscordAddons#855]
I'd love the option to be able to like tracks that are currently playing from spotify via this interface.
I feel this is the only feature, that I can think of that's really missing at the moment.

I think an alternative here, would be to if implementing is to include it purely as an optional feature.
In the case it clutters up the already neat selection of buttons, being able to replace one with a like button.

Additionally, love the plugin - great stuff!

**Comment by mwittrien** [comment]
Not possible since discord Spotify integration only subscribes to their song management module
