### ISSUE TITLE
[BUG] - NOTIFICATIONSOUNDS (PLUGIN COMPATABILITY BUG)

### ISSUE THREAD

**Issue by ZinniaBelle** [mwittrien/BetterDiscordAddons#857]
**Describe the bug**
The sound will still play when getting a reply with the plugin "SuppressReplyMentions".

**To Reproduce**
Simply get a reply when using a "ping" sound.

**Expected behavior**
Sound should not play.

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by mwittrien** [comment]
Added Replies as a new sub type to the config menu, so you can change the sound or even mute it, that way you can tell NotificationSounds to not play sounds when getting mentioned by a reply
