### ISSUE TITLE
[IMPROVEMENT] - Notification sounds: Select specific audio device for notification

### ISSUE THREAD

**Issue by TuTAH1** [mwittrien/BetterDiscordAddons#858]
Notifications would play on device 2 while all other discord sounds will play on device 1.
If it's not possible to make directly, you can do this:
if the request to the notification sound made, before play notification, change the audio output to device 2, play notification sound, after [notification_sound.playtime] passed, change the audio output to device 2

**Comment by mwittrien** [comment]
You can't tell audios to play on specific output devices and changing it dynamically won't work
