### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/GoogleTranslateOption

### ISSUE THREAD

**Issue by jidbepp** [mwittrien/BetterDiscordAddons#859]
**Describe the solution you'd like**
make the recived message settings work
![why](https://user-images.githubusercontent.com/64148580/121407870-c2922100-c92d-11eb-804a-a6eee3e9eb2c.PNG)
**Describe alternatives you've considered**
just remove the option for it if it does not even work
![why](https://user-images.githubusercontent.com/64148580/121407870-c2922100-c92d-11eb-804a-a6eee3e9eb2c.PNG)

**Additional context**

**Comment by mwittrien** [comment]
Yes it works

Right click a message and press translate
