### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by jidbepp** [mwittrien/BetterDiscordAddons#862]
Describe the solution you'd like
make the recived message settings work
why
Describe alternatives you've considered
just remove the option for it if it does not even work
why

Additional context

**Comment by jidbepp** [comment]
i mean
the auto translate

**Comment by mwittrien** [comment]
It has no auro translate for incoming messages

Nowhere does it say it does
