### ISSUE TITLE
[IMPROVEMENT] - NotificationSounds - Make changing the Discodo Launch sound possible

### ISSUE THREAD

**Issue by Facu8104** [mwittrien/BetterDiscordAddons#863]
I think the title is pretty descriptive in this case. Basically, make it possible to change the Discodo sound that plays when you start Discord (if you unlocked the feature clicking 15 times the home button) so that I can use that nostalgic Skype startup sound
(☞ﾟヮﾟ)☞

**Comment by mwittrien** [comment]
It already does, but plugins are simply not loaded at the time discord plays the sound
