### ISSUE TITLE
[BUG] - Better Discord Plugin

### ISSUE THREAD

**Issue by kelvinwl** [mwittrien/BetterDiscordAddons#869]
**Describe the bug**
0BDFDB.plugin.js could not be compiled. I don't know what else to say.

**To Reproduce**
Just open the program.

**Expected behavior**
I guess it was supposed to open, update and run normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/12598286/121752418-76d6a780-cae6-11eb-9365-a9521713103f.png)

**Discord Build (stable, ptb or canary):**
Stable 87598 (2345772)
BetterDiscord 1.1.1
Host 1.0.9002
Windows 10 64-Bit (10.0.19043)

**Additional context**
None.

**Comment by mwittrien** [comment]
Redownload it
