### ISSUE TITLE
ReadAllNotificationsButton does not work.

### ISSUE THREAD

**Issue by Mef45** [mwittrien/BetterDiscordAddons#87]
When i click to "Read all" button nothing happened with my servers at all. Tried with and without "Include muted Servers" option.

- BD v0.2.82, JS v1.792 by Jiiks
- BBD v0.0.7 by Zerebos
- ReadAllNotificationsButton v1.3.5 by DevilBro
- Discord 0.0.5 for Linux

**Comment by mwittrien** [comment]
Try reloading

**Comment by Mef45** [comment]
Still nothing.
