### ISSUE TITLE
[BUG] - GoogleTranslate jumping

### ISSUE THREAD

**Issue by Huskydog9988** [mwittrien/BetterDiscordAddons#870]
**Describe the bug**
Jumping when a message is translated, and there are unread, or recently unread messages in a channel.

**To Reproduce**
When in a channel with unread messages, translate an unread message, client will jump up to "the top."

**Expected behavior**
The client doesn't jump all the way to the top.

**Discord Build (stable, ptb or canary):**
Ptb

**Comment by mwittrien** [comment]
Fixed by updating BDFDB
