### ISSUE TITLE
[BUG] - TopRolesEverywhere / Wrong Text Alignment in chat window

### ISSUE THREAD

**Issue by night2078** [mwittrien/BetterDiscordAddons#872]
**Describe the bug**
With the recent update of the plugin "TopRolesEverywhere" i am experiencing some sort of weird bug. The text of every RoleTag is aligned to the far right, leading to have the colored tag go all over the chat window.

Recent Update means: v3.0.6

Before this update, i had no issues using that plugin.

**To Reproduce**
The bug does always occur. Restarting discord or reinstalling the plugin did not help.

**Expected behavior**
The text of the tags should be aligned to the left, so the tag itself does not go all over the chat window.

**Screenshots**
![bug](https://user-images.githubusercontent.com/85808952/121789741-c09fba80-cbd8-11eb-83f6-d8b827bc2e46.PNG)

Unfortunately i don't have any images of it beeing correct. But i guess you can figure that the text should be on the left side.

**Discord Build (stable, ptb or canary):**
Stable 87693 (e152862
BetterDiscord 1.1.1

**Additional context**
-

**Comment by crazystich519** [comment]
is there a fix for this?

**Comment by night2078** [comment]
Well, it has just been closed without any comment by the dev. Not sure why, but i don't have any fix and this issue is still a thing for me.

**Comment by mwittrien** [comment]
Thats most  likely due to your theme 
Switch to the bot tag style in the plugin settings
