### ISSUE TITLE
[IMPROVEMENT] - OldTitleBar

### ISSUE THREAD

**Issue by RichardLaan** [mwittrien/BetterDiscordAddons#873]
It is my opinion the window drag area is too small. It took me a few minutes to find the drag area when I first used your plugin.  I ask for the entire title section to be an area that you can use to drag. See the image below for clarification on the area I am referring to.

It took me a few minutes to find the drag area when I first used your plugin. A possible alternative to extending the area is to make the area that is already there more visible. I think it could be possible to highlight the area when your mouse is over it, or change the mouse icon to the 'move' icon when over the area (if this is not possible due to plugin limitations, I am sorry for my ignorance!) 

The area that I request to make possible to drag the window is boxed in.
![temp](https://user-images.githubusercontent.com/85661330/121796936-e6ce5600-cbea-11eb-9d09-995f791c9a03.png)

The mouse icon I am referring to in the second paragraph.
![temp2](https://user-images.githubusercontent.com/85661330/121797034-94416980-cbeb-11eb-9b72-5641ca59d768.png)

**Comment by mwittrien** [comment]
that area is already the drag area. you simply need to hold down on an area that isnt covered by any other element

drag areas can't have a cursor icon
