### ISSUE TITLE
[BUG] - PLUGIN/NotificationSounds

### ISSUE THREAD

**Issue by FireFoxyLtu** [mwittrien/BetterDiscordAddons#874]
I cant change sound categories.

Every time i try to change categories .

I tried to create categories and i made a lot of them and they cannot be changed.

![notificationsounds](https://user-images.githubusercontent.com/85824441/121801254-173fdf80-cc3f-11eb-89f1-99e9a638c6ad.JPG)

Stable better discord.

I tried everything and nothing worked.

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/121885918-09f52480-cd15-11eb-8563-af3f2c25ec93.png)
Looks fine for me, make sure your BDFDB plugin is up to date
