### ISSUE TITLE
[IMPROVEMENT] - Plugin Repo

### ISSUE THREAD

**Issue by MalooMF9** [mwittrien/BetterDiscordAddons#875]
**Describe the solution you'd like**
Ability to visit plugin's source repository, or at least view source code, from the plugin repo menu, similar to the links available in BetterDiscord's own plugin menu after you install a plugin.

**Describe alternatives you've considered**
Potential alternative would be the ability to download a plugin without activating it. This would allow looking at the downloaded file's source and links in BD's plugin menu.

**Additional context**
Not being able to examine a plugin's source or read its documentation before installing it makes me leery, especially for some of the ones that don't just have local effects, or make additional API calls. While I can try to track down that information myself, part of the point of a plugin repo is providing everything you need to find and install plugins.

**Comment by mwittrien** [comment]
added, youll need to redownload it manually
didnt wanna increment the version number for such a specific change
