### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by RedstoneGyerek** [mwittrien/BetterDiscordAddons#876]
The selection buttons are sooo small and when I select something, it's just not selecting it.

Every time.

The selection buttons are sooo small and when I select something, it's just not selecting it.
The buttons sould be bigger and the selection sould do what I want.

https://drive.google.com/file/d/1sPK0XPaVOmB2p5Ai6-GDpGQDi-m0Dkaj/view?usp=sharing

Stable 87781 (b8af783)

Send help

**Comment by mwittrien** [comment]
#874
