### ISSUE TITLE
Remove the "lightcord" Window

### ISSUE THREAD

**Issue by TheMongoloid** [mwittrien/BetterDiscordAddons#878]
It's rather annoying choosing to use a specific discord client and the one thing that stops/makes it a pain to use is when people add a window telling you not to use it... It's personal preference on what people use. I understand you're trying to help people by spreading a word that it's risky (It's not) but can you please remove the lightcord window on ALL your plugins as it makes it annoying for people who just want to use your good plugins

**Comment by mwittrien** [comment]
Use BD if you want to use my plugins

Its a PERSONAL choice to make my plugins only work on BD :)
