### ISSUE TITLE
[Custom Colors/Stylization] - Char Counter

### ISSUE THREAD

**Issue by NeverEndingCycle** [mwittrien/BetterDiscordAddons#882]
It would be really nice to have one or two config settings for color, drop shadow, outline, etc. When using this plugin with your basic background theme, the gray is really hard to see on most custom images.

![image](https://user-images.githubusercontent.com/42754840/122324880-6b1c2400-cede-11eb-8996-1e7a14c99432.png)

**Comment by mwittrien** [comment]
Change it then woth custom css
