### ISSUE TITLE
[INCOMPATIBILITY] - PinDMs and AccountDetailsPlus 

### ISSUE THREAD

**Issue by AdamExample** [mwittrien/BetterDiscordAddons#884]
**Describe the incompatibility**
Having PinDMs enabled stops AccountDetailsPlus by Zerebos from working until it is manually disabled and enabled, this must be done every time discord is loaded

**To Reproduce**
Have PinDMs and AccountDetailsPlus enabled at the same time

**Expected behavior**
When AccountDetailsPlus works normally it should open the user popout of your own account when you click your profile picture to the left of your mute, deafen and settings icons.

**Screenshots**
clicking profile picture without PinDMs enabled &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; clicking profile picture with PinDMs enabled
![when it works](https://user-images.githubusercontent.com/28219016/122502087-3a2f1280-cff6-11eb-942c-5f1adcbf55fc.png)![when it does not work](https://user-images.githubusercontent.com/28219016/122502609-394ab080-cff7-11eb-9375-50d144fb6b55.png)
</details>

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Issue is at AccountDetailsPlus
Nothing i can do
