### ISSUE TITLE
[BUG] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by KingAbyx** [mwittrien/BetterDiscordAddons#886]
**Describe the bug**
Whenever I try to save an image with "Save imagine as..." option in the context menu. It gives me the error "Image could not be saved in [filepath]"

**To Reproduce**
See above

**Expected behavior**
Downloading the image in the filepath

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I'm on linux

**Comment by Thedoczek** [comment]
1. What plugin do you use?
2. Are you sure this is a plugin problem?

**Comment by KingAbyx** [comment]
I figured it out. It was a permissions problem on my hdd. Probably a good idea to add more specific error messages if possible
