### ISSUE TITLE
[BUG] - OldTitleBar "Windowed" button can't work.

### ISSUE THREAD

**Issue by fly9588** [mwittrien/BetterDiscordAddons#887]
**Describe the bug**
"Windowed" button can't work.

**To Reproduce**
See above.

**Expected behavior**
See above.

**Screenshots**
None.

**Discord Build (stable, ptb or canary):**
Stable 88181 (22a0e04)
BetterDiscord 1.1.1

**Additional context**
Windows 10 64-Bit (10.0.19042)

**Comment by mwittrien** [comment]
What plugin

**Comment by fly9588** [comment]
> What plugin

Sry , it's OldTitleBar.

**Comment by mwittrien** [comment]
Try disabling Window Transparency in the BD settings and fully relaunch discord

**Comment by fly9588** [comment]
Thanks for reply.
It seems okay now , I'll try another computer few days ,
but the windowed button always show on "Full Window" icon , is it normal ?

**Comment by mwittrien** [comment]
should be fixed now
