### ISSUE TITLE
OldTitleBar - Unmaximizing/Maximizing results in unexpected behavior

### ISSUE THREAD

**Issue by CollinScripter** [mwittrien/BetterDiscordAddons#89]
This seems to be a Linux specific issue, although I am unable to test on macOS. This issue seems to occur on Linux on at least two different desktop environments. Unmaximizing and maximizing results in unexpected behavior where the window is either not correctly maximized or unmaximized.

**Discord on KDE Plasma 5 on Manjaro:**
![peek 2018-07-12 23-53](https://user-images.githubusercontent.com/5771065/42679308-7abaefb6-864f-11e8-97e4-79be1862bfbf.gif)

**Discord Canary on GNOME 3 on Ubuntu 18.04:**
![peek 2018-07-13 03-39](https://user-images.githubusercontent.com/5771065/42679337-9322c560-864f-11e8-861e-d6446e9ca32d.gif)
Not shown due to the framerate of these gif images, there is slight graphical glitching when the window does try to resize. This issue can be resolved by removing lines 271-277 and replacing that section with [`require("electron").remote.getCurrentWindow().unmaximize();`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winunmaximize). In addition, removing lines 280-283. This fix has been tested on GNOME 3, KDE, and Windows 10.

As a side note, why did you initially do unmaximizing/maximizing this way? If there is an issue with other operating systems we could check to see if BetterDiscord is running on Linux and use unmaximize then.

**Comment by mwittrien** [comment]
Fixed in 1.3.6

No real reason why I simulated it, I simply did not see the unmaximize function  😅
