### ISSUE TITLE
[Improvement] - ServerColums: Choosing order

### ISSUE THREAD

**Issue by Thedoczek** [mwittrien/BetterDiscordAddons#890]
Just ability to select if servers should be ordered in way A or B
![test](https://user-images.githubusercontent.com/69758777/122818259-427a9c80-d2d9-11eb-94d6-badfe9ebb13c.png)
Useful if using phone often, where there is only one column always, and you got used to what is under what.

**Comment by mwittrien** [comment]
not possible
