### ISSUE TITLE
[BUG] - SpotifyControlls

### ISSUE THREAD

**Issue by KK-Designs** [mwittrien/BetterDiscordAddons#898]
**Describe the bug**
When I resume the song it goes the end of the song and doesn't do anything.

**To Reproduce**
Resume a paused some

**Expected behavior**
Should resume the song and everything should be normal.

**Screenshots**
I cant get one :(

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Only happens when you resume a song, pausing it is fine

**Comment by mwittrien** [comment]
Not happening to me

Take a video if you wanna show me the issue
