### ISSUE TITLE
OldTitleBar- DM names are not clickable

### ISSUE THREAD

**Issue by CollinScripter** [mwittrien/BetterDiscordAddons#90]
OS: Ubuntu 18.04, Manjaro, Windows 10
The name of users should be clickable, but isn't.
**Behavior shown in OldTitleBar:**
![broke](https://user-images.githubusercontent.com/5771065/42683037-35d58108-865a-11e8-9b89-4650b7a5153e.gif)
**Intended behavior shown in regular Discord:**
![working](https://user-images.githubusercontent.com/5771065/42683095-5c58aeea-865a-11e8-97bf-85ad644e8871.gif)
Group DMs do not seem to be afflicted by this issue

**Comment by mwittrien** [comment]
Fixed in 1.3.6
