### ISSUE TITLE
[BUG] - BadgesEverywhere - Colored badges option does not work.

### ISSUE THREAD

**Issue by 404UNFca** [mwittrien/BetterDiscordAddons#904]
**Describe the bug**
Since the recent update that changed the badges color to white, the "Use colored badges" option in the plugin settings does nothing when enabled.

**To Reproduce**
Switch on use colored badges, badges should be colored, but they instead remain white.

**Expected behavior**
They should go back to being colored.

**Screenshots**
![image](https://user-images.githubusercontent.com/5123258/123503300-26039a80-d620-11eb-8be1-92aab19ff9d4.png)
![image](https://user-images.githubusercontent.com/5123258/123503304-30259900-d620-11eb-843c-12f8e93d522c.png)

**Discord Build (stable, ptb or canary):**
![image](https://user-images.githubusercontent.com/5123258/123503312-3f0c4b80-d620-11eb-8053-6de01c1fbe3f.png)

**Additional context**
If the icons on the plugins' Settings panel are also supposed to re-color if the "Use colored badges" option is enabled; they don't, and they also remain white as you can see in the provided screenshot above.

**Comment by mwittrien** [comment]
The option was removed since discord no longer has an option to switch between colored/gray badges
They are colored to me no idea why they are gray for you, most likely something you changed in the accessbility settings or maybe a theme

**Comment by mwittrien** [comment]
I also see the winner badges in your settings

Which should no longer exist since discord removed them

**Comment by 404UNFca** [comment]
> 
> 
> The option was removed since discord no longer has an option to switch between colored/gray badges
> They are colored to me no idea why they are gray for you, most likely something you changed in the accessbility settings or maybe a theme

Not using a theme. Issue was I had to reboot Discord. Now everything is showing as it should.
