### ISSUE TITLE
[BUG] - DisplayServersAsChannels - Only a dot is visible while others are invisible 

### ISSUE THREAD

**Issue by GoldenMyst** [mwittrien/BetterDiscordAddons#905]
**Describe the bug**
It seems like it shows the servers as channels but the dot is only visible while the rest isnt.

**To Reproduce**
When enabling this plugin.

**Expected behavior**
Display servers as channels without some parts missing.

**Screenshots**
![Screenshot_33](https://user-images.githubusercontent.com/74118946/123516467-089af480-d651-11eb-9f0d-f4fadeb6fca8.png)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
Works fine on my end
Try Ctrl R and make sure its not a plugin or theme conflict
