### ISSUE TITLE
[BUG] - THEM/BASICBACKGROUND 1.0.5

### ISSUE THREAD

**Issue by nexioss** [mwittrien/BetterDiscordAddons#907]
**Describe the bug**
when having the backgroundblur set like 5px or more, and wented to upload a file the upload pop-up is blured too.

**To Reproduce**
drag any file to discord whithout droping it.

**Expected behavior**
having a clear view of the pop-up

**Screenshots**
![vlcsnap-2021-06-26-19h28m14s724](https://user-images.githubusercontent.com/86494178/123521308-2484b180-d6b6-11eb-8a6a-0bf4a8eb680b.png)

**Discord Build (stable, ptb or canary):**
Stable 88806 (ec5c1a3)

**Additional context**
the next pop-up when the file is droped to add a commantary is fine
![CaptureJAJE](https://user-images.githubusercontent.com/86494178/123521353-6f062e00-d6b6-11eb-94eb-0244b7ac79ff.PNG)

**Comment by mwittrien** [comment]
Fixed

**Comment by nexioss** [comment]
thanks for your fast respons
