### ISSUE TITLE
[BUG] - PLUGIN/STATUSEVERYWERE

### ISSUE THREAD

**Issue by nexioss** [mwittrien/BetterDiscordAddons#908]
**Describe the bug**
dont work at all.

**To Reproduce**
just installe the plugin and acivate it .

**Expected behavior**
adding the statue directly on the chat .

**Screenshots**
![Capturnge](https://user-images.githubusercontent.com/86494178/123521642-42ebac80-d6b8-11eb-8b5f-348554768a79.PNG)

**Discord Build (stable, ptb or canary):**
Stable 88806 (ec5c1a3)

**Additional context**
none

**Comment by mwittrien** [comment]
not my plugin

**Comment by nexioss** [comment]
yeah sorry i just see that
