### ISSUE TITLE
OldTitleBar - Login screen lacks movable area and window controls

### ISSUE THREAD

**Issue by CollinScripter** [mwittrien/BetterDiscordAddons#91]
OS: Windows 10 & Ubuntu 18.04
The screen for logging into a discord account lacks the draggable area and lacks window controls. Normally the New Title Bar is above the window and handles this.
**NewTitleBar:**
![windozebar](https://user-images.githubusercontent.com/5771065/42684609-8fffec0a-865e-11e8-9d82-4367278cd5f5.gif)
**OldTitleBar:**
![windozenobar](https://user-images.githubusercontent.com/5771065/42684614-96927240-865e-11e8-90bc-d76240ecdc86.gif)
Restarting discord after logging out does unload the plugins and shows the new bar, as plugins don't load until after login, but this can still be a slight issue on operating systems that don't have the new bar and let the OS handle the bar. (Linux)

**Comment by mwittrien** [comment]
Added in 1.3.6
