### ISSUE TITLE
[IMPROVEMENT] - SENDLARGERMESSAGES

### ISSUE THREAD

**Issue by thegamerx1** [mwittrien/BetterDiscordAddons#913]
it slices emojis pls fix thx
![28_06_2021_Discord_em4e8czetM](https://user-images.githubusercontent.com/34986564/123705210-f1355480-d866-11eb-9869-9a483a2b84ea.png)
![28_06_2021_Discord_z4iYwolGP2](https://user-images.githubusercontent.com/34986564/123705212-f2668180-d866-11eb-9069-0e2df90050a2.png)

**Comment by mwittrien** [comment]
The plugin isnt meant to spam
