### ISSUE TITLE
[IMPROVEMENT] - Improved TopRoleEverywhere + EditRoles interactions

### ISSUE THREAD

**Issue by SirBlockles** [mwittrien/BetterDiscordAddons#917]
I would like changes to role colors in EditRoles to apply to role tag selection in TopRoleEverywhere - for example, on a vanilla discord client, Role A is colored and Role B is not. If I were to use EditRoles to make Role A colorless and Role B colored, it would be nice if TopRoleEverywhere would respect this change and make the user's tag show Role B (as long as the "ignore colorless roles" option is active)

Also, the color picker in EditRoles can be a bit finicky. Sometimes "default color" changes the role back to its original color, while other times it sets it back to `null`, especially if you select a color swatch, save, and set it back to default.

**Comment by mwittrien** [comment]
> Also, the color picker in EditRoles can be a bit finicky. Sometimes "default color" changes the role back to its original color, while other times it sets it back to null, especially if you select a color swatch, save, and set it back to default.

thats actually a bug i fixed now which made it seem like you could set roles to colorless via "default color"

EditRoles does not allow you to change roles to colorless
