### ISSUE TITLE
[IMPROVEMENT] - BetterFriendsList

### ISSUE THREAD

**Issue by etzli** [mwittrien/BetterDiscordAddons#918]
**Hide the hidden category**
Basically I suppose people will be more satisfied and safe by actually being able to hide the hidden category bc its visible and uhh probably they feel like if a friend or a family member looked at the hidden friends they would be like "They were lying to me this whole time?" or something idk I'm not using my full imagination for this.

**Ideas I think would fit**
So I got 2 solutions actually, either right click on the button "Hidden" and a button pops up saying "Hide Category"
![image](https://user-images.githubusercontent.com/86798112/124169296-c0dff700-daae-11eb-8b7e-612deef0d015.png)
Or just put a button next to the "New Group DM"
![image](https://user-images.githubusercontent.com/86798112/124169401-e240e300-daae-11eb-8de9-417b0b999f10.png)

That's all I had to say, thanks for listening.

**Comment by mwittrien** [comment]
You can disable the hidden category in the plugin settings
