### ISSUE TITLE
OldTitleBar - Discord sets the wrong frame type

### ISSUE THREAD

**Issue by CollinScripter** [mwittrien/BetterDiscordAddons#92]
Affects: Any OS running on Linux

By default, Discord sets the frame type in the main electron to false due to using the default NewTitleBar, but in Linux based operating systems, the NewTitleBar isn't used, and the frame type is overwritten to true. This overwrite can be seen in mainScreen.js in Discord's files.
```
  if (process.platform === 'linux') {
    mainWindowOptions.icon = _path2.default.join(_path2.default.dirname(_electron.app.getPath('exe')), 'discord.png');
    mainWindowOptions.frame = true;
  }
```
**Current behavior: (GNOME 3 w/ Arc Darker Theme)**
![image](https://user-images.githubusercontent.com/5771065/42685963-7987ed7a-8662-11e8-853e-1b369ab9171f.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/5771065/42685907-5292aa70-8662-11e8-9bf0-24043ece6062.png)

I'm currently temporary fixing this by commenting out the line where it sets the frame to true in mainScreen.js, but this file is overwritten every time discord updates, which as a Discord Canary user, can be a pain to fix every time. The frame type cannot be changed mid-run, due to electron not implementing it, an issue on electron concluded that it was too much work to implement. The easiest way I can see to fix this is to check if the user is running on a Linux based OS, then comment out the line and restart Discord, although there may be better ways as I'm not familiar with BetterDiscord/Discord's inner workings.

**Comment by CollinScripter** [comment]
There exists a [TransparencyPatcher](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/TransparencyPatcher/TransparencyPatcher.plugin.js) which could help as an example on how to patch mainScreen.js.

**Comment by mwittrien** [comment]
I'll add an option to enable the paching of the mainScreen.js when i got some more free time in 1.3.7.

**Comment by CMTFrostyy** [comment]
Server folder doesnt work. I create a folder but there is nothing inside

**Comment by CollinScripter** [comment]
@CMTFrostyy That's unrelated to this issue, create a new one or ask for help on their Discord server

**Comment by mwittrien** [comment]
Added to 1.3.8
