### ISSUE TITLE
[IMPROVEMENT] Add verified badges and partner badges on EditServers 

### ISSUE THREAD

**Issue by Skriptic** [mwittrien/BetterDiscordAddons#920]
**Describe the solution you'd like**
Hey would be great if you guys added the option to add verified badges to a server and partner badges to servers on edit servers, for example you could add verified badges on front end and remove badges and partner badges I think that would be an amazing feature and that would just be an amazing feature to add (front end obviously) for people who just wanna mess around I think that would be a cool feature to add!

**Describe alternatives you've considered**
Maybe a entire new plugin for that, but why do that? When it can be implemented on EditServers!

**Additional context**
Not really it's pretty self-explanatory.

**Comment by mwittrien** [comment]
No

My plugins arent there to fake verified tags

**Comment by Skriptic** [comment]
What

**Comment by Skriptic** [comment]
I never said they where going to fake that? You guys litterly have the feature to edit server names etc. You guys might aswell add the option front end to remove them or add them?? You guys can edit Server banners and profile pictures....?

**Comment by Skriptic** [comment]
> No
> 
> My plugins arent there to fake verified tags

Your a very rude & weird individual you haven't even read what I said. Good luck with the future.
