### ISSUE TITLE
[IMPROVEMENT] - Remove Lightcord Nagging

### ISSUE THREAD

**Issue by onkoe** [mwittrien/BetterDiscordAddons#922]
**Describe the solution you'd like**
I would prefer the Lightcord nagging be removed from the codebase. If your plugins don't work, and people decide to bother you about it, kindly tell them that you don't support Lightcord installations. 

**Describe alternatives you've considered**
Anyone can remove the nagging by reverting to versions prior to [commit e481f64](https://github.com/mwittrien/BetterDiscordAddons/commit/e481f645747e32634ef919f26eb661dcdda3c274) or simply removing the code highlighted in the specific sections of each plugin within the commit. Since it seems like the maintainer doesn't view Lightcord kindly, this is the most likely option in my view. 

**Additional context**
![image](https://user-images.githubusercontent.com/66580279/124342218-01f80a00-db88-11eb-9997-7004ebaa0ac9.png)
...it's a bit much

**Comment by mwittrien** [comment]
#878
