### ISSUE TITLE
[BUG] - NotificationSounds

### ISSUE THREAD

**Issue by Boii1** [mwittrien/BetterDiscordAddons#923]
**Describe the bug**
Sound Configuration completely empty.

**To Reproduce**
Open NotificationSounds' Settings in Better Discord's plugin list.

**Expected behavior**
A full list of sounds/audio and their corresponding events tied to them appear w/ customization/etc. (obv)

**Screenshots**
Menu Open: [Imgur](https://i.imgur.com/VwxGMra.png)
Menu Closed: [Imgur](https://i.imgur.com/NwE93aW.png)

**Discord Build (stable, ptb or canary):**
Stable 89294 (f4e00f9)
BetterDiscord 1.1.1

**Additional context**
Updated earlier and noticed this issue. Furthermore notification pings don't work anymore since it updated.

**Comment by Boii1** [comment]
This error as well when it comes to notification pings: [NotificationSounds] (v3.6.2) Fatal Error: "before" callback of VM518:173 dirtyDispatch in e TypeError: Cannot read property 'focus' of undefined.

**Comment by mwittrien** [comment]
Ctrl R
