### ISSUE TITLE
[BUG] - PinDMs - BD crash from screenshare

### ISSUE THREAD

**Issue by GioBrauer** [mwittrien/BetterDiscordAddons#926]
**Describe the bug**
Discord/BD will crash if someone you're in a call with screenshares or alt-tabs off their screen. This happens from just having PinDMs installed, so if I remove it from my plugins folder, the crash stops happening.

**To Reproduce**
Install PinDMs, get in a voice call with someone, and have them screenshare.

**Expected behavior**
In this case I just didn't expect discord to crash from someone I'm in a call with screensharing.

**Screenshots**
I don't have screenshots but when the action mentioned is done, discord closes/restarts and I get an error message saying BetterDiscord crashed.

**Discord Build (stable, ptb or canary):**
I'm using Stable 89550 (3c2108a)

**Comment by mwittrien** [comment]
No thats a BD issue
