### ISSUE TITLE
[IMPROVEMENT] Mute all channels at once 

### ISSUE THREAD

**Issue by Adelscott** [mwittrien/BetterDiscordAddons#928]
I don't know if I should create this as it would be a new plugin. But here I go.
When I join a new server with sometimes hundreds of channels, I want to mute each one but one or two.

That's a feature asked on Discord official [community](https://support.discord.com/hc/en-us/community/posts/360048489252-Mute-all-channels-but-one) but as always they never listen.

**Comment by mwittrien** [comment]
I am not open for plugin requests
