### ISSUE TITLE
[BUG] I AM RECIEVING NOTIFICATIONS FROM PEOPLE THAT ARE NOT IN MY FRIENDLIST

### ISSUE THREAD

**Issue by owersite** [mwittrien/BetterDiscordAddons#929]
Hello! My name is Aleksandar and i am starting to receive notifications from people i USED to have in friend-list but don't have anymore.

Example:
![n](https://user-images.githubusercontent.com/60113773/124755664-f01dba80-df2b-11eb-8c70-7d222c1a6b20.png)
![unknown](https://user-images.githubusercontent.com/60113773/124755666-f0b65100-df2b-11eb-87f5-d7351fad7cd4.png)

Fix that asap.

**Comment by mwittrien** [comment]
Mind your tone boy

"Fix asap" Fix your tone when talking zo strangers

And there is nothing to fix you are just blind
Use the Strangers List
