### ISSUE TITLE
Plugin and Theme Repo: Nothing is actually downloaded

### ISSUE THREAD

**Issue by TiZ-EX1** [mwittrien/BetterDiscordAddons#93]
Hi, I'm using the Flatpak version of Discord on Linux, and BandagedBD. I have the Plugin and Theme Repo plugins installed, but when I download plugins and themes, nothing appears in my plugin or theme folders. I thought maybe they were stored somewhere else, but when I restarted discord, there was no evidence that I had ever downloaded them. Opening up the console didn't show any errors.

**Comment by TiZ-EX1** [comment]
I just noticed that Restart-No-More doesn't work for me either. Are a bunch of file-related functions just broken on Linux or something?

**Comment by CollinScripter** [comment]
Also on Linux, this seems to be a Flatpak only issue, as both PluginRepo and Restart-No-More worked fine for me.

**Comment by TiZ-EX1** [comment]
That makes more sense. I noticed that Restart-No-More tries to create a watch on subdirs of `$HOME/.config/discord`, but that directory doesn't exist. Creating it doesn't change this because it's in a sandbox. There is `$HOME/.var/app/com.discordapp.Discord/config/discord`, but I'm not sure how that appears inside of the sandbox. Discord itself and BetterDiscord--installed through betterdiscordctl--know to look there.
