### ISSUE TITLE
[IMPROVEMENT] - Server-wide ChannelEdit colors?

### ISSUE THREAD

**Issue by TheChilliPL** [mwittrien/BetterDiscordAddons#932]
**Describe the solution you'd like**
I think it'd be an amazing feature to let server administrators set default channel colors for anyone using this plugin. Of course, plugin users could disable that function if they don't like it, but I think it would let the admins personalize the server even further. Vanilla Discord users wouldn't see that but everyone with this plugin would and the colored channel list could seem a lot clearer.  
The biggest problem with that is the fact we'd need a way to store and download the server-wide configuration.

**Describe alternatives you've considered**
Custom API would need a server and connecting to it for every server someone uses may not seem great, but without it, we'd need a way to store color information about channels in e.g. channel topics. Placing colors there would allow us to not have a server nor a custom API, but the colors would be visible as plain text for everyone else.

**Additional context**
<details>
<summary>Example look of a fully colored channel list</summary>

![image](https://user-images.githubusercontent.com/18823939/125113096-7a128280-e0e8-11eb-8b33-08912be11aab.png)

</details>

**Comment by mwittrien** [comment]
Plugins are client sided and i will keep it like that

I am not gonna invest in a server
