### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by OsoaGitHub** [mwittrien/BetterDiscordAddons#936]
**Describe the solution you'd like**
An option to translate statuses

**Describe alternatives you've considered**
Copy and pasting statuses into Google Translate

**Comment by mwittrien** [comment]
statuse/about mes dont have a context menu

you can copy the status/about me into your message input, select the part you wanna translate with your mouse and right click it to search for translation

**Comment by mwittrien** [comment]
![image](https://user-images.githubusercontent.com/23700969/125439929-93052e87-fc0d-4a7b-9648-e9fbd671c6d4.png)
