### ISSUE TITLE
[BUG] - Translator Bug

### ISSUE THREAD

**Issue by CrackHub** [mwittrien/BetterDiscordAddons#938]
**Describe the bug**
Translator highlight wrong message after translate.

**To Reproduce**
Look gif.

**Expected behavior**
Highlight translated message.

**Screenshots**
![Animation1](https://user-images.githubusercontent.com/54614906/125305301-ebe00b80-e336-11eb-944b-cae32c850eb2.gif)

**Discord Build (stable, ptb or canary):**
Stable 89709 (8d00f68)
BetterDiscord 1.2.0
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

**Comment by mwittrien** [comment]
try redownloading BDFDB plugin, doesnt happen to me, it should mark the chat as read before rerendering the messages to avoid that issue
