### ISSUE TITLE
[BUG] - imageUtilities

### ISSUE THREAD

**Issue by lolpowerluke** [mwittrien/BetterDiscordAddons#940]
**Describe the bug**
imageUtilities not working with biggerStreamPreviews

**To Reproduce**
1: enable biggerStreamPreview and imageUtilities
2: find someone that is streaming on discord
3: open the streamPreview

**expected**
1: image not fullscreen
2: unable to use zoomFunction

**Comment by mwittrien** [comment]
Update BDFDB Plugin
