### ISSUE TITLE
Read_all button disappears

### ISSUE THREAD

**Issue by Infelicitas12021** [mwittrien/BetterDiscordAddons#941]
9 times out of 10 the read all button doesn't load in. 
![Screenshot from 2021-07-12 10-17-14](https://user-images.githubusercontent.com/79287056/125313021-72c2c300-e2fa-11eb-8626-17f1300052b7.png)

**Comment by mwittrien** [comment]
reloaded like 20 times and it always appeared, might be an issue with your theme
