### ISSUE TITLE
[BUG] Plugin / Theme Repo crashing on Canary

### ISSUE THREAD

**Issue by RobotHanzo** [mwittrien/BetterDiscordAddons#942]
**Describe the bug**
Having plugin or theme repo installed causes Discord Canary to crash right after launch

**To Reproduce**
Install either PluginRepo or ThemeRepo on Discord Canary and launch it

**Expected behavior**
Starts up normally

**Discord Build (stable, ptb or canary):**
Canary 89748 (a7662ec)
BetterDiscord 1.2.0
Host 1.0.37 Windows 10 64-Bit (10.0.19043)

**Comment by Wolfhound905** [comment]
I am running into the same issue.
Here is my log file: [debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/6803293/debug.log)


Discord Build:
Canary 89757 (80b09f6)
BetterDiscord 1.2.0
Host 1.0.37 Windows 10 64-Bit (10.0.22000)

**Comment by mwittrien** [comment]
fixed by redownloading BDFDB
