### ISSUE TITLE
[BUG] - BDFDB causes crash on Canary

### ISSUE THREAD

**Issue by RazerMoon** [mwittrien/BetterDiscordAddons#943]
**Describe the bug**
Discord Canary crashes if BDFDB library is present.

**To Reproduce**
Install latest Canary version and try to start Discord with BDFDB in the plugin folder.

**Expected behavior**
No crashing.

**Screenshots**
None.

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**
[debug.log](https://github.com/mwittrien/BetterDiscordAddons/files/6802910/debug.log)

**Comment by Wolfhound905** [comment]
Are you sure you are on the newest version of `0BDFDB.plugin.js`? You have to install manually. 
Also there seems to be an issue with the `PluginRepo.plugin.js` so I would remove it from the plugin folder if you have it.

**Comment by RazerMoon** [comment]
My bad, turns out my discord only crashes if I have BDFDB _and_ BadgesEverywhere or GoogleTranslateOption.

**Comment by RazerMoon** [comment]
Alright, issue fixed. Turns out I had to replace BadgesEverywhere and GoogleTranslateOption with ShowBadgesInChat and Translator respectively, which are the new names apparently. Still, would've appreciated a notice somewhere to change to the new ones.

**Comment by mwittrien** [comment]
You should have gotten an update prompt like always

**Comment by RazerMoon** [comment]
> You should have gotten an update prompt like always

Well, can't really get an update prompt if Discord crashes before the notice can appear ¯\_(ツ)_/¯.
