### ISSUE TITLE
[BUG] - EmojiReplace - In some sections, replacing emojis don't work

### ISSUE THREAD

**Issue by GoldenMyst** [mwittrien/BetterDiscordAddons#944]
**Describe the bug**
I noticed EmojiReplace only seem to work in chat. It doesn't replace emojis in statues, dm list, servers, usernames, channels, etc. Is this a bug?

**To Reproduce**
N/A

**Expected behavior**
I was expecting for this theme to replace every emoji in every section of discord, but it didn't.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
Usernames/servernames etc cant contain emojis

Those are ascii symbols

**Comment by GoldenMyst** [comment]
how about server channels & nicknames?

**Comment by mwittrien** [comment]
Same story
