### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by PaskaPinishkes** [mwittrien/BetterDiscordAddons#945]
**Describe the bug**
ImageUtilities is not working on latest Discord Canary (with latest BetterDiscord version). None of the features of the plugin are working even though the plugin itself is enabled, and instead, the vanilla image viewer and image context menu appear. No crashes occur.

**To Reproduce**
Install and try using ImageUtilities in Discord Canary with the latest version of BetterDiscord installed.

**Expected behavior**
ImageUtilities should work as normal.

**Discord Build (stable, ptb or canary):**
Discord Canary

**Additional context**
Yesterday, the plugin was working fine on Discord Canary, so the problem started with an update released today or last night.

**Comment by mwittrien** [comment]
Update BDFDB Plugin
