### ISSUE TITLE
[BUG] - 0BDFDB

### ISSUE THREAD

**Issue by psychedelic-fox** [mwittrien/BetterDiscordAddons#946]
**Describe the bug**
0BDFDB does not start, nor do the addons that rely on it.

**To Reproduce**
Start Powercord (Discord Canary) with 0BDFDB (w/ bdCompat).

**Expected behavior**
0BDFDB starts along with the plugins that rely on it.

**Screenshots**
[Screenshot of settings page](https://postimg.cc/D8pkRZfx/e91686cc)

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**
I am using Powercord/Canary and running 0BDFDB using a plugin called bdCompat. This setup worked fine prior to the latest Canary build.

**Comment by mwittrien** [comment]
My plugins are made for BD

I dont actively support PowerCord so i dont keep track whether it works on it or not

Try redownloading the library
