### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by MrMcyeet** [mwittrien/BetterDiscordAddons#947]
**Describe the solution you'd like**
Add an option to try to auto-translate incoming messages.
Since you implimented the per/channel settings

**Describe alternatives you've considered**
Not really any alternatives that I can think of other than just not adding the feature?
I dunno, It'd be cool to have since when handling support tickets for non-native english speakers, you can reliably expect all messages for a given channel to be in a different language

**Comment by mwittrien** [comment]
Not possible due to api limits
