### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by abdelrahman-aboelnour** [mwittrien/BetterDiscordAddons#948]
**Describe the bug**
I am no longer able to view channel details overview 

**To Reproduce**
no option to view channel details overview in right click any longer

**Expected behavior**
Channel details overview in the screenshots on the betterdiscord page

**Screenshots**

**Discord Build (stable, ptb or canary):**
stable

**Additional context**

**Comment by mwittrien** [comment]
Try ctrl r

**Comment by abdelrahman-aboelnour** [comment]
> Try ctrl r

That actually worked ! But why is that ? Exiting discord completly and starting it again never worked but this does

**Comment by mwittrien** [comment]
No clue honestly, sometimes plugins act up :s
