### ISSUE TITLE
[IMPROVEMENT] - Translator

### ISSUE THREAD

**Issue by lolpowerluke** [mwittrien/BetterDiscordAddons#949]
**Describe the solution you'd like**
translate uploads
![image](https://user-images.githubusercontent.com/47672899/125789053-1cb27206-c8da-469a-aab7-1cc072958da5.png)

**Comment by bscabl** [comment]
2 requests.. can you have it tell you what language its detecting.. and how difficult would it be to add an auto translate on receive.. like.. if you're in a room and the whole convo is incoming in something other than your native language clicking every line is cumbersome. keep up the great work!

**Comment by zhai1987** [comment]
![image](https://user-images.githubusercontent.com/72744153/126900300-aeacdd69-ff2e-453c-a79f-2d3a447cc53a.png)
![image](https://user-images.githubusercontent.com/72744153/126900312-53867afb-4710-471f-b5ee-1615c3266c6b.png)
