### ISSUE TITLE
PersonalPins: Don't see my notes

### ISSUE THREAD

**Issue by Purple0Rain** [mwittrien/BetterDiscordAddons#95]
I don't see my notes anywhere anymore, which really bothers me. I thought I had to maybe find an updated version of this plugin? But even after reinstalling it, I still don't see it.

**Comment by Drflash55** [comment]
Can confirm newest Discord update breaks PersonalPins as of Version V1.5.7.

![image](https://user-images.githubusercontent.com/13694448/42942014-9adf7e2e-8b2c-11e8-8b87-ca4d7c2038f5.png)

Will not appear next to the Member List and Search Bar.

**Comment by JerryCMancuso** [comment]
+1 Discord just updated yesterday, and I noticed today that PersonalPins is no longer accessible. I haven't used PersonalPins in a little while, so it may be coincidence that I'm just now not seeing it.
