### ISSUE TITLE
[BUG] - Huge amount of errors in BDFDB

### ISSUE THREAD

**Issue by BluTree** [mwittrien/BetterDiscordAddons#950]
**Describe the bug**
There are many errors coming from the lib, and plugins using this lib makes discord crashes

**To Reproduce**
Launch discord with only BDFDB loaded and look at console

**Screenshots**
![image](https://user-images.githubusercontent.com/11920536/125839510-b123a80b-be79-4d8f-aed1-84e27cc5e60c.png)

**Discord Build (stable, ptb or canary):**
Stable 90136 (3507a4c)

**Comment by vperpl** [comment]
ye plugin suddenly started to kill better dc.

**Comment by mwittrien** [comment]
Fixed on 1.7.7

**Comment by Nagol12344** [comment]
thanks

**Comment by tmbottegal** [comment]
Thank you so much for fixing this so quickly!

**Comment by wyslijp16** [comment]
> Fixed on 1.7.7

I have the same on 1.7.7.

**Comment by mwittrien** [comment]
Make sure you are really using 1.7.7 and reloaded discord at least once
