### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Vortecked** [mwittrien/BetterDiscordAddons#951]
I am using discord PTB, and i have everything installed properly and i have the plugin installed and enabled in the plugins menu, but it does not show hidden channels. I have used this plugin in the past and it worked fine, but now it does not work for me. When I close+reopen discord or do control+r, it says that the plugin was enabled or loaded or whatever, but it does not do anything

**Comment by Vortecked** [comment]
update: it works on discord canary, but for specific reasons i would prefer to use discord ptb,

**Comment by mwittrien** [comment]
Make sure your BDFBD is on 1.7.7
