### ISSUE TITLE
[BUG] - ImageUtilities crashes BD

### ISSUE THREAD

**Issue by 573rn-1i** [mwittrien/BetterDiscordAddons#952]
**Describe the bug**
It crashes the discord when import

**To Reproduce**
When import or when boot up the discord if you had it imported

**Expected behavior**
Not crashes the BD

**Discord Build (stable, ptb or canary):**
Stable

**Comment by 573rn-1i** [comment]
Also still find a lot of Errors in the updated bdfdb

**Comment by mwittrien** [comment]
Update BDFDB to 1.7.7
