### ISSUE TITLE
[BUG] - BDFDB Crashing Better discord

### ISSUE THREAD

**Issue by watisdatikalikffffali** [mwittrien/BetterDiscordAddons#953]
**Describe the bug**
The bug Crashes Better discord.

**To Reproduce**
When ever the plugin is installed and running.

**Expected behavior**
Yesterday i was installed a bunch of your plugins and it needed BDFDB so i installed it today i booted up my pc to find that betterdiscord has crashed cause of an issued.

**Screenshots**
![image](https://user-images.githubusercontent.com/65788718/125853919-bf52f5d0-7229-49a3-8667-b1c2549c3a7c.png)
![image](https://user-images.githubusercontent.com/65788718/125853937-db486227-2c8f-4bdf-8cee-46a1174d0c96.png)

.

**Discord Build (stable, ptb or canary):**
I am Using stable.

**Additional context**
I belive the reason is cause it keeps dumping its raw css to the plugins folder.

**Comment by mwittrien** [comment]
#950
