### ISSUE TITLE
BDFDB Causes BD to crash Discord

### ISSUE THREAD

**Issue by tmbottegal** [mwittrien/BetterDiscordAddons#954]
**Describe the bug**
BDFDB causes BD to crash Discord. Some sort of critical error.

**To Reproduce**
Update Discord to it's current version with BDFDB loaded.

**Expected behavior**
Not to crash?

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by mwittrien** [comment]
#950
