### ISSUE TITLE
[BUG] - BDFDB is crashing Discord

### ISSUE THREAD

**Issue by MrConorAE** [mwittrien/BetterDiscordAddons#955]
**Describe the bug**
If BDFDB is in the plugins folder and is loaded, Discord crashes.

**To Reproduce**
Using the latest version of the library installed, try and load BetterDiscord.

**Expected behavior**
BetterDiscord should load successfully.

**Discord Build (stable, ptb or canary):**
Stable (90136)
BetterDiscord 1.2.0

**Additional context**
Removing BDFDB fixes the issue, but then about half of my plugins can't load ("missing library plugin").

**Comment by mwittrien** [comment]
#950
