### ISSUE TITLE
BDFDB Crashing Better Discord When Update Is Needed

### ISSUE THREAD

**Issue by slysnake96** [mwittrien/BetterDiscordAddons#956]
**Describe the bug**
BDFDB was crashing Better Discord due to it needing an update and I could not "Click To Update" it.
I removed all files with the name BDFDB from the Plugins folder and force restarted Better Discord.
Better Discord then recognised that the plugin was missing and that it was needed so it automatically downloaded and updated it for me.

**To Reproduce**
Not sure how to reproduce considering that it is an update issue that can easily be solved by the end user with the correct information on how to fix the issue.

**Expected behaviour**
Problem: BDFDB will crash Better Discord upon needing an update.
Solution: Remove all files with the name BDFDB from the Plugins folder and force restart Better Discord.
Expected Behaviour: Better Discord then recognises that the plugin is missing and is needed so it will automatically download and update it.

**Screenshots**
No screenshots to show due to already fixing the issue.

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
I first believed that a different plugin was the culprit due to the fact that it was the last one to show up on the blue "Click To Update" button at the top of Better Discord when a plugin needs an update.
EDIT: Forgot to mention that I had already tried manually updating the plugin by downloading it and removing the old files and installing the new one directly from here:  https://betterdiscord.app/plugin/BDFDB

**Comment by TheChilliPL** [comment]
Downloading [BDFDB from here](https://betterdiscord.app/plugin/BDFDB) and replacing the one already in `%appdata%\BetterDiscord\plugins` seems to have worked for me

**Comment by TheChilliPL** [comment]
I also suspect it might not be possible to fix because it crashes before any update bar shows up as it should if there's an update available

**Comment by slysnake96** [comment]
> Downloading [BDFDB from here](https://betterdiscord.app/plugin/BDFDB) and replacing the one already in `%appdata%\BetterDiscord\plugins` seems to have worked for me

I forgot to mention that I have tried to manually update through that site directly already but it still creates the same issue.
The best fix, for me, was to remove the files altogether as stated in the bug report above.

**Comment by TheChilliPL** [comment]
That's weird: after replacing the `0BDFDB.plugin.js` file, it started to work perfectly well for me. Have you tried updating the other plugins requiring that library?

**Comment by slysnake96** [comment]
> That's weird: after replacing the `0BDFDB.plugin.js` file, it started to work perfectly well for me. Have you tried updating the other plugins requiring that library?

All other plugins are already up to date I double checked after fixing the issue.
Also the issue is already fixed and this is just a bug report.

**Comment by mwittrien** [comment]
#950
