### ISSUE TITLE
[Improvement] CreationDate - "years" for $agoAmount

### ISSUE THREAD

**Issue by superluig164** [mwittrien/BetterDiscordAddons#957]
Currently, in the date formatting area, there is no way to say "x years ago."  I wanted to set it up like this:

January 1, 2018 (3 years ago)

However, $agoAmount only shows months.  So instead it shows the number of months.

Can we have it also show years?

**Comment by mwittrien** [comment]
Discord has no years_ago formatter
Only for days/weeks/months

**Comment by superluig164** [comment]
I'm not an experienced web developer, but is it not possible to replicate the functionality in the plugin?

**Comment by mwittrien** [comment]
Writting a multi lingual years formatter without knowing 20+ languages? Not really
