### ISSUE TITLE
[BUG] - EditRoles crashes on context menu

### ISSUE THREAD

**Issue by Drflash55** [mwittrien/BetterDiscordAddons#959]
**Describe the bug**
Discord fatal crashes when you right-click on a user in a server that has a role that is edited for them.

**To Reproduce**
1. Have EditRoles turned on.
2. Go to a server.
3. Right-click on a user that has a role that is currently edited.

**Expected behavior**
Should just open up normally without locking up. BetterDiscord doesn't even shut off to tell you there was an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/13694448/125935220-3f8ccc3d-2f43-4d25-9447-23f5bc650432.png)

**Discord Build:**
Stable 90176 (333b0b5)
BetterDiscord 1.2.0

**Additional context**
It doesn't crash on anyone else whose role is not currently edited. But if a user has a role that is edited using "EditRoles", Discord experiences a fatal crash.

**Comment by lolpowerluke** [comment]
for me it just crashes whenever I open a menu like in the screenshot in any server, unrelated to edited roles
![image](https://user-images.githubusercontent.com/47672899/125944023-c2ef9dd0-12b1-4f86-8a95-70e4868e154f.png)

**Comment by ransagy** [comment]
Same here, After a fresh reinstall of BD. Any more details we could provide for this?

**Comment by mwittrien** [comment]
I am on Vacation

**Comment by ransagy** [comment]
That's very good, Enjoy. I wasn't writing to rush anyone.
Just asking if there's any further details we could collect from our machines - Others logs or whatever we didn't add.
