### ISSUE TITLE
[BUG] - Many plugins dont work.

### ISSUE THREAD

**Issue by ExDonald** [mwittrien/BetterDiscordAddons#960]
These next plugins doesnt work anymore (using in powercord with the bdCompat plugin and canary discord)

BDFDB
error code: 
![image](https://user-images.githubusercontent.com/63741142/125950213-7b8dc617-8993-4566-9e4e-6434b930b7fb.png)

CreationDate
error code: 
![image](https://user-images.githubusercontent.com/63741142/125950267-08cbd2ce-38c1-451d-95ef-1c650680f305.png)

Friends notification
error code:
![image](https://user-images.githubusercontent.com/63741142/125950334-ce17907f-77b0-40b1-8f16-d8645319877c.png)

ShowHiddenChannels
error code: 
![image](https://user-images.githubusercontent.com/63741142/125950387-5b210d99-f483-43e9-92a5-096f3a0bfca5.png)

Translator
error code: 
![image](https://user-images.githubusercontent.com/63741142/125950443-953621f0-444d-403b-b1c2-a636482c1fef.png)

 I Am sure there are more but those the one I have. i am also sure its because I use canary and they changed some stuff in the code but because of my lack in coding knowledge I have 0 idea.

**Comment by Spencer-0003** [comment]
Try using version 1.7.7 of the library, it works for me:
![image](https://user-images.githubusercontent.com/36741900/125960939-e2dcefcd-cbb6-4a89-91bb-c48452052f06.png)

**Comment by ExDonald** [comment]
OH YEA THANKS! for some reason it didnt update so I hade to manually download and update it myself. thanks a lot <3

**Comment by PiniponSelvagem** [comment]
Also, NotificationSounds does not work, got broken on last discord update :(
Settings panel opens with nothing in it, and the sound replacement is also broken (plays default discord sounds).
