### ISSUE TITLE
[BUG] - PersonalPins/DTM-16 - PersonalPins menu overlaps.

### ISSUE THREAD

**Issue by bakabakabakabakabaka** [mwittrien/BetterDiscordAddons#962]
**Describe the bug**
(Theme doesn't affect this) The personalPins menu overlaps images. At first I thought it was an issue with ImageUtilities or DTM-16 so I disabled them, but it didn't make any difference. I currently cannot test whether other plugins are to blame.

**To Reproduce**
Simply open the menu and click an image to view it.

**Expected behavior**
The personalPins menu should be under the image or the image should be above it.

**Screenshots**
![image](https://user-images.githubusercontent.com/65756037/126017131-1c69661a-2305-488b-9d10-a3e81f986138.png)

**Discord Build (stable, ptb or canary):**
PTB 90212

**Comment by mwittrien** [comment]
What image

**Comment by bakabakabakabakabaka** [comment]
Any image I open.

**Comment by lolpowerluke** [comment]
> What image

its hard to see, but the voicecall thing is the image

**Comment by mwittrien** [comment]
Theme Issue, not a plugin issue
