### ISSUE TITLE
[IMPROVEMENT] - FriendNotifications: offline ⇒ any status notification

### ISSUE THREAD

**Issue by Brawaru** [mwittrien/BetterDiscordAddons#963]
**Describe the solution you'd like**

Add an ability to have a simple ‘$user has came up _online_’ (of course not with this wording) notification when user status changes from offline to any status (online, idle, dnd).

**Describe alternatives you've considered**

- Watching all status changes (online, idle, dnd) — does not really signal that the friend has came up online, but rather that they’ve changed their status; plus this gets too spammy.

**Additional context**
×

**Comment by mwittrien** [comment]
Addee

**Comment by Brawaru** [comment]
Thanks much!
