### ISSUE TITLE
[BUG] - PINDMS || DOESNT FUNCTION?

### ISSUE THREAD

**Issue by sunsetteOS** [mwittrien/BetterDiscordAddons#964]
**Describe the bug**
Since the latest update of Discord, PinDMs doesn't appear to have any functionality.  It's fully up to date (v1.8.3), and claims to be loaded, but will not work.
All of my folders have disappeared, and right clicking does not show the PinDMs functions in the context menu.

**To Reproduce**
Install the latest version of Betterdiscord and PinDMs (v1.8.3) on the current version of Discord (Build Number 90176)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Make sure your BDFDB plugin is on 1.7.7

**Comment by sunsetteOS** [comment]
Oh, that fixed it.  Thank you very much, I apologize for the inconvenience!
