### ISSUE TITLE
[BUG] - NotificationSounds not working

### ISSUE THREAD

**Issue by PiniponSelvagem** [mwittrien/BetterDiscordAddons#965]
**Describe the bug**
NotificationSounds v3.6.2 dosent not load correctly, default discord sounds play instead the ones i previously had and settings opens an empty window.

**To Reproduce**
NotificationSounds v3.6.2 + BetterDiscord 1.2.0 + latest version of discord (since it automatically downloads it)

**Expected behavior**
Custom notification sounds instead of the default ones, and plugin settings window should show which sounds are enabled.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8899966/126036982-17b4395e-e023-4612-bfe0-15d7737a661a.PNG)
![Capture2](https://user-images.githubusercontent.com/8899966/126036983-091e6faa-8e55-4da1-bf2f-11e579509869.PNG)

**Discord Build (stable, ptb or canary):**
![Capture3](https://user-images.githubusercontent.com/8899966/126036986-5cc33435-90d2-4121-ad45-5bcf01fe8b30.PNG)

**Additional context**
Nothing to add, it says it loads, but nothing happens. Worked great till the last discord update, might have been that.

**Comment by mwittrien** [comment]
What is your BDFDB Version

**Comment by PiniponSelvagem** [comment]
BDFDB v1.3.5
will check if this is the latests from your repo after writing this
if its not the latest, i will update and will see if it fixes (and close if it works)

**Comment by mwittrien** [comment]
Newest is 1.7.7
