### ISSUE TITLE
ShowHiddenchannels doesnt work

### ISSUE THREAD

**Issue by Caryfuc** [mwittrien/BetterDiscordAddons#967]
Hello i have issue with ShowHiddenchannels it doesnt work. Plugin is in correct folder and he is turn on but i can´t open plugin settings is says: Could not open settigns for ShowHiddenChannesl.

Anyone can resolve this issue? 
Thanks

**Comment by mwittrien** [comment]
Make sure your BDFDB plugin is on 1.7.7

**Comment by Caryfuc** [comment]
Thank you so much bro <3
