### ISSUE TITLE
[BUG] - PLUGIN/BDFDB

### ISSUE THREAD

**Issue by wyslijp16** [mwittrien/BetterDiscordAddons#968]
Describe the Bug
The BDFDB library is recently causing a crash loop when starting up discord. It's trying to load the library, and is instandly crashing, and restarting. It works when starting discord via the terminal, for some weird reason.

To Reproduce
Install BDFDB

Expected Behavior
Just start up

Discord Version
Stable

**Comment by mwittrien** [comment]
#950
