### ISSUE TITLE
[Bug] - Basic Background - Boost announcement

### ISSUE THREAD

**Issue by Soulivan71** [mwittrien/BetterDiscordAddons#973]
Have an anormal shadow with discord boost announcement
> [Screen](http://prntscr.com/1d6u2yq)

**Comment by Soulivan71** [comment]
Its fixed for now or in few days ?

Le sam. 24 juil. 2021 à 21:34, Mirco Wittrien ***@***.***> a
écrit :

**Comment by mwittrien** [comment]
Now

**Comment by Soulivan71** [comment]
Ok thx
