### ISSUE TITLE
Plugin settings UI blank

### ISSUE THREAD

**Issue by intellectualpancake** [mwittrien/BetterDiscordAddons#974]
When I click on the NotificationSounds Settings, the UI shows up blank, the sounds also do not work, I have tried reinstalling the plugin, and clearing the config, but it doesn't change.
![image_2021-07-19_180720](https://user-images.githubusercontent.com/81973109/126233600-59b763d1-3c2d-493e-95c3-cdadd3dc215a.png)

**Comment by mwittrien** [comment]
Update BDFDB to 1.7.7 and reload discord
