### ISSUE TITLE
[IMPROVEMENT] - ShowBadgesInChat - Option to turn off Boosting Badges in DM List

### ISSUE THREAD

**Issue by AKASGaming** [mwittrien/BetterDiscordAddons#975]
**Describe the solution you'd like**
Boosting Badges in DM List seems a bit odd, so maybe an option to disable it?

**Describe alternatives you've considered**
- Clicking the badges could take you to the server
- or just adding an option to turn this part off

**Comment by mwittrien** [comment]
Boost badge is a general badge and not server specific

**Comment by AKASGaming** [comment]
That wasn't the whole point of the feature request, maybe you could still add the option to turn them off?

**Comment by mwittrien** [comment]
You can already turn off boost badges
