### ISSUE TITLE
[BUG] - Popups not working

### ISSUE THREAD

**Issue by fowlis** [mwittrien/BetterDiscordAddons#977]
**Describe the bug**
Cannot click the note button in the bar to open the menu to view notes
Using most recent PersonalPins and BDFDB plugin versions, (compared to the plugin pages on betterdiscord.app)
Hasn't seem to have had a secret update today, would have noticed a changelog
Have downloaded both plugins from the site to be sure, and reloaded to no prevail

**To Reproduce**
Click the note button in the bar

**Expected behavior**
Note menu should open

**Discord Build (stable, ptb or canary):**
Discord Stable

**Comment by JourneyOver** [comment]
Having same issue sadly :( really missing my pinned notes

**Comment by Andrzejone** [comment]
The same issue here. Reinstalled the plugin, didn't help

**Comment by Jnss98b** [comment]
Same issue here

**Comment by REVENGE977** [comment]
Same issue here

**Comment by JourneyOver** [comment]
From devilbro's discord:

```
[11:06 AM] DevilBro: @everyone  Discord seems to have changed something with popups, so any plugin using a popup will not work properly (PersonalPins Note Popup, SpotifyControls Volume Slider, any Plugin using a Color Picker, etc.)
[11:06 AM] DevilBro: Ill fix it on saturday once i am home
```

So we just have to wait till saturday, and then he will fix it.
