### ISSUE TITLE
[BUG] - ClickableMentions

### ISSUE THREAD

**Issue by DS-GitHub** [mwittrien/BetterDiscordAddons#978]
**Describe the bug**
Plugin Not Working

**To Reproduce**
Just use this plugin(clicking a Mention in Message Input)

**Expected behavior**
Plugin works(open a User Popout)

**Screenshots**
Just try it. Not works.

**Discord Build (stable, ptb or canary):**
Canary

**Additional context**
Hope it solved as soon as possible.

**Comment by mwittrien** [comment]
Redownload BDFDB plugin and reload discord

**Comment by lolpowerluke** [comment]
> Redownload BDFDB plugin and reload discord
still doesnt work

**Comment by mwittrien** [comment]
#977
