### ISSUE TITLE
[IMPROVEMENT] - URI support?

### ISSUE THREAD

**Issue by AMoonRabbit** [mwittrien/BetterDiscordAddons#979]
**Describe the solution you'd like**
I've tried modifying the theme to use a local image by using a uri but the theme loses the background instead. Is uri supported, or does the image have to be hosted on the internet?

**Describe alternatives you've considered**
Support local image files if not supported already

**Additional context**
Tried both formats below and neither work.
![image](https://user-images.githubusercontent.com/3766988/126606432-5db0cb07-4f89-46c0-8761-940a24b3f7ca.png)
![image](https://user-images.githubusercontent.com/3766988/126606453-b1a32261-bfd2-46c5-ac1d-ea32c1acc68f.png)

**Comment by mwittrien** [comment]
You cant use local images in css
