### ISSUE TITLE
Laggy Animation - Animation On/Off switch?

### ISSUE THREAD

**Issue by bkGamingYT** [mwittrien/BetterDiscordAddons#98]
Hi. **Is there a way I can disable the animation when opening and closing folders?** The reason is because it looks laggy and I would like it better if it just closed instantly. I'm pretty sure I could edit the code but I don't know where to find the animation thingy xD

**Thank you** 😃

**Comment by bkGamingYT** [comment]
Update: It appears that upon opening the folder, there is no animation, but when closing it there is. Could I just get an animation on both instead no animation at all? Sorry that I changed my mind hah it just looked laggy because one had no animation and the other did.

**Comment by mwittrien** [comment]
There is an animation on opening and closing, if it's laggy then your PC has trouble running the animation due to low specs

**Comment by mwittrien** [comment]
You could do it with CSS
