### ISSUE TITLE
[IMPROVEMENT] - OpenMoji

### ISSUE THREAD

**Issue by jef** [mwittrien/BetterDiscordAddons#981]
**Describe the solution you'd like**

It would be cool to add [OpenMoji](https://openmoji.org/).

**Comment by mwittrien** [comment]
I am pulling my emojis from https://emojipedia.org/openmoji/ with a self written grabber since doing it by hand would take months

and the openmoji emojis on emojipedia barely cover half of the emojis used by discord

**Comment by jef** [comment]
> the openmoji emojis on emojipedia barely cover half of the emojis used by discord

Out of curiosity, which emojis are missing? I thought they kept up-to-date with the latest Unicode.

**Comment by mwittrien** [comment]
EmojiPedis is missing everything from the last big two emoji updates for OpenMoji

**Comment by jef** [comment]
Looking at https://emojipedia.org/unicode-13.0/, I believe all of those include OpenMoji. Sorry if I'm wrong/being stubborn. Just also wanting to learn here ☺️

**Comment by mwittrien** [comment]
Ok i think they are trolling me,
When you first asked i checked for 13.1 and none of them showed up on the overview for OpenMoji lol
Maybe they just added them 🤔

Well ill add them then

**Comment by jef** [comment]
> Ok i think they are trolling me,

🤣 

Awesome! Thank you @mwittrien! I'd also be interested in seeing your script (if it's not already on GitHub). If that's something you'd rather keep private, I also understand.

Thanks for all the information and hearing me out ☺️

**Comment by mwittrien** [comment]
Added

**Comment by jef** [comment]
Nicely done! Looks great ☺️ Thank you!
