### ISSUE TITLE
[BUG] - CompleteTimestamps/CreationDate/JoinedAtDate formatting

### ISSUE THREAD

**Issue by xupaii** [mwittrien/BetterDiscordAddons#982]
**Describe the bug**
I'm unable to change the format of the date, it's currently in $mm/$dd/$yyyy format but I would like $dd/$mm/$yyyy. I'm unable to change this in any of the listed plugins.

**To Reproduce**
When I'm in the settings tab, there seems to be no way for me to format it by typing $dd/$mm/$yyyy. When I press on the "date" icon on the right, nothing happens.

**Expected behaviour**
When I last used the plugin, I think it brought up a second window to format the date. Unfortunately nothing pops up for any of the right-hand side icons at the moment, and nothing changes in the preview date either.

**Discord Build (stable, ptb or canary)**
Stable

**Additional context**
I have reinstalled all my plugins & the versions are up-to-date. I have tried reinstalling these 3 plugins and nothing changes still.

**Comment by mwittrien** [comment]
#977
