### ISSUE TITLE
[BUG] - PersonalPins PLUGIN won't open

### ISSUE THREAD

**Issue by P1ll0w** [mwittrien/BetterDiscordAddons#985]
Hey ! im really not good at coding, but i need some help for this plugin please !

**Describe the bug**
ok, so Note won't open when i click on. I mean, when I try to open the saved pins, the overlay won't appear
![image](https://user-images.githubusercontent.com/68938523/126860543-b0167c9b-7cbb-4f68-b063-ebd3aca86ffa.png)
this "logo"
(I can add pins)

**To Reproduce**
I don't really know now, just wanted to see my personal pins, and it failed because it won't open

**Expected behavior**
Normally it should open when I click on the little logo

**Screenshots**
![image](https://user-images.githubusercontent.com/68938523/126860343-8aa73fa1-2d24-4699-827f-223fddd2d10b.png)
on this screen, the "Noter le message" works nice like here down
![image](https://user-images.githubusercontent.com/68938523/126860360-72ca75f8-6b31-45ad-8e62-6cb1cd18334b.png)
But, i can't open it.

**Discord Build (stable, ptb or canary):**
i think it's the normal discord, like, i don't use canary or the bot version sooo... the usually discord version

thank you if you can help me :)

**Comment by mwittrien** [comment]
Good at coding? Bad at read i guess

#977
