### ISSUE TITLE
[BUG] - BDFDB takes too much time to load

### ISSUE THREAD

**Issue by barbaduk** [mwittrien/BetterDiscordAddons#986]
After latest Discord update and subsequent BetterDiscord and BDFDB updates initial load takes ages (well it's acctualy like 5 seconds, but compared to previous versions, which loaded instantly...)

I deleted all other plugins, re-downloaded BD and BDFDB, reset everything to default and it changed nothing.
Once i delete BDFDB everything loads instantly, but of course asks for BDFDB to be installed.

I thought it was cuz of emergency fix from vacation, but now it's another update and nothing changed.

![ScreenX_2021 07 24](https://user-images.githubusercontent.com/41954202/126879157-c1f7b46a-ce89-4496-9aec-2ccd56b85436.png)

**Comment by mwittrien** [comment]
You can thank discord for that :) nothing i can do about it
