### ISSUE TITLE
[IMPROVEMENT] - translator

### ISSUE THREAD

**Issue by bscabl** [mwittrien/BetterDiscordAddons#987]
2 requests.. can you have it tell you what language its detecting.. and how difficult would it be to add an auto translate on receive.. like.. if you're in a room and the whole convo is incoming in something other than your native language clicking every line is cumbersome. keep up the great work!

**Comment by mwittrien** [comment]
It already tells you the languages if you hover over the (translated) stamp

Auto translations arent possible due to api limits

**Comment by bscabl** [comment]
oh, it does! i didnt notice that, thanks for the quick reply!

I figured.. but thanks! :)
