### ISSUE TITLE
[BUG] - ImageUtilities doesn't work

### ISSUE THREAD

**Issue by Blush-112** [mwittrien/BetterDiscordAddons#989]
**Describe the bug**
Since a couple of weeks ago the ImageUtilities plugin is not working, at least for me, I updated BD at v1.2.0 and checked if the plugin was in the latest version (v4.4.4) but it still doesn't work, I asked in the discord server if it was just me or I needed to do something different, since the members of the server didn't know what to do I submitted this issue here

**Expected behavior**
I tried reloading Discord with Ctrl+R but didn't worked

**Screenshots**
![image](https://user-images.githubusercontent.com/88003499/127052609-c92e7a1e-a43c-40fb-a8b2-0ae1a7749f6c.png) 
![image](https://user-images.githubusercontent.com/88003499/127053123-a4f56138-430c-4105-9e10-243a5421a997.png)

**Discord Build (stable, ptb or canary):**
Stable

**Comment by mwittrien** [comment]
Make sure you are using BDFDB 1.7.9
