### ISSUE TITLE
[BUG] - TRANSLATOR

### ISSUE THREAD

**Issue by TOWUK** [mwittrien/BetterDiscordAddons#990]
**Describe the bug**
always limit and dont work token yandex (i cant change translate engine, where parameters change engine????????)
![image](https://user-images.githubusercontent.com/28830162/127058848-665325b9-70f2-466e-ac5c-2ba2532675ed.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/28830162/127058763-a71949d5-92f5-4f0b-a37c-5ef196c8e0aa.png)

**Discord Build (stable, ptb or canary):**
latest stable

**Comment by mwittrien** [comment]
Press ths tranSlateion icon in the bottom right
