### ISSUE TITLE
[IMPROVEMENT] - PLUGIN/THEMENAME

### ISSUE THREAD

**Issue by KBOC359** [mwittrien/BetterDiscordAddons#992]
**Describe the solution you'd like**
Ok so everytime i listen to a song on spotify and it appears in discord if you click the photo of the album it will say that your status is not being displayed (on the little button down right) and it's always turned off by default, i would for there to be at least a toggle or something so whenever i listen to a song it appears in my status automatically without me having to turn it manually

**Describe alternatives you've considered**
idk

**Additional context**
![Discord_VfhpzcBHOn](https://user-images.githubusercontent.com/31526906/127232788-aff9722f-d09a-4dee-929b-04ce5fbc2c83.png)

**Comment by mwittrien** [comment]
Thats the settings for the status activity of spotify, you can toggle it by clicking the icon or in discords settings
