### ISSUE TITLE
[IMPROVEMENT] - Make ShowHiddenChannels show threads

### ISSUE THREAD

**Issue by josephjthomas** [mwittrien/BetterDiscordAddons#994]
Discord rolled out threads lately for servers. It would be cool to include them in the ShowHiddenChannels plugin or make a new one ShowHiddenThreads.

**Comment by mwittrien** [comment]
Ill add support for threads for all my plugins in the next days

**Comment by mwittrien** [comment]
showing threads isnt possible as described in the change log
