### ISSUE TITLE
[IMPROVEMENT] - ShowHiddenChannels - Show as muted

### ISSUE THREAD

**Issue by itsmeboy0** [mwittrien/BetterDiscordAddons#996]
**Describe the solution you'd like**
An option to show hidden channels as muted to differentiate them easily (please include voice channels as well.

**Describe alternatives you've considered**
N/A

**Additional context**
Also the lock doesn't darken when I mute a hidden channel.

**Comment by mwittrien** [comment]
Control icons dont darken when a channwl is muted
The lock is already significant enough to make hidden channels obvious
If you need it to be more obvious use the class that is added to hidden channels by  the plugin and use css

**Comment by itsmeboy0** [comment]
> The lock is already significant enough to make hidden channels obvious

It's quite hard to tell if hidden channels are mixed with visible channels.

> If you need it to be more obvious use the class that is added to hidden channels by the plugin and use css

But sure, I will try this. Thanks.
